vectordotdev/vector

lib/vrl/stdlib/src/parse_int.rs
This PR fixes a problem that `parse_int("0")` does not work without setting the base explicitly. The problem comes from the base inference. When the value starts with `0`, the function assumes it to be octal and start parsing from index 1. However, for `"0"`, there is nothing from index 1 so it ends up with an error complaining about empty string:
```
---- parse_int::tests::parse_int_zero stdout ----
thread 'parse_int::tests::parse_int_zero' panicked at 'assertion failed: `(left == right)`
left: `Err("could not parse integer: cannot parse integer from empty string")`,
right: `Ok(Integer(0))`', lib/vrl/stdlib/src/parse_int.rs:119:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This PR fixes the problem by parsing values starts with `0` from the …
=> fix(vrl): fix parse_int("0")

src/lib.rs, src/sources/aws_s3/sqs.rs, src/sources/aws_sqs/config.rs
This also removes needless checks, since `available_parallelism` cannot be < 1 (as guaranteed by the type).
As a somewhat related changed, maybe a future PR should also change `client_concurrency` fields to also be `NonZeroUsize`, to avoid the `as` casts.
=> chore: avoid a possible panic

src/config/enterprise.rs
Closes [OP-505](https://datadoghq.atlassian.net/browse/OP-505)
This PR
- Removes the build info related fields on enterprise logs
- As documented in the ticket, we're ok with doing this prior to implementing https://datadoghq.atlassian.net/browse/OP-349 (which is the path forward to retrieving this information in the future).
=> chore(observability): Remove build info fields from enterprise logs

src/sources/datadog/agent/logs.rs, src/sources/datadog/agent/tests.rs
Testing and customer experience have revealed that the `status` field is an unnecessary footgun that trips up attempts to process log messages sourced from the Datadog agent.
Some context, friend: when the Datadog agent collects logs from a [Docker](https://cs.github.com/DataDog/datadog-agent/blob/433bc3f47d0bdc891e06611ea331cc1dfce7bdfa/pkg/logs/internal/parsers/dockerstream/docker_stream.go?q=stderr+language%3AGo+path%3A*%2Fdocker*#L110) or a [Kubernetes](https://cs.github.com/DataDog/datadog-agent/blob/433bc3f47d0bdc891e06611ea331cc1dfce7bdfa/pkg/logs/internal/parsers/kubernetes/kubernetes.go?q=stderr+language%3AGo+path%3A*%2Fkubernetes*#L83) container, it will tag the log line with a status based entirely on the stream that it read that log from. `stdout` will always be tagged `INFO`, …
=> fix(datadog_agent source): Remove the `status` field footgun for logs.

Cargo.lock, lib/codecs/Cargo.toml, lib/vrl/stdlib/Cargo.toml, lib/vrl/stdlib/src/parse_syslog.rs
Fixes #13165 
This updates `syslog_loose` with [this](https://github.com/StephenWakely/syslog-loose/pull/17) so it can now handle empty param values in the structured data.
=> fix(syslog source): update syslog_loose to handle empty param values.

src/sources/datadog/agent/logs.rs, src/sources/datadog/agent/tests.rs
Reverts vectordotdev/vector#13219
Apologies for not leaving a review quickly enough on vectordotdev/vector#13219. I'm not really sold on doing this in Vector. From Vector's perspective, it should receive the `status` field exactly as it was received from the Datadog agent for a couple of reasons:
* Users might have transformations they want to do based on the `status` field
* As a Vector user, if I setup `datadog_agent` -> `datadog_logs` I'd expect the data to go through to Datadog, unaltered.
I'm 💯 on adjusting the behavior to avoid the footgun of having `custom_level` added during Datadog ingestion (mapped from `status`), but I'd rather revert this Vector change until we are able to understand it better and identify the correct place to handle it.
=> fix(datadog_agent source): Revert remove the `status` field footgun for logs

src/sources/gcp_pubsub.rs, website/cue/reference/components/sources/gcp_pubsub.cue
The `_secs` naming is the common convention in Vector. This adds the new
options and adds a deprecation notice for the old ones.
=> chore(gcp_pubsub source): Rename `_seconds` settings to `_secs`

src/aws/mod.rs, src/internal_events/aws.rs, src/test_util/components.rs
For `aws_s3`, the `endpoint` (which is the path) includes the object key
information resulting in very high cardinality tags. For example:
```
vector_processed_bytes_total{component_id="sink0",component_kind="sink",component_name="sink0",component_type="aws_s3",endpoint="/timberio-jesse-test/test-metric-cardinality/date%3D2022-06-22/1655913536-cc808697-2d56-43b3-a419-bd6148b9d368.log.gz?x-id=PutObject",protocol="https",region="us-east-1"} 402207 1655913540158```
```
I think this tags isn't useful for AWS sinks, generally.
I realize the component spec requires it though. There has been some
discussion of removing `endpoint` and other tags until we get user
requests for them and can understand the use cases better. The current
tags were optimistic in that we _thought_ users might want them, …
```
=> fix(aws provider): Remove `endpoint` from metrics tags

website/cue/reference/components/sinks/prometheus_exporter.cue
=> docs(prometheus_exporter sink): Document that metrics are at /metrics

lib/vrl/cli/src/repl.rs, lib/vrl/compiler/src/compiler.rs, lib/vrl/compiler/src/expression/abort.rs, lib/vrl/compiler/src/expression/block.rs, lib/vrl/compiler/src/expression/not.rs, lib/vrl/compiler/src/expression/op.rs, lib/vrl/compiler/src/expression/variable.rs, lib/vrl/compiler/src/state.rs, lib/vrl/compiler/src/value.rs, lib/vrl/compiler/src/value/arithmetic.rs, lib/vrl/compiler/src/value/convert.rs, lib/vrl/stdlib/src/decrypt.rs, lib/vrl/stdlib/src/encrypt.rs, lib/vrl/stdlib/src/parse_json.rs, lib/vrl/stdlib/src/type_def.rs, lib/vrl/tests/src/main.rs, lib/vrl/tests/src/test.rs, lib/vrl/vrl/src/prelude.rs
This applies `rustfmt` to VRL crates, using Vector's nightly only [config](https://github.com/vectordotdev/vector/blob/4972d4d770db3457ff7a9b7e30e2157374c9b8e0/.rustfmt.toml).
=> chore(vrl): rustfmt

lib/vrl/vrl/src/lib.rs, lib/vrl/vrl/src/runtime.rs
So that callers don't need to also import `vector_common`.
=> chore(vrl): Reexport TimeZone type

lib/vrl/compiler/src/compiler.rs, lib/vrl/compiler/src/context.rs, lib/vrl/compiler/src/expression.rs, lib/vrl/compiler/src/expression/abort.rs, lib/vrl/compiler/src/expression/array.rs, lib/vrl/compiler/src/expression/assignment.rs, lib/vrl/compiler/src/expression/block.rs, lib/vrl/compiler/src/expression/container.rs, lib/vrl/compiler/src/expression/function_argument.rs, lib/vrl/compiler/src/expression/function_call.rs, lib/vrl/compiler/src/expression/if_statement.rs, lib/vrl/compiler/src/expression/literal.rs, lib/vrl/compiler/src/expression/noop.rs, lib/vrl/compiler/src/expression/not.rs, lib/vrl/compiler/src/expression/object.rs, lib/vrl/compiler/src/expression/op.rs, lib/vrl/compiler/src/expression/predicate.rs, lib/vrl/compiler/src/expression/query.rs, lib/vrl/compiler/src/expression/unary.rs, lib/vrl/compiler/src/expression/variable.rs, lib/vrl/compiler/src/function.rs, lib/vrl/compiler/src/function/closure.rs, lib/vrl/compiler/src/lib.rs, lib/vrl/compiler/src/program.rs, lib/vrl/compiler/src/state.rs, lib/vrl/compiler/src/type_def.rs, lib/vrl/compiler/src/value/arithmetic.rs, lib/vrl/compiler/src/value/error.rs
This PR is part of the ongoing "VRL compiler cleanup" work.
The PR denies all Clippy restrictions, similar to `vector-core`, and then allows those that cannot be fixed using the unstable `--fix` flag. In future PRs, some of these "allows" might be resolved and become denied, or we'll update the initial comment with one explaining why we want to explicitly allow the specific pattern.
Note that this PR is _not_ intended as a forum for discussion on the (lack of) individual merits of the enabled lints, as those discussions happened in #7341, #11597 and other places. This is merely following agreed-upon precedence. Reversing some of these precedences can be discussed in separate issues, without blocking this PR from being merged.
=> chore(vrl): clippy deny+fix on compiler

lib/vrl/stdlib/src/log_util.rs, lib/vrl/stdlib/src/parse_nginx_log.rs, website/cue/reference/remap/functions/parse_nginx_log.cue
The ordering of fields was incorrect. The format is:
```
log_format combined '$remote_addr - $remote_user [$time_local] '
'"$request" $status $body_bytes_sent '
'"$http_referer" "$http_user_agent"';
```
Closes: #13325
=> fix(vrl stdlib): Fix parsing of user for parse_nginx_log

soaks/tests/syslog_log2metric_humio_metrics/vector.toml, src/sinks/humio/metrics.rs, website/content/en/highlights/2022-05-23-0-23-0-upgrade-guide.md, website/cue/reference/components/sinks/humio.cue, website/cue/reference/components/sinks/humio_logs.cue
With this change, metrics are now always sent to Humio using the JSON format.
=> enhancement(humio_metrics sink)!: Remove `encoding` option from `humio_metrics` sink

website/cue/reference/components/sinks.cue
Closes: https://github.com/vectordotdev/vector/issues/13263
=> docs(buffers): Document disk buffer minimum size

benches/dnstap/mod.rs, benches/lua.rs, lib/vector-core/src/event/lua/event.rs, lib/vector-core/src/event/lua/log.rs, lib/vector-core/src/event/mod.rs, lib/vector-core/src/event/test/mod.rs, src/api/tests.rs, src/sinks/console/sink.rs, src/sinks/datadog_archives.rs, src/sinks/gcp/cloud_storage.rs, src/sinks/influxdb/logs.rs, src/sinks/util/encoding/mod.rs, src/sinks/websocket/sink.rs, src/sources/dnstap/mod.rs, src/sources/dnstap/parser.rs, src/sources/kubernetes_logs/parser/mod.rs, src/sources/socket/mod.rs, src/sources/splunk_hec/mod.rs, src/transforms/lua/v1/mod.rs, src/transforms/lua/v2/mod.rs, src/transforms/reduce/merge_strategy.rs, src/transforms/throttle.rs
The use of this function has been discouraged for some time, and there
are few enough uses now to just get rid of it. This change is mostly
pretty mechanical.
=> chore: Drop `Event::new_empty_log`

website/layouts/partials/data.html
- Updates data template reference to `.required` and `.common` of the `.config` object
https://datadoghq.atlassian.net/browse/WEB-2162
- encoding.codec is marked as required and should have a "required" badge (fixed), not "optional" (live)
- https://deploy-preview-13353--vector-project.netlify.app/docs/reference/configuration/sinks/gcp_cloud_storage/#encoding.codec
=> fix(template website): Fix data template reference to .config

benches/transform/common.rs, lib/vector-core/src/event/mod.rs, src/config/unit_test/mod.rs, src/sinks/aws_cloudwatch_logs/integration_tests.rs, src/sinks/file/mod.rs, src/sinks/gcp/cloud_storage.rs, src/sinks/loki/integration_tests.rs, src/sinks/loki/sink.rs, src/sinks/new_relic_logs.rs, src/sinks/redis.rs, src/sinks/splunk_hec/logs/integration_tests.rs, src/sinks/util/encoding/codec.rs, src/sources/heroku_logs.rs, src/sources/kubernetes_logs/parser/cri.rs, src/sources/kubernetes_logs/parser/docker.rs, src/sources/kubernetes_logs/parser/mod.rs, src/test_util/mod.rs, src/topology/test/backpressure.rs, src/transforms/lua/v2/mod.rs, src/transforms/sample.rs
Last one. This removes the last mechanism for creating an implicit log event.
=> chore(core): Remove `Event::from(String)`

website/cue/reference/remap/expressions.cue, website/cue/reference/remap/expressions/function_call.cue, website/layouts/partials/data.html
This PR resolves the "[Update VRL Website Documentation](https://github.com/vectordotdev/vector/blob/b530718e961b6d4a0a4ba9428fdcccb41a8a8e18/rfcs/2021-08-22-7204-vrl-error-diagnostic-improvements.md#update-vrl-website-documentation)" section of RFC https://github.com/vectordotdev/vector/pull/8894.
The PR adds a note to the "function call" expression docs, explaining how fallibility works for function calls.
closes #12903.
=> docs(external docs): add note about function fallibility

website/content/en/highlights/2022-05-23-0-23-0-upgrade-guide.md
This adds a highlight note about the removal of the VRL VM runtime. See #12888.
=> docs(external docs): add highlight about removal of VRL VM runtime

website/content/en/docs/about/under-the-hood/architecture/data-model/log.md, website/content/en/docs/about/under-the-hood/architecture/data-model/metric.md
When rendered, nearly all this text is repeated as-is just above it.
https://vector.dev/docs/about/under-the-hood/architecture/data-model/metric
=> remove repeated text

.github/semantic.yml, .github/workflows/integration-test.yml, Cargo.toml, Makefile, scripts/integration/docker-compose.axiom.yml, src/sinks/axiom.rs, src/sinks/mod.rs, website/content/en/docs/reference/configuration/sinks/axiom.md, website/cue/reference/components/sinks/axiom.cue, website/cue/reference/services/axiom.cue, website/cue/reference/urls.cue, website/data/redirects.yaml
This adds a sink for [Axiom](https://axiom.co). Axiom has support for the bulk API, so this sink is wrapping the `elasticsearch` sink as discussed in https://github.com/vectordotdev/vector/issues/12882.
Here's an example configuration using Axiom Cloud and an API token:
```toml
[sinks.axiom]
inputs = ["whatever"]
type = "axiom"
token = "xaat-1234"
dataset = "vector-dev"
```
Support for configuring the timestamp field on Axioms bulk API is underway and will be deployed + released this week. Until then, the timestamp in Axiom will be the ingestion timestamp and each event will have a `timestamp` key, so I guess it makes sense to wait with merging until that is live (I will comment as soon as that is the case).
1. Does the `axiom.cue` file look sane to you? Can I preview the generated docs …
=> feat(sink): Add Axiom sink

src/sinks/datadog_archives.rs
Fix a tiny typo in the datadog_archives sink for a missing Azure config
=> fix(datadog_archives) fix typo in error msg

src/sinks/pulsar.rs, src/sinks/websocket/config.rs
=> fix(websocket sink, pulsar sink): Fix superfluous `flatten` attribute in `encoding` key

website/content/en/highlights/2022-05-23-0-23-0-upgrade-guide.md, website/content/en/highlights/2022-07-05-0-24-0-upgrade-guide.md
Adds a missing upgrade note for the breaking change introduced in #13317.
=> docs(external docs): add highlight about VRL assignment breaking change

Makefile
Fully qualify vector-dev image name for easier podman usage
=> chore: Fully qualify vector-dev docker image

Cargo.lock, Cargo.toml, lib/value/Cargo.toml, src/api/schema/relay.rs
Manually submitting PR to get the two crates updated in lockstep.
=> chore(deps): bump async-graphql / async-graphql-warp from 3.0.38 to 4.0.4

website/content/en/highlights/2022-07-07-secrets-management.md, website/cue/reference/configuration.cue
Also update the docs to include a full description of how it works
rather than linking to Datadog's docs as:
* the link was already broken
* it's possible the agent might diverge
* Non-Datadog user, Vector users, might be confused
=> docs(config): Add highlight for secrets management

Cargo.lock, lib/vector-common/Cargo.toml, lib/vector-common/src/finalizer.rs
The (un)ordered finalizer framework was initially implemented as an
async loop that was spawned as a separate task. It was later converted
to return a stream of finalizers to allow callers to use that stream
within the same task as the source. This was a manual implementation of
the `Stream` trait.
This change converts that manual implementation back to the same form as
the original implementation using the `async_stream::stream` macro. This
is being done to prepare for the reintegration of the "flush" mechanism
required by the kafka source rebalance fix (#10434).
(Review note: unified diff mode is likely useless for this PR)
=> chore(core): Reimplement finalizer stream using `async-stream`

website/content/en/highlights/2022-07-07-sink-codecs.md, website/cue/reference/components/sinks.cue, website/cue/reference/components/sources.cue
=> docs(codecs): Correct sink codec highlight and document length_delimited framing

website/cue/reference/components/sinks.cue, website/cue/reference/components/sources.cue
Meant `unsigned` not `unsized`.
=> docs(codecs): Correct length_delimited header documentation

src/sources/datadog/agent/mod.rs
Integration tests used the `generate_config` function for the config, which defaulted to using the new log namespacing feature, but the test assertions assumed it was not using this feature, so it was switched off.
=> fix(datadog_agent source): fix datadog agent integration test

src/topology/running.rs, src/topology/test/reload.rs
Remove inputs to which the component is no longer connected during reloading.
fix #13228
=> fix(topology): don't panic when re-add input

lib/vrl/cli/src/cmd.rs
This fixes a clippy lint when running `cargo clippy --workspace --no-default-features`
=> chore(vrl): Fix clippy warning on cli

website/cue/reference/components/sinks.cue
A user on Discord pointed out that while the docs for the minimum size of `buffer.max_size` specify a value of 268435456 (256MB exactly: 256 * 1024 * 1024), the true limit is actually 268435488, which is 256MB _plus_ the ledger size.
We changed this in #13356 to be as precise as possible with tracking bytes used on disk by the buffer, and respecting `buffer.max_size`, where before, we only considered the size of buffer data files themselves.
=> fix(buffers): fix minimum size value for `buffer.max_size` in docs

src/sinks/elasticsearch/service.rs
Closes: #8439
An HTTP header `Accept-Encoding` was missing when compression enabled in the elasticsearch sink.
=> fix(elasticsearch sink): add Accept-Encoding header for compression

src/sinks/elasticsearch/service.rs
This reverts commit 61756a545fd9e2aad5044739789c6f1e111ddcfc.
Reverting this until we have support for reading compressed responses.
https://github.com/vectordotdev/vector/pull/13571#issuecomment-1187691980
=> fix(elasticsearch sink): revert add Accept-Encoding header for compression 

src/sources/util/grpc/mod.rs
Mirroring the log we emit when building an HTTP server:
```shell
2022-07-18T17:55:19.657202Z  INFO source{component_kind="source" component_id=source1 component_type=vector component_name=source1}: vector::sources::util::grpc: Building gRPC server. address=0.0.0.0:6000
2022-07-18T17:55:19.657235Z  INFO source{component_kind="source" component_id=source0 component_type=opentelemetry component_name=source0}: vector::sources::util::grpc: Building gRPC server. address=0.0.0.0:4317
```
=> enhancement(observability): Log the address used when building gRPC servers

lib/vector-core/src/event/array.rs, src/sinks/aws_cloudwatch_logs/integration_tests.rs, src/sinks/datadog/events/tests.rs, src/sinks/datadog/logs/tests.rs, src/sinks/elasticsearch/integration_tests.rs, src/sinks/kafka/tests.rs, src/source_sender/mod.rs
The `EventArray` functions `for_each_X` are equivalent to composing an `iter_X` iterator with that iterator's `for_each` method. Since the composable solution provides for more possible uses, drop the `for_each_X` special cases in favour of new `iter_X_mut` iterator generators.
=> chore(core): Replace `EventArray::for_each_X` with an iterator

scripts/cross/aarch64-unknown-linux-gnu.dockerfile, scripts/cross/aarch64-unknown-linux-musl.dockerfile, scripts/cross/armv7-unknown-linux-gnueabihf.dockerfile, scripts/cross/armv7-unknown-linux-musleabihf.dockerfile, scripts/cross/powerpc-unknown-linux-gnu.dockerfile, scripts/cross/powerpc64le-unknown-linux-gnu.dockerfile, scripts/cross/x86_64-unknown-linux-gnu.dockerfile, scripts/cross/x86_64-unknown-linux-musl.dockerfile, scripts/environment/prepare.sh
There appears to be a change in `main` that is causing the binaries to
be built requiring a newer version of glibc (2.29).
Opened cross issue here: https://github.com/cross-rs/cross/issues/960
Fixes: #13600
=> chore(releasing): Pin to cross 0.2.4

src/config/enterprise.rs
Closes OP-502
This PR
- Changes the default `reporting_interval_secs` to `1` second. This affects how often the `internal_metrics` and `host_metrics` sources scrape for data.
Opening as a draft to view soak results.
=> chore(enterprise): Change default enterprise reporting interval seconds to 1

lib/vector-buffers/src/internal_events.rs, lib/vector-buffers/src/test/helpers.rs, lib/vector-buffers/src/topology/channel/receiver.rs, lib/vector-buffers/src/variants/disk_v1/mod.rs, lib/vector-buffers/src/variants/disk_v1/reader.rs, lib/vector-buffers/src/variants/disk_v1/tests/acknowledgements.rs, lib/vector-buffers/src/variants/disk_v1/tests/basic.rs, lib/vector-buffers/src/variants/disk_v1/tests/mod.rs, lib/vector-buffers/src/variants/disk_v2/ledger.rs, lib/vector-buffers/src/variants/disk_v2/reader.rs, lib/vector-buffers/src/variants/disk_v2/tests/basic.rs, lib/vector-buffers/src/variants/disk_v2/v1_migration.rs
This reverts commit 000fe8bb918a5409b8b7df0d43c436648c611d32.
After discussing the user experience impacts of this change, we have decided to reverse course on
this implementation in favor of the ability to redirect events or batches with errors to alternate
destinations.
Epic: #12145
=> fix(buffers): Revert handle negative acknowledgements by stopping readers

lib/vector-core/src/metrics/handle.rs
The internal metrics histogram buckets are all divided on constant power-of-two borders. As such,
the right bucket number can be computed with a relatively simple log_2 calculation and bounding
instead of the existing loop-and-test.
=> chore(metrics): Eliminate histogram bucket loop

lib/vrl/stdlib/src/log_util.rs, lib/vrl/stdlib/src/parse_apache_log.rs, lib/vrl/stdlib/src/parse_common_log.rs
Closes: #10597
The reporter made a few observations:
1. There are error log formats that apache defines which the current regex doesn't support (it's noted in the code that the current implementation only supports the "simple" format , so perhaps this is somewhere between an enhancement and a bug I guess).
2. The error message when parsing fails for the input error format, is claiming it failed for a "common" format.
I attempted to address both.
For  \#1 I ended up using the reporter's supplied regex, as it looked correct to me and I'm not a regex whiz to where I could spot improvements on that.
Note that there may be other common|error|combined log formats that the current regexes don't support and I'm wondering if a full audit of all the formats that are possible is warranted: …
=> fix(vrl): extend parse_apache_log error format compatibility

src/sources/mongodb_metrics/types.rs
After monitoring MongoDB for a while, Vector will throw out errors like:
```
{ message: "invalid value: integer `2666800889`, expected i32" }
```
MongoDB returns `bytes written from cache` 64-bit integer, but we are trying to parse it as i32.
Signed-off-by: KernelErr <me@lirui.tech>
=> fix(mongodb_metrics source): Change bytes_written_from to i64

rfcs/2022-05-17-11532-chronicle-sink.md
Ref: #11532 
This RFC discussing the implementation of a new sink for [Google Chronicle](https://cloud.google.com/chronicle/docs/overview).
There are a number of complications around how to handle the sending of both unstructured log events and structured UDM events, so this RFC intends to clarify the best way to handle this.
[Readable](https://github.com/vectordotdev/vector/blob/stephen/11532_chronicle_rfc/rfcs/2022-05-17-11532-chronicle-sink.md)
=> chore(new sink): add RFC for Google Chronicle sink

docs/USER_EXPERIENCE_DESIGN.md
it's not obvious this is what was meant, but it was broken in an obvious manner
=> docs: fix typos

src/config/diff.rs, src/topology/builder.rs
Closes #13229 
When reloading the enrichment tables, Vector queries the existing enrichment tables for their indexes. Then the tables are loaded and these indexes are sent to the new tables.
It does this unless it is a new enrichment table - since that table will not have any indexes applied to it (due to it not having been loaded before). To determine if it is a new table the code was calling `!diff.enrichment_tables.contains_new`. It turns out that this function returns true if the table is new *or* has been modified. So if the table has been modified, the reload was thinking it was new and thus not passing the indexes on to the newly loaded table.
This resulted in Vector panicking when that index was queried.
This fix adds a new function that we can call to check if the table has …
=> fix(enriching): fetch indexes if vector config is modified

website/content/en/highlights/2022-07-07-0-23-0-upgrade-guide.md, website/cue/reference/releases/0.23.0.cue
This was noted in the upgrade guide, but not in the changelog (as observed by
https://github.com/vectordotdev/vector/issues/10807#issuecomment-1195962669).
=> docs(releasing): Add note to 0.23.0 about libc/libc++ changes

Cargo.lock, Cargo.toml
=> chore(deps): Upgrade AWS Smithy crates to 0.46.0

lib/datadog/grok/src/parse_grok.rs, lib/vrl/stdlib/src/parse_groks.rs
=> fix(vrl): Do not include empty matches for `grok` pattern

lib/vrl/stdlib/src/parse_grok.rs, lib/vrl/stdlib/src/parse_groks.rs
Closes #12612.
(And therefore also introduces the same bug as #13534 in `parse_groks` to `parse_grok`).
#10287 is also somewhat related to this.
=> chore(vrl): Call `parse_groks` in implementation of `parse_grok`

lib/vrl/stdlib/src/parse_grok.rs
Fixes a conflict that was a result of merging #13721 and #13635.
=> chore: Fix outdated test in `parse_grok`

src/sinks/elasticsearch/sink.rs, src/sinks/elasticsearch/tests.rs
=> fix(elasticsearch sink, sematext sink): Fix index template being excluded via `only_fields`/`except_fields` transform

src/internal_events/socket.rs, src/sinks/util/socket_bytes_sink.rs, src/sinks/util/tcp.rs
By emitting the `BytesSent` event in `BytesSink`, we can avoid the premature emit in the TCP socket code and the duplicated events there too.
Closes #13528
=> chore(sinks): Regularize the emitted events in socket sinks

src/api/schema/metrics/host.rs, src/sources/host_metrics/cgroups.rs, src/sources/host_metrics/cpu.rs, src/sources/host_metrics/disk.rs, src/sources/host_metrics/filesystem.rs, src/sources/host_metrics/memory.rs, src/sources/host_metrics/mod.rs, src/sources/host_metrics/network.rs
All of the metrics out of this source were collected into separate
`Vec`s and then pushed into the same result `Vec`. This change creates a
result buffer and pushes all the metrics into that result. This ends up
allowing for simpler code in a number of places.
As a result of the change, all of the metrics emitted by this source
will have the same timestamp on each collection representing the start
of the collection.
=> chore(host_metrics source): Simplify internal collection of metrics

src/internal_events/socket.rs
The socket sink/source related metrics had an extraneous `.to_string()` on some
of the constant strings used for modes, which causes an unnecessary memory
allocation.
Ref: https://github.com/vectordotdev/vector/pull/13739#discussion_r931898917
=> chore(observability): Remove extraneous to_string

Cargo.lock, Cargo.toml, src/codecs/decoding/decoder.rs
The bug in question: #11245.
This behavior has changed with the upgrade from `tokio_util` beyond `0.6.8`. See #11257 and https://github.com/tokio-rs/tokio/issues/3976.
The upgrade should have been blocked, but the `deny` script hasn't been enforced on CI: #13446.
The upgrade happened inadvertently in #12450.
Unfortunately, we can't easily roll back at the moment since some utilities have been built on top of the new features in `tokio_util`.
=> fix(codecs): Fix bug where Vector shuts down when a decoding error is returned to `FramedRead`

distribution/install.sh, website/content/en/docs/setup/installation/_index.md, website/cue/reference/administration/example_docker_install_commands.cue, website/layouts/shortcodes/docker-example-install-scripts.html
This change adds a `--prefix` option so that users using the install script can manually    specify a custom installation directory and save them from having to copying the `vector`    binary to their $PATH in some situations.
Also added docs to the "Installation script" section for example usage.
Fixes #13486.
=> enhancement(distribution): add `--prefix` option for installation script

src/codecs/encoding/transformer.rs
In #13783, a user reported that despite specifying an invalid configuration field (`onlyfields` vs `only_fields`), Vector still loaded their configuration without issue, leading to a scenario where the intended behavior (only allow specify fields) did not occur, as they believe the configuration was valid.
We've simply added the `#[serde(deny_unknown_fields)]` annotation to detect this scenario, as well as a unit test to ensure we've correctly fixed the issue. There's certainly precedent to potentially use `deny_unknown_fields` by default with an escape hatch for necessary situations, but I figured it was easy enough to fix in this isolated case.
Closes #13783.
=> fix(codecs): deny unknown fields on transformer config

Makefile
By default, `make check` would only check the `default` feature set, and would
not check any tests or other anciallary code, while `make check-clippy` checks
everything. This makes both such checks go through everything.
=> chore(dev): Make `make check` and `make check-clippy` line up

website/content/en/docs/setup/installation/package-managers/msi.md
The current MSI filename has been changed from `vector-x86_64.msi` to `vector-x64.msi`. And quiet mode is not an element way to install programs.
Signed-off-by: KernelErr <me@lirui.tech>
=> docs(installation msi): Fix powershell script

src/aws/auth.rs, website/cue/reference/components/aws.cue
Issue:  https://github.com/vectordotdev/vector/issues/13829
Allow a user to optionally specify the `auth.region` without changing the underlying sink behavior.  If a user does not specify `auth.region` then there should be no change to functionality.
If a user does specify `auth.region` only the credential providers will reference that region.
Very open to comments/changes etc.
=> feat(aws): add auth.region option when assuming role

src/http.rs
As described in #13683, when enabling the proxy for the http sink, the hyper ProxyConnector is not configured properly with the user supplied tls settings. Therefore, certificate verification using a private PKI or client cert authentication are broken.
=> fix(http sink): cert verification with proxy enabled

lib/vrl/compiler/src/test_util.rs, lib/vrl/stdlib/Cargo.toml, lib/vrl/stdlib/benches/benches.rs, lib/vrl/stdlib/src/is_ipv4.rs, lib/vrl/stdlib/src/is_ipv6.rs, lib/vrl/stdlib/src/lib.rs, website/cue/reference/remap/functions/is_ipv4.cue, website/cue/reference/remap/functions/is_ipv6.cue
As stated in the title.
Fixes #13849.
=> feat(vrl): add methods to check if a string is an IPv4 or IPv6 address

rfcs/2022-07-28-13691-registered-internal-events.md
This is intentionally not fleshed out in full detail, as the proposal is relatively small and self-contained.
Ref #13691 
[Rendered view](https://github.com/vectordotdev/vector/blob/registered-internal-events-rfc/rfcs/2022-07-28-13691-registered-internal-events.md)
=> chore(observability): RFC for registered internal events

src/transforms/log_to_metric.rs
=> fix(log_to_metric transform): add metric timestamp if source log lacks one

src/sources/prometheus/remote_write.rs, src/sources/prometheus/scrape.rs
This is an attempt to fix the recent spate of Prometheus unit test failures on macOS. These don't seem to reproduce at all locally for most folks, but the macOS CI runners are shared and generally far more underpowered than local development environments, which seems to be the most likely cause of why they fail in CI but not locally.
At any rate, the changes made here are very much correct and not actually a stopgap or hack so this is still an improvement regardless of the current CI situation.
=> fix(prometheus_scrape source,prometheus_remote_write source): wait for mock endpoint in tests

website/content/en/highlights/2022-07-07-0-23-0-upgrade-guide.md
Include breaking change from #13176
=> chore(docs): Update v0.23 upgrade guide

src/sources/docker_logs.rs
Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>
fix #13314
There is another bug(#13861) found during the investigation. It can be fixed by #13862.
=> fix(docker_logs source): fix metrics not attached to the source

website/cue/reference/components.cue, website/cue/reference/components/sources.cue, website/cue/reference/components/sources/socket.cue
Only socket-based sources support this so far.
Fixes: #13914
=> docs(config): Only render `client_metadata_key` if available

distribution/install.sh
|When using the `curl sh.vector.dev | bash`-based installation method, the installer script can modify the user's `$PATH` to add the binary directory so that `vector` is available on the path.
Normally, this should be `~/.vector/bin` so that `vector` is on the path, but the installer script currently only adds `~/.vector` to `$PATH`. This PR simply tweaks that to add the right binary subdirectory to land at the expected behavior.
=> fix(setup): add the correct bin directory to $PATH

lib/vector-common/src/internal_event/mod.rs, scripts/check-events, src/internal_events/mod.rs
This sets up the core trait structures and macros for registering internal
events that may later be emitted. It also updates check-events to scan for
registered metrics. No actual component changes are present, they will be
handled in separate PRs.
=> chore(core): Set up registered internal event structures

website/content/en/docs/about/under-the-hood/architecture/data-model/log.md
=> docs: Remove mention of `coercer` and parser transforms

website/cue/reference/components/transforms/geoip.cue
Replaced by enrichment table support
=> chore(geoip transform): Deprecate `geoip` transform

scripts/environment/bootstrap-ubuntu-20.04.sh, soaks/Dockerfile.builder
Required to upgrade to prost 0.11 which drops support for building protoc. Opening as a separate PR
to be able to upgrade the builder image used by the prost 0.11 upgrade PR.
=> chore: Install protoc for soak builder too

lib/vrl/stdlib/src/unnest.rs
Cloning the entire `root` variable during the `events` iterator for each map is highly inefficient. The time & space complexity explodes as the target array grows.
Target `path` of the `root` will be replaced anyway. Therefore, we can simply remove the `values` from the `root` value to create a `trimmed` value, which we can use it to clone much more efficiently.
This fixes #13983
=> fix(unnest): Faster & less memory by dropping to-be-replaced values

lib/file-source/src/file_server.rs, lib/file-source/src/file_watcher/mod.rs, lib/file-source/src/file_watcher/tests/experiment.rs, lib/file-source/src/file_watcher/tests/experiment_no_truncations.rs, src/sources/file.rs, src/sources/kubernetes_logs/mod.rs, website/cue/reference/components/sources/file.cue
Motivation: If an application produces log lines faster than the resolution of the timestamp used additional information is needed to maintain ordering, and form part of a unique document id used in downstream services such as Elasticsearch.
Off by default, turned on by setting a value in config for `offset_key`.
This addresses issue #6633.
=> enhancement(file source): Add optional byte offset to file source events

website/cue/reference/components/sinks/prometheus_exporter.cue
Fix a redundant naming: use `prometheus_exporter` instead of `prometheus`.
=> docs: Rename prometheus to prometheus_exporter sink

lib/vector-core/src/config/mod.rs, src/sources/datadog_agent/logs.rs
Some sources need to use a configurable metadata field name when using the `Legacy` namespace, but a hard-coded name when using the `Vector` namespace. Now both names are passed into the `LogNamespace::insert_source_metadata` function.
=> chore(core): Allow configurable names for "source" metadata

docs/DOCUMENTING.md
Adds a link to install cue. I wasn't aware when attempting to contribute that cue was a separate dependency.
=> docs: Adds link to directions for installing cue

lib/lookup/src/lookup_v2/borrowed.rs, lib/lookup/src/lookup_v2/jit.rs, lib/lookup/src/lookup_v2/mod.rs, lib/lookup/src/lookup_v2/owned.rs
This is some cleanup that was pulled out of https://github.com/vectordotdev/vector/pull/14011 to help simplify the implementation there.
This unifies `OwnedSegment::CoalesceField` and `OwnedSegment::CoalesceEnd` into a single `OwnedSegment::Coalesce`. It was originally split to more closely model `BorrowedSegment`, which needs it for performance reasons (to prevent allocations). `OwnedSegment`'s however are not expected to be parsed / created at runtime and having a single coalesce segment is easier to work with.
I'd also eventually like to remove `OwnedSegment::Invalid`, but that will come later.
=> chore(core): Simplify lookup path coalesce segments

lib/value/src/value/convert.rs, lib/vrl/stdlib/Cargo.toml, lib/vrl/stdlib/benches/benches.rs, lib/vrl/stdlib/src/chunks.rs, lib/vrl/stdlib/src/lib.rs, lib/vrl/tests/tests/functions/chunks_chunk_size_at_least_1.vrl, lib/vrl/tests/tests/functions/chunks_fallible_given_expression.vrl, website/cue/reference/remap/functions/chunks.cue
Issue: https://github.com/vectordotdev/vector/issues/13329
This adds a `chunks` method (chunks rather than chunk following the slice naming convention for [slice's chunks method](https://doc.rust-lang.org/std/primitive.slice.html#method.chunks)). This chunks data based on a given `chunk_size` in bytes. The result is an array of bytes of `chunk_size` in length.
______
👇 The below was true for the initial PR, which attempted to respect unicode code point boundaries. After [this comment](https://github.com/vectordotdev/vector/pull/13794#pullrequestreview-1065676560) that is no longer the aim of this PR.
______
~It attempts to respect unicode code point boundaries, but makes no guarantees about grapheme cluster boundaries: https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries~
~A …
=> feat(vrl): Adds `chunks` function

src/sinks/elasticsearch/service.rs
Unless I am mistaken ElasticSearch has little to do with containerd.
=> fix(elasticsearch sink): fix error msg spelling

scripts/check-deny.sh
So that it doesn't output all of the warnings, making it more difficult to find the errors. We may
make more of these warnings failures in the future (e.g. the licences per
https://github.com/vectordotdev/vector/issues/12190).
=> chore(dev): Lower `cargo deny` log level

src/internal_events/file.rs
Closes #13986.
Per [spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#error), error's should be rate limited at 10s.
=> enhancement(file source): Add 10s rate limit to all `file` source errors

src/internal_events/template.rs
Part of #14019.
Part of #13995.
Depending on configuration some templating errors cause dropped events, this intends to adhere the `TemplateRenderingError` event to the `EventsDropped` spec this is the case.
This PR will affect any component using the `TemplateRenderingError` event.
=> enhancement(observability): Adhere TemplateRenderingError to EventsDropped spec

src/sinks/prometheus/exporter.rs
part of #14077 
part of #13995
=> enhancement(prometheus_exporter sink): use common test helpers in tests

docs/specs/instrumentation.md
That sources shouldn't emit that they discarded events if they haven't created the events yet.
=> chore(internal docs): Clarify dropped events for sources

proto/dd_trace.proto, src/sinks/datadog/traces/request_builder.rs, src/sources/datadog_agent/tests.rs, src/sources/datadog_agent/traces.rs
Fix for https://datadoghq.atlassian.net/jira/software/c/projects/OBPS/boards/1533?modal=detail&selectedIssue=OBPS-8
NOTE: I am posting a review because I believe the code change is correct, however while trying to test the fix against the expected behavior from the JIRA issue, I am not seeing the `kube_namespace` tag. What I'm wondering is perhaps the helm values to generate the reproduction attempt are not correct ?
This is the data generated before applying the fix, note tags is empty:
```
{"agent_version":"7.38.2","app_version":"","container_id":"b6fbf7915a1d6229310bf6fe4979f4374bb761ba0b3b709171606b8fcb8c84a3","dropped":false,"env":"none","error_tps":0.0,"host":"minikube","language_name":"python","language_version":"3.10.6","origin":"","payload_version":"v2","priority":10,"runtime_id": …
```
=> fix(datadog agent source): traces are missing k8s tags

docs/CONTRIBUTING.md, docs/DEPRECATION.md, docs/DEVELOPING.md, docs/DOCUMENTING.md, docs/README.md, docs/USER_EXPERIENCE_DESIGN.md, docs/specs/buffer.md, docs/specs/component.md, docs/specs/configuration.md, docs/specs/instrumentation.md, docs/specs/target.md
Found via `markdownlint *.md --disable MD013 MD024`.
=> docs: fix markdown in internal docs

.github/workflows/integration-test.yml, .github/workflows/k8s_e2e.yml, .github/workflows/publish.yml, .github/workflows/test.yml
CI environments should be installing all needed tools. My intent is to supress the duplicate cross
installation.
=> chore(ci): Remove AUTOINSTALL from CI

lib/enrichment/src/find_enrichment_table_records.rs, lib/enrichment/src/get_enrichment_table_record.rs, lib/enrichment/src/vrl_util.rs, lib/vrl/compiler/src/function.rs, lib/vrl/stdlib/src/del.rs, lib/vrl/stdlib/src/encode_percent.rs, lib/vrl/stdlib/src/exists.rs, lib/vrl/stdlib/src/is_json.rs, lib/vrl/stdlib/src/log.rs, lib/vrl/stdlib/src/match_any.rs, lib/vrl/stdlib/src/match_datadog_query.rs, lib/vrl/stdlib/src/parse_apache_log.rs, lib/vrl/stdlib/src/parse_grok.rs, lib/vrl/stdlib/src/parse_groks.rs, lib/vrl/stdlib/src/parse_key_value.rs, lib/vrl/stdlib/src/parse_nginx_log.rs, lib/vrl/stdlib/src/parse_regex.rs, lib/vrl/stdlib/src/parse_regex_all.rs, lib/vrl/stdlib/src/parse_user_agent.rs, lib/vrl/stdlib/src/redact.rs, lib/vrl/stdlib/src/sha2.rs, lib/vrl/stdlib/src/sha3.rs, lib/vrl/stdlib/src/to_timestamp.rs, lib/vrl/stdlib/src/to_unix_timestamp.rs, lib/vrl/stdlib/src/unnest.rs
This is a continuation of the cleanup from https://github.com/vectordotdev/vector/pull/12888
Some code was originally preserved even though it was unused because the LLVM runtime may have used it. Now that it seems like the LLVM runtime won't exist anytime soon, that is also being cleaned up.
=> chore(vrl): cleanup unused code (saved for LLVM runtime)

Cargo.lock, lib/k8s-test-framework/Cargo.toml, lib/k8s-test-framework/src/lock.rs, src/config/loading/mod.rs, src/trace.rs
As of Rust 1.63, the std locks can be created in `const` context, meaning they
can be used directly in `static` expressions (so long as the contained
initializer is also `const`, of course). This change drops several `OnceCell`s
used just to initialize such locks.
=> chore: Create std locks in const context

docs/specs/instrumentation.md
We should not emit if _Vector_ will retry, but we should emit if Vector drops even if end-to-end
acknowledgements are enabled as we cannot know if the client will retry.
=> chore(dev): Clarify events dropped internal event for retries

src/internal_events/internal_metrics.rs, src/internal_events/mod.rs, src/sources/internal_logs.rs, src/sources/internal_metrics.rs
Closes: #14129.
Closes: #14130.
Part of  #13995.
- Added test helper assertions
- Added `BytesReceived` event emission to `internal_metrics` in order to comply
=> enhancement(internal_logs, internal_metrics source): Add test helpers to assert source compliance

docs/specs/instrumentation.md
Was, I think, inadvertently dropped by af1905a
=> chore: Re-add dropped `stage` field to component error spec

src/internal_events/file.rs, src/internal_events/journald.rs, src/internal_events/kafka.rs, src/source_sender/mod.rs, src/sources/file.rs, src/sources/journald.rs, src/sources/kafka.rs, src/sources/mod.rs
We are moving forward on handling processing and delivery errors by alternate
means that will no longer require sources to reject events. This halting
behavior is surprising to users and causes situations that are difficult to
recover from without complicated manual adjustments. As such, we are going to
revert this series in order to prevent regressions.
This partially reverts the following commits:
fix(kafka source): Fix handling of negative acknowledgements (#12901)
2dfa85b69def8492b4e5081bbfcc755107737957
fix(journald source): Fix handling of negative acknowledgements (#12913)
da11de593a7b3802c923c732725054e9ab2ee07f
fix(file source): Fix handling of negative acknowledgements (#12936)
4c584221536be94bfb90ef2385c5628577c55ec0
Ref: …
=> revert(sources): Revert halting stream sources on error acknowledgements

docs/specs/instrumentation.md
=> chore: Clarify events dropped log should be rate limited

docs/DEPRECATION.md
A user on Discord pointed out that they were confused that they were not seeing warning logs in the CLI when using a deprecated configuration option, despite the deprecation documentation saying it should be there.
This boiled down to the wording about "when possible" being buried at the end. This change simply moves it to the very beginning to emphasize that there may not always be a log message about deprecated option usage.
=> chore(docs): update wording around deprecation warnings in CLI to emphasize optionality

src/codecs/decoding/decoder.rs, src/internal_events/codecs.rs, src/internal_events/http.rs, src/sources/http.rs, src/sources/util/http/prelude.rs
Closes:  #14056.
Part of: #13995.
=> enhancement(http source): emit Error and ErrorDropped events per instrumentation spec

website/cue/reference/components/sinks/aws_s3.cue
Should require `ListBucket`
Closes: #14166 
=> docs(aws_s3 sink): Fix permission for healthcheck

docs/specs/component.md
We intend to replace the measurements for these with JSON estimations of byte sizes, but, until we
do, I think it's useful to have these in here to ensure all sources / sinks report these consistently.
Separately we will, at some point, add `SinkNetworkBytesSent` and `SourceNetworkBytesReceived` to
indicate network bytes. Marked these as "to be implemented" for now.
=> chore: Re-add bytes events to the spec

Cargo.lock, Cargo.toml
Now that 0.24.0 has been released.
=> chore: Bump version to 0.25.0

src/internal_events/aws_ecs_metrics.rs
Closes #14193
Adds 10s rate limits to aws_ecs_metric events.
Doesn't appear as though events can be dropped unless there's a StreamClosedError.
=> enhancement(aws_ecs_metrics source): Add log rate limits

website/cue/reference.cue, website/cue/reference/components/sinks.cue, website/cue/reference/components/sinks/socket.cue, website/cue/reference/components/sources.cue
Technically it is supported on all sinks, but so far the pattern has been to only document codecs
that are typically used for a given sink so I just documented it on the `socket` sink which is
likely to be the only one this codec is used with.
Fixes: #14230
=> docs(codecs): Document support for GELF codec

Cargo.lock, Cargo.toml, src/sinks/file/mod.rs, src/test_util/mod.rs, website/cue/reference/components/sinks.cue, website/cue/reference/components/sinks/file.cue
This is part of #2302
I'm a bit uncomfortable with raising `zstd` to a true dependency, but the `lines_from_zstd_file` test function is always built. I put in the current version `0.10` from Cargo.lock.
todos:
=> feat(file sink): support Zstandard-compressed output

src/sources/aws_sqs/source.rs
So that metrics are correctly tagged.
Fixes: #14252
I still want to test this manually. #14196 will verify it further and add tests, but this should at least fix the issue.
=> fix(aws_sqs source): Pass span context to spawned tasks

src/internal_events/file.rs, src/internal_events/kubernetes_logs.rs, src/internal_events/redis.rs, src/internal_events/statsd_source.rs, src/sinks/file/mod.rs
=> enhancement(file sink): Adhere to instrumentation spec

lib/vector-config/tests/smoke.rs, tests/shutdown.rs
The `timely_shutdown_vector_v1` test is causing CI breakage, and the other is just unworkable as it stands.
=> chore(tests): Remove vector v1 tests

lib/vrl/stdlib/src/parse_key_value.rs, website/cue/reference/remap.cue, website/cue/reference/remap/functions/parse_key_value.cue
=> enhancement(vrl): In `parse_key_value` group duplicate keys into an array

src/sinks/http.rs, website/cue/reference/components/sinks/http.cue
We had previously released the widened input type support in Vector in 0.22.0 but narrowed it in
ahead of 0.23.0 thinking that we never released the widened support.
We still need to figure out a better way to model this in the docs: where the input type varies depending on the configured codec.
Fixes: #14319
=> fix(http sink): Expand input type support to match codec's

.cargo/config.toml
In order for dynamically loaded Lua modules to work, they need to be able to link against the symbols provided by the Lua libraries. These symbols are not exposed unless `vector` is linked with the `-rdynamic` flag. This flag was removed by #13074 (Fix application of `rustflags`) and here we are restoring just this flag for linking.
Closes #14271
=> chore(dev): Restore the `-rdynamic` linker flag

src/internal_events/mongodb_metrics.rs
Closes #14198
Both errors are prior to event creation in Vector and don't need to increment a dropped counter.
=> enhancement(mongodb_metrics source): Rate limit internal errors

lib/vector-common/src/internal_event/events_received.rs, lib/vector-common/src/internal_event/mod.rs, src/internal_events/common.rs, src/sources/aws_s3/sqs.rs, src/sources/eventstoredb_metrics/mod.rs, src/sources/file_descriptors/mod.rs, src/sources/journald.rs
EventsReceived emitted the a superset of OldEventsReceived's metrics and logs, this should have zero impact on users.
=> chore: Remove unneeded OldEventsReceived

.gitignore, Makefile, docs/DEVELOPING.md, scripts/environment/Dockerfile, scripts/environment/prepare.sh
This is based on my set up on Fedora 36. I have verified that `CONTAINER_TOOL=docker` (using fedora package `moby-engine`), and `CONTAINER_TOOL=podman` can spawn a shell, where `make check` finishes.
=> chore: update environment with rustup cache, podman compat

lib/vector-common/src/internal_event/service.rs, lib/vector-core/src/stream/driver.rs
I missed that the `SinkSendError` (and `ComponentEventsDropped`) event gets emitted on the retry logic, which means we don't need to emit internal events here! That's what happens when too much time elapses between submitting PRs and merging them :grimacing: 
Reverted back to the error! log print that was here before my change.
Fixes this unit test failure:
```
failures:
sinks::datadog::logs::tests::handles_failure_v2
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 269 filtered out; finished in 0.03s
--- TRY 4 STDERR:        vector sinks::datadog::logs::tests::handles_failure_v2 ---
thread 'sinks::datadog::logs::tests::handles_failure_v2' panicked at 'Failed to assert compliance, errors:
- Multiple (2) events matching `Error`: (`ServiceCallError`, `SinkSendError`). Hint! …
```
=> fix(internal events): Double emission of `Error` event in sink framework code.

docs/specs/instrumentation.md
If an error occurs that prevents Vector from starting, we don't need to emit an event. This updates the component spec to clarify this.
=> chore: add note about errors that prevent Vector starting to Component Spec

website/cue/reference/components/sources/host_metrics.cue
Missed this in this PR: https://github.com/vectordotdev/vector/pull/14328
=> fix(docs): add cpu count metrics to `host_metrics` cue docs

src/sources/demo_logs.rs
Ref #14374 
This wraps the unit tests with `assert_source_compliance` to ensure the source emits the correct events.
Note this works with unit tests rather than integration tests since integration tests aren't required due to the simplicity of the source.
=> enhancement(demo_logs source): add assert_source_compliance to unit tests

website/cue/reference/components/sinks/prometheus_exporter.cue
* the default for this option is `false`, not `true`
Ref: https://github.com/vectordotdev/vector/blob/5230fcdbb348376a35729a1a2ad7920b7243aa1c/src/sinks/prometheus/exporter.rs#L164-L166
=> fix(docs): fix wrong default value for `suppress_timestamp` in `prometheus_exporter` sink

website/cue/reference/components/sources/internal_metrics.cue
=> docs(internal_metrics): Fix labels for uptime_seconds

Makefile
Some duplicates have crept into the list of integration tests in the Makefile.
=> chore: remove duplicate integration tests

src/sinks/honeycomb.rs
Honeycomb uses "[time](https://docs.honeycomb.io/api/events/#batched-events-body)" for the batch api endpoint in sending Honeycomb events to represent the timestamp of the event, not "timestamp".  This change will allow Honeycomb to correctly pick up the timestamp field.
=> fix(honeycomb sink): Fixes timestamp field to match Honeycomb spec

lib/vector-core/src/schema/definition.rs, src/sources/datadog_agent/mod.rs
fixes: https://github.com/vectordotdev/vector/issues/14387
Some of the new "log namespace" code assumed that the global schema keys would always be valid, but previously you could set it to an invalid path (such as the empty string) which would prevent the data from being inserted. This is now also supported with the new code.
=> fix: allow empty log schema keys

src/sinks/prometheus/remote_write.rs
Closes: #14092
Epic:  #13995
- Adds test compliance test helpers
- Adds emission of `EndpointBytesSent`
- emits `EventsDropped` when template rendering error occurs.
Note: wanted to use a Registered event, but I don't think it exists yet for `EndpointBytesSent`
=> enhancement(prometheus_remote_write sink): Adhere to instrumentation spec

.github/workflows/integration-test.yml, scripts/integration/docker-compose.datadog-agent.yml, scripts/integration/docker-compose.datadog-logs.yml, scripts/integration/docker-compose.datadog-metrics.yml, scripts/integration/docker-compose.datadog-traces.yml, src/sinks/datadog/logs/integration_tests.rs, src/sinks/datadog/metrics/integration_tests.rs, src/sinks/datadog/traces/integration_tests.rs
Will fail faster and more clearly than retrying forever.
=> chore: Require TEST_DATADOG_API_KEY for Datadog integration tests

src/internal_events/dnstap.rs, src/sources/dnstap/mod.rs, src/sources/dnstap/parser.rs
When parsing a dnstap message, if there is an error parsing the message or if the message has an invalid `data_type_id` (anything other than 1), the entire message is inserted as raw data. The parser inserts the entire message into the event as raw data and returns a success.
Currently when this happens an `error` is logged and `component_errors_total` is incremented.
This PR changes this so that it just logs a warning and does not increment `component_errors_total` (should it still increment this?).
Now, the only time an error is raised is if there is an error decoding the raw bytes of the `dnstap` protobuf message. In this case the parse function returns an `Err` which then logs the `error`. The message is then dropped.
=> fix(dnstap source): recoverable parse errors should be a warning

scripts/integration/docker-compose.docker-logs.yml, src/sources/docker_logs.rs
Ref #14411 
This adds `assert_source_compliance` calls to the integration tests for the docker logs source.
There is also a fix to the docker-compose file. It appears the integration tests weren't running at all without this.
=> fix(docker_logs source): add assert_source_compliance calls to integration tests

src/sinks/honeycomb.rs
Closes #14152
It _seems_ like the errors are handled by shared code, and nothing needs to be added here. There are no integration tests for this sink.
=> chore(honeycomb sink): Use HTTP_SINK_TAGS for compliance

src/sinks/new_relic/config.rs, src/sinks/new_relic/mod.rs, src/sinks/new_relic/model.rs, src/sinks/new_relic/sink.rs
Closes #14209
Events are handled by the new sink framework, use the new shared `SinkRequestBuildError`
=> chore(new_relic sink): Adhere to InternalEvents spec

src/internal_events/statsd_sink.rs, src/sinks/datadog/events/service.rs, src/sinks/datadog/logs/service.rs, src/sinks/datadog/metrics/service.rs, src/sinks/datadog/traces/service.rs, src/sinks/influxdb/metrics.rs, src/sinks/prometheus/remote_write.rs, src/sinks/statsd.rs, src/sinks/util/udp.rs
Closes: #14214
Epic: https://github.com/vectordotdev/vector/issues/13995
This is the sink that made me realize the EventsDropped aren't being handled by the sink retry code.
There is ongoing discussion on how to handle it but this PR bring statsd sink up to the current standards.
=> enhancement(statsd sink): Adhere to instrumentation spec

lib/vrl/stdlib/src/del.rs, website/cue/reference/remap/functions/del.cue
This adds a `compact` option to the `del` function, which deletes empty objects / arrays.
=> add compact option to del

scripts/check-events, src/internal_events/common.rs, src/internal_events/loki.rs, src/sinks/loki/healthcheck.rs, src/sinks/loki/integration_tests.rs, src/sinks/loki/mod.rs, src/sinks/loki/sink.rs, src/sinks/loki/tests.rs
- chore(loki sink): Remove duplicate code from healthcheck
- chore(loki sink): Misc cleanup and comments
- enhancement(loki sink): Adhere to errors and dropped events spec
Closes #14208
Adds the required `count` property to dropped events logs, and checks for it in the `check-events` script.
=> enhancement(loki sink): Adhere to InternalEvents spec

src/internal_events/aws_cloudwatch_logs.rs, src/sinks/aws_cloudwatch_logs/integration_tests.rs, src/sinks/aws_cloudwatch_logs/request.rs, src/sinks/aws_cloudwatch_logs/request_builder.rs
- enhancement(aws_cloudwatch_logs sink): Use shared EventsDropped and remove duplicate internal event
- enhancement(aws_cloudwatch_logs sink): Adhere to InternalEvents spec
Closes #14201
=> enhancement(aws_cloudwatch_logs sink): Adhere to InternalEvents spec

src/sinks/aws_kinesis_firehose/config.rs, src/sinks/aws_kinesis_firehose/integration_tests.rs, src/sinks/aws_kinesis_firehose/request_builder.rs, src/sinks/aws_kinesis_firehose/service.rs, src/sinks/aws_kinesis_firehose/sink.rs
Closes #14203
Majority of errors are handled by the new sink code, or the encoder.
=> chore(aws_kinesis_firehose sink): File cleanup and use SinkRequestBuildError

src/internal_events/exec.rs, src/sources/exec/mod.rs, src/test_util/components.rs
Ref #14451 
If the `Sender` is closed when the command thread tries to send it, that event is dropped. Before we were emitting a `trace`. I've updated this to emit an `Error` and update `component_discarded_events_total`.
I can't really think of a realistic situation where this error would occur, but it is a potential so we should emit.
=> fix(exec source): emit discarded error when channel is closed

lib/vector-core/src/config/global_options.rs, src/config/builder.rs
Merging two global configs has had several bugs when fields were not properly handled. This change reorganizes the merge operation to create a new structure, thus ensuring any new fields will be handled, and moves the operation into the appropriate impl block, to make it easier to locate where to make the changes.
Ref #14423
=> chore(config): Move global config merging into core

docs/specs/instrumentation.md
This PR clarifies the instrumentation spec by
- explicitly requiring errors to emit an `EventsDropped` event
- explicitly require the `intentional` property to be set on the counter emitted from `EventsDropped`
=> chore(internal docs): Explicitly require errors to emit an `EventsDropped` event / explicitly require `intentional` property

src/sources/exec/mod.rs
Ref #14451
This wraps the tests with a call to `assert_source_compliance`.
=> fix(exec source): Add `assert_source_compliance` to tests

scripts/features
The `features` script that extracts cargo features from a configuration file was hard-coded to accept only TOML configuration files. Since we are seeing more YAML configuration files, this also needs to account for that file format.
=> chore(dev): Allow loading YAML configs with `run-vector` script

src/sinks/prometheus/exporter.rs
Replaces `eprintln!` with `error!`, and emits an `info` log (like our other HTTP servers) that contains the address the component will be listening on.
=> feature(prometheus_exporter sink): Emit address when building server.

build.rs, src/internal_events/process.rs, website/cue/reference/components/sources/internal_metrics.cue
=> feat(internal_metrics): Added ```vector_info```  internal metric, capturing build information

scripts/check-events
Since [this commit](https://github.com/vectordotdev/vector/commit/3e0ca6bdf0f4f4bb3bc66ddfc14c6b961f83dbd2) the `check-events` script is not reporting the file path in which there is an error. This PR brings it back.
Signed-off-by: Jeremie Drouet <jeremie.drouet@datadoghq.com>
=> fix(ci): report filename when check-events errors

src/internal_events/docker_logs.rs, src/sources/docker_logs.rs
Ref #14411 
When receiving a message from docker that is older than the previous one, this message was being dropped and a `trace` message was emitted.
I would argue that this should be a component error, and this PR makes it so. 
It's not 100% clear to me under what circumstances this error would occur, so I am open to arguments as to why this should remain a trace - in which case I will update to add a comment with that reason.
=> fix(docker-logs source): old messages that are dropped should be a component_error

src/internal_events/common.rs, src/sinks/aws_kinesis_firehose/sink.rs, src/sinks/aws_kinesis_streams/sink.rs, src/sinks/aws_sqs/sink.rs, src/sinks/datadog/events/sink.rs, src/sinks/datadog/logs/mod.rs, src/sinks/datadog/logs/sink.rs, src/sinks/loki/sink.rs, src/sinks/new_relic/sink.rs, src/sources/docker_logs.rs, src/sources/http_scrape/integration_tests.rs, src/sources/http_scrape/scrape.rs
- chore(observability): Don't include name field for SinkRequestBuildError
- chore: Fix typos and use NamedComponent for http_scrape
The `name` field duplicates the info included at the beginning of the log, removing it saves us some work.
```text
2022-09-21T20:11:11.005652Z ERROR sink{component_kind="sink" component_id=sink0 component_type=aws_s3 component_name=sink0}: vector::internal_events::common: Failed to build request for <NAME> error=<ERROR> error_type="encoder_failed" stage="processing" internal_log_rate_limit=true
```
=> chore(observability): Don't include name field for SinkRequestBuildError

website/cue/reference/components/sources/host_metrics.cue
The load averages are calculated over a period of minutes, not seconds as the reference currently states.
Closes #14521
=> docs(host_metrics source): Fix description of load1/5/15 metrics

src/sinks/pulsar.rs, website/cue/reference/components/sinks/pulsar.cue
=> feat(pulsar): message keys as config field

lib/vrl/stdlib/Cargo.toml, lib/vrl/stdlib/benches/benches.rs, lib/vrl/stdlib/src/keys.rs, lib/vrl/stdlib/src/lib.rs, lib/vrl/stdlib/src/values.rs, website/cue/reference/remap/functions/keys.cue, website/cue/reference/remap/functions/values.cue
Issue: https://github.com/vectordotdev/vector/issues/11888
This adds a `values` method and a `keys` method to print out only the keys or values of a given iterable vrl `Value` input.
Examples is yet to be implemented, future iteration is needed and feedback is welcome.
Testing:
To be determined
=> feat(vrl): Adds `keys()` and `values()` function

src/sinks/pulsar.rs
`Display` on `Value` quotes `Bytes`, which we don't want.
=> chore(pulsar sink): Fix integration test for partition key

lib/prometheus-parser/src/lib.rs
The error message was always saying u32 was the max even though it could be u64.
=> fix(prometheus_scrape source): Improve error messages for out of range values

lib/vrl/stdlib/src/parse_xml.rs
In our company we found a potential panic in `parse_xml` which crashes vector.
XML payload causing panic
```xml
<p><?xml?>text123</p>
```
I added test case for this, but I am not sure about it.
According to spec this is incorrect xml
>  https://www.w3.org/TR/xml/#sec-prolog-dtd
>  xml declaration should be first element in the file
But `roxmltree` parses it without an error
Should we depend on this behavior? If not then test should be removed
=> fix(vrl parse_xml): Fix panic in parse_xml vrl function

src/sources/vector/mod.rs, website/content/en/highlights/2022-10-04-0-25-0-upgrade-guide.md, website/cue/reference/components/sources/vector.cue
closes https://github.com/vectordotdev/vector/issues/13562
=> chore(vector source): Remove unused `shutdown_timeout_secs` option

scripts/check-events
Previously, the `check-events` script would scan all files in this project – including the `target` directory with lots of many small files that are not relevant to this script - and filter them in Ruby.
This PR at least reduces the scope to the `src` and `lib` directories.
=> chore(ci): Limit search in `check-events` script to `src`/`lib`

src/sinks/util/http.rs
Ref: #14526 
Epic: #13995
This emits a `RequestBuildError` if the `request_builder` function returns an error.
I have looked through all the sinks that implement this trait, and none currently emit an event here, so as far as I can tell there doesn't appear to be any risk of duplicate events.
=> fix(observability): emit `RequestBuildError` when `HttpSink::request_builder` errors

Makefile, scripts/integration/docker-compose.chronicle.yml, src/sinks/gcp/chronicle_unstructured.rs
Ref #14595 
This adds a `run_and_assert_sink_error` call to the unhappy path integration test. This highlighted the issue that error returns from chronicle were not  emitting an error. So this also fixes that.
As an added bonus it seems the chronicle integration tests weren't included in the list of tests, so this PR also adds them to the Makefile.
=> fix(gcp_chronicle sink): add run_and_assert_sink_error to unhappy path test

lib/vector-buffers/src/topology/channel/receiver.rs, lib/vector-common/src/finalizer.rs, lib/vector-common/src/shutdown.rs, lib/vector-core/src/stream/batcher/mod.rs, lib/vector-core/src/stream/concurrent_map.rs, lib/vector-core/src/stream/driver.rs, lib/vector-core/src/stream/partitioned_batcher.rs, lib/vector-core/src/tls/incoming.rs, src/sink.rs, src/sinks/aws_cloudwatch_logs/request.rs, src/sinks/aws_cloudwatch_logs/service.rs, src/sinks/pulsar.rs, src/sinks/splunk_hec/common/service.rs, src/sinks/util/adaptive_concurrency/future.rs, src/sinks/util/adaptive_concurrency/semaphore.rs, src/sinks/util/adaptive_concurrency/service.rs, src/sinks/util/http.rs, src/sinks/util/normalizer.rs, src/sinks/util/retries.rs, src/sinks/util/service/health.rs, src/sinks/util/sink.rs, src/sinks/util/socket_bytes_sink.rs, src/sinks/util/udp.rs, src/sources/kubernetes_logs/lifecycle.rs, src/test_util/mod.rs, src/utilization.rs
Rust 1.64 [stabilized
`std::task::ready!`](https://doc.rust-lang.org/stable/std/task/macro.ready.html) which is an equivalent macro to `futures::ready!`, so prefer the `std` version.
=> chore: Use `std::task::ready!` instead of `futures::ready!`

lib/vector-common/src/shutdown.rs, lib/vector-core/src/stream/driver.rs, src/sinks/socket.rs, src/sinks/splunk_hec/common/service.rs, src/sinks/websocket/sink.rs
Rust 1.64 [stabilized
`std::future::poll_fn`](https://doc.rust-lang.org/stable/std/future/fn.poll_fn.html), so prefer the `std` version.
=> chore: Use `std::future::poll_fn` instead of `futures::future::poll_fn`

lib/vector-common/src/internal_event/mod.rs, lib/vector-core/src/stream/driver.rs, src/sinks/amqp/service.rs, src/sinks/aws_cloudwatch_logs/service.rs, src/sinks/aws_kinesis_firehose/service.rs, src/sinks/aws_kinesis_streams/service.rs, src/sinks/aws_sqs/service.rs, src/sinks/azure_common/config.rs, src/sinks/datadog/events/service.rs, src/sinks/datadog/logs/service.rs, src/sinks/datadog/metrics/service.rs, src/sinks/datadog/traces/service.rs, src/sinks/elasticsearch/service.rs, src/sinks/gcs_common/service.rs, src/sinks/kafka/service.rs, src/sinks/loki/service.rs, src/sinks/new_relic/service.rs, src/sinks/s3_common/service.rs, src/sinks/splunk_hec/common/response.rs, src/sinks/vector/service.rs
This is a small refactoring of sinks to move the creation of the `EventsSent` emitted by the new-style sink driver from the individual sinks into the driver itself. This will assist with setting up the registered `EventsSent` type.
=> chore(sinks): Emit `EventsSent` in driver in new-style sinks

website/content/en/docs/setup/installation/manual/from-source.md
Add description about installing CMake and Protoc on Windows platform. 
Signed-off-by: Rui Li <me@lirui.tech>
=> docs(windows installation) Add CMake and Protoc install

src/sinks/gcp/pubsub.rs, src/sources/gcp_pubsub.rs
Ref #14637 
This updates the error path integration test to call `run_and_assert_sink_error`. Luckily, the test still passes so no further changes were needed.
=> fix(gcp_pubsub sink): Add `run_and_assert_sink_error` to integration test

website/content/en/docs/about/under-the-hood/architecture/_index.md, website/content/en/docs/about/under-the-hood/architecture/buffering-model.md, website/cue/reference/components/sinks.cue, website/cue/reference/urls.cue
This PR adds an initial version of docs about Vector's buffering capabilities: why we buffer, the types of buffers available, the various buffering behaviors, and recommended configurations based on common use cases.
I've also tweaked the common buffering block used by sinks to adjust both the format and to be more inline with the described buffer implementation details/behavior in the new docs.
=> chore(docs): add initial version of buffering docs

src/sinks/elasticsearch/integration_tests.rs
The ElasticSearch integration tests were failing because a recent merge allowed multiple endpoints to be specified. One of the tests was asserting that only a single endpoint was parsed from the config. This was now failing because some tests specified multiple endpoints.
I have removed the call to check for a single endpoint for these tests.
=> fix(elasticsearch sink): don't assert a single endpoint for tests with multiple endpoints

website/cue/reference/components/sinks.cue, website/cue/reference/releases/0.22.0.cue
As stated in the title.
Specifically, #14617 made it look like this: https://deploy-preview-14617--vector-project.netlify.app/docs/reference/configuration/sinks/aws_s3/#buffer
This PR makes it look like this: https://deploy-preview-14664--vector-project.netlify.app/docs/reference/configuration/sinks/aws_s3/#buffer
=> chore(docs): fix a broken link in the sink buffer docs + spelling error in upgrade notes

Cargo.lock, lib/codecs/Cargo.toml, lib/vrl/stdlib/Cargo.toml
Closes #14651 
This updates the `syslog_loose` parser so it doesn't panic when parsing invalid dates (such as Feb 29 2022).
The PR in `syslog_loose` that fixes this can be seen [here](https://github.com/StephenWakely/syslog-loose/pull/19).
=> fix(syslog source): don't panic on invalid dates

website/cue/reference/components/aws.cue
* Remove `AWS_CREDENTIAL_EXPIRATION` reference which seems to be a leftover from Rusoto migration.
* Remove warning about credentials process now that it's [implemented](https://github.com/awslabs/smithy-rs/pull/1356) in the SDK. Confirmed in `0.24.1`
```
2022-10-01T07:43:17.176046Z DEBUG send_operation{operation="HeadBucket" service="s3"}:provide_credentials{provider=default_chain}:load_credentials{provider=Profile}:load_credentials_file: aws_config::profile::parser::source: config file loaded path=~/.aws/credentials size=175
2022-10-01T07:43:17.176214Z  INFO send_operation{operation="HeadBucket" service="s3"}:provide_credentials{provider=default_chain}:load_credentials{provider=Profile}: aws_config::profile::credentials: constructed abstract provider from config file chain=ProfileChain …
```
=> docs: Update AWS documentation

src/sources/file_descriptors/mod.rs
=> fix(stdin source): Avoid blocking `vector validate` on input

website/content/en/docs/about/under-the-hood/architecture/concurrency-model.md
Noticed by https://github.com/vectordotdev/vector/commit/c69081153841e1bfcee3a59a02f867036616e26e#r85543345
=> docs: Re-add concurrency diagram

src/internal_events/grpc.rs, src/internal_events/mod.rs, src/sources/util/grpc/decompression.rs
Ref #14501 
This emits errors when an error occurs in the grpc server used by the Vector and OpenTelemetry sources.
=> fix(vector source,opentelemetry source): emit errors on grpc errors

Cargo.lock, lib/vector-api-client/Cargo.toml, lib/vector-api-client/src/gql/tap.rs, src/list.rs, src/tap/mod.rs
No more usage of the problematic `value_parser`, the `buffer_perf` example isn't using derive and is happy - manually tested.
```shell
vector on  spencer/fix-more-clap-v4-changes is 📦 v0.25.0 via 🦀 v1.64.0
❯ rg 'value_parser'
lib/vector-buffers/examples/buffer_perf.rs
151:                    .value_parser(["disk-v1", "disk-v2", "in-memory"])
website/content/en/highlights/2022-05-03-0-22-0-upgrade-guide.md
165:- `key_value_parser`
370:##### `key_value_parser`
375:[transforms.key_value_parser]
376:type = "key_value_parser"
383:[transforms.key_value_parser]
website/content/en/highlights/2022-08-16-0-24-0-upgrade-guide.md
170:- `key_value_parser`
website/content/en/highlights/2021-02-16-0-12-upgrade-guide.md
107:* …
```
=> fix(cli): fix another couple panics caused by the clap v4 upgrade

src/internal_events/file_descriptor.rs, src/internal_events/mod.rs, src/sources/file_descriptors/file_descriptor.rs, src/sources/file_descriptors/mod.rs, src/sources/file_descriptors/stdin.rs
Ref #14503 
This wraps the error path test in a `assert_source_error` call. The test failed so it also fixes it to emit an error when it occurs.
=> fix(stdin source): emit event on error

src/sinks/datadog/metrics/encoder.rs
This PR reintroduces the logic to differentiate rate metrics and count metrics in the `datadog_metrics` sink. This was a regression introduced in #13960.
We also now have a unit test making sure this is handled correctly, so hopefully no more regressions by yours truly, or anyone, as far as rate metrics go. 🤞🏻 😅 
Fixes #14740.
=> fix(datadog_metrics sink): properly encode rate metrics

src/transforms/lua/v1/mod.rs, website/content/en/highlights/2022-10-04-0-25-0-upgrade-guide.md, website/cue/reference/components/transforms/lua.cue
=> chore(lua transform): Add deprecation notice for version 1 API

website/content/en/docs/administration/management.md, website/content/en/docs/setup/installation/operating-systems/archlinux.md, website/content/en/docs/setup/installation/operating-systems/centos.md, website/content/en/docs/setup/installation/operating-systems/debian.md, website/content/en/docs/setup/installation/operating-systems/macos.md, website/content/en/docs/setup/installation/operating-systems/nixos.md, website/content/en/docs/setup/installation/operating-systems/raspbian.md, website/content/en/docs/setup/installation/operating-systems/rhel.md, website/content/en/docs/setup/installation/operating-systems/ubuntu.md, website/content/en/docs/setup/installation/operating-systems/windows.md, website/content/en/docs/setup/installation/package-managers/apt.md, website/content/en/docs/setup/installation/package-managers/dpkg.md, website/content/en/docs/setup/installation/package-managers/pacman.md, website/content/en/docs/setup/installation/package-managers/rpm.md, website/content/en/docs/setup/installation/package-managers/yum.md
With the next version (since 0.24.1 isn't building for me, but master is) Vector will be available in the Arch Linux community repository.
Current [PKGBUILD](https://man.archlinux.org/man/PKGBUILD.5) file in development: https://fb.hash.works/tIUPCi/
I wasn't sure about the weights, I figured you wanted stuff to be sorted alphabetically?
=> docs(setup): Add pacman / Arch Linux

Cargo.lock, lib/vrl/web-playground/Cargo.toml, lib/vrl/web-playground/index.html
Closes https://github.com/vectordotdev/vector/issues/14657
Closes https://github.com/vectordotdev/vector/issues/14712
Added three monaco editors one for the program, the event, and the output.
Added a button to get the content of the program and event to pass to `run_vrl()` parse the output and print it in the output monaco editor.
The above image showcases the current state of the three editors and how they can be used to run vrl code.
Recently pushed out a commit that adds the state of the web playground to the URL encoded into base64.
Example:
A state of
```javascript
{
"program": ".message2 = \"something here\"",
"event": {
"message": "<102>1 2020-12-22T15:22:31.111Z vector-user.biz su 2666 ID389 - Something went wrong"
}
}
```
Generates the URL …
=> feat(vrl): Add MVP web UI to run VRL program without access to browser console

src/sources/heroku_logs.rs, src/sources/http.rs, src/sources/http_scrape/integration_tests.rs, src/sources/http_scrape/scrape.rs, src/sources/http_scrape/tests.rs, src/sources/prometheus/remote_write.rs, src/sources/prometheus/scrape.rs, src/sources/util/http/method.rs, src/sources/util/http/mod.rs, src/sources/util/http/prelude.rs, src/sources/util/http_scrape.rs, src/sources/util/mod.rs, website/cue/reference/components/sources/http_scrape.cue
This PR partially resolves https://github.com/vectordotdev/vector/issues/14676
I have enabled only GET and POST methods like the most reasonable. Other methods could be enabled quite easily later if will be a need in it (just extend corresponding enum and update the documentation). This is the reason, why `HttpMethod` enum was copied from `http` source - they support different set of HTTP methods and I see no need to support in both sources equal set of HTTP methods.
=> feat(http): add custom method support to http_scrape source

lib/vector-core/src/event/metric/mod.rs, lib/vector-core/src/event/metric/series.rs, lib/vector-core/src/event/vrl_target.rs
closes https://github.com/vectordotdev/vector/issues/14693
Previously assigning to `.tags` of a metric would only append tags. Now it overwrites instead.
=> fix(vrl): Fix `target_insert` for metric tags

src/internal_events/splunk_hec.rs
Closes #14212.
Part of #13995.
=> enhancement(splunk_hec_logs sink): Comply to `*EventsDropped` instrumentation spec in `splunk_hec_logs` sink

src/internal_events/splunk_hec.rs
Closes #14213.
Part of #13995.
=> enhancement(splunk_hec_metrics sink): Comply to `*EventsDropped` instrumentation spec in `splunk_hec_metrics` sink

src/sources/splunk_hec/mod.rs
Ref: #14505 
This adds a call to `assert_source_error` in the unhappy path test to ensure the correct error events are emitted.
Fortunately the test passed, so no further changes were needed.
=> fix(splunk_hec source): add assert_source_error to error path test

website/content/en/docs/reference/vrl/examples.md
Examples will most closely match real-world usage vs. copying into the REPL where the behavior can
diverge due to differences like known type information or lack of support for unicode escape
sequences.
=> docs(vrl): Clarify passing in example data via `vector vrl`

src/internal_events/amqp.rs, src/internal_events/apache_metrics.rs, src/internal_events/aws_cloudwatch_logs.rs, src/internal_events/aws_ec2_metadata.rs, src/internal_events/codecs.rs, src/internal_events/common.rs, src/internal_events/docker_logs.rs, src/internal_events/eventstoredb_metrics.rs, src/internal_events/exec.rs, src/internal_events/gcp_pubsub.rs, src/internal_events/journald.rs, src/internal_events/kafka.rs, src/internal_events/kubernetes_logs.rs, src/internal_events/postgresql_metrics.rs, src/internal_events/process.rs, src/internal_events/prometheus.rs, src/internal_events/pulsar.rs, src/internal_events/socket.rs, src/internal_events/udp.rs, src/internal_events/unix.rs, src/internal_events/websocket.rs, src/internal_events/windows.rs
This adds a `internal_log_rate_limit = true` to a bunch of `error!` calls in internal_metrics that were missing them.
=> fix(observability): add internal_log_rate_limit to `error!` calls

lib/vrl/stdlib/src/parse_key_value.rs
Closes #14630 
This fixes an issue where a tab could not be used as a delimiter in `parse_key_value`. 
The issue was caused because it was looking for the delimiter with:
```rust
preceded(space0, tag(field_delimiter))(input)     
```
`space0` consumes tab characters as well as spaces, so the `tag(field_delimiter)` was not finding the tab.
This PR changes `space0` to `many0(tag(" "))` which searches exclusively for spaces and not tabs.
=> fix(vrl): allow tabs to be used as delimiter in parse_key_value

src/sinks/aws_cloudwatch_metrics/mod.rs, src/sinks/aws_kinesis_firehose/service.rs, src/sinks/aws_kinesis_streams/service.rs, src/sinks/aws_sqs/service.rs, src/sinks/azure_common/service.rs, src/sinks/elasticsearch/service.rs, src/sinks/gcs_common/service.rs, src/sinks/prometheus/remote_write.rs, src/sinks/redis.rs, src/sinks/s3_common/service.rs, src/sinks/util/udp.rs, src/sinks/vector/service.rs
Closes #14215.
Part of #13995.
Emitting an error when the sink fails is handled in the service driver: https://github.com/vectordotdev/vector/blob/5149fef19f249b9990803c68c3b3a615abc063ac/lib/vector-core/src/stream/driver.rs#L123
=> enhancement(vector sink): Comply to `*EventsDropped` instrumentation spec in `vector` sink

lib/vrl/compiler/src/expression/function_call.rs, lib/vrl/tests/tests/issues/14796_closure_type_def.vrl
closes https://github.com/vectordotdev/vector/issues/14796
Small fix for closures. The block type of a closure was being recalculated after the closure parameters were removed from the type. The correct type already exists, so that one is used instead.
=> fix(vrl): fix closure block type calculation

src/sources/amqp.rs
I did a quick audit on the usage of the `EventsReceived` internal event in our sources.
The `amqp` source reports the byte size of the incoming frame, rather than our calculation of the event byte size.
=> fix(amqp source): Fix `byte_size` in `EventsReceived` internal event in `amqp` source

src/internal_events/socket.rs
This origined from a bad merge in #14511 I did on top of #14765.
=> chore(socket source): Fix duplicate `internal_log_rate_limit` attribute

website/cue/reference/configuration.cue
I _swear_ this wasn't rendering when I made the PR adding this line but...
=> docs: Remove extra deprecation warning

src/sinks/aws_s3/config.rs, src/sinks/aws_s3/integration_tests.rs, src/sinks/aws_s3/sink.rs, src/sinks/datadog_archives.rs, src/sinks/s3_common/config.rs, src/sinks/s3_common/mod.rs, src/sinks/s3_common/partitioner.rs, src/sinks/s3_common/service.rs, src/sinks/s3_common/sink.rs
Closes #12099
Adds a new composite key for partitioning that includes ssekme_key_id with templating as requested by https://github.com/vectordotdev/vector/issues/12099
=> enhancement(aws_s3 sink): Template support for ssekms_key_id

src/internal_events/datadog_traces.rs, src/sinks/datadog/traces/stats.rs
Adds this missing logic:
https://github.com/DataDog/datadog-agent/blob/cfa750c7412faa98e87a015f8ee670e5828bbe7f/pkg/trace/stats/concentrator.go#L211-L214
Also reverted the Error emission based on user feedback- that Error is being fired all the time, and so reverted it back to debug log and created an issue to track that.
The issue is here: https://github.com/vectordotdev/vector/issues/14859
, and in it I've included the logic for the `Error` internal event so it doesn't have to be re-created.
=> fix(datadog_traces sink): Add more missing APM stats logic , temporarily replace Error with debug log

src/sinks/prometheus/exporter.rs
This uses the `retain` function to handle expiring metrics instead of building a vec of metrics to remove. It also switches the insert process to using the `entry` API to avoid accessing the hash twice on insert.
=> chore(prometheus_exporter sink): Small tweaks to event processing

lib/value/src/value/serde.rs, lib/vector-core/src/event/test/mod.rs, src/api/schema/events/log.rs, src/sinks/aws_kinesis_streams/sink.rs, src/sinks/datadog/traces/request_builder.rs, src/sinks/datadog/traces/sink.rs, src/sinks/datadog/traces/stats.rs, src/sinks/elasticsearch/config.rs, src/sinks/influxdb/logs.rs, src/sinks/loki/sink.rs, src/sinks/papertrail.rs, src/sinks/splunk_hec/logs/encoder.rs, src/sinks/vector/mod.rs, src/sources/aws_sqs/integration_tests.rs, src/sources/docker_logs.rs, src/sources/file.rs, src/sources/file_descriptors/file_descriptor.rs, src/sources/file_descriptors/stdin.rs, src/template.rs, src/test_util/mock/transforms/basic.rs, src/topology/test/mod.rs, src/transforms/log_to_metric.rs, src/transforms/remap.rs
This allows for lossless bytes-to-utf8 conversions, as well as regex references and `Null`, to return without allocating a copy of the data.
This is mostly tech debt, found when working on pre-parsing template strings, but it could end up being a small performance lift.
=> chore(core): Change `Value::to_string_lossy` to return `Cow`

lib/vrl/web-playground/index.html, lib/vrl/web-playground/src/lib.rs
Closes https://github.com/vectordotdev/vector/issues/14659
Current iteration for printing out diagnostic messages while attempting to setup a more complex structure to eventually add severity, contains_warnings, etc as fields for future use. 
This will print out the diagnostic message in the existing output box but without using xterm.js as I found using the uncolorized field will satisfy the requirement and reduce complexity of introducing another library. 
If feedback is to add colorization then we can support that by adding the xterm.js console window.
=> feat(vrl): Display VRL diagnostic messages in web UI

soaks/tests/syslog_log2metric_humio_metrics/vector.toml, soaks/tests/syslog_log2metric_splunk_hec_metrics/vector.toml, soaks/tests/syslog_regex_logs2metric_ddmetrics/vector.toml
The soak tests that use a `log_to_metric` transform have a trivial configuration that don't exercise many of the features of the transform. This change adds a set of tags to all of these transforms that use template substitution to generate dynamic tags, this increasing the complexity and exercising more code paths.
This will be used to check the impact of #14902 and #14908
=> chore(soak tests): Add templated tags to log2metric soaks

src/api/tap.rs, src/transforms/log_to_metric.rs
While I was looking at `log_to_metric` for #14902, it seemed there was a lot of repetitive config and code in this transform. Rather than tack it on to the previous PR, I split it out to make it easier to review.
@tobz I'm assuming there should be something more intelligent said in the config commentary, but the rendered docs on this one are so far from the existing Cue that I have no idea what "better" looks like here.
=> chore(log_to_metric transform): Unify common config and render bits

.github/workflows/soak_comment.yml
https://github.com/actions/github-script/releases/tag/v5.0.0 broke this with the SDK upgrade since
the functions are further namespaced.
Fixes: #14868
=> fix(ci): Use new interface in soak test comment posting

website/cue/reference/components/kafka.cue, website/cue/reference/urls.cue
Ref #4261
This adds documentation to the kafka source and sink to advise on how to use these components to connect to Azure event hubs.
=> docs(kafka source, kafka sink): added docs for using kafka components with Azure Event Hubs

src/sources/http_client/client.rs
Closes #14978
Standardizing on `Bytes::from` in the log namespacing feature, and removed extra qualification.
=> chore(http_client source): Small cleanup on existing log namespace feature

src/sinks/axiom.rs, src/sinks/elasticsearch/common.rs, src/sinks/elasticsearch/config.rs, src/sinks/elasticsearch/integration_tests.rs, src/sinks/elasticsearch/mod.rs, src/sinks/elasticsearch/tests.rs, src/sinks/sematext/logs.rs, website/cue/reference/components/sinks/elasticsearch.cue
Reverts vectordotdev/vector#14918
This is causing soak tests to fail because lading doesn't respond correctly to the version endpoint. This fact also highlights that the PR being reverted could be considered a "breaking change" so, before we re-introduce it, we should decide to either preserve compatibility (default to `v7`) or make the breaking change and add an upgrade note to the next release so that users know to expect it.
cc/ @ktff
=> fix(elasticsearch sink): Revert add `api_version` option

src/api/schema/metrics/host.rs, src/sources/host_metrics/disk.rs, src/sources/host_metrics/filesystem.rs, src/sources/host_metrics/memory.rs, src/sources/host_metrics/mod.rs, src/sources/host_metrics/network.rs
We have used both `cfg(windows)` and `cfg(target_os = "windows")` in a number of places. This picks the simpler form, which is equivalent to `cfg(target_family = "windows")` and related to `cfg(unix)` which we also use.
=> chore: Standardize on `cfg(windows)`

Cargo.lock, Cargo.toml, src/aws/mod.rs
=> chore(deps): Upgrade AWS SDK crates to 0.21.0 and Smithy to 0.51.0

Cargo.lock, Cargo.toml
Now that 0.29.0 has been published there per https://github.com/fede1024/rust-rdkafka/issues/478#issuecomment-1295925976
=> chore(deps): Switch rdkafka back to crates.io

.github/workflows/integration-test.yml, .github/workflows/soak.yml
Discovered these ones hanging recently for the full 6 hours.
=> chore(ci): Add timeouts to CI jobs that hung recently

src/transforms/throttle.rs
ref: https://github.com/vectordotdev/vector/issues/15031
This one is very simple. The events are just passed through as-is, so the existing schema definition is used
=> chore(throttle transform): add log namespace support to throttle transform

README.md
Issue labels seem to have been renamed from `Type: New Feature` to `type: feature` at some point, breaking this link
=> docs: Fix roadmap voting link in readme

lib/vector-core/src/config/mod.rs
This adds `get_source_metadata` and `get_vector_metadata` functions on `LogNamespace` to make it easier to fetch information where the location depends on the log namespace.
=> chore(core): add `LogNamespace` getter functions

scripts/ci-generate-publish-metadata.sh
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore(ci): Update usages of deprecated set-output in Github Actions

.github/workflows/regression.yml
To improve maintainability of the `smp`-based regression detector, this pull request moves the `smp` crate version into an output variable of the `compute-metadata` job. This change will make changing the `smp` crate version in the regression workflow easier when needed (e.g., when adding analysis from `smp`).
Signed-off-by: Geoffrey M. Oxberry <geoffrey.oxberry@datadoghq.com>
=> refactor(ci): move smp crate version to variable

scripts/ci-generate-publish-metadata.sh
Fixes some missing bit from this change:
https://github.com/vectordotdev/vector/commit/3b7916b82e28979a1121508f1926164fe03f60e9
which was done to address this:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
$ make ci-generate-publish-metadata         
vector_version::0.25.0
vector_build_desc::86bd9202a 2022-11-02
vector_release_channel::nightly
vector_cloudsmith_repo::vector-nightly
```
```
$ GITHUB_OUTPUT=/tmp/gh-output.out make ci-generate-publish-metadata 
$ cat /tmp/gh-output.out 
vector_version::0.25.0
vector_build_desc::86bd9202a 2022-11-02
vector_release_channel::nightly
vector_cloudsmith_repo::vector-nightly
```
=> fix(ci): fix issues in ci-metadata-script

.github/workflows/regression.yml, regression/cases/splunk_hec_route_s3/lading/lading.yaml, regression/cases/splunk_hec_route_s3/vector/vector.toml
This pull request updates the Regression workflow to analyze results from regression experiments using `smp`. To do so, it makes the following changes:
* Updates the `smp` crate version from 0.3.0 to 0.5.0.
* Updates flags as needed in the `smp job submit` and `smp job cancel` invocations.
* Uncomments the analysis job @blt set up, and adds a couple steps to post regression reports to PR comments.
h/t and thanks go to @blt & @GeorgeHahn for making the setup process easy, and many thanks to y'all for your patience and for being early adopters!
=> feat(ci): add analysis from smp to regression workflow

.github/workflows/regression.yml
It is possible that two PRs with working with the same baseline SHA can push the same tag up to ECR. Today this will silently pollute one PR experiment set. In the future this will cause an error that terminates the workflow. To correct this we include the unique PR number in the image tag.
=> fix(ci): Include PR number in the regression target tag

lib/codecs/src/decoding/format/bytes.rs, lib/codecs/src/decoding/format/gelf.rs, lib/codecs/src/decoding/format/syslog.rs, lib/vector-core/src/schema/definition.rs, lib/vector-core/src/schema/requirement.rs, src/sources/datadog_agent/tests.rs, src/topology/schema.rs, src/transforms/aws_ec2_metadata.rs, src/transforms/remap.rs
ref: https://github.com/vectordotdev/vector/issues/15031
There were 2 main changes:
- The schema definition was updated with the enrichment data. (all optional)
- `Definition::with_field` was renamed to `Definition::with_event_field` to more closely match the naming of `Definition::with_metadata_field`. A new `Definition::with_field` was added that can set a field on either the event or metadata.
=> chore(aws_ec2_metadata transform): add log namespace support to `aws_ec2_metadata` transform

soaks/tests/http_pipelines_blackhole/vector.toml, soaks/tests/http_pipelines_blackhole_acks/vector.toml, soaks/tests/http_pipelines_no_grok_blackhole/vector.toml
We currently set the event to null when the initial ```parse_json``` fails.
=> fix(soak tests) Fix http pipelines soak tests

src/app.rs
Resolves https://github.com/vectordotdev/vector/issues/11944
Just a small fix: report an error to stderr instead of built-in logging based on tracing.
Tested locally - works fine.
=> fix(config): error message with threads=0

src/sources/internal_metrics.rs, website/cue/reference/components/sources/base/internal_metrics.cue, website/cue/reference/components/sources/internal_metrics.cue
Resolves https://github.com/vectordotdev/vector/issues/13143
Change default scrape_interval to 1 second.
Tested:
- Local build
=> fix(internal_metrics): change default scrape_interval to 1

lib/vector-core/src/schema/definition.rs, src/sources/aws_s3/mod.rs, src/sources/datadog_agent/mod.rs
The type of the optional `legacy_key` in some helper functions was changed from `Option<LegacyKey<&OwnedValuePath>>` to `Option<LegacyKey<OwnedValuePath>>`. The reference made it hard to use in practice. The reference isn't really necessary. Since this code only runs at startup, an extra clone is easier.
Here is an example from the redis source to get a `legacy_key` value now:
(`self.redis_key` is `Option<String>`)
```rust
let redis_key_path = self
.redis_key
.as_ref()
.map(|x| owned_value_path!(x))
.map(LegacyKey::InsertIfEmpty);
```
=> chore(core): Remove reference from `LegacyKey` usage to make it easier to use

.github/workflows/regression.yml, .github/workflows/regression_trusted.yml
This commit splits the regression flow into an untrusted pull_request event triggered flow and a trusted workflow_run event triggered flow. This accomplishes the same basic goal as the existing workflow run excepting that we do not require the PR contributor to have access to project secrets, meaning that dependabot, open-source contributors et al will be able to participate in the regression detector.
This commit brings the regression detector up to feature parity with the soak tests. Because of the nature of the workflow_run this PR will not post regression detector results: the workflow_run must be present in `master` branch before it will kick on. I had originally intended to split this work into two PRs but decided against this as landing the `regression_trusted.yml` separately would …
=> fix(ci): Introduce trusted/untrusted regression workflow split

.github/workflows/regression_trusted.yml
In #15142 we introduced the split between the trusted and untrusted regresison detector workflow. Unfortunately the trusted side can only be tested once it's merged into master branch and we had a bug. The github-scripts that download artifacts referenced `github.actions.rest` when it should have read `github.rest.actions`.
Please note that because of the nature of workflow_run triggered workflows this change will not be reflected in the PR's workflow runs.
=> fix(ci): Correct github.actions.rest to github.rest.actions

.github/workflows/regression_trusted.yml
Dependabot-originated PRs should be able to post comments with the new trusted/untrusted workflow split.
Previously: #15142
cc: @blt
=> fix(ci): Remove dependabot restriction from comment step

lib/vector-core/src/metrics/recorder.rs
Const init the thread locals based on the work here: rust-lang/rust#83416
=> enhancement(core): const init thread locals

src/internal_events/remap.rs
And so shouldn't log errors.
Closes: #15160
=> fix(remap transform, observability): `abort` is an intentional drop

src/config/builder.rs, src/sources/amqp.rs, src/sources/aws_s3/mod.rs, src/sources/datadog_agent/mod.rs, src/sources/demo_logs.rs, src/sources/http_client/client.rs, website/cue/reference/components/sources/base/amqp.cue, website/cue/reference/components/sources/base/aws_s3.cue, website/cue/reference/components/sources/base/datadog_agent.cue, website/cue/reference/components/sources/base/demo_logs.cue, website/cue/reference/components/sources/base/http_client.cue
Hiding this field until we are ready to release it.
=> fix(docs): Hide the `log_namespace` option

lib/lookup/src/lookup_v2/mod.rs, lib/lookup/src/lookup_v2/optional_path.rs
An `OptionalTargetPath` already existed, which allows setting a path to empty string to disable setting that field. This is the same thing, but for paths without a target.
=> chore(core): Add `OptionalValuePath`

lib/lookup/src/lookup_v2/owned.rs, lib/value/src/kind/collection.rs, lib/value/src/kind/collection/field.rs, lib/value/src/kind/collection/index.rs, lib/value/src/kind/collection/unknown.rs, lib/value/src/kind/comparison.rs, lib/vector-core/src/event/log_event.rs, lib/vector-core/src/event/metadata.rs, lib/vector-core/src/schema/definition.rs, lib/vector-core/src/schema/requirement.rs, lib/vrl/compiler/src/expression/function_call.rs, lib/vrl/compiler/src/expression/op.rs, lib/vrl/compiler/src/type_def.rs
`schema::Definition::assert_valid_for_event` was added as an easy way to validate that a schema definition is valid for a specific event. This can easily be added to integration tests, or any test where you already have valid events, and the associated schema definition.
`assert_valid_for_event` will panic is the event doesn't match, and print out debug information.
`is_valid_for_event` is available if you don't want a panic. It will still give the debug info as a `String`.
Both of these functions are only available in tests. They are available in `vector-core` when running tests, or in any other crate by enabling the `test` feature of `vector-core` in `dev-dependencies` (which many crates do already).
=> chore(core): add schema definition test utility

website/config.toml
Clean up privacy links.
- Remove Privacy link from meta menu sidebar
- Add Privacy link in footer (to datadoghq.com/privacy)
- Remove unused `menus.subfooter` data
Looking at the docs site, see that "Privacy" is no longer in the Meta sidebar menu, but in the footer (Links to datadoghq.com)
https://deploy-preview-15194--vector-project.netlify.app/docs/
=> chore(template website): Clean Up Privacy Links

lib/vector-core/src/event/metric/series.rs, lib/vector-core/src/event/metric/tags.rs, lib/vector-core/src/event/vrl_target.rs, src/api/schema/events/metric.rs, src/sinks/aws_cloudwatch_metrics/mod.rs, src/sinks/datadog/metrics/encoder.rs, src/sinks/gcp/stackdriver_metrics.rs, src/sinks/influxdb/mod.rs, src/sinks/prometheus/collector.rs, src/sinks/prometheus/remote_write.rs, src/sinks/s3_common/service.rs, src/sinks/splunk_hec/metrics/encoder.rs, src/sinks/statsd.rs, src/transforms/tag_cardinality_limit.rs
The `MetricTags` implementation has a single implementation of iteration over its values that previously only had single-valued results, but now has multi-valued results. These new semantics are unsuitable for most current uses of metric tags, so separate these out into iterating over tags with a single value and interating over all values of all tags.
Epic: #14742
=> chore(metrics): Separate out iterating over single and multi-value tags

src/sources/amqp.rs, src/sources/aws_s3/sqs.rs
=> chore: Cleanup match used for legacy timestamp handling

.github/workflows/regression_trusted.yml
The trusted side of the regression detector flow accidentally did not have parity with the soak tests, leading to an observable difference in results in some PRs, notably #14984. One such accidental lack of parity we repair in this PR: ensure that the soak's environment variables are passed just the same in the Regression Detector.
Please note that the changes made here will not take effect until they are merged into `master`. 
=> fix(ci): Pass the same environment variables in Regression Detector as Soak

.github/workflows/regression_trusted.yml
I find the Github API confusing, especially around Github Actions. Which pieces map to what parts of their UI, what works in concert implicitly and what do not is hard -- for me -- to understand. Fun fact, if you want to protect a branch you need a 'commit status' and that is separate from a 'check' although they are often both created at the same time, automatically? A "check run" is a single line-item in a "check suite" but is not a commit status and cannot gate a branch change, also a 'run' cannot be placed easily in a 'suite' per [this conversation](https://github.com/orgs/community/discussions/24616).
This commit adjusts the Regression Detector to use only commit statuses. We are now able to link to the triggered workflow and can also set branch protection based on the status. We are …
=> fix(ci): Use commit statuses, not checks in Regression Detector workflow

website/cue/reference/components/sinks/base/aws_kinesis_streams.cue, website/cue/reference/components/sources/base/dnstap.cue, website/cue/reference/components/sources/base/socket.cue
Some PRs got through with out-of-sync machine-generated Cue documentation files before the new CI check added in #15162 was merged in, which is now leading to `master` failing -- rightfully so -- as there is an out-of-sync issue.
This PR simply updates those files.
=> chore(docs): synchronize machine-generated Cue documentation

lib/vrl/core/src/expression.rs, lib/vrl/diagnostic/src/diagnostic.rs, lib/vrl/vrl/src/runtime.rs, lib/vrl/web-playground/public/index.css, lib/vrl/web-playground/public/index.html, lib/vrl/web-playground/src/lib.rs
Closes https://github.com/vectordotdev/vector/issues/15176
Closes https://github.com/vectordotdev/vector/issues/15128
Closes https://github.com/vectordotdev/vector/issues/14713
- added JSONL support by using the monaco API
- added helpful error messages if JSON.parse() fails when reading input from event editor
- implemented styling recommendations from Jean's comments mentioned in issue linked above
- changed language highlighting to coffeescript
- changed layout when viewing from a mobile device
- fixed bug with `atob` and `btoa` failing when reading the base64 string from url params (we needed to use URIEncode and URIDecode)
Mobile device:
Edit:
Addressed comments below and also added formatted diagnostic messages from runtime errors or aborts.
We also handle runtime errors:
=> feat(vrl): Polish web playground

src/sinks/azure_blob/config.rs
`azure_common::config::build_client` requires a String not a SensitiveString, in the conversion using to_string() we were accidentally converting to the sensitive value to `**REDACTED**`.
This fixes it by using the same method that seems to have been used in the PR that introduced this change: https://github.com/vectordotdev/vector/pull/14305 to call `.inner()` to retrieve the value from inside the struct and then converts that to a String.
Closes: #15214
Related:
- https://github.com/vectordotdev/vector/discussions/15170
=> fix(azure service)!: Retrieve .inner() from SensitiveString for Azure ConnectionString

lib/vector-config/src/num.rs, lib/vector-config/src/schema.rs, scripts/generate-component-docs.rb, website/cue/reference/components/sinks/base/aws_cloudwatch_logs.cue, website/cue/reference/components/sinks/base/aws_cloudwatch_metrics.cue, website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue, website/cue/reference/components/sinks/base/aws_kinesis_streams.cue, website/cue/reference/components/sinks/base/aws_s3.cue, website/cue/reference/components/sinks/base/axiom.cue, website/cue/reference/components/sinks/base/azure_blob.cue, website/cue/reference/components/sinks/base/clickhouse.cue, website/cue/reference/components/sinks/base/datadog_logs.cue, website/cue/reference/components/sinks/base/datadog_traces.cue, website/cue/reference/components/sinks/base/elasticsearch.cue, website/cue/reference/components/sinks/base/gcp_cloud_storage.cue, website/cue/reference/components/sinks/base/http.cue, website/cue/reference/components/sinks/base/humio_logs.cue, website/cue/reference/components/sinks/base/humio_metrics.cue, website/cue/reference/components/sinks/base/loki.cue, website/cue/reference/components/sinks/base/new_relic.cue, website/cue/reference/components/sinks/base/splunk_hec_logs.cue, website/cue/reference/components/sinks/base/splunk_hec_metrics.cue, website/cue/reference/components/sources/base/dnstap.cue
This PR fixes two small glitches:
- adding (un)signed integer fields to the configuration schema as `number` (which implies floating-point number) instead of `integer`
- generating the incorrect numeric type for numeric values that are part of any "enum" values in a schema
The first thing is simple: JSON Schema supports two numeric type, `integer` and `number`, which represent whole integers (`u32`, `i64`, etc etc) and floating-point numbers, respectively. We were emitting `number` in all cases, even though we had access to the necessary data to properly select either `integer` or `number`. We fixed that with a mere few changed lines.
The second thing, and the thing that represents like 95% of this PR, is fixing the numeric type used to describe numeric values in an "enum" schema. …
=> chore(docs): miscellaneous fixes to generate config schema and derived docs output

.github/workflows/regression.yml
This PR is intended to correct the problem identified in #15230, namely that the Regression Detector is not correctly building baseline variant separately from comparison variant and is instead building two copies of the comparison. This is a consequence of Github Actions' willingness to treat a non-existent 'need' as an empty string and actions/checkout's willingness to treat an empty string as non-existent field.
Quite annoying to debug, relatively simple to fix. We have confirmed the efficacy of this fix in #15287 where we intentionally introduced a break into the comparison side. Note now that in that PR baseline builds as expected, comparison does not.
=> fix(ci): Correct Regression Detector variant checkout

scripts/integration/docker-compose.splunk.yml, src/sinks/splunk_hec/logs/config.rs, src/sinks/splunk_hec/logs/integration_tests.rs, website/cue/reference/components/sinks/base/splunk_hec_logs.cue, website/cue/reference/components/sinks/splunk_hec_logs.cue
As spotted by CI failing. The `auto_extract_timestamp` field only works for version 8 and above of Splunk.
This updates the integration tests to check the Splunk version and not test for version 7. The `SPLUNK_VERSION` environment variable needs passing through to the test.
The docs are updated to point out the setting only works for version 8 and above.
=> fix(splunk_hec sink): auto_extract_timestamp only works for version 8 and above

src/topology/test/reload.rs
When the scrape interval on the `internal_metrics` source is left at the default of 1.0 seconds or less, some kind of race condition in the `topology_disk_buffer_conflict` test is triggered, but it is unclear why. All these tests should work regardless of the scrape interval. This warrants further investigation, but this at least shuts up the flaky test.
This was triggered by #15124
=> chore(topology): Fix flaky `topology_disk_buffer_conflict` test

Cargo.lock, Cargo.toml, lib/codecs/Cargo.toml, lib/opentelemetry-proto/Cargo.toml, lib/prometheus-parser/Cargo.toml, lib/vector-core/Cargo.toml
Closes #15229
Closes #15136 
Closes #15130
=> chore(deps): Bump prost, prost-build, and prost-types to 0.11.2

src/sources/logstash.rs
Adds log namespace and schema def support as described in https://github.com/vectordotdev/vector/pull/13720.
closes: https://github.com/vectordotdev/vector/issues/15026
epic: https://github.com/vectordotdev/vector/issues/13723
=> feat(logstash source): Add log namespace and schema def support

src/sources/aws_s3/sqs.rs
Vector logs an error like this when attempting to handle S3 test events via SQS:
`Could not parse SQS message with id 9447ae6e-d699-4944-940f-d4017230993b as S3 notification: data did not match any variant of untagged enum Event`
The Amazon S3 test event messages is structured like so (https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html) :
```
{  
"Service":"Amazon S3",
"Event":"s3:TestEvent",
"Time":"2014-10-13T15:57:02.089Z",
"Bucket":"bucketname",
"RequestId":"5582815E1AEA5ADF",
"HostId":"8cLeGAmw098X5cv4Zkwcmo8vvZa3eH3eKxsPzbB9wrR+YstdA6Knx4Ip8EXAMPLE"
}
```
This changes the S3 TestEvent struct to match the above by renaming the "event_name" member to "event". I'm not sure if my test case is correct or if I should be testing a specific function / …
=> fix(aws_s3 source): fix s3:TestEvent serialization

lib/vector-core/build.rs
Follow-up to  #15367
, the same flag needs to be added to the `build.rs` for `vector-core`.
Manually tested using `make build-dev`
=> chore(core): allow protobuf building on >=3.12 for vector-core

Cargo.lock, Cargo.toml
The tokio-util patch we have is getting too out of sync with upstream, and it's created conflicts in a contributor PR.
This change updates our usage of the patch.
=> chore(cargo.toml) update `tokio-util` patch to be based on `v0.7.4`

website/cue/reference/components/sources/docker_logs.cue
While adding log namespace support I noticed this enrichment wasn't represented correctly in the documentation. The path was wrong, and the example was a copied from teh message example.
```rust
// Labels.
if !self.metadata.labels.is_empty() {
for (key, value) in self.metadata.labels.iter() {
log_event.insert(
(PathPrefix::Event, path!("label").concat(path!(key))),
value.clone(),
);
}
}
```
=> docs(docker_logs source): Fix example log in docs

src/app.rs, src/cli.rs, src/internal_telemetry/allocations/mod.rs
Allows users to configure the rate at which we report allocation tracking metrics (in milliseconds).
=> enhancement(observability): Configurable reporting rates for tracking allocations. 

.github/workflows/regression_trusted.yml, regression/Dockerfile
This commit updates the `smp` binary to 0.6.2 from 0.5.1, the most relevant change being that we are now able to introduce a 'detect-regression' ding analogue from the soak tests. I have also fixed a bug where cancellation would not correctly signal back to the originating PR.
Please note that this change will not take effect until it is merged into the default branch, owing to the nature of Github Actions' triggers.
=> fix(ci): Update smp binary version, introduce regression detection ding

website/Makefile, website/custom-headers/_preview
This adds a `X-Robots-Tag: noindex` header for deploy previews and branch deploys.
We currently use branch deploys for versioned docs deploys (e.g. https://v0-24.vector.dev/).
I realized while working on this that it uses the same settings for these branch deploys (staging
Algolia index and "preview" environment for the Hugo build). I started down the path to making the
branch deploys more "production like" but this turned into a rabbit hole I thought best to leave for
now and just solve the immediate need of avoiding these sites being indexed.
=> chore(docs): Avoid indexing branch deploys

.github/workflows/regression_trusted.yml
Missed in #15376 we bungled the name of the secret in the detect-regression step. This caused a failure in #15416.
=> fix(ci): Correct secret name in Regression Detector trusted flow

lib/vector-core/src/event/metric/mod.rs
This was initially 0, as any JSON-encoded representation of metrics is not representative of the final shape of metrics as they are delivered by sinks (metrics are often compacted aggressively, as opposed to logs, which are free-form, and thus have to be (mostly) delivered "as-is").
But since this would confuse users by showing up as 0 bytes throughput in the topology for metrics, it is now reporting the in-memory size of metrics.
We might still do an actual JSON-encoded representation of metrics in the future, but this is "good enough" to solve the before-mentioned confusion.
=> chore: use in-memory size for JSON encoded size of metrics

src/list.rs
This change allows callers to check the enrichment tables features the binary was built with.
=> feat(cli): Add enrichment tables to list subcommand

website/content/en/docs/reference/configuration/unit-tests.md
Document how hyphens can be used in unit test input data with an example.
=> docs(unit tests): Document the use of hyphens in key names in input data

website/content/en/docs/reference/configuration/_index.md
A user pointed out the config at the Configuration index had become out of date, which has happened before.
This PR updates all of the examples to be valid as of `v0.26.0`, verified with `vector validate --no-environment` locally.
Longer term we could look into templating a known-good file from our `config/` directory that is validated during CI rather than keep an isolated config directly in the MD.
=> docs: Update config example due to breaking changes

lib/vector-core/src/tls/mod.rs, lib/vector-core/src/tls/settings.rs, src/kafka.rs
Vector's documentation states that it supports both inline PEM-encoded certificates and locations to certificate files.
https://vector.dev/docs/reference/configuration/sinks/kafka/#tls.crt_file
> Absolute path to a certificate file used to identify this connection, in DER or PEM format (X.509) or PKCS#12, or an inline certificate in PEM format. If this is set and is not a PKCS#12 archive, key_file must also be set.
However, for Kafka it works only if a location is provided. Otherwise, the following error occurs:
```
x Sink "destination/cluster/test-kafka-dest": creating kafka producer failed: Client creation error: ssl.certificate.location failed: error:140DC002:SSL routines:use_certificate_chain_file:system lib
```
This happens …
=> fix(kafka): support PEM encoded certificates

src/sources/socket/mod.rs, src/sources/util/net/tcp/mod.rs
`DecodingConfig`s were not being configured with log namespaces, which led to nesting log messages in Vector NS's within a "message" key.
=> fix(socket source): set log namespace in decoder config

.github/workflows/publish.yml
Nightlies are failing to publish recently with:
>  Reason given: A package with architecture ‘amd64’,  distro version ‘any-distro/any-version’,
> name ‘vector’ and package type ‘Binary’ already exists in the ‘timber/vector-nightly:
> vector@0.27.0-1 (vB0T33WkKxiK)’ package. “Replace Package w/ Same Version” was enabled for your
> package. - This package should be deleted.
While looking at this I noticed that the download counts for the nightly packages are typically 0 or
single digits though so I’m inclined to just delete the repository. I don’t think we should really
be overwriting the packages if we did support it, anyway. We should be separately versioning with
a date-based scheme like we do for the docker images.
The nightly packages _are_ available via packages.timber.io. …
=> chore(releasing): Do not publish nightlies to CloudSmith

.github/workflows/regression_trusted.yml
This commit upgrades `smp` to 0.6.5 and lading to 0.11.3. The most salient changes are these:
* `smp` now supports a 'timeout' flag, allowing analysis to proceed even if not all regression replicates are finished
* `lading` fixes an OTEL gRPC bug, which impacted some versions of datadog-agent and Vector
=> feat(ci): Update Regression Detector lading, smp versions

src/components/validation/runner/mod.rs
This PR fixes a bug introduced with the merging of #15140 where the latest `master` was not merged in prior to merging the RFC PR, such that the code in the RFC PR was out of sync with the changes made in #15087.
=> bug(core): fix bug in component validation runner

lib/vrl/stdlib/src/filter.rs, lib/vrl/tests/tests/functions/filter/invalid_input.vrl
The REPL would panic with the input
```coffee
. = ["foo", "bar", null]
["foo", "bar", null]
$ type_def(.)
{ "array": { "0": { "bytes": true }, "1": { "bytes": true }, "2": { "null": true } } }
$ filter(.) -> |_index, value| { is_string(value) }
thread 'main' panicked at 'internal error: entered unreachable code: function requires collection types as input', lib/vrl/stdlib/src/filter.rs:38:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is because the REPL has a "validator" that runs while a user is typing input and it runs the program with a "dummy" event (null) to see if it's valid. The `filter` function will panic with a `null` input.
This changes the function to return an error rather than panic.
A test was also added, although it would not …
=> chore(vrl): remove panic from filter fn

src/sinks/aws_cloudwatch_metrics/mod.rs, website/content/en/highlights/2023-01-17-0-27-0-upgrade-guide.md
Noticed as part of #15522, the Metric API now is documented with a limit of 30 dimensions
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Metric.html
=> feat(aws_cloudwatch_metrics sink): Allow up to 30 metric dimensions

src/sinks/amqp/integration_tests.rs, src/sources/amqp.rs
I also noticed the schema definition was using `LegacyKey::Overwrite` while the insert code had been (and was) using `LegacyKey::InsertIfEmpty` so I matched that behavior.
=> feat(amqp source): Better handling of key configuration with OptionalValuePath

Cargo.lock, lib/vrl/web-playground/public/index.js, lib/vrl/web-playground/public/vrl-highlighter.js
Adds simple syntax highlighting to VRL 
Closes: https://github.com/vectordotdev/vector/issues/15543
I can take suggestions on what colors should be used for each keyword and suggestions on what events should also be highlighted against.
For example:
I think some people might disagree with highlighting `.foo` in
```
.foo = something
```
I'll post example playground links with code so others can test and play with the highlighting.
=> feat(vrl): add syntax highlighting to playground

Cargo.toml, src/aws/auth.rs, src/aws/mod.rs, src/sinks/aws_kinesis/firehose/integration_tests.rs, src/sinks/elasticsearch/integration_tests.rs, website/cue/reference/components/aws.cue, website/cue/reference/components/sinks/base/aws_cloudwatch_logs.cue, website/cue/reference/components/sinks/base/aws_cloudwatch_metrics.cue, website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue, website/cue/reference/components/sinks/base/aws_kinesis_streams.cue, website/cue/reference/components/sinks/base/aws_s3.cue, website/cue/reference/components/sinks/base/aws_sqs.cue, website/cue/reference/components/sinks/base/elasticsearch.cue, website/cue/reference/components/sinks/base/prometheus_remote_write.cue, website/cue/reference/components/sources/base/aws_s3.cue, website/cue/reference/components/sources/base/aws_sqs.cue
If AWS authentication through IMDS request fail, Vector drops the event. This allows users to configure retry attempts & timeout by exposing parameters that is already built-in to the `aws-sdk-rust` library.
New configurable IMDS client parameters for authenticating with AWS
```rust
pub struct ImdsAuthentication {
/// Number of IMDS retries for fetching tokens & metadata
max_attempts: u32,
/// Connect timeout for IMDS, in seconds.
connect_timeout: Duration,
/// Read timeout for IMDS, in seconds.
read_timeout: Duration,
}
```
**Example**
```toml
auth.imds.max_attempts = 5
auth.imds.connect_timeout_seconds = 10
auth.imds.read_timeout_seconds = 10
```
Resolves #14671
=> enhancement(aws config): Make IMDS client configurable for AWS authentication

src/sources/heroku_logs.rs, src/sources/http_server.rs
=> fix(http_server source, heroku_logs source): use configured `LogNamespace` in `DecoderConfig` construction

src/sources/file_descriptors/file_descriptor.rs, src/sources/file_descriptors/mod.rs, src/sources/file_descriptors/stdin.rs
Replace `Option<String>` with `Option<OptionalValuePath>` to better handle path parsing.
=> feat(file_descriptor source,stdin source): Use OptionalValuePath for host_key

src/sinks/http.rs
Changes the logic within http sink, to `insert` user-configured headers in the request instead of adding them.
This allows, among other things, to override the `Content-Type` header generated by the sink, which is useful e.g. to solve the problems detailed in https://github.com/vectordotdev/vector/issues/3378.
There is no negative impact, as the `request.headers` http sink configuration property already is a map, so does not allow for duplicate headers.
=> enhancement(http sink): allow overriding content-type header

src/sources/kubernetes_logs/parser/cri.rs
This PR replaces the regex with a simple parser for the CRI log string.
The asymptotic complexity of the new parser does not depend on the length of the log.
This solves the issue of the growing number of open files mentioned in #15590
Also in our deployment with an average log length of 15 KB, this patch cuts the CPU load in half.
=> enhancement(kubernetes_logs source): Replace regex with a simple parser for CRI logs

src/sources/aws_kinesis_firehose/mod.rs, src/sources/aws_s3/mod.rs, src/sources/aws_s3/sqs.rs, src/sources/aws_sqs/config.rs, src/sources/docker_logs/mod.rs, src/sources/file.rs, src/sources/file_descriptors/file_descriptor.rs, src/sources/file_descriptors/stdin.rs, src/sources/internal_logs.rs, src/sources/internal_metrics.rs, src/sources/journald.rs, src/sources/kubernetes_logs/mod.rs, src/sources/prometheus/scrape.rs, src/sources/splunk_hec/mod.rs, website/cue/reference/components/sources/base/aws_kinesis_firehose.cue, website/cue/reference/components/sources/base/aws_s3.cue, website/cue/reference/components/sources/base/aws_sqs.cue, website/cue/reference/components/sources/base/docker_logs.cue, website/cue/reference/components/sources/base/file.cue, website/cue/reference/components/sources/base/file_descriptor.cue, website/cue/reference/components/sources/base/internal_logs.cue, website/cue/reference/components/sources/base/internal_metrics.cue, website/cue/reference/components/sources/base/journald.cue, website/cue/reference/components/sources/base/kubernetes_logs.cue, website/cue/reference/components/sources/base/prometheus_scrape.cue, website/cue/reference/components/sources/base/stdin.cue
This PR removes `vector` from source descriptions because they will be getting pulled into the Reference section in Observability Pipelines docs.
ref: DOCS-4568
=> chore(docs): remove mentions of Vector from source descriptions

src/sources/nats.rs, website/cue/reference/components/sources/base/nats.cue, website/cue/reference/components/sources/nats.cue
Fixes: #14339
This MR adds information about subject for events extracted from NATS source
Example: 
```
{
"message": "asd",
"nats_subject": "test.123",
"source_type": "nats",
"timestamp": "2022-12-04T14:32:16.320259Z"
}
{
"message": "asd",
"nats_subject": "test.321",
"source_type": "nats",
"timestamp": "2022-12-04T14:32:22.696902Z"
}
```
Was retrieved by source with following configuration
```
sources:
nats_source:
type: nats
url: nats://localhost:4222
subject: "test.*"
subject_key_field: "nats_subject"
connection_name: noname
```
Key name is configured and default is just `subject`, but I'd be happy to change that if necessary. Also, I'd be happy to add any missing documentation/tests if i've missed something
=> enhancement(nats source): added subject key in event metadata

src/sources/heroku_logs.rs
Noticed as part of https://github.com/vectordotdev/vector/issues/15635
The legacy path was hardcoded to "host" but it could have been overwritten by the global schema.
=> fix(heroku_logs source): Fix schema def for the host key path

website/cue/reference/components/sources/vector.cue
As part of #15635
The original PR, https://github.com/vectordotdev/vector/pull/11905, added support for the v1 source but not v2.
=> docs(vector source): Source doesn't support tls client metadata enrichment

src/sources/socket/mod.rs, src/sources/socket/tcp.rs
=> feat(socket): Use OptionalValuePath in the tcp socket config

.github/workflows/regression_trusted.yml
This commit adjusts the names of the detect-regression check to `detect-regression` and adjusts the name of the `download-analysis` to `analyze-experiment`, to more accruate reflect its purpose. This change will require the required check to be adjusted to point to `Regression Detector / detect-regression`
=> fix(ci): Correct check names in trusted Regression Detector workflow

Cargo.toml, src/sources/aws_ecs_metrics/mod.rs, website/cue/reference/components/sources/aws_ecs_metrics.cue, website/cue/reference/components/sources/base/aws_ecs_metrics.cue
=> docs(aws_ecs_metrics source): Use generated configuration docs

scripts/cross/bootstrap-centos.sh, scripts/cross/entrypoint-centos.sh, scripts/cross/x86_64-unknown-linux-gnu.dockerfile
=> chore(x86_64 platform): Build packages with an older glibc to reenable centos7 and others.

src/sources/aws_kinesis_firehose/mod.rs, website/cue/reference/components/sources/aws_kinesis_firehose.cue, website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
- docs(aws_kinesis_firehose source): Use generated docs for configuration
- +un-option the compression config
Closes #15670
This _should_ be compatible, `vector-old` was generated with v0.26 and `vector-new` was generated with these changes.
```toml
data_dir = "/var/lib/vector/"
[sources.source0]
address = "0.0.0.0:443"
type = "aws_kinesis_firehose"
[sources.source0.acknowledgements]
[sources.source0.decoding]
codec = "bytes"
[sources.source0.framing]
method = "bytes"
[sinks.sink0]
inputs = ["source0"]
print_interval_secs = 1
[sinks.sink0.healthcheck]
enabled = true
[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```
```toml
data_dir = "/var/lib/vector/"
[sources.source0]
address = "0.0.0.0:443"
record_compression = "auto"
type = …
```
=> docs(aws_kinesis_firehose source): Use generated docs for configuration

website/cue/reference/configuration.cue
The supported databases are already listed under the `geoip` type for enrichment tables.
Closes: #15686 
=> docs(enriching): Remove misleading documentation about supported databases

scripts/integration/docker-compose.kafka.yml, website/cue/reference/services/kafka.cue
Updating integration tests to target oldest non-EOL Kafka version (using Confluent as the benchmark) and docs to match.
Closes: #1984
=> chore(kafka): Update Kafka support

website/cue/reference/components/sinks.cue, website/layouts/partials/data.html
They were incorrectly showing up on all request-based sinks even though not all support dynamic
partitioning. Instead I just added additional pointers to the template docs with the options that
support templating.
Closes: #11242
=> docs(sinks): Remove partitioning docs

scripts/environment/bootstrap-windows-2019.ps1
CI started pulling in newer, incompatible, versions of dependencies.
=> chore(ci): Lock nextest install on Windows

src/config/enterprise.rs, src/sinks/datadog/logs/config.rs, src/sinks/datadog/logs/service.rs, src/sinks/datadog/logs/tests.rs, src/sinks/http.rs, src/sinks/util/http.rs, website/cue/reference/components/sinks/base/datadog_logs.cue, website/cue/reference/components/sinks/datadog_logs.cue, website/cue/reference/components/sources/base/host_metrics.cue
Closes OPB-509
This PR
- Adds user customizable headers to Datadog Logs sink configuration, similar to the `http` sink.
- Meanwhile, removes an internal `enterprise` flag. All enterprise logic will be removed at some point, but since it's unclear when, we use the new configuration to preserve current functionality. 
- This is required for migrating enterprise features.
=> enhancement(datadog_logs sink): Add custom header configuration

website/cue/reference/components/sources/docker_logs.cue
Per discussion in #7361. If we do find evidence we can re-add this warning.
Closes: #7361
=> docs(docker_logs source): Remove warning lacking evidence

.github/workflows/test.yml
The autoinstall of `cross` by the `Makefile` started failing for these recently which caused me to
realize it was installing the latest `cross`. This adds the same setup scripts that run on other CI
jobs to ensure a consistent environment.
We could improve this some since this job really only needs `cross` and not the rest of the setup by
breaking up the setup scripts or using the enivironment image we package as the CI image to save on
CI job run time.
=> chore(ci); Run same setup scripts for cross jobs

lib/codecs/src/lib.rs, src/sinks/elasticsearch/common.rs, src/transforms/lua/v2/mod.rs, src/transforms/metric_to_log.rs, src/transforms/mod.rs, src/transforms/remap.rs, website/cue/reference/components/sinks/base/elasticsearch.cue, website/cue/reference/components/sinks/base/humio_metrics.cue, website/cue/reference/components/transforms/base/metric_to_log.cue
This is the only component that configures the behavior of tags with an option
named something other than `metric_tag_values`, so rename it to get with the
program.
This is going to conflict with #15716 as they both touch the same bits of code, but they are functionally independent.
Epic: #14742
=> chore(metric_to_log transform): Rename option to `metric_tag_values`

lib/vrl/stdlib/src/parse_klog.rs, lib/vrl/stdlib/src/parse_linux_authorization.rs, website/cue/reference/remap/functions/parse_klog.cue, website/cue/reference/remap/functions/parse_linux_authorization.cue
The code side of this could potentially be fixed by formatting the timestamps involved. However, all the strings involved have a fixed type of `&'static str` which cannot be dynamically formatted. As a result, resolving this involves a cascade of type refactoring into either `String` or `Cow<'static, str>`, and the return from `examples` into something other than `&'static [Example]` since that too is no longer static.
That will not help the documentation tests, though.
=> chore(vrl): Fix year-dependent tests for 2023

lib/codecs/tests/data/native_encoding/schema.cue, rfcs/2022-10-12-14742-flexible-metric-tags.md, website/content/en/highlights/2022-12-22-enhanced-metric-tags.md, website/content/en/highlights/2023-01-17-0-27-0-upgrade-guide.md, website/cue/reference/data_model/schema.cue
Adds some docs for the metric tag model, largely unlinked though.
Epic: #14742
=> chore(data model): Add some metric tag model documentation

src/sources/nats.rs, website/cue/reference/components/nats.cue, website/cue/reference/components/sinks/nats.cue, website/cue/reference/components/sources/base/nats.cue, website/cue/reference/components/sources/nats.cue
A couple of errors were in the NATS source documentation as a result of both the source and sink sharing some documentation.
- The `subject` field is not templateable in the source.
- The `connection_name` field is mandatory. In the sink this defaults to `vector` if not specified. Arguably we could change the functionality of the source to match the sink - but I'm going for minimal impact here.
=> docs(nats source): fix documentation errors

src/sources/file.rs
This PR removes a duplicate span enter operation in the `file` source, which should improve performance slightly. As we already instrument the `SourceSender::send_event_stream(&mut messages)` operation, entering the span for each `map` operation on the `messages` stream is a no-op functionally, but incurs the performance overhead regardless.
=> chore(file source): avoid duplicate span enter in message stream map

rfcs/2022-12-09-541-reload-api.md, src/app.rs
[Rendered](https://github.com/vectordotdev/vector/blob/reload-api-rfc/rfcs/2022-12-09-541-reload-api.md)
In addition to the RFC, I've included some code changes that start to demonstrate the direction of the refactoring discussed here. I plan to continue pushing updates there as they seem relevant to evaluating the RFC, but if any of them are controversial independent of the content just let me know and I'll separate them out.
=> chore: Add RFC for Reloading API

website/cue/reference/components/sinks/splunk_hec_metrics.cue
Closes #15621
Epic #15420 
Testing Splunk with duplicate tag names shows that Splunk just ignores all but the last value. Since this is the current behaviour of Vector, this PR just updates the documentation to reflect this.
=> docs(splunk_hec sink): update docs re duplicate tags

Cargo.lock, lib/vector-common/src/datetime.rs, lib/vector-config-common/Cargo.toml, lib/vector-config-common/src/attributes.rs, lib/vector-config-macros/src/ast/container.rs, lib/vector-config-macros/src/ast/field.rs, lib/vector-config-macros/src/ast/mod.rs, lib/vector-config-macros/src/ast/variant.rs, lib/vector-config-macros/src/configurable.rs, lib/vector-config/Cargo.toml, lib/vector-config/src/num.rs, lib/vector-config/src/schema.rs, lib/vector-config/tests/integration/smoke.rs
Adds support to specify a value for a `#[configurable(metadata(..))]` key/value pair so long as the value is capable of being serialized to JSON via `serde_json`. Additionally, if a string literal is provided that ends in `()`, we interpret it as an expression, which allows using the expression's result as the value.
Currently, both the key and value of a metadata key/value attribute are required to be strings. Initially, this was sufficient for the purposes of carrying out the configuration schema work related to the RFC. Over time as we've used the configuration schema output more and more, namely with converting over the Cue-based documentation to be derived from it, we've discovered that the strings-only limitation was too constraining.
Supporting types other than strings unlocks the …
=> enhancement(config): add support for any `serde_json`-capable value for `configurable` metadata KV pairs

.cargo/config.toml
To workaround issue in inventory crate when upgrading to Rust 1.65.0.
Just curious to see the difference in CI time here.
=> chore(ci): Use codegen-units = 1 for Windows

README.md
=> docs: Add Telegraf features to README

Cargo.toml, src/sources/apache_metrics/mod.rs, website/cue/reference/components/sources/apache_metrics.cue, website/cue/reference/components/sources/base/apache_metrics.cue
Very straightforward. Biggest changes: added units to a field, then an example to another.
=> docs(apache_metrics): Use generated docs

lib/vrl/stdlib/Cargo.toml, lib/vrl/stdlib/benches/benches.rs, lib/vrl/stdlib/src/decode_base16.rs, lib/vrl/stdlib/src/encode_base16.rs, lib/vrl/stdlib/src/lib.rs, website/cue/reference/remap/functions/decode_base16.cue, website/cue/reference/remap/functions/encode_base16.cue, website/cue/reference/urls.cue
These encode/decode functions enable Vector to work with logs produced with strings encoded with base16 (or hex).
`encode_base16` `decode_base16` are similar to the base64 functions - however less complex due to base16 being more simple than base64.
```
$ decode_base16!("some string")
function call error for "decode_base16" at (0:29): unable to decode value to base16
$ decode_base16!("736f6d6520737472696e67")
"some string"
$ encode_base16("some string")
"736f6d6520737472696e67"
```
=> feat(vrl): add `decode_base16`, `encode_base16` functions

src/config/diff.rs
Fixes an issue where components would be falsely flagged as different because of the way HashMaps can iterate in different order. Because of this unchanging components would be needlessly cycled on every reload.
Closes: #13716
=> fix(config): compare serialized JSON Values instead of string

src/config/loading/secret.rs, src/config/secret.rs, src/secrets/exec.rs, src/secrets/mod.rs, src/secrets/test.rs
Previously it was "consuming" the secret for each place it appeared as a placeholder in the
configuration causing it to fail to find the secret a second time.
Closes: #15795
=> fix(config): Allow secrets to be reused multiple times

src/sinks/clickhouse/config.rs, src/sinks/clickhouse/http_sink.rs, website/cue/reference/components/sinks/base/clickhouse.cue
Added support for ClickHouse setting which will allow to ingest timestamp with subsecond precision (`DateTime64` column). This trades off some performance cost on server side for ability to store same timestamp precision as vector uses
=> enhancement(ClickHouse sink): Adding date_time_best_effort flag

src/sources/internal_logs.rs, website/cue/reference/components/sources/base/internal_logs.cue, website/cue/reference/components/sources/internal_logs.cue
closes: https://github.com/vectordotdev/vector/issues/15894
epic: https://github.com/vectordotdev/vector/issues/14998
=> docs(internal_logs source): use auto-generated config docs

rust-toolchain.toml
Reverts vectordotdev/vector#15893
=> chore(deps): Revert update Rust to 1.66.1

rust-toolchain.toml
Reverts vectordotdev/vector#15913
Looks like the Docker images exist now.
=> chore(deps): Update Rust to 1.66.1

src/sources/nginx_metrics/mod.rs
This duration had been changed while updating it from a `u64` to a `Duration`, causing us to collect more metrics than we had expected in the test.
=> chore: Fix scrape duration for nginx_metrics integration test

scripts/generate-component-docs.rb, src/sinks/loki/config.rs, website/cue/reference/components/sinks/base/loki.cue
This PR fixes an issue with all examples for an `object` being applied to the fields of that object directly when generating the documention output from the configuration schema.
This made sense when metadata could only be string values, but now that we support all `serde_json`-capable types, trying to use the proper metadata (like objects for object fields, etc) results in setting example values that do not have the expected data type.
Now, when doing the above -- setting an object as the example value for an `object` field -- it will be correctly applied such that it shows that object an example for the overall object field, rather than any of its properties.
As a consequence of this change, we had to change the `loki` sink to emit an object for the example value rather than an array of …
=> fix(docs): apply object examples to the correct part of the docs output

.github/workflows/publish.yml
Remove debian:9 since it is EOL and add back amazonlinux:1 and ubuntu:14.04 now that we've re-added support for older
glibcs on x86_64.
=> chore(ci): Update OS test targets for packages

vdev/src/app.rs, vdev/src/commands/build.rs, vdev/src/commands/check/deny.rs, vdev/src/commands/check/fmt.rs, vdev/src/commands/check/markdown.rs, vdev/src/commands/exec.rs, vdev/src/commands/fmt.rs, vdev/src/commands/integration/start.rs, vdev/src/commands/integration/stop.rs, vdev/src/commands/integration/test.rs, vdev/src/commands/mod.rs, vdev/src/commands/release/prepare.rs, vdev/src/commands/run.rs, vdev/src/git.rs, vdev/src/testing/runner.rs
There are a number of functions that execute programs that do similar things in slightly different ways. This moves more of that functionality into the `Command` extensions and adds one more generic wrapper for the simple cases.
=> chore(dev): Replace `app::exec*` with a more generic framework in `vdev`

Cargo.lock
Reverts vectordotdev/vector#15975
CI "passed" with a failed cross test and the remainder cancelling
=> Revert "chore(deps): bump rustyline from 10.0.0 to 10.1.0"

vdev/src/commands/check/fmt.rs
Recent PR caused this not to be running the file from the `scripts/` directory.
https://github.com/vectordotdev/vector/blob/master/vdev/src/app.rs#L117-L120
=> chore: Fix vdev check fmt command

.github/workflows/test.yml, Makefile, vdev/src/commands/check/mod.rs
We now have a `vdev check style` that runs some file format checks on the source code, as well as `vdev check fmt` that runs `cargo fmt --check` _as well as_ doing the style check (in addition to `vdev fmt` that does style check fixes and runs `cargo fmt`). This PR removes the redundancy and references to it.
This was previously separated out in #8862 for the purpose of allowing to run the style check on all changes but still avoid running `cargo fmt` when not necessary. However, `cargo fmt` is quite light, rarely taking more than a second or two, so I don't see this as a particularly large obstacle.
=> chore(dev): Drop the separate `vdev check style` subcommand

Cargo.lock, Cargo.toml
Now that 0.27.0 has been tagged and released.
=> chore(releasing): Bump Vector version to 0.28.0

src/transforms/reduce/mod.rs, website/cue/reference/components/transforms/base/reduce.cue
This adds a `max_events` configuration option for `reduce` transforms to put an upper bound on the number of events a single grouping will combine https://github.com/vectordotdev/vector/issues/3027
=> enhancement(reduce transform): Add max_events option

docs/tutorials/lognamespacing.md
This PR adds a quick guide to adding Log Namespacing to sources.
Keeping in draft until I finish the guide to Schemas.
=> docs: added Log Namespacing tutorial

lib/vector-config/src/schema.rs, scripts/generate-component-docs.rb, src/sources/host_metrics/cgroups.rs, src/sources/host_metrics/mod.rs, website/cue/reference/components/sources/base/host_metrics.cue
This change moves Linux-specific CGroups configuration types into the root module in the host_metrics crate. This enables us to generate Cue docs for the source on all platforms. Note: the cgroups config options will do nothing on non-Linux platforms. They're only available for the sake of generating the docs. 
I also introduced the env variable `VECTOR_GENERATE_SCHEMA`. It's used to enable the CGroups defaults on non-Linux machines for the sake of generating the docs. When the env variable isn't set, `CGroupsConfig` is only allowed on Linux machines, and an error is thrown if it's used on non-Linux machines. I think that this introduces a decent pattern for when this situation pops up again. 
I tested this on my Mac and an Ubuntu machine. The expected behavior of not triggering any …
=> fix(host_metrics source): support generating Linux-specific docs on all platforms

website/scripts/create-config-examples.js
This fixes the issue on the website where null fields are showing as null in the example configs for YAML and JSON. They should not show at all.
Compare the advanced YAML config between [here](https://deploy-preview-16071--vector-project.netlify.app/docs/reference/configuration/sources/dnstap/) and the [live Vector website](https://vector.dev/docs/reference/configuration/sources/dnstap/#event-fields).
=> docs: Remove null fields from example configs on website

vdev/src/app.rs, vdev/src/commands/info.rs, vdev/src/commands/mod.rs, vdev/src/testing/runner.rs
This shows some useful info about the setup of the `vdev` command, much like running `docker info`.
=> chore(vdev): Add new `info` command to show overall vdev setup

vdev/src/commands/config/find.rs, vdev/src/commands/info.rs, vdev/src/commands/integration/show.rs, vdev/src/commands/meta/starship.rs, vdev/src/commands/status.rs, vdev/src/macros.rs, vdev/src/testing/runner.rs
This macro causes all displayed output to be highlighted as bold text. If we
need bold text for some output, we can recreate this macro for the selected
uses but, otherwise, the default should be just plain text output.
=> chore(vdev): Drop the `display!` macro

website/content/en/docs/reference/configuration/sources/statsd.md
Clarify a little bit the documentation regarding Statsd. Even if the linked repo consists implementation of the Statsd server, now should be clear that Vector could be used instead of Statsd server as a one more Statsd server implementation.
=> docs(statsd): update source description

vdev/src/commands/integration/test.rs, vdev/src/commands/test.rs, vdev/src/testing/integration.rs, vdev/src/testing/runner.rs
This just simplifies some of the code within the test runner hierarchy, reducing some duplication.
I came across this while working on fixing the broken integration tests and thought I could break it out for quick review.
=> chore(vdev): Refactor test runners

scripts/integration/docker-compose.shutdown.yml, scripts/integration/shutdown/test.yaml
The new test worked on my dev system and during the PR review, but has been failing in subsequent CI, so revert this to make `master` green again.
This reverts commit 1b27f7704b27768aa3bd92c9b86d5ecf4f3b6cd4.
=> Revert "chore(ci): Fix the shutdown integration test to run in vdev (#16128)

.github/workflows/gardener_open_pr.yml
Needs to run on base branch to have access to secrets.
Also fixes runs-on placement and runs the workflow on re-opened PRs.
=> chore(ci): Fix gardener PR workflow

vdev/src/commands/integration/show.rs, vdev/src/commands/integration/start.rs, vdev/src/commands/integration/stop.rs, vdev/src/commands/integration/test.rs, vdev/src/testing/integration.rs, vdev/src/testing/state.rs
Some of the integration test configs (notably splunk) are reused to run the same environment with different image versions. While it would be convenient to allow testing against multiple environments at the same time, there are some unresolved conflicts that make that currently impossible, most notably volume management. As this use case is more of an interesting use case than a requirement, we are going to reduce the complexity by allowing only starting one environment at a time.
=> chore(vdev): Allow only a single running integration test environment

website/content/en/docs/setup/installation/platforms/docker.md
Proof:
https://hub.docker.com/layers/timberio/vector/0.27.0-distroless-libc/images/sha256-7cc605c682ea9fc79e0f2732f6729b2cadec91d112f94b0699138c2d163a7a8c?context=explore
=> fix: (docs) Fix docker tag for distroless-libc image (In website documentation)

scripts/integration/amqp/compose.yaml, scripts/integration/apex/compose.yaml, scripts/integration/aws/compose.yaml, scripts/integration/axiom/compose.yaml, scripts/integration/azure/compose.yaml, scripts/integration/chronicle/compose.yaml, scripts/integration/clickhouse/compose.yaml, scripts/integration/datadog-agent/compose.yaml, scripts/integration/datadog-traces/compose.yaml, scripts/integration/elasticsearch/compose.yaml, scripts/integration/eventstoredb/compose.yaml, scripts/integration/gcp/compose.yaml, scripts/integration/http-client/compose.yaml, scripts/integration/humio/compose.yaml, scripts/integration/influxdb/compose.yaml, scripts/integration/kafka/compose.yaml, scripts/integration/logstash/compose.yaml, scripts/integration/loki/compose.yaml, scripts/integration/mongodb/compose.yaml, scripts/integration/nats/compose.yaml, scripts/integration/nginx/compose.yaml, scripts/integration/opentelemetry/compose.yaml, scripts/integration/postgres/compose.yaml, scripts/integration/prometheus/compose.yaml, scripts/integration/pulsar/compose.yaml, scripts/integration/redis/compose.yaml, scripts/integration/shutdown/compose.yaml, scripts/integration/splunk/compose.yaml, vdev/src/testing/integration.rs, vdev/src/testing/runner.rs
This should cause integration test runners and the associated networks to be cleaned up after a test is run and stopped. However, it did fail CI integration tests last time I tried, so I'm taking another try at it.
=> chore(ci): Clean up runner containers and networks on stop

src/sources/kafka.rs
Make one final attempt to commit stored offsets on kafka source shutdown.
=> feat(kafka): synchronous consumer offset commit on shutdown

scripts/integration/docker-compose.logstash.yml, vdev/src/testing/config.rs, vdev/src/testing/integration.rs, vdev/src/testing/runner.rs
Reverts vectordotdev/vector#16168
Temporarily reverting as this introduces some dead code on Windows which causes the nightly build to fail.
It looks like the PR workflows only warn on the dead code, but the release workflows consider it an error. Separately I think we should have the PR workflows consider it an error too.
=> chore(ci): Revert Fix the logstash integration test to run through vdev

website/cue/reference/components.cue, website/cue/reference/components/base/sinks.cue, website/cue/reference/components/sinks.cue
The proxy from SourceContext was not being rendered in the auto generated docs
=> docs(sinks): enable auto-generated proxy settings

lib/vector-core/src/tls/settings.rs, src/sinks/util/batch.rs, src/sinks/util/buffer/compression.rs, src/sinks/util/service.rs, src/sources/aws_kinesis_firehose/mod.rs, src/sources/aws_s3/mod.rs
Part of #16222.
This PR addresses the most common shared configuration types which drive the common `batch`, `compression`, `request`, and `tls` sections in most sinks, and in some sources.
This is a purely schema-based change, annotating these types as being advanced. It doesn't yet affect the auto-generated documentation as the documentation generation script doesn't pay attention to the attribute yet.
=> chore(config, docs): start marking certain shared config types as advanced

src/common/datadog.rs, src/config/enterprise.rs, src/sinks/datadog/events/config.rs, src/sinks/datadog/logs/config.rs, src/sinks/datadog/metrics/config.rs, src/sinks/datadog/mod.rs, src/sinks/datadog/traces/config.rs, website/cue/reference/components/sinks/base/datadog_events.cue, website/cue/reference/components/sinks/base/datadog_logs.cue, website/cue/reference/components/sinks/base/datadog_metrics.cue, website/cue/reference/components/sinks/base/datadog_traces.cue, website/cue/reference/components/sinks/datadog_traces.cue
- The changes to `site` , I had to do for each DD sink because they use shared code as you'll see in the PR. I didn't touch anything else in the configs for the other DD sinks so those will still get separate reviews.
- Consequently, my next PRs for the other DD sinks will be based off this one.
closes: https://github.com/vectordotdev/vector/issues/16224
=> docs(datadog_traces sink): use auto-generated config docs

Cargo.lock, lib/vrl/stdlib/Cargo.toml, lib/vrl/stdlib/benches/benches.rs, lib/vrl/stdlib/src/lib.rs, lib/vrl/stdlib/src/seahash.rs, website/cue/reference/remap/functions/seahash.cue, website/cue/reference/remap/functions/sha1.cue, website/cue/reference/urls.cue
Resolves [16072](https://github.com/vectordotdev/vector/issues/16072)
Rationale in the linked issue. 
Note that function converts unsigned int-64 seahash to signed int-64 to met VRL standards, so integer overflow happens when calculated hash is higher than signed int-64 max value. Depending on the use-case this might or mightn't be an issue.
=> feat(vrl): add `seahash` function

website/layouts/_default/component-card.html
Something that has annoyed me for a long time. The component tag at <https://vector.dev/components/> shows redundant scrollbars next to it. 
This PR removes them.
Tested on chrome, firefox and vivaldi on Linux.
=> docs: remove scrollbars from component tag on website

vdev/src/commands/integration/stop.rs, vdev/src/commands/integration/test.rs, vdev/src/testing/integration.rs
The compatibility hack was introduced in #16124 as we were starting to run tests through vdev but didn't want to deal with fixing all of them at once. The last test has been fixed, so this path is no longer needed.
=> chore(vdev): Drop backwards compat hack for old integrations

lib/codecs/src/decoding/framing/character_delimited.rs, lib/codecs/src/decoding/framing/newline_delimited.rs, lib/vector-buffers/src/config.rs, lib/vector-core/src/config/global_options.rs, lib/vector-core/src/config/proxy.rs, src/conditions/vrl.rs, src/config/builder.rs, src/transforms/remap.rs, website/cue/reference/components/base/sinks.cue, website/cue/reference/components/sources/base/amqp.cue, website/cue/reference/components/sources/base/aws_kinesis_firehose.cue, website/cue/reference/components/sources/base/aws_sqs.cue, website/cue/reference/components/sources/base/datadog_agent.cue, website/cue/reference/components/sources/base/demo_logs.cue, website/cue/reference/components/sources/base/exec.cue, website/cue/reference/components/sources/base/file_descriptor.cue, website/cue/reference/components/sources/base/gcp_pubsub.cue, website/cue/reference/components/sources/base/heroku_logs.cue, website/cue/reference/components/sources/base/http.cue, website/cue/reference/components/sources/base/http_client.cue, website/cue/reference/components/sources/base/http_server.cue, website/cue/reference/components/sources/base/kafka.cue, website/cue/reference/components/sources/base/nats.cue, website/cue/reference/components/sources/base/redis.cue, website/cue/reference/components/sources/base/socket.cue, website/cue/reference/components/sources/base/stdin.cue, website/cue/reference/components/transforms/base/remap.cue
This PR is a grab bag of a bunch of tweaks/cleanup work for the generated configuration schema / schema-based documentation:
- updated description for `max_length` configuration setting of the character/newline-delimited framers to indicate that the default value is, practically, unlimited, and that care should be taken, yadda yadda
- tweaks to the buffer configuration stuff, namely specifying the minimum disk buffer size as a validator attribute, and specifying the type unit of "bytes"
- a small tweak to `GlobalOptions` to not use `#[serde(default)]` at the type level, which drops some extraneous (and incorrect) default values from the generated schema [1]
- marking `ProxyConfig` as advanced
- hiding the `runtime` configuration setting from both the `remap` transform and the generic VRL …
=> chore(config, docs): a bunch of fixes/additions to schema output

vdev/src/testing/integration.rs, vdev/src/testing/runner.rs
More pure tech debt I wrote up last week and put aside as not strictly needed. This addresses another TODO item. In the current code base, handling running docker-compose is sprinkled throughout the overall integration test runner. This PR mostly just refactors that out into its own type to simplify the overall logic.
I think we could also get away with dropping the state files that indicate which integration test has been started already, as we should be able to get that information out of `docker ps` etc. As it stands now there are some known issues with, for example, rebooting while an integration test is setup causing the inability to start it again, etc.
=> chore(vdev): Clean up integration compose handling

.github/workflows/test.yml
Since changes to vdev could impact any of the CI jobs.
=> chore(ci): Run all checks when vdev is updated

Cargo.lock
Resolves https://rustsec.org/advisories/RUSTSEC-2023-0009
=> chore(deps): Update openssl-src crate

src/sinks/axiom.rs, website/cue/reference/components/sinks/axiom.cue, website/cue/reference/components/sinks/base/axiom.cue
Closes #16349
The docs drop both the `batch` and `encoding` options, but they weren't passed into the builder anyway - only using the defaults from `elasticsearch`
=> docs(axiom sink): Use autogenerated docs

src/sinks/honeycomb.rs, website/cue/reference/components/sinks/base/honeycomb.cue, website/cue/reference/components/sinks/honeycomb.cue
=> docs(honeycomb sink): Use autogenerated docs

lib/vector-common/src/datetime.rs, lib/vector-config-macros/src/configurable.rs, lib/vector-config/src/external/indexmap.rs, lib/vector-config/src/external/no_proxy.rs, lib/vector-config/src/metadata.rs, lib/vector-config/src/schema.rs, lib/vector-config/src/stdlib.rs, lib/vector-config/tests/integration/smoke.rs, scripts/generate-component-docs.rb, src/sinks/util/buffer/compression.rs, website/cue/reference/components/sinks/base/influxdb_metrics.cue, website/cue/reference/components/sinks/base/prometheus_exporter.cue, website/cue/reference/components/sinks/base/prometheus_remote_write.cue
In general, `Configurable` accomplishes most of its goals by providing a concept of schema "metadata". While we can trivially examine the raw structure of a Rust type -- what are its fields, what is the type of those fields, etc -- it's harder to divine intent and usage characteristics purely from the syntactical structure. We need a mechanism to annotate types and fields to better describe their purpose and usage.
This is the primary reason that `vector_config::Metadata` exists. We use it to hold the title/description of a schema element (struct, enum, struct/enum field, etc), as well as validation annotations, and custom attributes, such as free-form key/value pairs.
We use schema metadata in two main "modes": base and override.
The base metadata for a type implementing `Configurable` …
=> chore(config): fix schema generation handling of base vs override metadata

src/sinks/file/mod.rs, website/cue/reference/components/sinks/base/file.cue, website/cue/reference/components/sinks/file.cue
Closes #16345
* Updated the `idle_timeout` to actually be a duration and renamed internally
* Left a note for why it isn't using the shared util's compression struct
=> docs(file sink): Use generated documentation

src/sinks/aws_kinesis/streams/integration_tests.rs
We merged https://github.com/vectordotdev/vector/pull/16286
, without running integration tests there. Seems that new int test is not ready.
Timing out on master:
https://github.com/vectordotdev/vector/actions/runs/4129227074/jobs/7134930917
I also tried on my EC2 instance and saw the same behavior.
Commenting that out to unblock master while we sort it out.
Not reverting the commit because the commit also included a fix for a bug.
Ran the int test locally with this change:
```
$ cargo vdev int test aws
PASS [  59.148s] vector sinks::aws_kinesis::streams::integration_tests::kinesis_put_records_without_partition_key
```
=> fix(ci): temporarily disable new aws integration test that is failing

website/content/en/docs/about/concepts.md
User in discord support was asking about trace support in vector.
=> chore(external docs): Add note about trace events to concepts page

src/test_util/components.rs
These track_caller annotations are considered no-ops in async functions. These annotations were causing warnings and local tests to fail in certain cases.
=> fix(test_util): drop no-op track_caller annotations

Cargo.toml, rust-doc/Makefile, rust-doc/netlify.toml, scripts/environment/install-protoc.sh, src/lib.rs
This builds the rust docs for Vector and sets them to `rust-doc.vector.dev`.
Preview is [here](https://deploy-preview-16386--vector-rust-doc.netlify.app/vector/). I'll update it to only build on master once this PR is ready to merge.
When I switch `RUSTDOCFLAGS="--cfg docsrs"`, I get this error, so have disabled for now:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /home/stephenwakely/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-io-0.3.26/src/lib.rs:22:21
|
22 | #![cfg_attr(docsrs, feature(doc_cfg))]
|                     ^^^^^^^^^^^^^^^^
error: Compilation failed, aborting rustdoc
```
=> docs: Build rust-doc.vector.dev

website/cue/reference/components/sources/splunk_hec.cue
Confusion around this source came up in Discord. A user incorrectly thought that the root HTTP path should be used for sending events. Reading the docs, that's a valid interpretation given that we don't mention the specific endpoints to use. This change mentions all three endpoints in the the description 😄
=> docs(splunk_hec source): add info about endpoints

src/sinks/util/adaptive_concurrency/mod.rs
In #16150, a change was made to remove `#[serde(default)]` from `AdaptiveConcurrencySettings`. This is standard practice now due to how it affects the resulting configuration schema output, where we instead prefer to set the defaults on a per-field basis.
However, only one of the struct fields was changed to properly set the default, while the other two were not. This resulted in a change to the schema that made the two unchanged fields appear to be required, when they are in fact not.
=> chore(config): apply the field-level defaults to all ARC settings

.github/CODEOWNERS, docs/CONTRIBUTING.md
This updates CONTRIBUTING.md to mention that CODEOWNER reviews are required but also adds secondary
reviewers for each code owner that is an individual to cover the case where the primary reviewer is
inaccessible (e.g. on PTO).
This is in preparation for adding the requirement of review by the `@vectordotdev/ux-team` if requested.
=> chore(dev): Clarify CODEOWNERS requirements and add additional owners

.github/workflows/test.yml
Seems like this is generally useful, but, in particular, adding this to help determine why we are
seeing recent failures generating the docs from schemas in some PRs.
=> chore(ci): Upload config schema as artifact

src/transforms/mod.rs
Copies the equivalent [Cue transform docs](https://github.com/vectordotdev/vector/tree/master/website/cue/reference/components/transforms/base) into doc comments, so generated schema returns expanded descriptions.
Note: Each description was c/p'd manually. There's no hard association with Cue.
```bash
cargo run -- generate-schema
```
... and manually verify that transform descriptions in the returned JSON are expanded.
=> chore(internal docs): Update transform descriptions

website/content/en/highlights/2023-02-28-0-28-0-upgrade-guide.md, website/cue/reference/components/sources/aws_s3.cue
=> docs: Remove strategy link from s3 source page

src/aws/region.rs, src/kafka.rs, src/sinks/gcp/cloud_storage.rs, src/sinks/kafka/config.rs, src/sinks/prometheus/exporter.rs, src/sinks/prometheus/remote_write.rs, src/sources/aws_s3/mod.rs, src/sources/kafka.rs, src/sources/logstash.rs, src/sources/prometheus/remote_write.rs, src/sources/prometheus/scrape.rs, src/transforms/remap.rs
(Apologies for the codeowner spam!)
Small PR to mark a few fields with `docs::advanced` meta for internal schema generation.
```bash
cargo run -- generate-schema
```
... and manually verify that transform descriptions in the returned JSON are expanded.
=> chore(internal docs): Mark advanced schema props

src/sinks/aws_kinesis/config.rs, src/sinks/aws_kinesis/streams/config.rs, website/cue/reference/components/sinks/aws_kinesis_streams.cue, website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue, website/cue/reference/components/sinks/base/aws_kinesis_streams.cue
Closes #16342
Copies the same changes from the firehose PR for the base config
=> docs(aws_kinesis_streams sink): Use generated documentation

src/sinks/kafka/config.rs, src/sinks/kafka/sink.rs, src/sinks/kafka/tests.rs, website/cue/reference/components/sinks/base/kafka.cue, website/cue/reference/components/sinks/kafka.cue
Closes #16023
A few minor changes you might notice:
- I turned the `topic` var into a `Template` 
- brought in some docs & examples from the Kafka *source*, since they were slightly better in places
=> docs(kafka sink): autogen docs

src/sinks/pulsar.rs, website/cue/reference/components/sinks/base/pulsar.cue
Closes #16251
This sink was already ported over to the new Cue system a while back, but a contributor PR introduced the `producer_name` config option. This PR adds an example.
=> docs(pulsar sink): add example for producer_name

lib/codecs/src/encoding/format/json.rs, lib/codecs/src/encoding/format/text.rs, lib/vector-config-macros/src/configurable.rs, lib/vector-config-macros/src/configurable_component.rs, lib/vector-config/src/schema.rs, lib/vector-config/src/stdlib.rs, scripts/generate-component-docs.rb, src/sinks/util/buffer/compression.rs
As part of the work to tighten up the generated configuration schema for Vector, this PR introduces a change to mark all struct schemas as `additionalProperties: false`, which indicates that any properties not specifically defined should not be ignored, and should rise to the level of a validation error.
Originally, this PR started out as a way to do that _and_ automatically apply `#[serde(deny_unknown_fields)]` where appropriate... but due to conflicts between `deny_unknown_fields` and `flatten`, I had to abandon that portion of the work.
In this respect, the configuration schema is more strict than what `serde`/Vector will accept when parsing a configuration.
=> chore(config): mark structs as `additionalProperties: false`

lib/lookup/src/lookup_v2/optional_path.rs, lib/vector-common/src/datetime.rs, lib/vector-config-macros/src/configurable.rs, lib/vector-config/src/configurable.rs, lib/vector-config/src/external/chrono.rs, lib/vector-config/src/external/encoding_rs.rs, lib/vector-config/src/external/indexmap.rs, lib/vector-config/src/external/no_proxy.rs, lib/vector-config/src/external/toml.rs, lib/vector-config/src/external/tz.rs, lib/vector-config/src/external/url.rs, lib/vector-config/src/lib.rs, lib/vector-config/src/metadata.rs, lib/vector-config/src/schema.rs, lib/vector-config/src/ser.rs, lib/vector-config/src/stdlib.rs, lib/vector-config/src/str.rs, lib/vector-config/tests/integration/configurable_string.rs, lib/vector-config/tests/integration/smoke.rs, src/sinks/util/buffer/compression.rs, src/sinks/util/service/concurrency.rs
The `Serialize` trait is only used by the configurable system in order to
translate default values into `serde_json::Value`. Since the `Serialize` trait
is not object safe, this causes complications for making the other traits object
safe in preparation for moving to an inventory-style system for registering
components.
This change introduces an object-safe `ToValue` trait that is used to express a
direct conversion from values into a `serde_json::Value`. Where possible, this
is implemented directly, however the fallback of `serde_json::to_value` is used
for types where this is difficult.
=> chore(config): Replace `Serialize` with new `ToValue` trait in config schemas

src/sinks/loki/integration_tests.rs
Ref #16454
Epic #15453
This adds an integration test to the Loki sink to ensure that the field with a timestamp meaning is used as the timestamp sent to Loki.
=> chore(loki sink): add namespaced timestamp integration test

distribution/install.sh
Missed in #16398. Definitely could use some tests of this script on different platforms.
Fixes: #16472
=> fix(distribution): Add missing check_proc function to install script

lib/codecs/src/decoding/format/bytes.rs, lib/codecs/src/decoding/format/syslog.rs, lib/vector-core/src/config/log_schema.rs, lib/vector-core/src/event/log_event.rs, lib/vector-core/src/schema/definition.rs, lib/vector-core/src/schema/requirement.rs, src/sources/amqp.rs, src/sources/datadog_agent/tests.rs, src/sources/file.rs, src/sources/fluent/mod.rs, src/sources/gcp_pubsub.rs, src/sources/heroku_logs.rs, src/sources/http_server.rs, src/sources/internal_logs.rs, src/sources/journald.rs, src/sources/kafka.rs, src/sources/kubernetes_logs/mod.rs, src/sources/logstash.rs, src/sources/nats.rs, src/sources/opentelemetry/mod.rs, src/sources/splunk_hec/mod.rs, src/sources/syslog.rs, src/sources/vector/mod.rs, src/topology/schema.rs, src/transforms/metric_to_log.rs, src/transforms/remap.rs
This updates all the legacy paths (`LookupBuf`) used in semantic meaning to the new paths (`OwnedTargetPath`), which also allows semantic meaning to point to metadata.
Since the `with_metadata_field` helper function didn't allow setting a meaning, this required touching many different files. These changes were contained in the [update component definitions](https://github.com/vectordotdev/vector/pull/16455/commits/c91b5797bb148664c6c53e5715abc3f9c0a392e4) commit if you want to review those separately. The main changes are in the first commit, [add metadata support to semantic meaning](https://github.com/vectordotdev/vector/pull/16455/commits/2f60e67741e31c533e64b890e7a4087aaa29c7fa)
=> feat(core): add metadata support to semantic meaning

website/cue/reference/components/sinks/aws_s3.cue, website/cue/reference/components/sinks/azure_blob.cue, website/cue/reference/components/sinks/gcp_cloud_storage.cue
Based on a discord support discussion where the combination of these options was not clear.
=> chore(external docs): Add clarifying example for GCP Storage key_prefix usage

src/sinks/mod.rs, src/sources/mod.rs, src/transforms/mod.rs
This PR adds new `docs::label` meta to each component and updates descriptions to match  labels used in Cue data (for the most part).
The purpose is to disambiguate names from descriptions and give components standard meta in generated schema.
I've taken some liberties with grammar in places, preferring Title Cased names where appropriate and attempting to match brand or product names as they're commonly represented. Feel free to suggest additional changes as necessary. Both names and descriptions will be used in public UI.
=> chore(internal docs): `doc::label` meta for components, updated descriptions

lib/codecs/src/encoding/format/json.rs, lib/codecs/src/encoding/format/text.rs, lib/vector-config-macros/src/configurable.rs, lib/vector-config-macros/src/configurable_component.rs, lib/vector-config/src/schema.rs, lib/vector-config/src/stdlib.rs, scripts/generate-component-docs.rb, src/sinks/util/buffer/compression.rs
Reverts vectordotdev/vector#16464
We ran into some issues with `additionalProperties: false`; putting up as a ~draft~ PR to test this locally.
=> Revert "chore(config): mark structs as `additionalProperties: false`"

src/sinks/datadog/logs/sink.rs
This sink had a `SemanticJsonEncoding` which allowed using semanic meaning to retrieve data instead of the global log schema. This was never actually enabled though. Now that we have log namespacing which takes a slightly different approach to fetching data with semantic meaning, this is no longer needed.
This also has some minor fixes / adjustments:
- `host` was made optional (to match the sink requirement definition)
- `host` was renamed to `hostname` to match the Datadog Agent
- `timestamp` is now required (to match the sink requirement definition)
=> chore(datadog_logs sink): remove semantic encoder for the Datadog Logs sink

lib/vector-config-macros/src/ast/container.rs, lib/vector-config-macros/src/ast/field.rs, lib/vector-config-macros/src/ast/util.rs, lib/vector-config/src/metadata.rs, src/config/mod.rs, src/sinks/util/buffer/compression.rs
Another baby step towards making configuration schemas object safe. This stores the default value for the config metadata in a box instead of a concrete type. The type bounds on the metadata remain for now, as I'm trying to make this minimal behavior-preserving change before tackling the generic bounds. As far as I can tell from `vector generate-schema`, the resulting data is identical.
=> chore(config): Store default value in a box

.github/workflows/regression_trusted.yml, regression/cases/file_to_blackhole/experiment.yaml, regression/cases/file_to_blackhole/lading/lading.yaml
As part of updating the regression testing backend, this commit changes the optimization goal for the `file_to_blackhole` experiment to egress throughput from ingress throughput (the default).
This commit also modifies the Lading configuration for this experiment so that it writes a file to a TCP blackhole.
=> chore(ci): test file_to_blackhole egress throughput

regression/cases/file_to_blackhole/vector/vector.toml
As part of the changes in PR #16468, I modified the `file_to_blackhole` regression experiment's Lading configuration to add a Lading blackhole based on similar changes in a dogfood repo for regression testing. However, as @spencergilbert suggested and @GeorgeHahn confirmed, the Lading blackhole is redundant because the Vector configuration for that experiment also uses a blackhole sink.
This commit modifies the `file_to_blackhole` regression experiment's Vector configuration so that the Vector sink is now a TCP socket instead of a blackhole, which is consistent with the Vector configuration in our regression testing dogfood repo.
Signed-off-by: Geoffrey M. Oxberry <geoffrey.oxberry@datadoghq.com>
=> fix(ci): adjust file_to_blackhole Vector config

src/sinks/gcp/mod.rs, src/sinks/gcp/stackdriver_metrics.rs
fix(gcp_stackdriver_metrics): Fixes `GcpSeries` serialization format without breaking config.
=> fix(gcp_stackdriver_metrics): Fixes GcpSeries serialization format without breaking config.

Cargo.lock, lib/vrl/cli/Cargo.toml, lib/vrl/cli/src/repl.rs
Reverts vectordotdev/vector#16517
Seems to be causing build failures: https://github.com/nix-rust/nix/issues/1972
=> chore(deps): revert bump rustyline from 10.1.1 to 11.0.0

Cargo.lock, src/sinks/axiom.rs, website/content/en/highlights/2023-02-28-0-28-0-upgrade-guide.md
Closes #16493
The PR for `elasticsearch` actually implements the log namespace changes, this PR corrects the value as `elasticsearch` will always replace the `log_schema().timestamp_key()` with `@timestamp` for ES compatibility.
=> feat(axiom sink)!: Hardcode timestamp-field header to @timestamp

lib/vector-core/src/event/log_event.rs, src/sinks/datadog/events/sink.rs
`source_type` should point to a static metadata location (when using Log Namespacing), and not depend on semantic meaning
=> fix(core): Fix `LogEvent::source_type_path`

src/sinks/splunk_hec/logs/config.rs, website/cue/reference/components/sinks/base/splunk_hec_logs.cue
A recent PR broke the check component docs check on master. This fixes it.
=> docs(splunk_hec sink): generate component docs for splunk sink

lib/vector-config/src/schema.rs
Many of the schema generation functions were set up with a generic bound of `ToValue` to account for the contained default value, but that bound wasn't actually needed. This just cleans that up.
=> chore(config): Drop unused `ToValue` trait bound

Makefile
This just runs `scripts/build-ci-docker-images.sh` but that file no longer exists.
=> chore: Drop `build-ci-docker-images` make rule

src/sinks/datadog_archives.rs
Closes #16549
I left a few TODOs for possible changes we could make leveraging `meaning`s in the future, but opted to defer that work.
=> feat(datadog_archives sink): Use log namespacing and semantic meaning

src/transforms/reduce/mod.rs
Fixes flush not occuring when events arrive in high frequency (in rate faster then `expire_after` between events).
Fixes #16145.
=> fix(reduce transform): Fix flush not occuring when events arrive in high rate

src/sources/kafka.rs, website/cue/reference/components/sources/base/kafka.cue
Circling back to the PR this is reverting, I realized I was incorrect that Vector is already setting the `group.instance.id` option per my suggested test:
I think one test could be: is Vector setting the librdkafka option explicitly and do we want it to be configurable. In this case, the answer seems to be yes which means we should add a top-level option for it.
It doesn't look like Vector is currently setting that option. Given that, I don't think we actually need this new option but can just let users configure it via `librdkafka_options."group.instance.id" =  ....`
This reverts commit f90ca9e3e82b7577608b0c82a5feffb3f96d5f4c.
=> chore(kafka): revert make consumer group instance id configurable

.github/workflows/regression_trusted.yml
This commit doubles the number of Regression Detector replicates. We are working on a method to elide replicate runs automatically for experiments that have sufficient data but we want a higher maximum number of replicates. In the meanwhile, we believe that increasing the total number of replicates should address some of the 'wobble' we're seeing in some experiments here, that is, phantom dings.
=> [Single-Machine-Performance] Increase Regression Detector replicates

src/sinks/pulsar.rs, website/cue/reference/components/sinks/base/pulsar.cue
To be consistent with other sink batch options.
=> fix(pulsar sink): Rename batch size option

.github/workflows/regression_trusted.yml
This reverts #16583, which is causing the Regression Detector to hang.
=> [Single-Machine-Performance] Revert: Increase Regression Detector replicates

Cargo.lock, Cargo.toml
Closes #16504 
This adds the `openssl` feature to the `lapin` crate which allows the `amqp` components to work over tls with [CloudAMQP](https://www.cloudamqp.com/). Thanks @zamazan4ik for doing the investigation.
I am a little confused as to why this is necessary since the library should be using `native-tls` if no feature flag is specified, but I have tested it and this seems to be what is needed to make it work.
=> fix(amqp source, amqp sink): add openssl feature flag to lapin crate

Cargo.lock, Cargo.toml
=> chore(releasing): Bump Vector version to 0.29.0

src/sources/socket/tcp.rs, src/sources/socket/unix.rs, website/cue/reference/components/sources/base/socket.cue
Closes #16630 
A recent change added a default to the `max_length` config setting on the tcp socket source. Unfortunately if you have framing and `max_length` set it results in an [error](https://github.com/vectordotdev/vector/blob/master/src/sources/socket/mod.rs#L115-L116).
This removes the default for `max_length` so if it is unspecified the value remains `None`.
=> fix(socket source): remove default_max_length default

docs/DOCUMENTING.md
The `cue fmt` command references the `docs/` directory that is not used for docs written in cue (anymore). Those docs reside in the `website/` directory. Update the command to match.
=> docs(internal docs): fix cue fmt command

website/config.toml, website/layouts/partials/footer.html, website/layouts/releases/single.html
Closes: https://github.com/vectordotdev/vector/issues/16438
Seems to be working fine
=> chore(website): Add a links to footer for to the /releases and /downloads pages

Cargo.lock, Cargo.toml, scripts/integration/aws/compose.yaml, src/aws/auth.rs, src/aws/mod.rs, src/aws/region.rs, src/common/s3.rs, src/sinks/aws_cloudwatch_logs/config.rs, src/sinks/aws_cloudwatch_logs/integration_tests.rs, src/sinks/aws_cloudwatch_logs/request.rs, src/sinks/aws_cloudwatch_logs/retry.rs, src/sinks/aws_cloudwatch_metrics/mod.rs, src/sinks/aws_kinesis/firehose/config.rs, src/sinks/aws_kinesis/firehose/integration_tests.rs, src/sinks/aws_kinesis/streams/config.rs, src/sinks/aws_kinesis/streams/integration_tests.rs, src/sinks/aws_s3/integration_tests.rs, src/sinks/aws_sqs/config.rs, src/sinks/aws_sqs/integration_tests.rs, src/sinks/elasticsearch/common.rs, src/sinks/elasticsearch/service.rs, src/sinks/prometheus/remote_write.rs, src/sinks/s3_common/config.rs, src/sources/aws_s3/mod.rs, src/sources/aws_sqs/config.rs, src/sources/aws_sqs/integration_tests.rs, src/sources/aws_sqs/source.rs
- Revert "chore(deps): upgrade AWS crates to v0.54.1 (#16443)"
- Revert "chore(deps): Update aws-sdks to 0.23 and aws supporting crates to 0.53 (#16365)"
Closes #16629
Nathan and I tracked this down to a (possible) bug in the SDK, pending resolution/information upstream reverting the changes to the last known-good version we have.
=> fix(aws service): Revert AWS-SDK updates

website/cue/reference.cue
The ToC for the global options reference is broken by some headings within the docs for a certain field. Replaces the headings with **bold** text.
=> docs: replace headings with bold to fix table of contents rendering

vdev/src/testing/integration.rs
There was previous support of printing out the info level logs from Vector on the integration tests, and now it is requested to bring that functionality into vdev integration tests
This PR accomplishes the task by hardcoding the arguments in the test runner functions before they are ran.
Added the `ci-condition: integration tests enable` for testing
Closes #16367
=> feat(vdev): Support `TEST_LOG` and add `--no-capture` flag to cargo nextest

regression/cases/file_to_blackhole/experiment.yaml, regression/cases/syslog_regex_logs2metric_ddmetrics/experiment.yaml
In the days when this project used the 'soaks' we had a flag for declaring some experiments erratic, that is, when they fired we'd not ding a PR. The Regression Detector didn't expose an easy way to declare some experiments erratic and, for the most part, that worked alright. Lately we've been seeing what we call the 'wobble problem' which is vaguely co-incident to
https://github.com/DataDog/lading/pull/466 but not entirely explained by such. Capacity search made the problem more noticeable, we think.
Anyhow, this commit sets two experiments `syslog_regex_logs2metric_ddmetrics` and `file_to_blackhole` as 'erratic'. This has the same meaning as in the old days but is now exposed in a per-experiment configuration file.
REF SMP-333
=> fix(ci): Declare some Regression Detector experiments erratic

.github/workflows/regression_trusted.yml
This commit updates Single Machine Performance's `smp` tool to 0.7.2. This release includes a fix of undesirable behavior when our compute cluster is saturated, in which `smp` might allow analysis on a run that only has partial results.
REF SMP-333
=> fix(ci): Update `smp` to 0.7.2 from 0.7.1

.github/CODEOWNERS
Since this includes specifications and processes.
=> chore(dev): Adding ux-team as CODEOWNERS for docs/

docs/DEPRECATION.md
Following #16488, this updates the deprecation policy to indicate that when renaming a component we remove the documentation page for the old name and create a new one with the new page.
=> chore: Add notes on renaming components to Deprecation policy

lib/vector-lookup/src/lookup_v2/mod.rs, lib/vrl/lookup/src/lookup_v2/owned.rs
paths don't really have a reasonable default, and it's not required so it was removed
=> chore(vrl): Remove `Default` impl from owned paths

src/sinks/http.rs, website/cue/reference/components/sinks/base/http.cue
fixes: #16740
The default method was incorrectly changed to `GET` (from `POST`), in https://github.com/vectordotdev/vector/pull/16204
The code comment (and the actual #[derivative(Default)] code) is what led me to make that incorrect change.
Not sure what I was thinking.
I tracked down the history here for context:
- initially the HttpMethod enum only supported POST and PUT, and POST was set a the derivative(Default).
- then later the other http methods were added (by a separate contributor), but the derivative(Default) was not repositioned to continue to be on POST, instead it was above GET.
- then later a third unique contributor added doc comments over the enum and it's variant, re-iterating that GET was the default.
- also in play- the derivative(Default) was never actually applied, …
=> fix(http sink): restore POST as the correct default method

src/components/validation/runner/config.rs, src/components/validation/runner/mod.rs, src/components/validation/runner/telemetry.rs
There are comments in the code explaining the two fixes in detail. In summary, there are two async processes that we didn't synchronize prior to this change: a gRPC server that's the ultimate destination of metrics of all validation telemetry, and the internal metrics source that's emitting telemetry. The first issue was fixed with an explicit task collector (a wait group). The second issue was fixed by waiting for evidence of two internal metrics event emissions.
=> fix(component validation): fix two synchronization issues

src/sinks/aws_kinesis/firehose/integration_tests.rs, src/sinks/elasticsearch/config.rs, src/sinks/elasticsearch/integration_tests.rs, src/sinks/elasticsearch/mod.rs, src/sinks/elasticsearch/tests.rs, src/sinks/sematext/logs.rs
Resolves https://github.com/vectordotdev/vector/issues/16719
=> fix(elasticsearch): Fix panic in parsing `BulkConfig.index` by making `BulkConfig` non-optional.

regression/cases/enterprise_http_to_http/vector/vector.toml, regression/cases/syslog_regex_logs2metric_ddmetrics/vector/vector.toml, src/config/enterprise.rs, src/sinks/datadog/events/config.rs, src/sinks/datadog/logs/config.rs, src/sinks/datadog/metrics/config.rs, src/sinks/datadog/mod.rs, src/sinks/datadog/traces/config.rs, website/content/en/highlights/2023-04-11-0-29-0-upgrade-guide.md
Addresses the TODO introduced by https://github.com/vectordotdev/vector/pull/16280
(now that the serde alias is compatible with flatten.)
Additionally, removes the deprecated `api_key` alias.
=> chore(datadog sinks)!: extract default_api_key into shared config struct

src/sources/socket/mod.rs, src/sources/socket/tcp.rs, src/sources/socket/unix.rs, website/content/en/highlights/2023-04-11-0-29-0-upgrade-guide.md
As part of postmortem to #16630
- Downgrading terminating vector to a warning, and ignoring the `max_length` if configured in combination with framing.
- Marked this as officially deprecated
=> chore(socket source): deprecate the `max_length` setting for `tcp` and `unix` modes

Cargo.lock, Cargo.toml, src/sinks/mod.rs, src/sinks/opendal_common.rs, src/sinks/webhdfs/config.rs, src/sinks/webhdfs/integration_tests.rs, website/cue/reference/components/sinks/base/webhdfs.cue
This pull request addresses the issue of webhdfs sinks not being built.
Additionally, it updates OpenDAL to its latest version. For more information on the latest version, please refer to the following changelog: https://docs.rs/opendal/0.30.2/opendal/docs/changelog/index.html.
Close: https://github.com/vectordotdev/vector/pull/16779
=> fix(sinks): Sinks webhdfs is not built

lib/codecs/src/encoding/format/gelf.rs
This fixes #15362 
Currently using the socket sink with gelf encoding to sent to Graylog needs to have `sinks.*.encoding.timestamp_format=unix` configured but this drops sub second information from the timestamp field. The expected behavior of the gelf encoder would be to conform to the [gelf protocol](https://archivedocs.graylog.org/en/latest/pages/gelf.html) using floating point unix timestamps to encode millisecond precision as decimals.
Since Rfc3339 timestamps are not accepted bey Graylog the suggested solution is to always coerces the timestamp field to a numeric type making the `timestamp_format` config not needed. 
@neuronull suggestions are welcome
=> fix(gelf encoder): gelf encoder timestamp handling

website/cue/reference/components/sources/journald.cue
=> docs(journald source): Override default description for timestamp

README.md
Vector automatically builds and hosts Rust crate docs, but the link is not easy to discover.
The ending link tag `</a>` for all the links was also backwards, so that was fixed.
=> chore(docs): Add link to rust crate docs in README

lib/vrl/lookup/src/lookup_v2/mod.rs
Docs were added to the `lookup_v2` module (which will eventually move to the root of the crate when the lookup migration is done).
This should help explain the different path types, and when to use them.
=> chore(docs): Add docs to the `lookup` crate

src/app.rs, src/cli.rs
Breaking out more functionality from the big application methods. Pretty much all just code reorgs.
Again, probably best to view it with "hide whitespace changes" enabled.
=> chore(startup): Break up application config setup more

src/sinks/util/buffer/compression.rs
As required by https://datadoghq.atlassian.net/browse/OPB-655, the `Compression` field in for the `http` sink, when converted to JsonSchema, doesn't have a description for the second option which leads to a UI problem.
This PR just adds a description to that `oneOf` option.
=> fix(http sink): provide a description to the compression field

lib/codecs/src/encoding/format/csv.rs
Making timestamp format same with other codec such as `json`, and `vrl` display format.
=> fix(codec): format timestamp with utc in csv

.github/workflows/test.yml, lib/vector-config-common/src/schema/gen.rs, lib/vector-config-common/src/schema/json_schema.rs, src/amqp.rs, src/api/schema/events/notification.rs, src/api/schema/metrics/filter.rs, src/api/schema/metrics/host.rs, src/api/schema/sort.rs, src/aws/auth.rs, src/lib.rs, src/sinks/aws_cloudwatch_logs/request_builder.rs, src/sinks/datadog/mod.rs, src/sinks/influxdb/mod.rs, src/sinks/util/statistic.rs, src/sinks/webhdfs/mod.rs, src/sources/aws_ecs_metrics/parser.rs, src/sources/aws_kinesis_firehose/models.rs, src/sources/fluent/message.rs, src/sources/kubernetes_logs/k8s_paths_provider.rs, src/sources/kubernetes_logs/namespace_metadata_annotator.rs, src/sources/kubernetes_logs/node_metadata_annotator.rs, src/sources/kubernetes_logs/path_helpers.rs, src/sources/kubernetes_logs/pod_metadata_annotator.rs, src/sources/mongodb_metrics/mod.rs, src/sources/mongodb_metrics/types.rs
A number of RustDoc errors have crept in. This fixes them. 
This also adds a CI job to test the rust doc.
One rust doc error has been left in for now to test this CI job.
=> fix(docs): fix rustdoc errors

src/app.rs, src/cli.rs, src/signal.rs, src/vector_windows.rs
This is probably the last major change to the application setup stage, mostly focused on `ApplicationConfig`.
=> chore(startup): Break up application config setup

.github/workflows/regression_trusted.yml
This release adjusts how the `smp` program transmits data to its associated compute cluster. There are no user-facing changes in `smp`'s operation.
REF SMP-419
=> [single-machine-performance] Update `smp` to 0.7.3

src/sources/util/net/tcp/request_limiter.rs
Should resolve https://github.com/vectordotdev/vector/issues/16273
`clamp` call panics under certain situations, the `max`/`min` pair - does not (as it was written before `clamp` introduction in b56193e6769ea01cf375f90c7da57f540f609d6c (Rust 1.66 upgrade)).
=> fix(panic): fix panic under low resources

src/app.rs, src/control_server.rs, src/main.rs, src/signal.rs, src/vector_windows.rs
This breaks up the application run process into three logical phases: starting, main loop, and shutdown, each in their own method. Separate structs are used in each phase to encode the proper flow of control in the type system.
=> chore(startup): Split up `Application::run` into logical phases

website/content/en/docs/setup/installation/package-managers/dpkg.md, website/cue/reference/administration/interfaces/dpkg.cue
=> fix(docs, releasing): dpkg install docs use the correct package name

src/app.rs, src/control_server.rs, src/main.rs, src/signal.rs, src/vector_windows.rs
Reverts vectordotdev/vector#16873
This looks to maybe be causing k8s test failures. Reverting to see if they pass here.
=> chore(startup): [revert] Split up `Application::run` into logical phases

website/content/en/docs/reference/configuration/sinks/http.md, website/content/en/docs/reference/configuration/sources/http_client.md, website/content/en/docs/reference/configuration/sources/http_server.md
After getting another questions about the purpose of the http sources, I rewrote and unified the description for all three - as well as updating the tags.
We should include a "proper" way of writing descriptions in a style guide for our documentation.
=> docs: Unify the http component descriptions

src/app.rs, src/signal.rs
Making these signal functions async was a mistake. The better paradigm is to use a reference to the runtime to spawn tasks and block on rather than spuriously mark the function as async just because it has to run in a Tokio context.
Since #16873 broke the K8S E2E tests, I am breaking up that PR into individual steps to see which one might be have caused the problem. This is part 2 of (hopefully) 5.
=> chore(core): Pass an explicit runtime into functions that require it to be running

src/api/server.rs, src/app.rs, src/main.rs, src/vector_windows.rs
This separates out the step of starting the app, which is not async, from the actual async main running loop.
Since #16873 broke the K8S E2E tests, I am breaking up that PR into individual steps to see which one might be have caused the problem. This is part 3 of 5.
=> chore(startup): Break up app startup from running

lib/vrl/value/src/value.rs, lib/vrl/value/src/value/regex.rs
The `PartialEq` method was only comparing the integer portions which would result in things like
`1.4` and `1.2` matching. The custom `PartialEq` and `Hash` implementations predataded use of
`ordered_float::NotNan` for our `Value::Float` type, which provides the `Hash` and `PartialEq` trait
implementations for us. Previously we used a raw `f64` which is why these custom implementations
were necessary.
=> fix(core): Fix Value::Float comparisons

lib/vector-config/src/schema/helpers.rs
When generating the schema, Vector sets `$VECTOR_GENERATE_SCHEMA` which causes the `host_metrics` source to unconditionally emit config bits for cgroups, which are normally only present on Linux. Since, normally, Vector exits after generating the schema, this variable was never cleaned up. This change removes it immediately after generating the schema, which is useful for using the schema within a running program.
This just solves the most immediate problem. The longer term solution is to eliminate the need for this hack, but the path to that is unclear.
=> chore(config): Clean up helper environment variable after schema gen

.github/actions/spelling/excludes.txt
Had a typo in https://github.com/vectordotdev/vector/pull/16947 :(
This workflow only runs from `master` so the only way to test changes in CI is to update `master`.
=> chore(ci): Ignore gardener issue comment workflow again

src/sinks/splunk_hec/logs/integration_tests.rs
From [here](https://docs.splunk.com/Documentation/Splunk/latest/Data/Configuretimestamprecognition) by default timestamps over 2000 days old are ignored. 
This updates the integration test to calculate a date 1999 days ago to use in the test.
=> fix(splunk_hec sink): use date from 1999 days ago for auto_extracted timestamp integration test

src/sinks/axiom.rs
=> chore(axiom sink): Exit early if AXIOM_TOKEN isn't set in integration tests

src/sinks/aws_kinesis/streams/config.rs
I assumed that these lines meant that failures would be retried but it does not mean that in many cases, so let's make that explicit and describe the plans to address the behavior.
Updates #359.
Updates #7659.
Updates #16954.
=> doc(sinks/aws_kinesis): describe partial failure behavior

Cargo.lock, lib/vector-config-common/src/schema/json_schema.rs, lib/vector-config/Cargo.toml, lib/vector-config/src/schema/visitors/unevaluated.rs
In #16856, support was added for marking specific schema definitions in the overall Vector configuration schema with a field, `unevaluatedProperties`, that indicated that validation should disallow unevaluated properties: if you configure a specific component, but specified a configuration field that doesn't exist for that component, we want to emit an error during schema validation rather than silently ignore it.
In order to achieve this, a visitor implementation was created that visits the schema -- which is inherently a tree-like structure -- in a depth-first fashion, selectively marking (or unmarking) schema definitions with the aforementioned setting depending on how the schema definitions were assembled: there is some logic to when you should or shouldn't apply the setting, for …
=> fix(config): avoid resetting `unevaluatedProperties` value on subsequent visits

src/sources/kubernetes_logs/mod.rs
On startup, if Kubernetes API is unavailable or responds with an error, vector, without waiting, tries to send a request again.
Vector logs:
```
2023-03-29T17:28:32.024522Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
2023-03-29T17:28:32.024537Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
2023-03-29T17:28:32.024551Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
2023-03-29T17:28:32.024569Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
```
Pay attention to timestamps. These messages …
=> feat(kubernetes_logs): Add backoff for watchers

src/app.rs, src/topology/controller.rs, src/topology/mod.rs
This introduces the functionality required to better manage topology operations
from outside the main app routines.
This was introduced along with the experimental reload API in #15856 and subsequently removed in #16955.
=> chore(topology): Reintroduce the topology controller

src/app.rs, src/config/mod.rs, src/config/unit_test/mod.rs, src/validate.rs
The top-level `init_log_schema` function would load and parse the given config file paths and then use the `log_schema` data from that to setup the initial data. For both the run and validate commands, however, the immediate next step is to load the same config files again. This change moves the log schema init after this load step and uses the log schema from there to initialize.
=> chore(config): Simplify log schema init

src/topology/builder.rs
A tiny refactor, this function was getting a bit too long.
=> chore(topology): split `build_pieces` into smaller functions

lib/vector-buffers/src/topology/builder.rs
This missing bound on `IntoBuffer`  missed during the reintroduction of the shared topology controller #17027 prevents its full usage for Vector as a library.
=> chore(buffers): Add `Send` bound on `IntoBuffer` trait

src/transforms/reduce/mod.rs
Reverts vectordotdev/vector#16146
This is a behavior change from the documented behavior of `expire_metrics_ms` which is intended only to flush stale batches.
From the docs:
> The maximum period of time to wait after the last event is received, in milliseconds, before a combined event should be considered complete.
cc/ @tomers apologies for not catching this earlier during the PR review. We'll need to resolve your use-case another way to also preserve the existing behavior.
=> fix(reduce transform): Revert flushing on interval change to `expire_metrics_ms`

Cargo.lock
Accidentally pulled in more changes than desired as part of picking the v0.28.2 release commits to
master.
=> chore(deps): Reset dependencies bumped by a61dea1

lib/vector-buffers/src/variants/disk_v2/reader.rs, lib/vector-buffers/src/variants/disk_v2/tests/initialization.rs, lib/vector-buffers/src/variants/disk_v2/tests/mod.rs
In some cases, a buffer can fail to reopen after Vector has been stopped in an impromptu fashion, due to a partially-written record that causes the reader to loop endlessly, waiting for data that can't possibly arrive.
Fixes #16525, #16463, and #16231.
In this PR, we've simply piggybacked on some existing logic in the reader -- logic which decides whether or not it should keep waiting for data or should return that there wasn't enough data -- in order to avoid endlessly looping during the buffer initialization phase.
This ensures that when we indicate that the read should be "finalized" -- either the writer is done or we're still getting the buffer initialized -- and there's either not enough data to read the length delimiter, or there's not as many bytes as the length delimiter indicates …
=> fix(buffers): correctly handle partial writes in reader seek during initialization

.github/workflows/integration-test.yml
The test is failing on master, seemingly the root CA is not trusted in the debian CA store.
=> chore(ci): Disable `appsignal` integration test until CA issues are resolved

.github/workflows/integration-test.yml
The AppSignal endpoint certificate has been repaired.
=> chore(ci): re-enable `appsignal` integration test

Cargo.lock, vdev/Cargo.toml, vdev/src/commands/release/github.rs
Since this was moved to vdev, we lost the automatic shell globbing. This introduces the `glob` crate
to handle it. I tested it locally by swapping `gh` with `echo` and adding dummy files:
```
vector on  v0.29 [$!] is 📦 v0.29.0 via  v19.4.0 via 💎 v2.7.4 via 🦀 v1.66.1 on ☁️
❯ touch target/artifacts/{foo,bar}
vector on  v0.29 [$!] is 📦 v0.29.0 via  v19.4.0 via 💎 v2.7.4 via 🦀 v1.66.1 on ☁️
❯ cargo vdev release github
release --repo vectordotdev/vector create v0.29.0 --title v0.29.0 --notes [View release notes](https://vector.dev/releases/0.29.0) target/artifacts/bar target/artifacts/foo
```
=> fix(releasing): Fix globbing of release artifacts for GitHub

.github/workflows/install-sh.yml
the `18.04` ubuntu runner is now unsupported.
Two years ago this specific runner was selected for this workflow job due to apparent problems with 20.04.
Hopefully those have been resolved by now.
Ref failure: https://github.com/vectordotdev/vector/actions/runs/4660291736
=> chore(ci): update unsupported ubuntu version runners

.github/workflows/install-sh.yml
to fix
```
Run sudo apt-get install --yes python3-setuptools python3.6-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python3.[6](https://github.com/vectordotdev/vector/actions/runs/4672570181/jobs/8274890659#step:3:7)-dev
E: Couldn't find any package by glob 'python3.6-dev'
E: Couldn't find any package by regex 'python3.6-dev'
```
=> chore(ci): use python v3.8 in ubuntu 20.04 runner

.github/workflows/install-sh.yml
```
Run sudo apt-get install --yes python3-setuptools python3.8-dev
Reading package lists...
Building dependency tree...
Reading state information...
python3-setuptools is already the newest version (45.2.0-1ubuntu0.1).
python3.8-dev is already the newest version (3.8.10-0ubuntu1~20.04.7).
python3.8-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
```
=> chore(ci): remove unnecessary dep install

vdev/src/commands/release/homebrew.rs, vdev/src/git.rs
First commit is just `rustfmt` so you can focus on reviewing the others.
=> chore(releasing): Fix homebrew release script

scripts/build-docker.sh, scripts/release-s3.sh, vdev/src/app.rs, vdev/src/commands/build/publish_metadata.rs, vdev/src/commands/release/channel.rs
Fixes: https://github.com/vectordotdev/vector/issues/17129
=> chore(releasing): Fix release channels

Cargo.lock, Cargo.toml
=> chore(releasing): Bump Vector version to 0.30.0

lib/vector-config-macros/src/configurable_component.rs
Using `typetag` and the naive capitalization strategy caused a number of names to be incorrectly capitalized on the Datadog documentation.
This is a quick resolution to unblock the docs team while we create a more explicit field to be used by both OP and the documentation.
=> docs: Add a quickfix to handle special capitalization cases

Cargo.lock, Cargo.toml, src/sources/kubernetes_logs/mod.rs, website/cue/reference/components/sources/base/kubernetes_logs.cue
This PR adds an option that allows reading data directly from the Kubernetes API server cache than hitting the etcd quorum. It can significantly reduce Kubernetes control plane memory pressure in exchange for a chance of receiving stale data.
Updated versions:
* kube-rs-> [0.82](https://github.com/kube-rs/kube/releases/tag/0.82.0) 
* k8s-openapi -> [0.18](https://github.com/Arnavion/k8s-openapi/releases/tag/v0.18.0)
Fixes https://github.com/vectordotdev/vector/issues/16797
(More info can be found by checking the original kube-rs PRs for the list semantic option).
=> feat(kubernetes_logs): use kube-apiserver cache for list requests

src/sinks/appsignal/mod.rs, website/cue/reference/components/sinks/base/appsignal.cue
This allows users to configure TLS settings for the AppSignal sink.
Closes #17112
=> fix(appsignal sink): Add TLS config option

.github/actions/spelling/patterns.txt, lib/vector-core/src/config/proxy.rs
Ref: #17125
This adds the unit test proposed. It fails as expected, marking ignored so we can remove that line when the issue is worked on.
Before the ignore:
```
running 1 test
test config::proxy::tests::build_proxy_with_special_chars_url_encoded ... FAILED
failures:
---- config::proxy::tests::build_proxy_with_special_chars_url_encoded stdout ----
thread 'config::proxy::tests::build_proxy_with_special_chars_url_encoded' panicked at 'assertion failed: `(left == right)`
left: `Some("Basic dXNlcjpQJTQwc3N3MHJk")`,
right: `Some("Basic dXNlcjpQQHNzdzByZA==")`', lib/vector-core/src/config/proxy.rs:374:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After the ignore:
```
running 1 test
test config::proxy::tests::build_proxy_with_special_chars_url_encoded ... …
```
=> enhancement(core): add unit test (ignored) for support for encoding special chars in `ProxyConfig`

src/sinks/influxdb/logs.rs, src/sinks/influxdb/mod.rs
When trying to sink log without tags into influxdb, influxdb will error out `expected tag key after comma`. Which means the comma `,` should be omitted if there are no tags.
```
logs, message="hello world" # current behavior, which is invalid
logs message="hello world"  # expected behavior
```
Close #17020
=> fix(influxdb_logs): encode influx line when no tags present

.github/actions/spelling/expect.txt, lib/vector-config/src/schema/helpers.rs, lib/vector-config/src/schema/visitors/mod.rs, lib/vector-config/src/schema/visitors/unevaluated.rs
The `DisallowUnevaluatedPropertiesVisitor` visitor handles marking individual schemas, within the overall configuration schema for Vector, to disallow unevaluated properties from being allowed when validating a configuration against said schema.
This involves a chunk of logic to figure out the right schema to place the annotation on, as depending on how schemas are referenced, or combined together, the annotation might need to be added to a parent schema rather than all of its child schemas, and so on.
This logic checks if schemas can be marked with annotation by determining if they represent an object -- aka a struct -- and in doing so, knows how to check if the schema is an object schema, or if it _refers_ to an object schema by way of using _schema references_: a pointer to a schema …
=> fix(config): recurse through schema refs when determining eligibility for unevaluated properties

src/sinks/webhdfs/config.rs, src/sinks/webhdfs/mod.rs
This was being pulled into the `webhdfs` description in the OP docs, rather than just the usual "configuration for the foo component"
=> docs: Adjust doc comment locations

lib/codecs/src/decoding/mod.rs, src/sinks/webhdfs/config.rs, src/sources/docker_logs/mod.rs, website/cue/reference/components/sinks/base/webhdfs.cue, website/cue/reference/components/sources/base/amqp.cue, website/cue/reference/components/sources/base/aws_kinesis_firehose.cue, website/cue/reference/components/sources/base/aws_sqs.cue, website/cue/reference/components/sources/base/datadog_agent.cue, website/cue/reference/components/sources/base/demo_logs.cue, website/cue/reference/components/sources/base/docker_logs.cue, website/cue/reference/components/sources/base/exec.cue, website/cue/reference/components/sources/base/file_descriptor.cue, website/cue/reference/components/sources/base/gcp_pubsub.cue, website/cue/reference/components/sources/base/heroku_logs.cue, website/cue/reference/components/sources/base/http.cue, website/cue/reference/components/sources/base/http_server.cue, website/cue/reference/components/sources/base/kafka.cue, website/cue/reference/components/sources/base/nats.cue, website/cue/reference/components/sources/base/redis.cue, website/cue/reference/components/sources/base/socket.cue, website/cue/reference/components/sources/base/stdin.cue
Doc style edits for WebHDFS and a couple of edits missed previously.
=> chore(docs): make doc style edits

website/content/en/highlights/2023-02-28-0-28-0-upgrade-guide.md
Ref: https://github.com/vectordotdev/vector/issues/17147
=> chore(docs): update the `v0.28.0` upgrade guide with note about `datadog_logs` sink `hostname` key

lib/codecs/src/decoding/framing/newline_delimited.rs, lib/codecs/src/decoding/framing/octet_counting.rs, src/sources/socket/mod.rs, src/sources/socket/tcp.rs, src/sources/socket/udp.rs, src/sources/socket/unix.rs, website/content/en/highlights/2023-05-23-0-30-0-upgrade-guide.md, website/cue/reference/components/sources/base/socket.cue
This setting was officially marked deprecated in v0.29.0 and being removed for v0.30.0.
Note that the `udp` mode still has this as a valid option.
We had marked the entire option deprecated as there wasn't a way to distinguish them.
=> chore(socket source): Remove deprecated `max_length` setting from `tcp` and `unix` modes.

website/content/en/docs/about/concepts.md
Removes a trailing quote that doesn't match an opening quote.
I believe it's a typo.
=> chore(docs): Remove trailing, unmatched quote

Cargo.lock, lib/vector-config-common/Cargo.toml, lib/vector-config-common/src/constants.rs, lib/vector-config-common/src/human_friendly.rs, lib/vector-config-common/src/lib.rs, lib/vector-config-macros/Cargo.toml, lib/vector-config-macros/src/configurable_component.rs, lib/vector-config/Cargo.toml, lib/vector-config/src/component/description.rs, lib/vector-config/src/schema/helpers.rs, lib/vector-config/src/schema/visitors/human_name.rs, lib/vector-config/src/schema/visitors/mod.rs, lib/vector-config/src/schema/visitors/test.rs, src/sinks/mod.rs
In many cases, the generated name for an enum variant in the configuration schema (`logical_name`) is suboptimal as it is not human-friendly: there's no spacing, or the casing is awkward because of rules around naming imposed by Rust itself. Additionally, but unrelatedly, the same principle applies to struct field names, and their resulting property names in the schema, as we're stuck with simply exposing the raw field name, where we want a more human-friendly description for it.
In #16467, the `docs::label` metadata attribute was added for providing a human-friendly name for the enum variants that contained all configurable components in Vector. Over time, as part of the work to extend component registration to once again be dynamic, this attribute has been lost due to needing to once …
=> chore(config): emit human-friendly version of enum variant/property names in schema

Cargo.lock
cargo deny is flagging vulernability in h2, and thus the checks are failing.
https://github.com/vectordotdev/vector/actions/runs/4758498516/jobs/8456646415
See https://github.com/hyperium/hyper/issues/2877#issuecomment-1507135950
=> chore(deps): Update h2

src/sources/syslog.rs
Ref #16818
Whilst going over the postmortem for this bug I noticed that removing this field is not necessary in order to make the tests pass.
=> chore(syslog source): remove the remove of source_ip

src/docker.rs
Fix error when using DOCKER_HOST with tcp schema
Example of DOCKER_HOST with tcp: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option
=> fix(docker.rs): configuration error on DOCKER_HOST="tcp://..."

distribution/docker/distroless-libc/Dockerfile
Hello ! :wave: 
Very simple PR to upgrade the Debian version in the distroless-libc Dockerfile (the first image is Debian 11 but the final one if Debian 10, hence the presence of vulnerabilities)
=> chore(deps): Upgrade Debian to bullseye for distroless image

.gitignore
It is useful to extend the global helix configurations for project specific needs, for example you can add feature flags to be compiled. For example when adding or modifying integration tests.
=> chore(dev): ignore `.helix` dir

docs/DOCUMENTING.md, scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore(deps): Upgrade cue to 0.5.0

website/package.json
Seems to build and run fine without it.
=> chore(docs): Remove unneeded `yaml` dependency from website

scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore(dev): Install the correct `mold` based on CPU architecture

docs/DEVELOPING.md
This adds a note to `DEVELOPING.md` to say we shouldn't panic unless we absolutely have to.
=> chore: add note to DEVELOPING.md re panics

.gitignore
As pointed out here: https://github.com/vectordotdev/vector/pull/17203#discussion_r1175791563
, developers should just utilize a global gitignore for things like personal editor configs.
=> chore(dev): remove editors from gitignore

.github/workflows/baseline.yml
We haven't focused on this as much lately so dropping this back to just on demand.
=> chore(ci): Disable scheduled runs of Baseline Timings workflow

src/internal_events/tag_cardinality_limit.rs, src/transforms/tag_cardinality_limit/mod.rs
This patch addresses issue #15742 by adding the `metric_name` field to internal logs issued by the tag_cardinality_limit component.
=> feat: adds 'metric_name' field to internal logs for the tag_cardinality_limit component

src/sinks/gcp/stackdriver_metrics.rs
Closes #17263
Looks to have just been missed for this one sink, the other four GCP sinks appear to be calling it correctly. It strikes me that we should try and share more of the code between these sinks where possible to avoid these sorts of issues slipping in.
=> fix(gcp_stackdriver_metrics sink): Call function to regenerate auth token

src/transforms/sample.rs, src/transforms/throttle.rs, website/cue/reference/components/transforms/base/sample.cue, website/cue/reference/components/transforms/base/throttle.cue
The current wording is somewhat confusing. I'm hopeful that this new wording is more clear.
=> chore(docs): Clarify `key_field` for `sample` and `throttle` transforms

website/cue/reference/components/transforms/base/sample.cue, website/cue/reference/components/transforms/base/throttle.cue
#17372 broke CI due to suggestions added during review, which didn't have a following component doc regeneration
=> chore: Regen docs for sample and throttle

lib/tracing-limit/src/lib.rs
To use the word "suppressed" when messages are being suppressed. This is similar to SystemD and, we
think, will be less likely to confuse users into thinking that their event processing is being
suppressed.
=> enhancement(observability): Update internal log rate limiting messages

lib/vector-common/src/finalizer.rs, src/sources/kafka.rs
- fix(kafka source): Bias the tokio::select
- chore: Reorder finalizer tokio::select to remove existing finalizers before adding new finalizers
Might close #17276
=> Improve tokio::select behavior for kafka source and finalizers

.github/actions/spelling/expect.txt, docs/CONTRIBUTING.md, vdev/src/commands/check/licenses.rs
Also have the check command output how to fix it to guide contributors.
=> chore(dev): Add note about generating licenses to CONTRIBUTING.md

docs/USER_EXPERIENCE_DESIGN.md
Will need to be updated when log namespacing is released.
Ref: https://github.com/vectordotdev/vector/issues/17147
=> chore: Add UX note about encoding of log_schema keys

.github/workflows/integration-test.yml, .github/workflows/k8s_e2e.yml, Makefile
Noticed this still being used in a couple of places that it didn't need to be (it was only useful
for Github hosted runners with tight disk contraints). Once I removed them I found it wasn't being
used anywhere so removed the `make` task.
Saves roughly 3 minutes per test.
=> chore(ci): Remove ci-sweep tasks

src/transforms/aws_ec2_metadata.rs
These were comparing metadata which broke after https://github.com/vectordotdev/vector/pull/17369 since the metadata (like cached estimated JSON size) were, expectedly, different.
=> chore(ci): Fix event assertions for `aws_ec2_metadata` transform

website/config.toml
Having Support link to Observability Pipelines has proven to be confusing to users now that it is
separate from Vector. Instead I link to /community and then add an Enterprise link to point to
Observability Pipelines.
=> chore(docs): Add Enterprise link and update Support link

lib/vector-core/src/transform/mod.rs, src/sinks/humio/metrics.rs, src/sources/kubernetes_logs/parser/cri.rs, src/sources/kubernetes_logs/parser/docker.rs, src/sources/kubernetes_logs/parser/mod.rs, src/sources/kubernetes_logs/parser/test_util.rs, src/transforms/metric_to_log.rs
This is just breaking some of the direct coupling that we have to the current `Transform` design, making it a bit easier to change moving forward.
=> chore: remove transform type coercion

src/aws/auth.rs, src/sinks/aws_kinesis/firehose/integration_tests.rs, src/sinks/elasticsearch/integration_tests.rs
=> enhancement(aws provider): Let `region` be configured for default authentication

src/sources/fluent/mod.rs
Fluent ack messages were sent as plain JSON instead of msgpack format.
This is a fix for https://github.com/vectordotdev/vector/issues/17427
Without the fix, fluent-bit shows this error:
`[2023/05/16 15:16:06] [error] [output:forward:forward.0] ACK response not MAP (type:2)`
With the fix, this fluent-bit debug line is shown:
`[2023/05/16 15:16:40] [debug] [output:forward:forward.0] protocol: received ACK 47d92c1eb2dbd7f5f1ef8e6130392c66`
=> fix(fluent source): fix ack message format

.github/workflows/k8s_e2e.yml
Restricts the running of k8s tests.
We now run all versions once nightly on weeknights.
Otherwise,  run only the latest version.
To track the workflow, we will setup the slack GH App to subscribe to the workflow.
=> chore(ci): restrict k8s workflow runs

.github/dependabot.yml
We seem to be bumping up against this causing dependabot to space out updates. I don't see a great
reason to limit it, but could be missing something since it does have a fairly low default limit of
5.
=> chore(deps): Bump PR limit for Dependabot to 100

Cargo.lock
Fixes a compile-time warning about code being incompatible with future versions of Rust.
=> chore(deps): Update fs_extra to 1.3.0

Cargo.lock
Fixes compile-time warning about lalrpop using code that won't be compatible with newer versions of
Rust.
=> chore(deps): Bump lalrpop to 0.19.12

docs/specs/component.md
Also refactors the event lists so that they each have an `Emission` line.
=> chore(docs): Clarify when component received and sent bytes events should be emitted

Cargo.lock, Cargo.toml
Now that 0.30.0 has been released.
=> chore: Bump version to 0.31.0

.github/workflows/publish.yml
The syntax of the conditional for the publish workflow's failure notification job had a bug where an explicit expression was defined and was paired with an implicit expression. This resulted in the job running when it shouldn't.
Removed the explicit expression syntax from the other job conditionals to avoid potentially doing that in the future.
=> chore(ci): fix failure notify job conditional in publish workflow

.github/workflows/comment-trigger.yml
GitHub Support requested we try disabling the concurrency group to see if it resolves the issue of the workflow failing to start.
=> chore(ci): temporarily disable comment_trigger workflow

src/config/loading/secret.rs, src/config/mod.rs, src/config/vars.rs
Ref OPB-710
This PR
- Exposes patterns and the `interpolate` function for use in OPW. This will help deduplicate some logic and reduce maintenance burden. We use the patterns themselves in secret scanning logic, and will use the `interpolate` function in bootstrap-related logic.
=> chore(enterprise): Extend library functionality for secret scanning

distribution/install.sh
The patterns were incorrectly matching the the OS for ARMv7 builds which have extra chacters
indicating platform support.
Fixes: https://github.com/vectordotdev/vector/issues/17450
=> fix(distribution): Fix architecture detection for ARMv7

src/aws/mod.rs
While attempting to update `aws-smithy-async` (https://github.com/vectordotdev/vector/pull/17472) I noticed the SDK now provides an implementation of `AsyncSleep` for tokio, so our custom implementation is no longer needed.
=> chore: remove custom async sleep impl

license-tool.toml
Ref: https://github.com/vectordotdev/vector/pull/17378#pullrequestreview-1424780253
=> chore(ci): Drop VRL license exceptions

.github/workflows/integration.yml, .github/workflows/test.yml
- Test Suite and Integration Test Suite are required checks for CI, so their jobs always need to run (relevant if dependent job failed) to correctly mark the final status.
=> fix(ci): add missing logic to mark required checks failed

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv
Still need the hack to drop the `oldtime` feature.
=> chore(deps): Bump chrono to 0.4.26

README.md, netlify.toml, website/cue/reference/urls.cue
Discovered by https://github.com/vectordotdev/vector/issues/17547#issuecomment-1570289321
We dropped the public roadmap as it seemed to be doing more harm than good as it proved not to be
terribly accurate as priorities shift.
=> chore: Remove links to roadmap

src/sinks/redis.rs, src/sinks/vector/sink.rs
Ref #17465 
There were a couple of outstanding issues from the above PR. 
1. The redis sink was counting the network bytes before actually creating the bytes, so the count was always zero.
2. The Vector sink was not counting the `JsonSize` of the event. The comment saying this was not being used was incorrect.
=> fix(observability): correct emitted metrics

lib/vector-config-common/src/human_friendly.rs, lib/vector-core/src/tcp.rs, src/sources/apache_metrics/mod.rs, src/sources/aws_ecs_metrics/mod.rs, src/sources/aws_kinesis_firehose/mod.rs, src/sources/aws_s3/sqs.rs, src/sources/aws_sqs/config.rs, src/sources/gcp_pubsub.rs, src/sources/http_client/client.rs, src/sources/kafka.rs, src/sources/opentelemetry/mod.rs, src/sources/prometheus/scrape.rs, src/sources/splunk_hec/acknowledgements.rs, src/sources/util/multiline_config.rs, src/transforms/aggregate.rs, src/transforms/reduce/mod.rs, src/transforms/remap.rs, src/transforms/tag_cardinality_limit/config.rs, src/transforms/throttle.rs, website/cue/reference/components/sources/base/aws_kinesis_firehose.cue, website/cue/reference/components/sources/base/splunk_hec.cue
This PR updates the commonly used sources and transforms' field labels that needs a human_name label. Similar to this [PR](https://github.com/vectordotdev/vector/pull/17475).
=> chore(config): Update field labels for commonly used sources and transforms 

scripts/integration/http-client/compose.yaml, scripts/integration/http-client/test.yaml
- `dufs` a dep of the integration test, had a breaking change to the auth syntax
- pegged the version to a specific release since this component isn't tied to a specific service
=> fix(http_client source): adapt int test to use breaking change of dep

docs/specs/configuration.md
Codifying the status quo since there wasn't a strong motivator to change it and we want to maintain
consistency.
=> chore: Codify the use of abbreviate time units in config option names

docs/specs/configuration.md
Starting with `SHOULD` while we feel this out some more. Might change to `MUST` once we build up
more confidence.
=> chore: Codify flag naming including sentinel values

Cargo.lock, Cargo.toml, src/sinks/pulsar/config.rs, website/cue/reference/components/sinks/base/pulsar.cue
- Bumps [pulsar](https://github.com/streamnative/pulsar-rs) from 5.1.1 to 6.0.0.
- As part of this, a new config option for batch `max_bytes` is exposed for the sink.
=> chore(deps): bump pulsar from 5.1.1 to 6.0.0

src/sinks/loki/event.rs, src/sinks/loki/sink.rs
Currently the `loki` sink is encoding the event and then taking the estimated json size of that encoded event. This is wrong. All sinks should take the estimated json size of the unencoded event.
There is an open question around whether we should be taking the json size before or after the `only_fields` and `except_fields` are applied. I'm currently trying to get an answer to that. Currently everything is before.
The `loki` sink works a little bit different to the other stream based sinks. Most sinks pass the event unencoded to the request builder. It is at this point that the json size of the metrics are calculated.  However, `loki` encodes the event and passes the encoded value to the request builder. 
This PR changes it so it also passes the json size to the request builder so it can …
=> fix(loki sink): use json size of unencoded event

docs/tutorials/sinks/1_basic_sink.md, docs/tutorials/sinks/2_http_sink.md, src/internal_events/mod.rs, src/sinks/amqp/config.rs, src/sinks/amqp/encoder.rs, src/sinks/amqp/request_builder.rs, src/sinks/amqp/service.rs, src/sinks/amqp/sink.rs, src/sinks/aws_kinesis/config.rs, src/sinks/aws_kinesis/firehose/config.rs, src/sinks/aws_kinesis/service.rs, src/sinks/aws_kinesis/sink.rs, src/sinks/aws_kinesis/streams/config.rs, src/sinks/kafka/config.rs, src/sinks/kafka/service.rs, src/sinks/kafka/sink.rs, src/sinks/kafka/tests.rs, src/sinks/loki/config.rs, src/sinks/loki/event.rs, src/sinks/loki/service.rs, src/sinks/loki/sink.rs, src/sinks/loki/tests.rs, src/sinks/mod.rs, src/sinks/prelude.rs, src/sinks/pulsar/config.rs, src/sinks/pulsar/request_builder.rs, src/sinks/pulsar/service.rs, src/sinks/pulsar/sink.rs, src/sinks/util/encoding.rs
Generally our stream based sinks will share a lot of imports. This adds a `crate::sinks::prelude` module that can be imported to bring in the commonly used imports. The advantage is not only reducing the size of our imports and making it easier to maintain (often changes to the framework result in having to change the imports of all the sinks modules which is tedious) but it also encourages and guides using the shared components available.
This also updates the following sinks to use the prelude:
- amqp
- kafka
- aws_kinesis
- loki
- pulsar
=> chore: add sink prelude

.github/workflows/regression.yml
- Forces a greater depth when checking out the PR branch.
- This can later be improved to try a smaller depth, and keep increasing that until the base sha is found.
=> fix(ci): checkout a greater depth in regression workflow

src/sinks/prometheus/remote_write.rs, website/cue/reference/components/sinks/base/prometheus_remote_write.cue, website/cue/reference/components/sinks/prometheus_remote_write.cue, website/cue/reference/urls.cue
Resolves https://github.com/vectordotdev/vector/issues/17199
- add Zstd and Gzip support to Prometheus Remote Write
- add a new compression option in the config (Snappy is the default)
- update the documentation
Tested:
- Local build
=> feat(prometheus): add more compression algorithms to Prometheus Remote Write

lib/vector-core/src/sink.rs, src/config/unit_test/unit_test_components.rs, src/sinks/appsignal/mod.rs, src/sinks/aws_cloudwatch_metrics/mod.rs, src/sinks/azure_monitor_logs.rs, src/sinks/clickhouse/http_sink.rs, src/sinks/gcp/pubsub.rs, src/sinks/gcp/stackdriver_logs.rs, src/sinks/gcp/stackdriver_metrics.rs, src/sinks/honeycomb.rs, src/sinks/http.rs, src/sinks/influxdb/logs.rs, src/sinks/influxdb/metrics.rs, src/sinks/mezmo.rs, src/sinks/prometheus/remote_write.rs, src/sinks/redis.rs, src/sinks/sematext/metrics.rs, src/sinks/util/adaptive_concurrency/tests.rs, src/test_util/mock/sinks/error.rs, src/test_util/mock/sinks/panic.rs
This will help steer contributors away from writing new sinks in the deprecated fashion.
See https://github.com/vectordotdev/vector/issues/9261 for more context.
=> chore(sinks): mark VectorSink::from_event_sink as deprecated

Cargo.lock, lib/enrichment/Cargo.toml, lib/enrichment/src/find_enrichment_table_records.rs, lib/enrichment/src/get_enrichment_table_record.rs
We need to use enrichment tables in `vrl-wasm` and pulling vector-common is not needed so better not using it.
=> chore(enrichment): avoid importing vector-common in enrichment module

lib/vector-buffers/src/variants/disk_v2/reader.rs, lib/vector-buffers/src/variants/disk_v2/tests/initialization.rs, lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs, lib/vector-buffers/src/variants/disk_v2/tests/mod.rs
In #17644, a user reported disk buffers getting stuck in an infinite loop, and thus deadlocking, when restarting after a crash. They provided some very useful debug information, going as far to evaluate, add some logging, and get some values of internal state for the reader.
When a disk buffer is initialized -- either for the first time or after Vector is restarted and the buffer must resume where it left off -- both the reader and writer perform a catch-up phase. For the writer, it checks the current data file and tries to figure out if the last record written matches where it believes it left off. For the reader, it actually has to dynamically seek to where it left off within the the given data file, since we can't just open the file and start from the beginning: data files are …
=> fix(buffers): deadlock when seeking after entire write fails to be flushed

distribution/install.sh
Closes #17681 
Without `shift`ing the other possible input arguments, the `--prefix` argument will set the `prefix` incorrectly. When using [the official Docker example](https://vector.dev/docs/setup/installation/#installation-script), arguments of `-y --prefix` will result in the following error:
```
mkdir: unrecognized option '--prefix'
```
...as `"$2"` is `--prefix`, because `-y` was never `shift`ed out.
Adding a `shift` to the other arguments correctly removes them from the argument list when parsed.
=> fix(install.sh): Correctly `shift` all parsed arguments

scripts/cross/bootstrap-ubuntu.sh
To see if this helps with flakey apt installs.
=> chore(ci): Add apt retries to cross builds

lib/codecs/src/decoding/format/gelf.rs, lib/codecs/src/decoding/format/json.rs, lib/codecs/src/decoding/format/mod.rs, lib/codecs/src/decoding/format/native_json.rs, lib/codecs/src/decoding/format/syslog.rs, lib/codecs/src/decoding/mod.rs, lib/codecs/tests/native.rs, src/components/validation/resources/mod.rs, src/config/mod.rs, src/sources/datadog_agent/tests.rs, src/sources/http_client/integration_tests.rs, src/sources/syslog.rs, website/cue/reference/components/sources/base/amqp.cue, website/cue/reference/components/sources/base/aws_kinesis_firehose.cue, website/cue/reference/components/sources/base/aws_s3.cue, website/cue/reference/components/sources/base/aws_sqs.cue, website/cue/reference/components/sources/base/datadog_agent.cue, website/cue/reference/components/sources/base/demo_logs.cue, website/cue/reference/components/sources/base/exec.cue, website/cue/reference/components/sources/base/file_descriptor.cue, website/cue/reference/components/sources/base/gcp_pubsub.cue, website/cue/reference/components/sources/base/heroku_logs.cue, website/cue/reference/components/sources/base/http.cue, website/cue/reference/components/sources/base/http_client.cue, website/cue/reference/components/sources/base/http_server.cue, website/cue/reference/components/sources/base/kafka.cue, website/cue/reference/components/sources/base/nats.cue, website/cue/reference/components/sources/base/redis.cue, website/cue/reference/components/sources/base/socket.cue, website/cue/reference/components/sources/base/stdin.cue
Adds a `lossy` option to the relevant deserializers.
=> feat(codecs): add lossy option to `gelf`, `native_json`, and `syslog` deserializers

Cargo.lock, vdev/Cargo.toml, vdev/src/testing/config.rs
The version bump to `hashlink` is causing an issue for licensing, and we more commonly use the equivalent `indexmap` crate already, so just move the usage in `vdev` to that crate.
=> chore(deps): Drop use of `hashlink` crate

src/sources/http_client/client.rs
Fixes: https://github.com/vectordotdev/vector/issues/16814
This change is a now a no-op thanks to https://github.com/vectordotdev/vector/pull/17628 and https://github.com/vectordotdev/vector/pull/17688.
=> fix(http_client source): remove utf8 lossy conversion

.github/ISSUE_TEMPLATE/minor-release.md, distribution/docker/alpine/Dockerfile, distribution/docker/distroless-static/Dockerfile
Also added a note to the release checklists to look for new versions. Ideally dependabot could help
us keep up-to-date here.
=> chore(deps, releasing): Update to Alpine 3.18

Cargo.lock, lib/vector-config-common/Cargo.toml, lib/vector-config-common/src/schema/mod.rs, lib/vector-config/src/schema/visitors/inline_single.rs, lib/vector-config/src/schema/visitors/merge.rs, lib/vector-config/src/schema/visitors/unevaluated.rs, regression/Dockerfile
Key/value maps in the config schema currently use an `IndexMap`. This provides for stable ordering of the output between runs. Unfortunately, due to the use of initializers via `inventory`, that ordering is dependent on the order in which those initializers are run, which is in turn dependent on the choices the linker (and link-time optimization) makes when building Vector. The result is that config schemas can be very hard to compare between builds due to large blocks of it moving around in the output file.
This change changes this type to a `BTreeMap`, which is fully ordered internally. This will result in a consistent ordering of maps, hopefully producing config schema output that is more consistent.
=> chore(config): Make config schema output ordered

src/sinks/aws_s3/integration_tests.rs
Adding regression test for related issue: https://github.com/vectordotdev/vector/issues/11405
=> chore(flush on shutdown): validate s3 sink flushes

lib/vector-core/src/config/proxy.rs, src/http.rs
fix(auth): Vector does not put the Proxy-Authorization header on the wire (#17353) 
closes: #17353
=> fix(auth): Vector does not put the Proxy-Authorization header on the wire (#17353)

.github/workflows/test.yml
This check seems to be flakey but we haven't been able to reliably reproduce. Just retry for now. In
the future we hope to rewrite this script into Rust.
=> chore(ci): Retry `make check-component-docs` check

src/app.rs
I wasn't able to trigger this message on 0.30.0 so it may not even be relevant anymore, but at least
use the configured log level.
Closes: #1391
=> chore(observability): Have `tower_limit` use configured log level

website/cue/reference/components/sinks/datadog_traces.cue
Tracking issue for enhancement: https://github.com/vectordotdev/vector/issues/17732
=> chore(datadog_traces sink): Add additional warning around APM stats for `peer.service`

lib/vector-vrl/cli/src/main.rs, src/app.rs, src/main.rs, src/vector_windows.rs
Issue: [Exit non-zero when Vector fails to gracefully shutdown](https://github.com/vectordotdev/vector/issues/13731)
=> feat(error code when shutdown fails): set exit flag to non-zero when shutdown times out

.github/workflows/test.yml
Since the flakey test seems to have been resolved by
https://github.com/vectordotdev/vector/pull/17722 . We can bring it back if that turns out not to be
the case.
=> chore(ci): Remove upload of config schema

lib/vector-vrl/functions/src/set_semantic_meaning.rs, src/transforms/remap.rs
The `set_semantic_meaning` function didn't support setting meanings that point to metadata. This will be needed when log namespacing is enabled.
=> feat: add metadata support to `set_semantic_meaning`

website/cue/reference/components/sources.cue
I'm not aware of any sources that separate "steam segments" so I updated the language a bit to
account for how the `tcp` mode of the `socket` source handles `bytes` framing.
Reference: https://github.com/vectordotdev/vector/issues/17136
=> chore(docs): Clarify `bytes` framing for streams

src/internal_events/template.rs
If a render error doesn't result in a dropped event, it seems more like a warning than an error.
For the places that currently emit template errors with `drop_event: false`:
* `loki` sink: skips inserting label if key or value fails to render; falls back to `None` for
partitioning using `tenant_id`
* `throttle` transform: falls back to `None` for throttle key
* `log_to_metric` transform: skips tag addition
* `papertrail` sink: falls back to `vector` for the `process` field
* `splunk_hec_logs` sink: falls back to `None` for partition keys (source, sourcetype, index)
* `splunk_hec_metrics` sink: falls back to `None` for source, sourcetype, index
Fixes: #17487
=> fix(loki sink, observability): Drop non-fatal template render errors to warnings

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, src/aws/auth.rs, src/aws/mod.rs, src/aws/region.rs, src/common/s3.rs, src/sinks/aws_cloudwatch_logs/config.rs, src/sinks/aws_cloudwatch_logs/integration_tests.rs, src/sinks/aws_cloudwatch_logs/request.rs, src/sinks/aws_cloudwatch_logs/retry.rs, src/sinks/aws_cloudwatch_metrics/mod.rs, src/sinks/aws_kinesis/firehose/config.rs, src/sinks/aws_kinesis/firehose/integration_tests.rs, src/sinks/aws_kinesis/streams/config.rs, src/sinks/aws_kinesis/streams/integration_tests.rs, src/sinks/aws_s3/integration_tests.rs, src/sinks/aws_sqs/config.rs, src/sinks/aws_sqs/integration_tests.rs, src/sinks/elasticsearch/common.rs, src/sinks/elasticsearch/service.rs, src/sinks/prometheus/remote_write.rs, src/sinks/s3_common/config.rs, src/sources/aws_s3/mod.rs, src/sources/aws_sqs/config.rs, src/sources/aws_sqs/integration_tests.rs, src/sources/aws_sqs/source.rs
This PR changes the source of our AWS dependencies to track a fork to circumvent a currently unresolved bug upstream.
Smithy crates are upgraded to `0.54.x` and sdk crates are upgraded to `0.24.x`
Closes https://github.com/vectordotdev/vector/issues/17728
=> chore: Upgrade aws-smithy and aws-sdk crates

website/content/en/docs/setup/deployment/roles.md
According to https://discord.com/channels/742820443487993987/1040011926563983441/1040016552243761162, this warning isn't relevant anymore
=> docs: remove aggregator beta warning

website/cue/reference/components/sources/kubernetes_logs.cue
=> chore(kubernetes_logs source): Add warning about Windows support

src/topology/builder.rs
We have one for sources and transforms, but evidentially didn't for sinks.
Closes: #17763
=> fix(sinks): Add missing component span for sink building

CONTRIBUTING.md, vdev/README.md
This PR explains that we use`vdev` for testing and gives instructions for using vdev to run tests locally.
=> docs: explain how to run tests locally

.github/workflows/cli.yml, .github/workflows/cross.yml, .github/workflows/integration-test.yml, .github/workflows/k8s_e2e.yml, .github/workflows/misc.yml, .github/workflows/msrv.yml, .github/workflows/regression.yml
- In order to reduce CI costs, experiments were run on each of the altered workflows to understand the duration (and thus impact to DX) and changes in cost.
- The two cases of concern are what checks are run on each PR commit and in the merge queue:
- in the merge queue- there was a trivial change in runtime. This is because the bottleneck workflow is the mac unit test, which takes about 1 hour to run. All runner-size-reduced workflows in this PR that are in the merge queue, still run within that time frame.
- on each PR commit- this PR does not affect this case. However, a sister PR (#17724) does, because that PR fundamentally changes the integration test workflow to introduce the runner there, and so in that PR, we reduced to 4 core. That change adds 3 minutes of duration to the …
=> chore(ci): reduce runner sizing to 4 core and free tier

.github/workflows/publish.yml
Resolves git submodule issue on older OS images.
Based on https://github.com/actions/checkout/issues/758#issuecomment-1097027361
=> chore: Fix publish workflow for older OS images

src/sinks/azure_common/mod.rs, src/sinks/azure_common/service.rs, src/sinks/s3_common/mod.rs
=> chore(deps): Export more common bits for components

.github/workflows/comment-trigger.yml, .github/workflows/cross.yml, .github/workflows/integration-comment.yml, .github/workflows/unit_windows.yml
The PR comment author membership was being detected but that wasn't being used to validate if the workflow(s) should proceed.
=> chore(ci): fix comment author validation

.github/audit.yml, .github/workflows/changes.yml, .github/workflows/cli.yml, .github/workflows/compilation-timings.yml, .github/workflows/component_features.yml, .github/workflows/cross.yml, .github/workflows/environment.yml, .github/workflows/gardener_remove_waiting_author.yml, .github/workflows/install-sh.yml, .github/workflows/integration-test.yml, .github/workflows/k8s_e2e.yml, .github/workflows/misc.yml, .github/workflows/msrv.yml, .github/workflows/publish.yml, .github/workflows/regression.yml, .github/workflows/test.yml, .github/workflows/unit_mac.yml, .github/workflows/unit_windows.yml
- Revert "chore: Fix publish workflow for older OS images (#17787)"
- Revert "chore: Add submodules to all checkouts (#17770)"
- Revert "chore: Download submodules in the CI checkouts (#17760)"
=> chore: Revert all submodule introductions to fix CI

.github/workflows/component_features.yml, .github/workflows/master_merge_queue.yml
Moves the most costly (both $ and time) status check out of the merge queue into a fixed schedule.
The workflow can still be run on demand by a PR comment, or from the GHA UI.
=> chore(ci): move component features check out of merge queue

src/app.rs, src/config/mod.rs, src/config/unit_test/mod.rs, src/validate.rs, tests/integration/shutdown.rs
Preload global parameter log_schema before compiling sources config.
It fixes an issue with globally configured log_schema and sources in separate files. 
Revert 3e971fb9d9503ddac3a238cd6dc643703e725081
=> fix(config): Fix preloading log_schema

.github/workflows/publish.yml
To currently supported versions.
=> chore(ci): Update publish workflow test Ubuntu versions

.github/actions/spelling/allow.txt, Cargo.lock, Cargo.toml, lib/codecs/Cargo.toml, lib/enrichment/Cargo.toml, lib/opentelemetry-proto/Cargo.toml, lib/vector-common/Cargo.toml, lib/vector-config/Cargo.toml, lib/vector-core/Cargo.toml, lib/vector-lookup/Cargo.toml, lib/vector-vrl/cli/Cargo.toml, lib/vector-vrl/functions/Cargo.toml, lib/vector-vrl/tests/Cargo.toml, lib/vector-vrl/web-playground/Cargo.toml, src/transforms/remap.rs, website/cue/reference/remap/functions/format_timestamp.cue, website/cue/reference/remap/functions/from_unix_timestamp.cue, website/cue/reference/remap/functions/parse_nginx_log.cue
This updates VRL: `0.4.0` -> `0.5.0`
I'm also trying out the newish "workspace" dependencies, so the VRL version is only specified a single time.
VRL changes can be viewed here: https://github.com/vectordotdev/vrl/blob/main/CHANGELOG.md
=> Update VRL to `0.5.0`

lib/vector-core/src/event/vrl_target.rs, lib/vector-core/src/schema/definition.rs, src/conditions/vrl.rs, src/transforms/remap.rs
This fixes an issue with `remap` when using the `Vector` namespace, where assigning a non-collection value (such as a string) directly to the root ended up with that value nested under the `message` field. Now it stays on the root.
=> fix: remap behavior for root types when using the `Vector` namespace

.github/workflows/publish.yml
Currently the longest build job at 2 hours; the second longest is an hour.
=> chore(ci): Bump up OSX runners for release builds

.github/workflows/gardener_issue_comment.yml
As it was previously implemented, this workflow would add an issue to the Gardener board if it wasn't already present. This updates the graphql query to fetch the necessary project item id without creating new items.
Tested the graphql query in the [playground](https://docs.github.com/en/graphql/overview/explorer).
Tested the `jq` command locally. 
Example Issue ID: `I_kwDOCLjIc85p9V5j`
=> chore(ci): fix gardener issues comment workflow

.github/workflows/gardener_issue_comment.yml
Reverts vectordotdev/vector#17825
Just reverting until we can address https://github.com/vectordotdev/vector/actions/runs/5427730493/jobs/9871271740 to avoid notification noise.
=> chore(ci): revert fix gardener issues comment workflow

lib/vector-common/src/internal_event/mod.rs
Without these, the cache cannot be used for types outside of `vector-common`.
=> chore(observability): Fix a couple typos with the registered event cache

.github/workflows/integration.yml
This change removes running the `changes` job when the workflow is triggered in the merge queue, as that is not needed.
=> chore(ci): save time int test workflow merge queue

scripts/environment/bootstrap-macos-10.sh
We seem to be hitting https://github.com/Homebrew/homebrew-cask/issues/150323 which recommends this
workaround.
=> chore(ci): Set HOMEBREW_NO_INSTALL_FROM_API in CI

Cargo.lock, Cargo.toml
Now that 0.31.0 has been released
=> chore(releasing): Bump Vector to 0.32.0

website/cue/reference/releases/0.31.0.cue
I'm not sure why this wasn't flagged by the preview build. It does seem to run the link checker
there too.
=> chore(releasing): Fix link in v0.31.0 release docs

src/conditions/vrl.rs
closes: #17175 
As discussed offline with @fuchsnj, we do not need to handle fallible conditions because providing a fallible condition already results in an error.
=> enhancement: check VRL conditions return type at compile time

STYLE.md
This PR adds docs describing a detail of our UX system around CLI args 😎
=> docs: describe the difference between configuration fields and runtime flags

src/sinks/vector/config.rs
Fixes #17895 as discussed in #17873. The Vector source propagates downstream non-retryable errors as either DataLoss or Internal GRPC error codes. However, these error codes are not treated as non-retryable by the corresponding upstream Vector sink, leading to a delivery retry loop.
(update): Only treating DataLoss as non-retryable. As explained by @dsmith3197 in a commit review - Internal errors occur when At least one event in the batch had a transient error in delivery and DataLoss errors occur when At least one event in the batch had a permanent failure or rejection, with Internal taking precedence over Dataloss. With that in mind, we'll want to retry for Internal, but not DataLoss.
=> fix(vector sink): Add DataLoss error code as non-retryable

vdev/src/commands/integration/ci_paths.rs
Currently this causes all integration tests to run on common dependabot changes to
`lib/vector-core/Cargo.toml` even though those changes are likely to be very low risk. These tests
also fail due to dependabot not having access to secrets but that is being addressed separately; the
primary argument in this PR is that the tests aren't needed in the PR, just the merge queue, for changes to `Cargo.toml` due to the low risk.
I had originally just wanted to exclude only `lib/vector-core/Cargo.toml` but this wasn't possible
due to a lack of support by the paths-filter action
(https://github.com/dorny/paths-filter/issues/106). Upon reflection, I think it is is unlikely that
core changes will cause integration test failures that don't also cause other test failures so my
proposal is that we just …
=> chore(ci): Remove path filter that runs all integration tests

.github/workflows/integration.yml
- Incidentally this is a nice-to-have in general.
- However with the recent merge queue changes, it has become necessary because previously, all status checks would run on external contributor PRs, and the force merge because secret-requiring int tests was ok. But there is no option to force add to merge queue, it's just force merge to the protected branch.
- Thus, for the `pull_request` trigger, we need to skip the integration tests that require secrets.
- On contributor PRs that touch those integrations, team members can either run them locally after checking out the branch, or trigger them by comment on the PR.
=> chore(ci): check for team membership on secret-requiring int tests

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, src/transforms/tag_cardinality_limit/config.rs, src/transforms/tag_cardinality_limit/mod.rs, src/transforms/tag_cardinality_limit/tag_value_set.rs, src/transforms/tag_cardinality_limit/tests.rs
=> chore(deps): Swap out bloom crate for bloomy

vdev/src/commands/integration/ci_paths.rs
Each key needs to map to an array.
=> chore(ci): Fix integration test filter generation

.github/workflows/integration.yml, .github/workflows/k8s_e2e.yml, .github/workflows/test.yml
- Author membership using the get-user-teams-membership doesn't work for contributor PRs because the GHA requires a GH token with proper scopes, which they don't have. Fix=check if secrets are defined in the environment.
- This and a couple other workflows had a logic bug in that they could be added to the merge queue if the main dep job were skipped (i.e due to a bug in the workflow).
=> fix(ci): address issues in integration test suite workflow

website/content/en/guides/level-up/managing-complex-configs.md, website/content/en/guides/level-up/managing-schemas.md
=> chore(docs): Remove mentions of deprecated transforms from guides

src/sources/splunk_hec/mod.rs
Fixes #17670 
Field names sent from Splunk were being parsed as paths, so a field name like `(thing |` was causing the path parsing to panic. This fix sets each of the names as an event field so no parsing occurs.
=> fix(splunk_hec source): insert fields as event_path so names aren't parsed as a path

.github/actions/spelling/allow.txt, website/content/en/highlights/2023-07-05-0-31-0-upgrade-guide.md
=> chore(releasing): Add upgrade note for 0.31.0 about S3 path changes

.github/actions/spelling/allow.txt, .github/workflows/regression.yml
This should be a transparent change. If you notice any issues, please ping us in #single-machine-performance. We'll also be keeping a close eye on things after this is merged.
The Single Machine Performance team has built an API to interact with the regression detector system. This will allow us to maintain reliability while continuing to evolve the system. This is enabled with the `--use-curta` flag, which will become the default in an upcoming release.
The curta API uses a unique URI for each team. This isn't secret - all endpoints have authorization - but we'd prefer it not be public. The URI for Vector is in SMP-617. The `smp` binary can read this from the `SINGLE_MACHINE_PERFORMANCE_API` environment variable or the `--api-base` flag.
We have also changed how the analysis worker is …
=> chore(CI): Switch regression detector to new API and analysis service

.github/workflows/regression.yml
The `smp` 0.9.1 release fixes a backwards compatibility bug. This addresses the failure observed after updating Vector's SMP deploy: https://github.com/vectordotdev/vector/actions/runs/5535572306/jobs/10127326812
=> chore(CI): Update `smp` to version 0.9.1

.github/workflows/regression.yml
The `smp` status wait command was missing the `--use-consignor` flag. This caused it to wait for our EC2-hosted Analysis Worker to complete. Subsequent steps read the lambda hosted result (`consignor`), which may still be processing. Adding this flag corrects this synchronization bug.
=> chore(CI): Add missing `--use-consignor` flag on `smp` call

.github/workflows/regression.yml
Fall back to the legacy Single Machine Performance analysis workers. It turns out we don't have as much runtime on consignor as we thought, and we would like to let it soak in the SMP dogfood cluster for a while.
=> chore(CI): Single Machine Performance: turn off consignor

src/topology/test/mod.rs
This is passing consistently for me locally, so hopefully we can stop ignoring it.
Closes #2186
=> chore: stop ignoring topology test

vdev/src/commands/test.rs
Whenever `features` are not provided. Matches `make test` behavior.
Fixes: #17975
=> fix(vdev): Add `--features` with default features for vdev test

website/cue/reference/components/sources/syslog.cue
For UDP/TCP connections it will contain the IP address of the connection client. There is no
fallback to `hostname` that I can see (nor could I get it to fallback during testing).
=> fix(docs, syslog source): Correct docs for `syslog_ip`

src/sinks/clickhouse/config.rs, src/sinks/clickhouse/integration_tests.rs, src/sinks/clickhouse/service.rs, src/sinks/clickhouse/sink.rs, src/sinks/prelude.rs, vdev/src/testing/integration.rs, website/cue/reference/components/sinks/base/clickhouse.cue
Closes: https://github.com/vectordotdev/vector/issues/16329
=> feat(clickhouse sink): make `database` and `table` templateable

docs/DEVELOPING.md
There were a couple of small things I ran into while getting my development environment working, and I thought I'd update the docs to reflect them:
- `cargo-nextest` is neede for some of the `make` targets
- `SCOPE` needs to be capitalised when running tests, or it is silently ignored
=> docs: Fix "Bring your own toolbox" in `DEVELOPING.md`

.github/actions/spelling/expect.txt, distribution/install.sh
Adds support to the install script for installing x86 builds of Vector on aarch64-apple-darwin when Rosetta is installed.
=> chore: Install script supports Apple ARM with Rosetta

lib/vector-config/src/external/serde_with.rs, src/sources/demo_logs.rs, src/sources/gcp_pubsub.rs, src/sources/internal_metrics.rs, src/transforms/throttle.rs
The demo logs source `interval` parameter examples imply that demo logs faster than 1/sec are possible by specifying a fractional value. However, the demo logs source incorrectly parses this value using serde's [DurationSeconds](https://docs.rs/serde_with/latest/serde_with/struct.DurationSeconds.html). This is incorrect - fractional second parts are coerced into a full-integer value based on rounding rules. So currently, `interval` values of >= 0.5 to 1 behave the same as `interval = 1`, while `interval` values of < 0.5 behave the same as `interval = 0`. The correct serde struct to use is [DurationSecondsWithFrac](https://docs.rs/serde_with/latest/serde_with/struct.DurationSecondsWithFrac.html).
(edit): This has since expanded to complete replacement of all usages of `DurationSeconds<f64, …
=> fix(demo gcp_pubsub internal_metrics source throttle transform): Fix `interval` fractional second parsing

src/api/server.rs, src/app.rs, src/topology/controller.rs
This PR attempts to resolve: https://github.com/vectordotdev/vector/issues/13508
I'm not married to switching out the `Runtime` parameters for `Handle`s, it just seemed like the easiest way to get something that could spawn tasks into the `TopologyController` was `Handle::current()`, and that required shifting the parameter types to match. Let me know if another route would be preferred.
=> fix(reload): restart api server based on topology

CONTRIBUTING.md, docs/DEVELOPING.md, scripts/environment/prepare.sh, vdev/src/commands/build/licenses.rs, vdev/src/commands/check/licenses.rs
And update vdev as well as the docs to use the new binary name.
=> chore(dev): Install dd-rust-license-tool from crates.io

src/aws/auth.rs, website/cue/reference/components/sinks/base/aws_cloudwatch_logs.cue, website/cue/reference/components/sinks/base/aws_cloudwatch_metrics.cue, website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue, website/cue/reference/components/sinks/base/aws_kinesis_streams.cue, website/cue/reference/components/sinks/base/aws_s3.cue, website/cue/reference/components/sinks/base/aws_sqs.cue, website/cue/reference/components/sinks/base/elasticsearch.cue, website/cue/reference/components/sinks/base/prometheus_remote_write.cue, website/cue/reference/components/sources/base/aws_s3.cue, website/cue/reference/components/sources/base/aws_sqs.cue
aws assume role did not have support for specifying external id which is quintessential for security concerned consumers.
P.S. [contributing guidelines](https://github.com/vectordotdev/vector/blob/44be37843c0599abb64073fe737ce146e30b3aa5/CONTRIBUTING.md) is empty, help me if I'm missing anything. 
Closes: https://github.com/vectordotdev/vector/issues/17739
=> feat: add support for `external_id` in AWS assume role

src/sources/http_client/client.rs, src/sources/http_client/integration_tests.rs, src/sources/http_client/tests.rs, src/sources/prometheus/scrape.rs, src/sources/util/http_client.rs, website/cue/reference/components/sources/base/http_client.cue, website/cue/reference/components/sources/base/prometheus_scrape.cue
fixes #14087 
fixes #14132 
fixes #17659
this builds on what @wjordan did in https://github.com/vectordotdev/vector/pull/17660
- prometheus scrapes happen concurrently
- requests to targets can timeout
- the timeout can be configured (user facing change)
- small change in how the http was instantiated
=> enhancement(prometheus_scrape source): run requests in parallel with timeouts

lib/vector-core/src/config/log_schema.rs, lib/vector-core/src/event/log_event.rs, lib/vector-core/src/event/trace.rs, src/transforms/remap.rs
This part of https://github.com/vectordotdev/vector/issues/13033 and https://github.com/vectordotdev/vector/issues/7070.
* Change the `metadata_key` type to `OptionalValuePath`.
* This completes the LogSchema changes.
=> feat: Migrate LogSchema::metadata key to new lookup code

.github/workflows/publish.yml, distribution/docker/debian/Dockerfile, distribution/docker/distroless-libc/Dockerfile, regression/Dockerfile, scripts/cross/bootstrap-ubuntu.sh, scripts/integration/Dockerfile, tests/data/dnstap/Dockerfile, tilt/Dockerfile
Released in June. Prompted by https://github.com/vectordotdev/vector/issues/16673#issuecomment-1645602002
=> chore(deps): Upgrade debian usages to use bookworm

Tiltfile, lib/codecs/src/decoding/format/native.rs, lib/vector-common/src/finalizer.rs, lib/vector-config/src/schema/visitors/human_name.rs, lib/vector-core/src/tls/incoming.rs, lib/vector-core/src/transform/mod.rs, rust-toolchain.toml, src/conditions/datadog_search.rs, src/config/watcher.rs, src/sinks/clickhouse/sink.rs, src/sinks/datadog/logs/sink.rs, src/sinks/datadog/metrics/normalizer.rs, src/sinks/greptimedb/service.rs, src/sinks/greptimedb/sink.rs, src/sinks/loki/sink.rs, src/sinks/mod.rs, src/sinks/splunk_hec/metrics/sink.rs, src/sinks/statsd/normalizer.rs, src/sinks/statsd/sink.rs, src/sources/mod.rs, src/sources/util/grpc/mod.rs, src/sources/util/mod.rs
=> chore(deps): Update to Rust 1.71.0
