vectordotdev/vector

- src/sinks/gcp/stackdriver_metrics.rs
There was no `assert_sink_compliance` test for the GCP Stackdriver Metrics sink. This PR adds that test.
Luckily the test passes, so no further changes were needed!
> enhancement(gcp_stackdriver_metrics sink): add `component_spec_compliance` test

- website/cue/reference/components/sources/kubernetes_logs.cue
> fix(docs): Add missing container_id and pod_owner information

- website/cue/reference/components/sinks/datadog_traces.cue
> fix(docs): Correct `datadog_traces` sink warning about APM stats.

- CONTRIBUTING.md
> chore: link docs/CONTRIBUTING.md to CONTRIBUTING.md

- website/cue/reference/components/sinks/http.cue
> docs(http sink): Document `method` option

- Cargo.lock
- Cargo.toml
- deny.toml
- distribution/install.sh
- lib/vector-core/src/metrics/mod.rs
- lib/vector-core/src/schema/definition.rs
- lib/vrl/compiler/src/expression/function_call.rs
- lib/vrl/tests/tests/issues/14796_closure_type_def.vrl
- scripts/check-deny.sh
- scripts/environment/prepare.sh
- src/config/builder.rs
- src/sinks/datadog/metrics/encoder.rs
- src/sources/datadog_agent/mod.rs
- website/content/en/releases/0.24.2.md
- website/cue/reference/configuration.cue
- website/cue/reference/releases/0.24.0.cue
- website/cue/reference/releases/0.24.1.cue
- website/cue/reference/releases/0.24.2.cue
- website/cue/reference/versions.cue
Milestone: https://github.com/vectordotdev/vector/milestone/97
> chore(releasing): Prepare v0.24.2 release

- src/sources/socket/mod.rs
> chore(socket source): Test compliance to instrumentation spec in `socket` source

- src/internal_events/sample.rs
- src/transforms/sample.rs
> chore(sample transform): emit `ComponentEventsDropped` internal event

- src/internal_events/tag_cardinality_limit.rs
- src/transforms/tag_cardinality_limit.rs
> chore(tag_cardinality_limit transform): emit `ComponentEventsDropped` internal event

- src/internal_events/throttle.rs
- src/transforms/throttle.rs
> chore(throttle transform): emit `ComponentEventsDropped` internal event

- Cargo.lock
- lib/vrl/web-playground/Cargo.toml
Closes https://github.com/vectordotdev/vector/issues/14948
running `wasm-pack` output:
https://gist.github.com/jonathanpv/460884f7c3bcbad8212d974cfa63805b
> chore(vrl): add js feature to getrandom

- website/cue/reference/components/transforms/tag_cardinality_limit.cue
> chore(external docs): Add clarifying note to `tag_cardinality_limit` transform. 

- src/sources/file.rs
The defaults inadvertently regressed in 82806d2a2
> fix(file source): Fix file source defaults

- lib/vector-common/src/internal_event/service.rs
- src/sources/amqp.rs
> fix(observability): Fix a few more usages of internal_log_rate_secs

- src/transforms/filter.rs
Ref https://github.com/vectordotdev/vector/issues/15031
This is just a pass-through schema definition
> chore(filter transform): add log namespace support to filter transform

- Makefile
- lib/codecs/src/decoding/format/bytes.rs
- lib/vector-core/src/schema/definition.rs
- src/sources/aws_s3/mod.rs
- src/sources/aws_s3/sqs.rs
> feature(aws_s3 source): Add log namespace and schema support

- website/cue/reference/components/sources/journald.cue
The text here was correct, but the issue number in the link was wrong; fix it.
> docs: fix link to journalctl discussion

- website/cue/reference/releases/0.25.0.cue
> chore(releasing): Add known issues for 0.25.0 release

- scripts/integration/docker-compose.datadog-agent.yml
> fix(ci): Explicitly set DD_HOSTNAME for Datadog Agent integration tests

- website/cue/reference/components/sinks/base/elasticsearch.cue
- website/cue/reference/components/sources/base/aws_s3.cue
- website/cue/reference/components/sources/base/aws_sqs.cue
- website/cue/reference/components/sources/base/file.cue
- website/cue/reference/components/sources/base/host_metrics.cue
> chore(docs): Re-sync docs from config schema

- lib/vrl/stdlib/src/parse_cef.rs
Closes #15091.
A one line fix and a test.
> fix(vrl): Fix parsing escape character for `parse_cef` 

- website/cue/reference/releases/0.25.0.cue
> chore(releasing): Add another known issue for prometheus remote write source

- src/sinks/prometheus/mod.rs
- src/sinks/prometheus/remote_write.rs
- website/cue/reference/components/sinks/base/prometheus_remote_write.cue
> fix(prometheus_remote_write sink): re-add support `Bearer` Auth config option

- website/cue/reference/components/sinks.cue
- remove redundant '"' from JSON
Tested:
- Local Avro serializer craetion with the example
> docs: update Avro scheme example

- soaks/tests/http_pipelines_blackhole/vector/vector.toml
- soaks/tests/http_pipelines_blackhole_acks/vector/vector.toml
> fix(ci): fix http pipelines soaks

- src/sources/amqp.rs
- src/sources/aws_kinesis_firehose/filters.rs
- src/sources/aws_kinesis_firehose/handlers.rs
- src/sources/aws_kinesis_firehose/mod.rs
- src/sources/aws_s3/sqs.rs
Closes: #15175
- feat(aws_kinesis_firehose source): Add log namespace and schema def
- +added test for vector namespace
> feat(aws_kinesis_firehose source): Add log namespace and schema def

- website/cue/reference/components/sinks/base/aws_s3.cue
- website/cue/reference/components/sinks/base/elasticsearch.cue
> chore(docs): Regenerate docs

- lib/vector-core/src/config/proxy.rs
- website/cue/reference/components/base/sinks.cue
- website/cue/reference/components/base/sources.cue
- website/cue/reference/components/transforms/base/aws_ec2_metadata.cue
Hey!
Making a few tweaks to some markdown 🥇 
Thanks!
> chore(internal docs): Tweaks to markdown

- src/sources/dnstap/mod.rs
- src/sources/dnstap/parser.rs
- src/sources/dnstap/schema.rs
- src/sources/util/framestream.rs
Closes #15009 
This adds `log_namespace` support to the `dnstap` source.
> enhancement(dnstap source): add log_namespace to dnstap

- scripts/generate-component-docs.rb
As more developers have tried to use `make generate-component-docs`, they've hit issues with the dependency on the `logging` gem. This is unintuitive because... none of us really use Ruby, and there's no good place to say "hey, install this gem first!".
This PR just removes `logging` and writes our own logger. It's simple enough. The output is essentially identical.
> chore(docs): remove logging dep for generate-component-docs script

- src/sources/file_descriptors/file_descriptor.rs
- src/sources/file_descriptors/mod.rs
- src/sources/file_descriptors/stdin.rs
> feature(file_descriptor, stdin source): Add log namespace and schema support

- src/sources/amqp.rs
Closes: #15102
Epic: #13723
Namespacing was largely already implemented, so this just adds some extra fields to the schema and adds a couple of tests.
> feat(amqp source): update schema definition for amqp source

- lib/vrl/web-playground/netlify.toml
> fix(vrl playground): Fix Netlify builds 

- lib/value/src/kind/collection.rs
fixes: https://github.com/vectordotdev/vector/discussions/15183
This fixes an issue when typedefs are merged for the "merge" VRL operator.
Specifically, if you have a type with a known field, being merged with a type that doesn't have that known field, but has a unknown value set, an invalid type definition could be returned.
> fix(vrl): fix internal merge function when using overwrite

- src/sources/nats.rs
Adds log namespace and schema def support.
closes: #15027
epic: #13723
Signed-off-by: Stephen Wakely [fungus.humungus@gmail.com](mailto:fungus.humungus@gmail.com)
> feat(nats source): Add log namespace and schema def support

- Cargo.lock
- Cargo.toml
- lib/codecs/Cargo.toml
- lib/loki-logproto/Cargo.toml
- lib/loki-logproto/build.rs
- lib/opentelemetry-proto/Cargo.toml
- lib/prometheus-parser/Cargo.toml
- lib/vector-core/Cargo.toml
> chore(deps): Update prost to 0.11.3

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(kubernetes): Regenerate manifests for 0.17.1

- config/examples/docs_example.toml
- config/examples/namespacing/transforms/apache_sample.toml
- tests/namespacing/ignore-invalid/vector.toml
- tests/namespacing/success/vector.toml
- website/content/en/docs/reference/configuration/_index.md
I've been trying out sampling with `rate = 50` and confused by almost no events getting through.
> Fix sampling documentation

- rfcs/2022-10-31-15056-tooling-revamp.md
> chore(internal docs): Fix markdown

- Cargo.lock
- Cargo.toml
> chore(releasing): Bump version to 0.27.0

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(kubernetes): Upgrade manifests to 0.18.0 of Helm chart

- website/content/en/highlights/2022-08-16-0-24-0-upgrade-guide.md
- website/content/en/highlights/2022-11-07-0-26-0-upgrade-guide.md
> chore(releasing): Add migration example for geoip transform

- src/sources/aws_sqs/config.rs
- src/sources/aws_sqs/source.rs
> feat(aws_sqs source): Add log namespace and schema support

- website/content/en/highlights/2022-11-07-0-26-0-upgrade-guide.md
> chore(releasing): Add missing paren to 0.26.0 upgrade guide

- src/sources/kubernetes_logs/mod.rs
- src/sources/kubernetes_logs/namespace_metadata_annotator.rs
- src/sources/kubernetes_logs/node_metadata_annotator.rs
fixes: https://github.com/vectordotdev/vector/issues/15489
> fix(kubernetes_logs source): Allow `namespace_labels` to be disabled

- lib/vector-core/src/config/global_options.rs
> chore(config): Test the rest of the global option merging

- .github/workflows/publish.yml
Most recent release seems to have introduced an issue, https://github.com/cloudsmith-io/action/issues/37
> chore(releasing): Pin cloudsmith github action version

- website/layouts/partials/meta.html
Add in meta tag from facebook for domain verification (only for homepage)
https://datadoghq.atlassian.net/browse/WEB-2932
> enhancement(template website): Add meta tag for domain verification

- lib/vrl/stdlib/Cargo.toml
- lib/vrl/stdlib/src/abs.rs
- lib/vrl/stdlib/src/lib.rs
- website/cue/reference/remap/functions/abs.cue
Resolves https://github.com/vectordotdev/vector/issues/15531
- add abs function
- add tests
- add documentation
Tested:
- Locally with `vector vrl` REPL
> feat(vrl): add abs function

- scripts/environment/prepare.sh
> chore(deps): bump cargo-deb and cargo-nextest to latest versions

- website/cue/reference/components/sources/datadog_agent.cue
> docs(datadog_agent source): Brush off trace support docs

- src/sources/syslog.rs
> feat(syslog source): Better handling of host_key input with OptionalValuePath

- Cargo.lock
- lib/vrl/compiler/Cargo.toml
https://github.com/advisories/GHSA-hc92-9h3m-c39j
> chore(deps): Bump `anymap` version

- src/main.rs
> enhancement(observability): Improve allocation tracing docs

- src/sources/docker_logs/mod.rs
> feat(docker_logs source): Improve host_key handling with OptionalValuePath

- src/sinks/prometheus/exporter.rs
- implement graceful shutdown if a port cannot be taken on the start
Tested:
- Local run
> fix(prometheus): implement graceful shutdown

- website/cue/reference/components/sinks/gcp_stackdriver_metrics.cue
> docs(gcp_stackdriver_metrics sink): update docs re duplicate tags

- website/cue/reference/components/sources/base/nats.cue
> fix(external docs): generate component docs for nats source

- Cargo.lock
- Cargo.toml
- lib/codecs/Cargo.toml
- lib/codecs/src/encoding/format/avro.rs
Replaces apache_rs.
Closes: #15597
> chore(deps): Switch to apache_avro

- src/sources/socket/mod.rs
- src/sources/socket/udp.rs
> feat(socket): Use OptionalValuePath in the udp socket config

- src/sources/util/unix_stream.rs
> chore(docs): typo fix

- deny.toml
> chore(security): Remove unneeded deny for RUSTSEC-2020-0159

- docs/DEVELOPING.md
Per https://github.com/vectordotdev/vector/issues/9131
> docs: Document Proptest as preferred property testing framework

- src/transforms/remap.rs
- website/cue/reference/components/transforms/base/remap.cue
> fix(remap transform): Use global timezone if configured

- Cargo.lock
- lib/file-source/Cargo.toml
- lib/file-source/src/file_server.rs
- lib/file-source/src/lib.rs
- src/sources/file.rs
- src/sources/kubernetes_logs/mod.rs
- website/cue/reference/components/sources/base/kubernetes_logs.cue
- website/cue/reference/components/sources/kubernetes_logs.cue
Resolves https://github.com/vectordotdev/vector/issues/15738
> feat(kubernetes_logs): add 'read_from' and 'ignore_older_secs' options

- docs/DOCUMENTING.md
From recent personal pains, as well as other contributors.
> chore(internal docs): add note about cue versioning

- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
> chore(kubernetes): Update manifests from Helm charts

- .github/workflows/labeler.yml
> fix(ci): Add permissions to labeler

- Cargo.lock
- Cargo.toml
> chore(deps): upgrade h2 and remove patch

- Cargo.lock
- Cargo.toml
See https://github.com/streamnative/pulsar-rs/pull/243#pullrequestreview-1252455199 for the issue that was introduced in 5.0.1 and fixed in 5.0.2.
> chore(deps): skip pulsar 5.0.1

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate k8s manifests for v0.27.0

- lib/file-source/src/checkpointer.rs
- lib/file-source/src/fingerprinter.rs
The checksum is now calculated only from the bytes read, and not from the entire buffer.
Also added an auto-update procedure from the previous version.
Resolves: #15700
> fix(file source): Fix checksum calculation

- src/sinks/console/config.rs
- website/cue/reference/components/sinks/base/console.cue
- website/cue/reference/components/sinks/console.cue
> docs(console sink): autogen cue docs

- .github/workflows/gardener_open_issue.yml
- .github/workflows/gardener_open_pr.yml
> chore(dev): Add new issues and PRs to Gardener backlog for triage

- .github/workflows/gardener_open_issue.yml
- .github/workflows/gardener_open_pr.yml
> chore(ci): Fix GHA add-to-project version

- src/sources/splunk_hec/mod.rs
- website/cue/reference/components/sources/base/splunk_hec.cue
- website/cue/reference/components/sources/splunk_hec.cue
> docs(splunk_hec source): Use generated docs for configuration 

- src/sources/syslog.rs
- website/cue/reference/components/sources/base/syslog.cue
- website/cue/reference/components/sources/syslog.cue
> docs(syslog source): Use generated docs for configuration

- src/sinks/vector/config.rs
- website/cue/reference/components/sinks/base/vector.cue
- website/cue/reference/components/sinks/vector.cue
> docs(vector sink): use auto-generated config docs

- src/sources/redis/mod.rs
- website/cue/reference/components/sources/base/redis.cue
- website/cue/reference/components/sources/redis.cue
> docs(redis source): Use generated docs for configuration

- src/sources/aws_sqs/config.rs
- website/cue/reference/components/aws.cue
- website/cue/reference/components/sources/aws_sqs.cue
- website/cue/reference/components/sources/base/aws_sqs.cue
> docs(aws_sqs source): Use autogenerated config docs

- src/sinks/websocket/config.rs
- src/sinks/websocket/sink.rs
- website/cue/reference/components/sinks/base/websocket.cue
- website/cue/reference/components/sinks/websocket.cue
closes: https://github.com/vectordotdev/vector/issues/16156
> docs(websocket sink): use auto-generated config docs 

- src/sinks/gcp/chronicle_unstructured.rs
- website/cue/reference/components/sinks/base/gcp_chronicle_unstructured.cue
- website/cue/reference/components/sinks/gcp_chronicle_unstructured.cue
> docs(gcp_chronicle sink): Use generated docs for configuration

- .github/workflows/gardener_open_pr.yml
Seems to be catching Vector team member PRs. I think this may be because the team name needs to be
lowercased.
> chore(ci): Fix team PR check

- src/gcp.rs
- src/sinks/gcp/mod.rs
- website/cue/reference/components/sinks/base/gcp_chronicle_unstructured.cue
- website/cue/reference/components/sinks/base/gcp_cloud_storage.cue
- website/cue/reference/components/sinks/base/gcp_pubsub.cue
- website/cue/reference/components/sinks/base/gcp_stackdriver_logs.cue
- website/cue/reference/components/sinks/base/gcp_stackdriver_metrics.cue
- website/cue/reference/components/sinks/gcp_stackdriver_metrics.cue
- website/cue/reference/components/sources/base/gcp_pubsub.cue
> docs(gcp_stackdriver_metrics sink): Use generated docs for configuration

- src/sinks/http.rs
- src/sinks/util/http.rs
- website/cue/reference/components/sinks/base/aws_cloudwatch_logs.cue
- website/cue/reference/components/sinks/base/axiom.cue
- website/cue/reference/components/sinks/base/datadog_logs.cue
- website/cue/reference/components/sinks/base/elasticsearch.cue
- website/cue/reference/components/sinks/base/http.cue
- website/cue/reference/components/sinks/http.cue
closes: https://github.com/vectordotdev/vector/issues/16203
> docs(http sink): use auto-generated config docs

- website/content/en/docs/reference/vrl/_index.md
Resolves https://github.com/vectordotdev/vector/issues/15264 https://github.com/vectordotdev/vector/issues/14953
> docs(vrl): document VRL playground

- website/content/en/docs/reference/vrl/_index.md
> chore: Remove extra space

- vdev/src/main.rs
- vdev/src/testing/integration.rs
> chore(vdev): Fix Windows compile problem

- src/sinks/papertrail.rs
- website/cue/reference/components/sinks/base/papertrail.cue
- website/cue/reference/components/sinks/papertrail.cue
> docs(papertrail sink): Use generated docs for configuration

- vdev/src/commands/check/deny.rs
- vdev/src/commands/check/mod.rs
- vdev/src/commands/config/mod.rs
- vdev/src/commands/config/set/mod.rs
- vdev/src/commands/generate.rs
- vdev/src/commands/integration/mod.rs
- vdev/src/commands/meta/mod.rs
- vdev/src/commands/package.rs
- vdev/src/commands/release/mod.rs
> chore(vdev): Fix up some subcommand text

- src/sinks/humio/logs.rs
- src/sinks/humio/metrics.rs
- website/cue/reference/components/sinks/base/humio_logs.cue
- website/cue/reference/components/sinks/base/humio_metrics.cue
- website/cue/reference/components/sinks/humio.cue
- website/cue/reference/components/sinks/humio_logs.cue
- website/cue/reference/components/sinks/humio_metrics.cue
Closes #16208 
Closes #16209 
Epic #14999 
> docs(humio_metrics sink, humio_logs sink): Use generated docs for configuration

- .github/workflows/publish.yml
These are starting to OOM in CI and we haven't actually found a user need for them.
> chore(ci): Remove creation of debug tarballs

- vdev/src/testing/integration.rs
> chore(vdev): Fix Windows compilation again

- src/sinks/loki/config.rs
- website/cue/reference/components/sinks/base/loki.cue
- website/cue/reference/components/sinks/loki.cue
Closes #16347
Toby already did the cutover, so this is just small cleanups and polish.
> docs(loki sink): Polish docs and examples

- .github/workflows/publish.yml
> chore(ci): Remove another reference to the debug build

- src/sinks/aws_kinesis/streams/config.rs
- src/sinks/aws_kinesis/streams/integration_tests.rs
Resolves https://github.com/vectordotdev/vector/issues/16263
- return missing partition key
Tested:
- No
@neuronull I think you could review this one.
> fix(kinesis): add again missing partition key

- scripts/release-s3.sh
Hopefully the last one. Debug builds removed in dbb1378
> chore(ci): Remove another debug build reference

- src/sinks/pulsar.rs
- website/cue/reference/components/sinks/base/pulsar.cue
- website/cue/reference/components/sinks/pulsar.cue
> docs(pulsar sink): autogen docs

- src/sinks/splunk_hec/logs/config.rs
- website/cue/reference/components/sinks/base/splunk_hec_logs.cue
- website/cue/reference/components/sinks/splunk_hec_logs.cue
> docs(splunk_hec_logs sink): Use generated docs for configuration

- src/sinks/splunk_hec/common/acknowledgements.rs
- src/sinks/splunk_hec/metrics/config.rs
- website/cue/reference/components/sinks/base/splunk_hec_logs.cue
- website/cue/reference/components/sinks/base/splunk_hec_metrics.cue
- website/cue/reference/components/sinks/splunk_hec.cue
- website/cue/reference/components/sinks/splunk_hec_logs.cue
- website/cue/reference/components/sinks/splunk_hec_metrics.cue
> docs(splunk_hec_metrics sink): Use generated docs for configuration

- distribution/install.sh
This is work that was part of creating the install script for the OP Worker. The Vector install script is based on https://sh.rustup.rs. The functions updated in this PR were copied from the rustup script; this updates them with the latest changes.
> chore: Update install.sh from rustup script

- .github/CODEOWNERS
> chore(dev): Add @vectordotdev/ux-team CODEOWNERS

- lib/vector-core/src/config/mod.rs
fixes: https://github.com/vectordotdev/vector/issues/16385
The `path!()` macro assumes the key is a single path, which was not intended. Removing the macro and using the string directly correctly parses the path.
Note: we generally don't want to use raw string paths, but in this case since the global log schema doesn't provide pre-parsed paths yet, the raw string is used to prevent a perf hit from pre-parsing every time this helper function is used.
> fix(core): fix source metadata paths from being flattened with `insert_standard_vector_source_metadat`

- src/sinks/aws_kinesis/config.rs
- website/cue/reference/components/sinks/aws_kinesis_firehose.cue
- website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue
- website/cue/reference/components/sinks/base/aws_kinesis_streams.cue
> docs(aws_kinesis_firehose sink): Use generated documentation

- .github/workflows/publish.yml
Updating our OS versions for package verification in CI.
> chore: Update package verify OS versions

- src/sinks/papertrail.rs
Closes #16430 
Epic #15453
All I could see that needed doing was fetching the host name from the correct namespace...
> chore(papertrail sink): Add log namespacing support

- src/sinks/pulsar.rs
> chore(pulsar sink): Add Log Namespacing support

- lib/vector-core/src/event/log_event.rs
- src/sinks/honeycomb.rs
> chore(honeycomb sink): Add log namespacing support 

- src/sinks/loki/config.rs
- src/sinks/loki/sink.rs
> chore(loki sink) Add Log Namespacing support

- src/sinks/sematext/logs.rs
> chore(sematext_logs sink): Add log namespacing support

- website/cue/reference/remap/functions/to_timestamp.cue
> docs: Add more examples for to_timestamp

- src/sinks/aws_sqs/config.rs
- website/cue/reference/components/sinks/aws_sqs.cue
- website/cue/reference/components/sinks/base/aws_sqs.cue
> docs(aws_sqs sink): Use generated documentation

- src/sinks/aws_cloudwatch_logs/config.rs
- src/sinks/aws_cloudwatch_logs/request_builder.rs
> chore(aws_cloudwatch_logs sink): Add log namespace support

- src/sinks/datadog/events/config.rs
- src/sinks/datadog/events/sink.rs
> feat(datadog_events sink): Use log namespacing and semantic meaning

- Cargo.lock
> chore(deps): Regererate Cargo.lock

- Cargo.lock
- src/sinks/elasticsearch/config.rs
> feat(elasticsearch sink): Use log namespacing and semantic meaning

- website/content/en/highlights/2023-02-28-0-28-0-upgrade-guide.md
> chore: Fix typo in 0.28 upgrade guide

- Cargo.lock
- Cargo.toml
- distribution/install.sh
- lib/vector-core/src/config/mod.rs
- src/source_sender/mod.rs
- src/topology/builder.rs
- website/content/en/releases/0.27.1.md
- website/cue/reference/releases/0.26.0.cue
- website/cue/reference/releases/0.27.0.cue
- website/cue/reference/releases/0.27.1.cue
- website/cue/reference/versions.cue
> chore(releasing): Prepare v0.27.1

- src/sinks/kafka/config.rs
- src/sinks/kafka/request_builder.rs
- src/sinks/kafka/sink.rs
> feat(kafka sink): Use log namespacing and semantic meaning

- .github/workflows/integration-test.yml
> chore: Include AXIOM_TOKEN in workflow env

- src/sources/redis/list.rs
error scenario:
- vector starts and successfully initializes the redis source
- the connection experiences issues
- which lead to high CPU usage (>1 core)
the fix introduces a backoff at 100ms in case of a `RedisError::ErrorKind::IoError` to remediate the high CPU issue during described scenario
https://github.com/vectordotdev/vector/issues/16492
> fix(redis source): fix high cpu on redis intermittent connection issues

- .github/ISSUE_TEMPLATE/minor-release.md
> chore(releasing): Correct label in issue template

- .github/SUPPORT.md
Figured this was easier than inline comments. Generally my aim was to slim it down.
> Some suggestions for improving the SUPPORT.md doc

- .github/SUPPORT.md
Porting what started as an entry in the GH wiki.
To be used in GH Discussions, and in Discord support.
> chore(docs): extend SUPPORT.md to include guidelines on how to ask a support question about Vector

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Update k8s manifests to 0.19.2 of helm chart

- website/cue/reference/components/sources/aws_kinesis_firehose.cue
Erorr pointed out by https://discord.com/channels/742820443487993987/1067453424486064221/1067453424486064221
> docs(aws_kinesis_firehose source): Fix AWS CloudWatch forwarding example

- .github/ISSUE_TEMPLATE/minor-release.md
Based on running through it with the 0.28.0 release.
> chore(releasing): Some more tweaks to minor-release template

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate manifests for 0.20.0 of Helm chart

- src/conditions/mod.rs
> chore(core): Make `Condition::check` public

- Cargo.toml
- src/sources/util/http/encoding.rs
- website/cue/reference/components/sources/http_server.cue
Resolves https://github.com/vectordotdev/vector/issues/16289
> feat(http_server): add zstd support

- website/cue/reference/releases/0.28.0.cue
> chore(releasing): Add known issues for 0.28.0.

- src/config/mod.rs
> chore: Re-export `LogNamespace`

- .github/ISSUE_TEMPLATE/patch-release.md
Similar to minor release issue template but with some changes
> chore(releasing): Add patch release issue template

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate k8s manifests for 0.20.1 chart

- website/cue/reference/releases/0.28.0.cue
> chore(internal docs, releasing): Fix 0.28.0 cue

- .github/workflows/regression_trusted.yml
> chore(ci): Use info logging for smp job submission

- .github/ISSUE_TEMPLATE/patch-release.md
Discovered while running through it for 0.28.1.
> chore(releasing): Tweaks to patch release template

- src/sources/kubernetes_logs/pod_metadata_annotator.rs
- website/cue/reference/components/sources/base/kubernetes_logs.cue
- website/cue/reference/components/sources/kubernetes_logs.cue
Closes https://github.com/vectordotdev/vector/issues/15808
> feat(kubernetes_logs): Add container imageID field

- src/sources/syslog.rs
Resolves https://github.com/vectordotdev/vector/issues/16818
@spencergilbert you might me interested in this PR :)
> fix(syslog): source_id -> source_ip

- src/app.rs
This function was passed `cli::Opts` but only uses the `root` field within those options, so just pass that field in directly.
I swear, I had included these at one point in my other patch series, but somehow I `git stash`ed it into oblivion at some point.
> chore(startup): Simplify parameter to `ApplicationConfig::from_opts`

- website/cue/reference/components/sources/journald.cue
> docs: Specify journald source requirements

- Makefile
None of the behavior tests need any of the features other than `transforms`, so dropping the remainder of the default features will speed up the link time.
> chore(tests): Make the `test-behavior` test build a little faster

- src/app.rs
Since #16873 broke the K8S E2E tests, I am breaking up that PR into individual steps to see which one might be have caused the problem. This is part 1 of (hopefully) 5.
> chore(startup): Break out API startup from `Application::run`

- website/content/en/docs/reference/configuration/sinks/kafka.md
- website/content/en/docs/reference/configuration/sources/kafka.md
> docs: Update kafka components to have mirrored descriptions

- website/cue/reference/cli.cue
> fix (website/cue/reference): copy/paste error

- src/app.rs
- src/control_server.rs
#16927 may have found the broken patch in this PR set, so I'm bundling the last two together.
> chore(core): Break out shutdown from main running loop

- .github/actions/spelling/excludes.txt
> chore(ci): Ignore spelling in gardner workflow file

- website/content/en/_index.md
> chore: Update stars and contributor counts on the website

- .config/nextest.toml
Provides more useful information when failures happen: [example](https://vector.datadoghq.com/ci/test-commit/github.com%2Fvectordotdev%2Fvector/vector/spencer%2Faws-sdk-update/1e39187b86a0a13b41782a8ec60006e7fbbf5e0a?query=test_level%3Atest%20env%3Alocal%20%40git.repository.id%3A%22github.com%2Fvectordotdev%2Fvector%22%20%40test.service%3Avector%20%40git.branch%3A%22spencer%2Faws-sdk-update%22%20%40git.commit.sha%3A1e39187b86a0a13b41782a8ec60006e7fbbf5e0a%20%40test.status%3Afail&currentTab=overview&env=local&eventStack=AgAAAYc4NRUq4DlhjgAAAAAAAAAYAAAAAEFZYzROUlVxQUFEUllYelBuQjltenZBYwAAACQAAAAAMDE4NzM4MzUtNzIwMi00NjQ5LWEzOWEtMzIwZDY2MWIxYjNi&index=citest&spanID=2085427022842588502&testId=AgAAAYc4NRUq4DlhjgAAAAAAAAAYAAAAAEFZYzROUlVxQUFEUllYelBuQjltenZBYwAAACQAAAAAMDE4NzM4MzUtNzIwMi00NjQ5LWE …
> chore: Store failure output for junit artifact

- lib/vector-config/src/schema/helpers.rs
> chore(config): Expose a couple of schema helper functions

- vdev/src/testing/integration.rs
Making the `network` field in Compose struct non optional, as it currently is always a `Some()`.
> chore(vdev): Make network non optional in Compose struct

- .github/SUPPORT.md
> chore(docs): add error detail to support.md

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate Kubernetes manifests for 0.21.2

- .github/CODEOWNERS
> chore(administration): add `appsignal` to codeowners

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate manifests for 0.22.0 chart

- Cargo.lock
Some drift occurred in Cargo.lock
> chore(deps): true up cargo.lock

- src/sinks/loki/sink.rs
This PR adds warnings for issues than can arise during label expansion in the loki sink:
- warnings for label expansion errors
- warnings for dynamic/dynamic and dynamic/static label expansions collisions
- warnings for dynamic label null values
https://github.com/vectordotdev/vector/issues/16886
https://github.com/vectordotdev/vector/issues/12055
> chore(loki sink): warn on label expansions and collisions

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate manifests for 0.21.1 chart

- website/cue/reference/releases/0.29.0.cue
- website/cue/reference/releases/0.29.1.cue
> chore(releasing): Add known issues fixed by 0.29.1

- .github/ISSUE_TEMPLATE/patch-release.md
> chore(releasing): Update patch-release.md

- website/cue/reference.cue
> chore(docs): Document event type conditions

- src/internal_events/http.rs
- src/sources/util/http/prelude.rs
> enhancement(observability): Log underlying error for unhandled HTTP errors

- .github/workflows/integration-test.yml
> chore(ci): Increase timeout for integration tests to 30m

- website/cue/reference/components/sinks/loki.cue
> docs(loki sink): Fix formatting in labels example

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(kubernetes): Bump k8s manifests to 0.22.0

- lib/codecs/src/encoding/format/avro.rs
- lib/vector-config-common/src/human_friendly.rs
- lib/vector-core/src/tls/settings.rs
- src/aws/auth.rs
- src/sinks/aws_s3/config.rs
> chore(aws_s3 sink): Update metadata to match the editorial review for the schema.

- .github/workflows/integration-comment.yml
- .github/workflows/integration.yml
- .github/workflows/k8s_e2e.yml
- .github/workflows/master_merge_queue.yml
- .github/workflows/regression.yml
- .github/workflows/test.yml
- Made integration comment parsing more strict to not run on unintended comments
- Fix logic concurrency group logic issues for comment triggers on k8s and regression workflows.
- Use the merge queue's head sha for concurrency cancellation check, this is more correct and enables us to use the concurrency features of the merge queue
> chore(ci): fix a few logic bugs and more strict comment parsing

- src/sinks/blackhole/config.rs
- src/sinks/file/mod.rs
- src/sinks/kafka/config.rs
- src/sinks/mezmo.rs
- src/sinks/prometheus/exporter.rs
- src/sinks/util/batch.rs
- src/sinks/util/service.rs
- src/sinks/util/service/health.rs
This PR updates the sinks' field labels that needs a human_name label. Similar to this https://github.com/vectordotdev/vector/pull/17475 and https://github.com/vectordotdev/vector/pull/17517.
> chore(config): Update field labels for sinks

- .github/workflows/changes.yml
- Adds file detection for changes to the yaml files used in the creation of the int test containers.
> chore(ci): int test yaml file detection

- .github/workflows/gardener_issue_comment.yml
Reverts https://github.com/vectordotdev/vector/pull/16950
> enhancement(dev):  move blocked/waiting gardener issues to triage on comment

- .github/CODEOWNERS
- .github/actions/spelling/expect.txt
> chore(dev): Add @dsmith3197 to CODEOWNERS

- lib/file-source/src/file_server.rs
- src/app.rs
> fix(file source): Fix tailing problem when source number greater than 512

- .github/workflows/gardener_open_pr.yml
`GH_PAT_ORG` has the correct permissions for `read:org`
> chore(ci): fix team membership action

- .github/workflows/publish.yml
> chore(ci): Remove remaining Discord notification

- .github/workflows/component_features.yml
> chore(ci): Add schedule to component features workflow conditional check

- .github/workflows/gardener_issue_comment.yml
We were no longer getting the `item_id`
> chore(ci): fix gardener issues comment workflow pt 2

- .github/ISSUE_TEMPLATE/minor-release.md
> chore(releasing): Fix markdown syntax in minor release template

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate k8s manifests with v0.23.0 of the chart

- .github/workflows/gardener_issue_comment.yml
PullRequests and Issues are modeled as distinct objects in Github's graphql schema.
> chore(ci): fix gardener issues comment workflow pt 3

- lib/loki-logproto/Cargo.toml
- lib/loki-logproto/LICENSE
> chore(dev): Mark loki-logproto crate as unpublished

- CONTRIBUTING.md
> chore(docs): Fix links in CONTRIBUTING.md

- lib/codecs/src/decoding/format/syslog.rs
- lib/vector-core/src/config/log_schema.rs
- lib/vector-core/src/config/mod.rs
- lib/vector-core/src/event/trace.rs
- src/sources/http_client/client.rs
- src/transforms/remap.rs
This part of https://github.com/vectordotdev/vector/issues/7070 and specifically https://github.com/vectordotdev/vector/issues/18059.
Follow-up for https://github.com/vectordotdev/vector/pull/18090#discussion_r1276586495.
> feat: LogSchema metadata key refacoring

- docs/tutorials/sinks/1_basic_sink.md
- docs/tutorials/sinks/2_http_sink.md
Fix typo in the link in the word "sinks".
> docs(internal docs): Fix basic sink tutorial issues

- .github/actions/spelling/allow.txt
- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- lib/codecs/tests/data/native_encoding/schema.cue
- lib/enrichment/src/find_enrichment_table_records.rs
- lib/enrichment/src/get_enrichment_table_record.rs
- lib/enrichment/src/vrl_util.rs
- lib/vector-vrl/functions/src/set_semantic_meaning.rs
- website/cue/reference/remap/concepts/function.cue
- website/cue/reference/remap/expressions/function_call.cue
- website/cue/reference/remap/functions.cue
- website/cue/reference/remap/functions/encrypt.cue
- website/cue/reference/remap/functions/parse_nginx_log.cue
- website/cue/reference/remap/functions/to_timestamp.cue
- website/layouts/partials/data.html
VRL 0.6.0 changelog can be found [here](https://github.com/vectordotdev/vrl/blob/main/CHANGELOG.md#060-2023-08-02).
> feat(deps, vrl): Update VRL to 0.6.0

- Tiltfile
- rust-toolchain.toml
> chore(deps): Upgrade to Rust 1.71.1

- distribution/install.sh
- website/content/en/highlights/2023-08-15-0-32-0-upgrade-guide.md
- website/content/en/releases/0.32.0.md
- website/cue/reference/administration/interfaces/kubectl.cue
- website/cue/reference/releases/0.32.0.cue
- website/cue/reference/versions.cue
Checklist: https://github.com/vectordotdev/vector/issues/18187
> chore(releasing): Prepare v0.32.0 release

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate k8s manifests for v0.24.0 of the chart

- src/aws/mod.rs
- src/sources/aws_s3/mod.rs
When constructing the client we detect the region so we can use that for consistency rather than
requiring it to be specified (so that, for example, `AWS_REGION` is used if set).
> fix(aws_s3 source): Allow region to be optional

- website/cue/reference/releases/0.32.0.cue
> docs: 0.32.0.cue typo

- website/cue/reference/releases/0.32.0.cue
I meant to add this before since it seems like a notable enhancement.
> chore(releasing): Add note about protobuf codec addition for 0.32.0 release

- Cargo.toml
- lib/vector-buffers/Cargo.toml
- lib/vector-common/Cargo.toml
- lib/vector-core/Cargo.toml
This dependency is inherited by members of the vector workspace.
> chore: make pin-project a workspace dependency

- distribution/install.sh
Closes: https://github.com/vectordotdev/vector/issues/18291
> chore(distribution): Fix PATH modification to allow for spaces

- website/cue/reference/releases/0.32.0.cue
From https://github.com/vectordotdev/vector/milestone/114
> chore(releasing): Add known issues for v0.32.0

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- distribution/install.sh
- lib/vector-common/src/request_metadata.rs
- src/app.rs
- src/cli.rs
- src/sinks/util/encoding.rs
- src/sources/opentelemetry/mod.rs
- website/content/en/releases/0.32.1.md
- website/cue/reference/releases/0.32.0.cue
- website/cue/reference/releases/0.32.1.cue
- website/cue/reference/versions.cue
Checklist: https://github.com/vectordotdev/vector/issues/18312
> chore(releasing): Prepare v0.32.1

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Bump k8s manifests to v0.24.1 of the chart

- Cargo.lock
- lib/codecs/Cargo.toml
- lib/vector-config/Cargo.toml
- lib/vector-core/Cargo.toml
This is a fix for a recent regression. Tests can now run with `cargo test`.
> fix(deps): fix [dev-dependencies] for some libs

- website/content/en/docs/setup/installation/operating-systems/macos.md
This took me a while to track down since I thought this was generated by the cue data but it appears
to be duplicated here.
Closes: #18352
> fix(website): Fix installer list for MacOS

- .github/CODEOWNERS
> chore(dev): Add CODEOWNERS for documentation updates

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(kubernetes): Regenerate manifests from new Helm chart version

- rust-doc/Makefile
Updates the CI command to add the `--workspace` flag for rust-docs
> chore(rust-doc): Update amplify build to include workspace flag

- .github/actions/spelling/expect.txt
- distribution/install.sh
- docs/DEPRECATIONS.md
- src/config/loading/mod.rs
- website/content/en/highlights/2023-09-27-0-33-0-upgrade-guide.md
- website/content/en/releases/0.33.0.md
- website/cue/reference/administration/interfaces/kubectl.cue
- website/cue/reference/releases/0.33.0.cue
- website/cue/reference/versions.cue
Checklist: https://github.com/vectordotdev/vector/issues/18652
Also TODO:
> chore(releasing): Prepare v0.33.0 release

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing, kubernetes): Update manifests to v0.26.0 of the chart

- .github/actions/spelling/excludes.txt
- .github/dependabot.yml
Just a few things found while scanning `cargo tree`.
> chore(deps): Add more `dependabot` groups

- website/content/en/docs/reference/configuration/unit-tests.md
Fix the references of the transform so the test example is valid. Also added a missing `"`
>  docs(external docs): Fix metrics test example 

- website/cue/reference/releases/0.33.0.cue
> chore(releasing): Add known issue for 0.33.0 debian packaging regression

- .github/dependabot.yml
> chore(deps): Group csv crate updates

- .github/workflows/comment-trigger.yml
- .github/workflows/workload_checks.yml
This request came up during the Workload Checks brown bag talk.
> feat: add PR comment trigger for the workload checks workflow

- .github/workflows/regression.yml
- .github/workflows/workload_checks.yml
> chore(deps): Bump lading to 0.19.1

- lib/k8s-e2e-tests/tests/vector-agent.rs
> chore: convert test config to yaml

- config/vector.yaml
To be valid YAML
Ref: https://github.com/vectordotdev/homebrew-brew/issues/17
> fix(releasing): Update example YAML config data_dir

- website/cue/reference/remap/expressions/function_call.cue
ref: https://github.com/vectordotdev/vrl/issues/23
> feat(docs): add fallibility examples

- website/content/en/docs/setup/installation/platforms/kubernetes.md
updating the 2 "distribution/kubernetes" paths to include "tree/master"
> updating the doc, 2 urls were 404

- src/internal_events/mod.rs
This was caught by the component features nightly CI check.
> fix(amqp sink): remove unused feature flag

- src/sinks/datadog/traces/request_builder.rs
~This is 95% of the way to where I want it, and a significant improvement over the current state. I would like to expand the property tests a bit more to cover events that are too big, but it's good enough to review for now.~
Fixes #14244
OPW-87
> fix(datadog_traces sink): improve request size limiting

- website/cue/reference/releases/0.33.1.cue
> chore(releasing): Typo in v0.33.1 release docs

- Cargo.lock
- LICENSE-3rdparty.csv
- license-tool.toml
> chore(deps): Update dependencies

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(kubernetes): Regenerate manifests from 0.27.0 chart

- docs/DEPRECATIONS.md
Was already done in eca8c76130
> chore(dev): Remove deprecation action item for armv7 RPMs

- scripts/environment/prepare.sh
To include fix to not have empty newlines in conffiles.
Fixes: https://github.com/vectordotdev/vector/issues/19008
> fix(releasing): Update cargo-deb

- src/sinks/clickhouse/config.rs
Fixes https://github.com/vectordotdev/vector/issues/19061
> fix(clickhouse sink): fix healthcheck uri

- website/cue/reference/releases/0.34.0.cue
> chore(releasing): Fix formatting for v0.34.0 release note

- src/sources/datadog_agent/logs.rs
- src/sources/datadog_agent/tests.rs
Fixes https://github.com/vectordotdev/vector/issues/18868
> fix(datadog_agent source): return 200 on empty object payload

- src/kafka.rs
- src/sinks/kafka/sink.rs
- src/sources/kafka.rs
Fixes https://github.com/vectordotdev/vector/issues/16912
> fix(kafka source, kafka sink): propagate span for internal events

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing, kubernetes): Bump manifests to v0.29.0 of Helm chart

- website/config.toml
- Changes `Enterprise` to `Observability Pipelines` in the navigation
https://datadoghq.atlassian.net/browse/WEB-4275
> chore(website): WEB-4275 | Update Navigation

- src/api/tap.rs
- src/internal_events/log_to_metric.rs
- src/transforms/log_to_metric.rs
- website/cue/reference/components/transforms/base/log_to_metric.cue
enchancement(log_to_metric): add config option that will covert all logs to metrics
> feat(log_to_metric): dynamically convert all logs to metrics

- .github/workflows/publish.yml
> chore(deps): Updated Fedora versions used in testing to latest

- deny.toml
> chore(security): Ignore RUSTSEC-2023-0071 for now

- .github/workflows/regression.yml
This new consignor is recommended.
> chore(performance): Use welch consignor

- Cargo.lock
- LICENSE-3rdparty.csv
Resolves https://github.com/advisories/GHSA-fjx5-qpf4-xjf2
> chore(deps): Update rust_decimal crate and dependencies

- src/transforms/remap.rs
closes: https://github.com/vectordotdev/vector/issues/19286
> fix(remap): do not emit error/discarded metrics for re-routed events

- scripts/environment/bootstrap-windows-2019.ps1
- scripts/environment/prepare.sh
- scripts/integration/Dockerfile
https://nexte.st/CHANGELOG.html
> chore(deps): update nextest version to 0.9.64

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- lib/codecs/tests/data/native_encoding/vector_generate_fixtures.patch
- website/cue/reference/remap.cue
This will unblock:
- https://github.com/vectordotdev/vector/pull/19266
- https://github.com/vectordotdev/vector/pull/19081
> chore(deps): update VRL to v0.9.0

- website/cue/reference/releases/0.34.0.cue
Test for actions/labeler@v5 upgrade.
> fix(releases website): close code block

- website/assets/js/dd-browser-logs-rum.js
Update RUM domain per #incident-24152
> Update RUM domain

- .github/workflows/preview_site_trigger.yml
Adds an exclude list to the workflow so we don't run on specific branches
> fix(website): Add ignored branch check to workflow

- Cargo.toml
- docs/DEPRECATIONS.md
- src/internal_events/apache_metrics.rs
- src/internal_events/aws_ecs_metrics.rs
- src/internal_events/aws_kinesis_firehose.rs
- src/internal_events/common.rs
- src/internal_events/http.rs
- src/internal_events/logplex.rs
- src/internal_events/prelude.rs
- src/internal_events/prometheus.rs
- src/internal_events/splunk_hec.rs
- src/sinks/prometheus/exporter.rs
- src/sources/apache_metrics/mod.rs
- src/sources/aws_ecs_metrics/mod.rs
- src/sources/splunk_hec/mod.rs
- src/sources/util/http_client.rs
- website/content/en/highlights/2023-12-19-0-35-0-upgrade-guide.md
- website/cue/reference/components/sinks/splunk_hec_logs.cue
- website/cue/reference/components/sources/apache_metrics.cue
- website/cue/reference/components/sources/aws_ecs_metrics.cue
- website/cue/reference/components/sources/aws_kinesis_firehose.cue
- website/cue/reference/components/sources/heroku_logs.cue
- website/cue/reference/components/sources/http_client.cue
- website/cue/reference/components/sources/internal_metrics.cue
- website/cue/reference/components/sources/prometheus_remote_write.cue
- website/cue/reference/components/sources/prometheus_scrape.cue
- website/cue/reference/components/sources/splunk_hec.cue
> chore(observability)!: Remove deprecated HTTP metrics

- Cargo.lock
- Cargo.toml
> chore(deps): Update VRL to 0.9.1

- Cargo.lock
- Cargo.toml
- deny.toml
- distribution/install.sh
- lib/codecs/src/encoding/format/protobuf.rs
- src/sources/datadog_agent/logs.rs
- src/sources/datadog_agent/tests.rs
- website/content/en/releases/0.34.2.md
- website/cue/reference/releases/0.34.0.cue
- website/cue/reference/releases/0.34.2.cue
- website/cue/reference/versions.cue
Checklist: https://github.com/vectordotdev/vector/issues/19443
> chore(releasing): Prepare v0.34.2

- website/cue/reference/remap/functions/parse_klog.cue
- website/cue/reference/remap/functions/parse_linux_authorization.cue
https://github.com/vectordotdev/vrl/issues/8
> docs(vrl): update tests for 2024

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> enhancement(kubernetes): Update manifests to chart v0.29.1

- website/cue/reference/remap/expressions/function_call.cue
- website/cue/reference/remap/functions.cue
- website/cue/reference/remap/functions/assert.cue
- website/cue/reference/remap/functions/assert_eq.cue
- website/cue/reference/remap/functions/del.cue
- website/cue/reference/remap/functions/log.cue
- website/layouts/partials/data.html
Adds a new badge to each VRL function to indicate if the function is pure or not.
> chore(docs): Add pure/impure badge for VRL functions

- .github/dependabot.yml
> chore(deps): Group together crossbeam updates

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(kubernetes): Bump manifests to v0.30.0 of the chart

- website/content/en/highlights/2023-12-19-0-35-0-upgrade-guide.md
Suggested by https://github.com/vectordotdev/vector/pull/19528#pullrequestreview-1809625932
> chore(docs): Fix proofreading mistake in v0.35.0 upgrade guide

- .github/workflows/integration-comment.yml
I thought this existed before. It may have been removed accidentally.
> chore(ci): enable running all int tests comment

- website/cue/reference/components/sources/splunk_hec.cue
- website/cue/reference/services/splunk_client.cue
Rather than Splunk itself. This confused one user in Discord.
> docs(splunk_hec source): Clarify that this source receives data from Splunk clients

- Cargo.toml
- docs/DEVELOPING.md
> chore(deps): Document Vector's MSRV policy

- Cargo.lock
> chore(deps): Update h2

- .github/workflows/changelog.yaml
> chore(ci): Run the changelog check on the merge queue to pass required checks

- website/content/en/docs/reference/configuration/sinks/aws_sns.md
- website/cue/reference/components/sinks/aws_sns.cue
- website/cue/reference/urls.cue
> docs(aws_sns sink): Add documentation data

- src/extra_context.rs
The `TypeId` parameter that is used as a key for the internal `HashMap` can be extracted from the items being collected into the map, which leads to an implementation to collect from any iterable of boxed `Any` items.
> chore: Implement an easier creator for multi-valued `ExtraContext`

- changelog.d/19825.feature.md
- lib/codecs/Cargo.toml
- lib/codecs/src/decoding/format/mod.rs
- lib/codecs/src/decoding/format/vrl.rs
- lib/codecs/src/decoding/mod.rs
- lib/vector-core/src/lib.rs
- src/components/validation/resources/mod.rs
- website/cue/reference/components/sources/base/amqp.cue
- website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
- website/cue/reference/components/sources/base/aws_s3.cue
- website/cue/reference/components/sources/base/aws_sqs.cue
- website/cue/reference/components/sources/base/datadog_agent.cue
- website/cue/reference/components/sources/base/demo_logs.cue
- website/cue/reference/components/sources/base/exec.cue
- website/cue/reference/components/sources/base/file_descriptor.cue
- website/cue/reference/components/sources/base/gcp_pubsub.cue
- website/cue/reference/components/sources/base/heroku_logs.cue
- website/cue/reference/components/sources/base/http.cue
- website/cue/reference/components/sources/base/http_client.cue
- website/cue/reference/components/sources/base/http_server.cue
- website/cue/reference/components/sources/base/kafka.cue
- website/cue/reference/components/sources/base/nats.cue
- website/cue/reference/components/sources/base/redis.cue
- website/cue/reference/components/sources/base/socket.cue
- website/cue/reference/components/sources/base/stdin.cue
Closes: https://github.com/vectordotdev/vector/issues/13634
> feat(codecs): implement VRL decoder

- scripts/check_changelog_fragments.sh
Otherwise `git diff` will list fragments that were deleted on `master` but exist on this branch.
> chore(ci): Look at merge base when looking for added changelog files

- changelog.d/README.md
People seem to commonly include this.
> chore(dev): Add a note that GH usernames shouldn't start with @

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(kubernetes): Bump manifists to chart v0.30.2

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> feat(kubernetes): Bump manifests to chart v0.36.0

- Cargo.lock
- Cargo.toml
> chore(releasing): Bump development version to v0.37.0

- website/content/en/highlights/2024-02-13-0-36-0-upgrade-guide.md
- website/cue/reference/releases/0.36.0.cue
Hi, there are some small updates to the changelog. Hope it helps
> chore(releases website): 0.36 changelog fixes

- website/cue/reference/components/sources/statsd.cue
Ref: https://github.com/vectordotdev/vector/issues/20019
> docs(statsd source): Update statsd doc to mention timing conversion

- Cargo.lock
- Cargo.toml
> chore(deps): Update VRL to v0.12.0

- .github/ISSUE_TEMPLATE/patch-release.md
> chore(dev): Remove mention of handwriting changelog for patch release

- lib/dnsmsg-parser/src/dns_message_parser.rs
This changes tests for RData type currently unknown to `hickory_proto` to use a common mechanism that is used for known types too. The goal of this is to use a similar code path to an actual use case (which will first consider known types and then try to treat them as unknown).
In #19921 implementation for HINFO was added and there was a test that has treated HINFO as an unknown type that was run successfully, but in real application use case, it would fail for such records, since it would never get treated as an unknown type. This will help spot if any new types ,that are already supported by vector, have been added to `hickory_proto`.
Related: #19921
> test(dnsmsg_parser): fix tests for currently unknown rdata types

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate k8s manifests for Helm chart v0.31.1

- website/layouts/partials/banner.html
> chore(docs): Update banner to use past tense for repository decommissioning

- .github/CODEOWNERS
> chore(dev): Update CODEOWNERS to reflect consolidation

- lib/k8s-e2e-tests/src/lib.rs
- lib/k8s-e2e-tests/tests/vector-agent.rs
- lib/vector-buffers/examples/buffer_perf.rs
- lib/vector-buffers/src/lib.rs
- rfcs/2020-03-06-1999-api-extensions-for-lua-transform.md
- src/transforms/lua/v2/mod.rs
- website/cue/reference/components/transforms/base/lua.cue
- website/cue/reference/releases/0.31.0.cue
> chore: remove repetitive words

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
> chore(deps): Bump VRL to v0.13.0

- lib/vector-buffers/src/topology/channel/receiver.rs
- lib/vector-buffers/src/topology/test_util.rs
- lib/vector-stream/src/driver.rs
- rust-toolchain.toml
- src/sinks/aws_s3/integration_tests.rs
- src/sinks/azure_blob/integration_tests.rs
- src/sinks/datadog/metrics/request_builder.rs
- src/sinks/file/mod.rs
- src/sinks/util/service/health.rs
- src/sources/file_descriptors/mod.rs
- src/sources/http_client/client.rs
- src/sources/journald.rs
- src/sources/kafka.rs
- vdev/src/testing/integration.rs
Please pay special attention to the code deletions here. The compiler identified several unused members of structs, and the fixups I made may not be entirely correct.
> chore(deps): Bump Rust to 1.77.0

- website/config.toml
I'd planned to time this with the v0.37.0 release.
> chore(docs): Remove package deprecation banner

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Bump Kubernetes manifsts to chart version 0.32.0

- scripts/environment/bootstrap-ubuntu-20.04.sh
We are seeing a lot of flakiness for this upgrade lately and I'm not really sure it is necessary to be running this.
> chore(ci): Drop `apt-get upgrade`

- website/content/en/docs/setup/installation/package-managers/pacman.md
The reason of this change is explained in the Git Migration announcement: https://archlinux.org/packages/extra/x86_64/vector/
> docs: Update pacman.md as vector is available now in extra repository

- src/app.rs
optimize code:remove extra_context clone
> chore: remove unnecessary clone

- src/config/unit_test/mod.rs
- src/config/unit_test/tests.rs
> chore: Run unit test tests in CI

- website/content/en/docs/setup/installation/platforms/docker.md
> docs: Update docker.md

- website/content/en/docs/about/what-is-observability-pipelines.md
I didn't change the name of the file (although that should really be changed to `what-are-observability-pipelines.md`) because I didn't want to break links.  However, if you're willing to create a forwarding rule in your web server, it would be ideal if the file name and URL had `are`.
> docs: fix grammar in what-is-observability-pipelines.md

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- lib/vector-common/Cargo.toml
- lib/vector-config/Cargo.toml
- lib/vector-core/Cargo.toml
- lib/vector-vrl/tests/Cargo.toml
> chore(deps): Bump VRL to 0.14.0

- changelog.d/20281_chronicle_labels_support.enhancement.md
- src/sinks/gcp/chronicle_unstructured.rs
- website/cue/reference/components/sinks/base/gcp_chronicle_unstructured.cue
> enhancement(chronicle sink): support labels

- website/content/en/docs/setup/installation/operating-systems/nixos.md
Fixed NixOS page to show module usage.
> doc: nixos.md: Corrected to showcase module usage

- Cargo.toml
> chore(deps): Bump VRL to 0.15.0

- changelog.d/remove_strict_env_vars.breaking.md
- docs/DEPRECATIONS.md
- src/cli.rs
- src/config/cmd.rs
- src/config/enterprise.rs
- src/config/loading/config_builder.rs
- src/config/loading/loader.rs
- src/config/loading/mod.rs
- src/config/loading/secret.rs
- src/config/loading/source.rs
- src/config/mod.rs
- src/config/unit_test/mod.rs
- src/config/vars.rs
- src/providers/http.rs
- src/validate.rs
- website/cue/reference/cli.cue
> chore(config)!: Remove deprecated `--strict-env-vars` flag

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate k8s manifests for chart 0.32.1

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Regenerate manifests for chart v0.33.0

- changelog.d/loki-sink-default-out-of-order-action-accept.breaking.md
- src/sinks/loki/config.rs
- website/cue/reference/components/sinks/base/loki.cue
> chore(loki sink): Changed OutOfOrderAction default to accept

- scripts/environment/bootstrap-windows-2019.ps1
Workaround for issue in nextest caused by a change in rustup: https://github.com/nextest-rs/nextest/issues/1493
Fixes:
```
error: creating test list failed
Caused by:
for `vector-config-macros`, command
`'C:\a\vector\vector\target\debug\deps\vector_config_macros-4fc11cf764d99dff.exe' --list --format
terse` exited with code 0xc0000135: The specified module could not be found. (os error 126)
```
> chore(ci): Fix nextest / rustup dll issue

- Cargo.lock
- Cargo.toml
- src/transforms/reduce/merge_strategy.rs
https://datadoghq.atlassian.net/browse/OPA-1702
> chore(reduce): add arbitrary trait

- src/sinks/elasticsearch/mod.rs
Adding this attribute to facilitate internal proptesting
> chore(elasticsearch): add arbitrary trait to ElasticsearchApiVersion

- website/cue/reference/remap/functions/decrypt.cue
> docs(vrl): Correct documentation of algorithms supported by `decrypt`

- .github/workflows/k8s_e2e.yml
> chore(ci): Update minikube to v1.33.1

- changelog.d/alpine-update.enhancement.md
- distribution/docker/alpine/Dockerfile
- distribution/docker/distroless-static/Dockerfile
> chore(deps): Bump Alpine Linux base image to 3.20

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Bump k8s manifests to v0.34.0 of the chart

- .github/workflows/comment-trigger.yml
Removed in 5e7981ce4362e3491283c2ac9fcd19147fda69cb
> chore(ci): Remove reference to the deleted workload checks workflow

- .github/workflows/comment-trigger.yml
> chore(ci): Restrict comment trigger workflow to repository

- CONTRIBUTING.md
> chore(dev): Add a note to CONTRIBUTING.md about running clippy

- website/cue/reference/urls.cue
> chore(docs): Fix link to unit tests

- .github/workflows/changes.yml
- .github/workflows/integration.yml
Until we can get them passing again
> chore(ci): Temporarily disable eventstoredb integration tests

- Cargo.lock
- Cargo.toml
> chore(deps): Upgrade VRL to v0.17.0

- .github/CODEOWNERS
> chore(ci): Add global CODEOWNERS fallback

- lib/vector-common/src/byte_size_of.rs
- website/content/en/blog/log-namespacing.md
- website/cue/reference/configuration.cue
> docs(external docs): Fix the wrong log-namespace key.

- website/cue/reference/remap/functions/to_int.cue
> fix(docs, vrl stdlib): Document that `to_int` coerces `null`s

- Cargo.lock
- Cargo.toml
- lib/codecs/Cargo.toml
- lib/codecs/src/encoding/format/protobuf.rs
- src/conditions/datadog_search.rs
- website/cue/reference/remap/functions/match_datadog_query.cue
There are a number of breaking changes in VRL, so this adjusts Vector in advance of a full release of VRL.
> chore(deps): Bump VRL to the latest ref

- .github/workflows/regression.yml
When triggered by a [Pull Request
Review](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=submitted#pull_request_review).
> chore(ci): Fix fetching PR number for regression workflow

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(relasing): Regenerate k8s manifsts for chart 0.35.0

- .github/workflows/integration.yml
> fix(ci): usage of `a deprecated Node.js version`

- scripts/environment/bootstrap-ubuntu-20.04.sh
> chore(ci): Update version of cue to latest (0.10.0)

- Cargo.lock
- Cargo.toml
- changelog.d/21201_fields_iter.fix.md
- distribution/install.sh
- lib/vector-core/src/event/test/mod.rs
- lib/vector-core/src/event/util/log/all_fields.rs
- src/transforms/reduce/transform.rs
- website/content/en/releases/0.40.2.md
- website/cue/reference/releases/0.40.0.cue
- website/cue/reference/releases/0.40.2.cue
- website/cue/reference/versions.cue
Checklist: https://github.com/vectordotdev/vector/issues/21225
> chore(releasing): Prepare v0.40.2 release

- changelog.d/20836-more_aggregations.enhancement.md
- src/transforms/aggregate.rs
- website/cue/reference/components/transforms/base/aggregate.cue
Adds more functions to `aggregate` transform.
Closes: #3668
> feat(aggregate transform): add more aggregations to aggregate transform

- website/config.toml
> Update public key

- website/cue/reference/releases/0.41.0.cue
> chore(releasing): Add known issue around `source_event_id` for v0.41.0

- .github/actions/spelling/expect.txt
- changelog.d/18876_loki_structured_metadata.feature.md
- changelog.d/20138_aws_sso_support_for_secrets_manager_backend.fix.md
- changelog.d/20812_add_greptime_log_sink.feature.md
- changelog.d/20899_static_metrics.feature.md
- changelog.d/20930_socket_sink_accepts_metrics.fix.md
- changelog.d/20946_support_geoip_anonymousip_database.enhancement.md
- changelog.d/20994_honeycomb_sink_support_configurable_endpoint.feature.md
- changelog.d/20996_recursive_config_watcher.fix.md
- changelog.d/21036_kafka_sink_error_status.enhancement.md
- changelog.d/21039_allow-usage-of-metrics-only-decoders.fix.md
- changelog.d/21041_influxdb-decoder-timestamp-precision.fix.md
- changelog.d/21103_kafka_sink_oidc_authentication.enhancement.md
- changelog.d/21129_suppress_warnings_for_kafka_sink.fix.md
- changelog.d/21141_fix_crash_when_handling_metrics.fix.md
- changelog.d/21179_datadog_search_numbers.fix.md
- changelog.d/defer-log-schema-defaults.fix.md
- changelog.d/file-sources-exclude-patterns-not-match-some-files.fix.md
- changelog.d/http-server-query-params-with-namespace.fix.md
- changelog.d/socket-not-respecting-global-log-namespace.fix.md
- changelog.d/support-config-watch-for-windows.enhancement.md
- distribution/install.sh
- website/content/en/releases/0.41.0.md
- website/cue/reference/administration/interfaces/kubectl.cue
- website/cue/reference/releases/0.41.0.cue
- website/cue/reference/versions.cue
Checklist: https://github.com/vectordotdev/vector/issues/21228
> chore(releasing): Prepare v0.41.0 release

- website/cue/reference/releases/0.40.0.cue
> docs: Fix typo in 0.40.0 release changelog

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
> chore(releasing): Update manifests to v0.36.1 of the chart

- lib/vector-core/src/event/metadata.rs
Adds merging logic for the recently added `source_event_id`. The strategy here is to keep the oldest UUID. This is useful for N -> 1 transforms.
> fix(metadata): merge 'source_event_id's

- website/cue/reference/remap/functions/parse_influxdb.cue
> docs(vrl): Fix typo in parse_influxdb function description

- .github/ISSUE_TEMPLATE/patch-release.md
- The changelog key is added automatically
- The version number should be bumped before running the release cue generation
> chore(releasing): Minor tweaks to patch template

- changelog.d/21173_http_server_options_support.feature.md
- src/sources/util/http/method.rs
- src/sources/util/http/prelude.rs
- src/sources/util/http_client.rs
- website/cue/reference/components/sources/base/http.cue
- website/cue/reference/components/sources/base/http_client.cue
- website/cue/reference/components/sources/base/http_server.cue
Hello, 
* feat(http_server/http_client): OPTIONS http method support
* description: for #21169  add support OPTIONS method for http (client, server) sources
> http (server,client) OPTIONS method added

- Cargo.lock
> chore(deps): Bump community-id from 0.2.2 to 0.2.3

- lib/vector-vrl/web-playground/README.md
- scripts/ensure-wasm-pack-installed.sh
- scripts/environment/prepare.sh
> chore(deps): Use wasm-pack 0.13.0

- regression/cases/datadog_agent_remap_blackhole/lading/lading.yaml
- regression/cases/datadog_agent_remap_blackhole_acks/lading/lading.yaml
- regression/cases/datadog_agent_remap_datadog_logs/lading/lading.yaml
- regression/cases/datadog_agent_remap_datadog_logs_acks/lading/lading.yaml
- regression/cases/file_to_blackhole/lading/lading.yaml
- regression/cases/fluent_elasticsearch/lading/lading.yaml
- regression/cases/http_elasticsearch/lading/lading.yaml
- regression/cases/http_text_to_http_json/lading/lading.yaml
- regression/cases/http_text_to_http_json/vector/vector.yaml
- regression/cases/http_to_http_acks/lading/lading.yaml
- regression/cases/http_to_http_json/lading/lading.yaml
- regression/cases/http_to_http_noack/lading/lading.yaml
- regression/cases/http_to_s3/lading/lading.yaml
- regression/cases/otlp_grpc_to_blackhole/lading/lading.yaml
- regression/cases/otlp_http_to_blackhole/lading/lading.yaml
- regression/cases/socket_to_socket_blackhole/lading/lading.yaml
- regression/cases/splunk_hec_indexer_ack_blackhole/lading/lading.yaml
- regression/cases/splunk_hec_route_s3/lading/lading.yaml
- regression/cases/splunk_hec_to_splunk_hec_logs_acks/lading/lading.yaml
- regression/cases/splunk_hec_to_splunk_hec_logs_noack/lading/lading.yaml
- regression/cases/syslog_humio_logs/lading/lading.yaml
- regression/cases/syslog_log2metric_humio_metrics/lading/lading.yaml
- regression/cases/syslog_log2metric_splunk_hec_metrics/lading/lading.yaml
- regression/cases/syslog_log2metric_tag_cardinality_limit_blackhole/lading/lading.yaml
- regression/cases/syslog_loki/lading/lading.yaml
- regression/cases/syslog_regex_logs2metric_ddmetrics/lading/lading.yaml
- regression/cases/syslog_splunk_hec_logs/lading/lading.yaml
> chore(ci): Collect Vector telemetry in regression tests

- website/cue/reference/data_model/schema.cue
> fix(docs): Metric `namespace` should be optional

- docs/DEVELOPING.md
> fix(docs): typo

- website/cue/reference/components/sources/kubernetes_logs.cue
> docs(kubernetes_logs source): Clarify that the source only tails logs from the host

- regression/cases/file_to_blackhole/lading/lading.yaml
- regression/cases/fluent_elasticsearch/lading/lading.yaml
- regression/cases/otlp_grpc_to_blackhole/lading/lading.yaml
- regression/cases/socket_to_socket_blackhole/lading/lading.yaml
- regression/cases/syslog_humio_logs/lading/lading.yaml
- regression/cases/syslog_log2metric_humio_metrics/lading/lading.yaml
- regression/cases/syslog_log2metric_splunk_hec_metrics/lading/lading.yaml
- regression/cases/syslog_log2metric_tag_cardinality_limit_blackhole/lading/lading.yaml
- regression/cases/syslog_loki/lading/lading.yaml
- regression/cases/syslog_regex_logs2metric_ddmetrics/lading/lading.yaml
- regression/cases/syslog_splunk_hec_logs/lading/lading.yaml
- regression/config.yaml
Update lading to latest to pull in zstd support.
> chore(deps): Update lading to 0.23.3

- .github/workflows/regression.yml
> chore(deps): Downgrade smp to 0.16.1

- docs/DEPRECATIONS.md
> chore(docs): Fix link in DEPRECATIONS.md

- .github/CODEOWNERS
So that they are flagged for changes
> chore(ci): Add SMP as CODEOWNERS for .github/workflows/regression.yml

- .github/workflows/regression.yml
Currently ignores changes to regression.yml
> chore(ci): Run regression tests if workflow changed

- .github/workflows/test.yml
> chore(ci): add source changed gate in test.yml

- .github/CODEOWNERS
* The motivation of this PR to reduce noise for the OP team.
* Ensured via the Github settings that the OP team can still approve/merge PRs.
* @vectordotdev/observability-pipelines: Please ping me if there is any problem after this change.
> chore(CODEOWNERS): remove OP team

- .github/workflows/regression.yml
- Cargo.lock
Side-effect: cargo lock needed an update
> chore(ci): fix ignore filter

- .github/SUPPORT.md
- website/content/en/community/_index.md
Preview: https://pront-website-discord-followups.d1a7j77663uxsc.amplifyapp.com/community/
> chore(external docs): update support and community docs

- lib/vector-core/src/event/metric/mod.rs
- website/cue/reference/components/transforms/base/log_to_metric.cue
Fix a typo in the `MetricsKind` doc comment.
> docs(core): fix MetricsKind typo

- website/content/en/docs/reference/vrl/_index.md
The new page: https://pront-website-improve-vrl-guide.d1a7j77663uxsc.amplifyapp.com/docs/reference/vrl/
> chore(external docs): improve vrl.dev tutorial

- README.md
This PR formats the markdown tables in the README.
> chore: format markdown tables

- .github/workflows/semantic.yml
The current scope set is a bit too restrictive.
> chore(ci): additional scopes

- .github/workflows/semantic.yml
- website/cue/reference/components/sources/static_metrics.cue
> docs(static_metrics source): Fix example configuration

- .github/PULL_REQUEST_TEMPLATE.md
> chore(administration): improve GitHub PR template

- src/conditions/vrl.rs
- src/transforms/route.rs
- website/cue/reference/components/transforms/base/route.cue
- website/cue/reference/components/transforms/route.cue
closes: https://github.com/vectordotdev/vector/issues/9014
> chore(external docs): improve `route` transform docs

- .github/workflows/publish.yml
To properly support v4 we will need to do more work.
Revert to actions/upload-artifact@v3. 
Revert to actions/download-artifact@v3. 
See difference in behavior: 
* v3: https://github.com/vectordotdev/vector/actions/runs/11529095671/job/32097126538
* v4: https://github.com/vectordotdev/vector/actions/runs/11615653091/job/32346806272
Nightly workflow on this branch:
https://github.com/vectordotdev/vector/actions/runs/11618231339
> fix(ci): Revert to actions/[upload,download]-artifact@v3

- website/cue/reference/components/sinks/vector.cue
> docs(vector sink): Added proxy option to Vector sink

- regression/cases/datadog_agent_remap_blackhole/lading/lading.yaml
- regression/cases/datadog_agent_remap_blackhole_acks/lading/lading.yaml
- regression/cases/datadog_agent_remap_datadog_logs/lading/lading.yaml
- regression/cases/datadog_agent_remap_datadog_logs_acks/lading/lading.yaml
- regression/cases/file_to_blackhole/lading/lading.yaml
- regression/cases/fluent_elasticsearch/lading/lading.yaml
- regression/cases/http_elasticsearch/lading/lading.yaml
- regression/cases/http_text_to_http_json/lading/lading.yaml
- regression/cases/http_to_http_acks/lading/lading.yaml
- regression/cases/http_to_http_json/lading/lading.yaml
- regression/cases/http_to_http_noack/lading/lading.yaml
- regression/cases/http_to_s3/lading/lading.yaml
- regression/cases/otlp_grpc_to_blackhole/lading/lading.yaml
- regression/cases/otlp_http_to_blackhole/lading/lading.yaml
- regression/cases/socket_to_socket_blackhole/lading/lading.yaml
- regression/cases/splunk_hec_indexer_ack_blackhole/lading/lading.yaml
- regression/cases/splunk_hec_route_s3/lading/lading.yaml
- regression/cases/splunk_hec_to_splunk_hec_logs_acks/lading/lading.yaml
- regression/cases/splunk_hec_to_splunk_hec_logs_noack/lading/lading.yaml
- regression/cases/syslog_humio_logs/lading/lading.yaml
- regression/cases/syslog_log2metric_humio_metrics/lading/lading.yaml
- regression/cases/syslog_log2metric_splunk_hec_metrics/lading/lading.yaml
- regression/cases/syslog_log2metric_tag_cardinality_limit_blackhole/lading/lading.yaml
- regression/cases/syslog_loki/lading/lading.yaml
- regression/cases/syslog_regex_logs2metric_ddmetrics/lading/lading.yaml
- regression/cases/syslog_splunk_hec_logs/lading/lading.yaml
- regression/config.yaml
> chore(ci): Fix scraping of target metrics by lading

- scripts/environment/Dockerfile
This was flagged by https://docs.docker.com/reference/build-checks/stage-name-casing/ for being uppercase over here: https://github.com/vectordotdev/vector/pull/19683/files, but is also unnecessary since there is only one stage in this Dockerfile.
CI
> chore(ci): Remove environment stage name

- .github/workflows/publish.yml
Recently GitHub published this deprecation notice: 
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
This PR updates the remaining users of `@v3` packages to `@v4`. An unfortunate consequence is that we will stop verifying targets for Ubuntu 16 & 18, however we have no reason to expect any breakage there. 
* https://github.com/vectordotdev/vector/actions/runs/11710613939
* https://github.com/vectordotdev/vector/actions/runs/11711422229
Ref: https://github.com/vectordotdev/vector/issues/21721
> chore(ci): update all remaining GitHub actions v3 packages to v4

- Cargo.toml
This PR updates the `datadog-signing-keys` recommended package version
I'm not entirely sure this doesn't qualify as a user facing change, but I don't feel like it warrant a changelog entry. Please feel free to request one though!
> chore(dev): update datadog-signing-keys recommended version

- src/sinks/elasticsearch/common.rs
The new `service_type` is only used for OpenSearch AWS authentication.
`cargo check --no-default-features --features sinks-elasticsearch`
Follow-up to #21676
> chore(dev): Gate additional parameters in elasticsearch sink

- .github/workflows/regression.yml
We changed the default to readonly so each workflow which caused these steps to fail, but we don't actually need them now that the workflow runs nightly and not on PRs.
I'll test by running the workflow.
Related: https://github.com/vectordotdev/vector/pull/21773
> chore(ci): Remove vestigial commit status steps from regression workflow

- .github/workflows/master_merge_queue.yml
- .github/workflows/publish.yml
- .github/workflows/unit_mac.yml
- scripts/environment/bootstrap-macos.sh
The https://github.com/Homebrew/homebrew-cask/issues/150323 issue was fixed.
> chore(ci): remove 'unset HOMEBREW_NO_INSTALL_FROM_API' line

- Cargo.toml
- src/config/loading/mod.rs
> chore(dev): delete transforms-pipelines feature

- Cargo.lock
- Cargo.toml
- lib/codecs/Cargo.toml
- lib/dnsmsg-parser/Cargo.toml
- lib/dnsmsg-parser/src/dns_message_parser.rs
- lib/docs-renderer/Cargo.toml
- lib/prometheus-parser/Cargo.toml
- lib/vector-buffers/Cargo.toml
- lib/vector-common/Cargo.toml
- lib/vector-config/Cargo.toml
- lib/vector-core/Cargo.toml
- lib/vector-tap/Cargo.toml
* Make `snafu` a workspace dependency
* Remove `thiserror` dependency
* it only has one usage and we can achieve the same with snafu (the motivation is consistency) 
closes: https://github.com/vectordotdev/vector/pull/21754
> chore(deps): make snafu a workspace dependency

- .github/workflows/build_preview_sites.yml
- .github/workflows/create_preview_sites.yml
- scripts/environment/bootstrap-ubuntu-20.04.sh
Hugo installed by another CI workflow.
> chore(ci): delete unusued deps from ubuntu bootstrap

- .github/workflows/build_preview_sites.yml
https://github.com/vectordotdev/vector/actions/runs/11938767613
```
The workflow is not valid. .github/workflows/build_preview_sites.yml (Line: 10, Col: 3): Error calling workflow 'vectordotdev/vector/.github/workflows/create_preview_sites.yml@6cf6df5af282514cd48b534e027faf2c5c69b0fe'. The workflow is requesting 'issues: write', but is only allowed 'issues: none'.
```
> chore(ci): add issues write perms to build_preview_sites.yml

- .github/workflows/build_preview_sites.yml
- .github/workflows/create_preview_sites.yml
> fix(ci): add more perms for website preview workflows

- website/cue/reference/releases/0.30.0.cue
Tested with `cd website && make run-production-site-locally`.
> chore(website): remove invalid link

- .github/workflows/publish.yml
Fix for https://github.com/vectordotdev/vector/actions/runs/12024154544/job/33520578206
> fix(ci): drop ubuntu 23.04, use 24.04(LTS)

- website/cue/reference/remap/functions/parse_regex_all.cue
Removes the failure reason for `parse_regex_all`, which has different semantics from `parse_regex` when there is no match.
closes #21883
N/A
> docs(external): remove incorrect failure reason for parse_regex_all fallibility

- .github/workflows/scorecard.yml
Introducing an OpenSSF Scorecard in a GitHub repository provides a tool to assess the security posture of the repository by evaluating it against a set of best practices.
https://securityscorecards.dev/#the-problem
> feat(ci): introduce OSSF scorecard

- website/cue/reference/remap/functions/zip.cue
Ref: https://github.com/vectordotdev/vrl/issues/1157 and https://github.com/vectordotdev/vrl/pull/1158
> docs(vrl): Add documentation for new `zip` function

- .github/ISSUE_TEMPLATE/minor-release.md
Added some helpful context around the website updates. 
> chore(dev): tweaks to the minor release guide

- Cargo.lock
I think cherry-picking the release commit had a conflict that didn't resolve correctly: https://github.com/vectordotdev/vector/commit/023f5fef2775dc676122159d1733ec1f88849c4f
Ran `cargo check`
> chore(dev): Regenerate Cargo.lock to fix bad conflict resolution

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
Release step.
https://github.com/vectordotdev/vector/issues/21893
> chore(releasing): cargo vdev build manifests

- .github/dependabot.yml
Weekly strikes a better balance. 
> chore(ci): change some  dependabot schedules to weekly

- .github/dependabot.yml
The bot will start updating all transitive dependencies as well.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow
> chore(ci): dependabot allow all dep types

- Cargo.lock
- Cargo.toml
https://github.com/vectordotdev/vector/issues/21893
> chore(releasing): bump vector version to 0.44.0

- website/cue/reference/remap/functions/parse_float.cue
- website/cue/reference/remap/functions/parse_regex_all.cue
If `internal_failure_reasons` is empty, we create an `infallible` badge. 
This PR fixes two badges for functions that were falsely advertised as infallible.
> docs(external): fix fallibility badge

- .github/workflows/regression.yml
Based on my experience, we do not gain much by running this weekly. The trade-off is less noise at the cost of more bisecting efforts if a regression is found. We can always increase the frequency in the future if we find it hard to debug perf regressions when they happen.
> chore(ci): run regression suite weekly

- .github/workflows/regression.yml
https://github.com/vectordotdev/vector/pull/21979 updated the schedule to weekly, but it was still looking for the SHA from 24 hours ago meaning that most commits wouldn't be tested.
Will be tested by CI.
> chore(ci): Fix baseline SHA default for new weekly schedule

- .github/workflows/regression.yml
This should reduce false positives. Now that we are only running weekly, bumping this shouldn't lead to a large increase in costs. We should reconsider this configuration if we start running this on PRs again.
Will rely on CI.
> chore(dev): Bump regression replicas to 100

- .github/workflows/nightly.yml
There are usually no commits during the weekend.
> chore(ci): run nightly workflow on weekday commits (only)

- changelog.d/21988_emit_build_info_interval.fix.md
- src/internal_events/heartbeat.rs
- src/internal_events/process.rs
Emit `build_info` gauge on an interval to avoid expiration.
Edit:
Fixes: https://github.com/vectordotdev/vector/issues/21988
> fix(internal_metrics source): Emit `build_info` gauge on an interval

- Cargo.lock
- changelog.d/21988_emit_build_info_interval.fix.md
- changelog.d/21989-reduce-quote-invalid-path.fix.md
- distribution/install.sh
- website/content/en/releases/0.43.1.md
- website/cue/reference/releases/0.43.1.cue
- website/cue/reference/versions.cue
https://github.com/vectordotdev/vector/issues/21992
> chore(releasing): cherry-pick v0.43.1 patch commits

- .github/workflows/integration.yml
The `humio/humio` image these depend on was archived and the new `humio/humio-single-node-demo` image requires a license key that we don't have.
We will need to follow up on this to decide what to do with these tests.
Will use CI.
> chore(ci): Skip humio integration tests in CI

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
Release step
- Closes: https://github.com/vectordotdev/vector/issues/21992
> chore(releasing): build manifests for vector 0.43.1 chart 0.38.1

- .github/workflows/regression.yml
> chore(ci): SMP increase timeout to 120 mins

- .github/workflows/regression.yml
GitHub Actions didn't like using an environment variable in timeout-minutes.
Relying on CI.
- https://github.com/vectordotdev/vector/commit/d8dcf6c1ade08cec43a7d184a40db1561e28dad8
> chore(ci): Fix SMP job timeouts

- .github/workflows/changelog.yaml
- .github/workflows/changes.yml
- .github/workflows/ci-integration-review.yml
- .github/workflows/ci-review-trigger.yml
- .github/workflows/cli.yml
- .github/workflows/component_features.yml
- .github/workflows/create_preview_sites.yml
- .github/workflows/cross.yml
- .github/workflows/deny.yml
- .github/workflows/e2e.yml
- .github/workflows/gardener_issue_comment.yml
- .github/workflows/gardener_open_issue.yml
- .github/workflows/gardener_open_pr.yml
- .github/workflows/gardener_remove_waiting_author.yml
- .github/workflows/integration.yml
- .github/workflows/k8s_e2e.yml
- .github/workflows/msrv.yml
- .github/workflows/preview_site_trigger.yml
- .github/workflows/protobuf.yml
- .github/workflows/regression.yml
- .github/workflows/scorecard.yml
- .github/workflows/semantic.yml
- .github/workflows/spelling.yml
`ubuntu-latest` recently changed to 24.04 for some workflows which caused unexpected breakages. I think it is better to pin to a specific version and upgrade as-needed rather than track latest and have it break unexpectedly.
Will test with CI.
> chore(ci): Pin ubuntu versions in GHA

- .github/workflows/deny.yml
Similar to https://github.com/vectordotdev/vector/pull/22056 the timeout for `deny` seems to be too small now since the image version was pinned. Bumping.
> chore(ci): Bump cargo-deny timeout

- website/cue/reference/remap/functions/parse_klog.cue
Test is failing since it is dependent on the year. Updating to 2025.
`make test-vrl`
> chore(tests): Update year for parse_klog test

- website/cue/reference/remap/functions/parse_klog.cue
Add notice for `parse_klog` caveat.
https://github.com/vectordotdev/vrl/issues/8
> docs(external): add parse_klog notice

- website/cue/reference/remap/functions/parse_linux_authorization.cue
The logs don't include the year.
Auth logs don't include the year. https://github.com/vectordotdev/vector/pull/19493 made this change, but I think this was incorrect since the example input should match what users have.
The downside is that this test will break each year.
`make test-vrl`
Ref: https://github.com/vectordotdev/vector/pull/19493
> chore(vrl): Fix example for linux auth log

- website/cue/reference/components/sources/host_metrics.cue
Set the metric type to `counter`.
- Closes: https://github.com/vectordotdev/vector/issues/22066
> docs(external): fix network_* metric type

- website/cue/reference/releases/0.43.0.cue
- website/cue/reference/releases/0.43.1.cue
Adds https://github.com/vectordotdev/vector/issues/22129 to known release issues.
Closes: https://github.com/vectordotdev/vector/issues/22129
> docs(external): add known issue for v0.43.1

- .github/workflows/regression.yml
- PRIVACY.md
- docs/REVIEWING.md
- website/README.md
- website/package.json
- website/yarn.lock
Cleanup netlify deps and mentions.
```
cd website
make serve
```
> chore(website): remove obsolete mentions to netlify

- website/content/en/highlights/2025-01-13-0-44-0-upgrade-guide.md
Ref: https://github.com/vectordotdev/vector/pull/22192
> chore(releasing): docs feedback on v0.44.0

- website/cue/reference/remap/functions/parse_groks.cue
Document missing parameter and failure reasons.
Ref: …
> docs(external): fix 'parse-groks' VRL doc

- website/cue/reference/components/sinks/opentelemetry.cue
This PR adds an example payload the OpenTelemetry sink ships to the OTEL Collector, using wording provided based off of feedback from this PR: https://github.com/vectordotdev/vector/pull/22222
run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit …
> docs(external): Adds example log payload Vector ships OTEL Collector

- .github/workflows/integration.yml
- src/sinks/loki/tests.rs
We can detect if we can skip all jobs before spawning 33 jobs each time.
* Run when source code was changed: https://github.com/vectordotdev/vector/actions/runs/12835355683?pr=22237
* Run without any source code changes: https://github.com/vectordotdev/vector/actions/runs/12835784383 …
> chore(ci): integration test suite enhancements

- .github/workflows/unit_mac.yml
Bandaid for frequent failures.
Example: https://github.com/vectordotdev/vector/actions/runs/12835682586/job/35795656346 …
> fix(ci): bandaid for flaky macOS tests

- .github/workflows/regression.yml
To improve logging and help with debugging, this pull request updates Vector's CI to use the latest version of `smp`, v0.20.1.
I think this PR is part of testing the changes.
run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if …
> chore(ci): smp version: 0.19.3 -> 0.20.1

- Cargo.lock
> chore(dev): bump bitflags

- Cargo.lock
- distribution/install.sh
- website/scripts/cue.sh
Side-effect: Cargo.lock bitflags
> chore(dev): fix `vdev check scripts` warnings

- .github/workflows/regression.yml
- Cargo.lock
Display `report.md` in the workflow summary page. 
> chore(ci): display regression report in summary

- .github/ISSUE_TEMPLATE/feature.yml
> chore(dev): populated the new github 'type' field for features

- .github/workflows/regression.yml
As part of keeping Vector's `smp` up-to-date with latest stable, this pull request updates the `smp` version used in CI from 0.20.1 to 0.20.2.
By submitting it; if the Regression workflow is triggered, then running that workflow should exercises the changes in this PR. …
> chore(ci): update smp to 0.20.2

- .github/workflows/regression.yml
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error …
> fix(ci): make some final regression steps optional

- website/content/en/guides/_index.md
- website/content/en/guides/getting-started/_index.md
The 'getting started' guide was not included in the guides index.
> docs(external): fix getting starting guide rendering

- .github/workflows/integration.yml
https://github.com/vectordotdev/vector/pull/22242#issuecomment-2631762143
> chore(ci): make Integration Test Suite runnable on Actions

- Cargo.lock
- Cargo.toml
- lib/vector-core/src/tls/settings.rs
- src/http.rs
Fixes: https://github.com/vectordotdev/vector/actions/runs/13103787979/job/36555375584
> chore(deps): update openssl related crates

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
Reverted async-nats bump and tests are now passing.
Follow up: Need to ensure that the IT suite runs when dependencies change. …
> fix(ci): revert to a previous async-nats version 

- .github/workflows/integration.yml
Need to fast-forward the `check-all` step when in the merge queue.
> fix(ci): check for merge_group in check-all job

- .github/workflows/ci-integration-review.yml
- .github/workflows/integration.yml
- src/sinks/splunk_hec/logs/tests.rs
The integration test suite wasn't running for PRs in the merge queue. Now that this is fixed, test issues were exposed. …
> fix(ci): temporarily ignore failing tests

- changelog.d/22386_extend_watcher_paths.enhancement.md
- src/app.rs
- src/config/sink.rs
- src/sinks/http/config.rs
Fixes https://github.com/vectordotdev/vector/issues/17283
adding this sink to `config/vector.yaml` :
```
http_test:
type: "http"
inputs: ["parse_logs"]
uri: "http://test"
encoding:
codec: "json"
json:
pretty: true
tls:
crt_file: /etc/ssl/tls-cert/tls.crt
key_file: /etc/ssl/tls-cert/tls.key
```
then execute : 
`vector -c config/vector.yaml`
and we can see that tls files are part of the watcher paths :  …
> feat(cli): Add http sink tls cert/key to `config::watcher`

- website/yarn.lock
Fixes https://github.com/vectordotdev/vector/security/dependabot/63.
```
yarn upgrade @babel/core
yarn upgrade @babel/preset-env
``` …
> fix(website): use safe semver version

- .github/workflows/integration.yml
- src/sources/datadog_agent/mod.rs
Contributor PRs don't have access to secrets (for various valid reasons). See example:
https://github.com/vectordotdev/vector/actions/runs/13245571933/job/36971462667?pr=22236
However, we always run the integration tests suite in the merge queue and that should catch all regressions. We don't need to run this workflow on PRs directly.
run …
> chore(ci): only run integration tests when secrets are available

- changelog.d/22386_extend_watcher_paths.enhancement.md
- src/app.rs
- src/config/sink.rs
- src/sinks/http/config.rs
Reverts vectordotdev/vector#22386
Based on https://github.com/vectordotdev/vector/issues/17283#issuecomment-2651060238
> fix(cli): Revert add http sink tls cert/key to `config::watcher`

- lib/vector-config-common/src/constants.rs
- lib/vector-config-macros/src/attrs.rs
- lib/vector-config-macros/src/component_name.rs
- lib/vector-config-macros/src/configurable_component.rs
- lib/vector-config-macros/src/lib.rs
- lib/vector-config/src/component/marker.rs
- lib/vector-config/src/component/mod.rs
- scripts/generate-component-docs.rb
- src/config/api.rs
- website/cue/reference/api.cue
- website/cue/reference/base/api.cue
This is follow-up PR for #22408, perhaps the last one.
```bash
make generate-component-docs
cd website
make run-production-site-locally
``` …
> docs(external): Generate API docs from Rust code

- .github/workflows/publish.yml
Fix for https://github.com/vectordotdev/vector/actions/runs/13500848978/job/37725226087
Ref: …
> chore(ci): update publish-homebrew token

- changelog.d/host_metrics_process_metrics.fix.md
- src/sources/host_metrics/mod.rs
- src/sources/host_metrics/process.rs
- Closes: https://github.com/vectordotdev/vector/issues/22474
> fix(host_metrics source): use single system instance

- Cargo.toml
- lib/vector-config-common/src/schema/json_schema.rs
- lib/vector-config/src/schema/parser/query.rs
- lib/vector-config/src/schema/visitors/unevaluated.rs
- lib/vector-core/src/config/global_options.rs
- lib/vector-core/src/config/proxy.rs
- lib/vector-core/src/metrics/recorder.rs
- rust-toolchain.toml
- src/api/schema/metrics/source/file.rs
- src/encoding_transcode.rs
- src/secrets/exec.rs
- src/sinks/aws_cloudwatch_metrics/mod.rs
- src/sinks/azure_blob/integration_tests.rs
- src/sinks/datadog/traces/sink.rs
- src/sinks/vector/mod.rs
- src/sources/gcp_pubsub.rs
- src/sources/host_metrics/cgroups.rs
- src/sources/internal_metrics.rs
- src/sources/prometheus/parser.rs
- src/sources/splunk_hec/mod.rs
- src/template.rs
- src/transforms/dedupe/config.rs
- src/transforms/dedupe/mod.rs
- vdev/src/commands/e2e/mod.rs
- vdev/src/commands/integration/mod.rs
- vdev/src/testing/runner.rs
Update the Rust toolchain version to 1.85
> chore(dev): switch to Rust 1.85

- src/sources/host_metrics/tcp.rs
These tests are flakey. It seems like the TCP metrics are working so instead of reverting the whole PR, we can ignore the tests for now and debug/fix at a second phase.
run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). …
> chore(host_metrics source): ignore flakey tcp metrics tests

- .github/workflows/publish.yml
- scripts/environment/bootstrap-macos.sh
Fixes https://github.com/vectordotdev/vector/actions/runs/13668919992/job/38215409934
Similar to https://github.com/vectordotdev/vector/pull/22572 …
> fix(ci): install rust toolchain for macos nightly targets

- PRIVACY.md
- Removes the netlify reference from the Privacy markdown
> chore(website): WEB-5803 | Remove netifly references from Privacy markdown

- .github/workflows/regression.yml
Update `smp` CLI to the latest stable version, 0.21.0.
Please note Vector's SMP team has not been updated yet. I will deploy that update once this PR is approved, and need to do that before this PR is merged.
SMP is tested separately; changes in this PR will not run until Vector's Regression Detector workflow runs.
run `dd-rust-license-tool …
> chore(ci): update smp to 0.21.0

- Cargo.lock
- LICENSE-3rdparty.csv
- deny.toml
Fixed by:
* adding two unmaintained crates
* updating `ring`
> fix(ci): deny check fixes

- .github/workflows/k8s_e2e.yml
This is a bandaid for the most flakey job. To make things worse, this job runs at the very end, after all other checks have passed, and prevents PRs from merging. 
To be investigated at a later time.
run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and …
> chore(ci): add retries to k8s test job

- deny.toml
Currently failing: https://github.com/vectordotdev/vector/actions/runs/13800717849/attempts/1
> fix(ci): add new unmaintained dependency

- website/Makefile
- Remove linkcheck command from CI Make commands
Ref: …
> fix(website): Remove link checker command from CI commands

- README.md
Closes: https://github.com/vectordotdev/vector/issues/22530
> chore(website): fix enrichment table link

- .github/CODEOWNERS
Update CODEOWNERS rules to include the `vector-website` team. Also, specify a more accurate rule for the `documentation` team. …
> chore(administration): update CODEOWNERS for website related PRs

- website/content/en/guides/level-up/csv-enrichment-guide.md
fix typo in csv enrichment guide
> docs(external): fix typo in csv enrichment guide

- website/content/en/docs/about/under-the-hood/guarantees.md
Add `alpha` definition
https://github.com/vectordotdev/vector/discussions/22534#discussioncomment-1234305 …
> docs(website): add `alpha` definition

- .github/dependabot.yml
- .github/workflows/semantic.yml
The main motivation is to add the `no-changelog` label to website PRs automatically.
I will keep an eye out for this next Monday. …
> chore(ci): add the npm package ecosystem for dependabot

- src/sinks/s3_common/sink.rs
Due to the fact that there is no way to define a default value for a template value that may not exist as a workaround I'd like to create a custom partitioner for a given component. However the S3 sink only accepts a partitioner of type `S3Partitioner`.
This patch opens up the interface to the S3Sink to allow it to accept any type that implements `Partitioner` as long as its associated types `Item` and `Key` are the same as the `S3Partitioner`s (respectively `Event` and `Option<S3PartitionKey>`)
Against a local branch of OPW passing the new Partitioner type into the S3Sink::new() constructor
defined [here](https://github.com/vectordotdev/vector/blob/1ef01aeeef592c21d32ba4d663e199f0608f615b/Makefile#L450-L454). Some of …
> chore(sinks): Allow S3Sink builder to accept a type that implements Partitioner

- website/cue/reference/components/sinks/file.cue
- website/cue/reference/components/sources/file.cue
- website/cue/reference/components/sources/internal_metrics.cue
Add `open_files` metrics to the `file` source and sink docs. This metric is already supported but not documented. It was asked a few times by the community.  …
> docs(external): document 'open_files' metric

- website/content/en/docs/setup/installation/package-managers/homebrew.md
> docs(external): Clarify Homebrew support documentation

- website/content/en/blog/highlights-february-2025.md
- website/content/en/guides/developer/debugging.md
- website/scripts/typesense-index.ts
- Adds the `guides/developer` directory to search index
- Moves `guides/developer/debugging` to the developer directory
- Adds redirect for old double slug `debugging/debugging`
- Updates link in the February blog to remove the dobule debugging slug …
> fix(website): Update search index for developer guides

- scripts/environment/Dockerfile
We are now using 24.04 everywhere. 
CI checks.
> chore(ci): `scripts/environment/Dockerfile` now based on ubuntu-24.04

- .github/workflows/publish.yml
- scripts/build-docker.sh
- scripts/test-e2e-kubernetes.sh
Publish docker images to ghcr.io as well.
Note: I had to tweak the settings in https://github.com/vectordotdev/vector/pkgs/container/vector
https://github.com/vectordotdev/vector/actions/runs/13955142841
run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) …
> feat(ci): publish build images to the GitHub Container Registry

- website/cue/reference/components/sources/datadog_agent.cue
- website/cue/reference/urls.cue
Update link which pointed to deprecated OP docs and add a note for `zstd` compression.
```
cd website
make serve
``` …
> docs(external): fix DD agent docs

- changelog.d/add_headers_vector_source.enhancement.md
- src/sources/http_server.rs
- src/sources/vector/mod.rs
- website/cue/reference/components/sources/base/vector.cue
Reverts vectordotdev/vector#22695
Fix for: https://github.com/vectordotdev/vector/actions/runs/14119249793/job/39556308314
> chore(vector source): Revert add `headers` option"

- lib/vector-vrl/web-playground/README.md
fix dead link on web playground README
> docs(internal docs): fix dead link on web playground README

- website/cue/reference/remap/functions/is_nullish.cue
Provides much needed clarifications for the `is_nullish` function. …
> docs(external): fix is_nullish docs

- .github/PULL_REQUEST_TEMPLATE.md
> chore(dev): PR template enhancements

- distribution/kubernetes/vector-agent/kustomization.yaml
Service file exists, but not include in the kustomization.yaml
> chore(kubernetes platform): Update kustomization.yaml

- vdev/src/commands/release/prepare.rs
- vdev/src/git.rs
> chore(releasing): vdev perpare fixes

- .github/dependabot.yml
Updating monthly is a good trade-off because it reduces KTLO.
VRL can be updated more frequently (manually) if needed.
- The CI checks run only after we manually approve them. To minimize round-trips see the following local checks:
- `cargo clippy --workspace --all-targets …
> chore(ci): update interval changed to 'monthly'

- .github/CODEOWNERS
Example PR that needs docs review: https://github.com/vectordotdev/vector/pull/22702
> chore(administration): update CODEOWNERS files for cue docs PRs

- vdev/src/commands/release/homebrew.rs
Use modern GitHub repo link 
- The CI checks run only after we manually approve them. To minimize round-trips see the following local checks:
- `cargo nextest run --workspace` (alternatively, you can run `cargo test …
> fix(releasing): update homebrew repo link

- website/cue/reference/releases/0.46.0.cue
https://github.com/vectordotdev/vector/issues/22840
- After a review is requested, …
> chore(releasing): add known issue to v0.46.0

- config/examples/environment_variables.yaml
- config/examples/es_s3_hybrid.yaml
- config/examples/wrapped_json.yaml
- distribution/docker/README.md
- website/content/en/blog/graphql-api.md
- website/content/en/guides/advanced/cloudwatch-logs-firehose.md
update from
`/docs/reference/{sources, sinks, transforms}` 
to
`/docs/reference/configuration/{sources, sinks, transforms}`
The first dead link I found was the words "destination of your choice" in the guide [Ingesting AWS CloudWatch Logs via AWS Kinesis Firehose](https://vector.dev/guides/advanced/cloudwatch-logs-firehose/), and I ended up fixing more links as I found more.
- …
> docs(external): fix dead links to configuration reference

- .github/workflows/integration.yml
- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- distribution/install.sh
- scripts/integration/aws/compose.yaml
- src/sources/aws_sqs/source.rs
- website/content/en/releases/0.46.1.md
- website/cue/reference/releases/0.46.1.cue
- website/cue/reference/versions.cue
> chore(releasing): prepare v0.46.1

- Cargo.toml
- LICENSE-3rdparty.csv
- changelog.d/22857_junit_reports_for_unit_tests.feature.md
- src/unit_test.rs
Adds the ability to generate reports in JUnit format for vector unit tests. This allows to better integrate and visualize test results with CI/CD systems such as GitLab CI/CD.
<details>
<summary>Screenshots of unit tests results rendered in GitLab CI/CD UI</summary>
</details>
I don't _love_ the option name, so I am open to suggestions.
```sh
make check-licenses
make check-fmt
make check-clippy
make check-component-docs
```
- We recommend adding a `pre-push` hook, please see [this …
> feat(unit tests): add ability to generate JUnit reports

- .github/ISSUE_TEMPLATE/patch-release.md
> chore(dev): enhancements to the patch release template

- distribution/install.sh
- website/content/en/releases/0.46.1.md
- website/cue/reference/releases/0.46.1.cue
- website/cue/reference/versions.cue
> chore(releasing): add v0.46.1 patch commits

- website/cue/reference/releases/0.46.1.cue
> chore(website): fix rendering of 0.46.1.cue

- Cargo.lock
- Cargo.toml
- lib/vector-config-common/Cargo.toml
- lib/vector-config-common/src/validation.rs
- lib/vector-config-macros/Cargo.toml
Kudos to @tobz for the suggested workaround. …
> chore(deps): bump darling version

- .github/workflows/semantic.yml
- src/config/format.rs
- src/providers/http.rs
Support all config formats in HTTP Provider
Http config provider is not yet documented, hence no end-user side-effects expected. 
- Closes: [Vector Config Server](https://github.com/vectordotdev/vector/discussions/22709)
> enhancement(config provider): support all formats: YAML,TOML,JSON

- distribution/kubernetes/vector-agent/README.md
- distribution/kubernetes/vector-agent/configmap.yaml
- distribution/kubernetes/vector-agent/daemonset.yaml
- distribution/kubernetes/vector-agent/rbac.yaml
- distribution/kubernetes/vector-agent/service-headless.yaml
- distribution/kubernetes/vector-agent/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/README.md
- distribution/kubernetes/vector-aggregator/configmap.yaml
- distribution/kubernetes/vector-aggregator/service-headless.yaml
- distribution/kubernetes/vector-aggregator/service.yaml
- distribution/kubernetes/vector-aggregator/serviceaccount.yaml
- distribution/kubernetes/vector-aggregator/statefulset.yaml
- distribution/kubernetes/vector-stateless-aggregator/README.md
- distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
- distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
- distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
- distribution/kubernetes/vector-stateless-aggregator/service.yaml
- distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
```
cargo vdev build manifests
```
- After a review is requested, please avoid force …
> chore(releasing): build manifests - 0.46.1

- CONTRIBUTING.md
> docs(external): fix typo in CONTRIBUTING.md

- website/content/en/docs/about/concepts.md
> docs(external): updates concepts/traces page

- website/cue/reference/components/transforms/reduce.cue
Ref: #22945, #22962
- After a review is requested, please avoid force pushes to help us …
> docs(external): fix reduce transfrom examples

- vdev/src/commands/check/markdown.rs
- vdev/src/git.rs
Motivation: I have some ignored files in my local directory and this linter complains about them. 
- …
> chore(dev): run markdownlint on git files only

- .github/workflows/e2e.yml
Avoid noise on unrelated PRs while we investigate this.
- After a review is requested, …
> chore(ci): disable E2E datadog-logs test

- scripts/integration/Dockerfile
Follow up to https://github.com/vectordotdev/vector/pull/23049 …
> chore(ci): remove redundant rustup prefix

- scripts/e2e/Dockerfile
- scripts/integration/Dockerfile
- tilt/Dockerfile
> chore(ci): provide default RUST_VERSION if one is not specified

- scripts/e2e/Dockerfile
- scripts/environment/bootstrap-windows-2022.ps1
- scripts/environment/prepare.sh
- scripts/integration/Dockerfile
This hasn't been updated for a while. We can benefit from better error messages.
Changelog: https://nexte.st/changelog/#0.9.95
- …
> chore(ci): bump nextest to latest version

- scripts/e2e/Dockerfile
Same linking performance but faster workflows.
Tested this locally. …
> chore(ci): install mold (no need to build it)

- .github/workflows/e2e.yml
- .github/workflows/integration.yml
- scripts/e2e/datadog-logs/compose.yaml
- scripts/e2e/datadog-metrics/compose.yaml
- scripts/integration/amqp/compose.yaml
Fixes path resolution for docker compose configs.
We can go further and use the long syntax:
```
volumes:
- type: bind
source: ../../../tests/data/e2e/datadog/logs/agent_only.yaml
target: /etc/datadog-agent/datadog.yaml
bind:
create_host_path: false
```
The above would fail early with an obvious error. Probably worth a followup PR.
- Alternatively, we recommend running the following …
> fix(ci): path resolution for docker compose files

- vdev/src/commands/release/prepare.rs
> chore(releasing): relax prepare script branch creation

- vdev/src/commands/release/homebrew.rs
This avoids a password prompt. …
> fix(ci): update git repo url for homebrew release

- .github/ISSUE_TEMPLATE/minor-release.md
- .github/ISSUE_TEMPLATE/patch-release.md
> chore(releasing): improve release templates

- .github/workflows/regression.yml
SMP updated vector's backend infra, new client version to match. …
> chore(ci): Updates SMP cli client version

- scripts/e2e/datadog-logs/compose.yaml
- scripts/int-e2e-test.sh
- vdev/src/testing/config.rs
- vdev/src/testing/integration.rs
Follow up to https://github.com/vectordotdev/vector/pull/23066. …
> chore(ci): add docker compose debug logs (if a test fails)

- docs/REVIEWING.md
> docs(internal docs): remove vector-test-harness from REVIEWING.md

- .github/actions/spelling/allow.txt
> chore(internal docs): Add enableable to allow.txt

- changelog.d/23199_opentelemetry_source_panic_on_nan_attributes.fix.md
- lib/opentelemetry-proto/src/common.rs
Receiving a `NaN` float value should not cause the otel source to panic & drop a batch.  Any `NaN` received is instead kept as null.
1. Created a unit test & ran them.  New test failed w/ old code and succeeded with fix.
2. Ran the new version and sent a `NaN` value; confirmed it delivers as null.
- Alternatively, we recommend running the following locally before pushing to the remote …
> fix(opentelemetry source): Handle NaN in opentelemetry source without panic

- website/content/en/docs/setup/installation/manual/from-source.md
Corrects the configuration file extension in the Windows startup command for Vector.  The original command `.\target\release\vector --config config\vector.toml` incorrectly used TOML extension,  while Vector's actual config file is YAML format.
- `cargo clippy …
> docs(website): Fix config extension typo in Windows command (from-source.md)

- .github/workflows/gardener_remove_waiting_author.yml
Fix for https://github.com/vectordotdev/vector/actions/runs/15662402196/job/44174548835?pr=22862
- …
> fix(ci): add missing perms to gardener_remove_waiting_author.yml

- Cargo.lock
- Cargo.toml
Bump greptimedb to latest revision `f7243393808640f5123b0d5b7b798da591a4df6e`. This also removes duplicate version of dashmap.
N/A …
> chore(deps): Bump greptimedb

- website/.prettierrc.json
- website/layouts/partials/data.html
- website/layouts/partials/logs_output.html
- website/package.json
- website/yarn.lock
Best reviewed by ignoring whitespace changes. …
> chore(website): prettier rc formatting of hugo/html

- .gitignore
- README.md
> chore(dev): improve gitignore

- lib/codecs/src/decoding/mod.rs
- src/sources/http_client/client.rs
- website/cue/reference/components/sinks/base/websocket_server.cue
- website/cue/reference/components/sources/base/amqp.cue
- website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
- website/cue/reference/components/sources/base/aws_s3.cue
- website/cue/reference/components/sources/base/aws_sqs.cue
- website/cue/reference/components/sources/base/datadog_agent.cue
- website/cue/reference/components/sources/base/demo_logs.cue
- website/cue/reference/components/sources/base/exec.cue
- website/cue/reference/components/sources/base/file_descriptor.cue
- website/cue/reference/components/sources/base/gcp_pubsub.cue
- website/cue/reference/components/sources/base/heroku_logs.cue
- website/cue/reference/components/sources/base/http.cue
- website/cue/reference/components/sources/base/http_client.cue
- website/cue/reference/components/sources/base/http_server.cue
- website/cue/reference/components/sources/base/kafka.cue
- website/cue/reference/components/sources/base/mqtt.cue
- website/cue/reference/components/sources/base/nats.cue
- website/cue/reference/components/sources/base/pulsar.cue
- website/cue/reference/components/sources/base/redis.cue
- website/cue/reference/components/sources/base/socket.cue
- website/cue/reference/components/sources/base/stdin.cue
> chore(website): improve decoder docs

- website/cue/reference/components/transforms/aggregate.cue
- website/cue/reference/components/transforms/dedupe.cue
- website/cue/reference/components/transforms/exclusive_route.cue
- website/cue/reference/components/transforms/filter.cue
- website/cue/reference/components/transforms/log_to_metric.cue
- website/cue/reference/components/transforms/lua.cue
- website/cue/reference/components/transforms/metric_to_log.cue
- website/cue/reference/components/transforms/reduce.cue
- website/cue/reference/components/transforms/route.cue
- website/cue/reference/components/transforms/sample.cue
- website/cue/reference/components/transforms/tag_cardinality_limit.cue
- website/cue/reference/components/transforms/throttle.cue
- website/cue/reference/components/transforms/window.cue
> chore(website): add/fix telemetry input & output for transforms

- .github/workflows/integration.yml
- Cargo.lock
We always want to run the IT suite in the MQ.
NA
Should run in the MQ after this is approved.
Related: https://github.com/vectordotdev/vector/issues/23253
- `cargo nextest run --workspace` (alternatively, you …
> fix(ci): always run 'integration-tests' for the MQ

- .github/workflows/integration.yml
- Cargo.toml
Use source changes in integration.yml. Without this dependencies is never set
- After a review is requested, please avoid force …
> fix(ci): Use source changes in integration.yml

- .github/workflows/integration.yml
Require changes to run before downloading artifacts. Without this the integration.yml job would fail on a workflow_dispatch
NA
NA …
> fix(ci): require changes to run before downloading artifacts

- .github/workflows/integration.yml
Reverts vectordotdev/vector#23281
> Revert "fix(ci): require changes to run before downloading artifacts"

- website/assets/js/app.js
Use YAML for the default config language
NA
`make serve` in an incognito tab and open the any source/sink. Verify that the default config language is `yaml` instead of `toml` (sorry Tom) …
> chore(website): use YAML for the default config language

- .github/workflows/msrv.yml
> feat(ci): add workflow_dispatch to msrv

- .github/ISSUE_TEMPLATE/minor-release.md
- .gitignore
- Related: #23257
- Feel free to push …
> chore(releasing): improve minor release documentation

- website/layouts/partials/author-with-avatar.html
> fix(website): remove leftover dbg statement

- Cargo.lock
Fixes a build error on macos:
```
--- stderr
src/smoke.c:4:10: warning: cast to smaller integer type 'int' from 'uLong (*)(uLong, const Bytef *, uInt)' (aka 'unsigned long (*)(unsigned long, const unsigned char *, unsigned int)') [-Wpointer-to-int-cast]
4 |   return (int) adler32;
|          ^~~~~~~~~~~~~
1 warning generated.
error: cannot parse the debug map for '/dev/null': The file was not recognized as a valid object file
clang: error: dsymutil command failed with exit code 1 (use -v to see invocation)
```
`cargo build`
`cargo update -p libz-sys`
- up to date macos
- up to date rust infra
- up to date packages from brew
Don't think so. Build works, everything seems compatible.
- Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getti …
> chore(dev): Bump libz-sys for macos compatibility

- .github/workflows/integration.yml
Re-enables the Splunk IT suite.
N/A
CI run and:
```
./scripts/int-e2e-test.sh int splunk
```
closes: https://github.com/vectordotdev/vector/issues/22379
- `cargo nextest run --workspace` (alternatively, you can …
> fix(ci): re-enable splunk ITs

- .github/workflows/publish.yml
NA
NA
- Feel free to push as many …
> chore(ci): rename name for publish-github job

- .github/workflows/changelog.yaml
- scripts/check_changelog_fragments.sh
Checkout changelog script from master instead of running script from current branch
NA
NA
Related: #23376
> fix(ci): checkout changelog script from master

- deny.toml
The MIT-0 license was recently added to the VRL repo. We can allow it here as well.
N/A
```
cargo deny check
```
- After a review …
> fix(ci): add MIT-0 to allowed licenses

- tests/data/dnstap/Dockerfile
Fix for https://github.com/vectordotdev/vector/actions/runs/16327993327/job/46123151532?pr=23388
https://github.com/vectordotdev/vector/pull/23389#pullrequestreview-3026505561
- `cargo nextest run --workspace` …
> fix(ci): use Debian-native bind package

- .github/workflows/changes.yml
- .github/workflows/test.yml
- Makefile
- vdev/README.md
This splits up the test.yml workflow, which is currently the slowest workflow that runs in every PR. Tests currently run sequentially and this will make it so they run in parallel.
NA
Let ci run
- `cargo nextest …
> feat(ci): split up test.yml

- .github/workflows/test.yml
Merged both make test and make test-component-validation and upload test results. Test result upload was mistakenly removed in a previous PR.
When running locally running both commands sequentially doesn't take too much time, likely reusing compiled artifacts so it makes sense to merge these jobs even if not for uploading test results.
NA
Let ci run
- Related: #23383
> chore(ci): merge test/test-component-validation and upload results

- src/sinks/elasticsearch/common.rs
Add _ assignment to unused var for feature. `make check-component-features` was failing due to this
NA
`scripts/check-one-feature sinks-elasticsearch`
https://github.com/vectordotdev/vector/actions/runs/16359067684/job/46223514934
- `cargo clippy --workspace …
> fix(elasticsearch sink): allow unused var 

- .github/workflows/changelog.yaml
- changelog.d/test.fix.md
- scripts/check_changelog_fragments.sh
Refactor changelog file fetching. This way we never checkout more untrusted code than necessary.
NA
Added `on.pull_request` to the job to see changes. See successful run here: https://github.com/vectordotdev/vector/actions/runs/16426755331/job/46418842410?pr=23405
> chore(ci): refactor changelog file fetching

- benches/batch.rs
- benches/codecs/encoder.rs
- benches/codecs/newline_bytes.rs
- benches/distribution_statistic.rs
- benches/dnstap/mod.rs
- benches/enrichment_tables.rs
- benches/lua.rs
- benches/metrics_snapshot.rs
- benches/transform/common.rs
- benches/transform/dedupe.rs
- benches/transform/reduce.rs
- benches/transform/route.rs
- src/components/validation/runner/mod.rs
- tests/integration/cli.rs
- tests/integration/shutdown.rs
Discovered a bunch of errors when I ran:
```
cargo clippy --all-targets --all-features
```
These where not discovered by `vdev`. …
> chore(dev): clippy fixes

- scripts/int-e2e-test.sh
> chore(ci): scripts/int-e2e-test.sh debugging improvements

- .github/workflows/ci-integration-review.yml
> fix(ci): fix trigger for DD logs E2E

- scripts/int-e2e-test.sh
IT suite and E2E suite passes (minus the already failing OTEL e2e case) …
> fix(ci): remove arbitrary sleep

- scripts/int-e2e-test.sh
`vdev` is inconsistent with it's usage of temp files and the original compose.yaml file. …
> chore(ci): workaround vdev issues by using project-name for debug logs

- .github/workflows/e2e.yml
- scripts/e2e/opentelemetry-logs/compose.yaml
- scripts/int-e2e-test.sh
- tests/data/e2e/opentelemetry/logs/collector-sink.yaml
- tests/data/e2e/opentelemetry/logs/vector.yaml
- tests/e2e/mod.rs
- tests/e2e/opentelemetry/logs/mod.rs
* CI runs the tests as root which created file permissions issues
* Jobs dep graph was off, now it is guaranteed that logs will only start generating after all consumers are up
* Refactors the test driver (no need for async fns)
Future improvements:
* Make vdev run healthchecks 
* Rely on docker volumes exclusively (and provide an easy way to extract artifacts to the test driver)
- …
> chore(ci): fix and renable otel logs e2e

- .github/workflows/semantic.yml
We need to add `datadog_common sink` regarding to https://github.com/vectordotdev/vector/pull/23514#issuecomment-3156196666 .
Related: #23514
- `cargo nextest run --workspace` (alternatively, you can run `cargo …
> chore(ci): add datadog_common sink to semantic.yml

- src/api/tests.rs
```
cargo clippy --all-targets --all-features
```
This is a `make check-clippy` blind spot. …
> fix(dev): update test config

- changelog.d/log_to_metric_pair_expansion_error.fix.md
- src/internal_events/expansion.rs
- src/internal_events/mod.rs
- src/transforms/log_to_metric.rs
This PR introduces and emits a new error type. This error was silently ignored before.   …
> fix(log_to_metric transform): emit PairExpansion error

- .github/workflows/ci-integration-review.yml
- .github/workflows/e2e.yml
- .github/workflows/integration.yml
- .github/workflows/k8s_e2e.yml
- .github/workflows/master_merge_queue.yml
- .github/workflows/regression.yml
This standardizes the last step in many workflows that were only checking for failure and missed the check for cancelled
NA
/ci-run-all
- Related: https://github.com/vectordotdev/vector/actions/runs/16788246058/attempts/1?pr=22431
- `cargo clippy --workspace …
> fix(ci): fail when jobs are cancelled

- .github/workflows/semantic.yml
- Cargo.lock
- lib/opentelemetry-proto/Cargo.toml
- lib/opentelemetry-proto/build.rs
Rework how `build.rs` discover and builds OTEL protos.
Existing tests.  …
> chore(opentelemetry lib): improve build.rs

- .github/workflows/changes.yml
> fix(ci): fix not_website matcher

- website/layouts/highlights/li.html
Add a margin between the author and the badges in the release highlight section.
Go to `/releases/0.45.0/`
| Before | After |
|--------|------|
| <img width="314" height="210" alt="image" src="https://github.com/user-attachments/assets/623048f2-071b-43b2-aa43-b2437f857e13" /> | <img width="315" height="216" alt="image" src="https://github.com/user-attachments/assets/2ca8ea30-5297-483b-880d-0bf84fc984fe" /> |
NA
`make serve`
- We recommend adding a `pre-push` hook, please see [this …
> chore(website): Add a margin between the author and the badges

- website/content/en/highlights/2025-08-12-0-49-0-upgrade-guide.md
- website/cue/reference/releases/0.49.0.cue
Address review feedback: https://github.com/vectordotdev/vector/pull/23563#pullrequestreview-3112201946 …
> chore(website): 0.49.0 release - address docs review

- .github/workflows/semantic.yml
Also added `deprecations`.
- Feel free …
> chore(ci): sort semantic scopes

- website/content/en/highlights/2025-08-12-0-49-0-upgrade-guide.md
- website/layouts/partials/admonition.html
Document Vector 0.49.0 behavior change
NA
`make serve`
- Related: #23585 …
> fix(website): document Vector 0.49.0 behavior change

- .github/workflows/msrv.yml
We discovered that this timeout is hit multiple times and the PR fails to merge.
- After a review is requested, please avoid …
> fix(ci): msrv increase timeout

- CONTRIBUTING.md
- Makefile
- vdev/src/commands/check/rust.rs
* clippy is the default now
* added a fix flag
* auto-commit any fixes …
> chore(vdev): rust clippy enhancements

- lib/k8s-e2e-tests/tests/vector-agent.rs
- lib/k8s-e2e-tests/tests/vector-aggregator.rs
- lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
- lib/k8s-e2e-tests/tests/vector.rs
- vdev/src/commands/check/rust.rs
* pass `all-features` to cover all code
* fixed discovered issues
- After a review is requested, please avoid force pushes to …
> chore(vdev): fix default features to all-features

- scripts/run-integration-test.sh
We now do:
```
./scripts/run-integration-test.sh -r 1 -e latest-vector_oltp.yaml    e2e    opentelemetry-logs
```
Note that this only affect local runs. CI will iterate over all environments.
- `cargo nextest …
> fix(dev): fixed environment parsing for local IT runs

- src/api/schema/metrics/mod.rs
- src/internal_events/aws_sqs.rs
- src/internal_events/websocket.rs
Fix failures: https://github.com/vectordotdev/vector/actions/runs/17282102483/attempts/1 …
> fix(ci): features check

- vdev/Cargo.toml
Add properties to Cargo.toml 
Eventually we would like to bininstall this tool.
- After a review is requested, please avoid force …
> chore(vdev): prepare for crates.io

- Cargo.lock
- scripts/environment/bootstrap-macos.sh
> chore(ci): simplify bootstrap-macos.sh

- regression/cases/file_100_to_blackhole/experiment.yaml
- regression/cases/file_100_to_blackhole/lading/lading.yaml
- regression/cases/file_100_to_blackhole/vector/vector.yaml
As title states
NA
Running regression test
https://github.com/vectordotdev/vector/actions/runs/17586156954
- Related: #23612
> chore(performance): add 100 file source regression test

- scripts/integration/mongodb/compose.yaml
https://github.com/vectordotdev/vector/issues/23796
CI: https://github.com/vectordotdev/vector/actions/runs/17806132216/job/50618403722?pr=23797
- `make fmt`
- `make test`
- After …
> fix(ci): use legacy mongodb image

- changelog.d/aws_retry_strategy.fix.md
- src/sinks/aws_s3/config.rs
- src/sinks/s3_common/config.rs
- website/cue/reference/components/sinks/generated/aws_s3.cue
- website/cue/reference/releases/0.49.0.cue
Fix the default retry strategy. 
Improved documentation to explicitly state what errors are considered retriable.
Closes: https://github.com/vectordotdev/vector/issues/23616
Related: https://github.com/vectordotdev/vector/pull/23206
- `make fmt`
- `make check-clippy` (if there are …
> fix(aws_s3 sink): fix default retry strategy

- .github/workflows/environment.yml
- .github/workflows/master_merge_queue.yml
Context here: https://github.com/vectordotdev/vector/issues/23799
- `make fmt`
- `make test` …
> chore(ci): publish dev environment weekly

- .github/workflows/publish-homebrew.yml
- Makefile
- vdev/src/commands/release/homebrew.rs
* Need a dedicated PAT since we are writing to another repo
* Avoid env vars when possible
- `make fmt`
- `make test`
- After a review is requested, please avoid force pushes to …
> chore(ci): homebrew workflow fixes

- .github/actions/spelling/expect.txt
- .github/actions/spelling/patterns.txt
- `make fmt`
- `make test`
- Feel free to push as many commits as you want. They will be …
> fix(dev): add .md authors spelling pattern

- .github/workflows/component_features.yml
- .github/workflows/k8s_e2e.yml
- `make fmt`
- `make test`
- Feel free to push as many commits as you want. They will be …
> chore(ci): spread out schedules

- scripts/environment/binstall.sh
- scripts/environment/bootstrap-windows-2025.ps1
Something changed, we started seeing failures in the windows CI
See: https://github.com/vectordotdev/vector/actions/runs/18106142460/job/51521104805
NA
`/ci-run-unit-windows`
- `make fmt`
- `make check-clippy` (if there are failures it's possible some of them can be fixed with `make …
> fix(ci): windows rustup stable not installed by default

- lib/codecs/src/decoding/framing/chunked_gelf.rs
- lib/file-source-common/src/buffer.rs
- lib/file-source/src/file_server.rs
- lib/vector-buffers/src/variants/disk_v2/common.rs
- lib/vector-core/src/event/array.rs
- lib/vector-core/src/event/estimated_json_encoded_size_of.rs
- lib/vector-core/src/event/test/common.rs
- rust-toolchain.toml
- src/sinks/new_relic/healthcheck.rs
- src/sinks/util/service/health.rs
- src/sources/host_metrics/disk.rs
- src/sources/host_metrics/filesystem.rs
- src/sources/util/mod.rs
- src/transforms/lua/v1/mod.rs
- src/transforms/lua/v2/mod.rs
- src/transforms/sample/transform.rs
- vdev/src/app.rs
Upgrade toolchain to use 1.90.
https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/
NA
`make check-clippy`
- Related: https://github.com/rust-lang/rust-clippy/issues/15787
> chore(dev): use rust 1.90

- lib/file-source-common/src/checkpointer.rs
- lib/file-source-common/src/fingerprinter.rs
- lib/file-source/src/file_server.rs
- src/sources/file.rs
- src/sources/kubernetes_logs/mod.rs
This buffer was shared for some reason. It is now internal, initialized once with the max capacity already allocated.
NA
make test
> feat(file source): make fingerprinter buffer internal

- Cargo.lock
- LICENSE-3rdparty.csv
- lib/codecs/src/encoding/format/protobuf.rs
VRL dependency update
- `make fmt`
- `make test` …
> chore(dev): update VRL

- .github/workflows/integration.yml
As title states
NA
Run CI/MQ
- Related: #23915
- `make fmt`
- `make test`
- Feel free to …
> chore(ci): Ignore E2E datadog-metrics

- scripts/e2e/Dockerfile
- scripts/integration/Dockerfile
As title states
NA
Run CI/MQ
- `make fmt`
- `make test`
- Feel free to push as many …
> feat(tests): binstall cargo nextest in int/e2e tests

- Cargo.lock
- Cargo.toml
bump sysinfo to 0.37.2
NA
CI/MQ
- `make fmt`
- `make test`
- Feel free to push as many …
> chore(deps): bump sysinfo to 0.37.2

- .github/workflows/integration.yml
CI was running ALL int/e2e tests in the MQ
NA
MQ
> fix(ci): only run changed integrations in the MQ

- website/content/en/guides/advanced/merge-multiline-logs-with-lua.md
- website/content/en/guides/advanced/parsing-csv-logs-with-lua.md
- website/content/en/guides/aws/aws-secrets-manager-example.md
- website/content/en/guides/aws/aws-secrets-manager.md
- website/content/en/guides/aws/cloudwatch-logs-firehose.md
Reorganize AWS guides.
Add tags and description. 
Fix weights.
- `make fmt`
- `make test` …
> chore(website): re-organize and improve aws guides

- .github/workflows/changes.yml
- .github/workflows/test.yml
These tests were running every time even when not necessary
NA
MQ
> feat(ci): only run tests when change conditions are met
