vectordotdev/vector

Cargo.lock
Cargo.toml

Prompted by https://github.com/vectordotdev/vector/issues/11257#issuecomment-1649238963

chore(deps): Update tokio-util fork to 0.7.8

---

src/sinks/websocket/sink.rs

fixes: https://github.com/vectordotdev/vector/issues/18037

fix(websocket sink): send encoded message as binary frame

---

lib/vector-core/src/config/log_schema.rs
lib/vector-core/src/event/log_event.rs
lib/vector-lookup/src/lookup_v2/optional_path.rs
src/sinks/datadog/events/sink.rs
src/sinks/datadog/logs/sink.rs
src/sinks/elasticsearch/config.rs
src/sinks/influxdb/logs.rs
src/sinks/mezmo.rs
src/sinks/sematext/logs.rs

The lookup migration involves eliminating `String`s in favor of other types can convert to a `TargetPath`.
This part of https://github.com/vectordotdev/vector/issues/7070 and specifically https://github.com/vectordotdev/vector/issues/18059.
* This PR focuses on `LogEvent` path lookups.
* Unifies the path retrieval API in `LogEvent`. Regardless of the log namespacing, a `&OwnedTargetPath` is returned.
* Supporting `Legacy` namespaces creates some friction: 
* Existing `LogSchema` accessors still return the _value_ path. I also added new _target_ path accessors.
* Eliminated string conversions and copies deep in the code. However, accessing paths later might require cloning the target path in some contexts.
* When `Legacy` namespace code is deleted, these inefficiencies will go away.

feat: replace LogEvent 'String's with '&OwnedTargetPath's

---

benches/template.rs
lib/codecs/src/decoding/format/bytes.rs
lib/codecs/src/decoding/format/gelf.rs
lib/codecs/src/decoding/format/json.rs
lib/codecs/src/decoding/format/syslog.rs
lib/opentelemetry-proto/src/convert.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/vrl_target.rs
src/sinks/humio/logs.rs
src/sinks/loki/integration_tests.rs
src/sources/aws_sqs/integration_tests.rs
src/sources/aws_sqs/source.rs
src/sources/docker_logs/tests.rs
src/sources/fluent/mod.rs
src/sources/journald.rs
src/sources/splunk_hec/mod.rs
src/sources/syslog.rs
src/transforms/log_to_metric.rs
src/transforms/metric_to_log.rs

This part of https://github.com/vectordotdev/vector/issues/18059.
* Use `&OwnedTargetPath` instead of instantiating tuples.
* Use `maybe_insert` to reduce code duplication.

feat: replace tuples with &OwnedTargetPath wherever possible

---

lib/vector-core/src/event/trace.rs
src/sinks/datadog/traces/tests.rs
src/source_sender/mod.rs
src/sources/datadog_agent/mod.rs
src/sources/datadog_agent/traces.rs
src/sources/http_client/client.rs
src/test_util/mock/transforms/basic.rs
src/transforms/sample.rs

The lookup migration involves eliminating Strings in favor of other types can convert to a TargetPath.
This part of https://github.com/vectordotdev/vector/issues/7070 and specifically https://github.com/vectordotdev/vector/issues/18059.
This change focuses on `TraceEvent::insert`. The goal is to pass path types instead of `String`s.

feat: Refactor TraceEvent insert to use TargetPath compatible types

---

lib/codecs/src/decoding/format/bytes.rs

fixes: https://github.com/vectordotdev/vector/issues/17935

fix: allow empty message_key value in config

---

Cargo.lock
lib/codecs/Cargo.toml
lib/codecs/src/decoding/format/syslog.rs

Syslog wasn't parsing escapes in the SD fields properly as per [this issue](https://github.com/StephenWakely/syslog-loose/issues/18).
That is now fixed in the Syslog parser, so this updates the library version. For the interested the PR that fixed it in the library is [this](https://github.com/StephenWakely/syslog-loose/pull/21).
This is also being updated in [VRL](https://github.com/vectordotdev/vrl/pull/353).

chore(codecs): Update syslog_loose to properly handle escapes

---

lib/codecs/src/decoding/format/protobuf.rs
website/cue/reference/components/sources/base/amqp.cue
website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
website/cue/reference/components/sources/base/aws_s3.cue
website/cue/reference/components/sources/base/aws_sqs.cue
website/cue/reference/components/sources/base/datadog_agent.cue
website/cue/reference/components/sources/base/demo_logs.cue
website/cue/reference/components/sources/base/exec.cue
website/cue/reference/components/sources/base/file_descriptor.cue
website/cue/reference/components/sources/base/gcp_pubsub.cue
website/cue/reference/components/sources/base/heroku_logs.cue
website/cue/reference/components/sources/base/http.cue
website/cue/reference/components/sources/base/http_client.cue
website/cue/reference/components/sources/base/http_server.cue
website/cue/reference/components/sources/base/kafka.cue
website/cue/reference/components/sources/base/nats.cue
website/cue/reference/components/sources/base/redis.cue
website/cue/reference/components/sources/base/socket.cue
website/cue/reference/components/sources/base/stdin.cue

Follow up to https://github.com/vectordotdev/vector/pull/18019#discussion_r1278192502
The option "namespacing" is per: https://github.com/vectordotdev/vector/blob/master/docs/specs/configuration.md#polymorphism

fix(codecs): Move protobuf codec options under a `protobuf` key

---

lib/codecs/src/decoding/format/bytes.rs
lib/vector-core/src/event/log_event.rs
src/sinks/clickhouse/integration_tests.rs
src/source_sender/mod.rs
src/sources/amqp.rs
src/sources/aws_sqs/source.rs
src/sources/datadog_agent/tests.rs
src/sources/docker_logs/tests.rs
src/sources/exec/mod.rs
src/sources/file.rs
src/sources/heroku_logs.rs
src/sources/http_client/integration_tests.rs
src/sources/http_server.rs
src/sources/splunk_hec/mod.rs
src/template.rs
src/test_util/mock/transforms/basic.rs
src/topology/test/mod.rs

This part of https://github.com/vectordotdev/vector/issues/7070.
* The change in this PR are straightforward. Paths expressed as `(PathPrefix, Something)` are replaced by target paths.
* I also used some accessors like `get_message()` wherever possible.

chore: replace path tuples with actual target paths

---

lib/codecs/src/decoding/format/protobuf.rs
lib/codecs/src/decoding/mod.rs
src/codecs/decoding/config.rs
src/components/validation/resources/http.rs
src/components/validation/resources/mod.rs
src/components/validation/runner/mod.rs
src/sources/amqp.rs
src/sources/aws_kinesis_firehose/mod.rs
src/sources/aws_s3/mod.rs
src/sources/aws_sqs/config.rs
src/sources/aws_sqs/source.rs
src/sources/datadog_agent/mod.rs
src/sources/demo_logs.rs
src/sources/exec/mod.rs
src/sources/file_descriptors/mod.rs
src/sources/gcp_pubsub.rs
src/sources/heroku_logs.rs
src/sources/http_client/client.rs
src/sources/http_server.rs
src/sources/kafka.rs
src/sources/nats.rs
src/sources/redis/mod.rs
src/sources/socket/mod.rs

fixes: https://github.com/vectordotdev/vector/issues/18110
Propagate an error up the stack instead of panicking at deserializer instantiation.

fix: propagate config build error instead of panicking

---

lib/vector-api-client/src/client.rs
src/config/api.rs
src/lib.rs
src/tap/cmd.rs
src/tap/mod.rs
src/top/cmd.rs
src/top/dashboard.rs
src/top/mod.rs

Ref [OPB-962](https://datadoghq.atlassian.net/browse/OPB-962), [OPB-961](https://datadoghq.atlassian.net/browse/OPB-961)
This PR
- Re-arranges logic in both `top` and `tap` for easier library usage, and makes said logic public

chore(api): Refactor top and tap for library use

---

.github/actions/spelling/excludes.txt

Currently we have a couple warnings from the spell checker GHA for a couple .pb files, which are binary so we should ignore them.

chore(ci): exclude protobuf files from spell checking

---

docs/tutorials/sinks/1_basic_sink.md
docs/tutorials/sinks/2_http_sink.md

The recent changes for the Data Volume tags work mean there were some changes to the sink framework. This updates the tutorials to bring them up to date.

chore(external docs): update sink tutorials with Data Volume tag changes

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv

Switches to the crates.io release of the Azure SDK in order to stop depending on a version from previous year and the big git clone it entails.

feat: switch to crates.io release of Azure SDK

---

src/sinks/util/buffer/compression.rs

TOML parses as as an i64.
Discovered by https://discord.com/channels/742820443487993987/1136935387407855750/1138056823530868746

fix(config): Fix TOML parsing of compression levels

---

lib/vector-core/src/event/discriminant.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/trace.rs
src/api/schema/events/trace.rs
src/conditions/datadog_search.rs
src/sinks/datadog/traces/apm_stats/aggregation.rs
src/sinks/datadog/traces/request_builder.rs
src/sinks/datadog/traces/sink.rs
src/sinks/elasticsearch/config.rs
src/sinks/new_relic/model.rs
src/sources/datadog_agent/traces.rs
src/template.rs
src/transforms/sample.rs

This part of https://github.com/vectordotdev/vector/issues/7070.
* All `event.get(...)` calls outside of test code should use path types instead of strings.
* For dynamic string values, I used `parse_target_path`. 
An important note here: Currently we do not propagate parsing errors, we just return `None` instead. This PR doesn't change this behavior because it would take significant extra effort to refactor the code to propagate/handle parsing errors.

feat: Refactor 'event.get()' to use path types

---

benches/event.rs
benches/lua.rs
benches/remap.rs
lib/codecs/src/decoding/format/gelf.rs
lib/codecs/src/encoding/format/gelf.rs
lib/codecs/src/gelf.rs
lib/vector-core/benches/event/log_event.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/test/size_of.rs
lib/vector-core/src/event/trace.rs
src/codecs/encoding/transformer.rs
src/config/unit_test/mod.rs
src/sinks/aws_cloudwatch_logs/integration_tests.rs
src/sinks/aws_cloudwatch_logs/request_builder.rs
src/sinks/azure_monitor_logs.rs
src/sinks/humio/logs.rs
src/sinks/influxdb/logs.rs
src/sources/dnstap/mod.rs
src/sources/kafka.rs
src/sources/logstash.rs
src/sources/syslog.rs
src/sources/util/framestream.rs
src/sources/vector/mod.rs
src/template.rs

This part of https://github.com/vectordotdev/vector/issues/7070 and specifically https://github.com/vectordotdev/vector/issues/18059.
* Update (almost) all non-test code to instantiate paths.
* Mostly used `find` and `sed` for this work. 
* I manually edited some more complex usages.  
* I will follow-up with another PR for those `.get` functions that take a dynamic string as argument (those need explicit parsing and error handling). 
* Found some places that can use the new log schema accessors.
Note: 
Currently we do not check for parsing errors. This PR doesn't change this behavior because it would take significant extra effort to refactor the code to propagate/handle parsing errors.

chore: replace various string paths with actual paths

---

lib/vector-core/src/event/log_event.rs

fix: make LogEvent index operator test only

---

src/sources/vector/mod.rs

This was added in tonic 0.9 but caused a regression in Vector behavior. I think ideally this would
be configurable, but I think in this case we can let users ask for it since the use-case for the
`vector` source/sink is primarily such that the operator controls both sides and doesn't need to
worry about DOS from misbehaving clients.
Fixes: https://github.com/vectordotdev/vector/issues/17926

fix(vector source): Remove the 4MB default for requests

---

src/conditions/vrl.rs

Follow-up for https://github.com/vectordotdev/vector/issues/17175. This is a quick fix to avoid shallowing the error completely, ideally we would refactor the `check` to return an error.

feat: panic if the condition return type is not a boolean

---

Cargo.lock
Cargo.toml
lib/vector-core/src/tls/settings.rs
scripts/cross/bootstrap-centos.sh
scripts/cross/bootstrap-ubuntu.sh
src/app.rs
src/cli.rs

Vector currently vendors the OpenSSL library. Since the current vendored sources in `openssl-src` are pinned at version 1.1.1* by `openssl-sys`, this change pulls in a fork of that crate that pins the sources to version 3.1.*. This will move all uses of OpenSSL in Vector over to version 3.1.
For backwards compatibility, the "legacy" provider is loaded when the `VECTOR_OPENSSL_LEGACY_PROVIDER` environment variable is set or the `--openssl-legacy-provider` cli arg is provided. This is similar to what[ Node.js does](https://nodejs.org/en/blog/release/v17.0.0).
We have confirmed that this successfully cross compiles.

chore(deps): Bump OpenSSL base version to 3.1.*

---

.github/workflows/regression.yml

This commit updates the smp binary to its latest release, removing a legacy flow with no user-facing change. Peer to
https://github.com/DataDog/datadog-agent/pull/18725. I have not opted to update lading in this PR as the jump from 0.12 to 0.18 is rather large, despite the branch name. 
REF SMP-673

chore: Update `smp` to its latest released version

---

.github/workflows/regression.yml

chore(deps): Upgrading version of lading used

---

src/sinks/elasticsearch/config.rs
src/sinks/elasticsearch/tests.rs

Add support for ES datastream with empty namespace or dataset.
closes: #17883
Signed-off-by: Artur Malchanau <artur.molchanov@bolt.eu>

 enhancement(elasticsearch sink): Allow empty data_stream fields

---

Makefile

This is a small follow up fix to my previous PR: #18112
Apologies as I didn't notice it before. On my Debian machine, the issue described does not happen 🙈.
The `make` command inside of the Vector environment image optimizes `$(shell ...)` such that if the command to run is simple enough, it will just call it directly without using a shell. The problem is that the `command` command used to check if the Rust toolchain is installed is a shell builtin and, when optimized, `make` invocations that use the `check-build-tools` target emit the following error:
make: command: Command not found
This commit fixes the issue by using a redirect, and thus forcing `make` to use the shell.
Ref: https://stackoverflow.com/a/12991757

fix(dev): fix Rust toolchain check in Makefile

---

benches/dnstap/mod.rs
src/sources/dnstap/mod.rs
src/sources/dnstap/parser.rs
src/sources/dnstap/schema.rs

This is part of #18059.
* Now using `OwnedValuePath`s instead of `&str`.
* Removed a lot unnecessary `strcut`s and accessors. Deleted a lot of dead code. 
* Made the parser stateless. 
* Now recursively building paths on the go.

feat: Refactor dnstap to use 'OwnedValuePath's

---

.github/actions/spelling/expect.txt
distribution/docker/alpine/Dockerfile
distribution/docker/debian/Dockerfile
distribution/docker/distroless-libc/Dockerfile
distribution/docker/distroless-static/Dockerfile

chore(releasing): Run hadolint on distributed Dockerfiles

---

deny.toml

Resolved by https://github.com/vectordotdev/vector/pull/18165

chore(deps): Remove an unneeded advisory ignore

---

.github/actions/spelling/expect.txt
Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
src/top/dashboard.rs
src/top/state.rs

The `tui` crate is unmaintained and points to `ratatui` as the mantained fork.

chore(deps): Swap tui crate for ratatui

---

src/sources/socket/mod.rs

The actual type of the port value on a tcp socket is a number, but the typedef was set to bytes (a string).

fix: socket tcp port typedef

---

src/sinks/elasticsearch/common.rs
src/sinks/elasticsearch/integration_tests.rs

fix(elasticsearch): Ignore `pipeline` argument if it is an empty string

---

Cargo.lock
Cargo.toml

Now that 0.32.0 has been released.

chore(releasing): Bump Vector to 0.33.0

---

Cargo.lock
LICENSE-3rdparty.csv
deny.toml

chore(deps): Bump `nkeys` to 0.3.2

---

website/content/en/highlights/2023-08-15-0-32-0-upgrade-guide.md

I forgot to do this prior to the release
(https://github.com/vectordotdev/vector/pull/17669#discussion_r1289029219).

chore(releasing): Add 0.32.0 highlight for legacy OpenSSL provider deprecation

---

Cargo.toml
benches/event.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/test/mod.rs
lib/vector-core/src/event/test/serialization.rs
lib/vector-core/src/event/util/log/all_fields.rs
lib/vector-core/src/event/util/log/mod.rs
lib/vector-lookup/Cargo.toml
lib/vector-lookup/src/lookup_v2/mod.rs
src/codecs/encoding/transformer.rs
src/sinks/azure_blob/integration_tests.rs
src/sinks/gcp/pubsub.rs
src/sources/dnstap/mod.rs
src/sources/exec/mod.rs
src/transforms/dedupe.rs
src/transforms/metric_to_log.rs

fixes: https://github.com/vectordotdev/vector/issues/18240
Partially addresses: https://github.com/vectordotdev/vector/issues/18247
Also, this is part of https://github.com/vectordotdev/vector/issues/18059.

feat: change dedupe config paths to `ConfigTargetPath`

---

src/app.rs
src/cli.rs

The OpenSSL documentation is unclear about whether or not the default provider remains loaded when calling `try_load` with `retain_fallbacks=true`. We now explicitly load the default provider to be safe.
This also fixes the `--openssl-legacy-provider` cli arg, which could previously only be set to true.
The following now work
```
vector --openssl-legacy-provider
vector --openssl-legacy-provider=true
vector --openssl-legacy-provider=false
VECTOR_OPENSSL_LEGACY_PROVIDER=true ./target/debug/vector
VECTOR_OPENSSL_LEGACY_PROVIDER=false ./target/debug/vector
```
But the below still result in an error
```
vector --openssl-legacy-provider true
vector --openssl-legacy-provider false
```
In the future, we will refactor this to allow the user to specify a list of providers to load …

fix(deps): load default and legacy openssl providers

---

src/transforms/sample.rs

closes: https://github.com/vectordotdev/vector/issues/18215
The `sample` transform adds a `sample_rate` field to the event. When log namespacing is enabled, this should be moved to the event metadata so it doesn't override fields on the event itself.

fix(sample transform): Use metadata when log namespacing is enabled

---

lib/vector-common/src/request_metadata.rs
src/sinks/util/encoding.rs

Fixes #18265
The `Encoder` implementation for batches of Events for the tuple Encoder `(Transformer, crate::codecs::Encoder<Framer>)` was only counting the first event in the batch.
This fixes the issue to ensure all events are counted and adds tests to ensure it is correct. I have also tested manually with the AWS S3 sink.
Affected sinks are:
- WebHDFS
- GCP Cloud Storage
- AWS S3
- Azure Blob Storage
- Azure Monitor Logs
- Databend
- Clickhouse 
- Datadog Logs

fix(observability): add all events that are being encoded

---

website/cue/reference/components/sources/internal_metrics.cue

A user noticed that this metric is emitted but not documented (https://github.com/vectordotdev/vector/issues/18296).

fix(docs): add the 'http_client_requests_sent_total'

---

Cargo.toml
src/sinks/util/encoding.rs

Ref #18265 
This refactors the `encode_input` function to use `itertools` to determine the last item in the list to encode. It's a slightly tidier pattern that removes the duplicate code

chore: tidy `encode_input` function

---

src/sources/opentelemetry/mod.rs

addresses: https://github.com/vectordotdev/vector/issues/17926
This is the same fix applied to the `vector` source in https://github.com/vectordotdev/vector/pull/18186 . The `opentelemetry` source needs the same explicit max decoding size fix.

fix(opentelemetry source): Remove the 4MB default for gRPC request decoding

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
lib/vector-config/Cargo.toml
lib/vector-config/src/http.rs
lib/vector-config/src/lib.rs
src/sources/heroku_logs.rs
src/sources/http_server.rs
src/sources/prometheus/remote_write.rs
src/sources/util/http/prelude.rs
website/cue/reference/components/sources/base/http.cue
website/cue/reference/components/sources/base/http_server.cue

enhancement(http_server source): Configurable http response code

---

Cargo.toml
src/internal_events/mod.rs
src/transforms/mod.rs

The `log_to_metric` transform was missing a corresponding Cargo feature. Therefore, when compiling Vector with a reduced set of features, this transform was always included even if not requested.
This is the only transform that was missing a Cargo feature.
I tested this by compiling Vector with different feature sets and verifying the resulting binary config schemas:
```
cargo build --no-default-features --features 'sources-exec sinks-console'
cargo build --no-default-features --features 'sources-exec transforms sinks-console'
cargo build --no-default-features --features 'sources-exec transforms-log_to_metric sinks-console'
```
Before this PR, the first build above would only include the `log_to_metric` transform, when I was expecting none. If I included a specific transform feature, it …

chore(log_to_metric transform): add missing Cargo feature

---

Cargo.toml
src/internal_events/mod.rs
src/transforms/mod.rs

This reverts commit 69621bd79ad38ed6059443c739886eb5d611b5af.
Replaces: https://github.com/vectordotdev/vector/pull/18322
It [was raised](https://github.com/vectordotdev/vector/pull/18308#discussion_r1300283300) that https://github.com/vectordotdev/vector/pull/18322 will be insufficient since that will cause dead code warnings.

chore(log_to_metric transform): Revert missing Cargo feature `transforms-log_to_metric`

---

Cargo.lock
Cargo.toml

Cargo appears to have an issue with tag names containing a `+` that causes it to re-fetch the git repos as well as the cargo.io index on each run. Changing those tag names resolves the issue.
Upstream issue: https://github.com/rust-lang/cargo/issues/11085

chore(deps): Fix issue with `cargo` refetching refs on every run

---

src/sinks/appsignal/integration_tests.rs
src/sinks/appsignal/mod.rs
src/sinks/appsignal/normalizer.rs
src/sinks/appsignal/sink.rs
src/sinks/datadog/metrics/normalizer.rs
src/sinks/statsd/normalizer.rs
src/test_util/metrics.rs

Implement a normaliser for the AppSignal sink to convert absolute
counter metrics to incremental counters, and incremental gauges to
absolute gauges. The AppSignal API ignores absolute counters and
incremental gauges, so this change adds support for absolute counters
and incremental gauges.
This normaliser is inspired by the DataDog normaliser.

feat(appsignal sink): Normalize metrics 

---

src/transforms/route.rs
website/cue/reference/components/transforms/base/route.cue

This PR adds a new boolean option `reroute_unmatched` to the `route` transform.
It is inspired on the `reroute_dropped` option in the `remap` transform, allowing the user to control if they want or not the `<transform_name>._unmatched` output to be created and used. For backwards compatibility, this new option defaults to `true`.
Users that are not interested in processing unmatched events can use this option to avoid the following warning on Vector startup, and also to remove the unnecessary `_unmatched` output in `vector top`:
```
WARN vector::config::loading: Transform "route._unmatched" has no consumers
```
An example issue benefiting from this option is #15865 (closed). In that issue, the solution to eliminate the warning was simply to route the `_unmatched` output to a blackhole …

feat(route transform): Add option to enable/disable unmatched output

---

Cargo.lock
Cargo.toml
deny.toml

There are 2 relevant advisories here:
- https://rustsec.org/advisories/RUSTSEC-2023-0053.html
- This was fixed by upgrading `rustls-webpki` to `0.101.4`
-  https://rustsec.org/advisories/RUSTSEC-2023-0052.html
- This requires migration from `webpki` to `rustls-webpki`. It was added to the `ignore` section of `deny.toml` until dependencies can be updated

chore: update `rustls-webpki` due to security advisory

---

website/cue/reference/remap/expressions/comparison.cue
website/cue/reference/remap/functions/match.cue
website/cue/reference/urls.cue

closes: https://github.com/vectordotdev/vrl/issues/365

chore(docs): add more comparison examples

---

.github/actions/spelling/allow.txt
website/content/en/docs/administration/tuning/_index.md
website/content/en/docs/administration/tuning/pgo.md

Adds PGO documentation as discussed in https://github.com/vectordotdev/vector/issues/15631#issuecomment-1542411520
Feel free to suggest changes to the layout/wording/etc. As an example, I used a similar page from the ClickHouse documentation: https://clickhouse.com/docs/en/operations/optimizing-performance/profile-guided-optimization . Putted the page to this place as @jszwedko suggested in https://github.com/vectordotdev/vector/issues/15631#issuecomment-1683075569 .

docs: add PGO information

---

lib/vector-core/src/event/vrl_target.rs
src/transforms/remap.rs

Fixes the issue mentioned here: https://github.com/vectordotdev/vector/discussions/17889#discussioncomment-6796480
If a `remap` transform returns an array, the event is split into multiple events. In certain cases, the log namespace was not being used, which meant some values were being nested under a `message` field when it shouldn't be. This is now fixed.

fix(remap transform): log namespace should be used when splitting events from arrays

---

.github/workflows/publish.yml
Makefile
website/content/en/highlights/2023-09-26-0-33-0-upgrade-guide.md

- feat: Begin publishing armv7hl rpm packages
- docs: Add 0.33.0 upgrade guide
Following [discussion and discovery](https://datadoghq.atlassian.net/browse/AP-2268) this PR begins the deprecation process for the `armv7` rpm package and replaces it with an `armv7hl` package.
Based on cloudsmith numbers, this package is very unused (less than 10 downloads per package, less than 20 in the last 25 versions).

feat: Begin publishing armv7hl rpm packages

---

src/generate.rs

This quick PR adds missing conditional compilation features to the tests, which fail when any of the `demo_logs` source, the `remap` transform or the `console` sink are not compiled.
Fixes the following test panics when these features are not used:
```
---- generate::tests::generate_basic_yaml stdout ----
thread 'generate::tests::generate_basic_yaml' panicked at 'called `Result::unwrap()` on an `Err` value: ["failed to generate source 'demo_logs': component 'demo_logs' does not exist", "failed to generate transform 'remap': component 'remap' does not exist"]', src/generate.rs:656:68
---- generate::tests::generate_basic_json stdout ----
thread 'generate::tests::generate_basic_json' panicked at 'called `Result::unwrap()` on an `Err` value: ["failed to generate source 'demo_logs': component …
```

fix(tests): fix tests for the generate command

---

Cargo.toml
src/components/validation/resources/mod.rs
src/sources/datadog_agent/tests.rs

This PR adds a new `codecs-syslog` feature to Vector mapped to the `codecs/syslog` package feature.
This allows for code requiring the `syslog` _codec_ to not depend on the `syslog` _source_ anymore and instead depend on the `syslog` codec directly. For example, it is now possible to compile any source with `syslog` codec support using `codecs-syslog` without having to compile the `syslog` source with it.
A concrete example is the following build configuration, which does not work without this PR:
```
cargo build --no-default-features --features 'sources-stdin sources-exec codecs-syslog sinks-console'
```
This will build a Vector with `stdin` and `exec` sources with `syslog` codec support, without needing the `syslog` source.
I tested building and ran testing of the affected compoenents, …

feat(dev): decouple syslog source and codec features

---

src/sources/file.rs
src/sources/kubernetes_logs/mod.rs
website/cue/reference/components/sources/base/file.cue
website/cue/reference/components/sources/base/kubernetes_logs.cue

In response to https://github.com/vectordotdev/vector/issues/18088#issuecomment-1690491190
Might close: https://github.com/vectordotdev/vector/issues/18088

enhancement(kubernetes_logs source): Expose `oldest_first`

---

scripts/environment/bootstrap-ubuntu-20.04.sh

It seems like it might be causing `docker-ce` to be uninstalled.

fix(ci): Drop docker-compose from bootstrap install

---

Cargo.lock
Cargo.toml

To include changes from latest release.

chore(deps): Update fork of rust-openssl

---

.github/workflows/regression.yml

Noticed that when the Comment Trigger workflow was initiated on a different PR than mine, it cancelled my in progress run. The k8s workflow correctly handles this but it was missing from Regression workflow. This appears to be the only one missing it.

fix(ci): add comment trigger filter for regression workflow concurrency group

---

src/aws/mod.rs

This uses the default provider for FIPS which checks environment variables and configuration files
for this setting.
Part of: #18382

enhancement(aws provider): Use FIPS endpoints when configured to do so

---

STYLE.md
docs/tutorials/sinks/1_basic_sink.md
lib/codecs/src/decoding/format/gelf.rs
lib/codecs/src/encoding/format/gelf.rs
lib/vector-core/src/event/estimated_json_encoded_size_of.rs
rfcs/2021-07-27-7117-vrl-string-interpolation.md
rfcs/2022-03-15-11851-ingest-opentelemetry-traces.md

docs(file source): fix some typos

---

.github/actions/spelling/allow.txt
Cargo.lock
Cargo.toml
src/config/format.rs
src/generate.rs

Fix a test bug introduced by https://github.com/vectordotdev/vector/pull/18345.
Basically, the `generate_all` test runs multiple times vs the desired behavior which is one time for each possible enum value.
The test cases should run only once per enum value. 
I didn't find a way to configure `proptest` to do just that and `rstest` looks like a great candidate for this use case.

fix: use `rstest` in `generate` command tests (vs wrong usage of `proptest`)

---

Cargo.toml
src/sinks/prometheus/exporter.rs
src/sinks/statsd/config.rs
src/sinks/util/service/net/udp.rs
src/sinks/util/udp.rs

We have a couple of dependency updates that require it (clap and rmpv).
I'd still like to define an official MSRV support policy for Vector, but in absence of that,
I figured I'd bump to not block the dependency updates. The only real downside is users trying to
build Vector on systems where they only have access to older versions of Rust; which seems to be
fairly rare currently.

chore(deps): Bump MSRV to 1.70.0

---

scripts/environment/bootstrap-macos-10.sh

Otherwise it fails to update Python with:
```
==> Upgrading python@3.11
3.11.4_1 -> 3.11.5
==> Pouring python@3.11--3.11.5.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
rm '/usr/local/bin/2to3'
To force the link and overwrite all conflicting files:
brew link --overwrite python@3.11
To list all files that would be deleted:
brew link --overwrite --dry-run python@3.11
```
Example: https://github.com/vectordotdev/vector/actions/runs/5995416388/job/16258473755

fix(ci): Unlink python before `brew install`

---

Cargo.lock
Cargo.toml
lib/codecs/src/decoding/format/gelf.rs
lib/codecs/src/encoding/format/gelf.rs
lib/vector-core/src/event/test/common.rs
src/sources/gcp_pubsub.rs

I thought this would trigger a load of "[this could be a `const fn`](https://rust-lang.github.io/rust-clippy/master/#/missing_const_for_fn)" clippy errors due to a number of `chrono` functions now being `const`, but I guess that lint isn't turned on in libs. Subject for another PR perhaps.
Ref: https://github.com/chronotope/chrono/releases/tag/v0.4.27

Bump `chrono` to 0.4.27

---

rust-doc/Makefile

With the migration to amplify by the websites team, we want to build the rust-doc just scoped to vector. While the migration is not complete, this has been built on amplify with the new `ci-docs-build` command. Leaving the original `docs` command in place for local development. 
Preview site can be found here: https://devin-ford-amplify-rust-doc.d1hoyoksbulg25.amplifyapp.com/vector/
**NOTE:** This change will **NOT** effect the current netlify deployment

chore(rust-doc): Add new Make command for CI builds

---

.github/actions/spelling/expect.txt
Makefile

This commits adds an override to disable force pulling the environment image, leaving the container tool to pull it only when necessary instead.
Before this change, every time `make environment ENVIRONMENT_AUTOBUILD=false` is executed, it would force pull the image in `ENVIRONMENT_UPSTREAM` even if the image already exists locally. This is not efficient when the value in `ENVIRONMENT_UPSTREAM` is a static/fixed tag.
With the new override, the environment can be started very quickly when the image exists locally:
make environment ENVIRONMENT_AUTOBUILD=false ENVIRONMENT_AUTOPULL=false
The default value for `ENVIRONMENT_AUTOPULL` is `true` to preserve the current behavior.

feat(dev): add `ENVIRONMENT_AUTOPULL` override to Makefile

---

Cargo.toml

Apparently `cargo-deb` is including an extra newline in the generated `conffiles` file which causes a bug when used with Uyuni/SUSE Manager (https://github.com/vectordotdev/vector/issues/18439). I opened an issue upstream, https://github.com/kornelski/cargo-deb/issues/110, but observed that we only have conffiles in `/etc` and so don't actually need to include a `conffiles` control file. Per the Debian docs:
> dh_installdeb(1) automatically flags any files under the /etc directory as conffiles, so if your program only has conffiles there you do not need to specify them in this file. For most package types, the only place conffiles should ever be is under /etc, and so this file doesn't need to exist.
Closes: https://github.com/vectordotdev/vector/issues/18439
Signed-off-by: Jesse Szwedko …

fix(debian platform): Remove `conf-files` directive for `cargo-deb`

---

website/content/en/docs/about/concepts.md

Since not all sources, including the `http_server` source, do actually handle back-pressure in the
described ways yet. This confused a user that was expecting that the `http_server` source would be
returning 429s in the precense of back-pressure.

chore(docs): Emphasize the "may" bit of the backpressure docs

---

scripts/environment/bootstrap-ubuntu-20.04.sh

So that the bootstrap script installs docker-compose when used by scripts/environment/Dockerfile
(but not in CI which already has it).

chore(ci): Re-add docker-compose installation

---

website/cue/reference/remap/functions/parse_nginx_log.cue
website/cue/reference/urls.cue

Adds notes about recently added `ingress_upstreaminfo` log format for `parse_nginx_log()` function [VRL PR here](https://github.com/vectordotdev/vrl/pull/193)

docs: Add notes about `ingress_upstreaminfo` log format for `parse_nginx_log()` function

---

src/sinks/elasticsearch/service.rs
src/sinks/prometheus/remote_write.rs

Ref: #18288 
There were a couple of extra spots that the mentioned PR should have feature gated to only use when the `aws-core` feature was included.

chore: feature gate aws-core features

---

.github/workflows/changes.yml
.github/workflows/cli.yml
.github/workflows/compilation-timings.yml
.github/workflows/component_features.yml
.github/workflows/cross.yml
.github/workflows/environment.yml
.github/workflows/gardener_remove_waiting_author.yml
.github/workflows/install-sh.yml
.github/workflows/integration-comment.yml
.github/workflows/integration-test.yml
.github/workflows/integration.yml
.github/workflows/k8s_e2e.yml
.github/workflows/misc.yml
.github/workflows/msrv.yml
.github/workflows/publish.yml
.github/workflows/regression.yml
.github/workflows/test.yml
.github/workflows/unit_mac.yml
.github/workflows/unit_windows.yml

This reverts #18476.
Unfortunately V4 of `actions/checkout` uses node 20 which does not appear to be compatible with Ubuntu versions < 20 and older versions of CentOS.

chore(ci): revert bump actions/checkout from 3 to 4

---

website/cue/reference/components/sources/syslog.cue

It is incorrectly documented as using `gethostname` on the host receiving the data, but actually
extracts the host from the log message itself.
Closes: #18371

fix(syslog source, docs): Fix docs for `host` field for syslog source

---

Cargo.lock
Cargo.toml

As `0.9.93` switches to OpenSSL `300.1.2`.
Also switch to upstream for `openssl-src` since the PR we needed was merged in there (just
unreleased).

chore(deps): Remove openssl-sys patch

---

.github/workflows/unit_mac.yml

Previously this job was a required check for merging into master. With the merge queue it isn't required and this job option is resulting in failures of this job to not fail out of the merge queue.

fix(ci): don't continue on errors in unit-mac test

---

website/scripts/create-config-examples.js

This prefix is only defined for yaml examples and is inconsistent with other examples.

fix(docs): remove '---\n' prefix from toYaml config example generator

---

lib/vector-vrl/web-playground/build.rs
lib/vector-vrl/web-playground/public/index.css
lib/vector-vrl/web-playground/public/index.html
lib/vector-vrl/web-playground/public/index.js

feat: Add git sha to the VRL playground header

---

src/internal_events/http_client.rs
src/sinks/util/http.rs

There is some history around this code. It appears that originally this internal metric was named with an `Error` suffix, and that at some point there was a change to emit this internal metric because of that suffix. When in reality, this condition should generally be retried by the upstream.

fix(observability): don't increment component_errors_total for `HttpClient` warning

---

website/cue/reference/components/aws.cue

The mention of automatic refresh led to some confusion since it seemed to apply to all methods but
really only applies to some of them. I also noted the additional places automatically checked by the
AWS Rust SDK (https://docs.aws.amazon.com/sdk-for-rust/latest/dg/credentials.html).
Closes: #18491

chore(aws provider, external_docs): Update the AWS authentication documentation

---

.github/dependabot.yml

This tells dependabot that we want the `azure_*` and `prost` crates to be grouped into a single PR.
Docs for the settings are [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups).

chore(ci): group azure and prost crates for dependabot

---

src/sinks/datadog/metrics/encoder.rs

Fixes #18353
As part of #17764, we ended up splitting some code that made a strong assumption (sketch is not empty) from the place where we checked that assumption was true. It appears that the check itself was lost (except in some test-only code, unfortunately), resulting in Vector panicking on now-unexpected input (empty sketch) that was previously just skipped.
This change moves the check for emptiness back into the same function where we require it, adjusting function signatures as needed to allow for skipping those inputs. It also adds a test that we can handle empty sketches without panicking.

fix: skip encoding empty sketches

---

.github/workflows/publish.yml

Ubuntu 22.10 is [no longer supported](https://ubuntu.com/about/release-cycle), which is now breaking the nightly builds. 
This removes 22.10 from the `deb-verify` job.

chore(ci): remove kinetic as it's no longer supported

---

src/sinks/datadog/logs/config.rs
src/sinks/datadog/mod.rs
website/content/en/highlights/2023-09-26-0-33-0-upgrade-guide.md
website/cue/reference/components/sinks/base/datadog_events.cue
website/cue/reference/components/sinks/base/datadog_logs.cue
website/cue/reference/components/sinks/base/datadog_metrics.cue
website/cue/reference/components/sinks/base/datadog_traces.cue

If an endpoint is specified for the datadog sink configs, we don't automatically append the path based on event types so it needs to be specified by the user.
This is in contrast to the other datadog sinks, which use the endpoint setting as a base url.
This PR updates the behavior of the logs sink to be consistent with the rest.
Note this is is a breaking change for users however it is an uncommon setting and is mainly useful in testing environments.

chore(datadog_logs sink)!: Use `endpoint` config setting consistent with the other datadog_ sinks.

---

src/internal_telemetry/allocations/mod.rs
src/topology/running.rs

This PR ensures that allocation groups are not created/attached to components unless allocation tracing itself is enabled at runtime. Prior to this PR, it would always create/attach them so long as allocation tracing support itself was compiled in. This has the side effect of emitting warnings about exhausting allocation group IDs for configurations with many components (> 128) even when allocation tracing wasn't being used.
We've also made the log message emit at the warning level, rather than the info level, to highlight this fact more prominently.
Fixes #18480.

fix(core): don't show warning about max allocation groups if tracing not enabled

---

distribution/rpm/vector.spec

fix(distribution): Use yaml instead of toml file

---

src/sinks/gcs_common/config.rs

Fixes #18432 
Ref #10870
This updates the GCP sinks so that Vector will retry the request on an unauthorized response (401).
A user reported that GCP was sending 401s after a time even when a correct token was being sent. The user tested a custom build that had this fix and that has completely resolved their issue. 
I don't understand why GCP would be sending a 401 and why resending the request puts GCP right. Without fully understanding what is going on, I am slightly concerned that this could be covering a deeper issue. But it does fix the immediate issue, so unless this is causing a regression in some way I think it is worth pushing this through.

fix(gcp service): retry on unauthorized

---

.github/ISSUE_TEMPLATE/minor-release.md
docs/DEPRECATION.md
docs/DEPRECATIONS.md

Add a file to track deprecations through their lifecycle and remind us to come back to take any
deprecation actions as part of each release.
See https://github.com/vectordotdev/vector/issues/14983 for the process proposal. The intent is to
make sure we follow through on deprecations, migrations, and removals.
Closes: https://github.com/vectordotdev/vector/issues/14983

chore(dev): Add DEPRECATIONS.md file to track deprecations

---

Cargo.lock
Cargo.toml
deny.toml
distribution/install.sh
src/aws/auth.rs
website/content/en/releases/0.32.2.md
website/cue/reference/releases/0.32.0.cue
website/cue/reference/releases/0.32.2.cue
website/cue/reference/versions.cue

Checklist: https://github.com/vectordotdev/vector/issues/18610

chore(releasing): Prepare v0.32.2 release

---

website/cue/reference/components/sources/internal_metrics.cue

Noticed by https://github.com/vectordotdev/vector/discussions/18615#discussioncomment-7063705

fix(external docs): Document intentional label on component_discarded_events_total

---

website/content/en/blog/vector-remap-language.md
website/content/en/guides/level-up/transformation.md
website/cue/reference/components/sinks.cue

chore(docs): Convert a few more configs to YAML

---

netlify.toml

To drop people into #support rather than #development since we get a lot of users asking support
questions in #development.

chore(website): Update chat.vector.dev redirect

---

Tiltfile
rust-toolchain.toml

chore(deps): Bump Rust to 1.72.1

---

.github/actions/spelling/expect.txt
src/app.rs
src/config/sink.rs
src/http.rs
src/lib.rs
src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/tests.rs
src/topology/builder.rs

Allow the Vector "app" name, which is used for the `User-Agent` and `DD-EVP-ORIGIN` headers, to be configurable at compilation time.
Also fixed `DD-EVP-ORIGIN` header value for when enterprise features are enabled. It was previously only set to `vector-enterprise` for the datadog internal logs sink. It is now set to `vector-enterprise` for all datadog logs sinks.

feature(enterprise): configurable app name

---

src/sinks/kafka/config.rs
src/sinks/kafka/request_builder.rs
src/sinks/kafka/service.rs
src/sinks/kafka/sink.rs

Fixes: https://github.com/vectordotdev/vector/issues/18633, https://github.com/vectordotdev/vector/issues/11025
This PR includes a few improvements:
1. Requests are now built concurrently, which should improve the maximum throughput of the sink
2. The Tower Service is now capped at a concurrency of 64 instead of 100k.
The 100k concurrency limit resulted in memory explosion when Kafka applies backpressure to the producer. The sink has four places where events can buffer: (1) the actual sink buffer, (2) the request builder, (3) the Tower service, and (4) the rdkafka producer. In its previous state, the 100k concurrency limit for the Tower service meant that the minimum combined buffer was > 100k events. Now, we limit the concurrency of (2) and (3) to 64 each while the user can configure (1) …

fix(kafka sink): performance improvements and fix memory leak

---

src/sources/journald.rs
website/cue/reference/components/sources/base/journald.cue

This PR adds a new configuration option to the `journald` source, enabling arbitrary command line arguments to be specified. An example would be `--merge`, closing issue #18430.

enhancement (journald source): Add `extra_journalctl_args` option to specify arbitrary command line arguments to journalctl

---

website/Makefile

This commit adds two new Makefile overrides for configuring the networking in the website Makefile:
* `SERVER_BIND`: Specify which network address to use in Hugo/HTTP servers for binding. The default value is `127.0.0.1` to preserve the current behavior.
* `SERVER_PORT`: Specify which port to use in Hugo/HTTP servers for listening. The default value is `1313` to preserve the current behavior.
Before this change, the Hugo/HTTP bind address and port was hard-coded to `127.0.0.1:1313`. This behavior is not always convenient. For example, when running Hugo inside of a Docker container. In this scenario, the Hugo/HTTP servers can be accessed form outside of the container as follows:
make serve SERVER_BIND=0.0.0.0
make run-production-site-locally SERVER_BIND=0.0.0.0
I also added a safety check …

feat(dev): add networking overrides to website Makefile

---

.github/actions/spelling/excludes.txt
lib/vector-vrl/web-playground/amplify.yml
rust-doc/amplify.yml
website/amplify.yml

Adds the amplify build spec files (`amplify.yml`) to the appropriate directories for each stand alone amplify app
- vector websites
- vector rust-doc
- vector vrl-playground

chore(websites): Add amplify build spec files to appropriate directories

---

Makefile

This commit adds two new Makefile overrides for configuring the networking of the environment:
* `ENVIRONMENT_NETWORK`: When non-empty, the value is passed to the container tool using `--network VALUE`. The default value is `host` to preserve the current behavior.
* `ENVIRONMENT_PUBLISH`: When non-empty, all space-separated values are passed to the container tool using `--publish VALUE` arguments. The default is empty to preserve the current behavior.
Before this change, the environment was hard-coded to always be started using `--network host`.
This behavior is not always convenient. For example, when using Docker Desktop for Windows, the `host` network is not supported and does not behave the same way as in Linux. In this scenario, publishing ports with the default `bridge` network can …

feat(dev): add environment networking overrides to Makefile

---

docs/REVIEWING.md
src/sinks/datadog/metrics/encoder.rs

This is a follow-up to https://github.com/vectordotdev/vector/pull/18405
In these changes we:
- use `Lazy` to create a static for the OriginProduct value to use
- set the OriginCategory and OriginProduct for edge cases where either the upstream Vector instance did not set the origin metadata, or where we forgot to update the source_type -> service mapping function when adding a new source.

chore(datadog_metrics sink): Set partial Origin Metrics in edge cases

---

.github/actions/spelling/expect.txt
scripts/environment/bootstrap-ubuntu-20.04.sh

The `nodejs` and `npm` packages installed from the stock Ubuntu Focal repository are outdated for the current website dependencies. This commit installs an updated Node.js (current LTS version) directly from the NodeSource repository instead.
The `yarn` package in the stock Ubuntu Focal repository is not the Yarn package manager. The package is actually an alias package for the unrelated `cmdtest` package (ref: <https://packages.ubuntu.com/focal/yarn>). This commit installs (enables) the correct `yarn` command using the same updated Node.js installation above.
Website development requires two tools not currently installed in the environment:
* Hugo (static site generator).
* htmltest (HTML checker for the website content).
This commit also installs these tools directly from their GitHub …

fix(dev): update environment for website development

---

.github/actions/spelling/allow.txt
.github/workflows/workload_checks.yml
workload-checks/README.md
workload-checks/typical/cases/http_text_to_http_json/README.md
workload-checks/typical/cases/http_text_to_http_json/experiment.yaml
workload-checks/typical/cases/http_text_to_http_json/lading/lading.yaml
workload-checks/typical/cases/http_text_to_http_json/vector/vector.toml
workload-checks/typical/machine.yaml

closes: #18555 
* Defines required "workflow checks" directories for Vector. You can find the existing Agent checks [here](https://github.com/DataDog/datadog-agent/tree/main/test/workload-checks).
* Adds a simple check based on the [http_text_to_http_json](https://github.com/vectordotdev/vector/tree/master/regression/cases/http_text_to_http_json) regression case.
* Adds Github workflow to run the Vector [nightly image](https://hub.docker.com/layers/timberio/vector/nightly-debian/images/sha256-961d0a9bb2fddb2e0de02620eb35f1528429369a55444d13dfb5b2cfd8f17705?context=explore).
Click here to see the [dashboard](https://app.datadoghq.com/dashboard/wj9-9ds-q49?refresh_mode=sliding&from_ts=1695061534460&to_ts=1695666334460&live=true).

feat(ci): Add Vector workload checks

---

src/config/loading/mod.rs

Otherwise it prints the warning about the default path change even if the user specified a path
themselves.

fix(config): Only try default paths if the path is not specified

---

Cargo.lock
Cargo.toml

Now that v0.33.0 has been released

chore(releasing): Bump Vector version to v0.34.0

---

src/convert_config.rs

These tests require `demo_logs`, `remap`, and `console` components.
Ideally we might update the component features check to run `cargo test` instead of just `cargo check` but I anticipate this would bloat the time significantly.
Fixes: #18697

fix(dev): Gate config conversion tests

---

website/cue/reference/remap/functions.cue
website/cue/reference/remap/functions/encode_key_value.cue
website/cue/reference/remap/functions/encode_logfmt.cue
website/cue/reference/remap/functions/log.cue
website/cue/reference/remap/functions/match_array.cue
website/cue/reference/remap/functions/match_datadog_query.cue
website/cue/reference/remap/functions/parse_url.cue
website/cue/reference/remap/functions/replace.cue
website/cue/reference/remap/functions/set_semantic_meaning.cue

This PR removes or replaces mentions of "Vector" in the function docs that are getting added to Datadog docs.
Related to [DOCS-6159](https://datadoghq.atlassian.net/browse/DOCS-6159).

chore(external docs): Remove or replace mentions of vector in functions doc

---

src/internal_events/docker_logs.rs
src/sources/docker_logs/mod.rs

Fixes https://github.com/vectordotdev/vector/issues/17747
We mistakenly began treating this as an error in https://github.com/vectordotdev/vector/pull/14449

fix(docker source): do not emit component error for out of order logs

---

.github/workflows/regression.yml

Due to not running automatically on PRs.
Example output: https://github.com/vectordotdev/vector/actions/runs/6355487977

chore(ci): Add a summary if the regression workflow is skipped

---

.github/workflows/spelling.yml

Reverts vectordotdev/vector#18723.
See https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22

chore(ci): Revet bump check-spelling/check-spelling from 0.0.21 to 0.0.22

---

website/assets/js/app.js
website/assets/js/cookie-banner.js
website/config.toml
website/layouts/partials/meta.html

- Adds TrustArc cookie consent banner dependencies and display script to the Vector website
- Adds Cookies link to footer to target with preferences behavior
https://datadoghq.atlassian.net/browse/WEB-3476

[WEB-3464] Adds TrustArc cookie consent banner

---

.github/actions/spelling/excludes.txt
.github/actions/spelling/expect.txt
website/assets/js/cookie-banner.js

chore(ci): Fix cookie banner style issues

---

website/Makefile
website/layouts/download/section.html

Sets the version to `latest` when the Download page loads for the first time.
[Jira Request](https://datadoghq.atlassian.net/browse/WEB-4065)
Also adds a make command to allow a hot reload environment for local development
- Goto the website preview deployment
- Click `Download` in the nav
- Select a different version other than `latest`
- Navigate to the home page
- Go back to the download page and ensure that the version has reset to `latest`

chore(website): Set download page dropdown to latest version

---

docs/specs/component.md

Creating partially as a strawman to push this conversation forward.
In https://github.com/vectordotdev/vector/pull/8858#discussion_r695992243 we attempted to codify the option name to use for addresses on which Vector components listen on. We couldn't come to a consensus then, so the change was backed out. Here I reintroduce a proposal. I considered both `bind` and `listen` and decided in `listen` mostly due to the fact that it seems to match more with socket terminology where `bind` just allocates the address and `listen` actually starts passively listening for clients (and then `accept` accepts a new connection).
Some prior art from other tools to consider:
* FluentD: `bind` and `port`
* Nginx: `listen`
* Apache HTTPD: `listen`
* OpenTelemetry Collector: `endpoint` for both binding and …

chore(docs): Add spec for `listen` option

---

Cargo.lock
Cargo.toml
lib/vector-vrl/tests/Cargo.toml
src/enrichment_tables/geoip.rs
src/sources/datadog_agent/traces.rs

closes: #17377 
* We can now re-enable default features.
* Removed `test`, `test_framework` and `arbitrary` features from `Cargo.toml`. 
* Note that some of these features are still used by the VRL crate in `[dev-dependencies]`.

chore(deps): clean up VRL crate features

---

.github/workflows/changes.yml
.github/workflows/integration.yml
scripts/integration/datadog-metrics/test.yaml
scripts/integration/datadog-traces/test.yaml
src/sinks/datadog/metrics/integration_tests.rs

The integration tests for this sink were silently validating nothing ... The input events generated for the test cases were getting filtered out silently during the conversion from absolute to incremental counters. So the batch status was saying delivered, but we never were validating that any events were _actually_ received , so all the logic to check the correctness of the responses was never getting executed.
Note this also fixes the workflow logic to run the dd int tests based on files changes.

fix(datadog_metrics sink): the integration tests weren't actually validating anything

---

regression/cases/otlp_http_to_blackhole/experiment.yaml

In light of regression detector results in #18650, #18740, and #18759 that report repeated suspicious regressions in the `otlp_http_to_blackhole` experiment, this commit / PR marks that experiment "erratic" so that its results do not prevent Vector PRs from merging.

ci: mark otlp_http_to_blackhole experiment erratic

---

lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/proto.rs
src/sinks/datadog/metrics/encoder.rs
src/sources/datadog_agent/metrics.rs
src/transforms/log_to_metric.rs

This changes the way we create the `DatadogMetricOriginMetadata` structure, so the design more closely matches the expected behavior that metrics sent from the `datadog_metrics` sink which have the Origin metadata set within Vector, will contain all of the fields.
It was motivated by a comment in https://github.com/vectordotdev/vector/pull/18761 , to suggest not panicking if all the fields are not set (which this also changes).

chore(metrics): improve creation of Origin metadata structures

---

website/content/en/docs/setup/quickstart.md

chore(docs): update quickstart.md to use YAML

---

.github/workflows/changes.yml
.github/workflows/comment-trigger.yml
.github/workflows/deny.yml
.github/workflows/test.yml

With the goal of not blocking PRs due to a new security vulnerability being reported on `master`.
There is a risk that this allows PRs to introduce vulnerabilities that won't be flagged until after
merge but we see this risk as small and easily remedied after the fact. We will also run these
checks before releases, when it is most important to resolve any extant CVEs.

chore(ci): Run deny check nightly instead of on every PR

---

src/sources/http_server.rs
src/sources/util/http/query.rs

closes: #17056 
Used [this setup](https://github.com/vectordotdev/vector/issues/18558#issuecomment-1720833363) to reproduce and confirm the fix. Note this PR is targeted to this specific bug, we are still using `event.as_mut_log()` in other places.

fix(http_server source): panic when http server receives metric events

---

website/cue/reference/remap/functions/parse_nginx_log.cue

This was supposed to be complementary to the following change in VRL: https://github.com/vectordotdev/vrl/pull/498
However, it looks like there were no examples for this format in the documentation, so instead this change adds a "best case scenario" of using `parse_nginx_log(..., "ingress_upstreaminfo")`

docs(vrl): add an example of parsing upstreaminfo with parse_nginx_log

---

.github/workflows/unit_mac.yml

We've observed a spike in CI times for the Mac unit tests that seems to be due to the fact that protoc is installed from source now (which pulls in a lot of dependencies like cmake) due to the precompiled binaries for MacOS 11 being dropped in https://github.com/Homebrew/homebrew-core/commit/8f9e41364f0396ec6a3b06ae6a2e5130513c1798
This updates the workflow to use MacOS 13 runners, which do have precompiled protoc binaries. This brings the bootstrap step back down to a comparable amount of time as before (~4 minutes).

chore(ci): Bump MacOS unit test runners to 13

---

docs/DEPRECATIONS.md
src/cli.rs
src/config/cmd.rs
src/config/loading/mod.rs
src/tap/cmd.rs
src/top/cmd.rs
src/validate.rs
website/cue/reference/configuration.cue

chore!(config, docs): delete deprecated vector.toml code

---

.github/workflows/publish.yml
Makefile

In `0.33.0` we began publishing an `armv7hl` package and announced `0.34.0` would no longer include an `armv7` package.

chore: Remove armv7 RPM package

---

lib/vector-core/src/tls/incoming.rs
lib/vector-core/src/tls/settings.rs

as reported in the issue https://github.com/vectordotdev/vector/issues/18842 for incoming connect alpn protocol negotiation do not happen.
as documented in https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_alpn_select_cb.html server should use SSL_CTX_set_alpn_select_cb() ([set_alpn_select_callback](https://docs.rs/openssl/latest/openssl/ssl/struct.SslContextBuilder.html#method.set_alpn_select_callback)) for selecting protocol while client should use SSL_CTX_set_alpn_protos() 
in this PR, allow setting alpn based on wether context is for client or server and use for_server flag in incoming connections.
after fix same curl returns below
```
curl -k -vv  -X POST https://localhost:443 -d "hello"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying …
```

fix(tls): for incoming connection alpn negotiation should be done using set_alpn_select_callback

---

src/source_sender/mod.rs
src/sources/mongodb_metrics/mod.rs
src/sources/nginx_metrics/mod.rs
src/sources/postgresql_metrics.rs
src/topology/test/mod.rs

Fixes https://github.com/vectordotdev/vector/issues/18644
This change emits `ComponentEventsDropped` events when a `SourceSender` send future is not polled to completion. This has been observed to occur in production for sources that use a Warp server.

fix(sources): emit `ComponentEventsDropped` when source send is cancelled

---

.github/CODEOWNERS
lib/dnsmsg-parser/src/dns_message_parser.rs

Fixes: https://github.com/vectordotdev/vector/issues/18854
In Vector v0.33.0, we upgraded the trust-dns-proto crate, which is used in the parsing of the dns messages for the dnstap source.
That dependency crate upgrade from v0.22.0 to v0.23.0 , introduced a change wherein the enum DNSSECRData was expanded with a new variant, RRSIG.
In the parser logic for that enum, that rdata type was previously considered "Unknown" by the trust-dns-proto , and in Vector we considered that Ok. But now it falls into the catch-all case in Vector, because we don't have a specific handling for the RSIG rdata type, which results in a `WARN` log to the user because we failed to parse the incoming data into an event.
So this is a case of an upstream dependency upgrade silently (our existing tests didn't cover …

fix(dnstap source): support DNSSEC RRSIG record data

---

src/internal_events/amqp.rs
src/sinks/amqp/service.rs
src/sinks/amqp/sink.rs

Fixes: https://github.com/vectordotdev/vector/issues/18921

fix(amqp sink): remove unnecessary unwrap & emit event dropped errors

---

.github/workflows/gardener_issue_comment.yml

Currently one annoyance is that when an issue is in Triage column and a team member posts a comment and moves that issue to Blocked/Waiting at the same time, the workflow triggers and moves that back to the Triage column 😭  so this change disables the movement for team members.

chore(ci): filter team members from gardener issue comment workflow

---

src/kafka.rs
src/sinks/kafka/service.rs
src/sinks/kafka/sink.rs

Fixes https://github.com/vectordotdev/vector/issues/18762
It isn't correct to set a concurrency limit on the service because the Kafka client does not return until the record is sent downstream and an acknowledgement is received. Rather, we remove the concurrency limit and use the underlying `FutureProducer` to determine whether or not the service is at capacity.

fix(kafka sink): Make KafkaService return `Poll::Pending` when producer queue is full

---

src/app.rs
src/components/validation/runner/mod.rs
src/config/mod.rs
src/config/unit_test/mod.rs
src/sinks/datadog/traces/apm_stats/integration_tests.rs
src/test_util/mod.rs
src/topology/builder.rs
src/topology/mod.rs
src/topology/running.rs
src/topology/test/crash.rs
src/topology/test/end_to_end.rs
src/topology/test/mod.rs
src/topology/test/reload.rs
src/validate.rs

This is a generalization of the work in #18888 which sets up a more generalized where one or more configs can be loaded as "internal" topologies. For simplicity, these internal configs are not connected to a controller and as such are not watched for changes nor participate in reloading. They are shut down after all the other components.
The last commit sets up a trivial internal topology in the standard runs to demonstrate the interface. It will be reverted before merging this PR.
This PR also contains a bunch of refactoring. The second-to-last commit contains the actual API, which is also [entirely localized to `app.rs`](https://github.com/vectordotdev/vector/pull/18919/files#diff-0b979b6de560b29c1d97336878db56179224aa21d96fe099630c6628479ed020).

chore(core): Set up internal topology API

---

src/sources/nats.rs
website/cue/reference/components/sources/base/nats.cue

This is a useful option to have to tune memory usage. Inspiration came from reading https://github.com/vectordotdev/vector/issues/12834. I believe the upstream issue still hasn't been resolved for that specific issue though.

enhancement(nats source): add subscriber_capacity option

---

lib/vector-buffers/src/variants/disk_v2/io.rs

This PR adds logic that constrains the file permissions for disk buffer data files, as well as the ledger, to only be readable/writable by the file owner: the user that the Vector process is running as.
Currently, the default permissions will typically to the files being readable by the group owner and world/other. There is no reason for outside processes to be able to read the disk buffer files. With the addition of secrets metadata to events stored in disk buffers, we want to ensure that the data files are as narrowly scoped to Vector as possible.
This has no affect on Windows systems, where setting file ACLs is more complex and does not have anywhere near as easy of a solution in code as doing so for Unix-based systems. This will likely be addressed in a future PR.
Fixes #18853.

fix(buffers): apply stricter file permissions to buffer data files when possible

---

src/sinks/blackhole/config.rs
website/content/en/highlights/2023-11-07-0-34-0-upgrade-guide.md
website/cue/reference/components/sinks/base/blackhole.cue

Users have been suprised by the `blackhole` sink emitting events processed logs at the `info` level
by default. This change changes the default to not report.

chore(observability, blackhole sink)!: Don't report by default

---

src/internal_events/tcp.rs
src/sources/socket/mod.rs
src/sources/statsd/mod.rs
src/sources/syslog.rs
src/test_util/components.rs
website/content/en/highlights/2023-11-07-0-34-0-upgrade-guide.md

I vote that we do this now, rather than following the formal deprecation process, due to the tag's cardinality explosion in real world scenarios. This does not introduce any breaking changes into Vector itself but rather has the possibility to break some metric queries that use the `peer_addr` tag.

chore(observability)!: remove `peer_addr` internal metric tag

---

license-tool.toml

Accidentally broke in https://github.com/vectordotdev/vector/commit/409b69dd6eb6316e388dfddb445b7271bc7cb841

chore(deps): Update license-tool.toml webpki version

---

website/content/en/docs/setup/installation/manual/vector-installer.md
website/content/en/docs/setup/quickstart.md
website/content/en/guides/getting-started/getting-started.md
website/content/en/highlights/2020-07-09-add-musl-and-glibc-support-to-install-sh.md
website/cue/reference/administration/example_docker_install_commands.cue
website/cue/reference/administration/install_commands.cue
website/cue/reference/administration/interfaces/vector_installer.cue

New hosting uses an HTTP redirect rather than passing the content back transparently.

chore: Follow redirects for `sh.vector.dev`

---

Cargo.lock
Cargo.toml
src/cli.rs
src/test_util/mod.rs
vdev/Cargo.toml
vdev/src/util.rs

Turns out this is in the stdlib now.
Replaces: #18966

chore(deps): Remove usages of atty

---

src/sources/journald.rs
website/cue/reference/components/sources/base/journald.cue

feat(journald source): Add emit_cursor option

---

docs/DEPRECATIONS.md

chore: Note the version to remove the v1 metrics support from the Datadog Metrics sink

---

regression/cases/file_to_blackhole/experiment.yaml
regression/cases/otlp_http_to_blackhole/experiment.yaml
regression/cases/syslog_regex_logs2metric_ddmetrics/experiment.yaml

Now that we seem to have stablized the tests, we can see if these show up as erratic again.

chore(regression): Unmark regression tests as erratic now

---

Cargo.lock
Cargo.toml
lib/codecs/Cargo.toml
lib/codecs/tests/data/native_encoding/vector_generate_fixtures.patch
lib/file-source/Cargo.toml
lib/prometheus-parser/Cargo.toml
lib/vector-common/Cargo.toml
lib/vector-config/Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-vrl/tests/Cargo.toml
website/cue/reference/remap.cue
website/cue/reference/remap/functions/contains_all.cue
website/cue/reference/remap/functions/from_unix_timestamp.cue
website/cue/reference/remap/functions/parse_float.cue

chore(deps): Update VRL to 0.8.1

---

.github/workflows/build_preview_sites.yml
.github/workflows/create_preview_sites.yml
.github/workflows/preview_site_trigger.yml
website/amplify.yml

- Updates the new preview site workflows to be able to have the correct access for secrets
- Addressed previous feedback
- Updates the sanitized branch to not replace `/`
- Updates github-scripts to the latest version and adds `.rest` to the github function calls
- Updates the website build file to account for release versions being "production" runs

chore(websites): Workflow updates

---

.github/actions/spelling/allow.txt
Cargo.lock
Cargo.toml
src/sinks/webhdfs/integration_tests.rs

This PR will bump opendal to v0.41, close https://github.com/vectordotdev/vector/pull/18989

chore(deps): Bump OpenDAL to v0.41

---

.github/workflows/build_preview_sites.yml
.github/workflows/create_preview_sites.yml

- Fixes the syntax for the secrets being passed into the job
- Sets the correct environment vars for the steps
- ensures fs is available in the comment step
- fixes a variable name in the comment step

chore(website): Workflow fixes

---

.github/workflows/build_preview_sites.yml
.github/workflows/create_preview_sites.yml

Workflow call has access to this specific secret for the token, and passing it causes the workflow to trip a check since it's a reserved variable name. Removing it from both the reusable workflow and caller.

fix: remove gh token call

---

website/content/en/highlights/2023-10-30-secrets-in-disk-buffers.md

With #18816, we've introduced a decently large change in behavior for what is stored in disk buffers, in terms of confidentiality. This PR adds a full highlight note (for the 0.34.0 release) about the overall change to include secrets in disk buffers, that the secrets are unencrypted, when events even have secrets, how best to secure disk buffer data _today_, and about likely future work to allow encrypting secrets in disk buffers.

chore(docs): add highlight post for secrets in disk buffers

---

website/cue/reference/remap/functions/truncate.cue

The truncate arguments say that "suffix" is a boolean, but it's a string.  They also say that "ellipsis" and "suffix" are required, but they're not.

docs: fix truncate arguments

---

src/convert_config.rs

when compiling `vector` with `rust` version `1.73.0` there is a warning - this PR fixes the warning
thanks to @StephenWakely for their assistance in https://github.com/vectordotdev/vector/issues/18870#issuecomment-1798553232

fix(config): rustc warnings

---

distribution/install.sh
website/content/en/highlights/2023-11-07-0-34-0-upgrade-guide.md
website/content/en/releases/0.34.0.md
website/cue/reference/administration/interfaces/kubectl.cue
website/cue/reference/releases/0.33.0.cue
website/cue/reference/releases/0.34.0.cue
website/cue/reference/versions.cue

Checklist: https://github.com/vectordotdev/vector/issues/19013
Milestone: https://github.com/vectordotdev/vector/milestone/117

chore(releasing): Prepare v0.34.0 release

---

website/content/en/highlights/2023-11-07-0-34-0-upgrade-guide.md
website/cue/reference/releases/0.34.0.cue

As part of the cutover plan described by the release highlight.

chore(releasing): Add deprecation note about respositories.timber.io deprecation

---

Cargo.lock
Cargo.toml

chore(dev): Bump Vector to v0.35.0

---

website/content/en/docs/setup/installation/package-managers/apt.md
website/content/en/docs/setup/installation/package-managers/yum.md
website/content/en/highlights/2023-11-07-new-linux-repos.md

We need to setup this redirect again with the new site hosting. Until we do that, putting a direct
link to the script.

chore(docs): Replace setup.vector.dev references

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
lib/dnsmsg-parser/Cargo.toml
lib/dnsmsg-parser/benches/benches.rs
lib/dnsmsg-parser/src/dns_message.rs
lib/dnsmsg-parser/src/dns_message_parser.rs
src/sources/dnstap/parser.rs

This crate was rehomed for the 0.24 release: https://www.memorysafety.org/blog/announcing-hickory-dns/

chore(deps): Replace trust_dns_proto with hickory_proto

---

src/sinks/loki/config.rs
src/sinks/loki/service.rs
src/sinks/loki/sink.rs
website/cue/reference/components/sinks/base/loki.cue

The Loki sink had some special code to handle snappy. snappy was https://github.com/vectordotdev/vector/pull/18676 to the global list of compression schemes. This meant Loki was specifying snappy twice. It looks like this broke the schema validation.
This PR removes the special config option for snappy, but hopefully still handles the choice of snappy differently (encodes it as protobuf), as it did before.

fix(loki sink): update to use the global list of compression algorithms

---

docs/DEPRECATIONS.md
docs/specs/component.md
src/internal_events/file.rs
src/sinks/file/mod.rs
src/sources/file.rs
src/sources/kubernetes_logs/mod.rs
website/content/en/highlights/2023-12-19-0-35-0-upgrade-guide.md
website/cue/reference/components/sinks/base/file.cue
website/cue/reference/components/sources/base/file.cue
website/cue/reference/components/sources/base/kubernetes_logs.cue

I would ideally like to remove this altogether or move towards the `file_tag_pattern` config option that @hhromic suggested [here](https://github.com/vectordotdev/vector/issues/11821#issuecomment-1185354328), but this is a good first step. I understand that it does provide value to users so it's unlikely we remove it altogether.
https://github.com/vectordotdev/vector/issues/15426
https://github.com/vectordotdev/vector/issues/11821

fix(file source, kubernetes_logs source, file sink): make `file` internal metric tag opt-out

---

CONTRIBUTING.md

I couldn't see this mentioned anywhere else. This adds a list of checks that should be run before submitting a PR to the `CONTRIBUTING.md` docs.

chore: List checks to be run prior to submitting a PR in `CONTRIBUTING.md`

---

website/content/en/highlights/2023-11-07-0-34-0-upgrade-guide.md

Closes: https://github.com/vectordotdev/vector/issues/19096

chore(releasing): Add upgrade note about TOML breaking change to v0.34.0

---

.github/workflows/create_preview_sites.yml

- Extracts the environment variables in the github script so they can be passed into the PR commenter
- Adds a sleep to the curl to allow the branch connection to happen with AWS, the job sometimes runs before aws knows about the branch 
- Reverts the sanitized branch name to remove both`/` and `.` and replace them with `-` for the urls
- Uses the standard branch name in the curl request

chore(website): Fix commenting step on workflow

---

website/cue/reference/releases/0.34.0.cue

Ref: https://github.com/vectordotdev/vector/issues/19110

chore(releasing): Add known issue for Datadog Metrics sink in v0.34.0

---

src/sources/datadog_agent/mod.rs
src/sources/kafka.rs
src/transforms/aggregate.rs
website/cue/reference/components/sources/base/datadog_agent.cue
website/cue/reference/components/sources/base/kafka.cue
website/cue/reference/components/transforms/base/aggregate.cue

This PR add `alpha` to mentions of traces and `beta` to mention of metrics in reference docs descriptions.
Related to [DOCS-6576](https://datadoghq.atlassian.net/browse/DOCS-6576).
Replaces this PR: https://github.com/vectordotdev/vector/pull/19031
[DOCS-6576]: https://datadoghq.atlassian.net/browse/DOCS-6576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(docs): Add alpha to traces and beta to metrics in descriptions

---

docs/DEPRECATIONS.md
src/internal_events/file.rs
src/sinks/file/mod.rs
src/sources/file.rs
website/content/en/highlights/2023-12-19-0-35-0-upgrade-guide.md
website/cue/reference/components/sinks/base/file.cue
website/cue/reference/components/sources/base/file.cue
website/cue/reference/components/sources/base/kubernetes_logs.cue

Similar to https://github.com/vectordotdev/vector/pull/19083, we have decided to make this opt-in immediately due to the impact it is having on users and downstream systems.

fix(file source, kubernetes_logs source, file sink): make file internal metric tag opt-in

---

website/content/en/docs/setup/installation/package-managers/apt.md
website/content/en/docs/setup/installation/package-managers/yum.md
website/content/en/highlights/2023-11-07-new-linux-repos.md

Updates the 3 files to reference https://setup.vector.dev instead of the direct s3 link now that the subdoomain is setup again

chore(website): WEB-4247 | Update references from s3 to setup.vector.dev

---

src/http.rs
src/sources/aws_kinesis_firehose/mod.rs
src/sources/datadog_agent/mod.rs
src/sources/datadog_agent/tests.rs
src/sources/heroku_logs.rs
src/sources/http_server.rs
src/sources/opentelemetry/http.rs
src/sources/opentelemetry/integration_tests.rs
src/sources/opentelemetry/mod.rs
src/sources/opentelemetry/tests.rs
src/sources/prometheus/remote_write.rs
src/sources/splunk_hec/mod.rs
src/sources/util/http/prelude.rs
website/content/en/highlights/2023-12-19-0-35-0-upgrade-guide.md
website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
website/cue/reference/components/sources/base/datadog_agent.cue
website/cue/reference/components/sources/base/heroku_logs.cue
website/cue/reference/components/sources/base/http.cue
website/cue/reference/components/sources/base/http_server.cue
website/cue/reference/components/sources/base/opentelemetry.cue
website/cue/reference/components/sources/base/prometheus_remote_write.cue
website/cue/reference/components/sources/base/splunk_hec.cue

Clients often use indefinitely persistent connections. Given that we recommend network-level load balancers, this can result in sub-par balancing as the worker pool grows due to a lack of rebalancing.
To resolve this, sources with a HTTP server now support a configurable option to send a `Connection: close` header and close the connection after a certain time interval. 
The default max age is 5 minutes.

ehancement(sources): Add `keepalive.max_connection_age_secs` config option to HTTP-server sources

---

src/config/mod.rs
src/config/unit_test/mod.rs
tests/behavior/transforms/vrl_test_input.toml
website/content/en/docs/reference/configuration/unit-tests.md

Add VRL as a valid input for unittests, this makes it possible to define test inputs as such:
```
[[tests.inputs]]
type = "vrl"
insert_at = "my_transform"
source = '''
. = {
"message": "foo bar baz",
"timestamp": now(),
"tags": {
"foo": "bar",
"fizz": "buzz"
}
}
'''
```
And it kinda works:
```
output payloads from ["my_transform"] (events encoded as JSON):
{"message":"foo bar baz","tags":{"fizz":"buzz","foo":"bar"},"timestamp":"2023-11-09T20:17:08.072518248Z"}
```
Since i basically just hacked around a bit; is this something that is useful and worthy of refining?
Inspired by #12490 and #15304
Closes: https://github.com/vectordotdev/vector/issues/15304

feat(unittests): add vrl as test input

---

lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/README.md
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/README.md
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service_http.yaml
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service.proto
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service_http.yaml
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service.proto
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/trace/v1/trace_service_http.yaml
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/common/v1/common.proto
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/logs/v1/logs.proto
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.proto
lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.proto
src/sources/opentelemetry/grpc.rs
src/sources/opentelemetry/http.rs

This will also make sure that all the necessary files exist for the rest of the signals.
Relates #1444
Signed-off-by: Harold Dost <h.dost@criteo.com>
Not expected to be a breaking change to https://github.com/open-telemetry/opentelemetry-proto/pull/414

chore: Update OpenTelemetry Protobuf Definitions to v1.0.0

---

scripts/integration/aws/test.yaml
src/sinks/aws_kinesis/streams/integration_tests.rs

Fixes: #16376
The integration test was disabled because it was failing on master when it was first introduced. Just needed a couple modifications.

chore(aws_kinesis_streams sink): re-enable int test for partition_key

---

website/content/en/docs/about/under-the-hood/architecture/data-model/log.md

This is not a current priority and so I don't think mentioning it in the docs is useful.

chore(docs): Remove stale docs content around schemas

---

.github/ISSUE_TEMPLATE/minor-release.md

This is now deployed via Amplify. We plan to try to automate this step in the future.

chore(releasing): Update minor release template step for updating vector.dev

---

.github/workflows/regression.yml
.github/workflows/workload_checks.yml

chore(deps): Update lading to 0.20.0

---

lib/codecs/src/encoding/format/csv.rs

```
cargo vdev test  encoding::format::csv::tests
Summary [   0.138s] 9 tests run: 9 passed, 2007 skipped
```
However:
```
cargo test --lib encoding::format::csv::tests --manifest-path ..../vector/lib/codecs/Cargo.toml
error[E0277]: the trait bound `vector_lookup::lookup_v2::ConfigTargetPath: From<&str>` is not satisfied
--> lib/codecs/src/encoding/format/csv.rs:321:52
|
321 |             let field = ConfigTargetPath::try_from(field_name.clone()).unwrap();
|                         -------------------------- ^^^^^^^^^^^^^^^^^^ the trait `From<&str>` is not implemented for `vector_lookup::lookup_v2::ConfigTargetPath`
|                         |
|                         required by a bound introduced by this call
```

fix(codecs): cargo test compilation error

---

scripts/integration/pulsar/test.yaml

The latest image has an issue (https://github.com/apache/pulsar/issues/21655) which is blocking the merge queue. Rolling back to the latest stable image.

fix(ci): peg pulsar docker image for int tests to stable image

---

.github/workflows/k8s_e2e.yml
.github/workflows/regression.yml

We saw empirically that if the `github.sha` event context is used on workflows that are dispatched via comment trigger AND pull_request trigger, results in any commit to the PR during in flight comment trigger executions , canceling the in progress run undesirably.
This removes that commit sha from the concurrency group settings. For regression workflow it's a "pure" fix because we don't do code changes detection on the PR commit event, but for k8s workflow there is a compromise that must be made. I selected the conservative approach which means we might have some runs that could be cancelled but aren't, as opposed to potentially having runs cancelled that we don't want.

fix(ci): Use correct concurrency group settings for comment trigger & PR commit workflows

---

scripts/environment/prepare.sh

chore(deps): Bump cargo-deb to 2.0.2

---

scripts/integration/pulsar/test.yaml

This reverts commit c2c2dbd7f86112ce8a0aa6a92ee92ee7e3a023e4.
Appears to have been fixed upstream by https://github.com/apache/pulsar/issues/21655#issuecomment-1837676414

chore(ci): revert peg pulsar docker image for int tests to stable image

---

Cargo.toml

I'm fairly certain this was committed by accident to `default` and then copied into `default-docs` when that was created.
The `component-validation-runner` is used for running a set of tests so we shouldn't be compiling that by default.

chore(dev): remove component-validation-runner feature from defaults

---

lib/codecs/src/encoding/format/protobuf.rs

closes: https://github.com/vectordotdev/vector/issues/19230

fix(codecs): fix 'ProtobufSerializerConfig' input type

---

src/components/validation/mod.rs
src/sinks/datadog/mod.rs
src/sinks/datadog/test_utils.rs

The regression was introduced [here](https://github.com/vectordotdev/vector/commit/b297070f9ab5f90d6fdb7ffe36d7d59a86cf6f1d#diff-3cf117ccbd31eed50dba7e907112a464ddc8e9941ce649135d855b749828c171R165).

fix: component validation runner and 'sinks::datadog::test_utils' feature gates

---

.github/workflows/labeler.yml

Reverts vectordotdev/vector#19300
Failure needs to be investigated: https://github.com/vectordotdev/vector/actions/runs/7144526651/job/19458318833?pr=19342

Revert "chore(ci): Bump actions/labeler from 4 to 5"

---

Cargo.toml

This change enables the use of jemalloc in all non-rust (C/C++) code used in vector, since it forces the `*malloc()` functions to point to jemalloc versions instead of libc. [read about `unprefixed_malloc_on_supported_platforms` feature](https://github.com/tikv/jemallocator/blob/master/jemalloc-sys/README.md#cargo-features)
Jemalloc releases memory back to the OS much more efficiently, which is also good for C/C++ code.
This results in significantly lower memory consumption when using Kafka sinks and sources, possibly because `librdkafka` uses a lot of internal buffering.
Our experience with vector-aggregator with kafka multiple sinks and sources:
Memory consumption without patch
Memory consumption with patch

enhancement(performance): Enable jemallocator for all non rust-code

---

Cargo.toml

datadog-signing-keys is an APT package to ease the management of signing keys for datadog-related packages. Adding it as soft dependency could simplify the key update for next rotation (2026)
I assume the `recommends` will work like the `depends`

enhancement(packaging):Add soft dependency on datadog-signing-keys

---

src/transforms/remap.rs

Error example:
```
2023-12-12T11:01:03.808753Z ERROR vector::topology::builder: Configuration error. error=Transform "my_transform_id": File contents were redacted.
error[E203]: syntax error
┌─ :11:7
│
11 │                                                           
│       ^
│       │
│       unexpected syntax token: "Colon"
│       expected one of: "\n", "!=", "&&", " ", "+", ",", "-", "/", ";", "<", "<=", "=", "==", ">", ">=", "??", "|", "|", "|=", "||"
│
= see language documentation at https://vrl.dev
= try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

fix(remap): filter out file contents from error logs

---

src/app.rs

When Vector sets a log level, either by the default `info` level or by adding `-v` or `-q` command-line options, it applies that log level to the following targets: `vector`, `codec`, `vrl`, `file_source`, `tower_limit`, `rdkafka`, `buffers`, `lapin`, and `kube`. These targets were set up to limit one or more of the _unlisted_ targets to reduce very chatty debug logs. By contrast, if the user specifies the environment variable setting `LOG_LEVEL=debug`, none of those targets are used.  This change drops all those hard-coded targets and sets all targets to the same level. If we discover there is still an issue with a chatty target, we can add an override for just that target instead of this list.

chore(observability): Simplify the default log targets selection

---

Cargo.toml

[APL-2390] Adds `datadog-signing-keys` as a recommended package for the Vector deb package, to support validating individual packages are signed.
[APL-2390]: https://datadoghq.atlassian.net/browse/APL-2390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(apt platform): Add datadog-signing-keys package as recommended

---

.github/workflows/publish.yml
vdev/src/commands/build/publish_metadata.rs

As part of migration of package hosting: https://vector.dev/highlights/2023-11-07-new-linux-repos/

chore(ci): Remove Cloudsmith package publishing

---

.github/workflows/cross.yml
.github/workflows/k8s_e2e.yml
.github/workflows/preview_site_trigger.yml
.github/workflows/publish.yml
.github/workflows/regression.yml
.github/workflows/workload_checks.yml

Reverts vectordotdev/vector#19391
[Nightly fails](https://github.com/vectordotdev/vector/actions/runs/7243425720/job/19731195831) because actions/download-artifact@v4 requires node v20 (https://github.com/actions/download-artifact/pull/233).

chore(ci): Revert bump the artifact group with 2 updates

---

.github/workflows/install-sh.yml

Missed one when updating them in 9893b86. `sh.vector.dev` is now has a HTTP redirect with the move
to Amplify for hosting (from Netlify).
It is causing a failure here: https://github.com/vectordotdev/vector/actions/runs/7265676030/job/19796083515

chore(ci): Fix test of install script

---

distribution/install.sh
website/content/en/docs/setup/installation/manual/vector-installer.md

Currently, the VECTOR_VERSION is hardcoded in the script, which restricts users from downloading specific versions of Vector. This pull request aims to allow downloading specific versions of Vector.
Closes https://github.com/vectordotdev/vector/issues/5033

enhancement(install vector): Allow downloading specific versions of Vector

---

.github/actions/spelling/excludes.txt

Suppresses some warnings we are currently seeing in CI like:
> Skipping `lib/codecs/tests/data/avro/generated/boolean.avro` because appears to be a binary file ('application/octet-stream'). (binary-file)

chore(ci): Configure spellchecker to ignore avro files

---

website/content/en/docs/setup/installation/platforms/docker.md

The example configuration creates a TOML file:
cat <<-EOF > $PWD/vector.toml
[snip]
but the start command example referred to a YAML.
Now they match!

docs: fix mismatch in config vs config file name

---

website/cue/reference.cue

The link has had a backslash as separator, effectively disabling the link itself, but actually like in the other examples, a forward slash was necessary.
Status quo on [the Website](https://vector.dev/docs/reference/configuration/global-options/#enrichment_tables.file.schema):
Will be fixed after being merged.

chore(docs): Fix link to RFC 3339

---

.github/workflows/changelog.yaml

This workflow is currently failing external contributor PRs, who don't have the secrets needed in the job step.

chore(ci): fix changelog workflow extern contribs

---

src/sinks/datadog/metrics/service.rs
src/sinks/datadog/mod.rs

This doesn't actually change the retry behavior but cleans up the logic to make it clearer what status codes are retried, improves the error messaging, and deletes a dead code path.
https://datadoghq.atlassian.net/browse/OPW-245

ehancement(datadog_metrics sink, datadog_logs sink): improve retry behavior code quality

---

.github/workflows/changelog.yaml

Dependabot does not have access to the secrets.
https://docs.github.com/en/github-ae@latest/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events

chore(ci): exclude dependabot from changelog job steps

---

.github/workflows/changelog.yaml

Noticed in an external contributor PR that this check was not working correctly due to a typo.

chore(ci): Fix the check for external contributor author GH usernames

---

src/aws/mod.rs
src/sinks/aws_cloudwatch_logs/retry.rs

ref https://github.com/vectordotdev/vector/pull/19312
There was a failure in the feature tests for the PR because
[aws_sdk_cloudwatch::config::RuntimeComponents](https://github.com/vectordotdev/vector/blob/c2cc94a262ecf39798009d29751d59cc97baa0c5/src/aws/mod.rs#L253) was being used as a parameter. This crate is only pulled in for the cloudwatch features.
This updates it to use use `aws_smithy_runtime_api::client::runtime_components::RuntimeComponents` instead. The `aws_smithy_runtime_api` crate is used by all AWS components.

chore: Fix aws feature error

---

src/sinks/prometheus/remote_write/mod.rs

A recent PR #10304 caused an error in the features CI check. This fixes that error.
Note the features job still fails due to errors that are fixed in #19567.

chore: only export RemoteWriteConfig for remote-write feature

---

.github/workflows/k8s_e2e.yml
.github/workflows/regression.yml

Currently they don't include any differentiating information about the PR that triggered the check
so it ends up grouping them into groups like:
```
Regression Detection Suite-
```
So that PRs will cancel each other.

chore(ci): Ensure PR runs of regression and k8s e2e tests don't cancel each other

---

.github/dependabot.yml
Cargo.lock
Cargo.toml

chore(deps): Bump graphql crates to 7.0.0

---

lib/vector-core/src/config/proxy.rs

When the `ProxyConfig` struct is serialized to TOML or YAML but either of the `http` or `https` fields are at their default `None` values, they will be emitted as "Null" values that cannot be re-serialized again. This skip serializing those fields in that case.

chore(config): Skip serializing default proxy config fields

---

changelog.d/gelf_at_character.enhancement.md
lib/codecs/src/decoding/format/gelf.rs
lib/codecs/src/gelf.rs
lib/codecs/src/lib.rs

Graylog itself emits labels containing @ characters on its "Output" feature (relaying GELF to another GELF receiver).
Observed examples are `_@timestamp` and `_@version`.
With this change, vector `socket` source with the `gelf` codec accepts all log events from Graylog Output.

enhancement(codec): Allow @ as valid GELF field character in decoder

---

Cargo.lock
Cargo.toml

chore(releasing): Bump Vector to v0.36.0

---

src/sinks/util/retries.rs

docs(sinks): improve documentation of `RetryLogic` trait functions

---

.github/workflows/gardener_issue_comment.yml

Noticed this filter seems to not be working.
Example: https://github.com/vectordotdev/vector/actions/runs/7508592931/job/20444305046

chore(ci): fix filter out PRs for gardener issue comment workflow

---

.github/workflows/k8s_e2e.yml
.github/workflows/master_merge_queue.yml
.github/workflows/protobuf.yml
.github/workflows/regression.yml
.github/workflows/test.yml

`github.ref` applies to both MQ and PR runs.

chore(ci): fix and simplify concurrency groups

---

config/examples/environment_variables.yaml
config/examples/es_s3_hybrid.yaml
config/examples/namespacing/sources/apache_logs.yaml
config/examples/wrapped_json.yaml
website/content/en/docs/reference/configuration/_index.md

As per file source docs, it only accepts a `ignore_older_secs`, not `ignore_older`, which is an undocumented alias. I think it's better to use only documented options in the examples.
Ref: https://vector.dev/docs/reference/configuration/sources/file/#ignore_older_secs

docs: Fix docs for `ignore_older_secs`

---

src/app.rs
src/internal_events/api.rs
src/topology/controller.rs

Following up on https://github.com/vectordotdev/vector/pull/19645, this PR emits the new graphql field on app startup and reload

fix(config api): emit graphql field of api config

---

Cargo.lock
vdev/Cargo.toml
vdev/src/platform.rs
vdev/src/testing/state.rs

The uses of this crate are pretty trivial and not worth pulling an extra dependency.
Replaces #19689

chore(vdev): Drop dependency on `cached` crate

---

src/aws/region.rs

This change removes the conditional compilation attribute `#[cfg(test)]` from the `RegionOrEndpoint` methods
Unfortunately, although the invocation is wrapped in a tokio::test, the reference to `with_region` is still not found.
I have removed the attribute from method `with_both` for consistency

fix(aws region): remove cfg test attribute

---

docs/DOCUMENTING.md
docs/README.md

- Fix `CONTRIBUTING.md` path, it's located in the parent directory of `docs`
- Suggest command `make generate-component-docs`. The command `cargo vdev build component-docs` fails with the following error:
```
usage: extract-component-schema.rb <configuration schema path>
Error: command: cd "/home/gabriel/temp/vector" && "/home/gabriel/temp/vector/scripts/generate-component-docs.rb"
failed with exit code: 1
```

chore(docs): suggest make generate-component-docs

---

lib/vector-config/src/external/http.rs
lib/vector-config/src/external/mod.rs

Copied from the support for `url::Url`.

chore(config): Add configurable support for `http::Uri`

---

.github/dependabot.yml

Motivated by adding `no-changelog` to all of them, I realized the domain for the `docker` updates
could be improved.

chore(ci): Update labels used by dependabot

---

src/config/sink.rs
src/config/source.rs
src/config/transform.rs
src/sources/socket/mod.rs
src/topology/builder.rs

This unifies the context available to all components, closing the gap.

chore(config): Pass the extra context to sources and transforms too

---

changelog.d/19643_only_set_connection_close_http1.fix.md
src/http.rs
website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
website/cue/reference/components/sources/base/datadog_agent.cue
website/cue/reference/components/sources/base/heroku_logs.cue
website/cue/reference/components/sources/base/http.cue
website/cue/reference/components/sources/base/http_server.cue
website/cue/reference/components/sources/base/opentelemetry.cue
website/cue/reference/components/sources/base/prometheus_pushgateway.cue
website/cue/reference/components/sources/base/prometheus_remote_write.cue
website/cue/reference/components/sources/base/splunk_hec.cue

Previously this header was sent when `max_connection_age` expired for all HTTP requests
regardless of HTTP version, but this header is not applicable to HTTP/2 and HTTP/3 requests. Instead
only send this header for other HTTP versions.
HTTP/2 and HTTP/3 support GOAWAY frames for this but I think this may need to be implemented at
a different level.
Fixes: #19643

fix(http_server source): Conditionally send Connection: Close header based on HTTP version

---

src/http.rs
website/content/en/highlights/2023-12-19-0-35-0-upgrade-guide.md
website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
website/cue/reference/components/sources/base/datadog_agent.cue
website/cue/reference/components/sources/base/heroku_logs.cue
website/cue/reference/components/sources/base/http.cue
website/cue/reference/components/sources/base/http_server.cue
website/cue/reference/components/sources/base/opentelemetry.cue
website/cue/reference/components/sources/base/prometheus_pushgateway.cue
website/cue/reference/components/sources/base/prometheus_remote_write.cue
website/cue/reference/components/sources/base/splunk_hec.cue

Ideally you could set this to `null`, but Vector requires all config values to be valid TOML, of
which `null` is not.
Closes: https://github.com/vectordotdev/vector/issues/19644

fix(docs, http_server source): Update docs for disabling `max_connection_age_secs`

---

src/transforms/mod.rs

This was overlooked in https://github.com/vectordotdev/vector/pull/19806

chore(sample transform): make containing module pub

---

Cargo.toml
src/test_util/mod.rs

This enables users to write tests using `assert_source_compliance` etc.

chore: expose component test utils

---

Cargo.lock
Cargo.toml

chore(deps): Bump VRL to 0.11.0

---

.github/actions/spelling/allow.txt
.github/actions/spelling/excludes.txt
.github/actions/spelling/expect.txt
changelog.d/19785_https_svcb_record_types_support.enhancement.md
lib/dnsmsg-parser/src/dns_message_parser.rs

Since these record types are supported by `hickory_proto` crate, it was just a matter of formatting them. This also adds tests based on the data from #19785.
Fixes: #19785

feat(dnsmsg_parser): add support for parsing HTTPS and SVCB records

---

.github/actions/spelling/excludes.txt
.github/actions/spelling/expect.txt
changelog.d/19812_journald_metadata_missing.fix.md
src/sources/journald.rs

Fixes issues with incorrect metadata output when journald source is in `log_namespace` mode. The existing code assumed the metadata fields used to derive `host` and `timestamp` fields were available on the event itself, but in `log_namespace` mode these fields get put on the `%journald.metadata` field.

fix(journald source): correctly emit metadata to log namespace

---

changelog.d/10304_add_prometheus_pushgateway_source.feature.md
changelog.d/19711_add_s3_source_delete_configuration.feature.md
scripts/check_changelog_fragments.sh

This breaks the linking to the user profile

chore(dev): Ensure changelog fragment author doesn't start with @

---

website/cue/reference/remap/functions/parse_etld.cue

docs(vrl): make `parse_etld` fallible in docs

---

.config/nextest.toml

The default is 30 minutes. We saw this timeout recently hit by `vector
sources::kafka::integration_test::handles_one_negative_acknowledgement`.

chore(ci): Reduce test timeout to 2 minutes

---

website/cue/reference/api.cue

Only IP addresses can be used, not `localhost`.

chore(api): Fix API address example

---

changelog.d/18863_k8s_logs_rotate_wait.enhancement.md
lib/file-source/src/file_server.rs
lib/file-source/src/file_watcher/mod.rs
lib/file-source/src/fingerprinter.rs
lib/file-source/src/internal_events.rs
src/internal_events/file.rs
src/sources/file.rs
src/sources/kubernetes_logs/mod.rs
website/cue/reference/components/sources/base/file.cue
website/cue/reference/components/sources/base/kubernetes_logs.cue

* enhancement(file source)
* enhancement(kubernetes_logs source) 
For the file and kubernetes_logs sources, introduced a new configuration variable, rotate_wait, of type Duration, defaulting to practical infinity. Out of the box, this default effectively turns this feature off. rotate_wait determines for how long vector keeps trying to read from a log file that has been deleted (most likely due to log rotation, hence the name of the variable). Once that time span has expired, vector stops reading from and closes the file descriptor of the deleted file, thus allowing the OS to reclaim the storage space occupied by the file. This behavior is similar to that of Fluentd's tail plugin: https://docs.fluentd.org/input/tail#rotate_wait .
Addresses …

enhancement(file source, kubernetes_logs source): add rotate_wait_ms config option

---

rfcs/2023-02-08-7496-vrl-return.md

Partly based on #7496 but closer to a subset from #19766 which does not include any breaking changes such as adding a new reserved keyword to VRL.

enhancement(vrl): RFC for return expression

---

changelog.d/include_paths_glob_patterns.enhancement.md
src/sources/kubernetes_logs/k8s_paths_provider.rs
src/sources/kubernetes_logs/mod.rs
website/cue/reference/components/sources/base/kubernetes_logs.cue
website/cue/reference/components/sources/kubernetes_logs.cue

In addition to the existing `exclude_paths_glob_patterns` configuration option in the kubernetes source, it would be useful to be able to limit the set of candidate logs with the `include_paths_glob_patterns` option, evaluated first.

enhancement(kubernetes): add support for include_paths_glob_patterns

---

Cargo.lock
Cargo.toml
changelog.d/19891_s3_sink_add_express_onezone_storage_class.enhancement.md
src/sinks/s3_common/config.rs
website/cue/reference/components/sinks/base/aws_s3.cue

This change adds support for S3 Express One Zone Storage Class.
Closes #19891

enhancement(s3 sink): add express one zone storage class

---

.github/workflows/changes.yml
.github/workflows/cli.yml
.github/workflows/comment-trigger.yml
.github/workflows/create_preview_sites.yml
.github/workflows/cross.yml
.github/workflows/deny.yml
.github/workflows/e2e.yml
.github/workflows/environment.yml
.github/workflows/gardener_issue_comment.yml
.github/workflows/gardener_open_issue.yml
.github/workflows/gardener_open_pr.yml
.github/workflows/gardener_remove_waiting_author.yml
.github/workflows/install-sh.yml
.github/workflows/integration-comment.yml
.github/workflows/integration.yml
.github/workflows/k8s_e2e.yml
.github/workflows/labeler.yml
.github/workflows/master_merge_queue.yml
.github/workflows/misc.yml
.github/workflows/msrv.yml
.github/workflows/preview_site_trigger.yml
.github/workflows/protobuf.yml
.github/workflows/publish.yml
.github/workflows/regression.yml
.github/workflows/spelling.yml
.github/workflows/test.yml
.github/workflows/unit_mac.yml
.github/workflows/unit_windows.yml
.github/workflows/workload_checks.yml

To override the default of 6 hours. This'll let us bump up the merge queue timeout.

chore(ci): Add a timeout to all CI jobs

---

src/transforms/remap.rs
website/cue/reference/components/transforms/base/remap.cue

The docs assumed the default was `false` when it is actually `true`. I slimmed them down so that
they don't refer to the default.
Fixes: #19916

docs(remap transform): Fix `drop_on_abort` docs

---

.github/ISSUE_TEMPLATE/minor-release.md
.github/ISSUE_TEMPLATE/patch-release.md

We've switched to having a long-running branch representing what to deploy to vector.dev to reduce coordination.

chore(dev): Update release instructions for deploying vector.dev

---

.github/actions/spelling/allow.txt
changelog.d/19937_edns_ede_support.feature.md
lib/dnsmsg-parser/src/dns_message.rs
lib/dnsmsg-parser/src/dns_message_parser.rs
lib/dnsmsg-parser/src/ede.rs
lib/dnsmsg-parser/src/lib.rs
src/sources/dnstap/parser.rs
src/sources/dnstap/schema.rs
website/cue/reference/components/sources/dnstap.cue
website/cue/reference/urls.cue

This adds support for EDNS extended DNS errors. This implementation is slightly different compared to original proposal in #19871, in that it does not return `ede` as a direct child of `responseData`, but rather in `opt` field of `responseData`, since that is where other EDNS options are located.
Fixes: #19871

feat(dnsmsg_parser): add support for EDNS EDE fields

---

src/internal_events/pulsar.rs

This fixes the [component check error](https://github.com/vectordotdev/vector/actions/runs/8026655517/job/21929517605) that is occurring on master due to the new pulsar source.

fix(pulsar source): PulsarErrorEvent only occurs for the source

---

Cargo.lock
Cargo.toml
src/aws/auth.rs
src/aws/mod.rs

Fixes #19879 
The assume role authentication wasn't using the http client, so when it needed to use TLS it was raising an error. Prior to the AWS crate upgrade it was using OpenSSL by default so TLS was built in. V1 of the crates use RustTLS, which we are avoiding, so we turn this feature off and rely on setting up the HTTP client ourselves.
I haven't been able to reproduce the exact error that was reported, but I'm fairly certain it's related. I will shortly have a custom build available for testing if someone want to check that this fixes the issue in their environment.

fix (aws service): use http client so we can use openssl tls.

---

Cargo.lock
Cargo.toml
src/aws/auth.rs
src/aws/mod.rs

Previously if a region wasn't specified, in the config the Region resolver over IMDS would use the AWS connector which uses `rustls`. Since we don't use `rustls` this would error.
So this sets it up so the region resolver uses our http client. The `default_provider` doesn't seem to let us setup our own connector, so I have had to configure a new provider chain.
I have tested this manually on ec2 with imds.

fix(aws service): determine region using our http client

---

src/components/validation/mod.rs

This change simply exposes the component validation framework
```
make test-component-validation
cargo nextest run --no-fail-fast --no-default-features --features component-validation-tests --status-level pass --test-threads 4 components::validation::tests
Starting 3 tests across 3 binaries (1435 skipped)
PASS [   5.856s] vector components::validation::tests::validate_component_tests_validation_components_sources_http_server_yaml
PASS [   9.688s] vector components::validation::tests::validate_component_tests_validation_components_sources_http_client_yaml
PASS [  11.890s] vector components::validation::tests::validate_component_tests_validation_components_sinks_http_yaml
------------
Summary [  11.890s] 3 tests run: 3 passed, 1435 skipped
```

chore(testing): expose component validation framework

---

Cargo.lock

We think this will fix #19627.

chore(deps): Update lockfree-object-pool to 0.1.5

---

src/app.rs
src/topology/controller.rs

The `TopologyController::reload` function took a configuration parameter to load as `Option<Config>`. However, if the config was `None`, it would immediately return with `ReloadOutcome::NoConfig`, which was the also only place that return value could be generated. Instead, this moves the handling of missing configurations to the two callers, simplifying the reload semantics.

chore(core): Remove optionality from topology controller reload

---

regression/cases/datadog_agent_remap_datadog_logs/vector/vector.yaml
regression/cases/datadog_agent_remap_datadog_logs_acks/vector/vector.yaml

This seems to be closer to what real-world usage would look like given customers would likely want
to compress egress traffic to reduce bandwidth costs.

chore(ci): Use gzip compression for datadog_logs regression tests

---

src/sinks/datadog/logs/config.rs
src/sinks/http/config.rs
src/sinks/prelude.rs
src/sinks/splunk_hec/logs/config.rs
src/sources/http_client/client.rs
src/sources/http_client/tests.rs
src/sources/http_server.rs
src/sources/splunk_hec/mod.rs

This is some tech debt because it took me this long to realize that we had no reason to compile the implementation of `ValidatableComponent` outside of unit test runs.

chore(testing): only compile ValidatableComponent in test runs

---

changelog.d/datadog_agent_ddtags_parsing.enhancement.md
src/sources/datadog_agent/logs.rs
src/sources/datadog_agent/mod.rs
src/sources/datadog_agent/tests.rs
website/cue/reference/components/sources/base/datadog_agent.cue

`ddtags` is a log event field set by the Agent, which is a string containing a comma separated list of tags (which can be either bare tags or key:value pairs). 
The new option `parse_ddtags` is disabled by default but when enabled, results in this string event field being parsed and expanded into an Object.
In addition to the unit tests, I validated this change manually with the Agent.

enhancement(datadog_agent source): add `parse_ddtags` config setting to parse the `ddtags` log event field into an object

---

Cargo.lock
LICENSE-3rdparty.csv

chore(deps): Bump whoami to 1.5.0

---

Cargo.toml
changelog.d/aws_credentials_process.fix.md

Otherwise it outputs this warning:
```
2024-03-07T11:59:25.573521Z  WARN provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider failed to provide credentials provider=Profile error=the credentials provider was not properly configured: ProfileFile provider could not be built: This behavior requires following cargo feature(s) enabled: credentials-process. In order to spawn a subprocess, the credentials-process feature must be enabled. (InvalidConfiguration(InvalidConfiguration { source: "ProfileFile provider could not be built: This behavior requires following cargo feature(s) enabled: credentials-process. In order to spawn a subprocess, the credentials-process feature must be enabled."
```

fix(aws provider): Enable `credentials-process` for `aws-config`

---

changelog.d/20035_dnstap_lowercase_hostnames.feature.md
lib/dnsmsg-parser/src/dns_message_parser.rs
src/sources/dnstap/mod.rs
src/sources/dnstap/parser.rs
website/cue/reference/components/sources/base/dnstap.cue

This adds `lowercase_hostnames` option to `dnstap` source, which lowercases all hostnames found in DNS records, for consistency
Fixes: #19901

feat(sources): add `lowercase_hostnames` option to `dnstap` source

---

changelog.d/20032_gzip_zlib_performance.fix.md
src/sinks/util/compressor.rs

Fix gzip and zlib performance degradation caused by:
* flate2 v1.0.28 started to resize its input buffer up to its capacity and back to the actual number of bytes written.
* Some sinks are writing to Compressor without buffering, resulting in frequent small writes to the flate2 writer. Within 32KB of input buffer in flate2, this causes an excessive number of memset operations and degraded sink throughput.
This fix introduces a wrapper buffer in front of gzip and zlib writers to accumulate data before calling the write function of the underlying writer.
fixes: #19981

fix(compression): Fix gzip and zlib performance degradation

---

changelog.d/aws_assume_role.fix.md
changelog.d/aws_region_autodetect.fix.md
changelog.d/kafka_rebalance_panic.fix.md

chore(releasing): Add missing changelog entries

---

Cargo.lock
Cargo.toml
changelog.d/20006_improve_greptimedb_tls.enhancement.md
src/sinks/greptimedb/mod.rs
src/sinks/greptimedb/service.rs

This patch improves TLS support for greptimedb sink, by updating the client sdk, and improving how we parse the configuration.
Before this patch, we will need to configure a custom server ca certificate to use TLS. However, for those hosting greptimedb using public ca, like letsencrypt, this server ca file is not required. So with change, we make server certificate completely optional for enable TLS.
This has been verified against greptimedb's hosted service.

feat(greptimedb sink): improve tls support for greptimedb sink

---

website/layouts/_default/component-card-selectable.html
website/layouts/_default/component-card.html
website/layouts/partials/meta.html

I missed a few spots in https://github.com/vectordotdev/vector/pull/20058

fix(docs): Use `component_kind` rather than `kind` in templates

---

regression/cases/enterprise_http_to_http/vector/vector.yaml

To unblock making unset env vars an error per https://github.com/vectordotdev/vector/pull/20062 since the regression tests use config from `master`.

chore(ci): Default env vars for enterprise_http_to_http regression case

---

changelog.d/deprecate_strict_env_vars.breaking.md
docs/DEPRECATIONS.md
src/cli.rs
website/cue/reference/cli.cue

chore(cli)!: Update default for --strict-env-vars to true

---

changelog.d/README.md
changelog.d/pulsar_source2.feature.md
scripts/check_changelog_fragments.sh
scripts/generate-release-cue.rb

This:
- Assumes contributors are space delimited, as we have been doing in practice
- Normalizes the description field so that it always terminates in a single newline. Previously, if
there were contributors, it would have an extra blank line

chore(dev): Update changelog generation script to handle authors and whitespace

---

.github/actions/spelling/allow.txt
changelog.d/20051_permit_origin_tcp.feature.md
lib/vector-core/src/ipallowlist.rs
src/sources/dnstap/tcp.rs
src/sources/fluent/mod.rs
src/sources/logstash.rs
src/sources/socket/mod.rs
src/sources/socket/tcp.rs
src/sources/statsd/mod.rs
src/sources/syslog.rs
website/cue/reference/components/sources/base/dnstap.cue
website/cue/reference/components/sources/base/fluent.cue
website/cue/reference/components/sources/base/logstash.cue
website/cue/reference/components/sources/base/socket.cue
website/cue/reference/components/sources/base/statsd.cue
website/cue/reference/components/sources/base/syslog.cue

Adds `permit_origin` config option to all sources that have a TCP mode (introduced in https://github.com/vectordotdev/vector/pull/19892).
Related: https://github.com/vectordotdev/vector/pull/19892

feat(sources): add `permit_origin` config option for all tcp sources

---

changelog.d/file_ignored_header_bytes_default.fix.md
src/sources/file.rs

To match the docs.
Fixes: #20072

fix(file source): Set ignored_header_bytes default to `0`

---

website/cue/reference/components/sinks/vector.cue

It was accidentally pulling the source's.
Fixes: #20092

fix(docs): Use correct how_it_works section for Vector sink

---

changelog.d/dd_logs_semantic_meaning.fix.md
src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/sink.rs

The `datadog_logs` sink now does not require a semantic meaning input definition for `message` and `timestamp` fields.
While the Datadog logs intake does handle these fields if they are present, they aren't required.
The only impact is that configurations which enable the Log Namespace feature and use a Source input to this sink which does not itself define a semantic meaning for `message` and `timestamp`, no longer need to manually set the semantic meaning for these two fields through a remap transform.
Existing configurations that utilize the Legacy namespace are unaffected.

fix(datadog_logs sink): relax required input semantic meanings

---

changelog.d/remove_remap_file_filter.enhancement.md
src/transforms/remap.rs

Reverts vectordotdev/vector#19356. After some more consideration we've decided to revert this until we can come up with a better long term solution.
Fixes: #20124

enhancement(remap): do not filter out file contents from error logs

---

src/components/validation/resources/event.rs
src/components/validation/resources/http.rs
src/components/validation/runner/mod.rs

This PR makes a few changes that became necessary when implementing the validation for the `datadog_agent` source (https://github.com/vectordotdev/vector/pull/20044)
- allow the log_builder test case event variant to define values that are non-strings
- in the HTTP External Resource for input driver- handle the case where we are dealing with character delimited JSON, by wrapping the event object in a JSON array and adjusting the runner's expected metric accordingly.
- and finally, a strange one- the `datadog_agent` component decodes the JSON fields into a custom structure, and then adds them to the log event. The only discrepancy is the timestamp, which the Agent sends (and thus the input driver must encode) as a unix timestamp (integer), but Vector converts that into a DateTime string …

chore(testing): further adjustments to component validation framework

---

src/api/schema/metrics/mod.rs
src/api/schema/mod.rs

https://github.com/vectordotdev/vector/commit/80f63bb6b52561ae4a9f98783ae98472c0798845 caused a failure when enabling just the `api` feature and not `host_metrics`. This seems to be due to the fact that `MetricsQuery` is empty when there `host_metrics` is disabled. To remedy this, I moved the feature gate so that `MetricsQuery` itself is not included when `host_metrics` is disabled.

chore(api): Move host_metrics feature gate

---

lib/vector-vrl/tests/src/docs.rs
tests/behavior/transforms/remap.toml
website/cue/reference/remap/functions/uuid_v7.cue
website/cue/reference/urls.cue

This PR introduces the following changes:
* add remap behavioral test for VRL `uuid_v7()` function
* provided cue website documentation for `uuid_v7()` function
* depends on vectordotdev/vrl/pull/738

feat(vrl): add `uuid_v7` function

---

Cargo.lock
Cargo.toml

Now that 0.37.0 has been released.

chore(dev): Bump Vector to 0.38.0

---

changelog.d/20192_geoip_geolite_city_support.fix.md
src/enrichment_tables/geoip.rs

Brings back support for `GeoLite2-City` DB after adding custom `mmdb` type. The issue was that previously any unknown DB type was treated as a City DB, which covered the case of `GeoLite2-City`. This now explicitly adds it as a supported type.
Fixes: #20191
Related: #20054

fix(enrichment_tables): bring back support for `GeoLite2-City` db

---

scripts/e2e/datadog-logs/compose.yaml
scripts/e2e/datadog-metrics/compose.yaml

The `latest` tag is throwing errors on GET requests. Temporarily pegging to unblock PRs.

chore(ci): peg `fakeintake` docker image

---

website/content/en/highlights/2023-03-26-0-37-0-upgrade-guide.md

`mode` is now a required parameter with no default. This was noticed by a user in Discord.

docs(dnstap source, releasing): Add breaking change note for dnstap source mode

---

src/components/validation/mod.rs
src/components/validation/resources/http.rs
src/components/validation/resources/mod.rs
src/components/validation/runner/config.rs
src/components/validation/runner/mod.rs
src/components/validation/validators/component_spec/mod.rs
src/sinks/datadog/logs/config.rs
src/sinks/http/config.rs
src/sinks/splunk_hec/logs/config.rs
src/sources/datadog_agent/tests.rs
src/sources/http_client/tests.rs
src/sources/http_server.rs
src/sources/splunk_hec/mod.rs
src/sources/vector/mod.rs

This enables support in the Component Validation Framework for setting the LogNamespace used within the input edge when transforms and sinks are under test, which is necessary when the Vector namespace is being used, in order for required semantic meanings to be defined.
Includes a couple small error handling improvements to the HTTP external resource as well, for debugging purposes.

chore(testing): support LogNamespace in Component Validation Framework

---

.github/workflows/compilation-timings.yml
.github/workflows/e2e.yml
.github/workflows/integration-comment.yml
.github/workflows/integration-test.yml
.github/workflows/integration.yml
.github/workflows/k8s_e2e.yml
.github/workflows/misc.yml
.github/workflows/publish.yml
.github/workflows/regression.yml
.github/workflows/test.yml
.github/workflows/unit_windows.yml

GHA is deprecating multi-label runners at the end of April.

chore(ci): Only use one label for selecting GHA runner

---

website/content/en/docs/setup/installation/platforms/kubernetes.md

This example kustomization file is rejected, with the following error:
```
error: accumulating resources: accumulation err='accumulating resources from 'git@github.com:vectordotdev/vector.git/tree/master/distribution/kubernetes/vector-agent': evalsymlink failure on '/home/user/Documents/workspace-kube/bug-free-broccoli/vector/git@github.com:vectordotdev/vector.git/tree/master/distribution/kubernetes/vector-agent' : lstat /home/user/Documents/workspace-kube/bug-free-broccoli/vector/git@github.com:vectordotdev: no such file or directory': evalsymlink failure on '/tmp/kustomize-1831957474/tree/master/distribution/kubernetes/vector-agent' : lstat /tmp/kustomize-1831957474/tree: no such file or directory
```
This is because the url is recognized as a github link, and gives an erroneous path. …

docs(kubernetes platform): fix example kustomization file

---

src/transforms/tag_cardinality_limit/config.rs
website/cue/reference/components/transforms/base/tag_cardinality_limit.cue
website/cue/reference/components/transforms/tag_cardinality_limit.cue

- Renamed `cache_size_per_tag` mentions to `cache_size_per_key`. This references are more than 2 years old, so I assume it was initially a typo
- Removed `fields` key from example of this transform configuration. Also looks like a oversight rather than something deliberate

docs: fix type cardinality docs

---

lib/vector-core/src/schema/meaning.rs
scripts/integration/datadog-logs/test.yaml
src/common/datadog.rs
src/sinks/datadog/logs/sink.rs
src/sources/datadog_agent/mod.rs

- Currently the `datadog_logs` sink only properly handles log namespaced `message`, `hostname`, `timestamp` and `ddtags` reserved attributes.
- This change extends that to support all the remaining reserved attributes: `service`, `severity` and alters the implementation to do so in a more generic fashion.
- Unit tests were extended to cover the additional attributes

chore(datadog_logs sink): properly encode all semantically defined DD reserved attributes

---

website/content/en/docs/setup/installation/platforms/docker.md

In the docker run command example it was missing --name vector, thus the command after failed

docs: Correct docker.md so the command can be executed

---

src/sinks/humio/logs.rs
src/sinks/humio/metrics.rs
src/sinks/splunk_hec/common/util.rs
src/sinks/splunk_hec/logs/config.rs
src/sinks/splunk_hec/logs/integration_tests.rs
src/sinks/splunk_hec/logs/sink.rs
src/sinks/splunk_hec/logs/tests.rs
src/sources/splunk_hec/mod.rs
website/cue/reference/components/sinks/base/humio_logs.cue
website/cue/reference/components/sinks/base/humio_metrics.cue
website/cue/reference/components/sinks/base/splunk_hec_logs.cue

- Currently the splunk hec logs sink has default paths for the `timestamp_key` and `host_key` configurable settings which statically point to the global log namespace location for these keys.
- In order to support log namespacing for these settings, the logic for determining the default case is moved from the configuration serialization down into the sink's encoding of the event. That is necessary because we must determine at runtime if each event received is namespaced or not.
- Note that this necessitated a small change to the Humio sinks as well simply due to those sinks being wrappers over Splunk HEC, to preserve existing behavior.

chore(splunk_hec_logs sink): support log namespaced host and timestamp attributes

---

changelog.d/20224_kafka_source_event_instrumentation.fix.md
src/sources/kafka.rs

This ensures the source `span` is passed through to the kafka consumer tasks so that metrics can be correctly instrumented.
Fixes: https://github.com/vectordotdev/vector/issues/20224

fix(kafka source): fix source span instrumentation

---

changelog.d/20228_fix-log-to-metric-set-supported.fix.md
src/transforms/log_to_metric.rs
testing/github-20228/config.toml

I am pretty sure this is a bug. I was not able to make this work. I submit a test case that fails on current released versions. How could I set up this test case to run continuously?

fix(log_to_metric transform): set not working in log-to-metric transform when all_metrics=true

---

changelog.d/prometheus_mixed_gauges.fix.md
src/sinks/prometheus/exporter.rs
src/sinks/util/buffer/metrics/normalize.rs

Big thank you to @RussellRollins for writing the failing test here! That was very helpful to narrow down the issue.
This simple fix here comes with some unfortunate downsides that we're going to need to consider before merging.
The root cause here is that we didn't really expect to need to handle a mix of incremental and absolute values for the same series. Concretely, this means the metrics normalizer only maintains state when it sees an incremental metrics that it needs to convert to absolute. If it sees an absolute metric, it assumes it will always be absolute and does not bother to store any state. That is why the failing test shows that incremental values "reset" the metric and don't take into account the previous absolute value.
To handle this case, we need to maintain state for all …

fix(metrics): normalizer doesn't handle mix of absolute and incremental metrics

---

.github/workflows/publish.yml

This was accidentally dropped in e9815e1f328 resulting in the SHA256SUMS not being uploaded to the GitHub releases.

chore(ci): Download SHA256SUMS to correct location

---

changelog.d/20214_amqp_expiration.enhancement.md
src/sinks/amqp/config.rs
website/cue/reference/components/sinks/base/amqp.cue

AMQP messages can be sent with an expiration by exposing the Lapin `with_expiration` option. This PR does that in the `properties` subsection of config
I filed an issue to attach to this PR https://github.com/vectordotdev/vector/issues/20214

enhancement(amqp sink): add expiration option to AMQP messages

---

changelog.d/19686_element_size_histogram.enhancement.md
src/internal_events/common.rs
src/internal_events/socket.rs
website/cue/reference/components/sources/internal_metrics.cue
website/cue/reference/components/sources/socket.cue
website/cue/reference/components/sources/statsd.cue
website/cue/reference/components/sources/syslog.cue

Useful when debugging low-level sources like UDP, TCP sockets
If this metric looks good, I can add docs and we can prepare to merge. Thanks!

enhancement(source metrics): Adding a histogram for event byte size

---

changelog.d/20172_max_number_of_messages.enhancement.md
src/sources/aws_s3/mod.rs
src/sources/aws_s3/sqs.rs
website/cue/reference/components/sources/base/aws_s3.cue

Implements #20172
Allows for selection of maximum number of messages to pull from the S3 queue.
Compiled and tested for functionality.

enhancement(aws_s3 source): Adds an option `max_number_of_messages` for the aws_s3 source

---

changelog.d/20282_aws_access_key_id_and_assume_role_auth.fix.md
src/aws/auth.rs

Fixes #20282 
This fixes the error that we received when using both `access_key_id` and `assume_role` together. The builder used in that situation should have had a custom http client provided so it could use our TLS and proxy settings.
*Note:* I have tested this by running locally with that authentication scheme in the config. This gave me the same error in the issue. I fixed the bug and ran again. I now get the error `STS refused to grant assume role`, which is expected because I have not set up a valid client in AWS. I am pretty confident that this fixes the issue, but have not tested 100% to the end to save time having to setup a fairly complex authentication scheme in AWS.

fix(aws service): use http client when building assume role for AccessKey

---

Cargo.lock
Cargo.toml
changelog.d/20331_databend_config_ndjson.enhancement.md
src/sinks/databend/config.rs
src/sinks/databend/encoding.rs
website/cue/reference/components/sinks/base/databend.cue
website/cue/reference/components/sinks/databend.cue

Added new config field `missing_field_as` as file format option for `NDJSON` encoding, default value is `NULL`.

feat(databend sink): add config missing_field_as for ndjson insert

---

rust-toolchain.toml

chore(deps): Bump rust-toolchain to 1.77.2

---

src/sources/host_metrics/cgroups.rs

* `cgroup_memory_anon_bytes` and `cgroup_memory_file_bytes` are no longer zero on cgroups v2 systems
* test `sources::host_metrics::cgroups::tests::generates_cgroups_metrics` should no longer flap
I'm not sure why the `is_root` check was there for cgroups v2. Memory is only in the root cgroup dir. No child dirs exist in cgroup root on my machine.
Fixes https://github.com/vectordotdev/vector/issues/18697

fix(host_metrics source): Include cgroups2 root memory metrics

---

lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
src/sources/datadog_agent/tests.rs
src/transforms/remap.rs

Trying to get mutable access to a log event field by meaning currently requires cloning the owned path returned by `find_key_by_meaning` because of the reference requiring another borrow to the log event. Instead, we can clone the underlying schema `Arc` and use that to index into the mutable log.

chore(core): Implement `LogEvent::get_mut_by_meaning`

---

.github/workflows/publish.yml
scripts/verify-install.sh

Adds `dd-pkg` to CI for linting the produced DEB and RPM packages. Today this only checks that the package doesn't contain any world-writable files.
This lint was previously performed at the time of package promotion, so this is just shifting the check closer to the source.

test: Install dd-pkg in *-verify workflows and lint in verify-install.sh

---

docs/specs/component.md

Vector originally published two component bytes metrics:
- `component_sent_bytes_total` the number of serialized bytes successfully sent by sinks (before
compression)
- `component_received_bytes_total` the number of serialized bytes successfully received by sources
(after decompression and filtering)
These were intended to be used by users to understand the volume of data flowing in/out of sources
and sinks. However, they were dependent on the exact serialization format such that the same event
going into the `socket` source vs. `vector` source might be measured differently. To have
a consistent metric we then added:
- `component_sent_event_bytes_total` the number of "estimated JSON event" bytes successfully sent by a components
- `component_received_event_bytes_total` the number of …

chore: Add future deprecation note for `component_(sent|received)_bytes_total` metrics

---

.github/workflows/environment.yml

We appear to be hitting the 15 minute timeout now.

chore(ci): Bump timeout for `publish-new-environment` in CI

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
changelog.d/19990_support_loading_secrets_from_aws_secrets_manager.feature.md
src/secrets/aws_secrets_manager.rs
src/secrets/mod.rs
website/cue/reference/configuration.cue

Adds an option to resolve secrets from AWS Secrets Manager - e.g.:
```yaml
secret:
loki:
type: "aws_secrets_manager"
secret_id: "/secret/my-fancy-secret"
sinks:
loki_application_logs:
auth:
strategy: basic
user: 'SECRET[loki.username]'
password: 'SECRET[loki.password]'
```
with the secret containg key/value pairs:
```
{
"username": "test",
"password": "example-password"
}
```
Fixes https://github.com/vectordotdev/vector/issues/19990

feat(config): Support loading secrets from AWS Secrets Manager

---

.github/workflows/component_features.yml

Since GH only supports one runner label we [recently updated](https://github.com/vectordotdev/vector/pull/20210/files) our workflows but missed one- the component features when run on demand via comment trigger.

fix(ci): component features comment trigger one runner label

---

.github/workflows/integration.yml
.github/workflows/misc.yml

A recent PR was bumping into these:
https://github.com/vectordotdev/vector/pull/20429

chore(ci): Bump timeouts for test-misc and integration tests

---

Cargo.lock
changelog.d/20437-enterprise.deprecation.md
docs/DEPRECATIONS.md
src/app.rs

Nobody is known to be using this feature, and it is adding complications to the code base. This change adds a warning if it is used and notes the deprecation state.

chore(enterprise): Deprecate the `enterprise` feature

---

Cargo.lock
vdev/Cargo.toml

It's listed in `vdev` but not actually used

chore(deps): Drop `cached`

---

website/cue/reference/remap/concepts/metrics.cue

docs: Fix link to remap event data model

---

website/cue/reference/components/sources/internal_metrics.cue
website/cue/reference/components/sources/kubernetes_logs.cue

These were removed during refactoring to use the `component_*` metrics.
Closes: https://github.com/vectordotdev/vector/issues/20491

chore(kubernetes_logs source): Remove unreported metrics from the docs

---

lib/vector-config/src/component/description.rs
src/generate.rs

The example value field in component descriptions is wrapped in an `Option`, but all uses of it set it to `Some`. This removes the optionality and drops the resulting unreachable error case.

chore(config): Drop support for missing example configs

---

scripts/e2e/Dockerfile
scripts/environment/bootstrap-windows-2019.ps1
scripts/environment/prepare.sh
scripts/integration/Dockerfile

Should resolve https://github.com/nextest-rs/nextest/issues/1493

chore(deps): Bump cargo-nextest

---

website/content/en/docs/setup/installation/operating-systems/nixos.md

Improved NixOS documentation by porting the config to JSON and also showing how to access an external service logs with additional group permissions.

doc: Improve NixOS documentation

---

website/content/en/guides/advanced/parsing-csv-logs-with-lua.md

The provided example does not work for postgres > 13 since there are 3 extra fields in the csv export: backend_type, leader_pid, query_id. 
When iterating over csv fields, the script cannot get columns names for these extra fields and fails with error `attempt to index a nil value (global 'column_name')`
Here is a suggestion to fix the example:
* iterate over columns name, not csv fields should be preferred imho.
* add extra column names `backend_type`, `leader_pid`, `query_id` in `column_names` variable

fix(external docs): Fix parsing-csv-logs-with-lua.md example for postgres > 13

---

.github/workflows/publish.yml

Prompted because centos:stream8 repos disappeared due to it being EOL. I removed other EOL versions and added newer versions we weren't currently testing.

chore(ci): Update versions of OSes used for testing the RPM package

---

src/enrichment_tables/file.rs

All of the fields required to instantiate a GeoIP enrichment table configuration are public, but all of the ones for files are private. This makes the latter public as well.

chore(enrichment_tables): Make configuration fields public

---

docs/specs/component.md

This contradicts the statement that the bytes metrics should be before compression and after decompression.
Ref: https://github.com/vectordotdev/vector/issues/20610

chore(docs): Remove references to HTTP Content-Length from component spec

---

Cargo.lock
changelog.d/20478_update_sasl2.fix.md

This is a minor update to `Cargo.lock` updating `sasl2-sys` to the 0.1.22 release. This fixes building on GCC 14+ and Clang environments (e.g. Fedora 40 and others), which fail building due to those compilers now treating various warnings as errors.
See original thread in #20478

chore(dev): Update sasl2-sys to fix building on GCC 14+ / CLang environments

---

deny.toml

Required by https://github.com/vectordotdev/vector/pull/20642
License text: https://opensource.org/license/unicode-license-v3
We are already complying with the terms which are similar to `Unicode-DFS-2016`.

chore(deps): Allow unicode-3 license

---

src/sinks/prometheus/remote_write/mod.rs

Only used when AWS configuration (`aws-core`) is enabled.
This was exposed by the Rust 1.78.0 upgrade in 58114f1345c1fe33807d14f0c8f8ae9087919d19

chore(deps): Ensure prometheus::remote_write::Errors is appropriately gated

---

.github/workflows/create_preview_sites.yml
.github/workflows/preview_site_trigger.yml

- Fixes the way the key is hashed
- Updates the workflow trigger to only run if the branch contains the word `website`
The branch creation settings on the apps was updated as well, for now only vector.dev will deploy via the workflow, the rust-doc and playground will also work after some cleanup in the app that doesn't happen via this PR

fix(website): Update action for previews

---

.github/workflows/environment.yml

p95 is 18 minutes which is a bit close for comfort. I've seen some timeouts recently.

chore(ci): Bump timeout for publishing new environment

---

.github/workflows/comment-trigger.yml

As repository is always `vectordotdev/vector` since this is a trigger on a comment.

chore(ci): Validate PR author instead of repository

---

.github/workflows/integration-comment.yml

Same fix as introduced to other comment workflow in https://github.com/vectordotdev/vector/commit/37e0c1dc5c532d8dc3b4c175566663c057158c2a

chore(ci): Restrict integration comment workflow to PRs from maintainers

---

changelog.d/20687-kafka_source_validate_deadlock.fix.md
src/sources/kafka.rs

This moves the `consumer.subscribe(topics)` call into the main kafka source loop, to ensure that callback handlers will be set up whenever the consumer is subscribed.
In `vector validate` mode for example, the consumer sometimes receives partition assignments, and the consumer invokes pre_rebalance handlers. The main consumer task is not polled in that scenario, so callback messages sent to the coordination task are never handled and the pre_rebalance handler deadlocks. Moving the subscribe call into the main loop means that the consumer will not join the group and will not get a partition assignment unless the main source task is being polled.
Closes https://github.com/vectordotdev/vector/issues/20687

fix(kafka source): consumer subscribe in main kafka source task

---

changelog.d/demo_logs_host.enhancement.md
src/sources/demo_logs.rs

I think it's reasonable for this field to be set by default.
Closes: https://github.com/vectordotdev/vector/issues/20726

enhancement(demo_logs source): Add `host` to emitted logs

---

changelog.d/update-x86-64-cross-base.breaking.md
scripts/cross/bootstrap-centos.sh
scripts/cross/entrypoint-centos.sh
scripts/cross/x86_64-unknown-linux-gnu.dockerfile

The previous base, CentOS 7, is now EOL as of 2024-06-30 so the mirrors are no longer responsive.
This drops support for the x86_64 build of Vector running on CentOS 7 (since Ubuntu 16.04 has
a newer glibc).

chore(releasing)!: Update the base image used for x86_64 artifacts to Ubuntu 16.04

---

changelog.d/19614_gcp_token_regeneration.enhancement.md
src/gcp.rs

Ref: https://github.com/vectordotdev/vector/issues/19614
**Summary:** This PR modifies the timing strategy used to regenerate the GCP authentication token.
I'm not a rust expert but when looking into the above GH Issue, it would seem that the 401 responses being returned from Google are likely as a result of a missed tick in the `token_regenerator` function.
Currently, the `expires_in` value (in seconds) is read from the token and divided by 2 in order to determine the Interval period to use as tick frequency.  If the `expires_in` value is 1000, there would be two ticks: one at 500 seconds in the future and another at 1000.  If the second tick is delayed for any reason, then Vector will send an out of date token to Google which will result in 401s.  Rust's default MissedTickBehaviour is …

fix(GcpAuthenticator): Improve token regeneration

---

website/cue/reference/components/aws.cue
website/cue/reference/components/sinks/base/aws_cloudwatch_logs.cue
website/cue/reference/components/sinks/base/aws_cloudwatch_metrics.cue
website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue
website/cue/reference/components/sinks/base/aws_kinesis_streams.cue
website/cue/reference/components/sinks/base/aws_s3.cue
website/cue/reference/components/sinks/base/aws_sns.cue
website/cue/reference/components/sinks/base/aws_sqs.cue
website/cue/reference/components/sinks/base/elasticsearch.cue
website/cue/reference/components/sinks/base/prometheus_remote_write.cue
website/cue/reference/components/sources/base/aws_s3.cue
website/cue/reference/components/sources/base/aws_sqs.cue

Reverts vectordotdev/vector#20774
I realized this was incorrectly updating the doc files directly rather than the code.

chore(ci): Revert "Add trailing slash to aws endpoint examples"

---

changelog.d/20575_kinesis_batching.fix.md
src/sinks/aws_kinesis/sink.rs

Send batches to AWS Kinesis Data Streams and AWS Firehose independent of ther parition keys.  In both API's batches of events do not need to share the same partition key.
This makes the protocol more efficient, as by default the partition key is a random key being different for every event.
I validated this commit locally, all unit tests are successful.  Relying on CI for integration tests.

fix(aws_kinesis sink): fix batching of requests #20575 #1407

---

website/cue/reference/components/sinks/base/aws_cloudwatch_logs.cue
website/cue/reference/components/sinks/base/aws_cloudwatch_metrics.cue
website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue
website/cue/reference/components/sinks/base/aws_kinesis_streams.cue
website/cue/reference/components/sinks/base/aws_s3.cue
website/cue/reference/components/sinks/base/aws_sns.cue
website/cue/reference/components/sinks/base/aws_sqs.cue
website/cue/reference/components/sinks/base/elasticsearch.cue
website/cue/reference/components/sinks/base/prometheus_remote_write.cue
website/cue/reference/components/sources/base/aws_s3.cue
website/cue/reference/components/sources/base/aws_sqs.cue

Was missed in https://github.com/vectordotdev/vector/pull/20774 because the check didn't run.

chore(docs): Regenerate component docs

---

src/sinks/gcs_common/service.rs

Replaces `//` with `/` when merging base url and object keys to avoid creating "/" root folder.

fix(gcs): replace // with / when merging base url and object key

---

.github/workflows/publish.yml

actions/checkout@v3 now requires NodeJS v20. This workaround should work temporarily but it looks like they might be pulling Node v16 from all runners in the nearish future. We'll need to figure something else out before then (maybe just checking out manually).

chore(ci): Use NodeJS v16 for package verification workflows

---

regression/cases/file_to_blackhole/experiment.yaml

During the recent SMP upgrade it was observed that this soak test exhibits strange behavior and, anecdotally, seems to be resulting in a lot of false positives like the ones seen here: https://github.com/vectordotdev/vector/pull/20821

chore(ci): Marke file_to_blackhole soak as erratic

---

.github/workflows/regression.yml

Vector has been seeing some unusual false positive results, and looking into the detailed data, we observe a "spike" in egress throughput at the beginning of the job.
By increasing the warmup duration, we should effectively ignore this early spike, which should give cleaner data for analysis.
Example:

chore: Increases default warmup duration for Regression Detector jobs

---

.github/workflows/regression.yml

Small fix that was missed in #20828

chore: Adds a trailing newline escape for smp job submit

---

changelog.d/vrl-secrets-impure.fix.md
lib/vector-vrl/functions/src/remove_secret.rs
lib/vector-vrl/functions/src/set_secret.rs

Otherwise the VRL compiler complains that the return value isn't consumed.
Fixes: #20809

fix(vrl): Mark set_secret and remove_secret as impure

---

.github/workflows/changes.yml

Avoids breakages like the one introduced by https://github.com/vectordotdev/vector/pull/20774

chore(ci): Run component docs check if component cue files change

---

changelog.d/vector_tap_duration_flag.enhancement.md
src/tap/cmd.rs
src/tap/mod.rs
website/cue/reference/cli.cue

Adds optional `duration` flag to `vector tap` command, which allows specifying how long to run `tap` before exiting (by default `tap` will run indefinitely)
Tested by using `tap` on a `demo_logs` test pipeline (both with and without the duration flag)

feat(tap): Add duration flag to vector tap

---

Cargo.lock
Cargo.toml
changelog.d/refactor_vector_tap_to_library.md
lib/vector-lib/Cargo.toml
lib/vector-lib/src/lib.rs
lib/vector-tap/Cargo.toml
lib/vector-tap/src/lib.rs
src/tap/cmd.rs

Adding a new use case which will re-use the logic used to implement the `vector tap` command to retrieve a live view of events flowing through Vector. This PR refactors out the required logic to a general library.
Will publish a follow-up PR that adds additional functionality for new use case.
Tested by using tap on a demo_logs test pipeline

refactor(tap): Refactor vector tap into library

---

changelog.d/20763_loki_sink_drop_invalid_timestamp_event.fix.md
src/internal_events/loki.rs
src/sinks/loki/sink.rs
src/sinks/loki/tests.rs

Fix https://github.com/vectordotdev/vector/issues/20763

fix(loki sinks): Fix loki event timestamp out of range panic

---

.github/actions/spelling/allow.txt
Cargo.lock
changelog.d/17125_proxy_auth_url_encoded.fix.md
lib/vector-core/Cargo.toml
lib/vector-core/src/config/proxy.rs

fixes: #17125
its common for proxy authorization to contain special characters as URL-encoded values. Vector previously did not decode these but does now with this change.
Note that a unit test was previously added to repro the issue. Its now been un-ignored and passes.

fix(proxy): support url-encoded auth values

---

.github/workflows/changes.yml
.github/workflows/integration.yml
scripts/integration/eventstoredb/test.yaml
src/sources/eventstoredb_metrics/mod.rs
src/sources/eventstoredb_metrics/types.rs

The integration test started failing because v26.4 of EventstoreDB switched the disk usage metric from a string like 30% to an integer. I updated the deserialization to handle both and added both versions to the integration test matrix.

chore(ci): Fix and reenable eventstoredb integration test

---

changelog.d/template-semantic-timestamp.fix.md
src/template.rs

The test here isn't passing, but pushing it up for feedback.
Closes: #20785

fix(config): For templates using stftime specifiers use semantic timestamp

---

.github/workflows/unit_mac.yml
scripts/environment/bootstrap-macos-10.sh

The package was renamed from rustup-init to rustup which seems to be causing some issues in CI where the package is already installed (because `rustup-init` was renamed to it) but `rustup` doesn't have the actual `rustup` binaries downloaded. Reinstalling seems to fix this.

chore(ci): Reinstall rustup in MacOS bootstrap

---

changelog.d/20768-default_gelf_stream_framing.breaking.md
lib/codecs/src/decoding/framing/character_delimited.rs
lib/codecs/src/decoding/mod.rs
lib/codecs/src/encoding/mod.rs
src/codecs/decoding/decoder.rs

Closes #20768.
I think that in my local environment some test fail but has nothing to do with the changes I did. Could you trigger them here and if its fails too in the CI I review what could happen?
Thanks

fix!(codecs): Use '\0' delimiter as default stream decode framer

---

changelog.d/20891_disallow_zero_for_sink_retry_params.fix.md
src/sinks/util/service.rs

Change `retry_initial_backoff_secs` and `retry_initial_backoff_secs` from `u64` to `NonZeroU64` to prevent divide by zero panic at runtime.
Fixes: #20890

fix: disallow zero values for sink retry parameters

---

CONTRIBUTING.md

The link pointed to the directory containing the right file, but is more convenient as a link to the file itself.

docs: Fix link to commit scopes in CONTRIBUTING.md

---

changelog.d/20834_nats_jetstream_sink.feature.md
src/sinks/nats/config.rs
src/sinks/nats/integration_tests.rs
src/sinks/nats/mod.rs
src/sinks/nats/service.rs
src/sinks/nats/sink.rs
website/cue/reference/components/sinks/base/nats.cue

Add new option `jetstream` to nats sink configuration that allows using jetstream to sink into nats

feat(new sink): Add possibility to use nats jetstream in nats sink

---

Cargo.lock
LICENSE-3rdparty.csv
changelog.d/19637_influxdb_line_protocol_decoder.enhancement.md
lib/codecs/Cargo.toml
lib/codecs/src/decoding/format/influxdb.rs
lib/codecs/src/decoding/format/mod.rs
lib/codecs/src/decoding/mod.rs
src/components/validation/resources/mod.rs
website/cue/reference/components/sources/base/amqp.cue
website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
website/cue/reference/components/sources/base/aws_s3.cue
website/cue/reference/components/sources/base/aws_sqs.cue
website/cue/reference/components/sources/base/datadog_agent.cue
website/cue/reference/components/sources/base/demo_logs.cue
website/cue/reference/components/sources/base/exec.cue
website/cue/reference/components/sources/base/file_descriptor.cue
website/cue/reference/components/sources/base/gcp_pubsub.cue
website/cue/reference/components/sources/base/heroku_logs.cue
website/cue/reference/components/sources/base/http.cue
website/cue/reference/components/sources/base/http_client.cue
website/cue/reference/components/sources/base/http_server.cue
website/cue/reference/components/sources/base/kafka.cue
website/cue/reference/components/sources/base/nats.cue
website/cue/reference/components/sources/base/pulsar.cue
website/cue/reference/components/sources/base/redis.cue
website/cue/reference/components/sources/base/socket.cue
website/cue/reference/components/sources/base/stdin.cue

feat(codec,sources): influxdb line protcol decoder

---

changelog.d/20930_socket_sink_accepts_metrics.fix.md
src/sinks/socket.rs
src/sources/socket/unix.rs

Closes https://github.com/vectordotdev/vector/issues/20756

fix(socket sink): Allow socket sink to accept metrics.

---

changelog.d/socket-not-respecting-global-log-namespace.fix.md
src/sources/socket/mod.rs

Socket source wasn't correctly merging log_namespace with global config.

fix(socket source): fix socket source ignoring global log_namespace when computing outputs

---

website/cue/reference/remap/functions/replace.cue

Even though the [replace function](https://vector.dev/docs/reference/vrl/functions/#replace) documentation already states that $$ should be used instead of $ in configuration files, the [specific use case example](https://vector.dev/docs/reference/vrl/functions/#replace-examples-replace-with-capture-groups) does not emphasize this distinction. This can easily lead to misunderstandings, especially for newcomers. Since many people will use this in configuration files, I believe it is necessary to explicitly clarify the different usage in the specific use case example.
related issue: #20988

docs(external docs): Emphasize the $$ rather than $ in config file.

---

.github/workflows/ci-integration-review.yml
.github/workflows/cli.yml
.github/workflows/component_features.yml
.github/workflows/cross.yml
.github/workflows/deny.yml
.github/workflows/environment.yml
.github/workflows/k8s_e2e.yml
.github/workflows/misc.yml
.github/workflows/regression.yml
.github/workflows/unit_mac.yml
.github/workflows/unit_windows.yml

It is `github.event` not `github.events`

chore(ci): Fix review comment trigger context

---

scripts/environment/bootstrap-ubuntu-20.04.sh
scripts/integration/README.md
vdev/src/testing/config.rs
vdev/src/testing/integration.rs
website/cue/reference/administration/management.cue

`docker-compose` usage has been removed from GHA runners as of July 29th, 2024. See https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/

chore(ci): Replace usages of `docker-compose` with `docker compose`

---

Cargo.toml

Snafu does not build if the futures feature is enabled and the std feature is disabled. Snafu was already being built with the std feature enabled because some other dependency of vector happened to enable it. This commit just makes the existing implicit feature dependency explicit instead.

<fix>: Correct snafu features

---

lib/codecs/src/decoding/mod.rs

Found a missing assert in a test that was done by myself.
the `matches` macro does not panic if the pattern does not match, it just returns false.

test(codecs): add missing assert in codec decoding tests

---

website/cue/reference/remap/errors/305_divide_by_zero_error.cue

As far as I can tell, VRL uses "null", not "nil", so this example is not correct. On the errors page, a bit down from the fixed example, you can see `null` used: https://vector.dev/docs/reference/vrl/errors/#handling 👍

docs(remap transform): Fix example syntax

---

changelog.d/defer-log-schema-defaults.fix.md
src/app.rs
src/config/mod.rs
src/config/unit_test/mod.rs
src/sources/docker_logs/mod.rs
src/sources/file.rs
src/sources/internal_logs.rs
src/sources/internal_metrics.rs
src/sources/socket/mod.rs
src/sources/socket/tcp.rs
src/sources/socket/udp.rs
src/validate.rs
website/cue/reference/components/sources/base/docker_logs.cue
website/cue/reference/components/sources/base/file.cue
website/cue/reference/components/sources/base/internal_logs.cue
website/cue/reference/components/sources/base/internal_metrics.cue
website/cue/reference/components/sources/base/socket.cue

Closes: https://github.com/vectordotdev/vector/issues/20974
Reverts https://github.com/vectordotdev/vector/pull/17759 and solves the issue fixed by that PR by, instead of deserializing configuration twice, to set the global `log_schema`, defer fetching values from the `log_schema` until _after_ deserialization (previously some config structs would attempt to fetch during deserialization, but the `log_schema` may not have been deserialized by that point).
Attempting to pull from `log_schema` during deserialization is an easy bug to reintroduce, but I don't see an easy way to prohibit it.
I think it is easiest to review the first two commits independently.

fix(config): Avoid parsing configuration files without interpolating secrets

---

changelog.d/20996_recursive_config_watcher.fix.md
src/config/watcher.rs

Close #20547, this problem is that the watcher doesn't watch dir recursively.
This easily changes the watcher to watch dir recursively. While this may not be the best solution, considering that `config::watcher::spawn_thread` is currently only used for watching config. IMHO, it seems intuitive to watch paths recursively.
Please let me know if you have any concerns about potential implications for users to upgrade the version.

fix(config): Make config watcher recursive.

---

changelog.d/README.md

Including: 
1. reflecting accurate release file handling: the information seems stale.
2. removing `heading-ids`: GitHub doesn't support [heading-ids](https://www.markdownguide.org/extended-syntax/#heading-ids)

docs(external docs): Update ChangLog doc

---

lib/vector-tap/src/lib.rs

A small improvement to error handling.

chore(tap): surface send error

---

changelog.d/21036_kafka_sink_error_status.enhancement.md
src/sinks/kafka/service.rs

currently all kafka errors result it a "Rejected" event, which for the HTTP sink returns a 400 to the user.
however most errors should be "Errored", which implies an error happened and not a bad event that can't be sent to the sink
I do wonder if the real issue is that driver.rs defaults to Rejected state on error, and perhaps that should be changed to Errored (here: https://github.com/vectordotdev/vector/blob/16d2300bd8def42248e49e42643c8c1a604835c8/lib/vector-stream/src/driver.rs#L209) - but that is a major and more risky change

enhancement(kafka sink): update service to set Errored status on events

---

Cargo.lock
Cargo.toml

chore(deps): Update fork of tokio-util to 0.7.11 (latest)

---

lib/vector-core/src/event/metadata.rs

The labels changed downstream, so we need to use the correct ones. This only applies to the v1 series endpoint.

fix(metrics): use correct series payload origin labels

---

src/config/loading/mod.rs
src/config/loading/secret.rs
src/config/secret.rs
src/config/unit_test/mod.rs
src/secrets/aws_secrets_manager.rs
src/secrets/exec.rs
src/secrets/test.rs

Since the caller was async no need to have the nested functions be sync.
I spent an hour or so trying to keep `SecretBackendLoader#retrieve` in a functional processing style, but gave up and went for the simpler approach of iterating and mutating.

chore(config): Refactor secrets loading to avoid use of futures::executor::block_on

---

.github/dependabot.yml

Ran into issue in https://github.com/vectordotdev/vector/pull/21069 because they weren't updated together.

chore(deps): Group dependabot tower updates

---

changelog.d/file-sources-exclude-patterns-not-match-some-files.fix.md
src/sources/file.rs

File source include and exclude pattern not work in the same way.
For example, suppose include pattern is `a//b/*.log.*` and exclude pattern is `a//b/test.log.*`I have some files a/b/1.log and a/b/test.log, a/b/1.log can match include pattern but a/b/test.log can not match exclude pattern. 
This is because include and exclude use different ways to match file and multi slashes in pattern makes this happen. The change of is commit is include and exclude both use glob::glob_with to match files.

fix(file sources): exclude pattern with multi slashes can not match some files

---

lib/codecs/src/decoding/framing/character_delimited.rs
lib/codecs/src/encoding/framing/character_delimited.rs
scripts/generate-component-docs.rb
website/cue/reference/components/sinks/base/aws_s3.cue
website/cue/reference/components/sinks/base/azure_blob.cue
website/cue/reference/components/sinks/base/console.cue
website/cue/reference/components/sinks/base/file.cue
website/cue/reference/components/sinks/base/gcp_cloud_storage.cue
website/cue/reference/components/sinks/base/http.cue
website/cue/reference/components/sinks/base/socket.cue
website/cue/reference/components/sinks/base/webhdfs.cue
website/cue/reference/components/sources/base/amqp.cue
website/cue/reference/components/sources/base/aws_kinesis_firehose.cue
website/cue/reference/components/sources/base/aws_s3.cue
website/cue/reference/components/sources/base/aws_sqs.cue
website/cue/reference/components/sources/base/datadog_agent.cue
website/cue/reference/components/sources/base/demo_logs.cue
website/cue/reference/components/sources/base/exec.cue
website/cue/reference/components/sources/base/file_descriptor.cue
website/cue/reference/components/sources/base/gcp_pubsub.cue
website/cue/reference/components/sources/base/heroku_logs.cue
website/cue/reference/components/sources/base/http.cue
website/cue/reference/components/sources/base/http_client.cue
website/cue/reference/components/sources/base/http_server.cue
website/cue/reference/components/sources/base/kafka.cue
website/cue/reference/components/sources/base/nats.cue
website/cue/reference/components/sources/base/pulsar.cue
website/cue/reference/components/sources/base/redis.cue
website/cue/reference/components/sources/base/socket.cue
website/cue/reference/components/sources/base/stdin.cue

Applies same fix from
https://github.com/vectordotdev/vector/commit/5a10aa2b0556563d11244b04829a72d86a8e338b with an additional change to handle char config options that lack a default.
Fixes: #21121

fix(docs, codecs): Correctly render character delimiter as a char in the docs

---

.github/actions/spelling/expect.txt
Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
changelog.d/21103_kafka_sink_oidc_authentication.enhancement.md

Currently OIDC for Kafka does not work due to not having the required libraries to run:
`Configuration error. error=Sink "kafka": creating kafka producer failed: Client config error: Configuration property "sasl.oauthbearer.client.secret" not supported in this build: OAuth/OIDC depends on libcurl and OpenSSL which were not available at build time sasl.oauthbearer.client.secret`
The fix is to add additional features (c-make and curl) to the Cargo.toml to resolve the error.

enhancement(kafka sink): Allow OIDC usage for Kafka

---

changelog.d/21129_suppress_warnings_for_kafka_sink.fix.md
src/sinks/kafka/config.rs
src/sinks/kafka/sink.rs
src/sinks/kafka/tests.rs

Use `rdkafka::client::Client` instead of Consumer in Kafka sink healthcheck
Discussed in https://github.com/vectordotdev/vector/discussions/20510

fix(kafka sink): Use rdkafka::client::Client instead of Consumer

---

.github/workflows/regression.yml

I've been seeing some timeouts sporadically.

chore(ci): Bump regression workflow timeout to 60 minutes

---

scripts/integration/aws/compose.yaml
scripts/integration/aws/test.yaml
src/sinks/aws_cloudwatch_logs/integration_tests.rs

Now that localstack supports CloudWatch Logs as a service.

chore(ci): Swap out mockwatchlogs for localstack

---

changelog.d/21141_fix_crash_when_handling_metrics.fix.md
src/sources/amqp.rs

amqp source crashes when handling metrics, this patch fixes the problem.
Here is my configuration to trigger the problem:
```
schema:
log_namespace: true
api:
enabled: true
sources:
my_source_id:
type: amqp
connection_string: amqp://guest:guest@127.0.0.1:5672/%2f?timeout=10
queue: "hello"
decoding:
codec: "native"
sinks:
...
...
```
And the crash log:
```
Aug 22 14:32:13 hostname vector[2541178]: 2024-08-22T06:32:13.882811Z  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=http://127.0.0.1:8686/playground graphql=http://127.0.0.1:8686/graphql
Aug 22 14:32:13 hostname vector[2541178]: thread 'vector-worker' panicked at lib/vector-core/src/event/mod.rs:124:18:
Aug 22 14:32:13 hostname vector[2541178]: Failed type coercion, Metric(Metric { ... }) is …
```

fix(amqp source): fix crash when handling metrics

---

lib/vector-vrl/web-playground/public/index.css
lib/vector-vrl/web-playground/public/index.html

- Removes conflicting overflow settings that would create multiple scroll bars
- Removes white background from input box that is already created by monaco editor to prevent disguising scrollbar issues
- Added additional padding at largest screen size to keep editors within window height
- Removed overflow-x: hidden hack to prevent hiding confusing scroll behavior rather than fixing root issue

fix(playground): removes conflicting overflow settings creating multiple scrollbars

---

lib/vector-config/src/external/vrl.rs
src/conditions/datadog_search.rs

The `datadog_search` condition previously was configured with a generic string, which would accept any text. When that condition was built, it would then parse that search string into a query data structure. Since that query data structure now supports deserialization directly, we can use that as the configuration type and skip the extra parse step.
This should not change any user facing behavior except for the exact wording of the error message for invalid query strings.

chore(config): Configure `datadog_search` condition directly

---

.github/workflows/ci-review-trigger.yml

I believe this check used to exist because comments can be left on PRs or Issues, but since we use reviews now, only PRs should trigger.

chore(ci): Fix review workflow trigger

---

.github/workflows/regression.yml

We recently discovered in https://github.com/vectordotdev/vector/pull/21074 , that PRs which regenerate the fixture files for codec tests (which results in a 💩  ton of file changes) , breaks a check in this workflow due to
```
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/vector/vector'. Argument list too long
```
hit on the `filter` job.
We should ignore that test data dir anyway and hopefully it addresses that issue.

chore(ci): add codec test data dir to regression workflow ignore filter

---

.github/workflows/regression.yml

Clone whole repository. Also use `origin/master` since a local branch may not be created.

chore(ci): Fix finding of merge-base for regression workflow

---

changelog.d/21201_fields_iter.fix.md
lib/vector-core/src/event/test/mod.rs
lib/vector-core/src/event/util/log/all_fields.rs
src/transforms/reduce/transform.rs

Closes: #21165
Related PR: https://github.com/vectordotdev/vector/pull/21067.
* [Path segments](https://vector.dev/docs/reference/vrl/expressions/#path) which contain special characters need to be quoted. 
* The fields iterator used to only escape the `.` character. Now it detects if a path segment needs to be quoted.
* This is a more generic fix compared to the ad-hoc `quote_invalid_paths` function. A side benefit, it that this PR paves the way for https://github.com/vectordotdev/vector/issues/21077.
Added/enhanced unit tests.
```
transforms:
reduce_scalyr:
type: reduce
inputs:
- my_input
group_by:
- session
expire_after_ms: 2000
max_events: 500
merge_strategies:
events: array
tests:
- name: map_reduce_scalyr.no_sev
inputs:
- type: vrl
insert_at: reduce_scalyr
source: |
. = {
"events": { …
```

fix(reduce transform): surround invalid path segments with quotes

---

Cargo.lock
Cargo.toml

chore(deps): Bump VRL to 0.18.0

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/service-headless.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

chore(releasing): Bump manifests to v0.36.0 of the chart

---

lib/vector-core/proto/event.proto
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/proto.rs

https://github.com/vectordotdev/vector/pull/21074 added a new field `source_event_id` which uniquely identifies an event as it passes through different components. 
Initially made the assumption that `source_event_id` will always be present in proto, and if it is not present we should log an error. However, did not account for the cases such as when the source is a previous version of vector [#21252](https://github.com/vectordotdev/vector/issues/21252), resulting in a noisy error logs. Removing this log as well as making `source_event_id` Optional in `EventMetadata`

fix(proto): Remove error log when source_event_id is not present

---

website/content/en/docs/reference/configuration/sinks/greptimedb_metrics.md
website/content/en/docs/reference/configuration/sources/static_metrics.md
website/cue/reference.cue
website/cue/reference/components.cue
website/cue/reference/components/sinks/greptimedb_logs.cue
website/cue/reference/components/sinks/greptimedb_metrics.cue
website/cue/reference/components/sources/static_metrics.cue

The new `static_metrics` source and `greptimdb_logs` sink were not correctly documented. Each commit can be reviewed separately.

docs(releasing): Fix docs for new components in v0.41.0

---

Cargo.lock
Cargo.toml
lib/vector-common/Cargo.toml
lib/vector-config/Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-vrl/tests/Cargo.toml
src/conditions/datadog_search.rs

This PR:
* updates `chrono-tz` (requires VRL version update)
* updates the code to use the latest `Filter` trait

chore(deps): update to latest VRL sha

---

Cargo.lock
Cargo.toml
distribution/install.sh
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/proto.rs
website/content/en/releases/0.41.1.md
website/cue/reference/releases/0.41.0.cue
website/cue/reference/releases/0.41.1.cue
website/cue/reference/versions.cue

Checklist: https://github.com/vectordotdev/vector/issues/21263

chore(releasing): Prepare v0.41.1 release

---

website/cue/reference/remap/functions/parse_influxdb.cue

docs(vrl stdlib): Fix whitespace for `parse_influxdb` notice

---

benches/languages.rs
lib/vector-tap/src/controller.rs

chore: fix symbol error

---

changelog.d/21313-new-relic-logs-attributes.fix.md
src/sinks/new_relic/mod.rs
src/sinks/new_relic/model.rs
src/sinks/new_relic/tests.rs

The New Relic log API specifies that all attributes other than `message` and `timestamp` should go into an `attributes` field, which may contain any JSON object data except for arrays. This change reworks the logs API model to move all attributes from the log event into this attributes field as well as using structures to encode fields with fixed names instead of using dynamic maps.
The tests have also been updated to compare the overall structure of the output data model so as to ensure that the resulting encoding generated by `serde` matches what we is specified in the New Relic API documentation.

fix(new_relic sink): Put log API attributes in separate structure

---

website/layouts/partials/data.html

Make sure HTML characters are escaped or marked as escaped.
Before:
https://vector.dev/docs/reference/vrl/functions/#remove
After:
https://jszwedko-website-fix-vrl-arguments-syntax.d1a7j77663uxsc.amplifyapp.com/docs/reference/vrl/functions/#remove

docs(vrl): Fix syntax for function arguments

---

changelog.d/21278-expose_mqtt_retain.enhancement.md
src/sinks/mqtt/config.rs
src/sinks/mqtt/service.rs
src/sinks/mqtt/sink.rs
website/cue/reference/components/sinks/base/mqtt.cue

Resolves #21278
Expose a boolean config flag named `retain` that gets passed to the MQTT client's `publish` function to tell the server to retain the messages.

feat(mqtt sink): expose retain config flag

---

website/content/en/docs/reference/vrl/_index.md

This update addresses the incorrect usage of the `to_timestamp` function in the provided VRL code example. To ensure proper parsing of the timestamp format, I have included the `parse_timestamp` function, based on a more accurate example that effectively handles timestamp conversion. The original code attempted to convert a timestamp using a non-existent function, which could lead to confusion for users.
Playground Link: https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiLiA9IHBhcnNlX2pzb24hKHN0cmluZyEoLm1lc3NhZ2UpKVxuXG4ucGFyc2VkX3RpbWVzdGFtcCA9IHBhcnNlX3RpbWVzdGFtcCEoLnRpbWVzdGFtcCwgZm9ybWF0OiBcIiVZLSVtLSVkVCVIOiVNOiVTLiVmWlwiKVxuXG5pZiBpc190aW1lc3RhbXAoLnBhcnNlZF90aW1lc3RhbXApIHtcbiAgLnRpbWVzdGFtcCA9IHRvX3VuaXhfdGltZXN0YW1wKC5wYXJzZWRfdGltZXN0YW1wKVxufSBlbHNlIHtcbiAgLnRpbWVzdGFtcCA9IHRvX …

docs(vrl): fix vrl code example

---

Cargo.lock
Cargo.toml
changelog.d/aws-rt-tokio.fix.md

We missed it for the aws-config crate which leads to a panic when the `EcsContainer` credentials provider is used. Some of the other additions are redundant since they just enable the feature on subpackages that we already enabled the feature on (like `aws-smithy-runtime`), but adding for completeness.
Ref: https://github.com/vectordotdev/vector/issues/20662#issuecomment-2368363337

fix(aws provider): Enable rt-tokio on all applicable AWS crates

---

changelog.d/21331-new-greptimedb-metric-option.enhancement.md
scripts/integration/greptimedb/test.yaml
src/sinks/greptimedb/metrics/config.rs
src/sinks/greptimedb/metrics/integration_tests.rs
src/sinks/greptimedb/metrics/request.rs
src/sinks/greptimedb/metrics/request_builder.rs
src/sinks/greptimedb/metrics/sink.rs
website/cue/reference/components/sinks/base/greptimedb.cue
website/cue/reference/components/sinks/base/greptimedb_metrics.cue

This patch adds an option `new_naming` to use `greptime_value` and `greptime_timestamp` for value and timestamp fields, in order to keep consistency with greptime's convention. 
To maintain backward-compatibility, the new option is `false` by default. It will not affect any previous user.

enhancement(greptimedb): add optional new_naming strategy for greptimedb sink

---

changelog.d/21383-nats-subscriber-capacity.fix.md
src/sources/nats.rs
website/cue/reference/components/sources/base/nats.cue

This PR updates the NATS source to use the same `subscriber_capacity` as the upstream async_nats library.
Closes https://github.com/vectordotdev/vector/issues/21383

fix(nats source): use correct default value for subscriber_capacity

---

changelog.d/21385-nats-source-multiple-url.enhancement.md
src/sources/nats.rs
website/cue/reference/components/sources/base/nats.cue

This PR adds support for specifying multiple URLs in the NATS source.
I decided to take the same [approach](https://docs.nats.io/running-a-nats-service/clients#nats-urls) as core NATS, which is to pass a string containing comma separated URLS, which feels slightly more idiomatic than attempting to support both an optional string/vector input.
Closes https://github.com/vectordotdev/vector/issues/21385

enhancement(nats source): add support for multiple URLs

---

Cargo.lock

It seems like it fell out of sync due to (silently) conflicting dependabot PRs.

chore(deps): Regenerate Cargo.lock

---

changelog.d/21137_configurable_gcs_sink_endpoint.enhancement.md
src/sinks/gcp/cloud_storage.rs
src/sinks/gcs_common/config.rs
website/cue/reference/components/sinks/base/gcp_cloud_storage.cue

Closes https://github.com/vectordotdev/vector/issues/21137
Adds an `endpoint` config parameter, following the same pattern as other sources/sinks.

enhancement(gcp_cloud_storage): Make API endpoint configurable

---

.github/workflows/install-sh.yml
Makefile

We no longer host install.sh in AWS S3 but instead reference it from GitHub. This change happened a while ago, but we apparently never updated the CI wrokflow; we just never noticed since we haven't changed the script since then.

chore(ci): Update install.sh workflow to not publish to AWS

---

distribution/install.sh

`etc/` doesn't exist in the MacOS packages. In the Linux packages it houses the SystemD files.
Closes: https://github.com/vectordotdev/vector/issues/21400

fix(releasing): Fix install.sh handling of new directory structure on MacOS

---

changelog.d/21423-optional-namespace-log-to-metric.fix.md
src/transforms/log_to_metric.rs

Closes #21423
Now this config
```toml
[sources.sample]
type = "demo_logs"
lines = ["weather,location=us-midwest temperature=82 1465839830100400200"]
format = "shuffle"
[transforms.influx]
type = "remap"
inputs = ["sample"]
source = """
. = parse_influxdb!(.message)
"""
[transforms.log_to_metric]
type = "log_to_metric"
inputs = ["influx"]
all_metrics = true
metrics = []
[sinks.console]
type = "console"
inputs = ["log_to_metric"]
encoding.codec = "native_json"
```
Produces the following output:
```console
2024-10-05T09:19:29.994825Z  INFO vector::app: Log level is enabled. level="info"
2024-10-05T09:19:29.996361Z  INFO vector::app: Loading configs. paths=["config.toml"]
2024-10-05T09:19:30.009987Z  INFO vector::topology::running: Running healthchecks.
2024-10-05T09:19:30.010365Z  INFO …
```

fix(transforms): optional metric namespace in `log_to_metric` transform

---

src/transforms/log_to_metric.rs

Found this unused clone while working on #21429. Didn't add this in that PR because it seemed unrelated to me. If you want me to include this small change in #21429 I'll do it without problem.
I think a changelog entry is not necessary for this internal fix.

enhancement(transforms): redundant clone in `log_to_metric` transform

---

website/content/en/docs/setup/installation/platforms/kubernetes.md

github.com/vectordotdev/vector/distribution/kubernetes/vector-agent?ref=master does not exist, updated to github.com/vectordotdev/vector/tree/master/distribution/kubernetes/vector-agent

* doc fix, fixing a ref path which goes to 404

---

website/config.toml
website/content/en/docs/about/observability-pipelines.md
website/content/en/docs/about/vector.md

This isn't adding much and is/are is confusing for Observability Pipelines.
Supersedes: #21444

docs: Remove "What is" from about pages

---

changelog.d/21455-socket-sink-graceful-reload.fix.md
src/lib.rs
src/sinks/util/tcp.rs

fixes: #15952
fixes: #14515 
It looks like a [PR](https://github.com/vectordotdev/vector/pull/12755) introduced a regression while making changes to the tcp socket sink to emit internal telemetry in accordance with the component specification.
This introduced a bug where the `TcpSink` crashes Vector during config reloads, while events are flowing through the topology.
The fix is to restore the behavior of peeking onto the stream before attempting to access the next event.
To test this, just use the `socket` sink in `tcp` mode, and watch the vector config. Send events continuously. Change the name of the input to the sink. In the before case, it crashes. After the fix, it does not.
```
RUST_BACKTRACE=1 VECTOR_LOG=info ./target/debug/vector --config ../vector_configs/http_server_socket.yaml …
```

fix(socket sink): gracefully shutdown on reload when stream is terminated

---

website/cue/reference/remap/functions/replace.cue

Closes: https://github.com/vectordotdev/vector/issues/21462

docs(vrl stdlib): Document regex replacement group escaping

---

.github/workflows/changelog.yaml
scripts/check_changelog_fragments.sh

Now an author line is always required. Removed the Vector team check to simplify validation.

chore(ci): simplify chanelog validation to always check for authors

---

Cargo.lock
changelog.d/21404-opentelemetry-logs-instrumentation-scope.feature.md
lib/opentelemetry-proto/src/convert.rs
src/sources/opentelemetry/tests.rs
website/cue/reference/components/sources/opentelemetry.cue

This introduces an optional `scope` object to logs, representing the InstrumentationScope object from the OTel protocol. This object may include:
* `name` (if nonempty)
* `version` (if nonempty)
* `attributes` (if nonempty)
* `dropped_attributes_count` (if nonzero)
This is particularly important for transmitting the logger name.
This PR only addresses instrumentation scope for logs.
resolves #21404

feat(opentelemetry source): add instrumentation scope to logs

---

.github/actions/spelling/allow.txt
.github/actions/spelling/excludes.txt
.github/actions/spelling/patterns.txt
scripts/environment/bootstrap-windows-2019.ps1

This is an attempt to reduce flakes such as [this one](https://github.com/vectordotdev/vector/actions/runs/11247975194/job/31272362725#step:3:67). An alternative that I considered was a generic retry script but this change is easier.

chore(ci): enable http retries for choco installations

---

Cargo.lock
LICENSE-3rdparty.csv
lib/vector-config/Cargo.toml
lib/vector-core/Cargo.toml

There has been some updates on `cidr-utils` used by `no-proxy` and a security fix on `async-graphql` (not used by vector, the feature is disabled).

chore(deps): bump no-proxy from 0.3.4 to 0.3.5

---

changelog.d/21443-serialize-loki-structured-metadata-to-json.fix.md
src/sinks/loki/event.rs
src/sinks/loki/tests.rs

fixes: #21443
Structured metadata wasn't added to the serializer implementation, which likely caused it not to be sent to Loki. I added the serialization.
Considering the `Encoder<Vec<LokiRecord>> for LokiBatchEncoder` is not unit tested anywhere, thus I tested it by trying to (JSON) serialize the event and see if the structured metadata is (correctly) in there.

fix(loki): serialize the structured metadata to JSON

---

lib/vector-core/src/event/test/size_of.rs

The strings used in this test are actually object map keys, which must have the type `KeyString`. This works now when `KeyString` is a simple wrapping of `String` but breaks if the types are different.

chore(tests): Fix event `size_of` test

---

website/cue/reference/components/sinks.cue
website/cue/reference/components/sinks/gcp_cloud_storage.cue

This PR updates the retry policy for the GCS sink documentation to include retries for the HTTP error 401 and 408 error codes, which are currently undocumented.

docs(gcs sink): add 401 and 408 under retry policy

---

.github/workflows/regression.yml

Bump to latest SMP to bring in analysis improvements.

chore(deps): Bump smp to 0.18.0

---

.github/ISSUE_TEMPLATE/minor-release.md

Noticed when pairing on the release process with @pront

chore(releasing): Update minor-release template with a few tweaks

---

.github/dependabot.yml
.github/workflows/regression.yml

* PR with the `"ci-condition: skip-regression"` label will skip the regression detector suite 
* PRs created by [dependabot[bot]](https://github.com/vectordotdev/vector/commits?author=dependabot%5Bbot%5D) will always have this label.
* What about regressions introduced by crate bumps? 
* To mitigate this risk, we will now run the suite weekly. This will allows us to investigate any regressions before we release a new Vector versions.
* Also, we can keep on eye for changelogs describing performance changes and trigger the regression suite on those PRs with review comments. 
In the future, we can also consider making this only run on schedule (e.g. nightly). But let's see how this smaller change works out.
Check what happens when:
- A new commit is pushed
- A `/ci-run-regression` review …

chore(ci): skip regression checks for PRs with the `ci-condition: skip-regression` label

---

.github/dependabot.yml
.github/workflows/regression.yml

The previous idea to use a PR label is not feasible, see [comment](https://github.com/vectordotdev/vector/pull/21540#issuecomment-2420299282).

chore(ci): revert recent changes to the regression workflow

---

.github/workflows/publish.yml

Ref: https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/
As part of this, I changed the MacOS package verification to test on all available runner versions.

chore(deps): Handle recent GitHub Actions deprecations

---

changelog.d/21245_pulsar_sink_connection_retry_options.enhancement.md
src/sinks/pulsar/config.rs
website/cue/reference/components/sinks/base/pulsar.cue

I want to be able to customize the connection retry options for the Pulsar client. This fixes https://github.com/vectordotdev/vector/issues/21242

enhancement(components): Add customizable connection retry options for Pulsar client in Pulsar sink

---

changelog.d/20404-log-redundant-timestamp.fix.md
src/sources/exec/mod.rs
src/sources/http_server.rs

When log namespacing is enabled, `exec` and `http_server` sources include a redundant `timestamp` field when decoding is enabled. When decoding is not enabled, they put the content under a _"message"_ key, instead of directly in the root object.
In the case of `exec`, the issue was caused by passing a hardcoded `LogNamespace` value to the decoder. Fixed by passing the parsed value.
In the case of `http_server`, the decoder ignored the global `LogNamespace`. Fixed by passing the correctly parsed value to the decoder.
Fixes #20404.

fix(sources): fix unexpected timestamp field

---

.github/workflows/changelog.yaml
.github/workflows/changes.yml
.github/workflows/ci-integration-review.yml
.github/workflows/cli.yml
.github/workflows/compilation-timings.yml
.github/workflows/component_features.yml
.github/workflows/cross.yml
.github/workflows/deny.yml
.github/workflows/e2e.yml
.github/workflows/environment.yml
.github/workflows/gardener_remove_waiting_author.yml
.github/workflows/install-sh.yml
.github/workflows/integration-test.yml
.github/workflows/k8s_e2e.yml
.github/workflows/misc.yml
.github/workflows/msrv.yml
.github/workflows/protobuf.yml
.github/workflows/publish.yml
.github/workflows/regression.yml
.github/workflows/unit_mac.yml
.github/workflows/unit_windows.yml

The `deb-verify` and `rpm-verify` jobs still require an older Node version.

chore(ci): update actions/checkout to v4

---

website/package.json
website/yarn.lock

Bumps `typesense-sync` to v1.0.4.

chore: upgrade `typesense-sync` package

---

changelog.d/21557_remove_pubsub_log_only_restriction.fix.md
src/sinks/gcp/pubsub.rs

Inspired by https://github.com/vectordotdev/vector/pull/18074

fix(sinks/gcp/pubsub.rs): remove pubsub log only restriction

---

.github/workflows/build_preview_sites.yml
.github/workflows/preview_site_trigger.yml

- Adds conditional to the deploy jobs to only run if the trigger workflow has a status of `success`
Context:
https://github.com/orgs/community/discussions/26238
https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run

fix(ci): Prevent workflow from triggering unless previous workflow succeeds

---

.github/workflows/regression.yml

* The outer job `submit-job` had a timeout less than the `Await job` step. 
* Confirmed with the SMP team that these timeouts can be set to the same value. This should make the workflow more maintainable.

chore(ci): set regression workflow timeouts to 70 mins

---

.github/workflows/regression_v2.yml

This PR introduces a new regression detection workflow, quite similar to the [existing one](https://github.com/vectordotdev/vector/blob/master/.github/workflows/regression.yml). However, there are a few notable changes here, this workflow:
* Runs on a nightly schedule.
* Supports inputs, a base SHA and a comparison SHA (this will help when bisecting commits).
* Completely removes all logic related to PRs. The expectation is to examine the nightly results in the ops channel or run ad-hoc workflows.
* I tested the input resolution and validation on a fork. 
* However, this needs more E2E testing. 
* To avoid disruptions, I am creating this under a different name with the intention to replace the existing workflow.

feat(ci): regression detection overhaul

---

.github/workflows/regression_v2.yml
regression/Dockerfile

* There is one real fix here, the `should-run-gate` job requires a step. 
* Tested here and the workflow runs properly: https://github.com/vectordotdev/vector/actions/runs/11482190851
* the failure is due to a known issue
* Also fixed all deprecation warnings for this new workflow.

chore(ci): regression detection v2 followups

---

.github/dependabot.yml

Patch updates, per semvar, have a low risk of incompatibility and so I think they can all be grouped together. The changelogs should still be reviewed when merging, but this should reduce CI costs.
I was going to add `minor` here too, but for dependencies pre-1.0, minor updates can be breaking. There is a dependabot issue asking for this behavior to change: https://github.com/dependabot/dependabot-core/issues/9647. Also some discussion about this on: https://github.com/dependabot/dependabot-core/issues/7795

chore(ci): Group together patch updates with dependabot

---

changelog.d/chronicle_compression_support.enhancement.md
src/sinks/gcp_chronicle/chronicle_unstructured.rs
src/sinks/gcp_chronicle/compression.rs
src/sinks/gcp_chronicle/mod.rs
src/sinks/util/buffer/compression.rs
website/cue/reference/components/sinks/base/gcp_chronicle_unstructured.cue

Google Chronicle's ingestion API supports use of GZip compression - https://cloud.google.com/chronicle/docs/reference/ingestion-api#frequently_asked_questions

feat(chronicle-sink): add support for compression to Google Chronicle sink

---

.github/actions/spelling/expect.txt
Cargo.lock
changelog.d/gelf-timestamp-nanoseconds.fix.md
lib/codecs/Cargo.toml
lib/codecs/src/decoding/format/gelf.rs

Fixes: https://github.com/vectordotdev/vector/issues/21610

fix(codecs): Fix gelf deserialization of subsecond timestamps

---

website/Makefile
website/package.json
website/scripts/typesense-sync.ts
website/yarn.lock

bump `typesense-sync` to get improved log metadata
build & deploy was successful: https://us-east-1.console.aws.amazon.com/amplify/apps/d1a7j77663uxsc/branches/brian.deutsch%2Fwebsite-bump-ts-package/deployments
recent log has expanded metadata (env, collection): https://dd-corpsite.datadoghq.com/logs?query=service%3Atypesense-sync&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZLE1GwaP-fUqwAAAAAAAAAYAAAAAEFaTEUxR3dyQUFEaXEyOVI4RG1IcFFBQQAAACQAAAAAMDE5MmM0ZDUtYzI2NC00ZjA2LTgwNzUtZWU1MmY4MTQ4Yzdl&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1729878639524&to_ts=1729879539524&live=true

chore(javascript website): bump ts package

---

changelog.d/18521-kubernetes-windows-metadata.enhancement.md
src/sources/kubernetes_logs/path_helpers.rs
src/sources/kubernetes_logs/pod_metadata_annotator.rs

This implements the changes from #19799, including the suggested fix for the failing test. I've been running the change with the path separator successfully for 5 months on Windows.
This resolves #18521.

enhancement(kubernetes_logs source): support scraping metadata from Kubernetes log files on Windows

---

src/sinks/azure_blob/config.rs
website/cue/reference/components/sinks/base/azure_blob.cue

Update Azure blob storage sink connection_string documentation to show SAS is supported
Closes #15394

docs(azure_blob sink): Clarify SAS connection_string support 

---

docs/DOCUMENTING.md
vdev/src/commands/check/component_docs.rs

The `CI=true` flag is a common gotcha. We can clean up further but this should help future contributors.

fix(external docs): add CI flag and use cue.sh

---

.github/actions/spelling/expect.txt
website/cue/reference/remap/functions/decrypt.cue
website/cue/reference/remap/functions/encrypt.cue

Update docs for new AES-SIV encryption/decryption types available in latest VRL.
Not tested.
https://github.com/vectordotdev/vrl/pull/1101

docs(vrl): Update docs for new AES-SIV encryption/decryption types available in latest VRL.

---

.github/workflows/publish.yml
changelog.d/21639_ubuntu-16.breaking.md

The Nightly workflow is broken because Ubuntu 18.04 is on an older glibc version.
```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
``` 
In this PR, I am reverting the changes to `deb-verify` and `rpm-verify`. There are a number of ways we can fix this going forward, but it's not time critical to do these updates.
Manually ran the workflow (TODO add link here).
https://github.com/vectordotdev/vector/pull/21639

fix(ci): deb-verify cannot use actions/checkout@v4

---

.github/actions/spelling/expect.txt
Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
lib/vector-core/Cargo.toml
lib/vector-core/src/event/lua/event.rs
lib/vector-core/src/event/lua/log.rs
lib/vector-core/src/event/lua/metric.rs
lib/vector-core/src/event/lua/util.rs
src/internal_events/lua.rs
src/transforms/lua/v1/mod.rs
src/transforms/lua/v2/mod.rs

These need to be updated together due to breaking changes.
n/a
Closes: https://github.com/vectordotdev/vector/pull/21647

chore(deps): Update VRL to c69a52e67 and mlua to 0.10.0

---

.github/workflows/k8s_e2e.yml

We seem to be hitting cases where the workflow dies because it runs out of space after the change to use the free runners in #19683 . Example: https://github.com/vectordotdev/vector/actions/runs/11710738799/job/32617708471
-

chore(ci): Clear space at the start of the k8s e2e workflow

---

Cargo.lock
Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-core/src/config/telemetry.rs

Fixes race condition in tests which require access to the global telemetry state.
* `cargo test`
* `cargo vdev test`
closes: https://github.com/vectordotdev/vector/issues/21488

fix(tests): make the `TELEMETRY` singleton thread local for tests

---

changelog.d/21743_add_ede_code_30.enhancement.md
lib/dnsmsg-parser/src/ede.rs

This adds EDE code 30 (Invalid Query Type), added in https://datatracker.ietf.org/doc/draft-ietf-dnsop-compact-denial-of-existence/04/ (which can also be seen in the EDE list -
https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#extended-dns-error-codes) to the list of known ede codes, which generates the purpose string.

enhancement(dnstap source): add EDE code 30 to known EDE codes

---

config/examples/wrapped_json.yaml

Fix the wrapped json example to work with the latest Vector version (v0.42.0). I was going to add tests here, but `vector validate --no-environment` doesn't execute VRL and so wouldn't have failed. See https://github.com/vectordotdev/vector/issues/15037
Ran `vector validate` locally.
- Closes https://github.com/vectordotdev/vector/issues/21741

docs(config): Update wrapped_json.yaml example

---

deny.toml

Vulnerable version is only used in dev dependencies. Will work on upgrading separately.
`cargo deny -L error check`
- Attempting to upgrade over here: https://github.com/vectordotdev/vector/pull/21757

chore(ci): Ignore RUSTSEC-2024-0336

---

website/cue/reference/components/kafka.cue

In the docs for the kafka source, the section about  `librdkafka` [here](https://vector.dev/docs/reference/configuration/sources/kafka/#librdkafka) currently only mentions the sink. This includes the source in the description since we also use it there -- see `rdkafka` import in the source [here](https://github.com/vectordotdev/vector/blob/master/src/sources/kafka.rs#L1550-L1559).
- ran `./website/scripts/cue.sh fmt` 
- `CI=true make check-docs` validated succesfully
- [n/a] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please …

docs(kafka source, kafka sink): include kafka source in `librdkafka` section

---

aqua/aqua.yaml
deny.toml
scripts/environment/prepare.sh

Upgrades cargo-deny to latest version, 0.16.1.
`cargo vdev check deny`

chore(deps): Upgrade cargo-deny to latest

---

website/cue/reference/remap/functions/decode_punycode.cue
website/cue/reference/remap/functions/encode_punycode.cue

This adds a note to `encode_punycode` and `decode_punycode` to inform users that it is meant to be used in IDN context and that passed values are handled like domain names. This is important because punycode by default doesn't use `xn--` prefix, but it is added in IDN context.
Related: https://github.com/vectordotdev/vrl/pull/1104

docs(vrl): document punycode as an IDN function

---

Cargo.lock

Manually ran `cargo update -p vrl` and committed the changes. The dependabot should do this automatically.

chore(deps): bump vrl

---

.github/workflows/custom_builds.yml
.github/workflows/nightly.yml
.github/workflows/publish.yml
.github/workflows/release.yml

Fixes workflow permission for publish

fix(ci): fix publish workflow permissions

---

website/cue/reference/configuration.cue

Currently log namespacing isn't supported when disk buffers are used per https://github.com/vectordotdev/vector/issues/18574.
n/a
Ref: https://github.com/vectordotdev/vector/issues/21578

docs(config): Document limitation of log namespacing with disk buffers

---

src/sinks/azure_blob/config.rs
src/sinks/gcp/cloud_storage.rs
website/cue/reference/components/sinks/base/azure_blob.cue
website/cue/reference/components/sinks/base/gcp_cloud_storage.cue

Copy note from AWS S3 sink about transparent decompression to other blob storage sinks since another user got tripped up by this for the Azure Blob Storage sink (https://github.com/vectordotdev/vector/issues/21795).
n/a
Ref: https://github.com/vectordotdev/vector/issues/21795

docs(azure_blob sink, gcp_cloud_storage sink): Note transparent decompression

---

changelog.d/21789_add_vector_hostname_env_variable.enhancement.md
src/lib.rs
website/cue/reference/cli.cue

By default, Vector uses the hostname returned by the gethostname. However, in cases when Vector is running in containers, it is meaningless because hostname is always the name of the container, e.g., the name of a pod in Kubernetes cluster.
This commit adds the way to override a hostname by using the env variable. In Kubernetes it can be used like this to see the name of a node where the Vector process is running (which is more meaningful).
```
env:
- name: VECTOR_HOSTNAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
```
Tested manually in the kubernetes cluster. …

feat(internal): Add VECTOR_HOSTNAME env variable

---

changelog.d/21889_support_compression_for_honeycomb_sink.enhancement.md
src/sinks/honeycomb/config.rs
src/sinks/honeycomb/request_builder.rs
src/sinks/honeycomb/service.rs
website/cue/reference/components/sinks/base/honeycomb.cue
website/cue/reference/components/sinks/honeycomb.cue

Support compression for the Honeycomb sink. The `zstd` format is enabled by default. 
Create a Honeycomb API key and configure compression for vector: 
```yaml
sources:
docker_logs:
type: docker_logs
include_labels:
- vector.enable=true
sinks:
honeycomb:
inputs:
- component: docker_logs
type: honeycomb
api_key: xxx
dataset: dataset-dev
compression: gzip
```

feat(honeycomb sink): Support compression

---

changelog.d/21704_file_sink_supports_encoding_input.feature.md
src/sinks/file/mod.rs
src/test_util/mod.rs

The file sink only supports [log event](https://github.com/vectordotdev/vector/blob/911156972f8d01ed030e5e4acc3eeebbfa396b80/src/sinks/file/mod.rs#L197) input. This PR changes it to support any input that the configured encoding supports.
I added single and multi-partition tests to the file sink tests module. I added a `log_` prefix to all the existing tests to disambiguate between the new `metric_` tests. I did not add a compression or reopening test for metrics input as it should be handled by the log tests.
The full test suite passes
```bash
nix develop nixpkgs-unstable#vector
cargo test 
....
test result: ok. 1623 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out; finished in 23.77s
Running tests/e2e/mod.rs (target/debug/deps/e2e-eab25220265d1d1d)
running 0 tests
test result: …
```

feat(file sink): supports input based on encoding type

---

.github/workflows/custom_builds.yml
.github/workflows/nightly.yml
.github/workflows/publish.yml
.github/workflows/release.yml

Fixes https://github.com/vectordotdev/vector/actions/runs/12143081309
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token

fix(ci): multiple workflows need 'contents: write' permissions

---

Cargo.lock

Fixes RUSTSEC-2024-0402
`cargo deny -L error check`

chore(deps): Bump hashbrown to 0.15.2

---

website/cue/reference/remap/syntax/expressions.cue

Add documentation for valid VRL syntax using newline and/or semicolons.
Verified the VRL syntax works in the VRL Playground [[share](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiIyBSZW1vdmUgc29tZSBmaWVsZHNcbmRlbCguZm9vKTsgLnRpbWVzdGFtcCA9IG5vdygpXG5cbiMgUGFyc2UgSFRUUCBzdGF0dXMgY29kZSBpbnRvIGxvY2FsIHZhcmlhYmxlXG5odHRwX3N0YXR1c19jb2RlID0gcGFyc2VfaW50ISguaHR0cF9zdGF0dXMpO1xuZGVsKC5odHRwX3N0YXR1cylcblxuIyBBZGQgc3RhdHVzXG5pZiBodHRwX3N0YXR1c19jb2RlID49IDIwMCAmJiBodHRwX3N0YXR1c19jb2RlIDw9IDI5OSB7XG4gICAgLnN0YXR1cyA9IFwic3VjY2Vzc1wiXG59IGVsc2Uge1xuICAgIC5zdGF0dXMgPSBcImVycm9yXCJcbn0iLCJldmVudCI6eyJtZXNzYWdlIjoiSGVsbG8gVlJMIiwiZm9vIjoiZGVsZXRlIG1lIiwiaHR0cF9zdGF0dXMiOiIyMDAifSwiaXNfanNvbmwiOmZhbHNlLCJlcnJvciI6bnVsbH0%3D)]
Create and test .cue file documentation:
```
➜  vector …
```

docs(vrl): add example syntax for valid expressions.

---

website/cue/reference/components/transforms/exclusive_route.cue
website/cue/reference/components/transforms/route.cue

Fixes the link to the new Exclusive Route in the Route transform, and vice versa.
e.g

docs(exclusive_route transform, route transform): fix links in route/exclusive route

---

Cargo.lock
Cargo.toml

Bump patched tokio-util to 0.7.13 courtesy of @Zettroke
Will rely on CI.

chore(deps): Bump patched tokio-util to 0.7.13

---

website/layouts/releases/single.html

For the new changelogs generated from changelog fragments, chores should be rendered too.
Addresses: https://github.com/vectordotdev/vector/issues/21988#issuecomment-2528544099
Running the website locally.

chore(website): Render chores for release changelog

---

changelog.d/21989-reduce-quote-invalid-path.fix.md
lib/vector-core/src/event/util/log/all_fields.rs
src/transforms/reduce/transform.rs

https://github.com/vectordotdev/vector/pull/21323 added unquoted iterators but it also made the other iterators return unquoted fields.
```
transforms:
transform0:
type: reduce
inputs:
- my_input
group_by:
- id
expire_after_ms: 2000
max_events: 500
merge_strategies:
foo: array
tests:
- name: map_transform0.space
inputs:
- type: vrl
insert_at: transform0
source: |
. = {
"a b": 1
}
- type: vrl
insert_at: transform0
source: |
. = {
"a b": 1
}
outputs:
- extract_from: transform0
conditions:
- type: vrl
source: |
assert_eq!(., {"a b": 2})
```
Also added a unit test to cover this. …

fix(reduce transform): enable quoting for invalid fields

---

changelog.d/21873-correctly-propagate-http-config-provider.fix.md
src/providers/http.rs

Copied from the body of the commit:
> Problem: The HTTP config provider has been failing to parse the provided TOML from its endpoint when polled. My best guess is that including the `?` on the end of the http provider load results in the TOML parser subtly exploding due to the aliased return type (`BuildResult`).
>
> It appears that this was broken in `8ed9ec24c1eba0b2191d7c1f24ec2a7540b5bebf`.
>
> See https://github.com/vectordotdev/vector/issues/21873 for the initial issue report.
>
> Solution: Correctly propagate the `ConfigBuilder` by not using the `?` operator. This appears to allow the TOML parser to correctly pick up on the return type.
> ...
I'm not entirely certain _why_ the TOML parser is choking when we use the sugar `?`. Best I can tell, is the generated match arms aren't …

fix(config): correctly propagate http config provider Result to caller

---

deny.toml

Ignore RUSTSEC-2024-0421 until we can upgrade direct dependencies to upgrade idna:
- mongodb (https://github.com/mongodb/mongo-rust-driver/blob/main/migration-3.0.md)
- hickory-proto (https://github.com/vectordotdev/vector/pull/21759/files)
`cargo deny -L error check`
https://github.com/vectordotdev/vector/pull/21996

chore(deps): Ignore RUSTSEC-2024-0421 temporarily

---

website/cue/reference/remap/functions/to_float.cue

No longer relevant since v0.43.1.
https://github.com/vectordotdev/vector/issues/21992

docs(external): remove obsolete note

---

.github/workflows/integration.yml

The comment here is invalid so I just deleted it. The commented integration test steps below should show as a marker that the humio tests are being skipped. I'm not sure how this slipped through the merge queue.
Will rely on CI.
- https://github.com/vectordotdev/vector/pull/22016

chore(ci): Fix integration test file syntax

---

website/layouts/partials/css.html
website/layouts/shortcodes/jump.html

- Updates 2 files so that the site can be built with the latest version of hugo: `vhugo v0.139.4+extended+withdeploy`
- Updates `website/layouts/partials/css.html` to use `hugo.IsSever`
- `site.IsServer` variable was deprecated in Hugo version 0.112.0
- Updates `website/layouts/shortcodes/jump.html` with the following:
- Added better path handling that works with both leading slash and no leading slash
- Improved error message to include the actual file path
- Added compatibility layer for page lookups
Locally and with a preview site
To test:
1. Pull …

chore(website): bump hugo to latest version

---

.github/workflows/semantic.yml
src/sinks/greptimedb/metrics/config.rs
website/cue/reference/components/sinks/base/greptimedb.cue
website/cue/reference/components/sinks/base/greptimedb_metrics.cue

This patch updates examples of `greptimedb_metrics`
- corrected example value of `gzip_compression`
- add example of `new_naming`
- removed redundant example of `endpoint`
N/A

chore(greptimedb_metrics sink): fix greptimedb examples

---

Cargo.lock
Cargo.toml
lib/codecs/Cargo.toml
lib/docs-renderer/Cargo.toml
lib/file-source/Cargo.toml
lib/loki-logproto/Cargo.toml
lib/prometheus-parser/Cargo.toml
lib/vector-api-client/Cargo.toml
lib/vector-buffers/Cargo.toml
lib/vector-common/Cargo.toml
lib/vector-config/Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-lib/Cargo.toml
lib/vector-tap/Cargo.toml
lib/vector-vrl/tests/Cargo.toml
lib/vector-vrl/web-playground/Cargo.toml
vdev/Cargo.toml

Guided by `cargo machete`
Ran all features workflow.

chore(deps): remove some unused deps

---

scripts/integration/humio/compose.yaml
scripts/integration/humio/test.yaml

The `humio/humio` image was archived. The `humio/humio-single-node-demo` seems to be the one to use now.
Will test using CI.

chore(dev): Switch to new humio image

---

changelog.d/22013-optional-clickhouse-skip_unknown_fields.breaking.md
src/sinks/clickhouse/config.rs
src/sinks/clickhouse/integration_tests.rs
src/sinks/clickhouse/service.rs
website/cue/reference/components/sinks/base/clickhouse.cue

Copied from the body of the commit:
> Problem: The Clickhouse sink's `skip_unknown_fields` doesn't follow the Clickhouse server default. It always sends a value for `skip_unknown_fields`; furthermore, there is also no way to _disable_ `skip_unknown_fields` setting a "strict" mode for Clickhouse. We really want to permit either a default value from the Clickhouse server, meaning we shouldn't specify `skip_unknown_fields` by default. Otherwise, if a user _wants_ to specify the strict mode for unknown fields, they should then pass either `true` or `false` for click house.
>
> Solution: Change the `skip_unknown_fields` value to be of an `Option<bool>` instead of just a `bool`. This permits using the defaults provided by the Clickhouse server and doesn't send the `skip_unknown_fields` value to …

fix(clickhouse sink)!: make `skip_unknown_fields` optional

---

Tiltfile
lib/vector-core/src/tls/incoming.rs
rust-toolchain.toml

Update Rust toolchain to 1.82.0. Surprisingly few clippy changes this time.
Ran `cargo clippy` locally, but will rely on CI for other tests.

chore(deps): Update to Rust 1.82.0

---

.github/workflows/regression.yml

SMP jobs now run more replicates, they take longer.

chore(soak tests): Increases inner GH action timeout to match job-level timeout

---

.github/workflows/cli.yml

I've started to see timeouts for this job since pinning the `runs-on` to `ubuntu-20.04`.
- https://github.com/vectordotdev/vector/commit/475e93f182cc51e06ca74f8545a245203bcec1d0

chore(ci): Bump timeout for cli tests

---

changelog.d/add_default_fallback_index_elasticsearch_destination.enhancement.md
src/sinks/elasticsearch/config.rs
src/sinks/elasticsearch/mod.rs
src/sinks/elasticsearch/tests.rs
website/cue/reference/components/sinks/base/elasticsearch.cue

Currently, the Elasticsearch destionation has the option to specify an [index](https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#bulk.index) to write events to. This field supports template syntax, however if the template is not able to be resolved, the default behavior is to drop the event.
Adding an optional field that specifies a fallback index that logs can be written to if there is a template rendering error.

enhancement(elasticsearch sink): Add option to specify a default index if template cannot be resolved for Elasticsearch destination index

---

changelog.d/22026-retry-kafka-policy-violations.fix.md
src/sinks/kafka/service.rs

Copied from the body of the commit:
> Problem: Some messages were getting dropped by Vector due to Kafka throwing `PolicyViolation` errors. These should be retried as a policy can be as simple as a more aggressive rate limit.
>
> ---
>
> Solution: Retry any messages that had the `RDKafkaErrorCode::PolicyViolation` error.
>
> ---
>
> Note: A dynamic back off may be better, as there may be a rate limit out there that still needs more than 100ms to back off on requests.
>
> ---
>
> See the original issue at https://github.com/vectordotdev/vector/issues/22026
>
> Closes https://github.com/vectordotdev/vector/issues/22026
Ensures Kafka retries messages that error out with `RDKafkaErrorCode::PolicyViolation`.
- `cargo test --no-default-features --features …

fix(kafka sink): retry messages that result in kafka policy violations

---

changelog.d/21999-add-option-to-use-virtual-addressing.feature.md
src/aws/mod.rs
src/common/s3.rs
src/common/sqs.rs
src/secrets/aws_secrets_manager.rs
src/sinks/aws_cloudwatch_logs/config.rs
src/sinks/aws_cloudwatch_logs/integration_tests.rs
src/sinks/aws_cloudwatch_metrics/mod.rs
src/sinks/aws_kinesis/firehose/config.rs
src/sinks/aws_kinesis/firehose/integration_tests.rs
src/sinks/aws_kinesis/streams/config.rs
src/sinks/aws_kinesis/streams/integration_tests.rs
src/sinks/aws_s3/config.rs
src/sinks/aws_s3/integration_tests.rs
src/sinks/aws_s_s/sns/config.rs
src/sinks/aws_s_s/sns/integration_tests.rs
src/sinks/aws_s_s/sqs/config.rs
src/sinks/aws_s_s/sqs/integration_tests.rs
src/sinks/s3_common/config.rs
src/sources/aws_s3/mod.rs
src/sources/aws_sqs/config.rs
website/cue/reference/components/sinks/base/aws_s3.cue

The following PR adds an option to enable virtual host style addressing to an s3 sink. The `force_path_style` option defaults to `true` for backwards compatibility and may eventually be desired to default to `false` as path style addressing will eventually be removed from aws s3.
This is my first Rust and first Vector PR, so please correct me on any contribution guidelines, style semantics, and code patterns!
I pointed an aws s3 sink at my object storage service and validated both path style and vhost style addressing works and also has the correct `authority` in access logs. …

feat(aws_s3 sink): add option to use virtual addressing

---

changelog.d/22079_correct_filter_condition_via_vector_generate.fix.md
src/transforms/filter.rs

Fixed typo in filter component produced by `vector generate`
Untested. I stumbled upon it while playing around with `vector generate` in the cli.
Can be reproduced with e.g. `# vector generate /filter`. If this PR doesn't follow the guidelines, feel free to delete it and push the fix.

fix(config): Correct `filter` transform generation via `vector generate` to use a comparison

---

changelog.d/22090_remove_gcp_pubsub_msg_size_limit.fix.md
src/sources/gcp_pubsub.rs

Removes the default 4MB message size decoding limit created by Tonic 0.9, preventing the gcp_pubsub source from receiving messages larger than this size.
Created a test PubSub topic in a personal GCP account, published a >4MB size message to the topic, and read from the subscription successfully.
- [-] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
- Closes: #22090

fix(gcp_pubsub source): Remove Tonic default 4MB decode size limit

---

changelog.d/s3_sink_add_glacier_ir_storage_class.enhancement.md
src/sinks/s3_common/config.rs
website/cue/reference/components/sinks/base/aws_s3.cue

This PR addresses the absence of the Glacier Instant Retrieval storage class option, which is available as a configurable option provided by AWS. Following the approach of previous similar PRs, this update introduces support for the Glacier Instant Retrieval storage class.
refer to the [official documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/sc-howtoset.html).
```
make test SCOPE="sinks::s3_common"
```
#5245 
#19893

enhancement(aws_s3 sink): add glacier instant retrieval storage class

---

.github/workflows/publish.yml

`macos-latest-xlarge` is for ARM architecture based on https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners.
This PR is an immediate fix. Will followup with another PR to add support for both ARM and Intel and fix the verification step.
Ref: https://github.com/vectordotdev/vector/issues/22129

fix(ci): macOS runner for Intel

---

.github/workflows/publish.yml
distribution/install.sh

Follow up to https://github.com/vectordotdev/vector/pull/22134. 
We now have access to a GitHub runner which can produce ARM executables.
Ref: https://github.com/vectordotdev/vector/issues/21721

feat(ci): publish ARM macOS builds

---

website/layouts/partials/data.html

Try to resolve #22136.
`log_to_metric` transforms
`static metric`
```
make quick-build
make serve
```
Navigate to [log to metric transforms](http://localhost:1313/docs/reference/configuration/transforms/log_to_metric/) and [static metric](http://localhost:1313/docs/reference/configuration/sources/static_metrics/)
Close #22136

chore(external docs): render array of object type in component docs

---

changelog.d/22050-fingerprint-uncompressed-file-content.fix.md
lib/file-source/src/fingerprinter.rs
src/sources/file.rs
website/cue/reference/components/sources/base/file.cue
website/cue/reference/components/sources/file.cue

This PR addresses https://github.com/vectordotdev/vector/issues/13193.
This PR will handle the case where attempting to fingerprint compressed content. It will also handle a use case with log rotation, where an uncompressed active file might be monitored and then rotated into a compressed file with a new inode by a log rotation service. By comparing the uncompressed lines as a source of truth, it prevents messages from processing the files 2X.
I chose to explicitly check the magic bytes header by enumerating the signatures to make checking the different headers consistent. I checked a couple compression libraries, and I figured it would be complicated to try to move the ownership of a reader into multiple decoders with inconsistent functions that did not all permit easy checking of the …

fix(file source)!: use uncompressed content for fingerprinting files (lines and ignored_header_bytes)

---

.github/dependabot.yml

We stopped receiving PRs since vectordotdev/vector#21958. Although that configuration is valid based on the public docs. Reverting to test if this is the root cause. If it is, it is worth following up with GitHub support.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow

chore(ci): Revert "dependabot allow all dep types"

---

changelog.d/add_virtual_memory_process_metric.feature.md
src/sources/host_metrics/process.rs
website/cue/reference/components/sources/host_metrics.cue

Add virtual memory metric to the process host metrics collector. The current metric only covers process RSS.
```bash
make environment CONTAINER_TOOL="podman"
mkdir /etc/vector && cat << EOF > /etc/vector/vector.yaml
sources:
in:
type: "host_metrics"
collectors:
- "process"
sinks:
out:
inputs:
- "in"
type: "console"
encoding: 
codec: "native_json"
EOF
cargo run | jq .
...
{
"metric": {
"name": "process_memory_virtual_usage",
"namespace": "host",
"tags": {
"collector": "process",
"command": "target/debug/vector",
"host": "...",
"name": "vector-worker",
"pid": "74413"
},
"timestamp": "2025-01-11T01:14:11.300421047Z",
"kind": "absolute",
"gauge": {
"value": 836136960
}
}
}
```
defined …

feat(host_metrics source): Add process virtual memory metric

---

vdev/src/commands/release/homebrew.rs

* Update the homebrew.rs binary to support ARM64 macOS builds. 
* Greatly simplified replacement logic
On my fork with:
```
cargo run --package vdev --bin vdev -- -v release homebrew  --username pront
```
Result is here:
https://github.com/pront/homebrew-brew/commit/d74138158797e058791ebd2442e9035ecf32e1de
Depends on: https://github.com/vectordotdev/homebrew-brew/pull/22
Ref: https://github.com/vectordotdev/vector/issues/10193

feat(releasing): refactor homebrew.rs to support ARM builds

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
changelog.d/21972-add-tcp-collector-host-metrics.feature.md
license-tool.toml
src/api/schema/metrics/host.rs
src/sources/host_metrics/mod.rs
src/sources/host_metrics/tcp.rs
website/cue/reference/components/sources/base/host_metrics.cue
website/cue/reference/components/sources/host_metrics.cue

Add a new tcp collector to the host_metrics source to expose information about the systems's TCP stack. It exposes three metrics:
* `tcp_connections_total`: The total number of TCP connections. It includes the state of the connection as a tag.
* `tcp_tx_queued_bytes_total`: The sum of the number of bytes in the send queue across all connections.
* `tcp_rx_queued_bytes_total`: The sum of the number of bytes in the receive queue across all connections.
These metrics are only available for Linux systems as it uses the netlink subsystem.
* Unit tests for the code interacting with netlink and for the code writing to the metrics buffer.
* Manual testing by running the change locally with the below config file and comparing the output with `ss -a -t` on both Linux x86 and arm systems.
```yaml …
```

feat(host_metrics source): add a new collector for tcp stats

---

.github/workflows/changes.yml
.github/workflows/integration.yml
src/sinks/datadog/logs/tests.rs

The IT suite is the longest running check in the merge queue. This PR splits the IT suite in several jobs that run in parallel.
Note: The jobs still build Vector individually. I will follow-up so that we build Vector once and then we re-use the binary across the suite. …

feat(ci): run integration tests in parallel

---

rfcs/2020-03-06-1999-api-extensions-for-lua-transform.md
website/content/en/highlights/2022-03-22-0-21-0-upgrade-guide.md

Trivial fixes for `make check-markdown`   

chore(dev): fix markdown lint failures

---

.github/actions/spelling/allow.txt
.github/actions/spelling/expect.txt
.github/workflows/integration.yml
docs/tutorials/sinks/2_http_sink.md
scripts/integration/gcp/compose.yaml

Use images owned by the Vector org.
I published a new image today: https://hub.docker.com/repository/docker/timberio/chronicle-emulator/general …

chore(dev): replace plork images

---

website/cue/reference/components/sinks/opentelemetry.cue

This PR fixes the issue outlined [here](https://github.com/vectordotdev/vector/issues/22216). Currently the OpenTelemetry Sink's quickstart in the docs does not match the expected payload, causing the Collector to return 200 Success but not actually ingest the log. 
This PR updates the format so that it matches examples [provided by OpenTelemetry](https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/#examples).
Additionally, it sets the debug exporter to verbose so that new users experimenting with this logging can get console output of what they are sending. 
checks might not be …

docs(external): fix OpenTelemetry Sink Quickstart to match expected log data model

---

scripts/environment/install-protoc.sh

Bump the protoc version from 3.19.5 to 3.20.2 in
`scripts/environment/install-protoc.sh`. The [3.19.5 release](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.5) of protocol buffers don't include assets for macOS arm64, hence the script fails on the same.
The bump is to 3.20.2 instead of 3.20.3 because for some reason, only the [3.20.2 release](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.2) contains assets for macOS arm64.
Furthermore, modify the flags passed to the `mv` command to be macOS compatible.
By running the script on a macOS arm64 machine.
checks …

chore(dev): fix protoc installation script for macOS arm64

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv

Bump to the latest version.
Ideally we want to enable the `fips` feature but it's not trivial: https://github.com/vectordotdev/vector/pull/21504 …

chore(deps): bump async-nats to v0.38

---

regression/config.yaml

This release of lading contains a fix for splunk-hec tests that do not transmit an ackId.

chore(ci): Update lading to 0.25.4

---

changelog.d/datadog_search_syntax_support_ddtags.enhancement.md
src/conditions/datadog_search.rs

Enhance the Datadog search syntax on transforms filters: we want some keywords to query on several fields at once (OR condition):
- `tags` will lookup the fields `tags` and `ddtags` (previously only `tags`)
- `source` will lookup the fields `source` and `ddsource` (previously only `source`)
This is because although we try to stay vendor-agnostic, the DD agent source is widely used and generates the fields `ddtags` and `ddsource`, which is misleading for Observability Pipelines users.
Issue [here](https://datadoghq.atlassian.net/jira/software/c/projects/OPA/boards/2519?assignee=712020%3Aaadb2df8-efc5-4003-84d1-0667652ecd9e&selectedIssue=OPA-2847) (Datadog access)
`cargo test --package vector --lib -- conditions::datadog_search::test --show-output` passes all the tests.
The includes the …

feat(datadog service): support filtering on ddtags and ddsource in datadog search syntax

---

changelog.d/22077_per_metric_limits_for_tag_cardinality_limit_transform.feature.md
src/transforms/tag_cardinality_limit/config.rs
src/transforms/tag_cardinality_limit/mod.rs
src/transforms/tag_cardinality_limit/tests.rs
website/cue/reference/components/transforms/base/tag_cardinality_limit.cue

This adds the ability to add per metric limits in `tag_cardinality_limit` transform, besides the global configuration that applies to all metrics. It supports matching metrics by name and optionally by namespace too.
Added new tests to `transforms::tag_cardinality_limits::tests` and also tested manually with the following configuration:
```yaml
sources:
static_metrics_test:
type: static_metrics
interval_secs: 1
metrics:
- name: customA
value:
gauge:
value: 3.0
kind: absolute
tags:
custom_tag: custom_tag_1
another_tag: test
- name: customA
value:
gauge:
value: 4.4
kind: incremental
tags:
custom_tag: custom_tag_2
another_tag: test
- name: customA
value:
gauge:
value: 4.4
kind: incremental
tags:
custom_tag: custom_tag_3
another_tag: test2
- name: customB
value:
gauge:
value: 3.0
kind: …
```

feat(tag_cardinality_limit transform): enable per metric limits for `tag_cardinality_limit`

---

website/cue/reference/configuration.cue

I try to fix the issue mentioned in #22234, and I also find the similar change is needed in `enrichment_table` when I dive deep into the document.
I find the `secret` is not a simple enum, and it's more like a classic Rust enum which may have different optional fields.
Listened the hint by @pront, I find the `kind` field is optional field when `type` is `counter` in `log_to_metrics transform`, which is similar to our case.
The [log_to_metrics docs](https://github.com/vectordotdev/vector/blob/1af287f1f05050e0382d3dac6efb888508dce390/website/cue/reference/components/transforms/base/log_to_metric.cue#L51-L72) insert a optional `relevant_when` field to let the reader knows that this is a optional field in certain case. I try to insert the same notice to both `enrichment_table` and `secret`. …

docs(external): fix `enrichment_table` and `secret` docs

---

changelog.d/22348_dnstap_protobuf_update.feature.md
lib/dnstap-parser/proto/dnstap.proto

This updates dnstap protobuf schema to version v20250201
Related: …

chore(dnstap source): update dnstap protobuf schema

---

.github/workflows/regression.yml

Turns out the artifact was implicitly unzipped. 
Based on this https://github.com/vectordotdev/vector/actions/runs/13108162028/job/36571342183. …

fix(ci): fix report path

---

src/sinks/humio/logs.rs

Want to re-use the `humio_logs` integration elsewhere, which includes using the `HumioLogsConfig` struct. However, the fields in this struct are currently marked `pub(super)`, need to switch this to `pub`. 
`cargo build`

feat(internal): Make fields in HumioLogsConfig public

---

lib/vector-vrl/functions/src/get_secret.rs
lib/vector-vrl/functions/src/remove_secret.rs
lib/vector-vrl/functions/src/set_secret.rs
src/sinks/elasticsearch/sink.rs
src/sources/journald.rs
src/sources/kubernetes_logs/parser/docker.rs

Converting to lossy UTF-8 string is already possible by `Value::as_str` method, that now utilizes `simdutf8` that is faster than `String::from_utf8_lossy`.
Standard test case
run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if …

chore(vrl): use `as_str()` as implemented by `Value` 

---

website/cue/reference/components/transforms/remap.cue
website/cue/reference/urls.cue

Rephrases and clarifies on event types.
P.S. I also noticed that `inputs` is not rendered.
Ref: …

docs(external): add note for input/output typs in remap docs

---

changelog.d/log-fields-additional-types.enhancement.md
lib/vector-config/src/external/vrl.rs
src/config/mod.rs
src/config/unit_test/mod.rs
src/config/unit_test/tests.rs

By making vrl Value a configurable type
- [] Bug fix
Closes: #9386

enhancement(unit tests): Allow objects and arrays in log_fields test input

---

Cargo.lock
Cargo.toml

Enable simdutf8 feature for maxminddb that was added to 0.25 version that increase performance.
Standard test case. …

chore(performance): Enable simdutf8 feature for maxminddb

---

Cargo.lock
website/cue/reference/remap/functions/ip_cidr_contains.cue

Update documentation for ip_cidr_contains
N/A
https://github.com/vectordotdev/vrl/pull/1248

docs(vrl): Update documentation for ip_cidr_contains

---

.github/workflows/semantic.yml
website/cue/reference/components/sinks/websocket_server.cue

I have added a very simple usage example for `websocket_server`, per request in https://github.com/vectordotdev/vector/pull/22213#issuecomment-2669380311. …

docs(websocket_server sink): add `how_it_works` section for `websocket_server`

---

website/cue/reference/components.cue
website/cue/reference/components/sinks/websocket_server.cue
website/cue/reference/components/sources/heroku_logs.cue
website/cue/reference/components/sources/http_server.cue
website/cue/reference/components/sources/prometheus_pushgateway.cue
website/cue/reference/components/sources/prometheus_remote_write.cue

This adds an `Authorization configuration` `How it works` section to every component that uses shared server auth configuration, added in (#22236). It is rendered for every component that has the new feature flag set to true (`features.has_auth`). …

docs(external): add `how_it_works` section for auth config

---

website/cue/reference/components/sinks/websocket_server.cue

In the initial PR, I forgot to add the automatically generated configuration section to the `websocket_server` docs page. …

docs(external docs): fix missing configuration section for `websocket_server` docs

---

Cargo.lock
Cargo.toml
vdev/Cargo.toml
vdev/src/commands/release/prepare.rs
vdev/src/git.rs
vdev/src/util.rs

Full revamp of `prepare.rs` to match our current release process.
Example: https://github.com/vectordotdev/vector/issues/22445
This PR automates the following steps:
```
Create a new release branch from master to freeze commits
git fetch && git checkout origin/master && git checkout -b v0.<new version number> && git push -u
Create a new release preparation branch from master
git checkout -b website-prepare-v0.<new version number> && git push -u
Pin VRL to latest released version rather than main
```
To facilitate PR reviews, so I am going to automate more steps later.
checks might not be …

chore(releasing): automate release preperation steps (part 1)

---

src/tap/mod.rs

`vector tap -h` interval option states `Interval to sample _logs_ at, in milliseconds`, but website documentation states `Interval to sample _events_ at, in milliseconds`. Small change to sync them
(previous vector tap)
```console
> vector tap -h
Observe output log events from source or transform components. Logs are sampled at a specified
interval
Usage: vector tap [OPTIONS] [COMPONENT_ID_PATTERNS]...
Arguments:
[COMPONENT_ID_PATTERNS]...  Components IDs to observe (comma-separated; accepts glob
patterns)
Options:
-i, --interval <INTERVAL>        Interval to sample logs at, in milliseconds [default: 500]
-u, --url <URL>                  GraphQL API server endpoint
-l, --limit <LIMIT>              Maximum number of events to sample each interval [default:
100]
-f, --format <FORMAT> …
```

docs(external): update vector tap help

---

scripts/environment/prepare.sh

We can now use the released version.
```
cd vector/lib/vector-vrl/web-playground && RUST_LOG=info wasm-pack build --target web --out-dir public/pkg  && cd public && python3 -m http.server
```
run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit …

chore(ci): install released wasm-pack version 0.13.1

---

changelog.d/22479_websocket_server_sink_buffering.feature.md
src/sinks/websocket_server/buffering.rs
src/sinks/websocket_server/config.rs
src/sinks/websocket_server/mod.rs
src/sinks/websocket_server/sink.rs
website/cue/reference/components/sinks/base/websocket_server.cue
website/cue/reference/components/sinks/websocket_server.cue

This adds a message buffer to `websocket_server`, backed by a ring buffer, which hold a set maximum number of messages to replay to clients that connect late, or re-connect after losing connection. Messages are replayed based on `last_received` query parameter.
Besides the added unit tests, this was tested with the following configuration:
```yaml
sources:
demo_logs_test:
type: "demo_logs"
format: "json"
sinks:
websocket_sink:
inputs: ["demo_logs_test"]
type: "websocket_server"
address: "0.0.0.0:1234"
message_buffering:
message_id_path: "message_id"
acknowledgements:
enabled: false
encoding:
codec: "json"
```
When connecting to the websocket using the url "ws://localhost:1234", messages were received as previously, but when sent with "ws://localhost:1234?last_received={some-message-id}", …

feat(websocket_server sink): add message buffering for `websocket_server`

---

changelog.d/add-user-labels-to-gcp-stackdriver-logs-sink.enhancement.md
src/sinks/gcp/stackdriver/logs/config.rs
src/sinks/gcp/stackdriver/logs/encoder.rs
src/sinks/gcp/stackdriver/logs/tests.rs
website/cue/reference/components/sinks/base/gcp_stackdriver_logs.cue

This adds top level label field according to LogEntry docs https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#FIELDS.labels! 
This will allow users add additional labels to the label field in log entries not just the ones in resource object!
- Ran the unit tests
```bash
cargo test --package vector --lib -- sinks::gcp::stackdriver::logs::tests --show-output```
- cargo test --all
- Tested against an existing google account and viewed the logs in GCL.
- `cargo …

feat(gcp_stackdriver_logs sink): Support additional top level labels for gcp_stackdriver_logs sink

---

.github/workflows/k8s_e2e.yml
.github/workflows/msrv.yml
.github/workflows/test.yml
scripts/environment/bootstrap-ubuntu-24.04.sh
scripts/environment/prepare.sh

This https://github.com/vectordotdev/vector/actions/runs/13635254034/job/38112313325 fails on master.

fix(ci): `prepare.sh` should install the toolchain

---

website/cue/reference/releases/0.36.0.cue
website/cue/reference/releases/0.37.0.cue
website/cue/reference/releases/0.37.1.cue
website/cue/reference/releases/0.38.0.cue
website/cue/reference/releases/0.41.0.cue
website/cue/reference/releases/0.42.0.cue
website/cue/reference/releases/0.43.0.cue
website/cue/reference/releases/0.44.0.cue
website/cue/reference/releases/0.45.0.cue

This adds missing Quad9 credits in my PRs from previous releases, because that work was sponsored by Quad9. …

docs(external): add missing Quad9 credits in previous releases

---

changelog.d/22479_websocket_server_sink_buffering.feature.md
changelog.d/22528_enrichment_panic.fix.md

This adds missing Quad9 credits in my recently merged PRs, because that work was sponsored by Quad9.
--- …

docs(external): add missing Quad9 credits in changelog entries

---

CONTRIBUTING.md

Fix dead link on commit sub-categories in CONTRIBUTING.md

docs(internal docs): Fix dead link on commit sub-categories

---

Cargo.lock
LICENSE-3rdparty.csv

Weekly bump (usually done by dependabot) 

chore(dev): cargo update -p vrl

---

.github/workflows/build_preview_sites.yml
.github/workflows/create_preview_sites.yml
src/sources/host_metrics/tcp.rs

- Updates the permissions so we can extract the artifact
- Reverts the change to the id used to the previous one …

fix(website): Update permissions and revert id call

---

Cargo.lock
changelog.d/host_metrics_tcp_panic.fix.md
src/sources/host_metrics/tcp.rs

Check the input to NativeEndian::read_u32 since the latter can panic. 
On an ubuntu 24.04 instance with:
```
api:
enabled: true
sources:
my_source_id:
type: host_metrics
scrape_interval_secs: 30
sinks:
console:
inputs: [ "my_source_id" ]
type: console
encoding:
codec: json
json:
pretty: true
```
run `dd-rust-license-tool write` to regenerate …

fix(host_metrics source): add defensive check to prevent panics

---

scripts/generate-release-cue.rb
vdev/src/commands/release/prepare.rs
vdev/src/util.rs

This PR automates three additional release step:
* dockerfile version bumps
* generate release cue file
* Required enhancements to the `generate-release-cue.rb` script
* kubectl.cue version bump
The next PR will automate the last four steps. …

chore(releasing): automate more pre-release steps

---

changelog.d/20231-gcs-token-refresh.fix.md
src/gcp.rs

The simple calculation for the next deadline to sleep the gcp refresh token thread performs a subtraction which is unchecked.
The value of `expires_in` may be less then the constant `METADATA_TOKEN_EXPIRY_MARGIN_SECS`, causing the deadline to overflow and making the thread sleep for a long duration. Upon the next time the sink pushes to GCS the token would have already expired since the refresh thread hadn't awaken on time.
No tests as of yet have been added.
- `cargo clippy …

fix(gcp service): Prevent overflow for gcp token expiry calculation

---

Cargo.lock
Cargo.toml
lib/codecs/Cargo.toml
lib/k8s-e2e-tests/Cargo.toml
vdev/Cargo.toml
vdev/src/commands/release/prepare.rs

Automates more release steps:
* VRL changelog addition to the the release CUE file
* Update version number in `distribution/install.sh`
* Add new version to `website/cue/reference/versions.cue`
* Create new release md file
* Open release prep PR
If only I had a good CUE parser in Rust...
This is not pretty but it automates some error prone steps.  
- `cargo nextest run --workspace` (alternatively, you can run `cargo test …

chore(releasing): automate the rest of the release prep steps

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
changelog.d/22686_s3_sink_endpoint_url_from_aws_config_file.fix.md
src/aws/auth.rs
src/aws/mod.rs
src/sinks/aws_s3/config.rs

Prior to this PR, when endpoint_url was set in AWS_CONFIG_FILE, Vector would ignore it. After this PR, Vector will continue prioritizing manually-configured endpoint_url on an aws_s3 sink, but it will also use the value from AWS_CONFIG_FILE otherwise (assuming one is provided there).
Confirmed in a dev environment running Vector built from source off of this branch in a helm chart, writing to Ceph's S3 endpoint as configured in AWS_CONFIG_FILE but not configured in aws_s3 sink.
- …

fix(aws_s3 sink): Respect endpoint_url field in AWS_CONFIG_FILE

---

website/package.json
website/scripts/typesense-sync.ts
website/typesense.config.json
website/yarn.lock

- Bump `typesense-sync` to `v1.1.0`
- Updates `typesense.config.json` in accordance with package updates, including schema definition for easier updates in the future
- Latest build was successful here including typesense job: https://us-east-1.console.aws.amazon.com/amplify/apps/d1a7j77663uxsc/branches/brian.deutsch%2Ftypesense-update/deployments
- No changes to UI
- `cargo nextest run --workspace` (alternatively, you can …

chore(website): Update `typesense-sync` depedency, search config

---

lib/vector-core/src/event/discriminant.rs

Implements the `Display` trait for the `Discriminant` type, which will be used elsewhere to format a `Discriminant` type for metrics. For now not trimming quotes on Bytes type Values to simplify things (something like `trim_matches` will trim quotes that are technically a part of the string, for example if the String is `"""`, then `trim_matches` will trim this to an empty string)
Added unit test …

enhancement(internal): Implement Display trait for Discriminant type

---

src/transforms/throttle/config.rs
src/transforms/throttle/mod.rs
src/transforms/throttle/rate_limiter.rs
src/transforms/throttle/transform.rs

We want to re-use pieces of the `throttle` processor implementation, in particular the rate-limiter logic. Refactors out constructing / running the rate limiter (mainly by running I mean periodically flushing old keys) into a separate struct that can be re-used elsewhere. Also refactors out some metrics related code, and moves the `throttle` implementation inside it's own folder in `transforms` (further split `throttle.rs` into 2 files, `config.rs` and `transform.rs` to mimic the file structure seen in other transform implementations such as `sample`, `dedupe`, etc.)
Tested with vector config/pipeline containing throttle processor
defined [here](https://github.com/vectordotdev/vector/blob/1ef01aeeef592c21d32ba4d663e199f0608 …

enhancement(throttle transform): Refactor throttle/rate limiter logic into reusable wrapper

---

changelog.d/add_headers_vector_source.enhancement.md
src/sources/http_server.rs
src/sources/vector/mod.rs
website/cue/reference/components/sources/base/vector.cue

This PR adds option to include http headers in vector source log events similar to http source.
most of function and structs are reused from http source.
Use case: we have a use case where between vector sink in edge node and vector source in aggregator, there is a proxy. 
this proxy is responsible for validation and adding a header for `Provenance` purpose for log source.
we need to attach this Provenance header value to log event in aggregator which later will go to ETL pipeline.
GRPC protocol provide these headers as metadata and it seems tonic's Request struct exposes them as metadata but vector source just drops/ignores that field.
This pr is trying to use that metadata to add the header in log event is configure.
by default header config is empty string hence no data is added. …

 enhancement(vector source): add `headers` option

---

changelog.d/sample-percentage.feature.md
changelog.d/sample-ratio.feature.md
src/transforms/sample/config.rs
src/transforms/sample/tests.rs
src/transforms/sample/transform.rs
website/cue/reference/components/transforms/base/sample.cue

This change introduces the ability for the sample processor to reduce the amount of data on a stream in terms of percentages.
This allows for the ability to sample more then 50% of the stream, an ability it did not have before when the rate was expressed by the formula 1/N
Unit tests. Also added an additional test to explicitly test rates > 50%
- `cargo nextest run --workspace` (alternatively, you can run `cargo test …

feat(sample transform): Sample by percent rate

---

lib/vector-core/src/metrics/ddsketch.rs

This patch adds an explicit type conversion to avoid the ambiguity:
```
assert!(
keys.len()
<= usize::try_from(u32::MAX)
.expect("we don't support 16-bit systems")
);
```
When you self compile Vector with `time` or `domain` crate, you will meet this error:
```
error[E0283]: type annotations needed
--> /home/suika/.cargo/git/checkouts/vector-7010c25277c07669/063cabb/lib/vector-core/src/metrics/ddsketch.rs:460:22
|
459 |                 <= u32::MAX
|                 -- type must be known at this point
460 |                     .try_into()
|                      ^^^^^^^^
|
= note: multiple `impl`s satisfying `usize: PartialOrd<_>` found in the following crates: `core`, `deranged`:
- impl PartialOrd for usize;
- impl<MIN, MAX> PartialOrd<deranged::RangedUsize<MIN, MAX>> for usize
where the …
```

fix(dev): use explicit cast because deranged crate may break compile

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv

Reverts vectordotdev/vector#22759
This update breaks it IT:
https://github.com/vectordotdev/vector/actions/runs/14205431504/job/39801978223?pr=22770

Revert "chore(deps): Bump async-nats from 0.33.0 to 0.40.0"

---

scripts/generate-release-cue.rb
vdev/src/commands/release/prepare.rs

Refactoring to avoid passing arguments repeatedly.
Improved `generate-release-cue.rb` to discover repo root instead of using a hardcoded one.

chore(releasing): vdev prepare refactoring

---

Cargo.lock

Fix for https://rustsec.org/advisories/RUSTSEC-2025-0023
make check-deny
- The CI checks run only after we manually approve them. To minimize round-trips see the following local checks: …

fix(deps): update tokio to fix RUSTSEC-2025-0023

---

src/transforms/reduce/merge_strategy.rs
src/transforms/reduce/transform.rs

Refactors out the construction of the reduce processor's output stream into a reusable helper that can be used by other components. We want to pass in different `transform` functions to this helper so added this as a parameter.
Tested locally with vector pipeline
```
transforms:
transform-0:
inputs:
- source-0
type: reduce
group_by:
- input
merge_strategies:
input: "concat"
```
- The CI checks run only after we manually approve them. To minimize round-trips see the following local checks:
defined …

enhancement(reduce transform): Refactor reduce transform logic

---

changelog.d/22827_cloudwatch_auth_missing_region.fix.md
src/aws/auth.rs

Resolves newly created bug #22827, adding `region` to the credentials_file authentication method for aws services.
Before this fix, when using `auth.credentials_file`, and the file contained `role_arn`, and `web_identity_token` keys, the resulting sts calls produced a "Invalid Configuration" error in the log, and prevented the cloudwatch logs sink from authenticating.    This fix adds 'auth.region' to the valid spec, and sets the value to the `service_region` if not provided.
```
[sinks.output_my_cw]
type = "aws_cloudwatch_logs"
inputs = ["in"]
region = "us-east-2"
group_name = "group-test"
stream_name = "my-stream"
auth.credentials_file = "/root/.aws/credentials"
#auth.profile = "default"
encoding.codec = "json"
--------------------------
#Sample aws credentials file:
[default] …
```

fix(auth): #22827 missing region error when using AWS credentials file auth

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
src/sinks/webhdfs/config.rs
src/sinks/webhdfs/integration_tests.rs

This PR will bump opendal to latest v0.50.0 for up to date deps and performance improvement.

chore(deps): Bump OpenDAL to v0.53.0

---

Cargo.lock
Cargo.toml
src/enrichment_tables/geoip.rs
src/enrichment_tables/mmdb.rs

Update code for breaking changes in maxminddb 0.26 – now instead of error in case IP was not found, maxminddb returns `None`.
Cargo test
- Closes #22758

chore(deps): Bump maxminddb from 0.25.0 to 0.26.0 

---

changelog.d/22854_websocket_server_subprotocol_support.feature.md
src/sinks/websocket_server/config.rs
src/sinks/websocket_server/sink.rs
website/cue/reference/components/sinks/base/websocket_server.cue

Adds support for `Sec-WebSocket-Protocol` header in websocket connection request. By default (and currently, before this feature), the server ignored this header and never put it in responses. It can be configured to accept any subprotocol and put it in response header (some clients will require this) and it can also be configured to only accept some subprotocols and ignore others. This only affects the connection requests, everything afterwards functions the same.
Ran Vector with following configuration:
```yaml
sources:
demo_logs_test:
type: "demo_logs"
format: "json"
sinks:
websocket_sink:
inputs: ["demo_logs_test"]
type: "websocket_listener"
subprotocol:
type: any
address: "0.0.0.0:1234"
encoding:
codec: "json"
```
Without `subprotocol` option:
```
$ wscat --connect …
```

feat(websocket_server sink): add support for websocket subprotocol

---

.github/ISSUE_TEMPLATE/patch-release.md

chore(dev): enhancements to the patch release template

---

changelog.d/22831_increase_cloudwatch_log_event_max_size.fix.md
src/sinks/aws_cloudwatch_logs/request_builder.rs

Resolves issue #22859 by increasing the max event size for cloudwatch log events to ~ 1MB.   This matches the new limit updated by [AWS](https://aws.amazon.com/about-aws/whats-new/2025/04/amazon-cloudwatch-logs-increases-log-event-size-1-mb/).
Added one unit test but so far no functional tests have been run.
- Alternatively, we recommend running the following locally before pushing to …

fix(aws_cloudwatch_logs sink): increase cloudwatch logs max event size to match new aws limit of 1MB

---

changelog.d/14082_add_mermaid_support.feature.md
src/graph.rs

Adds support for rendering to `mermaid` format by running `vector graph --format mermaid`, as discussed and described in #14082.
Note: The `.graph.node_attributes` config is ignored for Mermaid rendering since it's explicitly set to be in DOT format. It should be possible to adapt but it's likely to lead to conflicts between the two formats.
In terms of implementing, could look like:
```
node_id@{shape: shapename}
style node_id key:value,key2:value2
```
(shapename would replace the shorthand in the current version; i.e. `/id/`)
https://mermaid.js.org/syntax/flowchart.html#styling-and-classes
Ran `vector graph` against an existing config with:
- no new flags
- `--format dot`
- `--format mermaid`
I observed no behavioral changes for the first two paths, and output rendered in mermaid format …

feat(cli): Add support for rendering to mermaid with `vector graph` command

---

changelog.d/22850_custom_auth_address_access.feature.md
src/common/http/server_auth.rs
src/sinks/websocket_server/sink.rs
src/sources/util/http/prelude.rs
website/cue/reference/components.cue

This adds access to `address`, besides `headers` access in VRL scripts for custom auth strategy. This can be useful for additional logging or whitelisting/blacklisting addresses.
Besides the tests added to the codebase, I ran basic tests with `http_server` source component:
```yaml
sources:
http_server_source:
type: "http_server"
address: "0.0.0.0:80"
auth:
strategy: "custom"
source: |-
log(.address)
.headers.authorization == "test"
sinks:
console:
inputs: ["http_server_source"]
target: "stdout"
type: "console"
acknowledgements:
enabled: false
encoding:
codec: "json"
```
Tested by making calls via curl:
```
$ curl -X POST vector:80
{"code":401,"message":"Auth failed"}
$ curl -X POST vector:80 -H "Authorization: test"
```
Client address was visible in Vector logs.
- Please read our [Vector …

feat(sources): add access to client address in custom VRL auth

---

changelog.d/22786_remove_empty_file_after_secs.fix.md
lib/file-source/src/file_server.rs
lib/file-source/src/fingerprinter.rs

Remove known small files based on remove_after_secs.
This test checks whether Vector properly removes empty log files after the configured `remove_after_secs` timeout.
```yaml
data_dir: ./data
sources:
in:
type: "file"
include:
- ./log/**/*.log
remove_after_secs: 60
sinks:
out:
inputs: ["in"]
type: "console"
encoding:
codec: "text"
```
Use the above config to start a Vector instance.
```sh
touch ./log/emptyfile.log
touch ./log/file.log
sleep 10s
echo "single line" >> ./log/file.log
sleep 30s
echo "single line" >> ./log/file.log
```
- `emptyfile.log` should be deleted after 60 seconds since it remains empty.
- `file.log` should **not** be deleted immediately, because it receives data during the interval and becomes fingerprintable.
```text
2025-04-18T16:17:47.016459Z  WARN …
```

fix(file source): Remove known small files based on remove_after_secs

---

changelog.d/s3-source-defer-or-delete.enhancement.md
src/internal_events/aws_sqs.rs
src/sources/aws_s3/sqs.rs
website/cue/reference/components/sources/base/aws_s3.cue

Introduces new optionally configurable options `max_file_age_secs` and `deferred_queue_url` to the `aws_s3` source.  This enables users to decide if they want to requeue S3 notification messages to a different SQS Queue for deferred processing or delete them after a certain age.
This is useful under a couple scenarios:
- the data is idempotent and we do not care to process all messages (no `deferred_queue_url` defined)
- the more recent data is more important and providing visibility to this data is more important than the older data
- using the `deferred_queue_url` this prevents us from losing the data, but let's us set a lower priority to it.
I ran a build locally with the below configuration to confirm that we were were not downloading the s3 files if configured to ignore them and that …

enhancement(aws_s3 source): optionally configure source to defer or delete older notifications

---

changelog.d/17294_allocation_group_id_groups_max_limit_increased.fix.md
changelog.d/17294_allocationgroupid_groups_max_limit_increased.fix.md
src/internal_telemetry/allocations/mod.rs

This merge request should close out  #22851 & #17294. 
vector would crash if AllocationGroupId::register() got called before NUM_GROUPS and allocate > 128. This PR increased NUM_GROUPS which prevents vector from crashing. 
- [-] Bug fix
- [ -] No
Built and ran locally for over 24 hours with internal_metrics exposed and scraped by prometheus. Built in alpine container and running in a lab for 48 hours on a busy instance. No crash. Without this change we would see 0.46 crash within a couple of hours across all instances.
as per comments already in code:
// TODO: Technically, `NUM_GROUPS` is lower (128) than the upper bound for the
// `AllocationGroupId::register` call itself (253), so we can hardcode `NUM_GROUPS` here knowing
// it's the lower of the two values and will trigger first.. but …

fix(internal): `AllocationGroupId::register` groups max limit increased to 256

---

website/cue/reference/components/sources/internal_metrics.cue

These don't exist anymore.
n/a …

docs(datadog service): Remove datadog specific telemetry

---

changelog.d/22921_remove_limit_if_use_apiserver_cache.fix.md
src/sources/kubernetes_logs/mod.rs
website/cue/reference/components/sources/base/kubernetes_logs.cue

1. configure a kubernetes_log source with `use_apiserver_cache = true`
2. collect pod logs and print logs to stdout
3. check k8s audit logs that if the list pods/nodes API use cache or not …

fix(kubernetes_logs source): remove limit if use apiserver cache

---

.github/workflows/integration.yml
Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
src/sinks/azure_common/config.rs

Quote from the issue:
"this introduced a regression transitively from Azure SDK version 0.20.0 that wasn't fixed until 0.22.0:
Issue: https://github.com/Azure/azure-sdk-for-rust/issues/1739
PR: https://github.com/Azure/azure-sdk-for-rust/pull/1997
Fixed in 0.22.0: https://github.com/Azure/azure-sdk-for-rust/commits/azure_identity%400.22.0/
It's worth noting, however, that 0.22.0 introduces its own regression - namely, the removal of EnvironmentCredential from DefaultAzureCredential."
- We recommend adding a `pre-push` hook, …

fix(azure service): revert deps bump

---

scripts/e2e/Dockerfile
tilt/Dockerfile

`ARG` needs to be requested in every build stage …

fix(ci): request ARG in every build stage

---

changelog.d/23048_fix_arith_logic_dnstap_parse.fix.md
lib/dnstap-parser/src/parser.rs

While parsing `dnstap` we can get panic while working with timestamps. Let's timestamp parse function returns Err for observe it. Maybe we should use more trivial construction and Err =)
Reproducer:
```rust
#[test]
fn repro_crash() {
let mut log_event = LogEvent::default();
let raw_dnstap_data = "KAJyAHICUgByMDAwMDAwMDAwMDAwMUAwMDAwMDAwMDAwMDAwMDAwMGD/////////rjAwMDAwMDAwMDAAcgJyAHIA";
let dnstap_data = BASE64_STANDARD
.decode(raw_dnstap_data)
.expect("Invalid base64 encoded data.");
let _parse_result = DnstapParser::parse(
&mut log_event,
Bytes::from(dnstap_data),
DnsParserOptions::default(),
);
println!("{:?}",_parse_result);
}
```
Trace:
```console
---- parser::tests::repro_crash stdout ----
thread 'parser::tests::repro_crash' panicked at lib/dnstap-parser/src/parser.rs:372:22:
attempt …
```

fix(parsing): Handling wrong timestamps in dnstap-parser

---

changelog.d/9819_watch_remap_external_vrl.enhancement.md
src/app.rs
src/config/mod.rs
src/config/transform.rs
src/transforms/remap.rs

This change ensures that updates to VRL source code are respected when calculating configuration diffs. External VRL files referenced in remap transforms (via file or files fields) are now tracked when `--watch-config` is enabled, allowing Vector to reload the configuration automatically when these files change.
Added a remap transform to config/vector.yaml :
```
transforms:
remap_logs:
type: remap
file: vrl/vrl_one
inputs:
- demo_logs_one
```
Started Vector with `vector -vvv  -c config/vector.yaml -w`
Then, modified the `/vector/vrl/vrl_one` file.
Vector detected the change and reloaded the configuration automatically as expected.
Added a remap transform to config/vector.yaml :
```
transforms:
remap_logs:
type: remap
files:
- vrl/vrl_one
- vrl/vrl_two
inputs:
- demo_logs_one
```
Started …

feat(remap transform): make `--watch-config` watch external VRL files in `remap` transforms

---

changelog.d/22926_enrichment_function_single_bounded_date_range_search.enhancement.md
lib/enrichment/src/lib.rs
lib/enrichment/src/vrl_util.rs
src/enrichment_tables/file.rs
website/cue/reference/remap/functions.cue

This PR resolves https://github.com/vectordotdev/vector/issues/21881 by enhancing the [enrichment functions](https://vector.dev/docs/reference/vrl/functions/#enrichment-functions) with support for single-bounded date range search. It's implementation is the addition of `FromDate` and `ToDate` to the `enum Condition` and their respective handling. 
Sidenote: I've been using vector for 1.5 years now but have never contributed nor written anything in rust before. I would like to become more knowledgeable of the codebase and a more active contributor so I welcome all feedback. Thank you in advance.
I ran unit tests:
```
cargo vdev test finds_row finds_rows_with_index_case_sensitive finds_rows_with_index_case_insensitive finds_row_between_dates finds_row_from_date finds_row_to_date
###
Summary …
```

enhancement(enriching): add from and to date search to enrichment tables

---

vdev/src/commands/release/prepare.rs

Recently the release CUE format changed. Now VRL changelog is separate from Vector changelog. This PR updates the prepare script to output the new format. 
- `cargo nextest run --workspace` (alternatively, you …

chore(releasing): update VRL changelog block insertion

---

src/source_sender/mod.rs

Prep work before pushing changes to the implementation. This should be entirely behavior neutral.

chore(sources): Refactor `struct SourceSender` a bit

---

changelog.d/23187_tls_enableable_config_deny_unknown_fields.fix.md
lib/vector-core/src/tls/settings.rs

Add deny_unknown_fields to TlsEnableableConfig so vector will not run when unused/invalid args are supplied
`cargo nextest run`
- …

fix(core): Add deny_unknown_fields to TlsEnableableConfig

---

changelog.d/aws-auth-session-token.enhancement.md
src/aws/auth.rs
website/cue/reference/base/configuration.cue
website/cue/reference/components/sinks/base/aws_cloudwatch_logs.cue
website/cue/reference/components/sinks/base/aws_cloudwatch_metrics.cue
website/cue/reference/components/sinks/base/aws_kinesis_firehose.cue
website/cue/reference/components/sinks/base/aws_kinesis_streams.cue
website/cue/reference/components/sinks/base/aws_s3.cue
website/cue/reference/components/sinks/base/aws_sns.cue
website/cue/reference/components/sinks/base/aws_sqs.cue
website/cue/reference/components/sinks/base/clickhouse.cue
website/cue/reference/components/sinks/base/databend.cue
website/cue/reference/components/sinks/base/elasticsearch.cue
website/cue/reference/components/sinks/base/http.cue
website/cue/reference/components/sinks/base/loki.cue
website/cue/reference/components/sinks/base/opentelemetry.cue
website/cue/reference/components/sinks/base/prometheus_exporter.cue
website/cue/reference/components/sinks/base/prometheus_remote_write.cue
website/cue/reference/components/sinks/base/websocket.cue
website/cue/reference/components/sources/base/aws_s3.cue
website/cue/reference/components/sources/base/aws_sqs.cue
website/cue/reference/components/sources/base/http_client.cue
website/cue/reference/components/sources/base/nginx_metrics.cue
website/cue/reference/components/sources/base/prometheus_scrape.cue

when using aws access and secret keys sometime session token is also required if these access token is temporary.
mechanism of getting the temporary token and renew the token is external to vector. external system uses secret backend mechanism to let vector know the new set of tokens.
- …

enhancement(sinks): allow to provide aws session token

---

website/cue/reference/components/transforms/remap.cue
website/layouts/partials/data.html

| Screenshot before | Screenshot after |
| ------------------ | ----------------- |
| <img width="831" alt="image" src="https://github.com/user-attachments/assets/5ca66ab1-b1a6-4790-a7af-a87b7ff1b7e4" /> | <img width="842" alt="image" src="https://github.com/user-attachments/assets/853b7920-ad9c-41e8-8915-c2e230e8d236" /> |
- Alternatively, we recommend running the following locally …

chore(website): minor improvements to output data section

---

website/layouts/partials/badge.html

fix(docs): Fixed documentation badges space on documentation
This change adds a mr-1 (margin-right) class to the badge container span to properly space badges when displayed inline, improving readability and visual layout in the documentation.
I built and previewed the documentation locally to verify that badges now have consistent spacing between each other without collapsing. The badges render correctly across different browsers and screen sizes.
- We recommend adding a `pre-push` hook, please see [this …

fix(website): Fixed documentation badges space on documentation

---

.github/workflows/changelog.yaml
.github/workflows/gardener_remove_waiting_author.yml
.github/workflows/semantic.yml
changelog.d/23224_test_changelog.feature.md

Running actions
- After a review is requested, please avoid force pushes to help us …

feat(ci): improve and remove authorization requirements

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
changelog.d/23228_vector_top_uptime.feature.md
src/top/dashboard.rs
src/top/metrics.rs
src/top/state.rs

Adds an additional field in title of `vector top`, displaying process uptime in seconds.
Just ran `vector top` with a running `vector` instance with `api` enabled.
- `cargo nextest run --workspace` …

feat(observability): add uptime seconds display to `vector top`

---

.github/ISSUE_TEMPLATE/minor-release.md

chore(releasing): minor fixes for minor release tmpl

---

.github/workflows/changes.yml
.github/workflows/k8s_e2e.yml

changes.yml check is being skipped in the merge queue making the check always run even when not necessary …

fix(ci): K8S E2E tests skipping changes.yml in MQ

---

.github/workflows/integration.yml

All tests were skipped for manual runs. This PR fixes that.
This PR also deletes the `check-changes` job since it's output was never used.
- `cargo nextest run --workspace` (alternatively, you can run `cargo …

fix(ci): IT suite should run when manually evoked

---

Cargo.lock
Cargo.toml
changelog.d/14621_http_client_source_vrl_query_parameters.enhancement.md
changelog.d/22581_max_merged_line_bytes.feature.md
changelog.d/22935_axiom_sink_trace_data_support.feature.md
changelog.d/22971_reconnect_broken_amqp_sink.fix.md
changelog.d/23022_hec_allow_content_header_contains.enhancement.md
changelog.d/23106_rcode_16_dnsmsg_parser_handling.fix.md
changelog.d/23123_dnstap_tcp_errors.fix.md
changelog.d/23165_custom_auth_path_access.feature.md
changelog.d/23187_tls_enableable_config_deny_unknown_fields.fix.md
changelog.d/23196_kafka_sink_rate_limit.feature.md
changelog.d/23199_opentelemetry_source_panic_on_nan_attributes.fix.md
changelog.d/23217_interval_ms_modifiable.feature.md
changelog.d/23228_vector_top_uptime.feature.md
changelog.d/5732_multicast_udp_socket_sources.feature.md
changelog.d/aws-auth-session-token.enhancement.md
changelog.d/dnstap_better_errors_timestamp.fix.md
changelog.d/elasticsearch-encoding.fix.md
changelog.d/fix_dnstap_extract_address_logic.fix.md
changelog.d/fix_prometheus_timestamp_parse.fix.md
changelog.d/skip_empty_ecs_metrics.fix.md
distribution/docker/alpine/Dockerfile
distribution/install.sh
website/content/en/releases/0.48.0.md
website/cue/reference/administration/interfaces/kubectl.cue
website/cue/reference/releases/0.48.0.cue
website/cue/reference/versions.cue

This PR prepares the release for Vector v0.48.0
https://github.com/vectordotdev/vector/issues/23257

chore(releasing): prepare v0.48.0 release

---

.github/workflows/integration.yml

Remove useless setup job in integration.yml. Since jobs run in separate pods that job was essentially doing nothing.
Somehow this job was being skipped in the MQ when PRs came in from external contributors which made it so the integration test job was also skipped
- …

fix(ci): integration remove useless setup job

---

changelog.d/23371_metric-tag-values-full-unmodifiable-tags.fix.md
lib/vector-core/src/event/vrl_target.rs

`metrics-tag-values: full` made tags unmodifiable
```yml
sources:
s0:
type: static_metrics
interval_secs: 1
metrics:
- name: response_time
kind: incremental
value:
counter:
value: 1
tags:
a: "b"
transforms:
default_transform:
type: remap
metric_tag_values: full # uncomment to break
inputs:
- s0
source: |-
.tags.a = "override"
sinks:
console:
type: console
inputs:
- default_transform
target: stdout
encoding:
codec: json
json:
pretty: true
```
Run the config and verified that the output tag contained `a: override`. Running this on master will just completely remove all tags.
Closes: #21512

fix(core): `metrics-tag-values: full` made tags unmodifiable

---

src/components/validation/resources/http.rs

The byte size of the decoded frame was used in *received_bytes_total calculations when instead, total size of payload on the wire is desired for comparison against the matching telemetry metric.
Local unit test of my project which depends on Vector

chore(codecs): Compare correct decoded byte size in Validator tests

---

.github/workflows/integration.yml

Only install datadog-ci if int test runs. Before checking if a test should run this is installed, wasting ~30s of ci time for no reason at all.
33*30s = 16.5 mins wasted per PR with no integration tests that should run 
NA
Let ci run
- `cargo clippy --workspace …

chore(ci): only install datadog-ci if int test runs

---

src/sinks/elasticsearch/tests.rs

AWS Auth is only enabled when aws-core is set to true and was causing component features job to fail with unreachable pattern
NA
```
./scripts/check-one-feature sinks-elasticsearch
./scripts/check-one-feature aws-core
./scripts/check-one-feature sinks-vector
```
https://github.com/vectordotdev/vector/actions/runs/16382855653/job/46297556997

fix(elasticsearch sink): match only when feature is enabled

---

.github/workflows/publish.yml
.github/workflows/unit_mac.yml

In publish.yml macos was using latest (bad practice) and in unit_mac.yml the image was now updated to be the arm64 one instead of x86_64.
This should hopefully increase merge queue performance also.
NA
Let CI run

chore(ci): pin macos runner image version

---

lib/vector-buffers/src/variants/disk_v2/tests/basic.rs

Test `reader_exits_cleanly_when_writer_done_and_in_flight_acks` was failing intermittently because it expects data to be immediately ready.
NA
`cargo nextest run -p vector-buffers reader_exits_cleanly_when_writer_done_and_in_flight_acks`
Related failed job: https://github.com/vectordotdev/vector/actions/runs/16504682382/job/46672140564
- Alternatively, we recommend running the …

fix(buffers): wait 1s before panicking in test

---

Cargo.lock
vdev/Cargo.toml

This bumps indicatif to the latest version since 0.17.12 was yanked (only a semver incompatibility).
Changes: https://github.com/console-rs/indicatif/compare/0.17.12...0.18.0
NA
`cargo vdev version`

chore(deps): bump indicatif to 0.18.0

---

.github/workflows/integration.yml

This reverts commit a9366ad55888c85258d0be206710e44a3de389df.
Splunk ITs are timing out again. Looks like it's the same exact issue as before
https://github.com/vectordotdev/vector/issues/22379
- `cargo nextest …

chore(ci): disable splunk ITs

---

.github/workflows/semantic.yml
Cargo.toml
src/sources/websocket/source.rs

Realized that the WebSocket source tests should actually be unit tests instead of integration tests -- after looking at the merge queue I realized the tests weren't triggering (a little late but better than never I suppose)
Related #23449

fix(websocket source): treat websocket source tests as unit

---

changelog.d/23515_max_packet_size_mqtt.feature.md
src/common/mqtt.rs
src/sinks/mqtt/config.rs
src/sources/mqtt/config.rs
website/cue/reference/components/sinks/generated/mqtt.cue
website/cue/reference/components/sources/generated/mqtt.cue

Allow setting max packet size for mqtt source and sink. Before this PR it was using default value from rumqttc of 10240. I kept that default behavior in this PR as well, but now the user can specify a different value to accept/send longer messages.
Reference: https://github.com/bytebeamio/rumqtt/issues/924
Default values in rumqttc:
https://github.com/bytebeamio/rumqtt/blob/005f73caf0c2a808210fd73f2db6e1bc38652c5c/rumqttc/src/lib.rs#L504-L505
```yaml
sources:
src:
type: mqtt
host: localhost
topic: v
max_packet_size: 20000
sinks:
out:
type: console
inputs:
- src
encoding:
codec: json
```
I ran a local mqtt server (`mosquitto -v`) and sent it a big message with `python -c "print('a'*19000)" | mosquitto_pub -t vector -l`., which was then received by vector and outputted to the console. …

feat(config): allow setting max packet size for mqtt source and sink

---

.github/workflows/semantic.yml
changelog.d/proto_codecs.enhancement.md
lib/codecs/src/decoding/format/protobuf.rs
lib/codecs/src/encoding/format/protobuf.rs

This is very similar to the `native` codecs.
I manually tested this while working on https://github.com/vectordotdev/vector/pull/23524
- `cargo nextest run --workspace` (alternatively, you can run `cargo test …

chore(codecs protobuf): allow all telemetry types

---

.github/workflows/changes.yml

A ref can change, this was causing PRs in the MQ to detect changes incorrectly. The ref in the MQ can change but the sha cannot
NA
Let ci run and let it run in the MQ
- `cargo nextest run --workspace` …

fix(ci): use sha instead of ref in changes.yml

---

src/conditions/datadog_search.rs

Searching using the `DatadogSearchRunner` is exposed through the `Conditional` trait. However, due to other use cases (namely VRL), that trait takes ownership of the event and returns a new copy of it. This ownership needlessly complicates the calling convention if we just want to use the search running, as the underlying VRL method only needs to borrow the event. This PR exposes the search interface directly, borrowing the event.
N/A
Unit tests
- We recommend adding a `pre-push` hook, please see [this …

chore(transforms): Expose Datadog search matching directly

---

src/lib.rs
src/nats.rs

Derived from https://github.com/vectordotdev/vector/pull/23554

chore(nats source): make shared nats module public

---

scripts/check-one-feature
src/sources/util/http_client.rs
src/sources/util/mod.rs

Fix the component features check when sources-okta is the only feature
NA
`./scripts/check-one-feature sources-okta`
`/ci-run-component-features`
- `cargo nextest run --workspace` (alternatively, you can run …

fix(dev): fix sources-okta component features check

---

.github/workflows/semantic.yml
lib/vector-vrl/web-playground/build.rs
lib/vector-vrl/web-playground/public/index.js

Mostly ChatGPT generated.
✅ Race conditions loading Monaco & wasm: wrapped in awaitable loaders.
✅ URL state parsing: guards against missing/invalid params.
✅ getState() bug: removed the stray return state; (undefined).
✅ JSONL detection/handling: more robust; trims/ignores blank lines; clearer errors.
✅ Result key mismatch: used res.result consistently (not res.output).
✅ Timezone element: don’t crash if #timezone-input is absent.
✅ Linting toggles: re-enable JSON linting after printing non-JSON errors.
✅ Version badges: don’t crash if the elements aren’t present.
✅ Safer defaults and small guardrails (e.g., lines[1] existence).
Also I fixed the broken VRL url link.
```sh
cd lib/vector-vrl/web-playground/
wasm-pack -v  build --target web --out-dir public/pkg
cd public && python3 -m …
```

fix(vrl playground): various fixes and enhancements

---

.github/workflows/integration.yml

We used to run these twice for internal contributors. 
Now we only run the suite in MQ. This is a cost saving measure.
All contributors can use the recently improved `scripts/run-integration-test.sh` for local development. 
- `make fmt`
- `make check-clippy` (if there are failures it's …

chore(ci): run IT suite once

---

src/config/loading/loader.rs
src/config/loading/mod.rs
src/config/mod.rs
src/secrets/exec.rs
src/signal.rs

This already exists via the `load_from_str` method, however this method does not invoke any secrets infrastructure therefore failing to load configs with strings like `SECRET[...]` as config values.
A new public method called `load_from_str_with_secrets` is exposed which mimics most of the logic in `load_from_paths_with_provider_and_secrets`. 
```
secret:
exec_backend:
type: "exec"
command:
[
/Users/me/workspace/datadog-secret-backend/datadog-secret-backend,
]
protocol:
version: v1_1
backend_type: file.json
backend_config:
file_path: /Users/me/workspace/datadog-secret-backend/secrets.json
sources:
agent:
type: "datadog_agent"
address: "SECRET[exec_backend.SOURCE_DATADOG_AGENT_ADDRESS]"
...
```
Called the newly exposed method with the config above.
- Please read our [Vector contributor …

chore(config): Expose a public way to load a config from str

---

Cargo.lock
changelog.d/utilization.breaking.md
src/utilization.rs

The utilization gauge value precision is now capped.
Technically a breaking change but no one should rely on more precision for this metric.
This change mostly affects debug builds.
Run a simple Vector config with `VECTOR_LOG=debug` and observe the logs:
```text
2025-10-03T20:43:34.286970Z DEBUG vector::utilization: component_id=console utilization=0.0002
2025-10-03T20:43:34.287131Z DEBUG vector::utilization: component_id=t0 utilization=0.0004
2025-10-03T20:43:34.287161Z DEBUG vector::utilization: component_id=t2 utilization=0.0002
2025-10-03T20:43:34.287188Z DEBUG vector::utilization: component_id=t1 utilization=0.0002
```
closes: https://github.com/vectordotdev/vector/issues/23828
- Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#get …

fix!(metrics): limit utilization precision and reduce debug log frequency 

---

vdev/src/testing/config.rs
vdev/src/testing/integration.rs

When I want to run any one of the integration test , I failed with the message `'str' object has no attribute 'get'`. I traced back to the [podman-compose source](https://github.com/containers/podman-compose/blob/v1.5.0/podman_compose.py#L1055) and it give me a hint to the error. It seems that the [`external` type](https://docs.docker.com/reference/compose-file/networks/#external) is boolean instead of string. However, our docker compose generator treat them as string type, which makes the podman compose failed to launch successfully. I fix here to given them concret type. I guess docker compose would tolerate it, but podman compose does not allow it.
```bash
make test-integration-loki
```
AS IS
```bash
❯ make test-integration-loki
cargo vdev --verbose integration test loki
Active …
```

fix(integration test): fix `external` type in `networks` in docker compose file

---

scripts/check-docs.sh

`website/scripts/cue.sh` was deleted but this path was never updated
NA
NA
- Failed run: https://github.com/vectordotdev/vector/actions/runs/18287480920/job/52066219808
- Related: #23951

fix(dev): Fix incorrect cue.sh path

---

website/scripts/typesense-index.ts

Highlights were not showing up in the search, this should fix it
NA
Let website spin up
- Related: #21735

feat(website): add highlights to typesense

---

changelog.d/23717_vector_test_color.feature.md
src/app.rs
src/common/http/server_auth.rs
src/conditions/vrl.rs
src/lib.rs
src/sources/http_client/client.rs
src/transforms/remap.rs

- `vector test` now disables ANSI color when non-interactive (e.g., CI), preventing escape codes in logs.
- All VRL diagnostics (compile errors/warnings, runtime errors) respect the global color setting.
- Minor: fix a logging field typo in runtime init debug message.
```bash
vector test
vector --color always test
vector --color never test
VECTOR_COLOR=always vector test
VECTOR_COLOR=never vector test
vector test | tee out.txt
```
- Verified TTY detection: `--color auto` shows ANSI when run in an interactive terminal, and no ANSI when piped/redirected.
- Forced behaviors validated with `--color always|never` and `VECTOR_COLOR=always|never`.
- Confirmed VRL diagnostics across `validate`, conditions (`src/conditions/vrl.rs`), `remap` transform, HTTP server auth, and HTTP client query …

feat(unit tests):  respect color flag for tests
