vectordotdev/vector

Cargo.lock
deny.toml

Resolves CVE RUSTSEC-2020-0071.

chore(deps): update time

---

deny.toml
lib/codec/Cargo.toml
lib/k8s-e2e-tests/Cargo.toml
lib/k8s-test-framework/Cargo.toml
lib/prometheus-parser/Cargo.toml
lib/tracing-limit/Cargo.toml
lib/vector-wasm/Cargo.toml

Advances toward https://github.com/timberio/vector/issues/5129 by adding
the permissive licenses that don't seem to have any additional
requirements.
Also clarifies the license for ring which has multiple and marks internal packages as not published.

chore(deps): Add some initial allowed licenses to deny.toml

---

lib/file-source/Cargo.toml
lib/file-source/src/checkpointer.rs
lib/file-source/src/fingerprinter.rs

This is just a couple of small tweaks to clean up the file source:
1. We were missing the features for the new tokio usage, but generally got away with it because we use them in the top-level crate. This fixes the `file-source` crate itself.
2. We weren't consistently `snake_case`-ing everything in the new checkpoints json file. This fixes that.

fix(file source): clean up file format and fix features

---

docs/reference.cue
docs/reference/api.cue
docs/reference/urls.cue

This PR adds some basic metadata about the GraphQL API that can be used for the docs site. The structure will likely change over time but I wanted to start schematizing things.

enhancement(external docs): Add Cue sources for GraphQL API

---

.github/workflows/pr.yml
Cargo.toml
Makefile
src/lib.rs

These appear to be unsupported:
https://github.com/jemalloc/jemalloc/issues/843
Build failure: https://github.com/timberio/vector/runs/1428614738

chore(performance): Disable jemallocator background threads on OSX

---

lib/file-source/src/checkpointer.rs
lib/file-source/src/file_server.rs
lib/file-source/src/internal_events.rs
src/internal_events/file.rs

Closes #5137
This clears out old checkpoints before writing to disk and adds some instrumentation around write timing. Checkpoints are considered old when the file they refer to was deleted more than 60 seconds ago, and any updates after "removal" will cancel the expiration.

enhancement(file source): expire checkpoints

---

docs/reference/components/sources/kafka.cue
src/sources/kafka.rs

Fixes: #1150
Fixes: #5143 
Fixes: #800
Modelled after the existing `key_field` configuration I inserted the topic, partition, and offset provided by rdkafka into events when configured. These should be opt-in and not affect users unless explicitly configured.

enhancement(kafka source): include kafka metadata as optional keys

---

src/sources/kubernetes_logs/mod.rs

This PR adds (an opt-in) filling of the ingestion timestamp to the `kubernetes_logs` source.

feat(kubernetes_logs source): Add ingestion timestamp

---

src/http.rs
src/internal_events/http_client.rs
src/internal_events/mod.rs

This PR adds proper instrumentation via the internal events to our HTTP client. It also enables logging the HTTP errors (on the `debug` level, as the callers will also do their own logging of the errors).
Closes #2766.

enhancement(metrics): Instrument the HTTP client

---

.github/workflows/pr.yml
Cargo.toml
Makefile
src/lib.rs

This ended up causing a couple of more issues:
It looks like we might need to disable the background threads for alpine as well:
```
#22 [linux/amd64 stage-1 5/5] RUN ["vector", "--version"]
#22 0.097 <jemalloc>: Error in dlsym(RTLD_NEXT, "pthread_create")
#22 ERROR: executor failed running [vector --version]: buildkit-runc did not terminate successfully
```
(re: the nightly failure https://github.com/timberio/vector/actions/runs/375637227)
I see the OSX build is still failing on master with the jemalloc background_thread issue due the benches feature as well: https://github.com/timberio/vector/runs/1435646011?check_suite_focus=true
I'd sill like to have this, but wanted to get master back to green. We can re-add this week, after resolving these.
Originally enabled in #4845 and an …

chore(ci): Disable jemalloc background_thread

---

benches/topology.rs
tests/tcp.rs

Removes unused `use` that clippy reported. Introduced with #4918.
This PR is just a small fix for master so I'll be merging it as soon as the relevant check passes.

chore: Remove unused `use`

---

docs/reference.cue
docs/reference/configuration.cue

This adds the `data_dir` global option. A case could be made to copy over all of the component options as well, but I'd like to wait on that since it'll significantly increase the resulting file size.

chore: Add global options

---

docs/reference/installation/_interfaces/helm3.cue
docs/reference/installation/_interfaces/kubectl.cue

This PR fixes some issues with the Kubernetes installation docs, in both `helm` and `kubectl` installation methods.
It also establishes some internal structure in the `helm` documentation, so the logic there is easier to follow.

chore(external docs): Correct the Kubernetes installation docs

---

src/internal_events/mongodb_metrics.rs
src/sources/aws_ecs_metrics/mod.rs
src/sources/aws_s3/sqs.rs
src/sources/host_metrics.rs
src/sources/internal_metrics.rs
src/sources/mongodb_metrics/mod.rs
tests/api.rs

When removed old futures from sources I noticed that we use `tokio::select` for shutdown where `StreamExt::take_until` can be used. Also, correct mongo db event name with other metrics sources.

chore: use StreamExt::take_until instead tokio::select!

---

src/app.rs

Dumps an info-level log when the API is disabled:
```
Nov 23 12:31:12.985  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
```
Closes #5156

chore(observability): API disabled log

---

src/metrics.rs

This PR adds an `internal_metrics_cardinality` counter, that exposes the cardinality of the internal metrics registry.
This should help with diagnosing issues like https://github.com/timberio/vector/issues/2356 and it might help with https://github.com/timberio/vector/issues/4582.

enhancement(metrics): Expose internal metrics cardinality as a internal metric counter

---

distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
scripts/check-style.sh

This PR corrects the #5192.
The YAML files are generated and previously were excluded from the style checks. We just correct the ignore list, and regenerate the files.

chore(ci): Fix whitespace in Kubernetes YAMLs (2)

---

docs/reference/installation/_interfaces/kubectl.cue

This PR corrects some functional issues with the existing kustomization instructions.
It also introduces proper version locking at the recommended `kustomization.yaml`, so that users can reliably refer to a particular Vector version, and upgrade as they need (contrary to us pushing a new release).

fix(external docs): Correct the kustomization instructions

---

src/api/server.rs
src/app.rs
src/config/api.rs
src/internal_events/api.rs
src/top/cmd.rs
tests/api.rs

Renames `api.bind` -> `api.address` to match other parts of our config.

chore(config): Rename `api.bind` -> `api.address`

---

docs/reference/components.cue
docs/reference/components/sources/docker_logs.cue

PR #5039 alerted me to the need to allow components to have aliases in the docs, i.e. names that still work in a particular version but are deprecated.

enhancement(external docs): Allow components to have aliases

---

.github/workflows/integration-test.yml
.github/workflows/test.yml

This refactors the CI actions that run on master and PRs to ensure that
master also runs the same tests that PRs run.
This was done by:
* Removing `master.yml` in-lieu of `integration-test.yml` that runs all
of the integration tests, only on master
* Removing `pr.yml` in-lieu of `test.yml` that runs all of the normal
tests, but on both PRs and master

chore(ci): Refactor PR/master CI actions

---

lib/vector-api-client/graphql/schema.json

In PR #5135 I neglected to re-generate the GraphQL JSON schema to reflect some of the changes to inline descriptions. This PR rectifies that.

chore(graphql api): Re-generate GraphQL schema to reflect recent changes

---

src/internal_events/splunk_hec.rs

This PR addresses a small metric naming discrepancy I encountered in my work for #4820.

fix(metrics): Address metric naming discrepancy

---

Cargo.lock
Cargo.toml
benches/default.rs
benches/remap.rs
lib/remap-lang/Cargo.toml
lib/remap-lang/src/expression.rs
lib/remap-lang/src/prelude.rs
lib/remap-lang/src/test_util.rs
src/remap/function.rs
src/remap/function/parse_json.rs
src/transforms/remap.rs

This PR introduces a few convenient macros to the `remap-lang` crate to quickly add tests and benchmarks for individual functions.
It also adds a few benchmarks and tests to get started.
I'll add more in follow-up PRs, but with this merged, everyone can use the new set-up to put more of our functions under test coverage.
Built-in expressions also aren't properly tested/benched yet, these will be tackled in a follow-up PR. This also doesn't cover testing complete remap programs (or the parser specifically), again, these will be tackled separately.

chore(remap): add benchmark and test framework

---

docs/highlights/2020-11-26-0-11-upgrade-guide.md

chore: Add upgrade guide for 0.11

---

src/top/dashboard.rs
src/top/metrics.rs
src/top/state.rs

Refactors `vector top` columns, to group events/byte counts and throughput.
Throughput is now displayed per second, irrespective of sample interval.
Updates columns without metrics to `N/A` to make it clearer that no metrics have been raised. Retains `--` where metrics are available but the sample interval hasn't elapsed.

chore(observability): Top throughput

---

docs/reference/components/sources/internal_metrics.cue
docs/reference/components/sources/kubernetes_logs.cue
src/internal_events/kubernetes_logs.rs
src/sources/kubernetes_logs/parser/cri.rs
src/sources/kubernetes_logs/parser/docker.rs
src/sources/kubernetes_logs/parser/picker.rs
src/sources/kubernetes_logs/parser/test_util.rs

This PR solved some of the issues in the `kubernetes_logs` source that I discovered during my pre-release checking and validation.
Among the changes, it introduces some new metrics in the event parsing and corrects the documentation for the telemetry.

chore(kubernetes_logs source): Kubernetes log parsing corrections

---

docs/reference/components/sources/file.cue
docs/reference/components/sources/internal_metrics.cue
docs/reference/components/transforms/lua.cue
src/internal_events/file.rs
src/internal_events/lua.rs

This PR is basically just another run through the metric names to bring them in line with established conventions, namely:
* All counters should end in `_total`
* Gauges should specify units when applicable

chore(metrics): More metric renaming to match conventions

---

CONTRIBUTING.md
PRIVACY.md

I did a quick review of our contributing and privacy policy language and tried to remove any ambiguity.
1. I relaxed the privacy language about the website since this is likely to change as more people work on the website, run A/B tests, and so on. The data will always be anonymous though.
2. I shortened the "phone home" language but did not change its intent.
3. Removed the mailing list since we do not maintain that anymore.

chore: Adjust privacy policy language

---

scripts/check-docs.sh
scripts/cue.sh

This PR introduces a utility script for CUE command - `scripts/cue.sh`.
It also rewrites the `check-docs` script using the `scripts/cue.sh`.
The goal of the script is to make it easier to use the cue in the everyday life:
- instead of
```shell
find docs -name '*.cue' | xargs cue eval --all-errors -e 'components.sources.kubernetes_logs' -c`
```
- one would simply do
```shell
scripts/cue.sh eval -e components.sources.kubernetes_logs
```
This is far less typing.
See `scripts/cue.sh help` for more info.
Supersedes #5184.

chore: Introduce an utility script for CUE

---

docs/reference/components/sources/host_metrics.cue

Earlier passes missed this particular issue. `host` is the default namespace for these but that is not hard-coded into the metric names.

fix(external docs): Remove hard-coded `host` namespace from host_metrics

---

Cargo.lock
Cargo.toml

Bumps to async-graphql 2.1.6.
Some fixes for fragments, Apollo Tracing (which we're not currently using, but might be useful later) and general bug fixes.
@sghall - tagged you for a quick sanity check that the web client still works as expected.

chore(graphql api): Async-graphql 2.1.6

---

Cargo.lock
lib/vector-api-client/Cargo.toml
src/top/cmd.rs

ping @leebenson 
This PR enables TLS subscription connections and allows users to get the error message on connection failures. 
I noticed that I could not connect to a remote instance using secure sockets in `vector top --url <some url>`.    I first added a log of the actual error which showed like this:
```
Couldn't connect to Vector API via WebSockets: Url("TLS support not compiled in.")
```
I think we should keep that so users can get a little more info when something goes wrong (optional).  We could also, use the same strategy for the other errors in this file (glad to add here).   So the fix was to enable the TLS feature in `tokio-tungstenite` and it now works against the remote instance.

enhancement(observability): Enable TLS subscription connections in vector top

---

docs/reference/remap.cue
docs/reference/remap/ceil.cue
docs/reference/remap/floor.cue
docs/reference/remap/format_number.cue
docs/reference/remap/parse_syslog.cue
docs/reference/remap/parse_timestamp.cue
docs/reference/remap/round.cue

This fixes the documentation errors noticed by [Steve](https://discordapp.com/channels/742820443487993987/751109034827972709/782782924541394965).
In the process I noticed that documentation was missing for a number of functions. So this also adds docs for:
- `ceil`
- `floor`
- `round`
- `parse_syslog`

chore(external docs): Remap documentation fixes

---

Cargo.lock
Cargo.toml
src/internal_events/mod.rs
src/internal_events/pulsar.rs
src/list.rs
src/sinks/papertrail.rs
src/sinks/pulsar.rs
src/sinks/util/encoding/config.rs
src/sinks/util/encoding/mod.rs
src/sinks/util/encoding/with_default.rs

enhancement(pulsar sink): introduce encoding schema and pulsar avro schema

---

.github/workflows/benches.yml

I neglected that this would always be the case on the first run. I'm
coming around to allowing them to run without anyway.

chore(ci): Allow benchmarks to run without baseline

---

lib/file-source/src/checkpointer.rs
lib/file-source/src/file_server.rs
lib/file-source/src/fingerprinter.rs
src/sources/file.rs
src/sources/kubernetes_logs/mod.rs

Closes #5088
This change makes the file source use checksums of the first line of the file no matter which checksum strategy is configured. The old configuration is left in place for now to facilitate an automated migration on startup that upgrades existing bytes-based checksums to the new line-based version.
The one gotcha at this stage is around compressed files. If a gzipped file is smaller than the maximum allowed line length (default 100kb), we will currently not return a checksum and not read the file. This is because we need some fixed stopping point to make the checksum stable, and EOF is not that. This will be fixed by #5085.

enhancement(file source): unify checksum methods

---

Cargo.lock
Cargo.toml

Fixes `make check-version`: https://github.com/timberio/vector/runs/1484814549?check_suite_focus=true

chore: Bump version to 0.12.0 now that 0.11.0 is released

---

scripts/release-github.sh

This interpolation didn't work, I assume it's due to the use if `'`.

chore: Fix release-github.sh VERSION interpolation

---

.github/workflows/benches.yml

Uploading many small files in GA seems to be resulting in some number of
them failing: https://github.com/timberio/vector/actions/runs/395559899
This change archives them first using zip and uploads this artifact.
This is how Github stores them anyway.

chore(ci): Archive bench artifacts before uploading

---

scripts/release-helm.sh

chore(ci): Correct the version notation for the nightly Helm charts

---

Cargo.lock
distribution/helm/vector-agent/templates/configmap.yaml
distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/templates/podmonitor.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/configmap.yaml
distribution/helm/vector-aggregator/templates/podmonitor.yaml
distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_metrics.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
lib/k8s-e2e-tests/Cargo.toml
lib/k8s-e2e-tests/src/lib.rs
lib/k8s-e2e-tests/src/metrics.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-test-framework/src/exec_tail.rs
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/lib.rs
lib/k8s-test-framework/src/log_lookup.rs
lib/k8s-test-framework/src/port_forward.rs
scripts/test-e2e-kubernetes.sh

This PR adds support for exposing `internal_metrics` via a `prometheus` sink in out Helm charts out of the box.
It also adds opt-in Prometheus annotations to `Pod` (`prometheus.io/scrape: "true"` and etc) and `prometheus-operator`-powered `PodMonitor` to simplify the integration into the existing cluster monitoring pipelines.
Closes #3799.
To do:

enhancement(kubernetes platform): Support exposing internal mertics out of the box in our Helm charts

---

src/sinks/aws_cloudwatch_metrics.rs
src/sinks/datadog/metrics.rs
src/sinks/influxdb/metrics.rs
src/sinks/prometheus/exporter.rs
src/sinks/statsd.rs

Adds `namespace` alias to `default_namespace` options that replaced `namespace` options in #4806.

chore: Add `namespace` alias for `default_namespace`

---

distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml

Fixes logging feedback loop between vector-aggregator and vector-agent.
Ref: https://github.com/timberio/vector/runs/1498792526

fix(kubernetes platform): Add exclusion label at vector-aggregator

---

src/config/format.rs

Test fail if required features are not enabled, so we need `cfg`.
Test added in #5005.

fix(tests): include config format test only with required features

---

docs/reference/components/sources/internal_metrics.cue
docs/reference/components/sources/mongodb_metrics.cue
docs/reference/components/sources/nginx_metrics.cue
docs/reference/components/sources/prometheus_remote_write.cue
src/internal_events/elasticsearch.rs
src/internal_events/mongodb_metrics.rs
src/internal_events/nginx_metrics.rs
src/internal_events/prometheus.rs
src/internal_events/splunk_hec.rs
src/sinks/elasticsearch.rs

@jszwedko should we also rename `request_error_total` => `requests_error_total` and `request_read_errors_total` => `requests_read_errors_total` (because we have `requests_completed_total` / `requests_received_total`)?
```
$ grep 'counter!\("request.*?"' -rhoP src/internal_events/ | sort -u
counter!("request_error_total"
counter!("request_read_errors_total"
counter!("requests_completed_total"
counter!("requests_received_total"
```
edit:
**Changes**:
- `events_processed_total` => `processed_events_total` (prometheus)
- `request_received_total` => `requests_received_total` (splunk_hec)
- `request_error_total` => `request_errors_total` (mongo, nginx)

chore: unify metric names

---

src/conditions/remap.rs
src/internal_events/remap.rs
src/transforms/remap.rs

Closes #4000 
Note it seems these events do not update the errors column in `vector top`. It is possible there is an error here, or in `vector top` which may be surfaced in  #5329.
@leebenson  does it look like these have been defined correctly?

chore(remap transform): update events for remap transform

---

src/sinks/splunk_hec.rs

CI integration test fix (https://github.com/timberio/vector/pull/5418#issuecomment-739990577)
In our docker image used in CI we have only `custom_index`, so the rendered value should be `custom_index` instead `rendered_value`.

chore(splunk_hec sink): fix test splunk_index_is_interpolated

---

src/generate.rs

Added in #4819 
Test should not be compiled without required features.

fix(tests): require features for generate_configfile test

---

src/http.rs

Leaving `Accept-Encoding` out lets the server decide what encoding to
use (very similar to `Accept-Encoding: *`). Currently, we only support
uncompressed responses (ref:
https://github.com/timberio/vector/issues/5440) so this sets
`Accept-Encoding: identity` to indicate this.
Ref: https://tools.ietf.org/html/rfc7231#section-5.3.4

enhancement: Set Accept-Encoding to identity for HTTP client

---

distribution/install.sh

Closes #5415 
This is going to need careful eyes over. Basically:
1. Replaced ldd -version check with a function (get_gnu_musl_glibc)
2. This command runs ldd --version
3. If GNU then extracts glibc version and compares (using bc because bash doesn't speak float) to 2.18. If earlier it returns 'musl' otherwise returns 'gnu'
4. If musl then returns 'musl'.

fix(setup): Add support for detecting glibc version to installer script

---

lib/remap-lang/src/expression.rs
lib/remap-lang/src/expression/array.rs
lib/remap-lang/src/expression/path.rs
lib/remap-lang/src/prelude.rs
lib/remap-lang/src/test_util.rs
lib/remap-lang/src/value/object.rs
src/event/mod.rs
src/remap/function/flatten.rs
src/remap/function/parse_json.rs
src/remap/function/to_bool.rs
src/remap/function/to_float.rs
src/remap/function/to_int.rs
src/remap/function/to_string.rs
src/remap/function/to_timestamp.rs
src/test_util/mod.rs

High-level changes:
* Allow function tests to fail individually (this was introduced in an earlier PR, but now applied to the `flatten` function tests as wel)
* Make it easier to work with commonly used remap types in tests (`Value`, `Array`, and soon `Map`)
Specific changes:
* add `value` macro to quickly create `remap::Value` types in tests
* change `array` macro to create an `expression::Array` (again often used in tests)
* remove `map` macro (will be reintroduced in #5279 to create `expression::Map`)
* add a few more `{Try}From` impls to go to/from different wrapper types
* update `flatten` function tests to use new set-up

chore(remap): improve test helpers

---

docs/reference/components/transforms/remap.cue

This fixes the `remap` transform example [used in the docs](https://vector.dev/docs/reference/transforms/remap/).

chore(external docs): Fix remap example

---

docs/reference/components.cue
docs/reference/components/transforms/filter.cue

Addresses #5495 by updating the filter transform docs to correctly indicate that metrics can be used as inputs.

fix(external docs): Specify that the filter transform takes metric inputs

---

docs/reference/components.cue

The table of timestamp options seen in docs like the [grok_parser](https://vector.dev/docs/reference/transforms/grok_parser) docs has a small syntax error involving a non-escaped slash.

fix(external docs): Fix timestamp info table syntax error

---

docs/reference/components/transforms/geoip.cue

Oops! This one snuck past us and has broken the `master` build.

fix(external docs): Fix syntax error in geoip.cue

---

lib/remap-lang/grammar.pest
lib/remap-lang/src/expression/arithmetic.rs
lib/remap-lang/src/operator.rs
lib/remap-lang/src/parser.rs
lib/remap-lang/src/value.rs
tests/behavior/transforms/remap.toml

Closes #3729 
Discussion in that issue stalled, so I have moved forward to try to satisfy all the issues raised there..
This PR makes two changes. 
- Ordinary division is now always float division. Before, if the first parameter was an Integer it would be Integer division. So `9 / 12 == 0`. Now it will be `9 / 12 == 0.75`. It does mean that even if the result is a whole number it will be a float - `4 / 2 == 2.0` 
- There is a new integer division operator - `//`. So `9 // 12 == 0`. Float parameters are cast to an integer.

enhancement(remap): add integer division

---

lib/k8s-e2e-tests/src/metrics.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs

This PR fixes the failing Kubernetes E2E tests.
The issue was in the test code, not in our app code, and the patch improves the test code to allow for more flexibility, effectively allowing the current app state (which is valid really and shouldn't fail the tests).

fix(kubernetes platform): Correct the prometheus format parsing at K8s E2E tests for the metrics pipeline

---

src/conditions/remap.rs

Broken in master: https://github.com/timberio/vector/runs/1547837589#step:9:1063
It is a bit odd that the error message differs from the tests below it in that includes "to an error", but this fixes it at least.

chore(ci): Fix conditions::remap::test::check_remap null check

---

.github/CODEOWNERS

I added Jean (@JeanMertz) for all remap functions and Stephen (@FungusHumungus) only for components that he added.
@FungusHumungus is this looks good for you or change for all remap components?

chore(remap): add owners to `.github/CODEOWNERS`

---

distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_labels.tpl
distribution/helm/vector-shared/templates/_reroll.tpl
distribution/helm/vector/values.yaml
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml

This PR adds two new parameters to the Helm charts: `podRollmeAnnotation` and `podValuesChecksumAnnotation`. See the diff to learn more about them.
It also restructures the internals of the Helm charts to share the annotation logic.
It also corrects the config checksum calculation logic by switching it to checksumming the evaluated config, rather than some odd behviour. The code we had there came from the official Helm docs, so was a bit surprising to find issues with it.
Closes #5524.

fix(kubernetes platform): Implement improvements to the Pod recreation on Helm release upgrades

---

Cargo.toml

[avro-rs](https://crates.io/crates/avro-rs) was added in #5021 for pulsar sink, but not marked as an optional dependency.

chore(deps): make avro-rs optional

---

docs/reference/remap/del.cue
docs/reference/remap/only_fields.cue

Field names can be of the form `."foo"` but not `".foo"`.

chore(external docs): Fix field name examples in Remap docs

---

Cargo.lock
Cargo.toml

chore(graphql api): async-graphql 2.2

---

src/internal_events/vector.rs
src/sinks/vector.rs

While checked internal events in sinks I noticed that we duplicate events/bytes for vector sink. Vector sink uses TcpSink from util which emit event internally:
https://github.com/timberio/vector/blob/ed31012bdf8fcf11b4862b49eaf28c55d306f02a/src/sinks/util/socket_bytes_sink.rs#L70-L74

fix(vector sink): remove duplicated event

---

Cargo.lock
Cargo.toml

This PR fixes (or rather is supposed to be fixing) the issue with docker that was reported earlier today.
Once merged, we'd want to backport it to 0.11 and ship with 0.11.1.
This is a hotfix, a proper resolution will be to simply bump the hyper once they cut a release.

fix(docker_logs source): Update hyper to work around the docker EOF errors

---

Cargo.lock
Cargo.toml
src/metrics.rs

Replacement of #5516. Except `metrics-tracing-context` this PR also update `metrics-util` and `metrics`.

chore(deps): bump metrics crates

---

distribution/helm/vector-agent/templates/configmap.yaml
distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-shared/templates/_metrics.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
lib/k8s-e2e-tests/src/metrics.rs
lib/k8s-e2e-tests/tests/vector-agent.rs

This PR adds a built-in host metrics source to our Helm charts and exposes it via the built-in Prometheus sink. It also applies other necessary changes to make host metrics work in the Kubernetes environment.
Closes #4163.
To do:

enhancement(kubernetes platform): Expose host metrics in our Helm charts out of the box

---

Cargo.lock
Cargo.toml
lib/remap-functions/src/parse_syslog.rs

Closes #5441 
Updates `syslog_loose` to v0.6.0 which handles missing priority fields. Now if that field is missing or invalid it defaults to 13 - `LOG_USER` and `SEV_NOTICE`. As a result, these fields are now always present in every message.

fix(syslog source): priority now defaults to 13, so is never missing

---

docs/reference/remap.cue
docs/reference/remap/redact.cue

This PR adds CUE sources for the `redact` function in Remap. I am aware that this function will likely change in the near term but I think it'd be beneficial to have this initial doc in place.

enhancement(external docs): Add docs for redact function for TRL

---

Makefile

it is a known `cross` issue/limitation (but perhaps not well documented) that running `cargo build --target $T`-like commands and then `cross build --target $T`-like commands (where `$T` is the target triple of the host) can cause runtime errors like "GLIBC symbol not found".
This is because the first `cargo build` (which runs outside docker) may produce build script artifacts (binaries / ELFs) that depend on a recent glibc; invoking `cross build` after that makes Cargo reuses those build scripts and run them *inside* the docker container, which (intentionally) has an old glibc. The issue is avoid by invoking `cargo clean` before using `cross`.
in the CI of this repo, this is only a potential issue for the `cross-build-x86_64-unknown-linux-gnu` target because `cargo install` (which does …

chore(ci): `cargo clean` before using cross

---

scripts/check-criterion-output.sh

Until we can reduce measurement noise as part of
https://github.com/timberio/vector/issues/5394 as, even if the workflow is marked to allow failures, it still marks the suite of checks as failing.

chore(ci): Always pass benches workflow

---

lib/remap-functions/Cargo.toml

The `syslog_loose` crate is now specified in two places. `vector/Cargo.toml` and `vector/lib/remap-functions/Cargo.toml`.
#5452 updated the version in `vector`, but not in `remap-functions`. This should bring them back into line and fix the failing test on master.

chore(remap): update syslog_loose version in remap-functions

---

docs/reference/components/sinks/elasticsearch.cue
docs/reference/urls.cue
src/sinks/elasticsearch.rs

Adds a configuration option to specify 'index' (default) or 'create' (for data streams)
Related: https://github.com/timberio/vector/issues/4939

enhancement(elasticsearch sink): add support for data streams

---

src/sources/file.rs

Closes #3780 
It seams #4196 happened less in recent weeks so we can verify if the test has been fixed for Mac OS.

chore(tests): Enable test `sources::file::tests::remove_file` for Mac OS

---

lib/remap-functions/src/lib.rs

In #5541 I neglected to add the new `includes` function to the Remap CLI.

chore(remap): Add includes function to TRL

---

lib/remap-functions/src/includes.rs
lib/remap-lang/src/type_def.rs

Introduced by https://github.com/timberio/vector/pull/5541. It currently causes a failing test on master: https://github.com/timberio/vector/runs/1580208153#step:9:740 . The test was correct, but the implementation didn't satisfy it.
Previously it was merging the type definitions of an array and a scalar
resulting in the type def, though the kind was Boolean, still having an
inner_type_def defined as the inner_type_def of the array.

fix(remap): Fix type definition for `includes()`

---

Cargo.lock
Cargo.toml
lib/k8s-e2e-tests/Cargo.toml
lib/k8s-test-framework/Cargo.toml

Instead of merging each PR from dependabot separately, I decided to try to join them in one:
- `anyhow: 1.0.32 => 1.0.36`
- `assert_cmd: 1.0.1 => 1.0.2` https://github.com/timberio/vector/pull/5618
- `inventory: 0.1.9 => 0.1.10` https://github.com/timberio/vector/pull/5621
- `k8s-openapi: 0.9.0 => 0.10.0` https://github.com/timberio/vector/pull/5622
- `seahash: 3.0.7 => 4.0.1` https://github.com/timberio/vector/pull/5620
- `sha-1: 0.9.1 => 0.9.2`
- `snafu: 0.6.9 => 0.6.10`
- `toml: 0.5.7 => 0.5.8`

chore(deps): bump deps

---

src/sinks/util/buffer/metrics.rs

While investigating #5589, I did some reductive work to simplify the tests for the metrics batch buffer. This doesn't actually change what is tested, it just reduces the amount of code needed to do so.

chore(metrics): Refactor metrics batch buffer tests

---

docs/reference/remap/parse_grok.cue
lib/remap-functions/src/parse_grok.rs
tests/behavior/transforms/remap.toml

Closes #4482 
Added a new `remove_empty` parameter to `parse_grok` - defaulting to false, that if set will remove any empty matches from the result.

enhancement(remap): added remove_empty parameter to parse_grok

---

docs/reference/components/transforms/remap.cue

Remap works with Metrics data now, but the docs need updating.
We need to document somewhere that Remap for metrics will only work with the following paths:
- `.name` - Read and Write
- `.namespace` - Read and Write
- `.timestamp` - Read and Write
- `.kind` - Read and Write - must be either "absolute" or "incremental"
- `.tags` - Read and Write - tags are specified by adding an extra segment, eg. `.tags.host`, `.tags.foo`
- `.type` - Read only - the type of the metric (will be "counter", "gauge", "set", "distribution", "aggregated histogram" or "aggregated summary")
I'm not sure of the right place in the docs to put this, any ideas?

enhancement(remap transform): docs for remap transform metrics

---

.github/workflows/nightly.yml
.github/workflows/release.yml
Makefile
distribution/debian/scripts/postinst
distribution/debian/scripts/preinst
docs/reference/installation/downloads.cue
scripts/package-deb.sh
scripts/package-rpm.sh

This PR.
1. Removes the extra musl-scaffolding we put in place until Cross supported glibc builds earlier than 2.18.
2. Hardens up the Debian pre and post inst scripts to cater for some edge cases with earlier versions of Debian and Ubuntu. Also I hate systemd.

chore(ci): Removed musl scaffolding and harden Debian packaging

---

docs/reference/components/sinks/pulsar.cue
docs/reference/components/sinks/splunk_hec.cue
docs/reference/components/sources/internal_metrics.cue
src/internal_events/pulsar.rs
src/internal_events/splunk_hec.rs
src/sinks/splunk_hec.rs

When reviewed #5651 found that `pulsar` do not have metric `encode_errors_total`. Also updated `telemetry` in docs for `pulsar` / `splunk_hec`.

chore(pulsar sink): add metrics to failed encode

---

lib/remap-lang/src/value.rs
tests/behavior/transforms/remap.toml

Closes #5523 
This raises an error if you try to divide by zero in Remap.
Previously, if you do integer division, it would panic Vector. With float division it would not panic, but would return Infinity, which could contribute to strange results (see #5530).

fix(remap): Remap should error on divide by zero

---

src/sources/journald.rs

Closes #5617 
Now if an array is not a valid integer sequence (non-ASCII string) value will be serialized as a string,

fix(journald source): handle incorrect int sequences as strings

---

Makefile
benches/remap.rs
lib/remap-lang/src/test_util.rs

Also adds them to CI so that we should catch it if they break again.
@FungusHumungus I'm not super confident with my fix to the `map` macro here. I'd appreciate your :eyes: 
The error I was resolving was:
```
error[E0277]: the trait bound `remap_lang::Value: From<remap_lang::expression::Map>` is not satisfied                                                                         
--> benches/remap.rs:39:1                                                                                                                                                      |                                                                                   
39 | / bench_function! {                                                               
40 | |     parse_json => remap_functions::ParseJson; …
```

chore(ci): Fix remap benches

---

src/internal_events/http_client.rs

close #5684 
I've scanned the list of standard headers in https://docs.rs/http/0.2.2/http/header/index.html and picked some potentially sensitive headers.

chore: Do not print sensitive headers

---

scripts/environment/bootstrap-ubuntu-20.04.sh
scripts/upgrade-docker.sh

Small fix to the bootstrap / installation scripts which break on the Docker installation when running on an arm64 host / container.
Ran this on a machine with Apple's M1 chip and the [Docker Apple M1 Tech Preview](https://docs.docker.com/docker-for-mac/apple-m1/).

chore(dev): Fix docker installation in dev environment on arm64

---

docs/reference/components.cue
docs/reference/components/sinks.cue
docs/reference/components/sinks/aws_cloudwatch_logs.cue
docs/reference/components/sinks/aws_kinesis_firehose.cue
docs/reference/components/sinks/aws_kinesis_streams.cue
docs/reference/components/sinks/aws_s3.cue
docs/reference/components/sinks/aws_sqs.cue
docs/reference/components/sinks/clickhouse.cue
docs/reference/components/sinks/datadog_metrics.cue
docs/reference/components/sinks/elasticsearch.cue
docs/reference/components/sinks/gcp_cloud_storage.cue
docs/reference/components/sinks/gcp_pubsub.cue
docs/reference/components/sinks/gcp_stackdriver_logs.cue
docs/reference/components/sinks/honeycomb.cue
docs/reference/components/sinks/http.cue
docs/reference/components/sinks/humio.cue
docs/reference/components/sinks/influxdb_logs.cue
docs/reference/components/sinks/influxdb_metrics.cue
docs/reference/components/sinks/logdna.cue
docs/reference/components/sinks/loki.cue
docs/reference/components/sinks/new_relic_logs.cue
docs/reference/components/sinks/prometheus_remote_write.cue
docs/reference/components/sinks/sematext_logs.cue
docs/reference/components/sinks/splunk_hec.cue
src/sinks/elasticsearch.rs
src/sinks/http.rs
src/sinks/new_relic_logs.rs
src/sinks/sematext/logs.rs
src/sinks/util/http.rs

Closes #4202 
Moves `headers` option in:
* `http` sink
* `elasticsearch` sink

chore(config): Move root level `headers` option to `request.headers` 

---

scripts/version.sh

On some awks it was failing due to an unnecessary escape! So we removed it.
Fixes https://github.com/timberio/vector/issues/5306

fix: Fixup version script

---

.github/workflows/benches.yml

I noticed in PR #3740, which is a docs-only PR, that the benchmark suite was run. To me, the benchmarks should be run only when truly necessary. This PR adds a `paths` parameter in the benchmark Action definition so that the benchmarks are only run when the Vector sources are updated and excludes everything else, like the `README`, the docs, the `Makefile, the RFCs, etc. The selection of paths was a bit guesswork-y on my part, so please do provide feedback so we don't remove anything that needs to remain.

chore(ci): Restrict usage of benchmark runs

---

.github/workflows/nightly.yml
.github/workflows/release.yml

To avoid apt prompting for things like configuring tzdata
Should fix https://github.com/timberio/vector/runs/1620351155?check_suite_focus=true#step:4:594

chore(ci): Set DEBIAN_FRONTEND for nightly and release workflows

---

.github/workflows/benches.yml
scripts/upload-benchmarks-s3.sh

This will allow us to analyze it with Athena.
I originally included group, function, and value in the object path to
be used for partitioning the data in Athena, but ran into issues with
the maximum partition length of 256. Instead all benchmark data for
a given run is concatted together (which includes the group, function,
and value).
The partitioning scheme was chosen to allow for comparisons across:
* Time for a given configuration (OS, allocator, etc.) for a given
benchmark
* Across configurations (e.g. comparing different allocators) for
a given benchmark
Corresponding Terraform PR for the AWS Glue Database bits: https://github.com/timberio/resources/pull/10

chore(ci): Upload criterion output data to S3

---

src/sources/syslog.rs

I fixed tests so in next year they will not fail :laughing:

fix(syslog source): do not use static year in tests

---

src/event/discriminant.rs
src/internal_events/socket.rs
src/lib.rs
src/mapping/parser/mod.rs
src/prometheus.rs
src/sinks/gcp/cloud_storage.rs

While checked [needless_lifetime](https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes) rule in https://github.com/timberio/vector/pull/5771#discussion_r550790780 found that [trivially_copy_pass_by_ref](https://rust-lang.github.io/rust-clippy/master/#trivially_copy_pass_by_ref) can be useful.

chore: add clippy rule trivially_copy_pass_by_ref

---

docs/reference/remap/to_int.cue
lib/remap-functions/src/to_int.rs

Closes #5730.
Enables users to pass timestamps to the `to_int` function to get the Unix time elapsed rather than needing to use `format_timestamp` and pass in `%s` as the format. The discussion around this appears to be a bit unsettled so I'm happy to defer to others on the desired end state here.

enhancement(remap): Enable casting timestamps into integers

---

.github/workflows/nightly.yml
.github/workflows/release.yml
Makefile
distribution/docker/alpine/Dockerfile
distribution/docker/distroless-libc/Dockerfile
distribution/docker/distroless-static/Dockerfile
scripts/build-docker.sh
scripts/release-docker.sh
scripts/test-e2e-kubernetes.sh

Our Docker build and release process relies on a twisty-path of shell scripts. This removes several pieces from the shell scripts and puts them into GitHub Actions actions inside our nightly and release workflow. Specifically, we remove the qemu and buildx steps from the script and replace them with actions. 

chore(ci): Refactor Docker build and release

---

Cargo.lock
Cargo.toml
benches/regex.rs
src/sources/util/fake.rs
src/test_util/mod.rs
tests/syslog.rs

Looks like #5811 trigger `dependabot` update. This PR includes:
- `approx` #5818
- `dirs-next` #5815 
- `itertools`
- `rand`
- `rand_distr`
- `cargo update --aggressive`
I leaved `tui` not updated for @leebenson (https://github.com/timberio/vector/issues/5289)

chore(deps): update

---

scripts/build-docker.sh
scripts/test-e2e-kubernetes.sh

Adds the docker push guard back into our CI scripts to fix k8s e2e test failure

fix(ci): Adds docker push guard back into CI scripts

---

.github/workflows/k8s_e2e.yml

chore(ci): Notify discord for failing k8s tests on master

---

lib/remap-functions/src/assert.rs
lib/remap-functions/src/contains.rs
lib/remap-functions/src/ends_with.rs
lib/remap-functions/src/ip_subnet.rs
lib/remap-functions/src/ip_to_ipv6.rs
lib/remap-functions/src/match.rs
lib/remap-functions/src/parse_grok.rs
lib/remap-functions/src/parse_url.rs
lib/remap-functions/src/redact.rs
lib/remap-functions/src/split.rs
lib/remap-functions/src/tokenize.rs
lib/remap-functions/src/truncate.rs
lib/remap-lang/src/function.rs
lib/remap-lang/src/value.rs

This adds a `Value::try_bytes_utf8_lossy` method, which basically merges these steps:
```rust
let value = self.value.execute(state, object)?;
let bytes = value.try_bytes()?;
let string = String::from_utf8_lossy(&bytes);
```
Into:
```rust
let value = self.value.execute(state, object)?;
let string = value.try_bytes_utf8_lossy()?;
```
This pattern is used so much throughout function impls, that I figured it was a worthy helper method to have.
I didn't update all cases yet, but we can do that as we move forward.

chore(remap): add "try_bytes_utf8_lossy" helper method

---

Cargo.lock
Cargo.toml
lib/derive_is_enum_variant/Cargo.toml
lib/derive_is_enum_variant/src/lib.rs
lib/derive_is_enum_variant/tests/tests.rs
lib/portpicker/Cargo.toml
lib/portpicker/src/lib.rs
src/test_util/mod.rs

Part of #5738 
This PR add [portpicker-rs](https://github.com/Dentosal/portpicker-rs) and [is_enum_variant](https://github.com/fitzgen/derive_is_enum_variant) abandoned crates to `lib`.

chore(deps): put `portpicker` and `is_derive_enum` to lib

---

.github/workflows/benches.yml
.github/workflows/test.yml
scripts/environment/bootstrap-ubuntu-20.04.sh

As Github Actions workflow label specifications will let jobs run on runners
that have a superset of the labels, we want to ensure that unit tests don't end
up running on benchmark runners given they are optimized for running
benchmarks where unit tests would likely benefit from hyperthreading and
using all available CPUs.
Admittedly, I'm using labels here to identify runner "roles" rather than
capabilities, as they seem to be intended for, but, for benchmarks, we
really do want to ensure they run on very specific runners that other
tests are not likely to want to run on.
I've applied the labels manually to existing, manually configured,
runners.
Ref: https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow
Signed-off-by: …

chore(ci): Restrict self-hosted workflows to specific runners

---

src/buffers/mod.rs
src/sink.rs
src/topology/builder.rs
src/topology/fanout.rs
src/topology/mod.rs
src/topology/task.rs

Closes #5776
Besides upgrading buffers to tokio channels, upgrades the rest of buffer interface to futures03. With that, disk buffers can be upgraded to futures03 independently.

chore(buffers): Upgrade to tokio channels

---

.github/workflows/benches.yml
Makefile

Build benchmarks on all CPUs first, and then run on the isolated CPU
(always 0).
Should be merged after https://github.com/timberio/vector/pull/5850

chore(ci): Run benchmarks on isolated CPU

---

.github/workflows/nightly.yml

I think the notifications are noisy for adhoc PR runs where the author
is likely checking on it.

chore(ci): Only notify failed nightly builds on master

---

benches/batch.rs
benches/buffering.rs
benches/event.rs
benches/files.rs
benches/isolated_buffering.rs
benches/lookup.rs
benches/lua.rs
benches/regex.rs
benches/remap.rs
benches/template.rs
benches/topology.rs
benches/wasm/mod.rs

Configure the noise thresholds for various benchmark groups based on the
findings in https://github.com/timberio/vector/issues/5394 when we ran
8 runs in parallel, 50 times, on our benchmark runner.
I didn't actually run the wasm benches as part of that test so just
configuring to 0.05 for now, but we can see.
Should merge after #5850 

chore(ci): Configure criterion noise thresholds

---

lib/remap-lang/grammar.pest
lib/remap-lang/src/expression/arithmetic.rs
lib/remap-lang/src/lib.rs
lib/remap-lang/src/operator.rs
lib/remap-lang/src/parser.rs

This PR adds support for the error coalescing operator `??`:
```rust
<lhs exp> ?? <rhs expr>
```
`rhs` is evaluated if `lhs` returns an error. This operator can be chained to try multiple expressions until one succeeds (or returning the error of the most rightward expression):
```rust
<expr 1> ?? <expr 2> ?? <expr 3>
```
It allows you to handle error-cases of expressions in a succinct way.
For example, trying to parse a message value using multiple regex patterns:
```rust
. = parse_regex(.message, /^(?P<timestamp>[^\\]]+) \\[(?P<level>\\w+)\\] (?P<pid>[0-9]+)#(?P<tid>[0-9]+): \\*(?P<cid>[0-9]+) (?P<message>.*)$/) \
?? parse_regex(.message, /client: (?P<client>[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})/) \
?? parse_regex(.message, /server: (?P<server>[^,]+)/) \
?? .
```
This …

feat(remap): add error coalescing operator

---

scripts/check-criterion-output.sh
scripts/parse-criterion-output.awk

I found this useful to look at.
Also default throughput values to "unknown" given they are sometimes null to align the table columns when they are missing.

chore(ci): Show p value for criterion benchmark table output

---

src/config/validation.rs

Minor spelling mistake in a variable name.

fix: Addressed minor spelling error in variable

---

docs/reference/components/sinks/gcp_stackdriver_logs.cue

chore(gcp_stackdriver sink): Make `resource` required in docs

---

benches/remap.rs

This PR removes a benchmark function that is bound to fail given changes introduced in #5745, specifically the removal of all `default` args in VRL functions.

fix(remap): Remove errant VRL benchmark

---

src/config/watcher.rs

The `file_update` test was flaky on mac https://github.com/timberio/vector/pull/5821/checks?check_run_id=1644393968 hopefully this was the cause.

chore(tests): Register signal handler before causing signal

---

src/sinks/util/http.rs
src/sinks/util/service.rs

Closes #5920 
A case of serde-rs/serde#1504.

fix(config): Avoid alias `in_flight_limit`

---

docs/reference/urls.cue

https://github.com/timberio/vector/actions/runs/476368665

fix(external docs): Fix cue formatting

---

scripts/build-docker.sh
scripts/test-e2e-kubernetes.sh

This is a follow-up after the #5848. That PR missed a case of non-native docker image builds, so we fix the soundness of this logic.
At the same time, we switch to an easier to use env var value-based condition from the env var presence condition.

chore(ci): More consistent docker push logic

---

docs/reference/remap/compact.cue
lib/remap-functions/src/compact.rs
lib/remap-functions/src/is_nullish.rs
lib/remap-functions/src/util.rs

Closes #5577 
This adds the `nullish` parameter to the `compact` Remap function.
Note, the issue asks for the parameter to be called `blank`, but I am calling it `nullish`, inline with the `is_nullish` function.
@lucperkins  I'm wondering about the docs, there is a section here I've just copied from the `is_nullish` function. Is there a better way we can do it to share the text?

enhancement(remap): added `nullish` parameter to `compact`

---

docs/reference.cue
docs/reference/remap/parse_json.cue
docs/reference/remap/parse_regex_all.cue

Uses the `#Event` definition so that we can signal if the event is a log or metric in Remap examples.

chore: Switch Remap to #Event definition

---

lib/remap-functions/src/redact.rs

This PR fixes the type definition for the `redact` function to indicate its fallibility. Going over this function, though, raised the following question for me.
In several functions, including `redact`, the work of handling non-required arguments happens during the `compile` step, which allows for a "cleaner" function struct that isn't just a placeholder for multiple `Box<dyn Expression>` values:
```rust
struct RedactFn {
value: Box<dyn Expression>,
filters: Vec<Filter>,
redactor: Redactor,
patterns: Option<Vec<Expr>>,
}
```
The problem I see, though, is that this doesn't allow for accurate `type_def`s. I believe you need either the original `Box<dyn Expression>` or `Option<Box<dyn Expression>>` to properly compute the type definition. In the case of the `redact` function, the type def …

fix(remap): Make the redact function fallible

---

tests/tcp.rs

Closes #4714
In short, the test didn't have enough cpu time to finish in time.
The fix isn't guaranteed to help, since this is more of CI hardware issue.
The most damning evidence is the lack of 
```
INFO vector::topology: Shutting down... Waiting on: out2, in1, in2, out1. 41 seconds left
```
logs which should happen every 5 seconds but only happened twice in span of 35 seconds.

fix(tests): Set `core_threads` for `merge_and_fork`

---

lib/remap-lang/grammar.pest

Recent changes to prevent reserved keywords being used as variables names was also preventing variable names with an underscore after a reserved keyword.
eg.
- `if_foo`
- `for_zorp`
- `for_`
were also being denied. I can't think of a reason why we shouldn't allow these.
Feel free to just close if you disagree.

fix(remap): allow underscores after reserved keywords for variable names

---

src/conditions/mod.rs
src/transforms/filter.rs
src/transforms/reduce/mod.rs
src/transforms/swimlanes.rs
tests/behavior/transforms/filter.toml
tests/behavior/transforms/reduce.toml
tests/behavior/transforms/swimlanes.toml

Closes #5724 
The type field for conditions is no longer optional.
So, for example using this transform:
```toml
[transforms.filter]
type = "filter"
inputs = ["stdin"]
condition."message.contains" = "funky"
```
Now results in this error:
```
Jan 11 11:53:31.861 ERROR vector::cli: Configuration error. error=missing field `type` for key `transforms.filter` at line 9 column 1
```
Which is not ideal, the error should really say `missing field 'condition.type'`. I'm not sure of a way to make this work though, any ideas?

enhancement(config)!: remove the check_fields default for conditions

---

lib/remap-lang/grammar.pest
lib/remap-lang/src/error.rs
tests/behavior/transforms/remap.toml

Closes #5443 
Add support for inserting comments into Remap using the `#` character.
```coffeescript
x = 1 # And so is this
```

feat(remap): added support for Remap comments

---

src/sinks/new_relic_logs.rs

This test is marked as `should_panic` as it is asserting that the
max_size is too big, but was panicking instead because it was missing
the encoding key.

chore(tests): Add missing encoding option to new_relic_logs sink test

---

distribution/helm/vector-agent/templates/podsecuritypolicy.yaml

This PR adjust the pod security policy since we experienced problems when trying to run with the current one. Basically it is necessary with a bit more permissions to be able to actually tail the logs on the host node.

fix(kubernetes platform): vector-agent pod security policy

---

.github/workflows/benches.yml

It does not exist if pulling the master artifacts fails.

chore(ci): Ensure target/criterion exists

---

docs/reference/components/sources/journald.cue
src/sources/journald.rs

Ref #4414 
~~The functionality and the docs are removed, but the option remains to detect it's usage and error with a helpful message.~~
EDIT:
Removes the docs and adds a warning with a message to use `remap` instead.
The plan is to deprecate first and then to remove the functionality and turn the warning into an error in a later release.

chore(journald source): Deprecate `remap_priority` option

---

scripts/release-s3.sh

This uploads artifact redirects as part of the release to keep backwards
compatibility with the links.
For example,
https://packages.timber.io/vector/nightly/2021-01-10/vector-amd64.deb
is pointed to
https://packages.timber.io/vector/nightly/2021-01-10/vector-nightly-amd64.deb.
I initially looked at [S3's conditional redirects](https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html#advanced-conditional-redirects) but this doesn't seem powerful enough to model the patterns we need.
Assuming we like this, I'll try to backpopulate the old releases.

chore(ci): Add S3 redirects for old artifact names

---

distribution/helm/vector-agent/Chart.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/Chart.yaml
distribution/helm/vector/Chart.yaml

Running [chart testing](https://github.com/helm/chart-testing) against the Helm charts had a few minor issues - below is the output. This PR fixes this allowing the charts to successfully pass linting.
```
➜  vector git:(master) ✗ docker run -it --rm -v $(pwd):/src quay.io/helmpack/chart-testing:v3.3.1 sh -c "cd /src; ct lint --chart-dirs distribution/helm --all --validate-maintainers=false"
Linting charts...
Version increment checking disabled.
------------------------------------------------------------------------------------------------------------------------
Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
vector => (version: "0.0.0", path: "distribution/helm/vector")
vector-agent => …
```

fix(kubernetes platform): Adhere to ct linting rules

---

lib/remap-lang/grammar.pest
lib/remap-lang/src/error.rs
tests/behavior/transforms/remap.toml

Ref: #5443 
This allows you to insert comments between multiline statements within Remap. So this sort of thing is possible:
```coffeescript
.b == 1 && \
.c == 8
```
Particularly handy with long remap conditions.

fix(remap): allow comments between multiline statements

---

scripts/environment/bootstrap-macos-10.sh

It was installing the now-released 3.0

chore(ci): Pin Ruby at 2.7 in CI for OSX

---

.gitattributes
.github/workflows/test.yml
Makefile
distribution/helm/vector-agent/templates/configmap.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/configmap.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_metrics.tpl
distribution/helm/vector-shared/templates/_vector_config.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-e2e-tests/tests/vector.rs
scripts/check-style.sh
scripts/helm-template-snapshot.sh
tests/helm-snapshots/README.md
tests/helm-snapshots/builtin_configs/vector-agent/config.sh
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-agent/values.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/config.sh
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/values.yaml
tests/helm-snapshots/topology_config/vector-agent/config.sh
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/values.yaml
tests/helm-snapshots/topology_config/vector-aggregator/config.sh
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/values.yaml

This PR adds the ability to pass values to the `sources`, `transforms` and `sinks` defined in Helm charts as an inline YAML, rather than as a TOML string in `rawConfig`.
It also adds snapshot testing mechanism to Helm templates - we generate and snapshot YAML files in various interesting configurations.
This new testing mechanism allows us to achieve the following goals:
- if some complicated configuration snapshot changes unintentionally we'll know, and will be able to fix it in time;
- when doing the development of the Helm charts, it easy to work on supporting more complicated configurations - you can prepare the snapshot config upfront, and then assert that it's working;
- core review for the changes in Helm charts becomes easier because the snapshots show how the effective …

enhancement(kubernetes platform): Allow passing component configs as YAML in Helm charts

---

src/sources/internal_metrics.rs

This PR fixes a bug with the scarping interval being 0 if the setting is omitted in the config file.
It also adds a lower limit to the interval value.
Closes #5680.

fix(internal_metrics source): Rework defaults and a minimal scraping interval value

---

docs/reference/remap/assert.cue
docs/reference/remap/ipv6_to_ipv4.cue
lib/remap-functions/src/assert.rs
lib/remap-functions/src/ip_cidr_contains.rs
lib/remap-functions/src/ip_subnet.rs
lib/remap-functions/src/ip_to_ipv6.rs
lib/remap-functions/src/ipv6_to_ipv4.rs
lib/remap-functions/src/parse_aws_alb_log.rs
lib/remap-functions/src/parse_aws_cloudwatch_log_subscription_message.rs
lib/remap-functions/src/parse_aws_vpc_flow_log.rs
lib/remap-functions/src/parse_duration.rs
lib/remap-functions/src/parse_grok.rs
lib/remap-functions/src/parse_json.rs
lib/remap-functions/src/parse_url.rs
lib/remap-functions/src/to_syslog_facility.rs
lib/remap-functions/src/to_syslog_level.rs
lib/remap-functions/src/to_syslog_severity.rs

There were a number of functions that should always be fallible that were not being marked as such. For example the ip functions are always fallible even when the parameter is a string because that may not represent a valid IP address.
There were also a number of places that did:
```rust
.fallible_unless(value::Kind::Bytes)
.into_fallible(true)
```
I have removed the `fallible_unless` line since that is unnecessary.

chore(remap): update functions that should be fallible

---

src/conditions/check_fields.rs
tests/behavior/formats/simple.json
tests/behavior/formats/simple.toml
tests/behavior/formats/simple.yaml
tests/behavior/formats/simple.yml
tests/behavior/transforms/add_fields.toml
tests/behavior/transforms/ansi_stripper.toml
tests/behavior/transforms/coercer.toml
tests/behavior/transforms/concat.toml
tests/behavior/transforms/dedupe.toml
tests/behavior/transforms/filter.toml
tests/behavior/transforms/grok_parser.toml
tests/behavior/transforms/json_parser.toml
tests/behavior/transforms/key_value_parser.toml
tests/behavior/transforms/logfmt_parser.toml
tests/behavior/transforms/lua_v1.toml
tests/behavior/transforms/lua_v2.toml
tests/behavior/transforms/merge.toml
tests/behavior/transforms/reduce.toml
tests/behavior/transforms/regex_parser.toml
tests/behavior/transforms/remap.toml
tests/behavior/transforms/remove_fields.toml
tests/behavior/transforms/rename_fields.toml
tests/behavior/transforms/split.toml
tests/behavior/transforms/swimlanes.toml
tests/behavior/transforms/tokenizer.toml

Closes #5742 
This adds a deprecation warning if the check_fields condition is used. I have **not** added a similar warning to `is_log` or `is_metric` conditions since that is not something Remap can currently do.
I have also updated the behaviour tests to use Remap conditions since many of them were using `check_fields`.

enhancement(config): deprecate `check_fields` conditions

---

docs/reference/remap/encode_base64.cue
docs/reference/urls.cue
lib/remap-functions/src/encode_base64.rs

Adds a `charset` parameter to the `encode_base64` function with two possible values: `standard` and `url_safe`. It's fairly trivial to add others in the future.
Closes #6011

enhancement(remap): Add charset parameter to encode_base64 function

---

docs/reference/remap/parse_duration.cue

I believe this is the only one that needs to be converted. If there are indeed others, let me know and I'll tack that on to this PR.
Closes #6013

fix(external docs): Convert parse_duration unit arg to enum

---

lib/remap-lang/src/expression/arithmetic.rs

Spotted [here](https://github.com/timberio/vector/issues/5530#issuecomment-761665271).
Since division by zero can produce an error, division and integer division operations will always be fallible.

fix(remap): division operations are always fallible

---

Cargo.lock
Cargo.toml

Until https://github.com/timberio/vector/issues/6005 is resolved.
Inadvertently upgraded in #6028 
Fixes https://github.com/timberio/vector/actions/runs/493151187

chore(tests): Pin thread_local to 1.0.1

---

docs/reference/installation/_interfaces/helm3.cue

Closes #6047.
I think we need a way to add some kind of notes/warning to the tutorial steps. I.e. I'd mention that `rawConfig` used to be a thing and is now deprecated there. Is there any better place for it?

chore(external docs): Remove the rawConfig from Helm tutorial

---

src/kubernetes/hash_value.rs
src/kubernetes/mod.rs
src/kubernetes/pod_manager_logic.rs
src/kubernetes/state/evmap.rs
src/sources/kubernetes_logs/k8s_paths_provider.rs

Closes #6001.
After #6061 is complete, we should add E2E tests for this.

fix(kubernetes_logs source): Support for collecting logs from static pods

---

docs/reference/components/sources/host_metrics.cue

chore(host_metrics source): Adds cue docs for customizing sysfs and procfs in host_metrics component

---

.github/CODEOWNERS
src/sources/postgresql_metrics.rs

Part of https://github.com/timberio/vector/issues/6086
- Add @fanatid & @jszwedko to `.github/CODEOWNERS`
- Add version verification after connect (there one more issue with `unwrap` client/version from `Option`, will fix in client refactoring)
- Add more asserts in tests, see https://github.com/timberio/vector/pull/5391#discussion_r558581861 @jszwedko any idea how to test `up` metric with `0`? :thinking:

chore(postgresql_metrics source): add more asserts in tests

---

docs/reference/remap/functions/ipv6_to_ipv4.cue
lib/remap-functions/src/ipv6_to_ipv4.rs

Closes #6046 
The `ipv6_to_ipv4` function was taking ipv4 addresses and converting them to ipv6 - the opposite of the intended purpose of this function. This fixes the function to just pass the ipv4 address through.

fix(remap): `ipv6_to_ipv4` function allows ipv4 addresses to pass through

---

Cargo.toml

This PR adds the now-optional `vrl-cli` feature to the pre-existing `default-*` feature sets and adds a new feature set that doesn't include `vrl-cli` (it's not yet clear that we'll need this, but we'll see). The effect of this PR is to include the VRL CLI in public releases of Vector. This PR should be merged only when the interface is in a state that we're comfortable releasing to users.

enhancement(cli): Add vrl-cli feature to default features

---

docs/reference/components/kafka.cue
docs/reference/components/sources/kafka.cue

These were documented as being reported for both the `kafka` source and
sink, but are only reported for the source currently.
`consumer_offset_updates_failed_total` is likely to only apply to the
source anyway.
I opened https://github.com/timberio/vector/issues/6133 to cover adding
them to the sink.

chore(external docs): Remove unreported metrics from kafka sink

---

Cargo.lock
Cargo.toml
Makefile
benches/default.rs
benches/metrics_bench_util/mod.rs
benches/metrics_no_tracing_integration.rs
benches/metrics_no_tracing_layer.rs
benches/metrics_off.rs
benches/metrics_on.rs
benches/metrics_snapshot.rs
src/event/metric.rs
src/metrics.rs
src/trace.rs

This PR adds benchmarks to the metrics system.
It also
- introduces some (hidden and undocumented) escape hatches to disable internal metrics subsystem,
- vendors the metrics registry implementation (to allow more flexibility in integrating with our needs),
- optimizes metrics snapshot procedure,
- disables `autobenches` cargo option (with our current configuration it only confuses people),
- adds the ability to reset the metrics registry via a controller.
Closes #5093.
---
Findings from the benches show that the topology of socket source to socket sink performs slower with internal metrics than without them by the order of roughly up to 10-15%, but ultimately the performance change *within the noize tolerance*.
```shell
$ critcmp | grep topology …
```

chore(performance): Metrics benches

---

docs/reference.cue
docs/reference/components/sinks/influxdb_metrics.cue
docs/reference/components/sinks/prometheus_exporter.cue
docs/reference/components/transforms/log_to_metric.cue
docs/reference/components/transforms/metric_to_log.cue
docs/reference/data_model/schema.cue
src/event/metric.rs
src/event/mod.rs
src/sinks/aws_cloudwatch_metrics.rs
src/sinks/console.rs
src/sinks/datadog/metrics.rs
src/sinks/humio/metrics.rs
src/sinks/influxdb/metrics.rs
src/sinks/prometheus/collector.rs
src/sinks/statsd.rs
src/sinks/util/buffer/metrics.rs
src/sinks/util/statistic.rs
src/sources/internal_metrics.rs
src/sources/prometheus/parser.rs
src/sources/statsd/parser.rs
src/transforms/log_to_metric.rs
src/transforms/lua/v2/interop/metric.rs
src/transforms/metric_to_log.rs
tests/support/mod.rs

The `MetricValue` type stored samples, buckets, and quantiles in pairs
of arrays. This reworks the appropriate variants to use an array of a
composite type that better represents the underlying data.
Several tests that rely on the JSON format are failing. I am unsure how
best to resolve this format change.
Closes #5581

chore(metrics)!: Rework histogram/summary data model

---

docs/reference/components/sources/kubernetes_logs.cue
docs/reference/urls.cue

This support was never added as
https://github.com/timberio/vector/issues/4211 was closed in-lieu of
https://github.com/timberio/vector/pull/4743

chore(external docs): Remove the mention of multiline support from kubernetes_logs

---

docs/reference/components/aws.cue
src/rusoto/auth.rs
src/rusoto/mod.rs
src/sinks/aws_cloudwatch_logs/mod.rs
src/sinks/aws_cloudwatch_metrics.rs
src/sinks/aws_kinesis_firehose.rs
src/sinks/aws_kinesis_streams.rs
src/sinks/aws_s3.rs
src/sinks/aws_sqs.rs
src/sinks/elasticsearch.rs
src/sources/aws_s3/mod.rs

Closes #4200
`AWSAuthentication` is an `enum` since #4199 will add an additional variant.

chore(config): Move `assume_role` option to `auth.assume_role`

---

docs/reference/components.cue

Switches our docs from using `check_fields` to `remap`.
Ref #4791

chore(external docs): Switch conditions docs from `check_fields` to `remap`

---

src/sinks/aws_cloudwatch_logs/mod.rs

The healthcheck actually calls DescribeLogGroups, not DescribeLogStreams, so the previous error was misleading.

fix(aws_cloudwatch_logs sink): Rename healthcheck error

---

benches/metrics_bench_util/mod.rs
benches/metrics_snapshot.rs

Based on
https://github.com/timberio/vector/runs/1746002475
We can refine these, but this should give us a starting point.

chore(ci): Configure noise thresholds for metrics benchmarks

---

deny.toml

New issues with advisories ids: https://github.com/timberio/vector/issues/6223 https://github.com/timberio/vector/issues/6224 https://github.com/timberio/vector/issues/6225

fix(ci): add new advisories ids to deny.tolm

---

docs/reference/components/transforms/filter.cue
docs/reference/components/transforms/reduce.cue
docs/reference/components/transforms/route.cue

chore: Add more remap examples for remap conditions

---

.github/workflows/benches.yml

I don't think these are useful for branches, but this specifically
addresses the issue that this check always fails for PRs from forked
repos as they don't have access to the AWS secrets.
Closes https://github.com/timberio/vector/issues/6131

chore(ci): Only upload benchmark artifacts on master

---

src/config/builder.rs
src/config/compiler.rs
src/config/unit_test.rs
src/config/validation.rs
tests/config.rs

Closes #2550
This allows for very simple wildcards in input lists. The `*` must be the last character in the string and we do a simple prefix match against all valid inputs (i.e. self is excluded). We could choose to expand this to a more full-featured glob syntax in the future, but there were enough questions there that this seemed like a better start. It is also my expectation that this should cover >95% of valuable use cases, so it may well be all we ever need.

feat(config): add wildcard expansion to inputs

---

Makefile

This PR fixes an itsy bitsy typo in the Makefile that's nonetheless causing some real issues.

fix(performance): Fix typo in Makefile cargo flag

---

lib/remap-functions/src/is_nullish.rs

`is_nullish` is supposed to accept all types and thus to be infallible, but the `accepts` function on `master` is a holdover from an early incarnation of the function that was only intended to work with strings and `null`. This PR brings `accepts` in line with the actual behavior of the function.

fix(remap): Fix is_nullish input type issue

---

lib/remap-functions/src/parse_aws_vpc_flow_log.rs

Introduced in initial PR: https://github.com/timberio/vector/pull/5504

fix(remap): fix field sublocation_type in parse_aws_vpc_flow_log

---

Cargo.lock
Cargo.toml
lib/remap-functions/Cargo.toml
lib/remap-functions/src/parse_syslog.rs

Closes #6015 
Ref #6249 
If `parse_syslog` is not passed a valid syslog message, it should error rather than return the unparsed message.
----
It's worth noting that the error message returned is just a generic `could not parse` message. Since the parser tries a fair number of different combinations to parse the message successfully, it is hard to actually pinpoint a specific part of the message that is responsible for the failure.

fix(remap): `parse_syslog` function should error on an invalid syslog message

---

distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/configmap.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_vector_config.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

According to the  #6227 I implemented helm api endpoint configuration.
I am not sure in the current implementation, because it looks a "little bit" weird ))
But I couldn't make up something better.
Also I am not so confident in grammar and will be glad to fix my mistakes.

enhancement(kubernetes platform): add the ability to configure Vector API at the Helm charts

---

docs/reference/remap/functions/merge.cue
lib/remap-functions/src/merge.rs
tests/behavior/transforms/remap.toml

Closes #6265 
`merge` used to mutate the first parameter rather than return the merged result, so you would have to do:
```
merge(., parse_json(...))
```
This changes the function so it now returns the result and leaves the first parameter untouched, so you have to do:
```
. = merge(., parse_json(...))
```
This brings it inline with how the rest of the Remap functions work.
Note I haven't needed to change much of the documentation as that was assuming merge worked like this anyway!

chore(remap): `merge` returns the result rather than mutates the parameter

---

scripts/setup_integration/loki_integration_env.sh

Loki integration tests have been [failing](https://github.com/timberio/vector/actions/runs/518416129) the past couple of days with no apparent change on our side. This changes our integration suite to use the latest release of Loki instead of the latest build from their master branch, which seems to fix the problem.
Without this change, our loki sink's requests to the `/loki/api/v1/push` endpoint were receiving responses with a status code of 400 and a body of `snappy: corrupt input`. As best I can tell, it seems like something broke in Loki and it's no longer respecting the `Content-Type` header that indicates our requests are JSON, not snappy-compressed protobuf messages. I'll open an issue there to follow up in case the relevant change ends up being released.

fix(tests): test against released version of loki

---

lib/remap-functions/src/parse_grok.rs

Closes #6252 
Ref #6249 
This make `parse_grok` return an error if it doesn't parse the input string correctly.
There was also a bug in the type_def which was declaring it's return type to be an Array. I have fixed it to return Map.

fix(remap): `parse_grok` should error when it fails to parse

---

src/config/validation.rs
tests/config.rs

fix(config): disallow non-unique component names

---

src/conditions/mod.rs
src/conditions/remap.rs
src/config/mod.rs
src/config/unit_test.rs
src/transforms/filter.rs
src/transforms/reduce/mod.rs
src/transforms/route.rs

Ref #4791 
This updates the conditions such that if you don't specify a subfield it will take the value as the remap source.
So both these examples work and are equivalent:
```toml
[transforms.filter]
type = "filter"
inputs = ["stdin"]
condition.type = "remap"
condition.source = 'contains!(.message, "funky")'
```
```toml
type = "filter"
inputs = ["stdin"]
condition = 'contains!(.message, "funky")'
```
`check_fields` conditions work and can be set as before. A deprecation warning is still emitted.

chore(remap): condition without subfields is set to Remap source

---

Cargo.toml

Now that we have [published RustDoc](https://vector-rustdoc.netlify.app/vector/) for Vector, this PR creates a `docs` feature that enables us to determine what gets published there. At the moment, the feature list is hard-coded in another repo but I think it'd be better to have that dictated here.

enhancement(external docs): Add docs feature

---

tests/crash.rs

Will open issue to resolve, but this should get CI back into a good
state.
Appears to have been introduced by https://github.com/timberio/vector/pull/6238
Issue to follow-up: https://github.com/timberio/vector/issues/6299

chore(ci): Temporarily comment out hanging tests

---

src/config/watcher.rs

This reverts https://github.com/timberio/vector/pull/6286
I haven't been able to track down why the tests don't pass yet so
reverting this for now to get master back to green since it was
only made to improve CI flakiness.
Fixes: https://github.com/timberio/vector/issues/6301

fix(tests): revert poll watcher change

---

Cargo.toml
scripts/environment/prepare.sh

This took a lot of fiddly testing. We now hard-code the earliest glibc we support (2.17) as the dependency of the Debian package. This ensures Debian/Ubuntu releases that choke on an empty `Depends:` field. Later Debian/Ubuntu releases should work forwards too.
We've also updated to the latest `cargo-deb` release, which support dropping the `Depends` field if not dependencies are present.

fix: #5642 - build deb packages that install on Deb 8

---

benches/topology.rs
src/config/mod.rs

chore: Add real world topology benchmark

---

docs/reference/components/sources/file.cue
src/sources/file.rs

This option was deprecated in 0.11.0 via https://github.com/timberio/vector/pull/5215, but the docs hadn't been updated.
The option is kept around and parsed from config files in order to
migrate checkpoints written by vector pre 0.11.0 to the new
checksum strategy which is to only checksum the first line (after
ignored_header_bytes).
This change removes `fingerprint.bytes` from the docs and outputs
a warning if the user has set it.

fix(file source): Deprecate fingerprint.bytes option

---

Cargo.lock
docs/reference/remap/functions/parse_common_log.cue
lib/remap-functions/Cargo.toml
lib/remap-functions/src/lib.rs
lib/remap-functions/src/parse_common_log.rs
tests/behavior/transforms/remap.toml

feat(remap transform): Add `parse_common_log` function

---

docs/reference/components/sinks/splunk_hec.cue

The question of which endpoint we use has come up a few times, most
lately here:
https://github.com/timberio/vector/issues/6185#issue-792042826
This updates the link to link directly to the endpoint we use.

chore(external docs): Update Splunk HEC endpoint link

---

docs/reference/components/sources/kafka.cue

Seems to have been a copy/pasta error.

chore(external docs): Fix timestamp documentation for Kafka source

---

src/sinks/aws_cloudwatch_metrics.rs
src/sinks/datadog/metrics.rs
src/sinks/influxdb/metrics.rs
src/sinks/prometheus/remote_write.rs
src/sinks/sematext/metrics.rs
src/sinks/util/buffer/metrics.rs
src/sinks/util/sink.rs

MetricsBuffer included a `state` component that was used to convert
metrics between absolute and incremental kinds. This relied on the batch
buffer never being dropped but rather just regenerated through
`Batch::fresh`. However, `PartitionBatchSink` never calls `fresh` but
rather generates a new batch for each partition and then just drops it.
This moves the state management out of the buffer and into a flat map
before the metrics enter the buffer.
Closes #6312

fix(metrics, sinks): Move normalization out of MetricsBuffer

---

scripts/slim-builds.sh

It's not clear to me why profile.dev was being written to Cargo.toml by
slim-builds.sh given that all of the values are defaulted.
The one value, `incremental`, that is changed, is changed in
`~/.cargo/config` which will override any profiles.
> The incremental value can be overridden globally with the
CARGO_INCREMENTAL environment variable or the build.incremental config
variable.
https://doc.rust-lang.org/cargo/reference/profiles.html#incremental
I think the release profile is similar, but will be removed by
https://github.com/timberio/vector/pull/6202 so I left it for now.

chore(ci): remove redundant build profile

---

CONTRIBUTING.md
lib/file-source/src/file_server.rs
src/sinks/util/adaptive_concurrency/controller.rs
tests/support/mod.rs

The CONTRIBUTING guide accidentally had an example of using Debug, but
we'd decided to prefer Display for errors.
Fixes https://github.com/timberio/vector/issues/6380

chore(observability): Prefer using Display for logging errors

---

Cargo.lock
Cargo.toml

Moved from https://github.com/timberio/vector/pull/6217
I little stuck with #6217 due to regressions. Not sure why CI is still green... currently `hyper:0.13.9` should break advisories check:
```
error[A001]: Multiple Transfer-Encoding headers misinterprets request payload
┌─ /home/kirill/projects/vector/Cargo.lock:244:1
│
244 │ hyper 0.13.9 git+https://github.com/hyperium/hyper?rev=a00cc20afc597cb55cbc62c70b0b25b46c82a0a6#a00cc20afc597cb55cbc62c70b0b25b46c82a0a6
│ ---------------------------------------------------------------------------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2021-0020
```

chore(deps): bump hyper version

---

lib/k8s-e2e-tests/src/lib.rs

This is a workaround for errors like this: https://github.com/timberio/vector/runs/1862911154?check_suite_focus=true

chore(tests): Implement a workaround for the K8s E2E Test Framework failure

---

.github/workflows/benches.yml
.github/workflows/environment.yml
.github/workflows/install-sh.yml
.github/workflows/integration-test.yml
.github/workflows/k8s_e2e.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/test-harness.yml
.github/workflows/test.yml
scripts/environment/bootstrap-ubuntu-20.04.sh

ubuntu-latest is in the process of being migrated which means the jobs
can run on either 18.04 or 20.04:
actions/virtual-environments#1816
We've seen some failures on 20.04 that we'll need to address before
upgrading.
https://github.com/timberio/vector/actions/runs/559968325
Also replace `ubuntu-latest` with `ubuntu-20.04` for jobs that seem to be fine on 20.04.
I ended up including a fix for https://github.com/actions/virtual-environments/issues/2703 as well.

chore(ci): Pin Github Actions runners to Ubuntu 18.04 for certain jobs

---

.github/workflows/benches.yml

A while back, in PR #5610, I *thought* I was restricting benchmark runs for PRs with changes only to certain paths. But it turns out those changes were only for pushes to `master`. Mea culpa. This PR fixes that.
One effect of these changes is to *always* run the benches on pushes to `master`. I'm not sure if this is desired, so please let me know if not.

enhancement(ci): Restrict benchmark runs to specific directories

---

config/vector.toml

fix(external docs): Fix typo in example Vector config

---

benches/languages.rs

This PR fixes a recent oversight that's causing the benchmarking suite to fail on `master`

fix(performance): Address failing bench in master

---

Cargo.lock
benches/languages.rs

There is a [security advisory](https://rustsec.org/advisories/RUSTSEC-2021-0023) on `rand_core`.
I have run `cargo update` on the project to update the dependencies to a patched version (0.6.2).
Note, a number of other crates have been updated too. I'm not particularly sure if this is a problem or not, so have decided to keep these updates.
```
╰─$ cargo update
Updating git repository `https://github.com/hyperium/hyper`
Updating crates.io index
Updating git repository `https://github.com/bytecodealliance/lucet.git`
Updating git repository `https://github.com/kyren/rlua`
Updating git repository `https://github.com/tower-rs/tower`
Updating git repository `https://github.com/tokio-rs/tracing`
Updating async-graphql-parser v2.4.6 -> v2.5.4
Updating bson v1.1.0 -> v1.2.0
Updating env_logger …
```

chore(deps): update package dependencies

---

lib/vrl/compiler/src/expression/op.rs
lib/vrl/compiler/src/type_def.rs
lib/vrl/tests/tests/examples/successful_parse_syslog_type.vrl

Replacing #6344 - I've updated it to work with the recent parser changes.
Following from #6182, a number of functions return fields that can be `Null`, for example `appname` from `parse_syslog` can be `Kind::Bytes | Kind::Null`.
This PR makes it possible to specify a default value using Or. Since we know that if the lhs is either Null or Bytes, we can deduce that the whole expression `lhs | rhs` will either be the `lhs - Kind::Null` or the `rhs`. 
Eg. This now typechecks:
```
.parsed = parse_syslog(.message)
.sha = sha3(.parsed.appname || "default")
```
However this will still not typecheck, the `procid` field can be either a string, an integer or null. So even after an Or it could still be an Integer or a String.:
```
.parsed = parse_syslog(.message)
.sha = sha3(.parsed.procid || …
```

enhancement(remap): improved type definitions for `or` with nullable fields

---

scripts/release-helm.sh

Adds a filtration to our release script to not publish the aggregator and unified helm charts to stable. This should remain filtered out until we complete the work on the vector:vector comms alterations or remove the consumption of the `vector` source and sink from the `kubernetes_logs` source.

chore(kubernetes_logs source): Don't publish vector-aggregator until agent->agg comms are corrected

---

lib/vrl/cli/src/repl.rs

I'm not sure how this got overwritten but this will set things aright

fix(cli): Fix function doc URL in VRL REPL

---

lib/vrl/tests/tests/issues/6361_query_type_definition.vrl

closes #6361
I previously thought this wasn't working, but I think I accidentally tested against an earlier version of the master branch. This test validates that it works as expected, and keeps working.

chore(remap): add type def test case

---

docs/reference/remap/functions/ipv6_to_ipv4.cue
lib/vrl/stdlib/src/ipv6_to_ipv4.rs

Part of https://github.com/timberio/vector/issues/6476.

fix(remap): Restore changes to ipv6_to_ipv4

---

lib/vrl/stdlib/src/parse_grok.rs

Part of #6476.
Note that this only updates the commented unit tests to the state they were in before the merge of #6353.
https://github.com/timberio/vector/blob/d4ccc81c9aa0e82dbac1da26602320ca0c549728/lib/remap-functions/src/parse_grok.rs#L118-L247
The relevant changes to the code itself have been migrated correctly.

chore(remap): Restore changes to parse_grok

---

docs/highlights/2021-02-16-vector-remap-language.md

cc @binarylogic 
Removing this component import in the markdown.  This is causing issues for the Gatsby site.  I don't see any other component imports in the docs so thinking this doesn't need to be there.  Let me know if this is needed for the existing docs for some reason and I'll try to find a workaround.

fix(internal docs): remove component import

---

Makefile
benches/languages.rs
tests/data/wasm/parse_json/src/lib.rs
tests/data/wasm/parse_syslog/fixtures/a/expected.json

Turns out these weren't running in CI because I neglected to add them to
the features for `make test-components`.
This adds them to run in CI and fixes a few issues. I changed the
assertion to assert that the expected value is a subset of the actual
one to ignore keys automatically added by the `socket` source component
(like `timestamp`). These assertions only run during tests and not
during the actual benchmark.

chore(ci): Fix language bench tests

---

.github/workflows/test.yml
Makefile
lib/vrl/stdlib/src/parse_syslog.rs
lib/vrl/tests/src/main.rs
scripts/test-vrl.sh

This PR adds the VRL test suite in `lib/vrl/tests` to our current CI testing pipeline. I've somewhat arbitrarily chosen to run this on Ubuntu, as I'm not sure that the platform should matter, but I'm open to suggestion on that.

enhancement(ci): Add VRL test suite to CI

---

.github/workflows/rustdoc.yml

This PR follows up on #6551 with some small changes suggested by @jszwedko. The third-party Action is now tied to a specific commit and the job is run on push rather than merge, which is effectively the same thing but easier to understand.

enhancement(ci): rustdoc build changes

---

Cargo.toml
Makefile
src/event/util/log/all_fields.rs
src/event/util/log/keys.rs
src/event/util/log/path_iter.rs
src/kubernetes/debounce.rs
src/kubernetes/reflector.rs
src/kubernetes/state/delayed_delete.rs
src/kubernetes/state/evmap.rs
src/kubernetes/state/instrumenting.rs
src/kubernetes/state/mod.rs

This PR does two things:
1. It adds a `make build-rustdoc` command, largely for use by a build process in another repo
2. It fixes a series of warnings produced by `cargo doc` when building the subset of the Rustdoc targeted for the https://rustdoc.vector.dev site (that link doesn't work yet but it will).

fix(external docs): Fix cargo doc errors

---

docs/reference/remap.cue
docs/reference/remap/errors/100_unhandled_root_runtime_error.cue
docs/reference/remap/errors/101_malformed_regex_literal.cue
docs/reference/remap/errors/102_non_boolean_if_expression_predicate.cue
docs/reference/remap/errors/103_unhandled_assignment_runtime_error.cue
docs/reference/remap/errors/104_unnecessary_error_assignment.cue
docs/reference/remap/errors/105_undefined_function.cue
docs/reference/remap/errors/106_function_argument_arity_mismatch.cue
docs/reference/remap/errors/107_required_function_argument_missing.cue
docs/reference/remap/errors/108_unknown_function_argument_keyword.cue
docs/reference/remap/errors/109_cannot_abort_function.cue
docs/reference/remap/errors/110_invalid_argument_type.cue
docs/reference/remap/functions/assert.cue

In going through and trying to exhaustively document VRL errors, I was struck by the thought that our current approach might be overkill. First, I'm not sure I see the value in providing an example compiler error output (in addition, those examples will be hard to maintain as the compiler will likely undergo swift changes post-0.12).
This is marked as a draft, as it includes only a proposed new `#Error` template and two reworked error codes.

enhancement(external docs): Pare down VRL error docs

---

src/sinks/util/service.rs
src/sinks/util/sink.rs

This just un-reverts #5076. The motivation is to reduce the complexity of our internal sink interfaces.
Signed-off-by: Kirill Fomichev <fanatid@ya.ru>
Closes #6062

chore: use PartitionBatchSink in BatchSink

---

lib/vrl/parser/src/lex.rs
lib/vrl/parser/src/parser.lalrpop
lib/vrl/tests/tests/diagnostics/syntax_error_ampersat_variable.vrl
lib/vrl/tests/tests/diagnostics/syntax_error_path_segment.vrl
lib/vrl/tests/tests/expressions/query/ampersat.vrl

Closes #6489 
This allows `@` in identifiers such as:
```
.@timestamp = now()
```
Signed-off-by: Stephen Wakely <stephen.wakely@datadoghq.com>

fix(remap): re-enable @ in identifiers.

---

lib/vrl/tests/tests/diagnostics/syntax_error_ampersat_variable.vrl

The VRL url that was printed in error messages was changed prior to a pr getting merged, which resulted in this test failing.
Signed-off-by: Stephen Wakely <stephen.wakely@datadoghq.com>

chore(remap): update vrl url in error message

---

deny.toml

Tracking issue to resolve:
https://github.com/timberio/vector/issues/6584
Also removed a couple of no longer relevant ignored CVEs.

chore(ci): Temporarily ignore RUSTSEC-2020-0146

---

Cargo.toml
Makefile

I think it useful to build vector's docs with all features. We are using `--no-deps` so it should not build docs for vector's dependencies.
Broken off from
https://github.com/timberio/vector/pull/6553#discussion_r583105047

chore(external docs): Build complete vector docs

---

cue.mod/module.cue

As discussed with @binarylogic, the vector project has been an excellent
source of regression tests for the CUE project.
Making vector a CUE module will mean we can add the project to the unity
(https://github.com/cue-sh/unity) regression test setup. The goal of
unity is to provide a corpus of CUE code against which we can run
regression tests and CUE (performance) experiments.
In those same discussions with @binarylogic we discussed how to
potentially refactor the vector project more towards CUE's package
model, and/or support additional input modes for cmd/cue itself that fit
better with vector's single-package approach (which works incredibly
well for the use-case). We leave any such changes for a later PR/CL here
or in the CUE project.

chore(administration): make vector repository a CUE module

---

src/app.rs
src/config/builder.rs
src/config/compiler.rs
src/config/loading.rs
src/config/log_schema.rs
src/config/mod.rs
src/config/unit_test.rs
src/service.rs
src/sinks/humio/logs.rs
src/sinks/humio/metrics.rs
src/sinks/humio/mod.rs
src/sinks/splunk_hec.rs
src/sources/docker_logs.rs
src/topology/mod.rs
src/validate.rs
tests/shutdown.rs

Closes  #6394
Resolves the race between loading log schema from the config file and using said schema for building the same config by first loading config and setting log schema and then loading config as usual. 
Replaces #6552

fix(config): Preload log scheme

---

distribution/helm/vector-agent/templates/serviceaccount.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/serviceaccount.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

Allow for specifying the automountServiceAccountToken field on the vector-agent service account.

enhancement(kubernetes_logs source): add the ability to specify automountServiceAccountToken for vector-agent

---

docs/reference/components/sources/file.cue
src/sources/file.rs

Also clarify ignore_older_secs in the docs.
Looking at our existing config options, we commonly suffix duration based config keys with their unit. This brings a few more in-line and resolves some user confusion: #6558
Aliases are added to maintain existing names.
Closes: #6558

chore(file source): Suffix config values with units

---

lib/tracing-limit/examples/by_span.rs
lib/tracing-limit/src/lib.rs

This expands the support for independently rate limiting based on
component_name in span keys to additional keys useful for VRL rate
limiting: `vrl_line_number` and `vrl_position`.
I had originally wanted to have the trace line specify these keys, like:
```
info!("hello", internal_log_rate_secs = 5, internal_log_rate_group_by = ["vrl_line_number"])
```
But tracing doesn't permit lists to be passed through (`tracing::Value`
has no `Vec` or similar implementations:
https://docs.rs/tracing/0.1.25/tracing/trait.Value.html).
So, instead, I just added it as another globally grouped key for now. We
can see how this evolves if we need to additional keys, it might be
worth revisiting how this is structured.
I benchmarked this vs. master using the benchmark mentioned here: again and saw:
master: …

chore(observability): Expand rate limit to additional keys

---

lib/vrl/compiler/src/test_util.rs

I had originally made these in
https://github.com/timberio/vector/pull/6408 but lost them somewhere
along the way in bad merge of master.
This adds throughput measurements to the vrl benches and reformats their
output to use `/`s for namespacing similar to how criterion does it
natively.
`remap-functions` is prepended to namespace all of the remap function benches.
Output now looks like:
```
remap-functions/ceil/literal
time:   [110.08 ns 110.26 ns 110.43 ns]
thrpt:  [9.0552 Melem/s 9.0696 Melem/s 9.0842 Melem/s]
```

chore(performance): small enhancements to vrl function bench output

---

lib/tracing-limit/src/lib.rs

While reviewing https://github.com/timberio/vector/pull/6622 I was going
to suggest that users could use 0 there if they wanted no rate
limiting; however, when I tried that, I realized it actually hits
the panic on line 35 :D
This updates the rate limiting logic to allow 0 to disable rate
limiting. If any other invalid value is provided (for example -1 or
"foo") then it is treated as 0. This seems like acceptable behavior to
me over panicking.

chore(observability): Allow internal_rate_limit_secs to be 0

---

docs/reference/remap/functions/parse_apache_log.cue
docs/reference/urls.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_apache_log.rs
lib/vrl/stdlib/src/parse_common_log.rs

Closes #5369 
This adds the `parse_apache_log` remap function. We can parse common, combined or default error formats.
It is possible to customise the error log format in apache. This function doesn't cater for that.
The common format is exactly the same as the already existing `parse_common_log` function that we have.  This pr factors that code out into a shared module, so both functions call the same code.

enhancement(remap): add parse_apache_log function

---

Cargo.lock
lib/tracing-limit/Cargo.toml
lib/tracing-limit/src/lib.rs

Use a fake clock since the OSX Github Actions runner seems particularly
noisy: https://github.com/timberio/vector/pull/6614#issuecomment-790885300
I should have done this originally anyway for robustness and to not
artificially bloat the test time.

chore(ci): Make tests for tracing-limit more robust

---

lib/vrl/parser/src/lex.rs
lib/vrl/parser/src/parser.lalrpop
lib/vrl/proptests/src/main.rs
lib/vrl/tests/tests/expressions/query/mixed_case.vrl

Closes #6625 
This updates VRL to allow uppercase characters in identifiers and underscores at the start of identifiers as per the [docs](https://master.vector.dev/docs/reference/vrl/expressions/#path_segments).
Previously underscores at the start of identifiers were being used to access test functions in the parser. I can't see these being used, but I have updated them to be `?`.
Signed-off-by: Stephen Wakely <stephen.wakely@datadoghq.com>

fix(remap): allow uppercase and underscores in identifiers.

---

src/lib.rs
src/sinks/util/adaptive_concurrency/controller.rs
src/stats.rs
src/topology/builder.rs
src/utilization.rs

See code comments for most of the explanation, but this introduces some simplified (but hopefully still useful) statistics about which components are bottlenecked.
Right now the data is just output as debug logs, but it would be relatively straightforward to emit gauges or something similar if we consider that a better user experience. Right now the focus was to keep things as simple as possible.

feat(observability): emit basic component utilization statistics

---

lib/vrl/stdlib/src/parse_key_value.rs

Closes #6624 
The issue with that log line was this field:  `\"kartik\" test`. It began with a `"` and so the parser assumed it was a delimited field. It parsed up to the closing delimiter and was then left with the text ` test` that it didn't know what to do with.
This PR updates the parser so after parsing a delimited field it peeks into the following input to see if we are actually at the end of the field. If we aren't, it then attempts to parse the field as an undelimited field instead.

fix(remap): allow partially quoted fields to be parsed as undelimited.

---

docs/reference/remap/functions/parse_logfmt.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/parse_key_value.rs
lib/vrl/stdlib/src/parse_logfmt.rs

Closes #6418 
This is just an alias for the parse_key_value function with default parameters. The compiler for this function just creates a `ParseKeyValueFn` and passes the default parameters.

enhancement(remap): added the parse_logfmt remap function

---

Cargo.toml
docs/reference/components/sources/kubernetes_logs.cue
src/kubernetes/api_watcher.rs
src/kubernetes/client/config/in_cluster.rs
src/kubernetes/client/config/kubeconfig.rs
src/kubernetes/client/config/kubeconfig_types.rs
src/kubernetes/client/config/mod.rs
src/kubernetes/client/mod.rs
src/sources/kubernetes_logs/mod.rs

This is my first PR to Vector. First of all, thank you for a great product.
I'm very excited about the Kubernetes support, however I don't plan to run Vector in-cluster, which, looks like the only thing supported at the moment.
This PR implements kubernetes source configuration via a kubeconfig file, which can be formatted as either yaml or json.
If `kube_config_file` is set in the source configuration, then this will be used, otherwise in_cluster configuration will be applied.
Please let me know whether something like this is usable for you. :)
Basic requirements for the kubeconfig current are:
- The kubeconfig file must have at least one context, and a `current-context` must be defined.
- The active context must refer to both a cluster and a user
- The context-referred cluster must …

enhancement(kubernetes_logs source): support for kubeconfigs as an alternative to in_cluster configuration

---

src/lib.rs
src/sinks/util/adaptive_concurrency/tests.rs
src/sources/host_metrics.rs
src/tls/settings.rs

This is no longer needed as `fn bool::then` is now stable.

chore: Drop internal `trait BoolAndSome`

---

src/config/watcher.rs

These seem to fail fairly frequently and make CI noisy.
Issue to address: https://github.com/timberio/vector/issues/5000

chore(ci): Disable file watcher tests on OSX

---

docs/reference/components/sources/http.cue
src/sources/heroku_logs.rs
src/sources/http.rs
src/sources/prometheus/remote_write.rs
src/sources/util/http.rs

Closes #5112 
Add three options to the http source:
* `url_path`: the path where log event should be posted (default: /)
* `path_key`: the name of the key used to export the path for each log even (default: path)
* `strict_path`: whether strict path should be enforce, if true only event send to the exact url_path will be accepted, if false log sent to a path that start with the value of url_path will be accepted
For example:
```
url_path: "/events"
strict_path: false
```
Will accept events posted to "/events/1234" and "/events/5678".
Outside the http source there is no behaviour change.
Open question: should we accept all URLs for the `heroku_logs` source as it would allow a user to send logs from multiple app to the same source.

enhancement(http source): URL path configuration flexibility, path also exposed as a new field

---

Cargo.toml

I've added this just to silence a warning. If we upgrade Criterion (it looks we probably should soon) we'll need this feature in place to continue getting generated HTML reports.

enhancement(performance): Add HTML reporting feature to Criterion dependency

---

scripts/release-s3.sh

Fixes a couple of issues discovered with the 0.12.0 release:
* Removing old artifacts wasn't using --recursive so it didn't match
anything
* I updated the redirection of artifacts to use `aws s3api` to list the
objects rather than local file names to make it easier to run locally
without having the built artifacts
* Refactored the latest channel artifact upload to just do one iteration
over all of the different folders that are uploaded to
The release also failed to delete the old artifacts but this is an issue with the AWS permissions for the CI user so I'll adjust that separately.

chore(ci): 0.12.0 s3 release fixes

---

src/config/watcher.rs

Clippy was complaining of unused imports on macOS due to tests themselves being marked with `not(target_os = "macos")`.

fix(tests): Fix `make check-clippy` on macOS

---

.github/PULL_REQUEST_TEMPLATE.md

Noticed in https://github.com/timberio/vector/pull/6692 that the PR template doesn't specify the same types as in [semantic.yml](https://github.com/timberio/vector/blob/v0.12.0/.github/semantic.yml#L13-L17).

chore(administration): Fix types in PR template according to semantic.yml

---

Cargo.lock

I'm not sure how much of a problem this kind of discrepancy is but should be addressed ASAP

fix(dev): Update Cargo.lock with new Vector version

---

docs/reference/remap/functions/string.cue

One more misquoted cue field that was ending up as base64.

chore(external docs): Fixes cue quoting

---

docs/reference/components/sinks/aws_cloudwatch_logs.cue

As having multiple vectors writing to the same stream will result in AWS
API errors regarding the sequence token.

chore(external docs): Note that the log stream must be unique for aws_cloudwatch_logs

---

docs/reference/components/transforms/filter.cue

Reported by user in discord:
https://discord.com/channels/742820443487993987/746070591097798688/819318820019109959
Using ' appears to cause cue to base64 encode it when exporting (it was
exported as `LmxldmVsID09ICJkZWJ1ZyI=`).

fix(external docs): Fix quoting for filter transform example

---

config/vector.toml
scripts/check-examples.sh

This PR fixes the example config in `config/vector.toml` by fixing the VRL program. It also removes the internal and host metrics from the console output, as that pushes a *lot* of information through the console and seems bound, I think, to be more confusing than illuminating.
Closes #6694

fix(config): Update example config

---

docs/reference/remap.cue
docs/reference/remap/errors/103_unhandled_assignment_runtime_error.cue
lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/tests/tests/diagnostics/unhandled_parse_regex_all_type.vrl
lib/vrl/tests/tests/internal/infallible_ok_maybe_null.vrl

I'm aware that `unhandled error` doesn't *quite* capture what's happening here. But I like (a) the concision and (b) the proximity to error messages in other languages.
Closes #6702

fix(remap): Change description of error code 103

---

lib/vrl/README.md

This PR creates a very basic README for the `lib/vrl` directory. It's currently meant only to explain the purpose of the different subdirectories, though we can expand its uses over time.

enhancement(external docs): Add basic README for lib/vrl

---

docs/reference/components/sinks/loki.cue

A user, and myself, were confused about this option in discord:
https://discord.com/channels/742820443487993987/746070591097798688/819576122881736737

chore(external docs): Clarify loki remove_timestamp config

---

lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/compiler/src/value/kind.rs
lib/vrl/tests/tests/expressions/assignment/infallible_external.vrl
lib/vrl/tests/tests/expressions/assignment/infallible_variable.vrl
lib/vrl/tests/tests/internal/infallible_ok_maybe_null.vrl
lib/vrl/tests/tests/internal/ok_assignment_default_value.vrl
lib/vrl/tests/tests/internal/progressive_type_checking.vrl
tests/behavior/transforms/remap.toml

This is based on a discussion between @jszwedko and myself in https://github.com/timberio/vector/issues/6507#issuecomment-784250762.
Before, the following program would fail:
```ruby
if (status, err = int(.status); err == null) {
status >= 200 && status < 300
}
```
This is because the type definition of `status` would either be an `int` if the rhs expression of the assignment succeeded, or `null` if it failed (in which case `err` would be a string with the actual error message).
This is annoying to deal with, as you'll have to then do another type coercion call similar to `int!(status)`.
With the changes in this PR, the infallible assignment implementation now tries to get the "default" (or, as Golang calls them ["zero"](https://tour.golang.org/basics/12)) value for a given type, and …

enhancement(remap): improved infallible assignment types

---

Cargo.lock
docs/reference/remap/expressions/assignment.cue
lib/shared/src/conversion.rs
lib/vrl/tests/Cargo.toml
lib/vrl/tests/src/main.rs
lib/vrl/tests/tests/examples/parse_nginx_access_log.vrl

This adds an example on parsing nginx access logs using the `parse_tokens` function.
The program for this was reported by as user to us as being cumbersome to work with. With the changes in https://github.com/timberio/vector/pull/6716 and the added common-log timestamp format support added in this PR, parsing becomes a bit easier to manage.
Eventually, we'll have a function specifically to parse nginx logs (see #6103), but the changes in this and the linked PR are still relevant, even outside the use-case of parsing Nginx logs.

 enhancement(remap): improve nginx log parsing ergonomics

---

.github/workflows/nightly.yml
.github/workflows/release.yml

This turned out to be an issue when trying to build 0.11.0 and 0.11.1
where it was getting a 301. Figured I'd make the fix here for the
future.

chore(releasing): Follow redirects when installing Strawberry Perl

---

docs/reference/components/transforms/remap.cue
lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/program.rs
src/transforms/remap.rs

This change makes sure the original event is kept as-is, if the VRL program fails at runtime.
This currently "just" clones the event before processing, which of course has a performance impact. Longer term, we can improve this by tracking which fields have been mutated, and only keeping their original values around, but I deemed that too big a change right now to work on.
Meanwhile, I think this is a worthwhile change to make. If people _really_ need the highest possible performance, they can still set `drop_on_err`, as the implementation in this PR takes that flag into account when deciding of the original event needs to be tracked or not.
**update**: pushed another commit based on an [observation made by @jszwedko](https://github.com/timberio/vector/issues/6025#issuecomment-770924310) …

enhancement(remap): don't mutate event when program fails

---

benches/remap.rs
benches/wasm/mod.rs
docs/reference/components/transforms/remap.cue
src/transforms/remap.rs
tests/behavior/transforms/remap.toml

enhancement(remap transform): Rename and document `drop_on_error`

---

Cargo.toml
scripts/cross/aarch64-unknown-linux-gnu.dockerfile
scripts/cross/aarch64-unknown-linux-musl.dockerfile
scripts/cross/armv7-unknown-linux-musleabihf.dockerfile
scripts/cross/x86_64-unknown-linux-gnu.dockerfile
scripts/cross/x86_64-unknown-linux-musl.dockerfile

This commit documents the release build options in `Cargo.toml` without 
changing them. It also sets the container paths for builds to absolute paths, 
resolving a build issue on my strict podman install. 

chore(releasing): Slightly fiddle with release build options, container paths

---

Cargo.lock

This change was missed in a previous update

chore: Add missing update to Cargo.lock

---

Cargo.toml
Makefile
distribution/rpm/vector.spec
scripts/package-deb.sh

Closes: #6648 
Closes: #6547
This updates the glibc requirements for the packages we build to:
* Not require glibc for musl packages
* Requiring glibc 2.15 for armv7 and amd64 builds, 2.18 for aarch64
following what `cross` links with
* Builds with glibc for the aarch64 packages
It accomplishes this by:
* leveraging `cargo-deb` to have different targets
based on the target tuple which have different glibc requirements.
* removing `AutoReqProv: no` from the rpm spec file. This allows RPM to
just generate the requirements.
For the gnu/x86_64 RPM this looks like:
```
/bin/sh
config(vector) = 0.13.0-1
ld-linux-x86-64.so.2()(64bit)
ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.10)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit) …
```

enhancement(releasing): Correct the glibc requirements for packages

---

docs/reference/components/sinks.cue

Small fix for SVG image in the reference section.  We should not be using MDX components (React JSX syntax) in the CUE data.  Just use regular markdown syntax.

fix(internal docs): Use regular markdown image syntax in reference section

---

.github/workflows/nightly.yml
.github/workflows/release.yml
Cargo.toml
Makefile
scripts/package-deb.sh

This:
* Renames the built debian packages to match expectations of
vector-VERSION-ARCH.deb
* Updates the nightly/release workflows to move the package uploading
for aarch64 to the gnu steps since we've updated the default packaging
to package glibc artifacts on aarch64

fix(ci): Fix workflow for packaging debian

---

scripts/setup_integration/aws_integration_env.sh

On OSX, the docker socket is a symlink so just mounting `/var/run`
results in the container not being able to follow the symlink to the
socket itself.
```
➜  vector git:(tokio-1.0) ls -l /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  74 Feb 24 15:39 /var/run/docker.sock ->
/Users/jesse.szwedko/Library/Containers/com.docker.docker/Data/docker.sock
```
Mounting the symlink directly appears to work. I'm guessing `docker` has
special handling for this.

fix(tests): Explicitly mount docker socket for AWS ECS metadata mock container

---

.github/workflows/nightly.yml
.github/workflows/release.yml

`release-docker` additionally needs the artifacts from `build-aarch64-unknown-linux-gnu-packages`.

chore(ci): Add missing dependency to release-docker step

---

docs/reference/configuration.cue

It seems like maybe they've been missing since we switched to cue?
Noticed by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/821522831007285269 

chore(external docs): Add missing log_schema global options to docs

---

Cargo.lock
Cargo.toml
src/metrics.rs

The default hasher in Rust hashmaps is secure against untrusted input but is
quite slow. This commit adjusts our metrics dashmap to use a faster hash because
we can trust its input, on account of it's under our control. This reduces the hash time
in our metrics from 3% of execution in `file -> remap -> blackhole` to 2%. 

chore: Adjust metrics dashmap to use twox hash

---

src/sinks/util/batch.rs
src/sinks/util/buffer/metrics.rs
src/sinks/util/buffer/mod.rs
src/sinks/util/buffer/vec.rs

Second attempt at something that will fix the inefficiency identified in #6341 without the trait complications of the previous pull request #6570. This defers allocation of batch buffers until their first push.

chore(sinks): Defer allocation of batch buffers until first use

---

docs/manual/about.md
docs/manual/about/concepts.md
docs/manual/about/under-the-hood.md
docs/manual/about/under-the-hood/architecture.md
docs/manual/about/under-the-hood/architecture/concurrency-model.md
docs/manual/about/under-the-hood/architecture/data-model.md
docs/manual/about/under-the-hood/architecture/data-model/log.md
docs/manual/about/under-the-hood/architecture/data-model/metric.md
docs/manual/about/under-the-hood/architecture/pipeline-model.md
docs/manual/about/under-the-hood/architecture/runtime-model.md
docs/manual/about/under-the-hood/guarantees.md
docs/manual/about/under-the-hood/networking.md
docs/manual/about/under-the-hood/networking/adaptive-request-concurrency.md
docs/manual/about/what-is-vector.md

Porting over the "About" section from the `vector-website` repo.  I've updated the links for images in these files as needed.

chore(external docs):  Port over the about section

---

Cargo.lock
lib/vrl/compiler/src/expression.rs
lib/vrl/compiler/src/expression/function_call.rs
lib/vrl/compiler/src/expression/levenstein.rs
lib/vrl/tests/Cargo.toml
lib/vrl/tests/src/main.rs
lib/vrl/tests/tests/diagnostics/call_to_undefined_function.vrl

Closes #6726 
This changes the algorithm used to find the suggestions for alternative functions when a user uses an unknown function in remap.
For some unknown reason the ngrammatic algorithm was causing a segfault when running a release version with jemallocator used. See #6819 for a minimal case where this would blow up.
This segfault doesn't occur on nightly, so we may want to look into reinstating this functionality on future versions of the Rust compiler.

fix(remap): use levenstein distance to find alternative suggestions for undefined functions

---

lib/vrl/cli/src/cmd.rs

This commit removes recompilation of the passed VRL program for each
interior execution. The program is compiled only the once now.

chore: Avoid re-compiling VRL program for each CLI execute

---

lib/vrl/cli/src/cmd.rs

This commit corrects the build if `--no-default-features` is passed.
Previously we'd try to import repl even if that wasn't available.

chore: Only build repl if it's a flagged-on feature

---

lib/vrl/compiler/Cargo.toml
lib/vrl/compiler/benches/kind.rs
lib/vrl/compiler/src/value/kind.rs

According to the `coz` profiling done in https://github.com/timberio/vector/pull/6868#issuecomment-806040265 the `Display` implementation of `Kind` has an outsized impact on overall throughput, at least in the test setup. Micro-benchmarks have been introduced in this commit. Baseline: 
```
➜  compiler git:(blt-kind_quoted) ✗ cargo criterion kind
Finished bench [optimized + debuginfo] target(s) in 0.14s
vrl_compiler::value::kind::display/"string"
time:   [98.154 ns 98.528 ns 98.918 ns]
change: [+1.2007% +1.8956% +2.5809%] (p = 0.00 < 0.05)
Performance has regressed.
vrl_compiler::value::kind::display/"array"
time:   [94.712 ns 94.971 ns 95.233 ns]
change: [-2.9792% -2.2242% -1.4878%] (p = 0.00 < 0.05)
Performance has improved.
vrl_compiler::value::kind::display/"regex"
time:   [94.924 ns …
```

chore(remap): Improve the `Display` performance of `Kind`

---

docs/reference/remap.cue
docs/reference/remap/errors/103_unhandled_assignment_runtime_error.cue
lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/expression.rs
lib/vrl/compiler/src/expression/abort.rs
lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/compiler/src/expression/function_call.rs
lib/vrl/compiler/src/value/error.rs
lib/vrl/core/src/lib.rs
lib/vrl/core/src/runtime.rs
lib/vrl/parser/src/ast.rs
lib/vrl/parser/src/lex.rs
lib/vrl/parser/src/parser.lalrpop
lib/vrl/tests/src/main.rs
lib/vrl/tests/tests/diagnostics/syntax_error_ampersat_variable.vrl
lib/vrl/tests/tests/diagnostics/syntax_error_path_segment.vrl
lib/vrl/tests/tests/diagnostics/unhandled_parse_regex_all_type.vrl
lib/vrl/tests/tests/examples/blog_vector_remap_language_error_diagnostic.vrl
lib/vrl/tests/tests/expressions/abort/abort.vrl

This PR adds a new `abort` statement.
This will be used (in a follow-up PR) together with a Vector Remap transform `drop_on_abort` option, to allow people to ignore an event without generating an error during processing in a VRL program.
For example, one could write:
```coffee
status, err = int(.status)
if err != null {
abort
}
```
In this case, if `.status` isn't an integer, we don't want to raise an error, but we know we want to drop the relevant event.
To support this, there are two changes made:
- At runtime, we now distinguish between two type of non-ok results: `Terminate::Abort` and `Terminate::Error`. The caller (in this case, Vector), can distinguish between the two and decide what to do in each specific case.
- A new `abort` statement is added to the language to facilitate this …

feat(remap): add abort-statement

---

docs/reference/components/sinks/splunk_hec.cue

chore(splunk_hec sink): Document templatable fields

---

lib/vrl/stdlib/src/parse_duration.rs

fix(remap): Parse µs durations

---

src/conditions/mod.rs
src/transforms/route.rs

Closes: https://github.com/timberio/vector/issues/6821
If trying to serialize an object with a single String that also has `serde(flatten)`, the serialization throws an error.
This causes an error when attempting to serialize the object. This occurs when reloading the config to see what transforms have changed.
The flatten isn't needed, so removing it doesn't cause any issues.

fix(route transform): enable LaneConfig to be serialized

---

src/sources/syslog.rs

Closes #4895 
This makes a number of changes to the octet decoder for the syslog source.
1. If we receive invalid data, the source position needs to be advanced past the erroneous bytes, otherwise the decoder loops forever on that invalid data.
2. We need to handle data coming in over multiple frames. Before the decoder assumed all the data would come in a single frame and treat the next frame as a new message. This may not be the case. So now the decoder maintains some state to allow it to handle a single message coming in over separate frames.

fix(syslog source): improve frame handling for the octet decoder

---

Cargo.lock
Cargo.toml
src/mapping/query/query_value.rs

Follow up to https://github.com/timberio/vector/issues/6005 where it was
upgraded as the size of the struct was reduced.
Removed unnecessary allow(clippy::large_enum_variant)

chore(deps): Remove thread_local pinning

---

Cargo.lock
Cargo.toml

This reverts commit fc7c788b11ea46881d3c704404acd69eaa7bb450.
Fixes #6712

chore(deps): revert goauth to 0.8.1

---

src/sources/syslog.rs

This was a silent merge conflict between
https://github.com/timberio/vector/pull/6890
and https://github.com/timberio/vector/pull/6864

chore(syslog source): Needed clippy changes for 1.51

---

benches/remap.rs
benches/wasm/mod.rs
docs/reference/components/transforms/remap.cue
lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/program.rs
src/internal_events/remap.rs
src/transforms/remap.rs
tests/behavior/transforms/remap.toml

Dropping on error was previously possible, but undocumented.
This PR also adds an option to `drop_on_abort`, which defaults to `true`, and will instruct Vector to drop events when the program is manually aborted through the `abort` statement.
closes #6720

feat(remap): support dropping events when remap fails or is aborted

---

lib/vrl/stdlib/src/log_util.rs

Fix a simple typo in expectations
Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>

fix(apache): typo on the expectation for building regexps

---

.github/workflows/release.yml
scripts/release-homebrew.sh

The script depends on the artifacts being in S3, but was not depending
on that step and so could run earlier resulting in it checksuming the
404 response from AWS leading to
https://github.com/timberio/homebrew-brew/issues/6

fix(releasing): Fix release-homebrew workflow dependency

---

scripts/release-s3.sh

Broken by bd05957b
Caused failure seen here: https://github.com/timberio/vector/runs/2231243784?check_suite_focus=true#step:19:5432

fix(releasing): Fix package naming for latest artifacts

---

scripts/setup_integration_env.sh

The integration setup wrapper ran the sub-script in a subshell, to no
real effect. This execs it directly, as it is the last command in the
script.
I separated from #6954 as it could potentially break tests if the subshell was required for some shell specific behavior, so I'll be watching for breakage.

chore(tests): Exec integration setup sub-script

---

Cargo.lock
Cargo.toml

Follow-up on #5872 as integration tests failed for mongodb.

chore: Upgrade mongodb crate to be compatible with tokio 1.x

---

Cargo.lock
Cargo.toml
src/sinks/pulsar.rs

Closes #6660, related to #5872.

chore: Upgrade pulsar crate to be compatible with tokio 1.x

---

Cargo.lock
Cargo.toml
lib/k8s-e2e-tests/Cargo.toml

fix(deps): Upgrade reqwest in k8s-e2e-tests

---

.github/dependabot.yml

I don't see why not and, because of dependabot's limit of 10 open PRs,
it can take it a while to create new ones on the weekly schedule.

chore(deps): Update dependabot frequency to 1 day

---

Cargo.toml

chore(deps): Upgrade Tokio to 1.4

---

docs/reference/components/aws.cue

Fixes #7009
Example is from https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-aws_session_token.html

fix(external docs): Fix example for AWS_SESSION_TOKEN

---

src/sources/host_metrics.rs

Fixes #6920
Previously specifying any `includes` for device would cause no matches
due to bad boolean logic.

fix(host_metrics source): Fix filtering of filesystem by device

---

Cargo.toml

Fixes #6987 
Also move the systemd config file to
`/lib/systemd/system/vector.service` as this seems to be more customary
for debian
(https://manpages.debian.org/jessie/systemd/systemd.unit.5.en.html).
I spot checked a few other packages:
* haproxy
* openssh-server
* nginx
* datadog-agent
And they all put their systemd configs in `/lib/systemd/system`.
`/etc/systemd/system` is for users to put system specific systemd
configuration.

fix(releasing): Ensure /etc/default/vector is not automatically overwritten

---

docs/reference/remap/functions/parse_nginx_log.cue
docs/reference/urls.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_nginx_log.rs

Create a parse for nginx access logs and error logs.
It's mainly a copy of `parse_apache_log`.
https://github.com/timberio/vector/issues/6103

feat(remap): create parser for nginx access and error logs

---

docs/reference/components/sinks.cue

This reverts commit 4c42b7d9d259114251a1a1b3c2b7fb213cc04c49.
I'm not sure why it doesn't work, but currently it doesn't render the
image. The previous, and reinstated, syntax seems to embed the SVG
directly. This is how the other SVGs are used.
```
➜  vector git:(fix-svg) rg 'SVG src='
docs/manual/setup/deployment/topologies.md
16:<SVG src="/optimized_svg/topologies-distributed_453_298.svg" />
47:<SVG src="/optimized_svg/topologies-centralized_1564_502.svg" />
79:<SVG src="/optimized_svg/topologies-stream-based_1516_506.svg" />
docs/reference/components/sinks.cue
413:                                                                    <SVG src="/optimized_svg/buffers-and-batches-serial_538_160.svg" />
436:                                            <SVG src="/img/buffers.svg" /> …
```

fix(external docs): Fix batches and buffer SVG

---

Cargo.lock
Cargo.toml
benches/metrics_snapshot.rs
src/event/metric.rs
src/metrics/handle.rs
src/metrics/mod.rs
src/metrics/recorder.rs
src/metrics/registry.rs
src/sinks/util/adaptive_concurrency/tests.rs
src/sources/internal_metrics.rs
tests/metrics_snapshot.rs

This commit introduces our own metrics-rs `Handle` implementation, one that takes constant space per metric type. This significantly reduces our happy path memory use under load and should resolve memory leaks noted in the closing issues. The leak culprit is metrics-rs `Histogram` combined with tracing integration. Their implementation relies on an atomic linked list of fixed-sized blocks to store samples. The storage required by this method grows until a quiescent period is found, a period that happens regularly when metrics-rs is not integrated with tracing and does not happen at present for reasons unknown. However, in our testing we've seen that a single histogram under heavy load can consume approximately 200Mb before being garbage collected, a burden vector doesn't need to bear as …

chore: Use our own metrics-rs Handle implementation 

---

src/transforms/aws_ec2_metadata.rs

Broken by 0135730ee37bc4113c03db5fb8db008a44ea997a
This replaces the partial assertions for the namespace test which
I think is sufficient to test that part of the functionality. It was
previously failing because it matching two log events where the actual
log event had many more fields enriched than the expected event.

fix(tests): Fix aws_ec2_metadata transform test

---

distribution/helm/vector-shared/templates/_reroll.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

We discovered that the config hash included in the daemonset of the vector-agent chart does not change as the configuration is changed. Therefore the pods are not re-created. This can be validated in the current code base running:
```
helm template vector-agent
...
annotations:
checksum/config: 75958f6034a2d836d57468a572df3af05ea5d4eaf4b8b5cbd6371e6ec319a696
```
and then adding some parameter which should change the configuration to yield another hash, e.g.:
```
helm template vector-agent --set internalMetricsSource.enabled=false
...
annotations:
checksum/config: 75958f6034a2d836d57468a572df3af05ea5d4eaf4b8b5cbd6371e6ec319a696
```
The hash of the configuration should differ as the content of the config map differs - however the hash is the same.
The problem is this in `_reroll.tpl` of …

fix(kubernetes platform): Config map hash

---

docs/reference/remap.cue
docs/reference/remap/functions/parse_regex.cue
docs/reference/remap/functions/parse_regex_all.cue
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/parse_regex.rs
lib/vrl/stdlib/src/parse_regex_all.rs
lib/vrl/stdlib/src/util.rs
lib/vrl/tests/tests/examples/successful_parse_regex_type.vrl

Closes #6721 
This pr adds a `numeric_groups` parameter to the `parse_regex` and `parse_regex_all` remap functions - defaulting to false - that if true the result will contain the indexes of the groups parsed by the regular expression - index 0 contains the whole match.
Without the flag set, only named groups are returned.

enhancement(remap)!: added numeric_groups parameter to parse_regex functions

---

distribution/helm/vector-shared/templates/_reroll.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

This reverts commit 27bb756f2c815efc5bf3bf363c705810431a0853.
This broke the k8s end-to-end tests. I'll reopen as a PR for
investigation to keep master green.

chore(kubernetes platform): Revert config map hash (#7060)

---

lib/vrl/parser/src/lex.rs
lib/vrl/tests/tests/diagnostics/invalid_escape_char.vrl
lib/vrl/tests/tests/diagnostics/unterminated_literal.vrl

Closes #6879 
Closes #6875 
The lexer was getting stuck in an infinite loop when it reached an unclosed quote. This changes the `query_start` function so that it returns a `Result` which allows the function to return an error in that situation.
Turns out the lexer was getting stuck whenever it was lexing a literal from within function arguments as it was ignoring any errors raised from lexing the literals and got stuck lexing the same text repeatedly.

fix(remap): prevent lexer getting stuck on an unterminated literal

---

scripts/environment/bootstrap-macos-10.sh

Otherwise it tries to pull from bintray which is going away.
Example failure: https://github.com/timberio/vector/pull/7091/checks?check_run_id=2325858722

fix(ci): Update homebrew when bootstrapping OSX

---

docs/reference/components/sources/splunk_hec.cue
src/sources/splunk_hec.rs

This addresses https://github.com/timberio/vector/issues/6524, where the Splunk HEC source does not support receiving a Splunk channel via a query parameter, which is a valid behavior according to the [spec](https://docs.splunk.com/Documentation/Splunk/8.1.2/Data/FormateventsforHTTPEventCollector).

enhancement: Support Splunk channel via query parameter

---

docs/reference/components/sinks/datadog.cue
docs/reference/components/sinks/datadog_logs.cue
docs/reference/components/sinks/datadog_metrics.cue

Closes #7079
This was added to the shared Datadog documentation in
https://github.com/timberio/vector/pull/4174 but never added
specifically to the sinks.

fix(datadog service): Document region parameter

---

src/sinks/clickhouse.rs

fix #7048 clickhouse sink incorrectly encodes arrays

fix(clickhouse sink):  Fix clickhouse sink incorrectly encodes arrays

---

lib/vrl/compiler/src/type_def.rs
lib/vrl/stdlib/src/slice.rs

Closes #6676 
Given an array, the slice remap function won't necessarily know at compile time what indexes are being returned. So the returned type definition should be a collection of all the possible subtypes contained within that array. This means if the array contains a mixture of types, we can no longer determine the exact type definition of a given position in the array following that function.

fix(remap): slice function collects subtypes 

---

src/sources/docker_logs.rs

Enum bollard::container::LogOutput is Console when docker started
with a tty. LogOutput::Console was missing in the new_event of a
stream value received
https://docs.rs/bollard/0.10.1/bollard/container/enum.LogOutput.html
Fixes #5903

fix(docker_logs source): Docker logs missing when container has a tty

---

deny.toml

This advisory seems to no longer be valid.
Closes: #6223

chore(ci): Remove unneeded advisory from deny.toml

---

docs/reference/components/sinks.cue

Ensure `except_fields`, `only_fields`, and `timestamp_format` appear on
all sinks supporting `encoding`. Previously they only appeared on sinks
that had healthchecks.
Fixes: #6949

fix(external docs): Document additional encoding fields

---

.github/workflows/test.yml
deny.toml

I neglected to enable all features. The `wasm` dependencies still depend
on an affected version of rust-cpuid.
This reverts commit f30d4c6ed43838b36769753f2a591c2378162e04.
I also modified the github workflow to run the `cargo deny` steps if `deny.toml` was modified, which would have caught this issue.

chore(ci): Add advisory RUSTSEC-2021-0013 back to  deny.toml

---

.github/workflows/benches.yml
Makefile

CRITERION_HOME having "s was causing it to put it in the wrong place
(locally it created a directory called " and created the directory structure
under there).
Also just upload `./target/criterion` since Github does the
zipping for us. We did need to zip when previously downloading the
artifact in the same workflow as this was not zipped yet and so we were
hitting limits trying to individually pull a very large number of files.

fix(ci): Ensure all benchmark artifacts are included

---

docs/reference/remap.cue
lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/tests/tests/issues/6792_lost_type_defs.vrl

Previously, remap would overwrite the type def of `.` whenever a new
field was assigned. That is:
```
.foo = 5
.bar = 6
```
Would result in the compiler only having type info for `.bar`.
This change causes it to merge the typedefs whenever a list of path
segments appears.
Big thangs to @FungusHumungus for talking this one through with me.
This addresses the example that appears here: https://github.com/timberio/vector/issues/6792#issuecomment-817986771 . It may also resolve some of the other comments on that issue, but I'm not 100% sure until I get responses from the commenters since I couldn't reproduce the other cases.

fix(remap): Preserve type defs when assigning fields

---

lib/file-source/src/file_server.rs

Closes #6761 
The `kubernetes_logs` source exposes a `PathProvider` that breaks one of
the `FileServer`s assumptions that all available files will be listed at
Vector startup time. Instead, the files are only returned once the k8s
metadata is available to the `kubernetes_logs` source. This caused the
`FileServer` to ignore any checkpoints that existed for these files.
As a short-term fix, we just always use the checkpoint, if available,
for any new files that are seen. This fixes the case for the
`kubernetes_logs` source where they are seen as "new" after start-up.
https://github.com/timberio/vector/pull/6564 exists to test this
behavior, but it seems to pass even without this change, so that test
will need to be updated. I did test it out locally though.
Thanks to @lukesteensen for …

fix(kubernetes_logs source): Always use file checkpoints if they exist

---

lib/vrl/stdlib/src/contains.rs
lib/vrl/stdlib/src/ends_with.rs
lib/vrl/stdlib/src/starts_with.rs

Fixes #7044
The docs and examples indicated that it should default to case
sensitive; however, `contains`, `starts_with`, and `ends_with`,
defaulted to case insensitive matching. This updates the
implementation to use case sensitive matching by default.

fix(remap): Fix case_sensitive defaults for string matching functions

---

Cargo.lock
Cargo.toml

And `carge upgrade && cargo update --aggressive`.
I backed out a few changes:
```
Upgrading grok v~1.0.1 -> v1.2.0
Upgrading async-graphql-warp v=2.6.4 -> v2.8.2
Upgrading once_cell v1.3 -> v1.7.2
Upgrading async-graphql v=2.6.4 -> v2.8.2
```
Due to incompatibilities in package dependencies.
I backed out
```
Upgrading db-key v0.0.5 -> v0.1.0
```
Because it requires code changes.

chore(deps): Bulk deps update

---

src/event/value.rs
src/sources/docker_logs.rs

Fixes: #5716
Previously labels on docker containers were inserted in such a way that
dots in their names would end up creating a nested structure in the log
event due to the semantics of `LogEvent.insert`.
For example:
```json
{
"container_created_at": "2021-04-16T18:53:19.946155600Z",
"container_id": "d6bd69d4bc64bef20b4e992dcc23113741067e8268762694f92899504ae14319",
"container_name": "docker_echo_1",
"host": "COMP-C02DV25MML87",
"image": "hashicorp/http-echo:latest",
"label": {
"com": {
"docker": {
"compose": {
"config-hash": "e7e5ba19811180f27a7af36667652d0cd686599e6184cb023d9b71d791ff6a1e",
"container-number": "1",
"oneoff": "False",
"project": {
"config_files": "docker-compose.yml",
"working_dir": "/private/tmp/docker"
},
"service": "echo",
"version": "1.27.4"
}
}
}
},
"message": …
```

fix(docker_logs source): ensure that docker labels are flattened

---

Cargo.lock
Cargo.toml

Now that 0.13.0 is released, so the nightlies get a new version number.

chore(dev): Bump to 0.14.0

---

Cargo.lock
Cargo.toml
lib/vector-core/src/lib.rs
src/lib.rs

These two types are required for the `Event` interface. I have re-exported them
back in the top-level package so no code changes are necessary at that level.
REF #7148 

chore: Move `Result` and `Error` into vector-core

---

deny.toml

Closes https://github.com/timberio/vector/issues/5584.

chore(deps, security): Remove RUSTSEC-2020-0053 from ignore list since `dirs` is maintained again

---

deny.toml

Appears to no longer be relevant.

chore(deps): Remove RUSTSEC-2020-0146 from deny.toml

---

.github/workflows/cargo_hack.yml

In #7200 I ran into #7222 and figured we might do well to make cargo-hack use
official. These runs will take _a long_ time considering the feature surface of
this project so I've made it strictly a nightly run.

chore: Add a cargo-hack workflow

---

.github/workflows/cargo_hack.yml

We found in the previous run of cargo-hack that it was OOM'ed. While we were
expecting a build failure -- see #7222 -- we did not expect _that_ failure.
Run on self-hosted hardware to get more memory for the build.

chore: Run cargo-hack on self-hosted machines

---

src/sources/splunk_hec.rs

chore(splunk_hec source): Update to `futures` 0.3

---

docs/reference/remap/expressions/assignment.cue

chore(external docs): Document VRL |= operator

---

docs/reference/components/sources/kubernetes_logs.cue
src/sources/kubernetes_logs/mod.rs

Fixes: #6966
This is specifically to allow a user to workaround the too-low hardcoded
value that was being used.
We have https://github.com/timberio/vector/issues/6967 to address that.
I lost the logs that the user provided that ran over that limit but
I believe it was due to having a very large number of labels in the
metadata for each message which is not included in the normal 16 KB
docker limit.

enhancement(kubernetes_logs source): Allow configuration of max_line_bytes

---

src/sources/aws_s3/sqs.rs
src/sources/kafka.rs

Fixes: #7258
Previously, we were cloning the `Pipeline` for each message which, due
to the behavior of futures::sync::mpsc::channel resulted in the
effective channel buffer growing by one for each message rather than any
back pressure.

fix(kafka source): Fix runaway memory usage of kafka source

---

docs/reference/components/transforms/reduce.cue

Can be seen [here](https://vector.dev/docs/reference/configuration/transforms/reduce/). I believe this is the right place to fix but am not super familiar with how docs are generated.

fix(external docs): typo

---

lib/lookup/src/lookup_view/mod.rs
src/event/value.rs

The lookup PR #7087 had some broken doc tests in it. This fixes them.
@blt, sorry about the conflicts..

fix(tests): fixed doc tests from lookup

---

.github/workflows/test.yml
Cargo.toml
Makefile
lib/file-source/Cargo.toml
lib/k8s-test-framework/src/reader.rs
lib/tracing-limit/Cargo.toml
lib/vrl/compiler/Cargo.toml
lib/vrl/stdlib/Cargo.toml

We currently use `--all-targets` to include benches (`--bench`), but `--all-targets` does not include `--doc` apparently (https://github.com/rust-lang/cargo/issues/6669). Instead of using `--all-targets` we just mark benches with `test = true` so that they will be tested along with the default targets (https://doc.rust-lang.org/cargo/commands/cargo-test.html#target-selection)
Also:
* Avoid setting `SCOPE` by default in the `Makefile` as this causes examples to be skipped for some reason.
* Use `make test` for Windows to take advantage of existing make targets. I tried `make test-components` there too, but it failed to build krb5.

chore(tests): Simplify `cargo test` usage

---

.github/workflows/benches.yml
.github/workflows/test.yml
Cargo.toml
Makefile
src/expiring_hash_map.rs

This commit was born out of a discussion
[here](https://github.com/timberio/vector/pull/7240#discussion_r622519274). This
changes the CI tests to only output the test name when the test fails, replacing
it with a simple dot, and does not capture test output, meaning individual tests
that `println` etc are now more terse. Notably this does not reduce output
entirely -- VRL tests print their name still, there's seemingly some debug
output that is present elsewhere -- but it's a start.
I wasn't clear from the original discussion if we wanted `--quiet` or not, so I
went ahead and included it here. Happy to back that out if folks feel strongly.

chore: Make CI tests run a little more quiet

---

.github/workflows/cargo_flake.yml

I have struggled in #7240 to get reliable test results. This has inspired both
PR #7269 and #7306 to reduce both output and turn-around time for tests. In this
PR I introduce a tool that is meant to repeatedly run our tests and identify any
that are flakey.

chore: Run cargo-flake on the project

---

.github/workflows/test.yml

This commit introduces caching of `target/debug` into our jobs as well as the
use of `restore-keys` to hit cache even when `Cargo.lock` has changed. This
commit is further work from #7269

chore: Introduce more aggressive caching

---

Cargo.lock
benches/default.rs
lib/vector-core/Cargo.toml
lib/vector-core/benches/lookup.rs

While the fixture data for this benchmark was moved into `vector-core` as a part
of #7240 the benchmark itself was not. This broke the build.
Resolves #7329

chore: Move `benches/lookup` into vector-core

---

.github/workflows/benches.yml

I had included `continue-on-error` originally since we didn't want to
flag regressions yet, but this also suppresses other errors (like the
benches couldn't run).
The `|| true` in `scripts/check-criterion-output.sh` should stop it from
flagging regressions as failed CI checks still.

fix(ci): Flag benchmark runs that fail to actually execute

---

src/sources/splunk_hec.rs

Ref #7097 
Adds support on our side. See https://github.com/timberio/vector/issues/7097#issuecomment-830676486

fix(splunk_hec source): Default `host` to remote address

---

src/cli.rs
src/service.rs
src/unit_test.rs
src/validate.rs

Closes #7242
It turned out that the use of delimiters needed to be enabled. 
This was affecting all cli arguments with multiple values, except for one.
This is now possible
```
vector -c "generate.toml,host_metrics.toml"
vector -c generate.toml,host_metrics.toml
vector validate "generate.toml,host_metrics.toml"
vector validate generate.toml,host_metrics.toml
VECTOR_CONFIG='generate.toml,host_metrics.toml' vector
...
```

fix(cli): Enable use of delimiters

---

docs/reference/components/sinks/datadog.cue
docs/reference/components/sinks/datadog_logs.cue
src/sinks/datadog/logs.rs
src/sinks/datadog/metrics.rs

As per Datadog documentation https://docs.datadoghq.com/getting_started/site/, Datadog now support several sites, at least:
* datadoghq.com
* us3.datadoghq.com
* datadoghq.eu
* ddgov-gov.com (us govcloud)
That being said a new site will be automatically supported by vector. This setting shall be prefered over the region one (it has precedence) but the ultimate endpoint can always be overiden using the `endpoint` option that supersedes both `site` and `region`. 
Closes #7303

enhancement(datadog sinks): Generic site support

---

rfcs/README.md

First thought the Readme was instructing to copy the RFC `rfcs/2020-02-10-445-internal-observability.md` (which doesn't exist) as an example, and noticed there's a dedicated template.
Adding a reference to that for (even) easier discoverability.

chore: Reference RFC template in RFC readme

---

Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metric.rs
lib/vector-core/src/event/value.rs

While VRL is essential to vector it is not a part of core. Allowing core to be
built without linking to VRL was originally a feature of #7240 but was removed
as it increased the testing surface overmuch.
By default, now, vector-core will not link with VRL.
Partially addresses #7327

chore: Make vrl optional in vector-core

---

lib/vector-core/src/event/mod.rs

As noted by @bruceg in #7240 we could avoid the explicit call to
`LogEvent::default` by deriving `Default` for `MakeLogEvent`. This is now done
and I've tidied up the relevant call-site.
Partially resolves #7327

chore: Derive `Default` for `MakeLogEvent`

---

src/sinks/util/http.rs
src/sinks/util/service.rs
src/sinks/util/sink.rs

Just a code simplification I pulled out of my current work.

chore(sinks): Drop unnecessary `Request` parameter from types

---

distribution/debian/scripts/postinst

Right now, the postinst script is checking for `systemd-journald` group while the actual Debian group is `systemd-journal`. This PR fix this typo and will result in correctly adding the user `vector` to the `systemd-journal` group if present.

fix(debian platform): Check the correct systemd-journal group before adding the vector user

---

rfcs/2021-04-07-6330-emitting-multiple-log-events-from-remap-transform.md

RFC for https://github.com/timberio/vector/issues/6330

chore: RFC for emitting multiple log events from remap

---

distribution/debian/scripts/postinst

They verify installation in a container without systemd running so the
`systemctl daemon-reload` step fails.

chore(ci): Fix deb verify steps

---

docs/reference/remap/functions/parse_klog.cue
docs/reference/urls.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/parse_klog.rs

Closes: #6793
This is very similar to parse_glog but I think a separate function is
still prudent in-case they continue to diverge.
The biggest differences right now are just spacing and the fact that timestamps
don't have a year in them.

enhancement(remap): Add parse_klog function

---

docs/reference/components.cue
docs/reference/components/sinks.cue
docs/reference/components/sinks/aws_cloudwatch_metrics.cue
docs/reference/components/sinks/aws_s3.cue
docs/reference/components/sinks/azure_monitor_logs.cue
docs/reference/components/sinks/clickhouse.cue
docs/reference/components/sinks/datadog_logs.cue
docs/reference/components/sinks/datadog_metrics.cue
docs/reference/components/sinks/elasticsearch.cue
docs/reference/components/sinks/gcp_cloud_storage.cue
docs/reference/components/sinks/gcp_stackdriver_logs.cue
docs/reference/components/sinks/gcp_stackdriver_metrics.cue
docs/reference/components/sinks/honeycomb.cue
docs/reference/components/sinks/http.cue
docs/reference/components/sinks/humio.cue
docs/reference/components/sinks/influxdb_logs.cue
docs/reference/components/sinks/influxdb_metrics.cue
docs/reference/components/sinks/kafka.cue
docs/reference/components/sinks/logdna.cue
docs/reference/components/sinks/loki.cue
docs/reference/components/sinks/new_relic_logs.cue
docs/reference/components/sinks/prometheus_remote_write.cue
docs/reference/components/sinks/sematext_logs.cue
docs/reference/components/sinks/sematext_metrics.cue
docs/reference/components/sinks/splunk_hec.cue

It was previously rendering ERB which appears directly in the docs
output. Instead, I do the equivalent string interpolation here in cue.
I'm curious if there is a better way to set `_parameter` than I found
which has a bunch of conditions due to the lack of an `else` clause.
I also fixed an issue that the `kafka` sink supports both `max_events`
and `max_bytes` but has a default of `null`. I updated the sink level
cue definition to let these keys be optional rather than assuming `null`
means unsupported.

fix(external docs): Fix rendering of buffers/batches sections

---

lib/vector-core/src/event/finalization.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/metric.rs
lib/vector-core/src/event/mod.rs
src/pipeline.rs
src/sources/datadog/logs.rs
src/sources/heroku_logs.rs
src/sources/http.rs
src/sources/prometheus/remote_write.rs
src/sources/util/body_decoding.rs
src/sources/util/http.rs
src/test_util/mod.rs

Revert "enhancement(datadog source, http source): Add acknowledgement support (#7325)"
This appears to be causing CI to hang. I figured reverting was better
than letting it pile up until we can resolve.
This reverts commit 838bdb227c42ee42aee5f70e45706d5f0ae6d29a.

chore: temporarily revert 7325

---

distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml

Ability to specify a command to the daemonsets containers. This is required to pass secrets with berglas (https://github.com/GoogleCloudPlatform/berglas) with Google Secret Manager (see here https://github.com/GoogleCloudPlatform/berglas/tree/main/examples/kubernetes#limitations )

enhancement(ci): support in helm vector-agent to specify command

---

scripts/release-s3.sh

Ensures we publish latest artifacts as, for example:
https://packages.timber.io/vector/latest/vector-0.13.0-x86_64-unknown-linux-gnu.tar.gz
in addition to
https://packages.timber.io/vector/latest/vector-latest-x86_64-unknown-linux-gnu.tar.gz
The install script depends on them being there.
Fixes: #7206

chore(releasing): Ensure latest artifacts are also published with version number

---

Cargo.toml
distribution/debian/scripts/postinst
distribution/debian/scripts/preinst

Signed-off-by: Johann Queuniet <sub_code.git@queuniet.fr>
Those tags allow debhelper scripts to hook into your custom Debian scripts and add their own logic to it. Right now the vector service isn't properly enabled by the Debian package as it should be, and it is likely because of missing postinst code from `dh_systemd`.
```
● vector.service - Vector
Loaded: loaded (/lib/systemd/system/vector.service; disabled; vendor preset: enabled)
Active: active (running) since Wed 2021-05-05 16:16:54 UTC; 24h ago
```
The final postinst script compiled into the deb file should have a section like this one:
```
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
deb-systemd-helper unmask 'vector.service' >/dev/null || true
if …
```

fix(debian platform): Add debhelper include tags to Debian scripts

---

lib/vector-core/src/event/finalization.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/metric.rs
lib/vector-core/src/event/mod.rs
src/pipeline.rs
src/sources/datadog/logs.rs
src/sources/heroku_logs.rs
src/sources/http.rs
src/sources/prometheus/remote_write.rs
src/sources/util/body_decoding.rs
src/sources/util/http.rs
src/sources/util/mod.rs
src/test_util/mod.rs

Closes #7202 
This is a repeat issue of #7325 that was reverted in #7426 because of a broken test. This fixes the broken test case in the `heroku_logs` source, caused because this move actually added support for acknowledgements to that source as well. We will definitely want to make sure all tests pass before merging this one.
Note that this also enhances the `datadog_logs` source, but that tag is not in the semantic list so I cannot use it in the PR title.

enhancement(heroku_logs source, http source): Add end-to-end acknowledgements

---

docs/reference/remap/functions/encode_logfmt.cue
lib/vrl/compiler/src/value/convert.rs
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/encode_logfmt.rs
lib/vrl/stdlib/src/lib.rs

Fixes #6972
This PR introduces a new `encode_logfmt` function, which is the opposite of `parse_logfmt`.

feat(remap): Add `encode_logfmt` function

---

docs/reference/installation/_interfaces/docker-cli.cue

The configuration we ship has it listen on 8686 by default.
Closes: https://github.com/timberio/vector/issues/7312

fix(external docs): Fix the API port in the docker docs

---

src/sources/kubernetes_logs/mod.rs

This is documented on the `kubernetes_logs` source, but not actually
available.

fix(kubernetes_logs source): Exposed data_dir configuration

---

.github/workflows/nightly.yml
.github/workflows/release.yml

Not having git causes the checkout action to fall back to using the REST
API which seems to require `tar`, likely after #7424, which the
amazonlinux:2 does not seem to have preinstalled.
Instead, just install the dependencies first.
See current nightly failure here: https://github.com/timberio/vector/runs/2589042546?check_suite_focus=true

fix(ci): Install git before checking out for verify jobs

---

scripts/environment/Dockerfile
scripts/environment/entrypoint.sh

This adds CROSS_DOCKER_IN_DOCKER as per
https://github.com/rust-embedded/cross#docker-in-docker and sets
`HOSTNAME` to the container ID as `cross` uses that with `docker
inspect` to fetch metadata and, since we use `--net=host`, HOSTNAME is
set to the hostname of docker host.

chore(dev): Configure cross to run correctly in `make environment`

---

src/sources/aws_s3/mod.rs
src/sources/aws_s3/sqs.rs

Fixes: #7437 
Per
https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html
the object key names in the SQS notification are URL encoded.
Notably
> Amazon S3 returns "application/x-www-form-urlencoded" as the content type in the response
is a lie. It returns `application/xml`.

fix(aws_s3 source): Properly handle urlencoded S3 object keys

---

CONTRIBUTING.md
lib/k8s-e2e-tests/src/lib.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-e2e-tests/tests/vector.rs

This allows you to specify thet namespace to run the kubernetes tests in by specifying a `NAMESPACE` environment variable:
If one isn't specified it defaults to `test-vector`.
eg.
```
NAMESPACE=florkshnoog CONTAINER_IMAGE_REPO=plork/vector-test SCOPE=glob_pattern_filtering  make test-e2e-kubernetes
```

enhancement(tests): specify the namespace to run k8s test in

---

docs/reference/installation/_interfaces/apt.cue
docs/reference/installation/_interfaces/docker-cli.cue
docs/reference/installation/_interfaces/dpkg.cue
docs/reference/installation/_interfaces/homebrew.cue
docs/reference/installation/_interfaces/nix.cue
docs/reference/installation/_interfaces/rpm.cue
docs/reference/installation/_interfaces/vector-installer.cue
docs/reference/installation/_interfaces/yum.cue
docs/reference/installation/interfaces.cue
docs/reference/installation/operating_systems.cue

Currently always renders as "none" due to `_shell` not propagating all
the way down. I was able to refactor this a bit to avoid needing to pass
_shell around based on the suggestion in
https://github.com/cuelang/cue/discussions/975#discussioncomment-752611
to use nested field definitions.
Closes: #7397

fix(external docs): Fix configure command in installation instructions

---

lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector.rs

#7388 was merged a tad prematurely. 
Not all the tests were updated to handle the override name. It also seems the tests for the Vector helm chart don't handle the namespace overriding well, so I have reverted those changes and will investigate a solution shortly.

fix(tests): fix broken k8s tests

---

src/sinks/util/encoding/mod.rs

Fixes: #7322
Currently, vector drops all subkeys from structured fields that don't
appear in `only_fields`, but it leaves the parent key. This fixes that
by pruning the parent if all subkeys were deleted.

fix(codecs): Filter object and array fields with only_fields

---

distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_image.tpl
distribution/helm/vector/values.yaml
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

Adds the last value to close #4443, based off the pre-existing work in [bitnami's postgres chart](https://github.com/bitnami/charts/blob/e91188c1dc8e409fd944962268ced92273f40e10/bitnami/postgresql/templates/_helpers.tpl#L297-L336)

enhancement(helm platform): Allow for global imagePullSecrets

---

scripts/environment/prepare.sh

A couple of people have been confused by its lack.

chore(dev): Pre-install cross in `make environment` image

---

deny.toml

Also removed RUSTSEC-2019-0036 which was no longer applicable.

chore(ci): Ignore RUSTSEC-2021-0067 while we try to fix it

---

.github/workflows/nightly.yml
.github/workflows/release.yml
scripts/environment/bootstrap-ubuntu-20.04.sh

We seem to be running out of memory on some builds.
Example failure:
https://github.com/timberio/vector/runs/2652886513?check_suite_focus=true
This PR runs the release builds on the self-hosted runners. Since they are now on the self-hosted runners, they need some more setup steps (copied from the Linux unit test workflow) and no longer need to run the `ci-sweep` job which was to free up resources on the hosted runners.

fix(ci): Try building release artifacts on self-hosted runners

---

Makefile

As is, the `bench-wasm` target has one argument too many and doesn't actually run cleanly.  I've also tweaked how the bench flags are included so that there's no extra empty argument present when the flags aren't set, which just makes the output a little cleaner.
Signed-off-by: Toby Lawrence <toby.lawrence@datadoghq.com>

chore(ci): fix bench-wasm target

---

.github/workflows/benches.yml
scripts/upload-benchmarks-s3.sh

This is a simplistic attempt at splitting up the benchmark runs in CI. Normally, we would invoke `make bench-all` which runs the sum of six otherwise individual/distinct benchmark groups. Now, we use a matrix build over those six individual benchmarks to run them in parallel, subject to runner availability. This should conceivably bring down the benchmark time to somewhere around the duration of the longest benchmark group, which should still be far below the current ~4 hour duration for benchmarks.
Signed-off-by: Toby Lawrence <toby.lawrence@datadoghq.com>

chore(ci): parallelize benchmarks

---

docs/reference/components/sources/internal_metrics.cue
docs/reference/components/sources/kubernetes_logs.cue
src/internal_events/kubernetes/instrumenting_watcher.rs
src/kubernetes/instrumenting_watcher.rs

fix(kubernetes_logs source): Replace incorrect invocation error with WatchStreamFailed

---

docs/reference/components/sinks/datadog_logs.cue
docs/reference/components/sources/datadog_logs.cue
lib/vector-core/src/event/metadata.rs
src/sinks/datadog/logs.rs
src/sources/datadog/logs.rs

It comes with:
* A few detail in the doc
* A flag not to save the API key in metadata

enhancement(datadog_logs sink): Use per-API key partitions for datadog logs sink

---

docs/reference/components/sinks/socket.cue

This config is only required when `mode` is `unix`.

fix(external docs): Fix relevant_when for socket.path config

---

.github/workflows/test.yml

Since we seem to be running out of memory during the build phase.
I'll see if CI passes here and maybe rerun a few times.
Example failure: https://github.com/timberio/vector/runs/2658803781

chore(ci): Try running Linux unit tests with less parallel jobs

---

lib/vector-core/src/event/mod.rs
lib/vector-core/src/event/proto.rs

This breaks out all the event proto related code into a separate module in `src/vector-core` and breaks up the `From` implementations into more primitive blocks. This introduces no new functionality other than the ability to convert to/from more parts of the event protocol.

chore: Reorganize event proto module

---

scripts/environment/bootstrap-ubuntu-20.04.sh

This script is run by the Dockererfile for `make environment` which
doesn't actually have an `ubuntu` user.
Failure: https://github.com/timberio/vector/runs/2665641110
This was broken by https://github.com/timberio/vector/pull/7564

fix(dev): Optimistically add ubuntu to docker group

---

src/internal_events/log_to_metric.rs
src/transforms/log_to_metric.rs

This is the documented behavior but we were not honoring it.

fix(log_to_metric transform): Drop events where `field` is null

---

lib/vector-core/buffers/src/disk/mod.rs
lib/vector-core/buffers/src/lib.rs
src/buffers.rs
src/topology/builder.rs
src/topology/mod.rs
src/topology/task.rs
src/utilization.rs

This commit adds an explicit +Unpin to our buffer type definition, introducing
`EventStream` type alias to tidy up some repitition. This is done to support
pull request #7576 where this changed is needed but is a little outside the
scope of that PR. The major change here is in `src/utilization` where I had to
re-implement the select loop to use an explicit stream definition. The `stream!`
macro used previously couldn't make the `+ Unpin` guarantee. It wasn't clear to
me that it could be fixed upstream.

chore: Add an explicit +Unpin to our buffers

---

lib/vrl/cli/src/cmd.rs
lib/vrl/cli/src/lib.rs

Currently, the actual details of the errors are masked so that users
just see things like: `parse error` and `json error` without additional
detail about what the issue is. This change ensures we display the
source of the error.
I also fixed the help doc for `--input` that was confusing a user as
they thought, understandably, that they could pass a pretty-printed JSON
object as a file; however `vector vrl` expects one JSON object per line.
We can improve this in the future to actually allow a prety printed
object here, but this at least makes the help doc accurate.

fix(cli): include error details in `vector vrl` output

---

Cross.toml

By default, `cross` won't pass through environment variables to the build container unless explicitly added to the `passthrough` setting in `Cross.toml`.  We need to do this for `VECTOR_BUILD_DESC` so that we can properly add back the `<git sha> <build time>` portion of the `vector --version` output. 

chore(ci): allow VECTOR_BUILD_DESC to be passed thru during packaging

---

docs/reference/remap/functions/match_any.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/match_any.rs

This is currently built on top of #7250 to take advantage of some of @jszwedko additions there. ~~It's also not documented and has one `unwrap` that needs removed, but I'm opening it in this state to get some feedback since it's my first real work with VRL.~~
The goal here is to optimize the case of checking against multiple regexes. Instead of `match(.foo, ...) || match(.foo, ...) || ...`, you can simply pass an array of patterns that are compiled to a `RegexSet` and checked efficiently in one pass. This is also more ergonomic than asking users to combine patterns manually.

enhancement(remap): add match_any function

---

lib/vector-core/buffers/src/disk/leveldb_buffer/reader.rs

Ref. #7425
Fixes issue with residual ldb files by requiring minimal size of uncompacted bytes. https://github.com/timberio/vector/issues/7425#issuecomment-849522738

fix(buffers): Min uncompact size

---

CONTRIBUTING.md
docs/reference/components/sinks.cue
docs/reference/components/sinks/elasticsearch.cue

In [sinks.cue](https://github.com/timberio/vector/blob/9b5d3b6efcf88c8dbe5901bee8ecb91149474096/docs/reference/components/sinks.cue#L164-L188), the `only_fields` and `except_fields` have the same description. This change fixes the description to show the correct function.
In [elasticsearch.cue](https://github.com/timberio/vector/blob/9b5d3b6efcf88c8dbe5901bee8ecb91149474096/docs/reference/components/sinks/elasticsearch.cue#L240), i've added a clarification that the operation will not update the document, but replace it. Usually updates will "patch" a partial document, but the `index` action replaces the full document, so if a partial document is sent, it will overwrite the existing one.
Fix a broken link in CONTRIBUTING.md

chore(external docs): clarify ElasticSearch bulk actions #7616

---

src/sinks/aws_cloudwatch_logs/mod.rs

fix(aws_cloudwatch_logs sink): Fix healthcheck to allow for log group creation at runtime

---

lib/vector-core/buffers/src/disk/leveldb_buffer/mod.rs
lib/vector-core/buffers/src/disk/leveldb_buffer/reader.rs

Ref. #7425
Reduces performance impact of deletes. In worst case scenario when sink manages to stay up to date, every event would result in one delete operation which negatively impacted write/read performance. This PR batches deletes to reduce that.

fix(buffers): Batch delete

---

lib/k8s-e2e-tests/Cargo.toml
lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/interface.rs
lib/k8s-test-framework/src/vector.rs
scripts/deploy-public-chart-test.sh
scripts/test-e2e-kubernetes.sh

Quick summary:
* Add the ability to spawn a generic chart into the k8s e2e tests framework
* Spawn a datadog agent, a vector aggregator and a dummy pod, the datadog agent read container log, ship those to vector where delivery is asserted in a simple test
Side note:
./lib/k8s-test-framework/src/vector.rs may be rename `chart.rs` as it now manage charts on a general basis on not only vector.

enhancement(tests): e2e logs ingestion from Datadog agent to Vector

---

docs/reference/components/sinks.cue

Ref.  #7425
Not sure if the warning is visible enough, maybe it should be moved.

chore(external docs): Document `disk` buffer behavior

---

distribution/helm/vector-agent/templates/NOTES.txt
distribution/helm/vector-aggregator/templates/NOTES.txt
distribution/helm/vector/templates/NOTES.txt
docs/highlights/2021-06-01-removing-helm-rawconfig.md

As far as I can tell, the only notice of deprecation before was the comments in `values.yaml`.
This will provide a more official notice and let us remove `rawConfig` with the 0.15 release.

chore(helm platform): Add deprecation notice for rawConfig

---

scripts/util/git_log_commit.rb

Currently, when listing commits from the last release during release
note generation, we end up:
* missing commits that appear in master before the last patch release
* listing commits that were released in the last patch release that were
cherry-picked from master and thus should not be included in the next
release changelog
Here we add `--right-only --cherry-pick`. `--right-only` limits to
commits that appear in master and excludes commits that are in the patch
release. `--cherry-pick` ensures we supress commits that were
cherry-picked and appear in the last patch release.
For example, generating the notes for v0.14.0 which looks at the log from v0.13.1, with this change, yields this diff from what it was previously:
```
0240ae601 - (fix-discord-action-versio) enhancement: created new …
```

chore(releasing): Fix commit listing when generating release notes

---

.github/semantic.yml
scripts/release-prepare.rb

Currently docs and task types are filtered however:
* docs is not actually a type though it appears as a toggle on the
release notes page (see https://vector.dev/releases/0.13.0/#changelog
for example)
* chore is a togglable type on the release notes page (it defaults to
unchecked)
Given this, I think it is appropriate to include all commits and let
users filter them. I would like to add additional filter capabilities to
the changelog in the future to, for example, filter out internal only
changes.

fix(releasing): Remove filters from changelog generation

---

docs/reference/components/sources/kubernetes_logs.cue
src/sources/kubernetes_logs/mod.rs

Closes #6771 
This updates the glob_minimum_cooldown_ms default to be 1000 ms.  It also adds documentation for the field.
This field is only the time it scans for new files within a pod, presumably for logs being rotated. It doesn't affect the time we are scanning for new pods. I am currently wondering if this needs to be documented too..

enhancement(kubernetes_logs source): Changed default for glob_minimum_cooldown_ms

---

rfcs/2021-06-01-7694-improve-monitor-build-performance.md

Closes #7694 
[Rendered markdown](https://github.com/timberio/vector/blob/tobz/rfc-7694/rfcs/2021-06-01-7694-improve-monitor-build-performance.md)

chore: RFC for improving/monitoring build performance

---

lib/vector-core/src/event/metric.rs
src/api/schema/metrics/filter.rs
src/sinks/prometheus/exporter.rs
src/sinks/util/buffer/metrics.rs
src/sinks/util/mod.rs

Closes #6045
**Note:** This changes the behavior of vector when an incoming metric stream changes type within a batch, including where histogram buckets are divided. This should effectively never happen in normal circumstances. We discussed documenting it, but I am unsure where would be appropriate.

chore(metrics): Rework metrics batch buffer

---

lib/lookup/src/lookup_buf/mod.rs
lib/lookup/src/lookup_buf/segmentbuf.rs
lib/lookup/src/lookup_view/mod.rs
lib/vector-core/buffers/src/variant/disk_and_memory.rs
lib/vector-core/src/event/discriminant.rs
lib/vector-core/src/event/legacy_lookup/mod.rs
lib/vector-core/src/event/legacy_lookup/segment.rs
lib/vector-core/src/event/value.rs
lib/vector-core/src/mapping/mod.rs

This commit trims public but otherwise unused functions from the codebase. I
used [warnalyzer](https://github.com/est31/warnalyzer) to find possible
public-but-dead candidates and manually tested each one. `warnalyzer` doesn't
have insight into tests, macros so it's possible I've deleted something needed
here and haven't quite got the right feature flags to light it up.
Neat tool, warnalyzer.

chore: Trim unused public functions

---

src/transforms/mod.rs

The `transform_one` function was added in #7701 but is unused by benchmarks,
which causes a warning when we compile them as test instances. This commit
allows `transform_one` to be dead to avoid the warning in that context.
Resolves #7728
REF #7733 

chore: Remove `transform_one` warning ding

---

src/sources/kubernetes_logs/mod.rs

Closes #7737 
It seems the recent change to 1000 was too small and wasn't giving the source enough time to be able to pick up the ip address of the associated pod. This changes it to 5000, which should hopefully be better.

fix(kubernetes_logs source): change glob minimum value to 5000

---

lib/vector-core/src/event/util/log/all_fields.rs
src/sinks/util/encoding/mod.rs

Currently, if the log event has a flattened dotted path like
`label.com\.docker\.stack\.namespace` it fails to be removed by
`only_fields` because fetching the keys for the event previously
returned unescaped keys. That is, it returned
`label.com.docker.stack.namespace` instead of
`label.com\.docker\.stack\.namespace`.
Notably, the keys syntax here is still using the legacy `.` escaping
rather than the path quoting that VRL supports (like
`label."com.docker.stack.namespace"`). Eventually we'd like to unify
these still.
Fixes: #7546

fix(codecs): Ensure that flat dotted paths are removed by only_fields

---

Cargo.lock
lib/k8s-e2e-tests/Cargo.toml
lib/k8s-e2e-tests/src/lib.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
lib/k8s-e2e-tests/tests/vector.rs
lib/k8s-test-framework/Cargo.toml
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/helm_values_file.rs
lib/k8s-test-framework/src/lib.rs
lib/k8s-test-framework/src/pod.rs
lib/k8s-test-framework/src/up_down.rs
lib/k8s-test-framework/src/util.rs
scripts/test-e2e-kubernetes.sh

Closes #7541 
Closes #7542
This PR makes three changes to our test suite to enable it to run on multinode kubernetes clusters.
1. It determines which node a given test pod is installed on and queries the logs from the Vector pod installed on that node. Before it would query a random pod in the daemonset.
2. It sets up Pod affinity to ensure that all test pods are installed on the same node so only a single Vector instance needs to be queried for that test.
3.  Customises the directory Vector is mounted to so that multiple Vector agents can be running on a node at any one time.
I have tested on Minikube and multinode Kind so far. Will test on AWS shortly..

enhancement(tests): run k8s-e2e tests on multinode kubernetes

---

lib/vrl/compiler/src/expression/op.rs
lib/vrl/compiler/src/value/arithmetic.rs
lib/vrl/tests/tests/expressions/comparison/ge.vrl
lib/vrl/tests/tests/expressions/comparison/gt.vrl
lib/vrl/tests/tests/expressions/comparison/le.vrl
lib/vrl/tests/tests/expressions/comparison/lt.vrl

feat(remap): add string comparison capability

---

lib/vector-core/src/lib.rs
lib/vector-core/src/source.rs
src/sources/mod.rs

This commit moves the `Source` type alias down into core. There's
little else that needs to be done here, not like with `Sink` which is
coming shortly.
REF #7150

chore: Move `Source` into core

---

src/sources/aws_s3/mod.rs
src/sources/aws_s3/sqs.rs

The new `client_concurrency` was not being correctly defaulted as we
were deriving `Default` rather than letting `Derivative` do it to call
our custom functions. The result was that it would default to 0 and the
source would immediately shut down.
I also added in `trace_init` calls to these tests to help with
debugging them.

chore(tests): Fix aws_s3 source integration tests

---

src/trace.rs

Currently tracing output always appears in tests because it side-steps
the print macros that `libtest` hijacks to capture output. Calling
`with_test_writer` swaps to using `print!` and so is captured
appropriately. It will now be output only if the test fails.
I attempted to refactor this a bit but struggled again to make this more
composable due to the fact that Subscribers and Layers are generic over
much of their configuration. I welcome thoughts here though.

chore(tests): Ensure that tracing output is captured

---

Cargo.lock
lib/vector-core/Cargo.toml
lib/vector-core/src/lib.rs
lib/vector-core/src/sink.rs
src/sinks/mod.rs
src/sinks/util/sink.rs

This commit moves `VectorSink` and `StreamSink` into core, leaving behind a fair
bit extra of the sink traits. Sink is our most complicated notion in vector by
far and fairly self-referential in its implementation. Getting it teased into
core will take some doing and will, very likely, need to be driven by need.
Future work in this area will be done one piece at a time. There's simply too
much code to move in bulk.
REF #7150

chore: Move `VectorSink`, `StreamSink` into core

---

distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_labels.tpl
distribution/helm/vector/values.yaml
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

enhancement(helm platform): Kubernetes recommanded labels and additional labels

---

scripts/setup_integration/kafka_integration_env.sh

Ref: https://github.com/wurstmeister/kafka-docker/issues/669
Fixes broken integration tests:
https://github.com/timberio/vector/runs/2766357722?check_suite_focus=true

chore(tests): Pin kafka version due to missing zstd support in latest

---

src/sources/fluent.rs

This commit corrects a clippy ding regard the needless clone of tag in
sources/fluent.rs. Looks like clippy got smarter. Noticed this as a part of my
work on #7783 which does not interact.

chore: Correct clippy ding in master

---

lib/vrl/parser/build.rs

The build.rs for vrl-parser placed its rerun-if-changed at the bottom of the
build.rs file, meaning cargo would not know to check if the grammer had changed
until after it had already rebuilt. This commit should save a minute of cycle
time, noticed as I was working on #7783.

chore: Rebuild vrl-parser only if parser.lalrpop has changed

---

.github/workflows/benches.yml
.github/workflows/cargo_flake.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/test.yml

This commit adds "-D warnings" to relevant Github Actions workflows, ensuring
that the build will fail if we leave any warnings present in the project.
Resolves #7733

chore: Warnings break build

---

src/app.rs
src/cli.rs
src/config/format.rs
src/config/loading.rs
src/config/mod.rs
src/config/unit_test.rs
src/config/watcher.rs
src/internal_events/process.rs
src/service.rs
src/transforms/lua/v2/mod.rs
src/unit_test.rs
src/validate.rs

This adds support for passing a configuration directory to look for
configuartion files to supplement the existing support for specifying
individual files. Vector will ignore any files in this directory that
are not one of its known formats (yaml, json, toml).
The motivation for this change is primarily to support a future change
to the way we manage helm charts to, instead of trying to build one
configuration file, instead write a separate file for managed sources
(`managed.yaml`) rather than translating it everything to TOML and
writing `vector.toml`; however it should also more easily enable users
to use a set of configuration files. We do currently support globbing,
but that has the disadvantage of causing a failure on start-up if the
glob doesn't match any files (which I think is …

feat(cli): Add support for --config-dir

---

src/sources/splunk_hec.rs

* enhancement: add x-forwarded-for support
- When an X-Forwarded-For HTTP Header is supplied with a request:
- pull out the value
- attempt to serialize it to an IpAddr
- set as the value for a `splunk_remote_addr` field in the event
Closes https://github.com/timberio/vector/issues/6763

enhancement(splunk_hec source): add x-forwarded-for header support

---

.github/workflows/metrics.yml
.github/workflows/nightly.yml

This PR adds a new workflow -- `metrics.yml` -- which is triggered by the completion of some of our other more common workflows, such as benchmarking and test suites.  When these workflows complete, this new workflow will extract metrics from them -- how long it was queued, how long it ran, success vs failure, etc -- and emit those metrics to our internal Datadog.

chore(ci): add tracking of workflow metrics for common workflows

---

lib/k8s-test-framework/src/namespace.rs
lib/k8s-test-framework/src/test_pod.rs
scripts/deploy-kubernetes-test.sh
scripts/test-e2e-kubernetes.sh

Ref #7540 
This makes the k8s tests pass `--force=true --wait-period=0 --wait=false` when deleting pods and namespaces to prevent the tests from waiting around whilst clearing up. This shaves several minutes from the test time.

enhancement(tests): delete resources without waiting in k8s tests

---

tests/data/wasm/assert_config/Cargo.lock
tests/data/wasm/drop/Cargo.lock
tests/data/wasm/multifaceted/Cargo.lock
tests/data/wasm/panic/Cargo.lock
tests/data/wasm/parse_json/Cargo.lock
tests/data/wasm/parse_syslog/Cargo.lock
tests/data/wasm/protobuf/Cargo.lock

Noticed that these were updated when I ran `make bench-wasm`.

chore(deps): Update Cargo.lock files for wasm tests

---

CONTRIBUTING.md

This option was removed in #7599, but I neglected to remove it from the CONTRIBUTING.md.
The namespace is now genererated randomly.

docs: Remove NAMESPACE from Contributing.md

---

docs/reference/components/sinks/elasticsearch.cue
src/sinks/elasticsearch.rs

Just adds the ability to use templating for the bulk action.

feat(elasticsearch sink): bulk action template

---

lib/k8s-e2e-tests/tests/vector-agent.rs

As noted in #7798  there is the potential for flakiness in tests. 
Some tests create a pod purely for the purpose of other tests to have affinity to to ensure they are all deployed on the same node. However these tests also scan the logs for any pods in a given namespace to test various things. If the affinity pod is created in this namespace there is the potential for any logs they create to interfere with the tests.
This PR creates these affinity pods in a separate namespace so they don't have the risk of getting in the way.

enhancement(tests): Create affinity pod in separate namespace for k8s tests

---

Makefile

As per https://github.com/mirror/make/blob/master/NEWS#L408-L414 the order pattern are match have change in GNU `make` 3.82, however macosx is shipping 3.81 and the target `cross-%` was defined before `cross-image-%` effectively leading to an unexpected behaviour as `cross-image-%` would never match. E.g. `make cross-image-xyz` would effectively match the taget defined as `cross-%`. 
It should help a bit #7545 by letting user use the `make` version shipped with macosx.

enhancement(dev): support older `make` version

---

.github/workflows/k8s_e2e.yml
docs/reference/components/sources/kubernetes_logs.cue
docs/reference/installation/platforms/kubernetes.cue
docs/reference/services/kubernetes.cue

While Vector still _runs_ on kubernetes 1.14.x, as far as I can tell it's no longer offered/supported
by any major cloud provider. Right now #6564 is failing CI as we try to use a kubectl command that isn't
supported in 1.14.x (`rollout restart`).
This PR does the following:
- Drops 1.14.10
I'd also suggest consider adjusting our documentation around required/supported kubernetes versions. We'll also need to update and include more versions in a followup

chore(ci)!: Update tested Kubernetes versions

---

distribution/helm/vector-agent/templates/daemonset.yaml
lib/k8s-e2e-tests/src/lib.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
lib/k8s-e2e-tests/tests/vector.rs

Closes #7544
As suggested [here](https://github.com/timberio/vector/pull/7810#issuecomment-857902297), this PR introduces lifecycle hooks into our Helm chart which the tests can use to cleanup the Vector data directory on deletion.
As this is my first actual work with the Helm charts, I would especially appreciate advice on whether I have implemented the changes there correctly.

enhancement(tests): cleanup vector dir post k8s test

---

docs/reference/components/sinks/clickhouse.cue
docs/reference/components/sinks/http.cue

It is actually defaulting to 10 MiB
Discovered by discord user:
https://discord.com/channels/742820443487993987/746070591097798688/852944913187864606

docs(http sink, clickhouse sink): Correct default max_bytes

---

docs/reference/components/sinks/clickhouse.cue
src/sinks/clickhouse.rs

Closes #6891
Defaults to false to maintain existing behavior. Integration test added to verify `true` allows unknown fields, existing integration tests cover the `false` path.

feat(clickhouse sink): Allow enabling `input_format_skip_unknown_fields`

---

lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/lib.rs
lib/k8s-test-framework/src/restart_rollout.rs

chore(kubernetes_logs source): Adds tests for checkpointing regressions in k8s

---

.github/workflows/benches.yml
Cargo.lock
Cargo.toml
benches/transform/common.rs
benches/transform/dedupe.rs
benches/transform/filter.rs
benches/transform/main.rs
benches/transform/reduce.rs
src/transforms/dedupe.rs
src/transforms/reduce/mod.rs

This commit introduces new transform benchmarks, written to be the bottom-up peer of our soak testing work. That is, these benchmarks should stable per-transform and allow us to do "napkin math" on a vector config composed of benched transforms. If we measure that on such-and-such computer a topology of transforms can achieved X throughput but in soak testing find out that the config does Y and the two X and Y are not within some tolerance of one another we have a bug. 
In order to achieve that ultimate goal these benchmarks should eventually be rigged up to have transform configurations that are peered to a soak configuration. It's early days yet for soak testing in the vector project so the configs in this commit are guesses. The point here is to have something that works, is stable in …

chore: Initial work on new transform benchmarks

---

.github/workflows/k8s_e2e.yml
CONTRIBUTING.md
scripts/test-e2e-kubernetes.sh

closes #7545
Account for minikube/kind non-default cluster name and
switch from `minikube cache` to `minikube image` as
the former is scheduled for deprecation.

enhancement(dev): k8s e2e tests script minor improvements

---

CONTRIBUTING.md

Adding some tidbits about using `sccache` locally when developing Vector.
Closes #7736.

chore(dev): add docs about using sccache locally

---

.github/workflows/environment.yml
scripts/environment/Dockerfile
scripts/environment/bootstrap-ubuntu-20.04.sh

This was removed in e147113ba as our CI runners already have this
installed, but the bootstrap script is also shared with the `Dockerfile`
used to create the image used by `make environment`.
This is related to https://github.com/timberio/vector/issues/7862 which
should hopefully improve the bootstrapping situation.
Failure: https://github.com/timberio/vector/runs/2833564450#step:6:8338

fix(ci): Install rustup when creating docker environment

---

docs/reference/components/sources/kubernetes_logs.cue

Closes #7691
I also noticed `pod_labels` isn't rendering the examples properly, but couldn't figure out why.
Not sure how much we care given the replacement of the current site.

docs(kubernetes_logs source): Add missing ingestion_timestamp_field and fix descriptions

---

docs/reference/components/sinks/elasticsearch.cue
scripts/setup_integration/elasticsearch_integration_env.sh
src/sinks/elasticsearch.rs

This PR introduce the `data_stream` mode. The `bulk_action` is automatically set to `create` when using this mode.
``` toml
[sources.random]
type = "generator"
format = "json"
[transforms.random_clean]
type = "remap"
inputs = ["random"]
source = '''
.@timestamp = to_string(.timestamp) ?? to_string(now())
'''
[sinks.elastic]
type = "elasticsearch"
inputs = ["random_clean"]
endpoint = "http://localhost:9200"
index = "my-data-stream"
mode = "data_stream"
```

feat(elasticsearch sink): handle data stream mode

---

docs/reference/components/sinks.cue
src/sinks/new_relic_logs.rs

This is the only supported encoding for the New Relic sink.
There was some discussion about this in
https://github.com/timberio/vector/pull/5281 when the default was
dropped. It was dropped as we thought `text` was also a valid encoding,
that we would be adding shortly, in which case it would make sense to
make the user choose; however, I found that `text` is not a valid
encoding for the New Relic logs API
(https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/).
Also document the undocumented region field.
Fixes #7872 

fix(new_relic_logs sink): Default encoding field to json

---

docs/reference/components/sinks.cue
docs/reference/components/sinks/new_relic_logs.cue

Accidentally added this to `sinks.cue` in #7870 but it should be in
new_relic_logs.cue

docs(new_relic_logs sink): Move region documentation to correct file

---

.github/workflows/environment.yml

This was breaking this check on forks which do not have access to the
secrets.

fix(ci): Do not login for publish-new-environment on PRs

---

lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/assert_eq.rs
lib/vrl/stdlib/src/lib.rs

This PR adds an `assert_eq!` function with the goal of making writing
unit tests easier.
The output may change with
https://github.com/timberio/vector/issues/6261 to make it easier to see
the condition that failed.
Closes #7833

enhancement(remap): Add assert_eq! function

---

docs/reference/remap.cue

Closes #7881 (partially)
There is a snippet of text referencing how remap interacts with metric events, but it's not rendered on today's website.
Do we want to edit the existing website and correct the snippet, or have an issue to ensure we document the interactions on the new website?

docs(remap): Fix 'Modify metric tags' example

---

docs/reference/configuration.cue
src/config/compiler.rs
tests/config.rs

https://github.com/timberio/vector/pull/6170 had added support for
wildcards in identifiers in vector configs, but only as the last
character. This PR expands support to allow glob matching in the same
way that `vector tap` does which allows for `*` to appear anywhere in
the input name.
Closes #6786

enhancement(config): Allow wildcards anywhere in identifiers

---

.github/workflows/nightly.yml
scripts/set-build-description.sh

This commit builds a release binary with debuginfo included. We build only a
tarball to avoid the situation where a user might install our CD-sized binary
accidentally. I have not made any changes to release-s3.sh as it didn't seem
like most other artifacts were explicitly mentioned there.
Resolves #7892

chore: Build a fat release binary

---

distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_metrics.tpl

Similar to the existing `extraRelabelings` option, and can be used in conjunction with it.
See also [Prometheus API docs](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#podmetricsendpoint): 
> MetricRelabelConfigs to apply to samples before ingestion.

enhancement(helm platform): metricRelabelings for Prometheus PodMonitor

---

.github/workflows/nightly.yml
scripts/release-s3.sh

This commit corrects the -debug artifact upload to be to `gnu-debug`. We
previously were overwriting the `gnu` artifact, which will be a rude surprise to
users. This we'll correct by triggering the nightly run manually.
This commit also adds a verify_artifact in the s3 upload for the debug tarball
to break the build if it's missing.
REF #7900 

chore: Correctly upload -debug artifact

---

src/conditions/mod.rs
src/transforms/sample.rs
tests/config.rs

The docs for the `sample` transform were updated to use an example remap
condition but the component itself only accepted `check_fields`-style
conditions. This updates the component to allow either condition style
(similar to the `filter` transform).
I updated the tests to just use the new remap style rather than check
both. I think it's fine to rely on the tests in `src/condition` to cover
the differences between conditions.
Fixes: #7863

fix(sample transform)!: Accept remap conditions

---

Makefile
src/sinks/pulsar.rs

Closes #7915
I found that:
- Initially our test tried to connect before pulsar was ready setting up, 15s seems to always pass locally
- When running against an already running pulsar container, we'd error with: `Field 'read_compacted' is not set`
I resolved this second one by explicitly setting that config on our test consumer, but I'm not sure why this wasn't an issue in the past or a consistent issue in testing...
We do appear to not be setting a specific tag so a change to the version we're testing against could have caused this.

fix(tests): Fix flakey pulsar integration test

---

build.rs
scripts/set-build-description.sh
src/internal_events/process.rs
src/lib.rs

Spun off from https://github.com/timberio/vector/commit/d2ace8eaef15f8a8a6da5c5cbd1b2b67207a8d99#r52260627
Moves where we include how debug information is injected into the binary
to `build.rs` rather than CI. This feels a bit safer in that it will
check even outside of CI and augment the version string accordingly.
A release build of vector looks like:
```
vector 0.15.0 (x86_64-apple-darwin)
```
That is, no debug info. A debug build of vector looks like:
```
vector 0.15.0 (x86_64-apple-darwin debug=full)
```
We currently just have a binary `debug` or nothing, which we could
switch back to here. I'm not really sure how often `debug` is set to `1`
to only include line info and if that is substantially different in
meaning than including full debug info.
Signed-off-by: Jesse Szwedko …

chore(releasing): Move where the `DEBUG` info is sensed during builds

---

lib/vrl/stdlib/src/parse_json.rs

refactor typedef:
- avoid duplication
- limit the kind of object in Array and Object.

chore(remap): define type def object and array inner type

---

docs/reference/components/sources/internal_metrics.cue

Also revise the adaptive concurrency metric descriptions to not be HTTP
specific since the controller could be used for non-HTTP requests in the
future.
I started to actually go through all of the sinks and add these metrics
where appropriate, but this turned into a bigger task than I expected so
I punted on it in-lieu of the upcoming work in #3900 . This change will
at least let users find these metrics.
This came up because a user in discord couldn't find descriptions for
them:
https://discord.com/channels/742820443487993987/746070604192415834/855217775983198228

docs(observability): Add missing HTTP metrics to internal_metrics docs

---

Cargo.lock
Cargo.toml
benches/metrics_bench_util/mod.rs
docs/reference/cli.cue
lib/file-source/src/file_server.rs
lib/file-source/src/fingerprinter.rs
src/app.rs
src/cli.rs
src/sources/internal_logs.rs
src/test_util/mod.rs
src/trace.rs

Closes #7641 
This adds an option for sending tracing spans to a local Datadog agent (with APM enabled, which is not the default, see [docs](https://docs.datadoghq.com/agent/docker/apm/?tab=linux)). There is still some work to do to make the tracing data interesting, but I've added some new spans to the file source that would have come in very handy in previous investigations.
An important thing to note is that these spans respect the current log level, so if you want to see the new tracing spans from the file source you'll need to run with something like `LOG=info,file_source=trace`. This obviously makes the logs noisy as well, so we may want to do some thinking about how to choose levels. If the performance impact is low enough many of these could be bumped to debug or even info.

enhancement(observability): add flag to send tracing spans to Datadog APM

---

Cargo.lock
Cargo.toml
src/sinks/aws_s3.rs

This is required when the bucket has [object
locking](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html)
enabled, but also gives a bit more confidence that the object makes it
to S3 uncorrupted.
Unfortunately the test I added doesn't actually validate that Vector
works with object locked buckets due to [a gap in
localstack](https://github.com/localstack/localstack/issues/4166) but
I did verify it manually be creating a bucket with object locking
enabled, observing the failure, making the implementation change, and
observing the success.
Closes: #7310

enhancement(aws_s3 source): Send content_md5 when writing objects

---

docs/reference/remap/functions/parse_key_value.cue
docs/reference/remap/functions/parse_logfmt.cue
docs/reference/urls.cue
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/parse_key_value.rs
lib/vrl/stdlib/src/parse_logfmt.rs

Add an option to support parsing `foo:bar,foobaar`.
```
parse_key_value!(
"foo:bar,foobaar",
field_delimiter: ",",
key_value_delimiter: ":",
standalone_key: true
)
```
returns
```json
{
foo: "bar",
foobaar: true
}
```

enhancement(vrl): standalone key support for `parse_key_value`

---

.github/workflows/benches.yml
.github/workflows/cargo_flake.yml
.github/workflows/test.yml

If a CI workflow fails, sometimes it won't make it to the step that stops the `sccache` process.  This causes issues on subsequent runs using the same runner, as `sccache` is still running, and `sccache --start-server` exits with a non-zero code if it's already running.... which then kills _that_ run.  No bueno.
We forcefully stop the `sccache` process before attempting to start it.  We still stop it after the run, or try, if we make it there... but this is a stopgap until there's a better/single action that can more cleanly provide the `try { start } finally { stop }` logic.

chore(ci): force stop sccache before attempting to start it

---

src/sources/aws_s3/sqs.rs

This fixes an issue introduced by 1ccb214 where the tracing span the S3 source was created within was not propagated when spawning the ingestor tasks, leading to internal metrics that lacked the necessary labels for proper filtering and for correctly driving `vector top`.

fix(aws_s3 source): labels missing for s3 source metrics

---

docs/reference/remap/functions/encode_key_value.cue
lib/vrl/stdlib/src/encode_key_value.rs
lib/vrl/stdlib/src/encode_logfmt.rs

Allow :
```json
{
"k1": "v1",
"k2": true,
"k3": false
}
```
to be serialised as:
`k1=v1 k2` 
See [here](https://github.com/kr/logfmt/blob/64c009c7f6482dbcd6fb94b6c1f9a7eda47c02d3/decode.go#L1-L20) for this logfmt "extension"

enhancement(vrl): support standalone key encoding in `encode_key_value`

---

lib/vrl/stdlib/src/parse_key_value.rs
lib/vrl/stdlib/src/parse_logfmt.rs

The fix addresses the following situation: when using space as a field
delimiter and `whitespace:lenient` along with `accept_standalone_key:true`
the field following a standalone key was dropped:
Before:
```
$ parse_key_value!("foo=bar foobarbaz bar=baz", key_value_delimiter: "=", field_delimiter: " ", whitespace: "lenient", accept_standalone_key: true)
{ "foo": "bar", "foobarbaz": true }
```
After:
```
$ parse_key_value!("foo=bar foobarbaz bar=baz", key_value_delimiter: "=", field_delimiter: " ", whitespace: "lenient", accept_standalone_key: true)
{ "bar": "baz", "foo": "bar", "foobarbaz": true }
```
In #7907 it was agreed to enable standalone key by default, but `parse_logfmt` was left with the setting deactivated (but the doc was updated) this fixes it.

enhancement(vrl): accept standalone key in `parse_logfmt` + minor related fix

---

docs/reference/components/sources/kubernetes_logs.cue
src/sources/kubernetes_logs/mod.rs

Pending investigation in
https://github.com/timberio/vector/issues/7840
This is just to make sure we don't accidentally release the new default
of 5s before we are confident in it.

chore(kubernetes_logs source): Revert glob minimum cooldown to 60s

---

lib/vector-core/src/event/finalization.rs

This is no longer needed with the update to atomig 0.3

chore(data model): Drop impl AtomInteger from status types

---

src/lib.rs
src/service.rs

This file is only used by `vector_windows.rs` which is flagged for
Windows.
```
cargo 1.54.0-nightly (44456677b 2021-06-12)
```
correctly picked up that there is dead code there when compiling on
non-Windows.
Discovered by @tshepang in https://github.com/timberio/vector/pull/7931
This PR supersedes https://github.com/timberio/vector/pull/7931

chore(dev): Flag src/service.rs as Windows-only

---

src/internal_events/aws_s3.rs
src/sources/aws_s3/sqs.rs

This PR introduces batching to the delete phase of the core S3 source loop.  After reading a batch of messages from SQS, we would process them one-by-one, and then, if enabled, delete them from SQS to mark them as completed.  Instead, we now batch up the message IDs to delete as we retrieve/process the files from S3, and only once a batch of SQS messages has been processed in that way do we delete them from SQS.
In a synthetic benchmark of many small files, such that the time spent reading the files from S3/sending them to the pipeline is small, we can observe a 40-50% increase in throughput to the overall source.

enhancement(aws_s3 source): batch SQS deletes

---

src/docker.rs

This is supported in Tokio again as of 1.7 and bollard as of 0.11.

enhancement(docker_logs source): Re-add named pipe support on Windows

---

lib/k8s-e2e-tests/tests/vector-agent.rs

Reverts timberio/vector#8006
This breaks any test setting config under kubernetesLogsSource because we concat the values files together rather than passing them both in with the `-f` flag

chore(tests): Revert glob faster in checkpoint test

---

src/http.rs

Currently, we create a dedicated `http` span when building an instance of `HttpClient<B>` that gets wrapped around subsequent usages of the client, such as when sending a request.  However, based on where we create this span -- when building `HttpClient<B>` itself -- and how we use it -- instrumenting request futures directly -- we never capture the current span context at the time of when the request is made, which leads to all internal metrics that happen in that request lacking labels.
This PR simply eschews the at-creation-time span and instead generates the `http` span when the request is being constructed.

fix(observability): missing tracing context on HTTP client metrics

---

docs/reference/components/sinks/kafka.cue
src/sinks/kafka.rs

Hi, this PR allows to disable sending kafka message key. The key is optional and vector is now always setting it, even as an empty value. Some kafka consumers excepts that key has the same encoding as the message (https://github.com/confluentinc/confluent-kafka-python/issues/428). Empty key breaks our consumer as we are sending AVRO messages through vector. So there is new option "none" which prevents sending the key to kafka.
Related PR https://github.com/timberio/vector/pull/7859, these two PR allows vector to work with AVRO and other binary protocols, at least from http source through kafka sink.
example config snippet
```
[sinks.out_kafka]
type = "kafka"  
inputs = ["http_in"]  
bootstrap_servers = "192.168.0.67:9092"  
compression = "none"  
key_field = "none"  
topic = "some-topic" …
```

enhancement(kafka sink): disable sending key when no `key_field` configured

---

src/line_agg.rs
src/sources/util/multiline_config.rs

Closes #6486
Closes #6855
Timeouts were never reset or removed so they naturally timed out and broke merging for a random multiline.
It was also causing a memory leak for large `timeout_ms` so it's at least a partial cause of #7525.

fix(processing): Manage timeouts in multiline

---

scripts/skaffold.sh
skaffold.yaml
skaffold/manifests/config.yaml

This modifies `skaffold.sh` to cross-build on OSX to create a Linux
binary (on Linux it will just do straight `cargo build` since it is more
efficient).
Also modifies the Helm config used to drop internal_metrics since that
is predefined.
Closes #8018

chore(dev): Get `./scripts/skaffold.sh` working on OSX

---

src/internal_events/wasm/mod.rs
src/transforms/wasm.rs
src/wasm/mod.rs

Just noticed some suggestions clippy has been giving when running `cargo clippy --all-features`.

chore: Apply suggestions from `cargo clippy --all-features`

---

src/utilization.rs

Closes #7982 
Pretty darn simple, but gets the job done. I opted to leave the existing debug logs for now, but don't feel strongly about it.

enhancement(observability): emit component utilization as a metric

---

lib/k8s-e2e-tests/tests/vector-agent.rs

Hopefully this works now after
https://github.com/timberio/vector/commit/7c648d5498d969ba314f9f9ccc5671b4cd515c37
Closes: #8014

chore(ci): Stop ignoring k8s e2e checkpointing test

---

distribution/systemd/vector.service

Closes #6555
This takes a first pass at hardening the service file we ship with Vector.
Depending on a user's need, they could harden it further by, for example,
disabling network binding if they aren't using a source that requires it or the
file system if they don't need to use a component that needs to read or write
to it.  My aim here was to provide a broad enough set that it should cover any
vector configuration.
Output of `systemd-analyze security vector`:
```
root@72314b979f5b:/# systemd-analyze security vector
NAME                                                        DESCRIPTION                                                                   EXPOSURE
- PrivateNetwork=                                             Service has access to the host's network …
```

enhancement(security): Harden SystemD service

---

distribution/helm/vector-agent/templates/service.yaml
distribution/helm/vector-agent/values.yaml

This PR is adding an option to the vector-agent helm chart to add extra ports to the service resource used for [Topology-aware traffic routing](https://kubernetes.io/docs/concepts/services-networking/service-topology/). So now also the traffic from the sources can be routed based on the topology of the cluster.

enhancement(helm platform): Option to add additional ports to the service in vector-agent helm chart

---

distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml

Signed-off-by: Michal Muransky <michal.muransky@lablabs.io>
Hi there, this PR is extending the `updateStrategy` of vector-agent DaemonSet. If the strategy is set to "RollingUpdate" user has an option to change the value of `maxUnavailable`.

enhancement(helm platform): Add maxUnavailable for updateStrategy in vector-agent helm chart

---

.github/workflows/test.yml

This will allow us to require this for the PR status checks as requiring
the matrix job directly doesn't work as we discovered in https://github.com/timberio/vector/pull/6861#issuecomment-868822823
https://github.community/t/status-check-for-a-matrix-jobs/127354

chore(ci): Add dummy job for cross matrix job

---

lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_apache_log.rs

fix(vrl): apache error parser without thread id

---

docs/reference/remap/functions/ip_aton.cue
docs/reference/remap/functions/ip_ntoa.cue
docs/reference/urls.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/ip_aton.rs
lib/vrl/stdlib/src/ip_ntoa.rs
lib/vrl/stdlib/src/lib.rs

This PR adds two new functions that convert IPv4 addresses to and from
their numbers-and-dots notation and numeric represenattion. These mimic
the C standard library inet_aton and inet_ntoa functions.
Rust's `Ipv4Addr` is directly convertable to/from `u32` via defined
`From` implementations; however these seem to use host-byte order rather
than network-byte order. I chose to maintain the C library behavior of
network-byte order.
We could opt to extend these functions to work with IPv6 addresses but
they'd require an internal integer representation capable of storing an
u128 whereas our current `integer` representation is i64.
Closes #7188

enhancement(vrl): Add ip_aton and ip_ntoa functions

---

distribution/debian/scripts/preinst
distribution/rpm/vector.spec

This refines the `vector` user created by the deb packages to create
with no login shell and with the home directory set to
`/var/lib/vector`. This brings it in-line with the user created by the
rpm package.
I also updated the rpm user creation to use long flags and in the same
order as the deb to make it easier to spot differences.
Closes #7945

enhancement(releasing): Refine Vector user for debian

---

docs/reference/components/sources/internal_metrics.cue

These are not added by Vector. They are added by Prometheus when
scraping an endpoint.

fix(external docs): Remove job and instance tags from internal_metrics

---

Cargo.lock
Cargo.toml

Bundles together a bunch of updates dependabot was making which were
running into issues due to different versions of rusoto being included
when updating individually.

chore(deps): Upgrade rusoto dependencies

---

Cargo.lock
Cargo.toml

Found as part of investigating #7842.
Between an upgrade of the crate and our move to turn off default features on deps, we lost `rdkafka`'s [direct integration](https://github.com/fede1024/rust-rdkafka/blob/b4ec50e72e9b6d0199519092c4db4835315d91ba/src/util.rs#L395-L418) with tokio and began using its [`NaiveRuntime`](https://github.com/fede1024/rust-rdkafka/blob/b4ec50e72e9b6d0199519092c4db4835315d91ba/src/util.rs#L375-L393).
It's not clear how much of a performance impact this actually has for us (my test setup didn't show much, but might be too artificial to do so), but it's definitely something to fix either way.

fix(kafka source): add tokio feature to rdkafka

---

src/dns.rs

I don't see a lot of value in specifically resolving vector.dev and it
is currently causing CI failures due to failed lookups. I was going to
`#[ignore]` it but figured I'd just update it to resolve a domain that
should always be there.

chore(tests): Resolve example.com instead of vector.dev for tests

---

tests/data/dnstap/Dockerfile

Closes #8074 
* Install Debian package `apt-utils` first before installation of any other packages
* Set environmental variable `DEBIAN_FRONTEND` as `noninteractive` to eliminate warnings like `unable to initialize frontend`
Signed-off-by: James Bai <jbai@bluecatnetworks.com>

fix(dnstap source): eliminate warnings while building docker image for dnstap IT

---

docs/reference/components/sources/kubernetes_logs.cue
src/sources/kubernetes_logs/k8s_paths_provider.rs
src/sources/kubernetes_logs/mod.rs

Relates #7934
This updates our `kubernetes_logs` source to watch for log files that have been rotated, ex: `0.log.20210618-133041`.
We exclude the following patterns by default:
- `"**/*.gz"` - See: https://github.com/timberio/vector/issues/7990
- `"**/*.tmp"` - These are related to the compression steps
When combined with a lower `glob_minimum_cooldown_ms` this should help with high throughput logging situations.

chore(kubernetes_logs source): Glob uncompressed rotated log files

---

docs/reference/remap/functions/format_int.cue
docs/reference/remap/functions/parse_int.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/format_int.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/parse_int.rs

For converting integers to/from strings.
We currently have `to_int` which is equivalent to `parse_int(foo, 10)`,
but the added `parse_int` is able to:
* Parse in a specified base
* Determine the base of the number by looking at its prefix (e.g. 0x ->
16)
I added an analogous `format_int` for going the other way.
Closes: https://github.com/timberio/vector/issues/7228

enhancement(vrl): Add `format_int` and `parse_int` functions

---

src/sources/aws_kinesis_firehose/handlers.rs
src/sources/aws_kinesis_firehose/mod.rs
src/sources/aws_s3/mod.rs
src/sources/aws_s3/sqs.rs

Closes  #7710
Enable for individually compressed messages to be empty for sources:
* `aws_kinesis_firehose`
* `aws_s3`
Other sources either don't have sub messages or they can't be individually compressed.

fix(aws service): Allow zero size compressed messages

---

docs/reference/components/sources/file.cue
docs/reference/components/sources/kubernetes_logs.cue
src/sources/kubernetes_logs/mod.rs

Closes #8070
I'm kinda reluctant to expose this for two reasons:
1. It exposes internal implementation.
2. It kinda isn't straightforward because of this sentence:
`If the file has less than this amount of lines then it won't be read at all.` 
Without knowing how the collection of logs from Kubernetes works users can shot them self in the foot by setting that value too high. That's because the logs are broken into several files, so the larger `lines` is the greater the chance is for the last logs of a container to be lost. So the way how collection works needs to be explained in the documentation. 
This should be fine as a quick fix, but considering how the problem of identifying files is difficult, it will probably be permanent. 
---
Ideally, we should only apply `lines` for the start of …

enhancement(kubernetes_logs source): Expose `lines` option

---

lib/vrl/stdlib/src/parse_syslog.rs

closes #7796
fixed by [this PR](https://github.com/StephenWakely/syslog-loose/pull/12)

fix(vrl): ensure parse_syslog handles non structured messages

---

docs/reference/components/transforms/lua.cue

Resolves:
https://github.com/timberio/vector/discussions/8133

docs(lua transform): Add `version` to examples

---

docs/reference/remap/functions/to_int.cue
lib/vrl/stdlib/src/to_int.rs

It seems like we explicitly decided to round, but I agree with the user
that filed #8135 that truncation is a more common behavior for integer
coercion of floats.
Fixes: #8135

fix(vrl): `to_int` truncates floats

---

.github/CODEOWNERS

Reported by user in discord:
https://discord.com/channels/742820443487993987/746070591097798688/861631959016275989

chore(dev): Remove non-existent aws and gcp teams from CODEOWNERS

---

docs/cue/reference/components/sources/kubernetes_logs.cue
docs/layouts/docs/component.html
docs/layouts/partials/data.html

There's currently some jankiness in the "How it works" section of various component docs. Here's a prominent example:
https://vector-dot-dev.netlify.app/docs/reference/configuration/sources/kubernetes_logs/#how-it-works
This PR fixes that directly. Here's the fixed version:
https://deploy-preview-8159--vector-dot-dev.netlify.app/docs/reference/configuration/sources/kubernetes_logs/#how-it-works

fix(template): Fix rendering issue in component "How it works" sections

---

.github/workflows/test.yml
scripts/environment/prepare.sh

Otherwise fails on MacOS in Github Actions with:
```
Traceback (most recent call last):
1: from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
/usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.21/exe/bundle (LoadError)
```
When `bundle install` is run.
I'm not quite sure why, but also this step seems unnecessary.

chore(ci): Avoid updating "bundled with" in CI

---

docs/cue/reference/components/sinks/loki.cue

This PR fixes an indentation issue causing the description for the `labels` config to appear as monospace text:
The broken version:
https://vector-dot-dev.netlify.app/docs/reference/configuration/sinks/loki/#labels
The fixed version:
https://deploy-preview-8180--vector-dot-dev.netlify.app/docs/reference/configuration/sinks/loki/#labels

fix(loki sink): Fix indentation issue in Loki sink docs

---

src/sources/journald.rs

The `instrument()` call here was replacing the component span. I think we could
have made a nested span instead, and preserved the labels, but I don't
see a reason to have this span here since the component already has its
own span.
Fixes #8162 

fix(journald source): Fix event metrics reporting

---

deny.toml

We don't seem to be affected since it only affects converting
`prost_types::Timestamp` to `SystemTime`.
Issue to resolve once dependencies are updated:
https://github.com/timberio/vector/issues/8184

chore(deps): Temporarily ignore prost warning

---

netlify.toml

This PR comments out the recently added build ignore script for Netlify, as that script appears to have been canceling builds that we don't want canceled (hashtag cancel culture!). I'm going to talk to their support and see if there's a way around this. At that point we can uncomment.

fix(external docs): Remove Netlify ignore logic (for now)

---

Cargo.lock
lib/vector-core/src/event/util/log/path_iter.rs
src/sources/aws_s3/sqs.rs

This PR does some minor tweaks to improve the performance of the S3 source, as well as some more generic tweaks.
We're approaching the performance shortcomings by focusing on the per-event overhead: a single S3 file itself may have hundreds of thousands of lines, or more, each of which could be turned into an event.  The overhead of creating that event can add up very quickly.
The biggest change here is switching from `LogEvent::insert` to `LogEvent::insert_flat` in the S3 source, which avoids a codepath that tries to parse the key as a JSONPath-esque value when it is otherwise not necessary.
At a higher level, for all the cases where we've yet to identify that `insert_flat` can be substituted in, we've updated `PathIter` to better utilize the pre-compiled regular expression it employs. …

enhancement(aws_s3 source): improve performance of S3 source

---

docs/content/en/_index.md

This PR fixes a small but jarring typo on the main page and also changes the wording in a few other sentences.

fix(external docs): Fix typos on main page plus some small wording changes

---

lib/vrl/stdlib/src/parse_key_value.rs

* Escaping ( closes #7839 ) problem, e.g.:
```
$ parse_key_value!(s'user="DOMAIN\account space" ip="1.2.3.4 space"', whitespace:"strict")
{ "space" ip": "1.2.3.4 space", "user": "\"DOMAIN\\account" }
```
* Quoted standalone key value that include the field separator, e.g.:
```
$ parse_key_value!(s'"foo==b" bar=baz', whitespace:"strict")
{ ""foo": "=b\"", "bar": "baz" }
```
All older tests are passing unmodified, but I'll probably add more to better cover corner cases.
Will create an issue about escaping because this:
```
$ parse_key_value!(s'foo="\"bar\""', whitespace:"strict")
{ "foo": "\\\"bar\\\"" }
```
should not happen, we should get (to be symmetric W.R.T `encode_key_value`):
```
{ "foo": "\"bar\"" }
```

enhancement(vrl): `parse_key_value` fixes

---

Cargo.lock
lib/file-source/Cargo.toml
lib/file-source/src/checkpointer.rs
lib/file-source/src/file_server.rs
lib/file-source/src/fingerprinter.rs

Adds logic to convert from checkpoints written by Vector before version 0.14.0 to 0.14.0 checkpoints by seeing if any checkpoints, that don't match an existing file, match if the old checkpoint strategy is used.
Also adds alias for `first_line_checksum` strategy which would have broken checkpoints if released.
Ideally I'd like to include this in 0.15.0 to avoid needing to release a 0.15.1 with it.
This will be released as a 0.13.1.
Fixes: #8182
TODO:

fix(file source): Handle legacy fingerprint checksums from < v0.14.0

---

distribution/install.sh

This PR updates the text output of the EZ install script, which tells you to look for the placeholder Vector config in $HOME/.vector/vector.toml, while the location is actually $HOME/.vector/config/vector.toml.

fix(setup): Fix config dir in install script output

---

docs/layouts/_default/baseof.html

I think since it's been several months and we have "By Datadog" in the
logo now the banner is no longer needed.
I left the partial there so it is easy to bring back with a new announcement if we need to.

docs: Remove the banner

---

distribution/helm/vector-agent/templates/configmap.yaml
distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/_helpers.tpl
distribution/helm/vector-aggregator/templates/configmap.yaml
distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/helm/vector-aggregator/values.yaml
distribution/helm/vector-shared/templates/_metrics.tpl
distribution/helm/vector-shared/templates/_vector_config.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
docs/content/en/highlights/2021-07-13-helm-customConfig.md
lib/k8s-e2e-tests/tests/vector-agent.rs
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

Rendered: https://deploy-preview-8168--vector-dot-dev.netlify.app/highlights/2021-07-13-helm-customconfig/
Related #7709
Close #7453
This PR introduces the `customConfig` key to rework how we configure Vector with Helm. It completes the first two steps from [the RFC's Plan of Attack](https://github.com/timberio/vector/blob/master/rfcs/2021-06-29-7709-helm-update-vector-config-pattern.md#plan-of-attack):
- Announce plan to deprecate current keys with a highlight in the 0.15.0 release, and mark the values as deprecated in the values.yaml
- If any deprecated key is used or set as enabled, block usage of new configuration and customConfig pattern
This also moves the `podMonitor` key out from under the now deprecated `prometheusSink` key to a separate top level key. I've additionally removed …

enhancement(helm platform): Introduce customConfig key

---

src/sources/aws_kinesis_firehose/mod.rs
src/sources/splunk_hec.rs
src/sources/util/http.rs

This ensures requests are correctly tagged with their span labels.
The `http` source was already correctly labeling, but I refactored it to
use the same mechanism for attaching the spans to the requests for
consistency.
Fixes: #8257
Ref: #7970

fix(observability): Fix span labels for http-based sources

---

docs/content/en/highlights/2021-07-13-helm-customConfig.md

@binarylogic pointed out that I didn't update the "using" section of the highlight after our decision to make the options mutually exclusive and preferring `customConfig` over the deprecated keys.

chore: Fix the using `customConfig` section

---

docs/Brewfile.netlify

Just a bit of housekeeping. Netlify has been issuing a warning re: the vector.dev Brewfile (`docs/Brewfile.netlify`). The issue is basically that you're not supposed to run `brew` on taps without running `tap` first. I figured we might as well address that, as that warning will probably become a build-breaking error at some point.

fix(ci): Remove Netlify warning about Brewfile

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-core/buffers/Cargo.toml

This commit upgrades the metrics libraries to their most recent
releases. Performance has improved considerably upstream, as demonstrated in
issue #8263.

chore: Upgrade metrics to latest releases

---

docs/layouts/highlights/single.html

Some recent templating changes caused pages under /highlights to have a doubled title header. This PR removes that.

fix(external docs): Remove redundant title header in highlights

---

docs/cue/reference/components/sources/datadog_logs.cue
docs/cue/reference/urls.cue

Minor doc update to highlight datadog agent config settings that should be updated to divert logs to a local Vector deployment.
Link to DataDog/documentation#10790, so this PR should be kept un-merged until DataDog/documentation#10790 has been merged.

docs: add Datadog agent config info in source/datadog_logs.cue

---

docs/layouts/docs/component.html

This PR addresses a scrolling that appears only on component pages (i.e. /docs/reference/configuration/{sources,transforms,sinks}/*).

fix(css website): Fix overflow scroll behavior on component pages

---

src/sources/dnstap/mod.rs
tests/data/dnstap/configure_bind.sh
tests/data/dnstap/named.conf.options.template

Signed-off-by: Yunkun Zhu <yzhu@bluecatnetworks.com>
Closes #8240.
This changeset is to fix dnstap source flaky IT. It includes the following:
* change the timeout value for receiving second event to `1s`
* make sure start BIND after Vector gets started
* avoid sending extra queries
* remove `rndc reconfig`
* set `multithreaded` option to `false`
* add `println!` for error cases

fix(dnstap source): Increase timeout for receiving events

---

.github/CODEOWNERS

This PR updates the CODEOWNERS file to cover everything in the `docs` directory. Previously only the `cue` subdirectory was covered, but this adds all of the other website inputs.

enhancement(ci): Update CODEOWNERS to cover vector.dev inputs

---

docs/content/en/docs/setup/installation/manual/from-archives.md
docs/content/en/docs/setup/installation/manual/from-source.md
docs/content/en/guides/getting-started/getting-started.md

There were some edits to the content files in the old `docs/` tree, but
these edits were never reflected in the live site as the content files
from the old website repo were the ones being used. The new site took
the old website repo content files as a start, I believe, as these were
the ones actually being used.
This PR migrates over some changes to the content files that were made
on the old `docs/` subtree.
Closes: #7920
Closes: #8191

docs: Add missing changes from the old docs/ directory

---

.github/semantic.yml
docs/content/en/guides/getting-started/getting-started.md

Given the Netlify build failures for most of today, I merged some PRs without ensuring that they pass CI. A few broken links managed to sneak in that way. This PR corrects that and adds a new Semantic PR category for link fixes.

fix(external docs): Fix broken links in getting started guide

---

docs/content/en/docs/reference/configuration/transforms/route.md

Due to a typo, the route transform doc was excluded from the public-facing docs. This PR fixes that error.

fix(external docs): Reinstate route transform doc

---

lib/k8s-e2e-tests/tests/vector-agent.rs

chore: Remove sleep from simple_checkpoint

---

docs/cue/reference/components/sources/file.cue
lib/file-source/src/checkpointer.rs
lib/file-source/src/fingerprinter.rs

Closes #7948
This PR addresses two of three improvements that can be done regarding performance impact of opening/closing files in file source. 
* Checkpoints are now only written if the state has changed.
* Document performance consideration for `glob_minimum_cooldown_ms`.
While the last improvement, the impact of globing, is being tackled in #7840.

chore(file source): Write checkpoints only if they changed

---

distribution/systemd/hardened-vector.service
distribution/systemd/vector.service

This replaces the previous vector.service file since a user reported
that the new file does not work on CentOS 7.
I think we'll want to do broader testing before making this the default.
For now, just include as an optional reference.
Closes: #8336

fix(releasing): Replace SystemD service file with previous

---

docs/content/en/highlights/2021-07-16-remap-multiple.md

Missed this when writing the other highlights

docs: Add 0.15.0 highlight for emitting multiple events from remap

---

src/sources/dnstap/mod.rs
tests/data/dnstap/configure_bind.sh
tests/data/dnstap/named.conf.options.template

Signed-off-by: Yunkun Zhu <yzhu@bluecatnetworks.com>
This enhancement is based on the comment https://github.com/timberio/vector/pull/8302#issuecomment-880894919. It makes sure to do proper cleanup in the end of each IT test case and let IT test cases not dependent on the container.

enhancement(dnstap source): Make sure ITs are independent of container

---

docs/layouts/releases/single.html

I think these are more important for users to see than what's coming
next for a given release.

docs: Move highlights up on release page

---

src/sinks/util/adaptive_concurrency/tests.rs

This was part of my work on the ARC testing for #8325 but I decided to break it out for separate review.

chore(sinks): Rework the ARC test harness to avoid the polling loop

---

docs/content/en/highlights/2021-07-16-rename-datadog-logs-source.md
docs/cue/reference/components/sources/datadog_logs.cue
docs/cue/reference/examples.cue
docs/cue/reference/services/datadog_agent.cue
docs/cue/reference/urls.cue
lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
src/sources/datadog/agent.rs
src/sources/datadog/mod.rs

We've decided to make this source specific to the agent as-per
https://github.com/timberio/vector/pull/8297#discussion_r670788059

chore(datadog service)!: Rename `datadog_logs` source to `datadog_agent`

---

Cargo.lock
Cargo.toml
lib/vector-core/Cargo.toml

Updates to `metrics-tracing-context@v0.8.0` which contains significant performance improvements, specifically with components that emit metrics on a per-event basis.

chore: update to latest version of metrics-tracing-context

---

src/sources/datadog/agent.rs
src/sources/util/body_decoding.rs
src/sources/util/mod.rs

This commit adjusts the way the datadog agent log payloads are parsed, avoiding
the generic `decode_body` and relying on our knowledge of the payload's
structure to avoid the branch misses etc etc inherent in that function. We gain
20Mb/s of parse speed per investigation done in #8263. This commit passes
tests (locally) but I don't have documentation on hand to assert that this
payload is, in fact, what the datadog agent is meant to send.
Resolves #8286

chore: Parse Datadog Log agent payloads faster

---

lib/vector-core/src/event/value.rs
src/sources/internal_metrics.rs

I realized today that `host` may not be enough to differentiate two vectors running on the same host so I added the process id too.

enhancement(internal_metrics source): Add pid as tag

---

docs/.gitignore
docs/algolia.json
docs/assets/js/search.tsx
docs/layouts/partials/meta.html
docs/scripts/algolia-index.ts

This PR updates the search indexing logic for the new vector.dev to include per-page tags. It also performs some basic input sanitation by ensuring that there's no extraneous whitespace in section titles. Including tags should improve the search sensitivity and give us more per-page levers that we can use to influence result sets.
Please note that this renames what was previously the `tags` field to `hierarchy` to make room for what I feel is a more intuitively named `tags` field.

enhancement(search website): Add page tags to search index

---

docs/cue/reference/components/sources/internal_metrics.cue

docs: Document internal_metrics tags

---

docs/layouts/highlights/li.html
docs/tailwind.config.js

This PR adds a highlight color scheme for, well, highlights 😄 The scheme in this PR is totally provisional and I'm open to suggestion on which highlight types correspond to which colors.
You can see the scheme on display here:
https://deploy-preview-8394--vector-project.netlify.app/highlights/

enhancement(external docs): Add color scheme for highlights

---

src/pipeline.rs

Instead of incrementing `events_out_total` -- via `emit!(EventOut { .. })` -- every time we get an event in `Pipeline`, we instead batch the updates and flush them out in `Pipeline::try_flush`.  For high events/second configurations, this can provide a significant reduction in metric emissions overall.

enhancement: batch events out metric in Pipeline

---

lib/vector-core/src/byte_size_of.rs
lib/vector-core/src/event/finalization.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/metric.rs
lib/vector-core/src/event/mod.rs
lib/vector-core/src/event/test/common.rs
lib/vector-core/src/event/test/mod.rs
lib/vector-core/src/event/test/serialization.rs
lib/vector-core/src/event/test/size_of.rs
lib/vector-core/src/event/value.rs
lib/vector-core/src/lib.rs

This commit introduces the `ByteSizeOf` trait into vector-core and implements
this for the `Event` type, focused specifically on the `LogEvent` side of that
structure in testing. This allows us to determine how big `Event` is in memory
without necessarily serializing it. The current implementation for `Event`
trawls through any collections to get the size of the structure but there's no
reason if we need constant time access why this can't be a continually
maintained value.
This has bearing on issue #8263, both in the recognition that the blackhole sink
is slow because of serialization to get byte size and in a similar constraint on
the datadog logs sink for similar reasons. 
Resolves #8272

chore: Teach `Event` what its size is

---

docs/content/en/docs/reference/configuration/template-syntax.md

chore: Replace `lua` example with `remap`

---

docs/assets/sass/toc.sass

This removes an extra scrollbar caused by a superfluous `overflow-y: scroll` setting (already covered by the containing div).

fix(css website): Remove extra scrollbar

---

docs/scripts/algolia-index.ts

PR #8261 introduced an issue with the `tags` and `hierarchy` fields (namely mixing them up in a few places). This PR addresses that.

fix(search website): Fix misnamed fields in Algolia indexing script

---

src/sinks/blackhole.rs

This commit adjusts the blackhole sink in two important ways. First, it
processes incoming events in a chunk using the `StreamExt::chunk` method,
reducing per-event overhead in this sink to 128th of previous, considering the
chunk size. This does imply that blackhole sink will not remove an event from
the stream until there are 127 of its compatriots waiting, but that seems
acceptable for what blackhole sink is. Second, the sink now uses ByteSizeOf
trait methods to calculate the size of the Event chunk, removing json
serialization cost discussed in #4705.
Blackhole sink is now as fast as it's severely mangled form discussed in #8263.

chore: Adjust blackhole sink to use ByteSizeOf trait

---

lib/vector-core/src/event/test/size_of.rs

This commit avoids double (or more) counting the keys that we insert into the
`LogEvent`. Previously we would always add the key size to the expected size of
the `LogEvent` even if the key already existed in the `LogEvent`.
Resolves #8413

chore: Avoid double-counting keys in `log_operation_maintains_size`

---

src/sources/file.rs

This commit marks two tests in the file-source as ignore. Both deal with
restarts. We've fiddled with this mechanism quite a bit lately. My argument is
that file-source needs a fundamental rethink -- I did the basic work in
[cernan](https://github.com/postmates/cernan) before `Future` existed -- and
tinkering with restart isn't working.
The test appears to be flakey only on Mac and Windows, our slowest CI machines,
which drives out CI turn-around time. Consider that #8421 has failed CI in two
runs because of one or other of these tests.

chore: Ignore flakey file-source tests

---

src/sinks/datadog/logs.rs

This commit adjusts the datadog logs sink defaults to the maximum payload byte
size, 5Mb, and total array events, 1000. See
https://docs.datadoghq.com/api/latest/logs/#send-logs I have also adjusted the
gzip compression ratio to `GZIP_FAST`, with consideration that in
https://github.com/timberio/vector/issues/8263#issuecomment-885152529 we found
vector spent 30% of its time in compression activity.
This does not appreciably change throughput but does address conversation around
adjusting sink defaults as a way of improving throughput.

chore: Adjust datadog logs sink defaults

---

src/sources/datadog/agent.rs

https://github.com/DataDog/datadog-agent/blob/a33248c2bc125920a9577af1e16f12298875a4ad/pkg/logs/processor/json.go#L24-L32

fix(datadog_agent source): Fix field naming for agent payloads

---

docs/content/en/highlights/2021-07-21-0-16-upgrade-guide.md
docs/cue/reference/components/sinks/datadog_logs.cue
src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/tests.rs

There are two acceptable encodings for datadog logs ingest: JSON and 'text'. The
text encoding is the more limited of the two and does not make sense for end
users to have as a configuration option, considering that JSON ingest is the
more accepted format for ingest.
This commit strikes the 'encoding' option from the sink entirely. This does
simplify the internal logic of the sink -- good -- but removes other features
inherent in the encoding configuration like field exclusion which may or may not
be a problem.
I have not updated the documentation yet but intend to with @spencergilbert's help.
REF #8263

chore(datadog_logs sink)!: Strike text encoding from Datadog logs sink

---

.github/workflows/nightly.yml
.github/workflows/release.yml
distribution/rpm/vector.spec
scripts/verify-install.sh

This happens now automatically as part of useradd as per https://github.com/timberio/vector/pull/8064
Also updates release scripts to have additional verification as `rpm -i`
doesn't exit non-zero whenever parts of the install script fail.
Fixes: #8361

fix(releasing): Remove creation of vector group from rpm

---

docs/cue/reference/components/sources/internal_logs.cue
src/sources/internal_logs.rs

Also allows for disabling via setting the key to `""`.
I'm still not crazy about these keys, but we don't have a better way to
handle it yet.
Partially addresses https://github.com/timberio/vector/issues/8407

enhancement(internal_logs source): Allow host_key and pid_key to be configured

---

src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/service.rs

This commit breaks the internal DatadogLogsJsonService up into a builder and a
renamed Service, migrating request building out of the config struct and into
the sole service, now that #8445 is landed. This does not change the user facing
view of the logs sink and does not appreciably move the needle on throughput but
it does stage future work.
Motivated by work in #8263

chore: Break service up into builder/service pattern

---

REVIEWING.md

Just a little housekeeping thing in light of #8372

fix(ci): Remove reference to CODEOWNERS file in REVIEWING.md

---

docs/assets/js/search.tsx
docs/scripts/algolia-index.ts

Current vector.dev:
With this PR:
I originally tried to fix this via the indexing script (which we still *could* do) but instead I opted to alter the view layer, which I think is more "correct."

fix(search website): Display title in all search result hierarchies

---

rfcs/_YYYY-MM-DD-issue#-title.md

I've found that we're not addressing cross cutting concerns in our RFC. This is important since they can heavily affect our implementation. For example, the "resource" abstraction proposed in the [CSV enrichment RFC](https://github.com/timberio/vector/pull/8400) is largely supported by the need for admin to provision resources and provide them to the new pipelines concepts being proposed in the [Pipelines RFC](https://github.com/timberio/vector/pull/8378).

chore: Add scope section to RFC template

---

docs/cue/reference/components.cue
docs/cue/reference/components/sinks/new_relic_logs.cue
src/sinks/datadog/logs/config.rs
src/sinks/new_relic_logs.rs
src/sinks/util/service.rs
src/sinks/util/service/concurrency.rs
src/sinks/util/service/map.rs

This commit adjusts our default tower limits to be wide open, effectively with
no rate limit. It is important for endpoints that dictate rate limits that we
have some mechanism in place for this but, overall, most endpoints do not set
explicit limits so why should we throttle ourselves?
Follow-up work will trawl through each sink and adjust where
higher-than-previous defaults have been set but are still quite low.
REF #8470

chore: Adjust default rate-limits to be wide-open

---

src/types.rs

While working on #8472 I noticed that we could slim the referenced file
down. The default config paths are no longer used and the wildcard import from
`shared::conversion` was overly broad considering our use of the types from that
sub-crate.

chore: Slim down `src/types.rs`

---

src/sinks/aws_cloudwatch_logs/mod.rs
src/sinks/aws_cloudwatch_metrics.rs
src/sinks/aws_kinesis_firehose.rs
src/sinks/aws_kinesis_streams.rs
src/sinks/aws_s3.rs
src/sinks/aws_sqs.rs
src/sinks/azure_blob.rs
src/sinks/azure_monitor_logs.rs
src/sinks/clickhouse.rs
src/sinks/datadog/metrics.rs
src/sinks/elasticsearch/mod.rs
src/sinks/gcp/cloud_storage.rs
src/sinks/gcp/pubsub.rs
src/sinks/gcp/stackdriver_logs.rs
src/sinks/gcp/stackdriver_metrics.rs
src/sinks/http.rs
src/sinks/influxdb/logs.rs
src/sinks/influxdb/metrics.rs
src/sinks/prometheus/remote_write.rs
src/sinks/redis.rs
src/sinks/sematext/metrics.rs
src/sinks/splunk_hec.rs
src/sinks/vector/v2.rs

This is a follow up from PR #8471. In this commit I've removed any default or
near-default TowerRequestConfig instances from `lazy_static` contexts and
shuffled them into their call-site. I have not changed any of the default
overrides.
The largest change here is the removal of `lazy_static` sites. This macro, while
convenient, introduces serialization into vector -- atomic read which is acq/rel
on x86 -- and I'd like it to be rare in the codebase.
For sinks that set an explicit rate limit I have mostly left these intact,
unless I knew better. That is, some sinks set a rate limit because that is a
documented limit and others set it to be higher than the previous default. If
there was no documentation suggesting that the rate limit was arbitrary I
assumed it was intentionally set and left …

chore: Rate limit defaults reconsidered

---

src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/tests.rs

This collection of commits tweaks a number of small things in the Datadog sink. I have added documentation describing the goals of the tests, avoid going through path iteration code if the log schema fields are identically named and expand the writing space for the encoder. 
I had imagined building off this work to introduce more direct serialization -- see https://github.com/timberio/vector/tree/blt-estimate_json_size for a hint of what I was thinking -- but with this commit vector on my machine clocks in at 230Mb/s in the setup described [here](https://github.com/timberio/vector/issues/8263). I'm satisfied that it's time to move on. 
Resolves #8263

chore: Small tweaks around the Datadog sink 

---

docs/cue/reference/components/sources/exec.cue
docs/cue/reference/components/sources/file.cue
docs/cue/reference/components/sources/fluent.cue
docs/cue/reference/components/sources/journald.cue
docs/cue/reference/components/sources/kubernetes_logs.cue
docs/cue/reference/components/sources/stdin.cue
docs/cue/reference/components/sources/syslog.cue
docs/cue/reference/remap/functions/assert.cue

The Hugo templates expect raw strings rather than Markdown for these fields. This PR updates the CUE sources to reflect that. I also snuck a `cue fmt` into this.

fix(external docs): Convert Markdown examples into raw text

---

netlify.toml

A new updated public roadmap for https://roadmap.vector.dev

chore: Update public roadmap URL

---

docs/cue/reference/components/sources/file.cue
docs/layouts/partials/data.html

Fixes #8508
In general, the structured data templates could use some touching up, but this provides a decent-enough view layer for now.
Here's an example:
https://deploy-preview-8514--vector-project.netlify.app/docs/reference/configuration/sources/file/#output-logs

fix(template website): Fix log output template

---

rfcs/2021-07-23-8447-extract-helm-charts.md

chore: RFC for extracing Helm charts to a separate repo

---

CHANGELOG.md
CONTRIBUTING.md
docs/README.md

To lay the foundation for upcoming policy changes I've cleaned up the `CONTRIBUTING.md` file to add a new "User experience" section. This adjusts the wording and moves the "Documentation" and "Changelog" section within it.

chore: Updating CONTRIBUTING.md with user experience section

---

src/service.rs
src/vector_windows.rs

On Windows, to restart the service, vector is first going to stop the service and wait for its state to become `Stopped` before starting it back.
The stop timeout delay is currently hardcoded to 10 seconds. However, the service might take longer to stop, making the restart fail (which might cause trouble with automated tools like `ansible`).
This PR introduces a new `--stop-timeout`  command-line argument  with a default  value of 60 seconds (instead of 10 before) to let the user control the timeout.

enhancement(windows platform): add `--stop-timeout` command-line argument for restart service sub-command

---

distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/helm/vector-aggregator/values.yaml

Similar to the existing `env` value.
This allows for example to configure the vector loglevel, as this is currently only possible via cli arg, as far as i can tell.

enhancement(helm platform): extra args for vector container

---

docs/layouts/docs/component.html
docs/layouts/partials/docs/component-alias.html

Some more housekeeping. I could swear that component descriptions were included in the docs, but a Git mishap may have prevented that from going live.

enhancement(external docs): Add component description to component template

---

lib/vector-core/buffers/src/disk/leveldb_buffer/reader.rs

Works around https://github.com/skade/leveldb/issues/43
Fixes: https://github.com/timberio/vector/issues/8532

fix(buffers): Actually read 100 events at a time

---

docs/layouts/docs/component.html

In #8416 I forgot that the component docs are a separate template and thus didn't apply the wider layout to the source/sink/transform docs. This PR fixes that.

fix(template website): Apply wider layout to component pages

---

docs/assets/sass/toc.sass
docs/assets/sass/variables.sass

In the current site, the TOC is a little crammed, above all because I was struggling to appropriately target nested levels within the TOC class hierarchy. This PR addresses that by adding a top margin only to the top-level items (i.e. the `h2` elements on the page).
Current:
Proposed:

fix(css website): Add spacing for top-level TOC elements

---

lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_apache_log.rs

Currently it could only handle ipv4 and when an ipv6 address comes it
runs into an "failed parsing port" error.
To fix the problem we there just needs to look until the Colon for the port part and look for as many or none Colon so that ipv4 and ipv6 can be handled.

fix(processing): Fix handling ipv6 support for apache error regex client part

---

docs/content/en/docs/setup/installation/package-managers/msi.md

For reasons that are opaque to me, the `{{< version >}}` shortcode invocation isn't working inside this code block, while the alternative syntax (`{{% version %}}`) seems to work fine.
Fixes #8575
PS: ignore the Netlify build errors here. I'm in touch with their support about this.

fix(external docs): Fix MSI installation link

---

lib/shared/src/datetime.rs
lib/vrl/compiler/Cargo.toml
lib/vrl/compiler/src/expression/function_call.rs

This commit removes a `span!` call with `Level::ERROR` setting from
`FunctionCall::resolve`. My understanding here is that this span did not
terminate into any collector and will not impact user observable remap
behavior. This does, however, add +9Mb/s throughput to the configuration
described in #8512.

chore: Remove tracing error span in hot path

---

docs/layouts/docs/component.html

This was an oversight on my part. This PR brings the width of the main text column on component pages in line with the rest of the docs.

fix(template website): Widen main text content on component pages

---

docs/cue/reference/components.cue
docs/cue/reference/components/sinks/aws_cloudwatch_metrics.cue
docs/cue/reference/components/sinks/gcp_cloud_storage.cue
docs/cue/reference/components/sinks/gcp_pubsub.cue
docs/cue/reference/components/sinks/gcp_stackdriver_logs.cue
docs/cue/reference/components/sinks/gcp_stackdriver_metrics.cue
docs/layouts/partials/data.html

`write` isn't super clear and also not correct when talking about
sources. I chose to use `operation` which I think more closely matches
the distinction `required_for` is trying to make between healthchecks
and normal component operation.

docs: Make docs clearer around when IAM permissions are required

---

docs/cue/reference/components/sources/prometheus_remote_write.cue

docs: Remove unpublished metrics from `prometheus_remote_write` source

---

src/sources/fluent.rs
src/sources/fluent/message.rs

The fluent protocol suggests that all map instances are String -> object. This,
I believe, allows us to consider map keys as entirely stringy. This resolves an
initial bottleneck in the source, per investigation in #8610.
This change is worth +123 Mb/s when sinking directly into a blackhole. This 
change is worth +59 Mb/s when going through the full configuration outlined 
in #8610 into `http_blackhole`. 

chore(fluent source): Treat only with stringy map keys

---

lib/vrl/compiler/Cargo.toml
lib/vrl/compiler/src/expression.rs
lib/vrl/compiler/src/expression/function_call.rs
lib/vrl/compiler/src/expression/query.rs
lib/vrl/compiler/src/type_def.rs
lib/vrl/stdlib/src/del.rs
lib/vrl/tests/tests/issues/8068_del_type_def.vrl

Closes #8068 
This ensures the type def for any paths are removed after they are removed using `del`.
To enable this fix I have had to add a new function, `update_state` to the `Expression` trait. This gives an expressions the option to mutate the state during the compilation stage. Note, I am only invoking this function whilst compiling a function call. For any other expressions, even if they implement this function it will currently have no effect. Technically, this may not be completely correct, but in the interests of not doing work when it isn't really necessary I have not pursued it further.

fix(vrl): update type_def after del

---

docs/content/en/highlights/2021-07-21-0-16-upgrade-guide.md
docs/cue/reference/components/sources/internal_metrics.cue
docs/cue/reference/components/transforms/lua.cue
src/internal_events/lua.rs

A [user in
discord](https://discord.com/channels/742820443487993987/746070591097798688/873110527612702741)
was confused about this metric. We document it as the memory used by
Vector, which is not accurate, as the only component that publishes this
metric is the `lua` transform.
To make this more clear and to avoid a collision with the inevitiable
`memory_used_bytes` that Vector will _actually_ publish indicating its
own memory use, I renamed it to `lua_memory_used_bytes`.

fix(lua transform): Adjust memory use metric to be more clear

---

docs/layouts/partials/data.html
docs/layouts/partials/heading.html

Fixes #8656
This PR adds links to the following for each VRL function:
* The "Function spec" section
* The "Examples" section
* Each example in the examples section
I've opted not to include any of the above in the generated TOC on the right side, as the TOC gets very busy when you include these things. But I could be persuaded otherwise.
The relevant page:
https://deploy-preview-8697--vector-project.netlify.app/docs/reference/vrl/functions
Example link:
https://deploy-preview-8697--vector-project.netlify.app/docs/reference/vrl/functions/#to_int-examples-coerce-to-an-int-timestamp

enhancement(external docs): Provide links to VRL examples

---

docs/layouts/partials/data.html

Analogous to #8697 but for VRL error examples.
Relevant page:
https://deploy-preview-8698--vector-project.netlify.app/docs/reference/vrl/errors
Example link:
https://deploy-preview-8698--vector-project.netlify.app/docs/reference/vrl/errors/#error-102-example-non-boolean-if-expression-predicate-strings

enhancement(external docs): Provide links to VRL error examples

---

src/sinks/aws_kinesis_firehose.rs
src/sinks/aws_kinesis_streams.rs
src/sinks/http.rs
src/sinks/splunk_hec.rs
website/cue/reference/components.cue
website/cue/reference/components/sinks/aws_cloudwatch_logs.cue
website/cue/reference/components/sinks/aws_kinesis_firehose.cue
website/cue/reference/components/sinks/aws_kinesis_streams.cue
website/cue/reference/components/sinks/aws_s3.cue
website/cue/reference/components/sinks/clickhouse.cue
website/cue/reference/components/sinks/datadog_events.cue
website/cue/reference/components/sinks/elasticsearch.cue
website/cue/reference/components/sinks/gcp_cloud_storage.cue
website/cue/reference/components/sinks/gcp_pubsub.cue
website/cue/reference/components/sinks/gcp_stackdriver_logs.cue
website/cue/reference/components/sinks/gcp_stackdriver_metrics.cue
website/cue/reference/components/sinks/honeycomb.cue
website/cue/reference/components/sinks/http.cue
website/cue/reference/components/sinks/influxdb_logs.cue
website/cue/reference/components/sinks/influxdb_metrics.cue
website/cue/reference/components/sinks/logdna.cue
website/cue/reference/components/sinks/loki.cue
website/cue/reference/components/sinks/new_relic_logs.cue
website/cue/reference/components/sinks/redis.cue
website/cue/reference/components/sinks/sematext_logs.cue
website/cue/reference/components/sinks/splunk_hec.cue

This commit makes a pass on our documention to correct bugs with regard to the
new concurrency and rate limit values introduced in #8471. I have not added
documentation for `retry_attempts` or adjusted any low limits found, see #8687.
This resolves #8661

chore: Update documentation for new concurrency, rate limit values

---

src/sinks/loki.rs

Closes #6463
Going through https://github.com/grafana/loki, loki returns one of:
* 500 Internal Server Error https://github.com/grafana/loki/blob/cd79adc8ab0c80c55a0f39b43322839c6ffb05d8/clients/pkg/promtail/server/server.go#L222
* 503 Service Unavailable https://github.com/grafana/loki/blob/cd79adc8ab0c80c55a0f39b43322839c6ffb05d8/pkg/loki/loki.go#L349
* 200 OK
So it should be ok to assume that on 404 we are dealing with Grafana Cloud, so instead we just check if its top level query is reacheable/OK.
We could also check if the provided endpoint ends with `grafana.net`, but that seems a bit fragile.

fix(loki sink): On `404` query top level for healthcheck

---

src/internal_events/topology.rs
src/topology/builder.rs

In https://github.com/timberio/vector/issues/8713 we observed that the
`file` source only publishes `events_in_total` with the `file` tag:
```
vector_events_in_total{component_kind="source",component_name="file",component_type="file",file="/tmp/logs/9.log",host="COMP-C02DV25MML87"} 10 1628878196694
```
But this initial publish of `events_in_total` at the topology level with
0 was also causing it to look like the `file` source was emitting no
events:
```
vector_events_in_total{component_kind="source",component_name="file",component_type="file",host="COMP-C02DV25MML87"} 0 1628878196694
```
For all of our other internal events we only publish a value when the
first event for that metric is triggered so I don't see why we shouldn't
do the same here.
I verified that `vector top` reports the …

fix(observability): Do not emit `events_in_total` with 0

---

website/content/en/highlights/2021-08-24-helm-vector-dev.md

chore: Add highlight for new helm.vector.dev repo

---

Cargo.lock
Cargo.toml
lib/prometheus-parser/Cargo.toml
lib/vector-core/Cargo.toml
src/internal_events/tcp.rs
src/sinks/vector/v2.rs
src/sources/vector/v2.rs
src/tls/incoming.rs
tests/data/wasm/protobuf/Cargo.toml
website/content/en/highlights/2021-07-21-0-16-upgrade-guide.md
website/cue/reference/components/sinks/vector.cue
website/cue/reference/components/sources/vector.cue

This PR makes a few changes to prepare for an official "v2" release of the vector source/sink combo.

enhancement(vector source, vector sink): prepare for v2 release

---

benches/remap.rs
benches/wasm/mod.rs
src/transforms/remap.rs
tests/behavior/transforms/remap.toml
tests/data/remap/program.vrl
website/cue/reference/components/transforms/remap.cue

This allows one to provide the VRL program source either as a string, or through an external file.
Note that this differs from the request in #6403. My interpretation of the request was different from what the issue described. I still think this is worth adding.
I'll leave the issue open for a potential follow-up that allows injecting snippets of VRL source inside a VRL program.

enhancement(remap transform): allow providing path to VRL program

---

website/README.md

The correct URL is https://cuelang.org/, not https://cue-lang.org/.

docs: updating a broken link

---

website/cue/reference/components/sources/kubernetes_logs.cue

Closes #8738
https://deploy-preview-8744--vector-project.netlify.app/docs/reference/configuration/sources/kubernetes_logs/

chore(kubernetes_logs source): Document minimum required version for Kubernetes

---

website/cue/reference/components.cue
website/cue/reference/components/sources/internal_metrics.cue

docs(observability): Document utilization metric

---

docs/layouts/partials/home/community.html
docs/layouts/partials/home/hero.html
docs/layouts/partials/home/installation.html
docs/layouts/partials/navbar.html
docs/tailwind.config.js

- Update "Docs" button to show dropdown on text hover
- Update width styles on search button section to allow responsiveness on screens > ~ 1200px
- Fix overflow caused by search
- Update 3 quick links buttons on mobile to wrap, center, and have a slightly larger icon size
- Give installs section a defined width, center
- Style community stats section to be mobile friendly, define width
- new `xxs` and `fourth` width breakpoints

fix(css website): Homepage Mobile Adjustments

---

website/content/en/releases/0.15.2.md
website/cue/reference/releases/0.15.2.cue
website/layouts/partials/docs/component-alias.html

From https://github.com/timberio/vector/pull/8765
I spot checked the diff of v0.15:docs and master:website and couldn't
see anything else that appeared to be missing.

docs: Add in some files that were dropped in merge

---

src/sinks/loki.rs

Closes #8702
I wasn't able to find some documentation that explicitly says `[a-zA-Z_][a-zA-Z0-9_]*` is the regex, but going through loki code and testing against Grafana Cloud it seems they follow Prometheus convention https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels. The closest mention of this is for LogQL under [Parser Expression](https://grafana.com/docs/loki/latest/logql/).

enhancement(loki sink): Validate label names

---

website/content/en/highlights/2021-07-21-0-16-upgrade-guide.md

Somewhere along the line this change was introduced, which breaks the site build (due to the link checker).

fix(external docs): Fix malformed heading causing site build to break

---

website/cue/reference/components/sinks/aws_s3.cue

We don't actually use `list_buckets`.

docs(aws_s3 sink): Remove unneeded IAM permission

---

website/cue/reference/remap/literals/regular_expression.cue

Noticed by user in discord:
https://discord.com/channels/742820443487993987/746070591097798688/877834630965891082

docs(vrl): Add missing regex flags

---

src/sources/datadog/agent.rs

This commit removes a lazy_static and call to a lazy_static from the
DatadogAgentSource. As a part of #8512 I spent some time trying to remove warp
from the agent source to see its effect and found that, on the whole, it would
not really be worth all that much. warp might bloat our stack traces somewhat
but is lean internally. That said, I did find that I could remove some
serialization from the source, primarily by migrating globally retrieved types
into the source struct itself.
See also #8472

chore: Migrate API_KEY_MATCHER and log_schema() into DatadogAgentSource

---

website/cue/reference/components.cue

This PR fixes some borked indentation by replacing a list with a table, which I think looks a little bit nicer.
Example: https://deploy-preview-8788--vector-project.netlify.app/docs/reference/configuration/transforms/aws_ec2_metadata/#proxy.no_proxy

fix(external docs): Fix indendation issue in config description

---

src/sources/kubernetes_logs/parser/cri.rs
src/sources/kubernetes_logs/parser/docker.rs
src/sources/kubernetes_logs/parser/picker.rs
src/sources/kubernetes_logs/parser/test_util.rs

Fix for https://github.com/timberio/vector/issues/8606
Change CRI parsing regex to allow capturing invalid UTF-8 symbols and deal extra \n symbol

fix(kubernetes_logs source): Fix regex parsing errors 

---

website/cue/reference/components/sinks/statsd.cue

This sink does not support it.
Closes #8821

docs(statsd sink): Remove encoding option

---

lib/vector-core/src/metrics/label_filter.rs

We are preseving this for compatibility but I missed this extra filter
in #8417

fix(observability): add back component_name label

---

website/cue/reference/components.cue
website/cue/reference/configuration.cue

docs(networking): Document global proxy options

---

website/content/en/docs/setup/installation/package-managers/vector-installer.md

As you can see on [this page](https://vector.dev/docs/setup/installation/package-managers/vector-installer), when you don't specify a language for a code block it comes out looking a bit funny. Just a small nit.

fix(external docs): Specify syntax for code block

---

website/assets/css/style.css
website/cue/reference/cli.cue
website/layouts/partials/banner.html
website/layouts/partials/home/community.html
website/tailwind.config.js

- Updates `hover:underline` class to use border-bottom
- Updates homepage community section links (2) for visual consistency
- Updates `li` behavior when containing elements such as `code` or `a` as a first or last child
Homepage
- https://deploy-preview-8860--vector-project.netlify.app/
`li` with links / code blocks
- https://deploy-preview-8860--vector-project.netlify.app/docs/setup/installation/platforms/docker/
- https://deploy-preview-8860--vector-project.netlify.app/highlights/2021-07-21-0-16-upgrade-guide/#vector_source_sink
- https://deploy-preview-8860--vector-project.netlify.app/docs/administration/validating/
- https://deploy-preview-8860--vector-project.netlify.app/docs/reference/cli/ (bullets at bottom)

fix(css website): Typography Fixes

---

.github/workflows/test.yml
scripts/check-fmt.sh
website/content/en/docs/setup/installation/package-managers/helm.md

Was previously gated to run only on Rust source changes, but this check
seems light enough to just always run it since it applies to all files.

chore(dev): Separate out `check-style` check

---

website/cue/reference/components/sinks.cue
website/cue/reference/components/sources.cue

The cue was a bit malformed so it wasn't rendering these options.

docs(socket source, socket sink): Document send/receive buffers

---

rfcs/2021-08-06-8619-framing-and-codecs-sources.md

chore(codecs): Add RFC for "Framing and Codecs - Sources"

---

docs/specs/component.md

Closes #8728
Closes #8709
This introduces the beginnings of a Vector component specification. The immediate need for this is to drive improvements around Vector's internal instrumentation. Issues like #8839, #8710, #8709, and #8693 all expose inconsistencies in Vector's internal instrumentation that presents problems for future work based on this data.

chore: Add component specification
