src/topology/builder.rs, src/transforms/log_to_metric.rs, src/transforms/mod.rs
This is a little funky, but it seemed to hit the right spot of non-invasive, flexible, and no perf impact (I was worried but the benches say I'm ok). Basically, transforms now have the option to implement a `transform_into` method where they can push as many events as they want into an output vec. The weird part is that this "overrides" the `transform` function but you still have to implement it.
Reasons I didn't do other things:
* Returning a vec from `transform` required a bunch of changes and made most transforms more annoying to write, plus required allocating that vec no matter what
* Passing in the output channel would mean transforms have to become more complicated stream adapters since `send` is async
* Making a whole new stream adapter so we could reuse the same output vec would …
=> Turn one event into multiple metrics

Cargo.lock, proto/event.proto, src/event/metric.rs, src/sources/statsd/parser.rs, src/transforms/log_to_metric.rs
This is to conform to Prom, Statsd and Graphite (and probably many others) metrics protocols which are using `float` types for passing values around.
Relates to #540
=> Use floats for metrics values

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, Makefile, scripts/signoff.sh
This change updates the `CONTRIBUTING.md` guide to require signed commits that adhere to the [DCO](https://developercertificate.org/). I chose this over a CLA because of it's simplicity and openness. CLAs vary from project to project and usually require legal review and other barriers to contributing. Changes include:
- Updated the `CONTRIBUTING.md` guide to reflect these changes.
- Onstalled the [DCO Github bot](https://probot.github.io/apps/dco/) that verifies commits adhere to this.
- Added a `make signoff` target that signs off all commits on a branch. This will most likely be a common task so this makes it very easy.
You can see an example of the commit signoff in the commit for this PR.
=> Add DCO and update CONTRIBUTING.md

Cargo.lock, Cargo.toml, lib/codec/Cargo.toml, lib/codec/src/lib.rs, lib/file-source/Cargo.toml, lib/file-source/src/file_server.rs, lib/file-source/src/lib.rs, lib/trace-metrics/Cargo.toml, lib/trace-metrics/examples/echo.rs, lib/trace-metrics/examples/yak_shave.rs, lib/trace-metrics/src/lib.rs, src/lib.rs, src/main.rs, src/metrics.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/prometheus.rs, src/sinks/tcp.rs, src/sinks/util/http.rs, src/sources/file.rs, src/sources/statsd/mod.rs, src/sources/syslog.rs, src/sources/tcp.rs, src/sources/util/tcp.rs, src/sources/vector.rs, src/topology/builder.rs, src/topology/mod.rs, src/transforms/json_parser.rs, src/transforms/regex_parser.rs, src/transforms/tokenizer.rs
`tokio-trace` has been renamed to `tracing`, this PR updates all our crates to point to the new github. Currently, waiting on this PR to fix certain crate issue internally within tracing.
Related https://github.com/tokio-rs/tracing/pull/139
=> Rename tokio-trace to tracing

DOCUMENTING.md, docs/meta/conventions.md
This was duplicated so I moved it back into the docs folder. I like that it's available at docs.vector.dev since it helps to describe syntax and other rules that make reading our documentation easier.
=> Cleanup documentation conventions

DEVELOPING.md
Checking the documentation is a part of `make check` and requires Ruby and Bundler 2. This PR adds them to the document with development requirements.
=> Add Ruby and Bundler 2 to development requirements

src/transforms/tokenizer.rs, src/types.rs
The tokenizer transform converts a "-" in the input into a "nil", keeping
the field as outlined in #523.
=> Convert "-" into "nil"

Cargo.lock, Cargo.toml, lib/trace-limit/Cargo.toml, lib/trace-limit/benches/limit.rs, lib/trace-limit/examples/basic.rs, lib/trace-limit/src/lib.rs
This implements a wrapper subscriber for tokio-trace and the tokio-trace-fmt subscriber. The goal here is to allow us to rate limit certain noisy logs. This only implements the wrapper sub, benchmarks, and an example. This does not include its use in vector that will come in a follow-up PR.
@lukesteensen I believe we've discussed this enough over slack that you should understand it but feel free to ping me with any questions.
Closes #418
=> Initial rate limit subscriber

src/transforms/regex_parser.rs
Log regex pattern match failures with a warning instead of just a debugging statement, include the original field, and truncate the original field to (arbitrary) 60 characters.
Closes #397
=> Log when regex does not match

Cargo.lock, lib/file-source/Cargo.toml, lib/file-source/src/file_server.rs, lib/file-source/src/file_watcher.rs, lib/file-source/src/lib.rs, src/sources/file.rs
Completes https://github.com/timberio/vector/issues/147 and https://github.com/timberio/vector/issues/444
Stores checkpoints as empty file entries under data_dir with path that looks like
chkpt/[hex file_fingerprint].[file_position]
**Adds preference to control how often file scans and checkpoint writes happen (globs).**
~~I plumb through the data_dir value following the example with sink.buffer.
That way means a lot of files for sources get touched. If this not optimal I can fix.~~ Fixed
~~Also finally fixed some annoying file tests.~~ Moved to https://github.com/timberio/vector/pull/612
=> File checkpoints feature

.metadata.toml, config/examples/transforms/grok_parser.toml, config/vector.spec.toml, docs/usage/configuration/specification.md, docs/usage/configuration/transforms/grok_parser.md, docs/usage/configuration/transforms/regex_parser.md, docs/usage/configuration/transforms/tokenizer.md, scripts/generate/templates/_partials/_component_sections.md.erb, src/transforms/grok_parser.rs, src/transforms/regex_parser.rs, src/transforms/tokenizer.rs, src/types.rs
The same as #406 but for the `grok_parser` transform.
Closes #477
The Rust grok crate provides no way to list the target field names like the regex parser and tokenizer can, so this change is unable to verify the field names. I have filed an issue with the grok crate.
=> feat(grok_parser transform): add type coercion

Cargo.toml, src/lib.rs
This adds the ability to create vector builds that do not include jemalloc and will instead use the default systems allocator. The goal for this is to provide the ability to make vector more portable since jemalloc is not supported everywhere. 
=> feat: Add `jemallocator` feature flag

src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs
This makes IO errors like `Connection refused` retriable for the S3 and Kinesis sinks. There's a larger conversation to be had about the rest of the error type and the appropriate way to handle them, but this seemed like a no-brainer worth getting in immediately.
Addresses the immediate cause of #647
=> fix: retry HttpDispatch errors for s3 and kinesis

src/lib.rs, src/sinks/aws_cloudwatch_logs.rs, src/template.rs, src/templating.rs
Extracts a simple templating system from the Cloudwatch implementation, cleans it up, and adds support for things like multiple keys.
I'm not in love with the name `Template`, so please feel free to propose any alternatives.
Basis for #522
=> feat: reusable templating system for event values

config/examples/sinks/aws_cloudwatch_logs.toml, config/examples/sinks/aws_kinesis_streams.toml, config/examples/sinks/aws_s3.toml, config/examples/sinks/elasticsearch.toml, config/examples/sinks/http.toml, config/examples/sinks/splunk_hec.toml, docs/usage/configuration/sinks/aws_cloudwatch_logs.md, docs/usage/configuration/sinks/aws_kinesis_streams.md, docs/usage/configuration/sinks/aws_s3.md, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/sinks/http.md, docs/usage/configuration/sinks/splunk_hec.md
The units for `batch_timeout` in docs and examples should be `seconds`, not `bytes`. This PR fixes it.
=> fix: Use correct units in example batch timeouts

.circleci/config.yml, docs/setup/installation/manual/from-archives.md, scripts/build-ci-docker-images.sh, scripts/ci-docker-images/builder-armv7-unknown-linux-gnueabihf/Dockerfile, scripts/ci-docker-images/builder-armv7-unknown-linux-musleabihf/Dockerfile, scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
Adds support for armv7 releases.
Ref https://github.com/timberio/vector/issues/544
=> chore: add support for armv7 releases, both gnueabihf and musleabihf

Cargo.lock, Cargo.toml, src/transforms/tokenizer.rs
Since we brought in nom they have finally released to the 0.5 version.
=> chore: Update nom from 0.5.0-beta2 to 0.5

scripts/generate/templates/_partials/_component_header.md.erb, scripts/generate/templates/_partials/_component_troubleshooting.md.erb
Signed-off-by: Denis Andrejew <da.colonel@gmail.com>
=> docs: replace some references to "sink" with `component.type`

CHANGELOG.md, src/sinks/elasticsearch.rs
Closes #471
@binarylogic looks like the docs already reflected this change, so I did not update them.
=> feat(elasticsearch): Default `doc_type` to `_doc` and make it optional

.circleci/config.yml, scripts/build-archive.sh, scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
This PR enables all features, including those with native dependencies, for `x86_64-unknown-linux-musl` target. The resulting binary is fully statically linked, LTO-optimized, and stripped.
The build toolchain is based on Clang and `libc++` from LLVM project, in addition to `musl`.
`libc++` is used by `rdkafka` and `leveldb`. Although it should be possible to link GNU `libstdc++` statically, it makes the resulting binaries licensed under LGPL, which might be not desirable as Vector's license is Apache 2. In contrast, `libc++` is MIT/UIUC licensed.
Clang is used not only because it is easy to pair with `libc++`, but also because it enables cross-language [linker plugin LTO](https://doc.rust-lang.org/rustc/linker-plugin-lto.html). Linker plugin LTO is different from [LTO codegen …
=> chore: Build for x86_64-unknown-linux-musl with all features and optimized binary size

.circleci/config.yml, docs/setup/installation/manual/from-archives.md, scripts/generate/metadata/links.rb, scripts/release-s3.sh
This changes moves the build process to a nightly job instead of on every commit to master. I've updated our release URLs from `edge` to `nightly` as well.
=> chore: release nightly instead of on each commit

proto/event.proto, src/event/metric.rs, src/sinks/prometheus.rs, src/sources/statsd/parser.rs
Seems like the general consensus is to prefer double precision floats for metric values. At least Graphite, Statsd, Prometheus and CloudWatch are all using double values, so I don't think we have reasons not to do the same.
Signed-off-by: Alexey Suslov <alexey.suslov@gmail.com>
=> chore: use double for storing metric values

.circleci/config.yml, docker-compose.yml
This fixes failed master builds due to a recent update to the localstack image. This forces us to use a specific version that we know will work.
=> fix: Use a locked down version of localstack

Cargo.lock
Closes #718 
This updates our one non dev-dependency usage of memoffset via updating crossbeam-epoch that is used via crossbeam-dequeue to 0.7.2.
=> fix: RUSTSEC-2019-0011 by updating crossbeam-epoch

docs/about/data-model/log.md, src/event/unflatten.rs
The serde::Serialize trait implementation for MapValue::Null (added in fbed6bdddddc627f6400bf36a075fcd897a8b09a) used to serialize to `"null"` (a string). However, the correct approach would be to serialize it as `null` to be able to distinguish between a missing value and a string with the value `null`.
Closes #724
Ref #678
=> fix: don't serialize MapValue::Null as a string

docs/about/data-model/README.md, docs/about/data-model/log.md, docs/about/data-model/metric.md, proto/event.proto, scripts/generate/templates/docs/usage/configuration/sources/statsd.md.erb, src/event/metric.rs, src/event/mod.rs, src/sinks/console.rs, src/sinks/prometheus.rs, src/sources/statsd/parser.rs, src/transforms/log_to_metric.rs
Ref #707
As discussed [here](https://github.com/timberio/vector/pull/707#issuecomment-518248036), timestamp information should be added into metric events.
=> feat(data model): add timestamps into metrics

CHANGELOG.md, config/vector.spec.toml, docs/usage/configuration/sinks/aws_cloudwatch_logs.md, docs/usage/configuration/sinks/aws_kinesis_streams.md, docs/usage/configuration/sinks/aws_s3.md, docs/usage/configuration/sinks/blackhole.md, docs/usage/configuration/sinks/console.md, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/sinks/http.md, docs/usage/configuration/sinks/kafka.md, docs/usage/configuration/sinks/prometheus.md, docs/usage/configuration/sinks/splunk_hec.md, docs/usage/configuration/sinks/tcp.md, docs/usage/configuration/sinks/vector.md, docs/usage/configuration/sources/statsd.md, docs/usage/configuration/specification.md, scripts/generate/metadata/sink.rb, scripts/generate/templates/_partials/_component_sections.md.erb, src/topology/builder.rs, src/topology/config/mod.rs, src/topology/mod.rs, tests/config.rs
This adds the ability to disable individual sink healthchecks in the case that you want the healthcheck to pass but not to actually run.
Closes #621
=> feat(topology): Add sink healthcheck disable

src/sources/file.rs, src/topology/config/mod.rs
Couple of small fixes:
* Forbidding unknown fields at root level of configs.
* Validation of sinks and sources for non-emptiness.
* Removing error in case of initialized after prefious run data_dir.
Closes #603.
=> fix: Config validation

src/topology/mod.rs
Ignoring this test will unblock CI from failing due to resource contention within the CI environment. This test specifically requires to spawn a few more tasks than other topology tests and due to this, we have to sleep. But this is not the correct solution. The test is still correct and works locally on beefer machines but struggles on CI. Hopefully, #694 will solve this issue.
=> chore: Ignore topology replace source and transform

CHANGELOG.md, src/main.rs
Small fix for the case when we can't parse new config during reload.
Closes #603
=> fix(config): reload with unparseable config

src/sources/mod.rs, src/sources/udp.rs, src/test_util.rs
Initial implementation of #338 plus tests.
=> feat(new source): Initial `udp` source implementation

src/sinks/prometheus.rs
Update of #733 caused by changes made in #726.
=> fix(prometheus sink): Update use of Metric::Set

.metadata.toml, CHANGELOG.md, config/vector.spec.toml, docs/usage/configuration/sinks/aws_cloudwatch_logs.md, docs/usage/configuration/specification.md, src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_logs/request.rs, src/template.rs
This is the first step for #683 and implements dynamic group creation. It also implements configuration for enabling and disabling dynamically creating groups and streams.
=> feat(aws_cloudwatch_logs sink): Add dynamic group creation

docs/usage/configuration/sinks/README.md, scripts/generate/templates/docs/usage/configuration/sinks/README.md.erb
Closes #708 
Because the available options and user expectations can differ so much between sinks, this stops short of laying out a single strategy that should always be followed. Instead, it goes over the goals of healthchecks and lays out some of the common pitfalls we want to avoid. Finally, there's a checklist that should help guide new implementations.
=> docs: Add guidance for writing healthchecks

proto/event.proto, src/event/metric.rs, src/event/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/console.rs, src/sinks/prometheus.rs, src/sources/statsd/parser.rs, src/transforms/log_to_metric.rs
Closes #512.
This PR adds tags support for metrics. Conceptually tags are pairs of `key` and `value` strings. They are stored in a HashMap, however it is possible to reconsider the choice of data structure.
Statsd source was updated to parse tag components (in DataDog format), and CloudWatch metrics sink was updated to send tags into API endpoint.
Follow up issue #760
=> feat(data model): add tags into metrics model

.circleci/config.yml
Update CircleCI configuration to only notify on master builds to reduce noise from pull requests.
=> fix: only notify on master builds

scripts/build-archive.sh
This PR restores `rust-toolchain` file on exit from the build script to keep the `make build-archive` command idempotent.
=> chore: Restore rust-toolchain after building archive

.circleci/config.yml, scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
Closes #791
`typetag` crate does not function correctly when the executable is linked by LLVM `lld`.
This PR switches the linker for MUSL build from LLVM `lld` to GNU `ld`. It means that linker plugin LTO cannot be used, but Rust codegen LTO is still working.
=> fix: Use GNU ld instead of LLVM lld for x86_64-unknown-linux-musl

Cargo.lock, Cargo.toml, src/sources/udp.rs
This change introduces a fix that allows us to use
BytesDelimitedCodec without needing to wrap it.
=> fix(udp source): Update to `tokio-udp` v0.1.5

Cargo.toml
Refs bed79bbaf9ed5ac566b1765ff989a4cbdd5aefcc
While working on #730 I noticed that the `clickhouse-integration-tests` was used in the code but not defined in the `Cargo.toml`. Thus running `cargo test --features clickhouse-integration-tests` fails:
```
$ cargo test --features clickhouse-integration-tests
error: Package `vector v0.4.0-dev (/home/markus/Coding/vector)` does not have these features: `clickhouse-integration-tests`
```
=> fix: Add missing clickhouse integration test feature

.metadata.toml, config/vector.spec.toml, docs/usage/configuration/sinks/http.md, docs/usage/configuration/specification.md, src/sinks/http.rs, src/sinks/util/http.rs
Closes #796 
Note that this contains no additional tests, as Vector currently has no tests for HTTPS behavior, and I could not see an simple way of turning existing HTTP tests into HTTPS.
=> feat(http sink): Add support for unverified HTTPS

distribution/docker/alpine/Dockerfile, scripts/release-docker.sh
This change switches our alpine build to use our musl builder to produce
a static binary that can run on an alpine container.
=> fix(workflow): Fix docker nightly builds

scripts/README.md
I got an error message about `bundler` being missing when I ran `make generate`. We should mention that additional requirement in the documentation.
=> docs: Add bundler to requirements

lib/file-source/src/file_server.rs
Closes #842
This ended up being kind of annoying. The naive solution results in spamming log messages every time we glob for new files. Rate limiting that log doesn't seem like a great solution because I don't think there's a point in reminding the user every so often that a small file is still small. This message is really targeted at people manually testing out Vector by `echo`ing to a file and then waiting for something to happen. Since that really only needs to happen once, we keep a set of files we've already warned about being too small and use that to log exactly one time when we see a small file. :man_shrugging:
=> fix(file source): log a single warning when ignoring small files

docker-compose.yml
Our old Kafka image was using 0.10.1, which is quite a few years old. This moves us to a better-supported docker image and a modern version of Kafka.
/cc @bruceg
=> chore: switch to more modern kafka image

Makefile, scripts/generate.rb, scripts/release-meta.rb, scripts/release-meta/Gemfile, scripts/release-meta/Gemfile.lock, scripts/util/core_ext/object.rb, scripts/util/printer.rb, scripts/util/version.rb
This adds a new `release-meta` make target. The purpose of this command is to prepare a `.meta/releases/X.X.X.toml` file that looks something like:
```toml
[releases."0.4.0"]
date = 2019-09-20
commits = [
{sha = "e53c86c0895ef0dfa48dbe8a4c572ea1c9d87a84", message = "Start v0.4.0-dev", author = "Ben Johnson", date = 2019-07-02T02:03:58.000000-04:00, files_count = 2, insertions_count = 14, deletions_count = 14},
{sha = "15d6b26409761aa5eb15c70082fc02f83d1e949c", message = "Ensure new bumped version uses -dev", author = "Ben Johnson", date = 2019-07-02T02:04:50.000000-04:00, files_count = 2, insertions_count = 2, deletions_count = 2}
]
```
This strategy has a number of benefits:
1. It becomes an efficient source of truth for release metadata.
2. It follows the same process and conventions …
=> chore(operations): Add relese-meta make target for preparing release metadata

.circleci/config.yml, scripts/build-archive.sh
The `VERSION` variable is no longer needed when building archives since we no longer use the version in the resulting archive file.
This fixes the following error when building archives:
```
scripts/version.sh: line 21: git: command not found
```
=> chore(operations): Remove $VERSION when building archives

.circleci/config.yml, .github/semantic.yml, scripts/generate/templates/.github/semantic.yml.erb
This adds the `verify-*` build steps to the overall test process to ensure our built binaries work across various targets. These steps generally execute in under 30 seconds so I don't see a problem enabling these by default.
=> chore(operations): verify builds by default

.meta/sinks/aws_s3.toml, config/vector.spec.toml, docs/usage/configuration/sinks/aws_cloudwatch_logs.md, docs/usage/configuration/sinks/aws_kinesis_streams.md, docs/usage/configuration/sinks/aws_s3.md, docs/usage/configuration/specification.md, scripts/util/metadata/sink.rb
Ran into some incorrect docs when setting up the S3 sink.
=> docs: fix s3 compression and endpoint options

distribution/install.sh
While installing vector using the install script, I've noticed that the script duplicated the export path line.
It was because I have .zprofile symlinked to .profile.
But after investigation I realized that the script didn't check for the export instruction, so running the script multiple time would duplicate the line.
Additionally, the export line didn't take into account the archive directory name.
The added path was `$HOME/.vector/bin:$PATH` while the path in my computer should have been `$HOME/.vector/vector-0.3.0/bin` it's because tar extract the content in its root directory.
So my fix include:
- getting the archive root dir name (line 178)
- creating a variable _path with the export command (I just realized my naming is a bit messy here) (line 184)
- checking if the path export …
=> fix(operations): fix install script path export

Cargo.lock, Cargo.toml
This updates `tokio-reactor` and `tokio-threadpool` to the latest
versions which provide fixes for MSRV and removes extra duplicate
crates.
=> chore(operations): Update tokio versions

distribution/install.sh
Otherwise it's returning 404 on x86_64 Linux:
```
$ curl https://sh.vector.dev -sSf | sh
__   __  __  
\ \ / / / /
\ V / / /
\_/  \/
V E C T O R
Installer
--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://docs.vector.dev
Community: https://vector.dev/community
--------------------------------------------------------------------------------
>>> Downloading Vector...
>>> command failed: downloader https://packages.timber.io/vector/latest/vector-latest-x86_64-unknown-linux-gnu.tar.gz /tmp/tmp.etSKmFja5Q/vector-latest-x86_64-unknown-linux-gnu.tar.gz
--------------------------------------------------------------------------------
curl: (22) The requested URL returned error: 404 
```
=> fix(cli): Corrected tarball URL address for Linux installation script

.circleci/config.yml, .meta/sinks/elasticsearch.toml, config/vector.spec.toml, docker-compose.yml, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/specification.md, src/sinks/clickhouse.rs, src/sinks/elasticsearch.rs, src/sinks/http.rs, src/sinks/splunk_hec.rs, src/sinks/tcp.rs, src/sinks/util/http.rs, src/sinks/util/mod.rs, src/sinks/util/tls.rs
This adds support for a standard set of TLS options to the Elasticsearch sink, as well as fixing some issues with other aspects of HTTPS support in that sink (the health check would not have worked as it was with some services).
Closes issue #887
=> feat(elasticsearch sink): Add support for TLS options

scripts/release-s3.sh
This adds the `--acl public-read` flag when uploading Vector artifacts to S3. I also added a light verification step post-upload to ensure the files exist and can be read. This would have detected the permission issues.
Ref https://github.com/timberio/vector/issues/956
=> fix(operations): Ensure released s3 files are public-read

.circleci/config.yml, scripts/release-homebrew.sh
Verifies and checks Vector install through Homebrew. This was previously broken and this should help prevent that in the future.
=> chore(operations): Verify and check Homebrew install

.circleci/config.yml, config/vector.toml
It turns out that this check wasn't actually verifying that the `vector` service started properly. Hence why https://github.com/timberio/vector/commit/4c9917754edd71a4ef53b9778d4540e3736d0abb was necessary.
=> chore(operations): Properly verify that the Vector Systemd service started

.circleci/config.yml, scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
This adds `git` to the musl build image, otherwise CI cannot checkout the code properly.
cc @a-rodin
=> chore(operations): Add git to musl build image

Cargo.lock, config/vector.spec.toml, docs/usage/configuration/sinks/clickhouse.md, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/sinks/http.md, docs/usage/configuration/sinks/kafka.md, docs/usage/configuration/sinks/splunk_hec.md, docs/usage/configuration/sinks/tcp.md, docs/usage/configuration/specification.md, scripts/util/metadata/sink.rb, src/sinks/util/tls.rs
The various sinks that support TLS all expect their certificate files to be in PEM format. This change add support for DER format certificate (X.509) and key (PKCS#8) files, and for PKCS#12 identity archives.
Closes #954
=> enhancement(networking): Add support for non-PEM certificate formats

.circleci/config.yml, scripts/check-generate.sh, scripts/generate.rb
This cleans up our CircleCI build process by:
1. Moves the install script testing and releasing into its own workflow.
2. Cleans up the job dependencies to be more specific to allow for quicker testing and building. For example, `verify-deb-artifact-on-deb-10` simply requires `build-x86_64-unknown-linux-gnu-archive-and-deb-package` instead of requiring all of the `check-*`, `test-*`, and `build-*` jobs. 
3. Fixes a bug when checking if there are pending `make generate` changes.
A note about Circle's frustrating synax: (this should further explain why this is so verbose):
1. Tags workflows are not enabled by default, you must explicitly enable tag workflows for each and every job in the workflow.
2. Because YAML does not allow the merging of arrays, it makes it impossible to reuse sections …
=> chore(operations): Improve CI efficiency

benches/buffering.rs, src/sources/file.rs, src/topology/builder.rs, src/topology/config/mod.rs, src/topology/mod.rs, tests/buffering.rs
It turns out #995 was not a complete fix to #979, due to the roundabout way we were using `GlobalOptions`. This simplifies the way that we're using it and adds a test to ensure we actually are setting the default data dir to `/var/lib/vector`.
=> fix(config): make global options actually use default

config/vector.spec.toml, docs/usage/configuration/sinks/aws_cloudwatch_logs.md, docs/usage/configuration/sinks/aws_kinesis_streams.md, docs/usage/configuration/sinks/aws_s3.md, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/sinks/http.md, docs/usage/configuration/sinks/kafka.md, docs/usage/configuration/sinks/splunk_hec.md, docs/usage/configuration/sinks/tcp.md, docs/usage/configuration/sinks/vector.md, docs/usage/configuration/sources/file.md, docs/usage/configuration/sources/syslog.md, docs/usage/configuration/specification.md, docs/usage/configuration/transforms/log_to_metric.md, scripts/generate/templates/_partials/_config_spec.toml.erb, scripts/generate/templates/options_table.rb, scripts/util/metadata/option.rb
This info was missing in the configuration specs.
=> docs: Add relevant when details to config spec

distribution/docker/alpine/Dockerfile, distribution/docker/debian/Dockerfile
=> fix: Add ca-certificates to docker images

distribution/docker/debian/Dockerfile
Following best practices from docker doc.
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
=> chore(operations): Remove debian cache to reduce image size

scripts/release-commit.rb
This bumps the Vector version in the `Cargo.toml` file during the release process. This ensures that the version included in the resulting binary matches.
Closes https://github.com/timberio/vector/issues/1010
Closes https://github.com/timberio/vector/issues/1021
=> chore(operations): Bump version in Cargo.toml before releasing

Makefile
Currently all outputs from `bundle install` including error messages are suppressed by `> /dev/null` pipe, which makes it difficult to figure which issue is causing the bundler to fail. I replaced the `> /dev/null` pipes with bundler's [--quiet](https://bundler.io/v1.2/bundle_install.html) option, which suppresses outputs only if the command succeeds. Hopefully this would help people when they're running into problems with bundle install.
=> chore: bundle install should print output on error

.meta/sources/syslog.toml, .meta/sources/tcp.toml, .meta/sources/vector.toml, Cargo.lock, Cargo.toml, benches/bench.rs, benches/buffering.rs, benches/http.rs, config/vector.spec.toml, docs/about/data-model/log.md, docs/usage/configuration/sources/syslog.md, docs/usage/configuration/sources/tcp.md, docs/usage/configuration/sources/vector.md, docs/usage/configuration/specification.md, src/sources/syslog.rs, src/sources/tcp.rs, src/sources/util/mod.rs, src/sources/util/tcp.rs, src/sources/vector.rs, src/topology/mod.rs, tests/buffering.rs, tests/crash.rs, tests/syslog.rs, tests/tcp.rs
This adds support for systemd socket activation to all the sources that use the `TcpSource` framework. That is, the syslog, tcp, and vector sources. It adds support for a new address type that indicates the socket is being passed in by systemd (or equivalent).
Closes #950 
I am not particularly comfortable with the `systemd#N` address syntax, but it was the best compromise I could think up. It is possible to autodetect when socket activation is in play, but since both Vector and systemd support multiple sockets, this creates an ambiguity with the order in which the sockets are used. I welcome alternate suggestions how to make it work better.
I have tested this on the command line using [systemfd](https://github.com/mitsuhiko/systemfd), but no automated tests are present other than address …
=> enhancement(networking): Add support for systemd socket activation

CONTRIBUTING.md
OpenSSL and pkg-config are required for successful build of Vector, so they are added to the requirements.
=> docs: Add OpenSSL and pkg-config to development requirements

docs/usage/administration/validating.md, src/main.rs, src/topology/builder.rs, src/topology/config/mod.rs, src/topology/mod.rs
Adds a sub command `validate` that performs linting of target configs.
The syntax for this subcommand is `vector -c ./foo.toml validate`, which is potentially a little confusing. Please refer to discussion within https://github.com/timberio/vector/issues/98.
=> feat(cli): Add validate sub command

Cargo.lock, Cargo.toml
Fixes `rdkafka` part of #1032.
Although it solves problem with compiling `rdkafka` crate, there are still linking issues with it unsolved yet.
=> fix(operations): Use rdkafka crate from the upstream Git repository

src/sources/journald.rs
This fixes two minor issues:
1. The checkpoint file is rewritten after each timeout, leading to a file write twice a second, even if no new records have been processed.
2. There are two identical error messages regarding retrieving the checkpoint in completely different contexts.
=> feat(journald source): Fix a couple minor issues with checkpointing

Cargo.lock
commit 137e9ea (fix(operations): Use rdkafka crate from the upstream
Git repository) changed a few lines in the `Cargo.lock` file, but
conflicted with changes in f90f50a (systemd socket activation). This
restores the differences.
=> chore(operations): Fix merge problem in Cargo.lock

Cargo.lock, Cargo.toml
This PR uses the latest version of [ctor](https://github.com/mmastrac/rust-ctor) crate from the Git repository.
Closes #1035 
Ref #1054 #946
=> chore(operations): Update `ctor` dependency

src/buffers/disk.rs
Currently there is one place in LevelDB-related code that implicitly assumes that `usize` is 64-bit. This PR fixes it by using `mem::size_of`.
Ref #1054
=> fix(buffers): Avoid dependency on platform-specific machine word size

.meta/sources/journald.toml, config/vector.spec.toml, docs/usage/administration/validating.md, docs/usage/configuration/sources/journald.md, docs/usage/configuration/specification.md, lib/journald/src/lib.rs, src/sources/journald.rs
This replaces the misleading `current_runtime_only` option with a
`current_boot_only` option.
Closes #1097
=> fix(journald source): Rework option to limit records to current boot

src/sinks/elasticsearch.rs
This change fixes the usage of `rusoto`'s credentials
the issue arises when a user wants to fetch credentials
via the network with the `InstanceMetadataProvider` type.
This type sets a timer that depends on the `tokio-timer`
being set. Previously, this sink used the `wait` combinator
that _does_ not wrap the future with a tokio timer. Thus,
when a user tried to run this it would fail out because
the timer was not set. This changes the code to allow
the `credentials` fetch future to be wrapped in a tokio
timer.
Closes #1093
=> fix(elasticsearch sink): Wrap provider call with a tokio runtime

.gitignore, Cargo.lock, Cargo.toml, src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_logs/request.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs
This PR updates Rusoto to 0.38.0 and adds a few `vim` files to the `.gitignore`, taking care of the first step of #1103.
All tests in `cargo test` are passing on Linux after this change. Hopefully I got the PR title right :)
=> chore(operations): Update Rusoto to 0.38.0

Cargo.lock, Cargo.toml, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/elasticsearch.rs
Closes #1103 
This PR updates Rusoto to 0.41.x. The x is because the credentials crate is at 0.41.1, while the rest are at 0.41.0.
There was a single easily dealt with type change during this update.
=> chore(operations): Update Rusoto to 0.41.x

.meta/sources/journald.toml, config/vector.spec.toml, docs/usage/configuration/sources/journald.md, docs/usage/configuration/specification.md, src/sources/journald.rs
This fixes a couple of issues with the journald source checkpoint handling discovered while dealing with #1097 / #1105.
1. After restarting, the last handled record in the journal would be repeated due to a one-off bug in the cursor handling.
2. The checkpoint is not updated during a stream of records, which could cause repeated records if Vector is interrupted.
=> fix(journald source): Cursor/checkpoint fixes

docs/usage/configuration/transforms/lua.md, scripts/generate/templates/docs/usage/configuration/transforms/lua.md.erb
Previously the documentation was put into an auto-generated file, which made `check-generate` test fail.
=> docs(lua transform): Put example of iterating over all fields out of the autogenerated file

src/sinks/elasticsearch.rs
All the other sinks that use a `RegionOrEndpoint` in their settings do
so with `serde(flatten)` to avoid requiring `region.region` in the
configuration. The elasticsearch sink was missing this directive.
Ref: #1099
=> fix(elasticsearch sink): Flatten out region configuration

Cargo.lock, Cargo.toml
I've released 1.1.0 of `grok`, I think you want to use it!
=> chore(operations): Update grok to version 1.0.1

lib/journald/src/lib.rs, src/sources/journald.rs
Apparently journald does not guarantee that records following the current boot marker will only be from that boot, so Vector needs to add a filter to force that.
=> fix(journald source): Limit journald records to the current boot

benches/bench.rs, benches/buffering.rs, benches/files.rs, benches/http.rs, lib/tracing-limit/benches/limit.rs, src/lib.rs, src/main.rs, src/runtime.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/http.rs, src/sinks/util/http.rs, src/sinks/util/mod.rs, src/sources/docker.rs, src/sources/file.rs, src/sources/tcp.rs, src/sources/udp.rs, src/sources/vector.rs, src/test_util.rs, src/topology/fanout.rs, src/topology/mod.rs, tests/buffering.rs, tests/syslog.rs
https://github.com/timberio/vector/issues/1085
The `tokio` runtime is still leaking out via `Shutdown` and `TaskExecutor` types. I haven't taken time to investigate if those need to be wrapped or abstracted away in some other way.
Additionally, `test_utils` and `main.rs` used the `tokio::Builder`  api to control the runtime's threadcount. Instead of creating a new `Builder`, I just provided alternate constructor methods on `Runtime`.
And obviously, I haven't implemented a free standing `spawn` function yet.
But other than that, it compiles and tests are passing. Let me know what you think
=> enhancement(operations): abstracts runtime into runtime.rs

scripts/check-version.rb
A follow-up for #1102. Because commits in master don't have chronological order, `git.log.since` doesn't always return all commits since the tag.
=> fix(operations): Handle edge cases in the Cargo.toml version check

Cargo.toml
Bump version in `Cargo.toml` to pass the version check from https://github.com/timberio/vector/issues/1083.
=> chore(operations): Bump version in Cargo.toml to 0.6.0

docs/usage/administration/validating.md, docs/usage/configuration/sinks/file.md, scripts/generate/templates/docs/usage/configuration/sinks/file.md.erb, src/sinks/file/file.rs, src/sinks/file/mod.rs, src/template.rs, src/test_util.rs
=> enhancement(file sink): Automatically create missing directories

lib/journald/src/lib.rs
As per systemd man: `sd_journal_flush_matches()` may be used to flush all matches, disjunction and conjunction terms again. After this call all filtering is removed and all entries in the journal will be iterated again.
So reset the filter and then apply the `_BOOT_ID` filter.
Discussion in #1081
=> fix(journald source): Flush and reset any current filter before applying new filter

src/main.rs
Closes #841 
Tested locally and works as expected.
=> fix(observability): ensure internal rate limiting is logged

config/examples/file_to_cloudwatch_metrics.toml, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/datadog_metrics.rs, src/sinks/util/batch.rs, src/sinks/util/buffer/metrics.rs, src/sinks/util/mod.rs
Undoing recently introduced `batched_with_max`, because it was not working as intended, and is basically not required.
Used with MetricBuffer, `batched_with_min` strategy will make sure the buffer sent out either when it contain `batch_size` metrics sharp, or it has timed out.
Ref #856
=> fix(aws_cloudwatch_metrics sink): Fix metrics batch strategy in sinks

docs/usage/administration/starting.md, src/lib.rs, src/list.rs, src/main.rs
This PR adds a subcommand `list` to Vector that prints out all available plugins for each component type in a specified format (currently supports plain text or json).
Closes #931.
=> feat(cli): Add list subcommand

src/sinks/elasticsearch.rs
This is an at-least-temporary fix to #1160
=> fix(config): stop accidentally requiring region for ES

CONTRIBUTING.md, Cargo.lock, Cargo.toml
Ref #1074 #1032.
This PR enables `vendored` feature for OpenSSL and uses a version of `rdkafka` from a fork with merged https://github.com/fede1024/rust-rdkafka/pull/169.
As a consequence, it allows us to remove OpenSSL from the list of development dependencies, thus reducing prerequisites for those who want to compile Vector locally, especially on macOS (see #1032 for details).
=> enhancement(operations): Use vendored OpenSSL

.circleci/config.yml
=> chore: Reduce CircleCI build memory usage

src/sinks/elasticsearch.rs
I missed running `cargo fmt` when resolving the merge conflict.
=> chore: Fix missed `cargo fmt` run on elasticsearch sink

docs/usage/administration/starting.md, src/generate.rs, src/lib.rs, src/main.rs, src/topology/config/component.rs, src/topology/config/mod.rs
For most components this will simply generate an empty table with
boilerplate fields (`type`, `inputs`, etc). Eventually, however,
components will have curated examples written for them which are baked
into the Vector binary and can be used to generate more useful files.
Signed-off-by: Ashley Jeffs <ash@jeffail.uk>
=> feat(cli): Add generate subcommand

config/vector.spec.toml, docs/usage/configuration/sinks/aws_cloudwatch_logs.md, docs/usage/configuration/sinks/aws_s3.md, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/sinks/file.md, docs/usage/configuration/specification.md, docs/usage/configuration/transforms/coercer.md, docs/usage/configuration/transforms/grok_parser.md, docs/usage/configuration/transforms/regex_parser.md, docs/usage/configuration/transforms/split.md, docs/usage/configuration/transforms/tokenizer.md, scripts/generate/templates/_partials/_component_sections.md.erb, scripts/util/metadata/transform.rb
In the docs, we call the [`strftime/strptime`](https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html) format `strftime` everywhere. However, in places where the timestamps are parsed from strings it would be more clear to call the format `strptime`, as what we do is similar to `strptime` function as opposed to `strftime`.
This PR updates this.
=> docs: Use `strptime` instead of `strftime` in docs where appropriate

src/topology/config/vars.rs
Before this change, you could reference environment variables in your
configuration like so:
$FOO
${FOO}
After this change, you can add a default value to that second style,
which is used when the provided environment variable does not exist:
${FOO:-my default value}
All characters except `}` are allowed in the default value. Perhaps we should
limit the allowed set of characters, to be on the safe side, or alternatively
add support for double `}}` to be interpreted as a single `}`?
=> feat(config): support default variable values

Cargo.lock
This PR updates `rdkafka` (more precisely, our fork of `rdkafka`) to use the recent fix of `rdkafka/cmake` feature (https://github.com/timberio/rust-rdkafka/commit/c7ee668afb43d662f0cc87af3b159c132d525419). Now it can be combined with `rdkafka/ssl_vendored` feature.
We need to use both features together for musl builds, which are currently possible only when `librdkafka` is built using `cmake`.
=> chore(operations): Update rdkafka to fix rdkafka/cmake feature

Cargo.lock, Cargo.toml
Supersedes https://github.com/timberio/vector/pull/1092, closes https://github.com/timberio/vector/issues/1056.
=> chore(operations): Use leveldb from fork with improved portability

src/sources/statsd/mod.rs, tests/syslog.rs
This PR increases wait timeouts for `syslog` and `statsd` tests in order to let them pass on QEMU emulation of ARMv7.
See also #1180.
=> fix(testing): Increase wait timeouts in tests which otherwise fail on slow CPUs

Cargo.lock, Cargo.toml
This is a yet another PR related to making Vector more portable.
Currently, as I see it, we have two objectives related to our build process and dependencies:
1. Provide pre-compiled binaries for a variety of platforms, including those [listed here](https://github.com/timberio/vector/milestone/18). Because we build them ourselves in CI, there are no constraints on number of build-time dependencies.
2. Streamline build process for first-time contributors, ideally making building Vector as easy as just installing [rustup](https://rustup.rs/), cloning Vector's repository and running `make build` or `cargo build`. It is fair to assume that the two most popular platforms among them are `x86_64-unknown-linux-gnu` and `x86_64-apple-darwin`.
While most of our dependencies can meet these …
=> chore(operations): Control which version of leveldb-sys to use with features

lib/journald/src/lib.rs, src/sources/journald.rs
The fix for journald cursor handling in #1086 was broken by subsequent changes in #1106 due to the invalid internal state logic. This effectively reintroduced the same bug and is fixed here (along with another bug).
=> fix(journald source): Re-fix journald cursor handling

Cargo.lock, Cargo.toml, src/event/mod.rs, src/transforms/ansi_stripper.rs, src/transforms/mod.rs
Given a log field with ansi escape sequences such as:
\x1b[32mhello\x1b[m world
The escape sequences are stripped from the string:
hello world
This transformer only works on string-type fields, any other field type
will result in a warning and an unchanged value.
---
This does not yet add any documentation, or changes any benchmarks or integration tests.
Closes #908
=> feat(new transform): Add ansi stripper transform

Makefile, src/main.rs, website/docs/administration/validating.md
The config targets for the validate command are now unadorned strings,
making it possible to utilize wildcard paths to validate multiple config
files in one command:
`vector validate ./configs/*.toml ./and/also/this.toml`
This also makes it more consistent with the new `test` subcommand.
=> enhancement(cli): Allow >1 config targets for validate command

.circleci/config.yml, scripts/check-generate.sh, scripts/ci-docker-images/checker/Dockerfile, scripts/run-docker.sh, scripts/util/core_ext/object.rb, scripts/util/metadata/post.rb, website/metadata.js, website/metadata.js.erb
This PR
1. Uses Ruby 2.6 for `check-generate`. The docker images for this are built in CI.
2. Makes generation of `website/metadata.json` deterministic by sorting keys of all hashes. Otherwise, `make generate` produces different output on different machines.
=> chore(operations): Fix `check-generate` check in CI

.circleci/config.yml, scripts/docker-run.sh
This PR renames script `scripts/run-docker.sh` to `scripts/docker-run.sh` and adds interactive mode to it.
It also uses `./scripts/docker-run.sh <ci-image-name> bash` as a shell for CircleCI `check-*` jobs, which results in cleaner `.circleci/config.yml`.
=> chore(operations): Use bash from Docker containers as a shell in Circle CI

src/sinks/blackhole.rs
The Vector website indicates that the blackhole sink accepts both log
and metric events, but this isn't true: it only accepts logs. There's no
reason this should be the case.
In particular, for metric sources (such as `statsd` in my case) that
want to accept/transform metrics but just send everything to `/dev/null`
for the moment (e.g. when debugging your configuration), there's no easy
way to do this, resulting in an annoying error in the startup topology
check.
I also like enabling blackholes with high `print_amount` settings
anyway, so that my `journald` logs show some progress occasionally. This
will allow me to send all streams to one blackhole that prints that
info.
This patch simply takes events and distinguish metrics, adding them to
the total event count, and taking the total …
=> feat(blackhole sink): accept metric events, too

scripts/build-archive.sh
Currently our release archives contain template file `config/vector.spec.toml.erb`. This PR prevents it from being bundled.
=> fix(operations): Don't put *.erb files to configs directory

website/docs/setup/installation/manual/from-source.md, website/docs/setup/installation/manual/from-source.md.erb
This PR fixes name of `shiplift/unix-socket` feature in installation docs.
=> docs: Fix name of `shiplift/unix-socket` feature

proto/event.proto, src/conditions/check_fields.rs, src/event/metric.rs, src/event/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/console.rs, src/sinks/datadog_metrics.rs, src/sinks/prometheus.rs, src/sinks/statsd.rs, src/sinks/util/buffer/metrics.rs, src/sources/statsd/parser.rs, src/topology/unit_test.rs, src/transforms/add_tags.rs, src/transforms/log_to_metric.rs, src/transforms/remove_tags.rs, tests/support/mod.rs
This PR implements a new metric model, with the following improvements
- `Metric` enum is turned into struct, to make code less repetitive
- Relative (Incremental) and Absolute metrics are clearly separated using dedicated `kind` field
- It became possible to aggregate all basic metrics types (except for Aggregated* ones)
This is a breaking change.
Closes #920, #747, #1025
=> enhancement(metric data model)!: Reorganise metric model

.circleci/config.yml
Because it looks like the timeouts happen only in debug mode, but our target binary is compiled in release mode. So the main downside is longer test duration.
=> fix(testing): Run `x86_64-pc-windows-msvc` tests in release mode

.circleci/config.yml
It looks like CircleCI executors sometime work slower than usually, which results in broken build jobs for ARM ([example](https://app.circleci.com/jobs/github/timberio/vector/45191)). It is probably caused by CPU being used by other build jobs on the same physical machine, which explains why such failures are non-deterministic.
This PR increases max timeout that CircleCI would wait for output before failing the build from 10 minutes to 30 minutes.
=> chore(operations): Increase CI output timeout

.circleci/config.yml, distribution/docker/README.md, distribution/docker/alpine/Dockerfile, distribution/docker/debian/Dockerfile, scripts/build-docker.sh, scripts/generate/templates/_partials/_docker_docs.md.erb, scripts/release-docker.sh, website/docs/setup/installation/containers/docker.md, website/docs/setup/installation/containers/docker.md.erb
Closes https://github.com/timberio/vector/issues/1196.
This uses the new `docker buildx` command to build images for all architectures at once. However, I haven't found a way to run images built with `docker buildx` locally to verify them yet. It looks like it is caused by multi-arch builders using `docker-container` engine, while `docker run` supports only `docker` engine.
=> chore(operations): Build multi-arch Docker images

scripts/generate/templates.rb, website/docs/setup/guides.md, website/docs/setup/installation/manual.md, website/docs/setup/installation/operating-systems.md, website/docs/setup/installation/package-managers.md
This makes capitalization of names of package managers same in different parts of the docs.
[Before](https://deploy-preview-1278--vector-project.netlify.com/docs/setup/installation/package-managers) | [After](https://deploy-preview-1283--vector-project.netlify.com/docs/setup/installation/package-managers)
=> docs: Use `sidebar_label` as subpage title if possible

.circleci/config.yml
This removes extra `setup_remote_docker` step from `relase-docker` CI job.
=> fix(operations): Remove extra `setup_remote_docker` step from `relase-docker`

.circleci/config.yml, .github/CODEOWNERS, scripts/upgrade-docker.sh
Sometimes the new `verify-docker` job fails in CircleCI ([example](https://app.circleci.com/jobs/github/timberio/vector/47471)).
It might be caused by issues related to persisting of the workspace after upgrading Docker, so this PR attempts to avoid this issue by merging the upgrade of Docker with building of the images into a single CircleCI step.
=> fix(operations): Upgrade Docker on the step in which it is used

src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/clickhouse.rs, src/sinks/datadog_metrics.rs, src/sinks/elasticsearch.rs, src/sinks/http.rs, src/sinks/splunk_hec.rs, src/sinks/util/mod.rs, src/sinks/util/retries.rs, tests/config.rs
I wanted to get more eyes on this work. This is most of issue #1090, but I have a few questions.
Is the transform I made to the clickhouse sink valid (ref `with_flat_map`) or should the conversion go the other way on the other sinks (into `with`)?
Should the retry policy be handled separately (ref #1022)?
Am I going the wrong way with `TowerRequestSettings::batch_sink` trying to cram too much into one function? My thinking was to bundle as much of the common code as I could in one place, but look at that return type, yuck.
=> enhancement(config): Refactor the sinks' request_* configuration

.meta/installation.toml, website/metadata.js
This fixes the link in the bottom of the main documentation page.
=> fix(website): Fix `Raspbian` id capitalization

.circleci/config.yml
The x86_64 RPM were built implicitly because the verifier depended on it, but as we don't verify ARM RPMs yet, they were not built.
=> fix(operations): Run `package-rpm*` jobs explicitly

src/sinks/datadog_metrics.rs
=> enhancement(datadog_metrics sink): Send aggregated distributions to Datadog

src/main.rs, src/types.rs, src/unit_test.rs
This commit makes the test and validate subcommands target the default config path in the absense of path arguments.
Closes #1310
Signed-off-by: Ashley Jeffs <ash@jeffail.uk>
=> fix(cli): Test & validate subcommands without args target default path

src/sinks/statsd.rs
=> fix(statsd sink): Fix statsd binding to loopback only

tests/topology.rs
This removes the timeouts needed for our topology multiple sources test.
=> chore(testing): Fix multiple sources test

.circleci/config.yml, .meta/links.toml, Cargo.lock, Cargo.toml, Makefile, website/docs/setup/installation/manual/from-source.md, website/docs/setup/installation/manual/from-source.md.erb
This PR reorganizes features and adds `default-musl` and `default-msvc` features which facilitate building on `*-unknown-linux-musl` and `*-pc-windows-msvc` platforms.
Some other wrapper features are also added, see the documentation.
=> chore(operations): Add "default-{musl,msvc}" features

scripts/ci-docker-images/builder-aarch64-unknown-linux-musl/Dockerfile, scripts/ci-docker-images/builder-armv7-unknown-linux-musleabihf/Dockerfile, scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
This speeds up building of the Docker images.
Ref #1320.
=> chore(operations): Use LLVM from an archive instead of Git

tests/support/mod.rs, tests/topology.rs
We've been seeing some flakiness in these tests on master, so I took a stab at fixing them. These have passed a few thousand times in a row for me locally, so hopefully CI feels the same way.
Instead of relying on sleeps to ensure that our mock source has a chance to process messages, we make its input an unbuffered channel. This means that the `send` future in our test will not resolve until the source actually has possession of the input, as opposed to it sitting in the channel buffer. This should remove all need to worry about timing for these interactions.
=> fix(testing): Remove sleeps from topology tests

.circleci/config.yml, scripts/build-archive.sh
Putting `/etc` directory with init scripts to the archives is relevant only for Linux. This PR modifies the `build-archive.sh` script to not do it for other operating systems.
=> fix(operations): Put `etc` directory only to Linux archives

Makefile
This makes it consistent with the way our build is [documented](https://vector.dev/docs/setup/installation/manual/from-source#feature-flags).
=> chore(operations): Allow passing features to `make build`

Cargo.toml, NOTICE, scripts/build-archive.sh, scripts/package-deb.sh
Closes #1348.
The name `NOTICE` is recommended by the Apache software foundation: http://www.apache.org/dev/licensing-howto.html.
I'm also thinking about including copyright information
```
Copyright (c) 2019 Vector Authors <vector@timber.io>
```
to the `NOTICE` file, as the `LICENSE` file is a standard Apache license file and doesn't contain any copyright information.
=> chore(operations): Add notices for OpenSSL to the license for binary distributions

.circleci/config.yml
Fixes this falure: https://app.circleci.com/jobs/github/timberio/vector/55773.
=> fix(operations): Add requirements for RPM release steps

scripts/generate.rb
The docs generation script `scripts/generate.rb` recurses into all directories to find `.erb` files to transform. However, on some systems, the `bundle install` command in the `Makefile` will install the required gems into a `vendor` directory within the Vector source tree. This results in `scripts/generate.rb` attempting to generate docs in the gems, leading to errors.
Further, the source tree no longer stores any `.erb` files in the `scripts` directory, so just skip all of it.
=> docs: Fix handling of locally-installed bundles

.circleci/config.yml, scripts/ci-docker-images/releaser/Dockerfile
This uses the same `./scripts/docker-run.sh` approach as the `check-fmt` and other similar jobs.
=> fix(operations): Fix `release-github` job

Cargo.toml
Bump version in `Cargo.toml` to pass the version check from https://github.com/timberio/vector/issues/1083.
=> chore: Bump version to 0.7.0

src/transforms/regex_parser.rs
Closes #1349 
When a regex pattern fails to match, we log a warning message that contains the value of the field we tried to match against. To keep the logs tidy, we truncate that value to a reasonable length.
The bug was that our truncation function didn't take into account multi-byte UTF-8 characters. If the byte index at which we attempted to truncate was not at a Unicode character boundary (i.e. in the middle of a multi-byte character), the string slice operation would panic and cause Vector to shut down.
=> fix(regex_parser transform): make truncation utf8-aware

src/dns.rs, src/sinks/clickhouse.rs, src/sinks/datadog_metrics.rs, src/sinks/elasticsearch.rs, src/sinks/http.rs, src/sinks/splunk_hec.rs, src/sinks/util/http.rs, src/sinks/util/tls.rs
This adds DNS resolution through our internal DNS resolver to all sinks based n the `sinks::util::http` module.
Related to #1307
=> feat(networking): Add internal DNS to http based sinks

lib/file-source/src/file_server.rs, lib/file-source/src/file_watcher.rs, lib/tracing-limit/src/lib.rs, src/event/metric.rs, src/generate.rs, src/list.rs, src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_s3.rs, src/sinks/datadog_metrics.rs, src/sinks/http.rs, src/sinks/prometheus.rs, src/sinks/util/buffer/metrics.rs, src/sources/kubernetes/mod.rs, src/sources/splunk_hec.rs, src/sources/syslog.rs, src/topology/builder.rs, src/topology/config/component.rs, src/topology/mod.rs, src/topology/unit_test.rs, src/transforms/geoip.rs, src/unit_test.rs
When through to try and familiarize myself with the code, cleaned up a few things along the way.
- Removed unnecessary clones where I could find them
- In a few spots used closures to prevent `_or` param from being strictly evaluated
- simplified an if-else clause
- len() > 0 == !is_empty()
- &String -> &str (so the function can take both owned Strings and slices)
- redundant `into()` calls
Random question: I had some trouble building where I got a rustup error like `some components unavailable for download for channel 1.39.0: 'lldb-preview', 'miri'`. I don't get this error on `cargo build` in any other project. Am I not building the project correctly?
=> chore: Remove unneeded remove clones

config/examples/docs_example.toml, src/transforms/sampler.rs, website/docs/setup/configuration.md
The field `pass_list` is documented as optional so this updates the transform to match that.
=> fix(sampler transform): Make pass_list field optional

.circleci/config.yml, scripts/build-docker.sh, scripts/release-s3.sh, scripts/util/version.rb, website/docs/setup/installation/manual/from-archives.md, website/docs/setup/installation/manual/from-archives.md.erb, website/docs/setup/installation/manual/from-source.md, website/docs/setup/installation/manual/from-source.md.erb, website/docs/setup/installation/package-managers/dpkg.md, website/docs/setup/installation/package-managers/dpkg.md.erb, website/docs/setup/installation/package-managers/msi.md, website/docs/setup/installation/package-managers/msi.md.erb, website/docs/setup/installation/package-managers/rpm.md, website/docs/setup/installation/package-managers/rpm.md.erb
Closes https://github.com/timberio/vector/issues/1255.
Note about the docs: the tabs titles still display exact versions, but the installation commands use `0.6.X`:
=> chore(operations): Add aliases for latest major and minor versions

scripts/ci-docker-images/checker/Dockerfile, scripts/ci-docker-images/releaser/Dockerfile
Release of Bunder 2.1 broke our `checker` and `releaser` Docker images, which used Bundler 2.0.
This PR forces installation of Bundler 2.0.x instead of the latest 2.1.x. The possible reason of the failures is the fact that 2.1 turned off all deprecated features by default (see [the release notes](https://github.com/bundler/bundler/releases/tag/v2.1.0)).
Going further, I think we need to migrate our Docker images to Bundler 2.1, which is represented by issue https://github.com/timberio/vector/issues/1393.
=> fix(operations): Use Bundler 2.0.x for the checker and releaser images

src/sinks/tcp.rs, src/sinks/vector.rs
=> chore(networking): Add custom dns for `vector` and `tcp` sinks

scripts/signoff-git-hook.sh
A git hook to automatically sign off the commits. Just a handy utility to simplify the formalities.
=> chore: Add scripts/signoff-git-hook.sh

README.md, website/docs/setup/installation/manual/from-source.md, website/docs/setup/installation/manual/from-source.md.erb
Removes some duplication from the item about installation of C and C++ toolchains.
=> docs: Remove duplicated string from the installation docs

src/buffers/mod.rs
This change allows the `Acker::ack` api to be more user friendly
by allowing users to ack zero items without forwarding that ack to
the inner buffer type.
Allowing the `Acker::ack` api to be more user friendly fixes a bug
when using the `StreamAck` sink combinator that would cause CPU usage
of vector to rise to unreasonable levels even when the sink is idle
(no events being processed). The root cause of this issue can be broken
up into two main problems. 1) `StreamAck<T>` would call `Acker::ack`
anytime the inner `Sink` type `T` would return `Ok(Async::Ready)` when
calling its `Sink::poll_complete`. This would cause `Acker::ack` to be
called with `0` pending items to ack. 2) When the buffer type was `Disk`
it would increase the counter by the ack amount and would notify the
writer task …
=> fix(buffers): Don't ack with zero items

.meta/links.toml, .meta/sinks/aws_s3.toml, config/vector.spec.toml, website/docs/reference/sinks/aws_s3.md
The `aws_s3` sink supports [either `region` or `endpoint`](https://github.com/timberio/vector/blob/0a11a36f41143f0c7f39096dc7ad19698d70231d/src/sinks/aws_s3.rs#L42) to specify the location of the target bucket. However, Vector's docs mention only the `region` option.
This PR adds the `endpoint` parameter to the documentation.
=> docs: Document `endpoint` parameter for `aws_s3` sink

tests/buffering.rs
Related issue #1503, this ignores the reclaim buffer test for the moment while we figure out why the nix builds fail.
=> chore(testing): Ignore recliam test

.meta/sinks/kafka.toml, config/vector.spec.toml, src/sinks/kafka.rs, website/docs/reference/sinks/kafka.md
=> chore(kafka sink)!: Use comma delim server list instead of an array

benches/buffering.rs, config/vector.spec.toml, scripts/util/metadata/sink.rb, src/buffers/mod.rs, website/docs/reference/sinks/aws_cloudwatch_logs.md, website/docs/reference/sinks/aws_kinesis_firehose.md, website/docs/reference/sinks/aws_kinesis_streams.md, website/docs/reference/sinks/aws_s3.md, website/docs/reference/sinks/clickhouse.md, website/docs/reference/sinks/elasticsearch.md, website/docs/reference/sinks/gcp_pubsub.md, website/docs/reference/sinks/http.md, website/docs/reference/sinks/kafka.md, website/docs/reference/sinks/new_relic_logs.md, website/docs/reference/sinks/socket.md, website/docs/reference/sinks/splunk_hec.md, website/docs/reference/sinks/vector.md
Closes #1130
Signed-off-by: Lucio Franco <luciofranco14@gmail.com
=> chore(config)!: Rename `buffer.num_items` to `buffer.max_events`

distribution/nix/default.nix.erb, tests/buffering.rs
This PR makes CI tests on NixOS pass using the following workarounds
1. Increasing the timeout in the tests involving buffers.
2. Disabling tests which require access to AWS credentials, as they don't work in CI.
Ref https://github.com/timberio/vector/issues/1180.
=> fix(operations): Fix tests for NixOS

.meta/sources/file.toml, config/vector.spec.toml, website/docs/reference/sources/file.md
Related to #1055.
This PR updates the docs for `start_at_beginning` to be clear on what it actually changes. @lukesteensen and I chatted and opted for not updating the code since this change is very nuanced. We most likely want to refactor part of the file source to reduce the places where we choose what to do with a file.
=> docs(file source): Clairfy `start_at_beginning`

src/event/mod.rs, src/transforms/ansi_stripper.rs
=> chore(log data model): Deprecate `LogEvent::into_value` in favor of `LogEvent::remove`

src/sinks/gcp_pubsub.rs
`into_iter()` is expected for arrays is expected to be deprecated in upcoming versions of Rust, nightly already give a warning on using it instead of `iter()`.
=> chore(testing): Use `.iter()` instead of `.into_iter()` for arrays

.meta/links.toml, .meta/sinks/splunk_hec.toml, config/vector.spec.toml, src/event/unflatten.rs, src/sinks/splunk_hec.rs, website/docs/reference/sinks/splunk_hec.md
Closes https://github.com/timberio/vector/issues/1534.
The option is added only to `json` encoding, as `text` encoding was not using `fields` previously.
I decided to not implement dropping the indexed fields from `events` mentioned in #1534 for now as I'm worried about unexpected results for existing users. It can be easily changed.
=> enhancement(splunk_hec sink)!: Add a new option for specifying indexed fields to `splunk_hec` sink

CONTRIBUTING.md
This change introduces some improved docs on the process for proposing large PRs. We've in the past run into issues with PRs living for a while because they are large and complex. This should hopefully clear some of that up.
=> chore(docs): Add PR length guidelines to contrib

scripts/util/metadata.rb
This PR makes sorting order of blog posts stable in case if there are multiple posts with the same date, so the content of README becomes a deterministic function of the content.
=> fix(operations): Make sorting of blog posts stable

.circleci/config.yml
Ref #1527.
This PR adds the same AWS keys to the environment as the ones used in `test-stable` for `test-x86_64-pc-windows-msvc` test job.
=> fix(operations): Add AWS API key for Windows tests in CI

.circleci/config.yml
It is used by `scripts/release-github.rb` script, but is not passed inside the Docker container where this job is running.
=> fix(operations): Pass `CIRCLE_SHA1` environment variable to `release-github` job

src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_logs/request.rs, src/sources/logplex.rs
This just upgrades a few log statements so that they show up by default. All of these statements should be sufficiently low volume as not to be annoying, but often enough that an operator can see what's happening.
This was prompted by running the cloudwatch sink myself and noticing that it's completely silent during operation, which makes me nervous.
=> enhancement(observability): enable more logging by default

.meta/sinks/socket.toml, .meta/sinks/vector.toml, config/vector.spec.toml, src/sinks/util/tcp.rs, src/sinks/vector.rs, src/sources/vector.rs, tests/tcp.rs, website/docs/reference/sinks/socket.md, website/docs/reference/sinks/vector.md
This PR fixes the issues observed in #1574 and also refactors our TCP sink to handle DNS resolution internally instead of during the build phase. Since the `vector` sink also uses this implementation it has also been fixed.
The issue was originally noted in #1574 and it showed that the `vector` sink would panic if set using a host name that was not an `IPv4` or `IPv6` address. The panic turned out to be produced from [`this line`] of code from `trust-dns`. This line attempts to find the current executor in thread local storage and spawn the tcp future onto that executor. Since, in our build phase we do not currently provide access to this executor in thread local storage the `spawn` here would fail and panic (which is normal behavior if you just call `tokio::spawn`). The problem here is …
=> fix(socket sink): Improve DNS resolution

scripts/generate/templates/_partials/_options.md.erb, website/docs/reference/env-vars.md, website/docs/reference/sinks/aws_cloudwatch_logs.md, website/docs/reference/sinks/aws_kinesis_firehose.md, website/docs/reference/sinks/aws_kinesis_streams.md, website/docs/reference/sinks/aws_s3.md, website/docs/reference/sinks/clickhouse.md, website/docs/reference/sinks/datadog_metrics.md, website/docs/reference/sinks/elasticsearch.md, website/docs/reference/sinks/gcp_pubsub.md, website/docs/reference/sinks/http.md, website/docs/reference/sinks/kafka.md, website/docs/reference/sinks/new_relic_logs.md, website/docs/reference/sinks/socket.md, website/docs/reference/sinks/splunk_hec.md, website/docs/reference/sinks/vector.md, website/docs/reference/sources/docker.md, website/docs/reference/sources/journald.md, website/docs/reference/sources/kafka.md, website/docs/reference/sources/socket.md, website/docs/reference/sources/syslog.md, website/docs/reference/sources/vector.md, website/docs/reference/tests.md, website/docs/reference/transforms/aws_ec2_metadata.md, website/docs/reference/transforms/log_to_metric.md, website/docs/reference/transforms/sampler.md
It fixed this build issue: https://app.netlify.com/sites/vector-project/deploys/5e2982396817e2000a105f1e.
=> fix(website): Escape special characters in options descriptions

distribution/rpm/vector.spec
Closes https://github.com/timberio/vector/issues/1581.
A special note: we need to mention in the docs that in order to use `journald` source, the `vector` user has to be added to `systemd-journal` group. However, as it not specific to just RPM package, I'm going to do it in a separate PR.
=> fix(platforms): Create `vector` user when installing RPM package

scripts/release-commit.rb, scripts/release-meta.rb
The flow for doing a new patch release is expected to be the following:
1. Backport all necessary fx from `master` to the branch corresponding to the minor version (for example `v0.7`). Pull requests (https://github.com/timberio/vector/pull/1586 is an example) can be used  to simplify reviewing and discussions, but these pull requests have to be merged using `git rebase` instead of `git merge --squash` in order to preserve the commit messages. As currently only squash merges are enabled in GitHub UI for Vector's repository, the simplest way to do it is to use the command line, for example:
```git
MINOR_VERSION_BRNACH=v0.7
PR_BRANCH=prepare-0-7-1
git checkout $PR_BRANCH
git rebase $MINOR_VERSION_BRANCH
git checkout $MINOR_VERSION_BRANCH
git merge $PR_BRANCH
```
2. Run `make release` in the …
=> chore(operations): Support bug fixing releases

scripts/release-commit.rb
A follow-up to https://github.com/timberio/vector/pull/1587. Running `make release` command didn't add the newly generated files in `.meta/releases` to the release commit automatically, which lead to incomplete releases. This PR fixes it.
=> fix(operations): Add all generated files to the release commit

distribution/rpm/vector.spec
Previously `systemd` was required only as built-time dependency, but not a run-time dependency. #1583 added it to the list of run-time dependencies, however it turned out that it breaks installation of the package on Amazon Linux: https://circleci.com/gh/timberio/vector/79129?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.
So this PR removes it from the list of dependencies, as Vector can start without it. The users who want to use `journald` source would already have it installed on their machines, so there is no need to explicitly require it.
=> fix(operations): Do not require `systemd` as an RPM dependency

Makefile, scripts/release-push.sh
This PR adds new Makefile target `push-release`.
Together with #1587 it splits single `make release` into two separate steps. The first one, `make release`, only generates a release commit, which is supposed to be pushed to `prepare-*` branch and tested in CI. On the other hand, `make release-push` actually tags the release and pushes it to the corresponding branch.
=> chore(operations): Add `release-push` target to the Makefile

src/sources/docker.rs
Fixes bug reported in [comment](https://github.com/timberio/vector/issues/984#issuecomment-573683760).
As mentioned in the following [comment](https://github.com/timberio/vector/issues/984#issuecomment-574225167), initial list of containers gotten from docker sometimes doesn't contain container of the vector requesting the list.  
This PR has a fix which checks all encountered containers if they are self/vector, and not only the ones from the initial list.
=> fix(docker source): Always check containers for self

.meta/sources/journald.toml, website/docs/reference/sources/journald.md, website/docs/reference/sources/journald.md.erb
See the note from https://github.com/timberio/vector/pull/1583#issue-366419329.
=> docs: Document adding the Vector user to a group which can use `journalctl`

.circleci/config.yml, src/sources/kubernetes/test.rs
This should fix CI failures for our kube tests by generating a unique namespace per test via appending a uuid v4 to each namespace.
=> chore(testing): Disable kuberenetes tests in CI temporarily

src/event/mod.rs, src/sinks/splunk_hec.rs
This is a minor refactor of `LogEvent` iterator traits. Usually `FromIterator` is implemented in terms of `Extend`, so I've done that which allowed simplifying in a few places. Additionally, `FieldsIter` has an `Iterator` implementation with a loop that would never loop (if `None` `return None`, if `Some` return (k, v))-- so I reduced that to a `.map` call.
=> chore(log data model): Add Event::extend, change param to slice

Cargo.toml, src/sinks/util/buffer/json.rs, src/sinks/util/buffer/mod.rs
This introduces a new buffer type which is designed to be used with
sitiation where you may want to batch events and limit batch sizes by an
amount of bytes but also embed these events in some deeply nested json
object. This leverages `serde_json::value::RawValue` and makes it much
easier to nest events in some json body.
```rust
fn build_request(events: Vec<BoxedRawValue>) -> http::Request<Vec<u8>> {
let json = json!({
"lines": events,
});
let body = serder_json::to_vec(&json).unwrap();
// snip
}
```
This is related to #1434 
=> chore(buffers): Introduce `JsonArrayBuffer` buffer

Cargo.lock, Cargo.toml, src/lib.rs
The version of `http` we were on had a vulnerability, so this is a simple bump to a new patch version to address it.
The `prost-build` bump is to bring it in line with the version we're using in our non-dev dependencies. This was likely overlooked last time we upgraded versions.
=> chore(security): upgrade http and prost-build deps

.github/workflows/ci.yaml, deny.toml
We can expand this later on, but this gives us a simple check for new security advisories against any of our dependencies.
The check should currently fail until we merge #1638, so I'll rebase after that.
=> chore(security): add cargo-deny check for advisories

Cargo.lock, Cargo.toml
```
Updating crates.io index
Updating git repository `https://github.com/timberio/leveldb`
Updating git repository `https://github.com/timberio/rust-rdkafka`
Updating git repository `https://github.com/timberio/rlua`
Updating git repository `https://github.com/tokio-rs/tracing`
Updating git repository `https://github.com/timberio/leveldb-sys`
Updating aho-corasick v0.7.6 -> v0.7.7
Adding anyhow v1.0.26
Updating arc-swap v0.4.3 -> v0.4.4
Updating arrayref v0.3.5 -> v0.3.6
Adding arrayvec v0.5.1
Updating atty v0.2.13 -> v0.2.14
Adding autocfg v1.0.0
Updating backtrace v0.3.40 -> v0.3.43
Updating blake2b_simd v0.5.8 -> v0.5.10
Updating block-padding v0.1.4 -> v0.1.5
Updating bstr v0.2.8 -> v0.2.10
Adding bumpalo v3.1.2
Updating cast v0.2.2 -> v0.2.3
Updating cc v1.0.46 -> v1.0.50
Updating …
```
=> chore: Upgrade all dependencies

distribution/rpm/vector.spec
In #1583 a problem with group creation was introduced, so that instead of group name `vector` an empty string was passed to the command. This PR fixes it.
=> fix(platforms): Fix group creation in the RPM package

Cargo.lock
I forgot to do this yesterday but there is a new `Cargo.lock` format in `1.41.0`, you can read more about it [here]. Since, we updated the lockfile to the latest version yesterday this is just a format change and adds no new dependencies.
[here]: https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#less-conflict-prone-cargolock-format
=> chore: Update to new lockfile format

src/main.rs
Sets some global [appsettings from Clap-rs](https://docs.rs/clap/2.33.0/clap/enum.AppSettings.html) to
* Give Vector's `--help` some colour where clap can support it. (`ColoredHelp`)
* Allow `vector gen` and other shorthands (`InferSubcommands`)
* Allow our team to manually specify the command ordering to make sure the are semantic and sensible. (`DeriveDisplayOrder`)
+ Reordered `vector test` to be near the bottom since it is experimental.
Please let me know if you think any should be skipped!
=> enhancement(cli): Add some flair to `--help`

Cargo.lock, Cargo.toml, lib/tracing-limit/Cargo.toml, lib/tracing-metrics/Cargo.toml
This release just went out, so thought we should upgrade to it so we can get off an `alpha` release.
=> chore: Upgrade to `tracing-subscriber 0.2.0`

.meta/.schema.json, .meta/_partials/_types.toml, .meta/transforms/coercer.toml, .meta/transforms/grok_parser.toml, .meta/transforms/logfmt_parser.toml, .meta/transforms/regex_parser.toml, .meta/transforms/split.toml, .meta/transforms/tokenizer.toml, config/vector.spec.toml, scripts/util/metadata.rb, scripts/util/metadata/transform.rb, website/docs/reference/transforms/coercer.md, website/docs/reference/transforms/grok_parser.md, website/docs/reference/transforms/logfmt_parser.md, website/docs/reference/transforms/regex_parser.md, website/docs/reference/transforms/split.md, website/docs/reference/transforms/tokenizer.md
This introduces the usage of partials in our `/.meta/**/*.toml` files allowing us to compose configuration files versus magical attributes deep in our `script/generate` Ruby files. I started with the `types` table as an example and plan to follow up with more changes over time to complete this transition.
The has the following advantages:
1. We can begin to remove custom logic deep in our `scripts/generate` Ruby files, reducing our dependence on these classes.
2. Moving construction of all options into the `.meta` dir has the advantage of running through our new [`.meta/.schema.json` file](https://github.com/timberio/vector/blob/master/.meta/.schema.json). Currently, options defined during Ruby class instantiation skip this validation.
3. It removes a layer that documenters have to deal …
=> chore(website): Allow partials in /.meta/*.toml files

src/sinks/clickhouse.rs, src/sinks/util/http.rs, src/sinks/util/retries.rs
Follow up to #1706 this adds a `RetryAction` enum to allow sinks to specify why they are _not_ retrying a request.
=> feat(networking): Add proper non retry messages

src/topology/builder.rs, src/topology/mod.rs, tests/config.rs
Prints topology warnings as... warnings. Also clarifies the message about zero outputs.
Closes https://github.com/timberio/vector/issues/414
=> feat(config): Clarify topology warnings

.circleci/config.yml
Fixes [this failure](https://app.circleci.com/jobs/github/timberio/vector/82129).
=> chore(operations): Fix `test-stable` CI job

Cargo.lock, Cargo.toml, README.md, src/main.rs, src/topology/config/mod.rs
This currently works by parsing each discrete file individually, and appending them to a root config. This has the advantage of being able to report the specific file that fails to parse or introduces a duplicate. However, it also means we need to manually determine how parsed config structs are to be merged.
Global fields may be specified multiple times, but if there is a collision then it is considered an error. This makes it possible to run configs together that also work individually.
=> feat(cli): Support multiple configuration files.

Makefile, scripts/docker-run.sh, scripts/run.sh
[Podman](https://github.com/containers/libpod) is a drop-in command line replacement for docker that adds the ability to run containers rootless with no daemon. For running things like `make generate` this may be a useful solution for some.
=> chore(operations): Add support for running containers under Podman

src/topology/builder.rs, src/topology/config/mod.rs, src/topology/config/validation.rs, tests/config.rs
This allows us to report to users the exact chain of components that
causes the cycle.
The message now looks like:
`ERROR vector: Topology error: Cyclic dependency detected in the chain [ baz -> foo -> bar -> baz ]`
Closes #321
=> feat(cli): Improve cyclic deps error message

.meta/sinks/splunk_hec.toml, config/vector.spec.toml, website/docs/reference/sinks/splunk_hec.md
It looks like our docs mention `ndjson` as being the config option but within the code we actually refer to it as `json`. This is because the user doesn't have to worry about the encoding format since we follow splunk's hec format. We also don't actually send the data as ndjson but as json anyways.
=> fix(splunk_hec sink): Fix encoding docs

Cargo.lock, Cargo.toml, config/kubernetes/vector-daemonset.yaml, src/main.rs, src/topology/config/mod.rs, src/topology/config/watcher.rs, website/docs/administration/process-management.md
Closes #938
Watcher now raises SIGHUP on Unix, and does nothing on Windows.
Instead of `reload_config` option in `toml`, we are accepting optional flag `-w` as cli argument.
=> enhancement(config): Option to reload config on file change

src/generate.rs
This PR changes the `vector generate` syntax to allow forward slashes: `foo/bar,baz/boo`, closing https://github.com/timberio/vector/issues/1684. This is backwards compatible as the pipe syntax can still be used.
The output now also adds empty lines between component types to make the formatting nicer:
```toml
data_dir = "/var/lib/vector/"
dns_servers = []
[sources.source0]
max_length = 102400
type = "stdin"
[transforms.transform0]
inputs = ["source0"]
drop_field = true
drop_invalid = false
type = "json_parser"
[sinks.sink0]
healthcheck = true
inputs = ["transform0"]
type = "console"
[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```
This is the lowest hanging fruit of https://github.com/timberio/vector/issues/1685, we're still missing:
1. Proper ordering of …
=> feat(cli): Improve `vector generate` syntax and formatting

.meta/tests.toml, src/conditions/check_fields.rs, src/conditions/mod.rs, src/config_paths.rs, src/lib.rs, src/main.rs, src/topology/config/mod.rs, src/topology/unit_test.rs, src/unit_test.rs, website/docs/reference/tests.md, website/docs/setup/guides/unit-testing.md
This adds a few quality of life improvements to the `test` subcommand:
You now see (in addition to before):
- The condition that failed (by index)
- The output that failed it, shown when there's > 1 output events (by index)
- The specific predicate(s) that failed for each condition (and their arguments)
- The input events that caused the test to fail
```
failures:
--- ./configs/test.toml ---
test 'foo':
check transform 'foo' failed conditions:
condition[0]: predicates failed: [ message.eq: 'foo', other_field.exists: true ]
payloads (JSON encoded):
input: {"hello":"world"}
output: {"foo_field":"foo value","hello":"world"}
```
You can now also configure test outputs with no conditions, and instead of running conditions Vector will print what went in and what came out:
Config:
```toml …
```
=> feat(cli): Test sub command improvements

src/generate.rs, src/topology/config/component.rs
Before:
```
vector generate 'stdin|console'
Generate error: component type 'console' does not exist
```
After:
```
vector generate 'stdin|console'
failed to generate transform 'console': type 'console' does not exist
```
It's also printed in red now.
=> feat(cli): Clarify generate error messages with type info

.github/workflows/ci.yaml, Makefile, docker-compose.yml, tests/Makefile, tests/behavior/transforms/add_fields.toml, tests/behavior/transforms/remove_fields.toml
This PR adds behavior tests for `add_fields` transform using the config unit testing framework.
The goal is to codify the current behavior of our transforms related to nested fields to ensure that  either it doesn't change or the changes are properly communicated in the release notes. It can be considered a part of work on #704, related to https://github.com/timberio/vector/pull/1662#issuecomment-584250760.
=> chore(testing): Add behavior tests for `add_fields` and `remove_fields` transforms

lib/file-source/src/lib.rs, lib/file-source/src/metadata_ext.rs, src/main.rs, src/sinks/file/file.rs, src/sources/file.rs, src/sources/socket/mod.rs, src/topology/config/watcher.rs, src/types.rs, tests/syslog.rs
As reported in #1412 , Windows builds/tests have lints and errors.
This PR fixes all lints and tweaks a few tests to make it viable for Windows to pass.
* Mark any `unix` only imports in `#[cfg(unix)]`.
* Windows errors if you try to rename a file into a path that already exists. So we now use a simple file rolling procedure in those tests.
* Improves `unwrap` errors into `expect` errors to give some context to failing tests.
=> fix(windows platform): Correct lints and tests

src/event/discriminant.rs
Adds a test to ensure the root event field order are properly compared.
Relevant to #1662, see https://github.com/timberio/vector/pull/1662#discussion_r380309848
=> chore(testing): Add field order test at src/event/discriminant.rs

.meta/sources/kafka.toml, config/vector.spec.toml, src/sources/kafka.rs, website/docs/reference/sources/kafka.md
Closes #1821 (the source part).
=> enhancement(kafka source): Support advanced `librdkafka` options

.meta/sinks/kafka.toml, config/vector.spec.toml, src/sinks/kafka.rs, website/docs/reference/sinks/kafka.md, website/docs/reference/sources/kafka.md
Closes  #1821 (the sink part).
=> enhancement(kafka sink): Support advanced `librdkafka` options

src/sources/splunk_hec.rs
=> fix(splunk_hec source): Make `token` option optional

.meta/transforms/json_parser.toml, config/vector.spec.toml, src/transforms/json_parser.rs, website/docs/reference/transforms/json_parser.md
=> fix(json_parser transform): only drop source field if JSON parse succeeds (#1861)

.github/semantic.yml, .github/semantic.yml.erb, .meta/sinks/aws_cloudwatch_logs.toml, website/docs/reference/sinks/aws_cloudwatch_logs.md, website/metadata.js
Advance the `cloudwatch_logs` sink to the [`prod-ready` status](https://vector.dev/docs/about/guarantees/#prod-ready). I'd like for this to live as an individual commit so that we can communicate status changes in release notes.
=> status(cloudwatch_logs sink): Advance to `prod-ready` status

.meta/sinks/clickhouse.toml, website/docs/reference/sinks/clickhouse.md
Ref #1876.
1.1.54378 was released on 2018-04-16, Vector passes Docker tests with it.
=> docs(clickhouse sink): Set `min_version` to `1.1.54378`

Cargo.toml, distribution/nix/default.nix.erb, src/dns.rs
This might resolve https://github.com/timberio/vector/issues/1803.
It is a result of a discussion with @LucioFranco we had today about ways to prevent `trust-dns-resolver` to access `/etc/resolv.conf`.
This is WIP because I haven't tested it yet on an actual NixOS machine. Note that tests on NixOS running in Docker would not be enough because Docker mounts `/etc/resolv.conf` from the host machine, so it is always present there.
=> chore(testing): Add feature `disable-resolv-conf` to allow testing on NixOS

.meta/tests.toml, src/topology/config/mod.rs, src/topology/unit_test.rs, website/docs/reference/tests.md, website/docs/setup/guides/unit-testing.md
This replaces the field `input` with an array `inputs`, allowing you to specify any number of input test events for your test. If an `input` is specified this test will still execute, making it backwards compatible with old tests.
~Note: there's a unit test that will fail, I need https://github.com/timberio/vector/pull/1814 in order for it to pass. I'll rebase once it's merged.~
Closes https://github.com/timberio/vector/issues/1819
=> feat(cli): Allow multiple unit test inputs

.meta/tests.toml, src/topology/config/mod.rs, src/topology/unit_test.rs, website/docs/reference/tests.md
This adds an array field `no_outputs_from` to the unit test spec. This allows you to explicitly verify that a transform does not output events during a test.
=> feat(cli): Add `no_outputs_from` field to unit tests

src/transforms/lua.rs, website/docs/reference/transforms/lua.md, website/docs/reference/transforms/lua.md.erb
When using the Lua transform with a function like this:
```lua
event["number"] = 42
```
the resulting event has the value converted back to a string:
```
{ ..., "number": "42", ... }
```
This PR changes the transform to preserve types, and also adds support for setting fields to boolean values, saving the need for further processing to restore the types. It also slightly changes the behavior to drop fields when set to invalid types, rather than erroring out the function. I'm not sure what impact this will have when it comes to https://github.com/timberio/vector/issues/704, however.
Fixes #857.
=> enhancement(lua transform)!: respect Lua types when converting back to events

src/event/mod.rs
Fixes #1872
After talking to @LucioFranco we decided this is the easiest fix. Moving forward, we should consider threading through global options safely.
=> fix: Fix failing benchmarks

.meta/sinks/clickhouse.toml, config/vector.spec.toml, src/sinks/clickhouse.rs, website/docs/reference/sinks/clickhouse.md
Allows users to specify a format for `timestamp` such that it can be parsed by Clickhouse as a `DateTime` data type.
By default we're not applying any formatting (sending as a string), this preserves backwards compatibility, it's also not an entirely unfavorable behavior since it has a higher precision. However, it's worth considering making `unix` formatting the default behavior here instead.
Closes #1443
=> feat(clickhouse sink): Add timestamp_format field

src/main.rs, src/trace.rs
Example json output:
```json
{"timestamp":"Feb 20 11:28:15.096","level":"INFO","target":"vector","fields":{"message":"Log level \"info\" is enabled."}}
{"timestamp":"Feb 20 11:28:15.096","level":"INFO","target":"vector","fields":{"message":"Loading configs.","path":"[\"/etc/vector/vector.toml\"]"}}
{"timestamp":"Feb 20 11:28:15.108","level":"INFO","target":"vector","fields":{"message":"Vector is starting.","version":"0.8.0","git_version":"v0.7.0-168-g841a8f8","released":"Wed, 19 Feb 2020 20:17:41 +0000","arch":"x86_64"}}
{"timestamp":"Feb 20 11:28:15.114","level":"INFO","target":"vector::topology","fields":{"message":"Running healthchecks."}}
{"timestamp":"Feb 20 11:28:15.114","level":"INFO","target":"vector::topology","fields":{"message":"Starting source \"stdin\""}}
{"timestamp":"Feb 20 …
```
=> feat(cli): Add `log-format` cli option

src/sources/kubernetes/file_source_builder.rs
Whenever an inode is reused from an old log file after rotating, Vector will keep the offset and not
process logs. This PR changes the source to use the default fingerprinting strategy instead.
Fixes #1910.
=> fix(kubernetes source): Use checksum fingerprinting

src/topology/unit_test.rs, tests/behavior/transforms/swimlanes.toml
When verifying unit tests Vector checks that input targets are actually connected to output targets in the topology. However, for targets within `no_outputs_from` this check seems heavy handed as it's nice to explicitly confirm it in a test even if components aren't necessarily directly connected.
Also fixes an issue with validating the tested topology when using `no_outputs_from` that was blocking it from being used with `swimlanes`.
=> fix(cli): Relax the requirements for `no_outputs_from` unit test targets

src/main.rs
Closes https://github.com/timberio/vector/issues/1752, closes #1903.
This turns on reporting of all errors happening inside `librdkafka` by default. However, currently these errors are not linked to a a particular sink or source. Ideally we also want to have the related sink or source in the report, but I think it is better to have a separate issue  for this because it might require modification of `rdkafka` to use `tracing` instead of `log`.
=> enhancement(observability): Enable `rdkafka` logs by default

src/lib.rs
This PR places `src/kafka.rs` module behind `#[cfg(feature = "rdkafka")]` in order to make it possible to build Vector without default features.
=> fix(operations): Fix build with `--no-default-features`

src/event/mod.rs
As it stands, vector will fail to run with partial `LogSchema` configuration. Example:
```toml
[log_schema]
message_key = "message"
timestamp_key = "timestamp" 
```
would report "missing field `host_key`".
One of the consequences is that adding a new key like `kubernetes_key` would break all configurations that are configuring `log_schema`.
This PR adds `#[serde(default)]` to the `struct LogSchema` which enables partial configuration.
=> fix(config): Partial `LogSchema`

src/conditions/mod.rs, src/topology/config/mod.rs, src/topology/unit_test.rs, src/transforms/swimlanes.rs, tests/behavior/transforms/add_fields.toml, tests/behavior/transforms/ansi_stripper.toml, tests/behavior/transforms/coercer.toml, tests/behavior/transforms/concat.toml, tests/behavior/transforms/grok_parser.toml, tests/behavior/transforms/json_parser.toml, tests/behavior/transforms/logfmt_parser.toml, tests/behavior/transforms/merge.toml, tests/behavior/transforms/regex_parser.toml, tests/behavior/transforms/remove_fields.toml, tests/behavior/transforms/rename_fields.toml, tests/behavior/transforms/split.toml, tests/behavior/transforms/swimlanes.toml, tests/behavior/transforms/tokenizer.toml
Allows you, for both unit test output conditions and swimlanes, to remove the `type = "check_fields"` line as it's now a default condition.
You _can_ still specify the `type` field without problems, which allows us to add more condition options in the future (coming soon!)
Closes #1840
=> feat(config): Default to `check_fields` condition

.meta/_partials/_conditions.toml, config/vector.spec.toml, src/conditions/is_log.rs, src/conditions/is_metric.rs, src/conditions/mod.rs, tests/behavior/transforms/swimlanes.toml, website/docs/reference/tests.md, website/docs/reference/transforms/swimlanes.md
This adds two new conditions `is_log` and `is_metric`, which are fairly self explanatory. They will allow writers of unit tests to check the actual type of an event coming out of certain transforms.
It will also allow users to create swimlanes that separate logs from metrics to different outputs. However, for swimlanes this currently isn't useful at all as it is forced to deal only in logs until https://github.com/timberio/vector/issues/421 is solved.
=> feat: Add `is_log` and `is_metric` conditions

website/docusaurus.config.js
This was added as part of the basic Docusaurus setup, but I am very much against tracking users.
=> chore(website): Remove Google Analytics

src/generate.rs
This updates the `vector generate` sub command expression to allow custom names for components rather than needing to manually change generated names such as `transform0` to something useful. The syntax is an optional prefix to the component type of the format `<name>:`, which looks like this:
`vector generate stuff:stdin/parser:regex_parser,cool_stuff:lua/console`
=> feat(cli): Allow names in generate subcmd expression

Makefile
Closes https://github.com/timberio/vector/issues/1979.
=> chore: Add `check-component-features` target to the main Makefile

src/transforms/lua.rs
Closes https://github.com/timberio/vector/issues/1721.
This PR adds explicit call to the garbage collector after each invocation of the `lua` transform. It fixes the issues with growing RAM consumption mentioned in https://github.com/timberio/vector/issues/1721. As I understand it, Lua runtime sometimes didn't call GC automatically, that's why there was leak-like pattern of memory usage.
Now the RAM usage of Vector with `lua` transform is flat, even with high event rates.
This explicit call doesn't significantly change the benchmarks because GC is called not after each invocation of the transform, but only each 16th invocation of the transform.
=> fix(lua transform): Explicitly call GC in `lua` transform

.meta/_partials/_conditions.toml, config/vector.spec.toml, src/conditions/check_fields.rs, website/docs/reference/tests.md, website/docs/reference/transforms/swimlanes.md
This adds two new predicates `contains` and `prefix` for the `check_fields` condition, expanding the logical expressions of both unit test outputs and the swimlanes transform.
=> feat(swimlanes transform): Add `contains` and `prefix` predicates to `check_fields`

src/sinks/statsd.rs
This reshuffles our timeout that was added in #2026 to correctly delay the write side of the test. This should give enough time to let the read side spawned task to poll for read interest. This should avoid a race condition where the read side has not gotten enough time to bind and poll for read interest by the time the write task has sent the packet. This is mostly an internal detail to this test and does not affect the actual sink.
=> chore(statsd sink): Reshuffle timeout in test

.meta/sinks/splunk_hec.toml, config/vector.spec.toml, src/sinks/splunk_hec.rs, website/docs/reference/sinks/splunk_hec.md
=> chore(splunk_hec sink)!: Rename `host_field` to `host_key`

.github/checklist.yml
The lockfile should only be updated if we change dependencies and this is when we should actually audit new deps.
=> chore(operations): Check lockfile over cargo.toml

.markdownlintignore
The `target` directory is created by `cargo` when Vector is built and contains various Markdown files with documentation for crates, which don't pass the linting.
Because of that, the `target` directory is added to `.markdownlintignore` in this PR.
=> chore: Add `target` directory to `.markdownlintignore`

website/docs/setup/installation/manual/from-source.md, website/docs/setup/installation/manual/from-source.md.erb
I've made some minor changes in "install from source code" document:
1. Remove 3-d step because its already included in 4-th step (mkdir -p vector)
2. Fixed download link used by curl, so you can paste it in console and its just work
=> docs: Fix for "download source code" step in install from source

.meta/sources/syslog.toml, website/docs/reference/sources/syslog.md
This is something I noticed while building a bnechmark. This improved our `syslog` source example.
=> docs: Improve syslog source example

scripts/ci-docker-images/checker-component-features/Dockerfile
Yesterday a [new version](https://pypi.org/project/remarshal/#history) of `remarshal` utility was released, which caused issues with installing it uisng `pip3` on Ubuntu 18.04 (see https://github.com/dbohdan/remarshal/issues/24).
This PR pins the version to the one which was used before.
=> chore(testing): Fix `check-component-features` test

src/sources/kubernetes/test.rs, src/topology/config/watcher.rs
Fixes the 1. point in #2002 
(Edit: closes #2002)
The problem was in `notify`/`inotify` interaction with `symlinks` and a pattern of changing files by switching from an old file to the new file with the same path. 
The fix re canonicalizes configuration paths after any change has been detected. That way we aren't watching over any `symlink` and are forcing `inotify` to re watch files.
=> fix(config): Force `symlink` re-evaluation

.github/CODEOWNERS, .meta/transforms/lua.toml, benches/lua.rs, config/vector.spec.toml, src/transforms/lua/mod.rs, src/transforms/lua/v1/mod.rs, src/transforms/lua/v2/mod.rs, tests/behavior/transforms/lua.toml, website/docs/reference/transforms/lua.md
This PR adds `version` configuration option to the `lua` transform. The version can take values `1` and `2`, the default values is `1`.
This also splits implementation for both versions, so all further changes on version 2 would not affect version 1.
Ref #2000.
=> enhancement(lua transform): Add `version` configuration option

src/sinks/clickhouse.rs, src/sinks/datadog_metrics.rs, src/sinks/elasticsearch.rs, src/sinks/util/batch.rs, src/sinks/util/http.rs
This PR is the first PR int he process of finishing off the `HttpSink` and general sink based http refactoring. This sink only touches `clickhouse`, `elasticsearch` and `datadog_metrics` but internally simplifies things.
Related to #1659
=> chore(sinks): Part 1 of `HttpSink` refactor

src/transforms/json_parser.rs
I wanted to add a test to ensure white-space does not break JSON parsing since this is a pretty common scenario.
=> chore(json_parser transform): Ensure white-space dooes not break parsing

src/event/util/log/insert.rs, tests/behavior/transforms/add_fields.toml
This PR fixes a bug in the new implementation of field path notation.
When value was inserted in the middle of an array, then instead of replacing the already present value with the same index, it shifted all values to the right. This was not consistent with what we had with in the previous `flatten`/`unflatten` implementation.
=> fix(transforms): Fix array insertion in field path notation

Cargo.lock, Cargo.toml
Ref https://github.com/timberio/vector/issues/2080.
=> chore(dependencies): Upgrade `regex` dependency

Makefile
Currently `make build` produces debug builds. However, users expect it to produce optimized release binaries.
=> chore(setup): Use `--release` Cargo flag in `make build`

docker-compose.yml
The latest `loki` image [breaks](https://circleci.com/gh/timberio/vector/89754) our CI job `test-stable`. I'm pinning the previous version for now, but I'm not sure is it an issue with `loki` itself or we need to update our config file.
=> chore(testing): Pin tag for `loki` Docker image

Cargo.lock
This probably happened during an incorrect merge conflict resolution.
=> chore: Correct Cargo.lock

.github/workflows/test-harness.yml, scripts/version.sh
Closes #1416
This adds a `test-harness.yml` Github Action that automates running the test harness on the current branch. Things left to do:
=> chore(operations): Add test harness GH action

Cargo.lock, Cargo.toml, src/transforms/lua/v2/interop/event.rs, src/transforms/lua/v2/interop/log.rs, src/transforms/lua/v2/interop/metric.rs, src/transforms/lua/v2/interop/mod.rs, src/transforms/lua/v2/interop/util.rs, src/transforms/lua/v2/interop/value.rs, src/transforms/lua/v2/mod.rs, tests/behavior/transforms/lua_v1.toml, tests/behavior/transforms/lua_v2.toml
This PR adds support for both metrics and log events in `lua` support APIv2 in accordance to [RFC 1999](https://github.com/timberio/vector/blob/master/rfcs/2020-03-06-1999-api-extensions-for-lua-transform.md).
The change is not documented because Lua API v2 is not stable yet, so it is not advertised in the documentation.
Closes https://github.com/timberio/vector/issues/1563, closes https://github.com/timberio/vector/issues/1406, and closes https://github.com/timberio/vector/issues/706 (for Lua APIv2).
=> enhancement(lua transform): Support metric events in version 2

.github/checklist.yml
The PR checklist both is pretty noisy which defeats the purpose. This reduces the checks to only important checks that do not happen regularly.
=> chore: Relax PR check list to only fire on important changes

Cargo.lock
This PR updates `bumpalo` dependency in `Cargo.lock`. It was prepared by removing the dependency from `Cargo.lock` and running `cargo check`.
Fixes the error generated by `cargo-deny`.
=> chore(dependencies): Update `bumpalo` dependency in `Cargo.lock`

src/event/merge.rs, src/event/mod.rs, src/event/util/log/insert.rs, src/sources/kafka.rs, src/sources/kubernetes/message_parser.rs, src/sources/splunk_hec.rs, src/test_util.rs, src/transforms/add_fields.rs, src/transforms/coercer.rs, src/transforms/geoip.rs, src/transforms/grok_parser.rs, src/transforms/logfmt_parser.rs, src/transforms/regex_parser.rs, src/transforms/remove_fields.rs, src/transforms/rename_fields.rs, src/transforms/split.rs, src/transforms/tokenizer.rs
Closes #2045, Closes #2046, Closes #2044 
Output a rate limited log on replaced or non-existing fields operated on by `add_fields`, `remove_fields`, or `rename_fields`
=> chore: add_fields, remove_fields, or rename_fields debug log on replaced or non-existing fields

.github/labels.yml, .github/labels.yml.erb, .github/semantic.yml, .meta/domains.toml
This change simplifies our "domains" that are used for labels, blog posts, and now guides. I want a single set of domains that we expose to users, and they should generally be broad. Changes are:
1. blog -> website
2. docs -> website
3. guides -> website
4. marketing -> website
5. platforms -> operations
6. setup -> ux
7. templating -> config
8. testing -> tests (for naming consistency)
9. +ux
=> chore: Simplify domains for labels, etc

src/event/discriminant.rs, src/event/merge.rs, src/event/mod.rs, src/sources/docker.rs, src/test_util.rs, src/transforms/lua/v2/interop/log.rs
This is an internal life quality improvement, allows us to get rid of doing `Event::new_empty_log().into_log()`.
=> chore: Add LogEvent::new

distribution/install.sh
The `get_architecture` function already supports them, so it is enough to add them to the `install_from_archive` function.
=> chore: Support ARM architectures in the install script

scripts/version.sh
The line https://github.com/timberio/vector/blob/f2f9b269d9f9dfe9b1d2af60821711c4c101cdd9/scripts/version.sh#L15 was added in https://github.com/timberio/vector/pull/2028, but it [breaks RPM packaging](https://app.circleci.com/pipelines/github/timberio/vector/6478/workflows/00fb6374-bac5-4d8f-87a4-44a1d63766ce/jobs/91413).
This PR removes it, which fixes RPM builds, but I'm not sure was it added just for debugging, or is it actually necessary for the test harness. If it is used, then this PR can be changed to modify  `package-rpm.sh` to take only the second part of the output produced by `make version`.
=> chore: Disable duplicated version output in `make version`

src/sinks/clickhouse.rs
The `Europe/London` timezone which was used in the integration tests recently switched to
daylight saving time, which caused the integration tests to break.
This PR changes the tests to use `UTC` time instead.
=> chore(tests): Use `UTC` instead of `Europe/London` in ClickHouse tests

rfcs/2020-03-17-2064-event-driven-observability.md
Closes #2064 
[Rendered](https://github.com/timberio/vector/blob/emit-events-rfc/rfcs/2020-03-17-2064-event-driven-observability.md)
=> chore: add event-driven observability rfc

.meta/sinks/loki.toml, website/docs/reference/sinks/loki.md.erb
Fixed:
* missing spaces at toml line breaks
* capitalize Loki where it refers the the product name
* correct "possiblity" typo
=> docs: minor fixes in Loki sink documentation

tests/Makefile
Please double-check me here.  I'm still getting my head around the build process and relying on naive pattern matching at this point.
=> chore(operations): RPM for aarch64 was using armv7

src/main.rs, website/docs/administration/monitoring.md.erb, website/docs/administration/process-management.md.erb
Resolves #1742 
This PR adds an option to pass `-qqq` (with 3 or more `q`'s) via the command line to disable all logs.
This is done by passing `off` as the trace level to the `tracing` crate.
See [EnvFilter](https://docs.rs/tracing-subscriber/0.2.3/tracing_subscriber/filter/struct.EnvFilter.html) and  [LevelFilter](https://docs.rs/tracing-subscriber/0.2.3/tracing_subscriber/filter/struct.LevelFilter.html) to why that works.
Note: Only logs written through the tracing crate are effected. Outputs through `println!` and  `eprintln!` are not effected.
Open questions:
-  Is a change in documentation required?
This is my first code contribution to vector. Feel free to to hint me on the correct formalities regarding PRs in this project.
Signed-off-by: Felix Stegmaier <stegmaier.felix@gmail.com>
=> feat(cli): Add -qqq command line flag to disable logs

website/src/pages/index.js
The redirect in `netlify.toml` doesn't work because the link is being opened without reloading the page.
=> chore(website): Fix link to the Docker platform on the main page

.meta/sinks/gcp_cloud_storage.toml, config/vector.spec.toml, website/docs/reference/sinks/gcp_cloud_storage.md
The [`acl`](https://vector.dev/docs/reference/sinks/gcp_cloud_storage/#acl) configuration option is documented to have no default value. However, in fact Vector sends `projectPrivate` ACL by default.
This PR updates the documentation to make it the actual behavior.
=> docs(gcp_cloud_storage sink): Document default value for `acl`

website/src/components/ConfigExample/index.js
Switches from
```shell
echo '
qwerty
'  > config\vector.toml
```
to
```shell
cat <<-VECTORCFG > config\vector.toml
qwerty
VECTORCFG  
```
The benefit is there's no need to escape quotes anymore.
=> chore(website): Use cat with heredoc instead of echo and quotes

src/sinks/gcp/cloud_storage.rs
@alathon pointed out in the chat that GCS XML API, unlike the JSON one, uses kebab case instead of camel case.
This PR adds that change, although I haven't tested it myself.
=> fix(gcp_cloud_storage sink): Use kebab case for ACL encoding

src/transforms/lua/v2/mod.rs, src/transforms/mod.rs, src/transforms/util/mod.rs, src/transforms/util/runtime_transform.rs
This is an internal change extracting the trait used to define scripted transforms from `lua` module to the `transforms` module. It makes it possible to reuse it in other transforms.
=> chore: Make `RuntimeTransform` trait available for all transforms

.github/workflows/test-harness.yml
The release builds use Rust codegen LTO, but the test harness doesn't enable it. This PR enables it for test harness too.
=> perf(tests): Enable Rust codegen LTO for test harness

src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_logs/request.rs
ref. #1483.
Enforces the 3rd point.
@JeanMertz created the base of the fix, since he needed it. And seeing that it's the one creating most of the issues, let's address this point now, while rest of the points will be in a later PR.
=> enhancement(aws_cloudwatch_logs sink): Sort events by timestamp

src/sources/http.rs, src/sources/logplex.rs, src/sources/util/http.rs
ref #2108 
Wires ShutdownSignal for:
- `http` source
- `logplex` source
=> chore(sources): Wire ShutdownSignal in `trait HttpSource`

Cargo.lock, Cargo.toml, src/list.rs, src/main.rs
Resolves #1750 
This PR updates the cli options for `--log-format` `--color` and `list --format`.
Now all possible values and the default value for each option are shown in the help text.
The changes are visible to the user when running `vector help` `vector help list` `vector -h` or `vector --help`.
The new annotation in structopt requires an upgrade of the used `structopt ` version.
Open Questions:
- Should any documentation be updated?
- Should any tests be updated?
- Is including the ` Cargo.lock` file in the PR the correct workflow?
New help message:
```plain
$ cargo run -- help    
vector 0.9.0 (g9d97e1e x86_64-unknown-linux-gnu 2020-04-11)
USAGE:
vector [FLAGS] [OPTIONS] [SUBCOMMAND]
FLAGS:
-r, --require-healthy    Exit on startup if any sinks fail healthchecks
-d, --dry-run …
```
=> enhancement(cli): Show possible values for --log-format --color and list --format

Makefile
This updates the description of the `package-*` jobs in Makefile, as they require the artifacts produced by `make build-archive`.
=> chore: Clarify dependencies of the `package-*` job in `make help`

src/topology/mod.rs
This allows us to avoid logging messages about shutdown when there is actually no shutdown work to do!
=> fix(topology): Improve topology shutdown logs

src/sinks/util/rusoto.rs
This PR improves our logging of lack of AWS credentials, before we were using the `DefaultCredentialsProvider` from `rusoto` but this set a deadline of 30seconds while our topology sets a hard limit of 10 seconds for a healthcheck. This would cause a poor error when the healthcheck timed out because it could not fetch credentials.
Before 
```
Apr 15 15:04:58.285 ERROR vector::topology::builder: Healthcheck: Failed Reason: deadline has elapsed
```
After
```
Apr 15 15:39:27.456 ERROR vector::topology::builder: Healthcheck: Failed Reason: DescribeLogStreams failed: Couldn't find AWS credentials in environment, credentials file, or IAM role.
```
=> fix(sinks): Reduce credentials fetch timeout

src/transforms/lua/v2/interop/util.rs
Closes https://github.com/timberio/vector/issues/2331.
=> fix(lua transform): Don't require `isdst`, `wday`, `yday` in timestamps

Cargo.lock
This adds a fix for erroneously logging about rate limiting the service and a possible condition where we could be hitting below the rate limit.
=> chore(networking): Bump `tower-limit 0.1.2`

scripts/util/metadata/highlight.rb
This PR changes uses only the filename part of the path to extract dates of the highlights.
It is necessary because otherwise `make generate` gives an error when the base path contains `-` characters.
=> chore: Use only the filename part of the paths to extract dates

src/event/mod.rs, src/transforms/tokenizer.rs
Closes #2314.
This haven't been benchmarked yet, as LTO builds are slow.
=> perf(tokenizer transform): Cache paths for parsed fields

Cargo.lock, lib/file-source/Cargo.toml, lib/file-source/src/file_server.rs, src/sources/file/mod.rs
=> chore(file source): Wire `ShutdownSignal`

src/sources/splunk_hec.rs
Tests of `splunk_hec` source haven't been running. The cause was this line:
```
#[cfg(features = "sinks-splunk_hec")]
```
which should have `feature` and not `features`. 
Because of this they weren't even compiled.
This PR fixes this and updates the test to compile.
Fortunately, all the tests are passing.
=> chore(splunk_hec source): Enable tests

.github/workflows/ci.yml
This change runs the `ci` workflow on pull requests only. I don't see the need to run these checks again on `master`.
=> chore(operations): Run ci workflow on pull requests only

src/shutdown.rs, src/sources/file/mod.rs, src/sources/journald.rs
ref. #2108 
Has basically the same wiring as `file` source.
=> chore(journald source): Wire `ShutdownSignal`

src/sources/kafka.rs, src/sources/prometheus/mod.rs, src/sources/socket/mod.rs, src/sources/socket/unix.rs, src/sources/statsd/mod.rs, src/sources/syslog.rs, src/sources/util/unix.rs
ref. #2108 
Wires `ShutdownSignal` to  
- `kafka` source
- `prometheus` source
- `statsd` source
- `syslog` source
- `socket` source
=> chore(sources): Wire `ShutdownSignal` to multiple sources with `take_until`

src/transforms/lua/v2/interop/util.rs, src/transforms/lua/v2/interop/value.rs, website/docs/reference/transforms/lua.md, website/docs/reference/transforms/lua.md.erb
Add an optional `nanosecond` field to the `FromLua` code to support
sub-second resolution in timestamps.
The default Lua table format for timestamps has an integer seconds
field. There's no sub-second field like milliseconds in the table
timestamp format. This means it's not possible to send timestamps
with sub-second resolution from Lua to Vector using the timestamp
table format alone.
Closes #2332.
=> fix(lua transform): support sub-second timestamp resolution

.github/workflows/ci.yml
Reduce our disk usage on the `test-stable` CI job to try to stabilize the test a bit more. This also turns off LTO and does some other risky stuff, so these binaries should only be used for testing.
If this works out, we should consider applying this across our debug/test pipeline, and far, far away from our release builds.
=> chore(platforms): Optimize binaries in `test-stable` CI to reduce binary sizes

src/sinks/splunk_hec.rs
ref. #2147.
Maps `log_schema.source_type_key` value to `sourcetype`.
=> enhancement(splunk_hec sink): Add `sourcetype`

Cargo.lock, Cargo.toml
I am getting CI failure and it looks like the version didn't get bumped. So I think this is correct?
=> chore: Bump cargo.toml version to `0.10.0`

src/buffers/disk/leveldb_buffer.rs, src/buffers/disk/mod.rs, src/buffers/mod.rs
This pushes all of the leveldb-specific code into its own module and introduces a simple trait for it to hide behind.
The trait is very likely to change in the future, but it captures the existing design well enough to help enable more targeted benchmarks, etc.
The next step is to add some new tests and benchmarks around this interface, which I'm currently working on.
=> chore(buffers): carve a seam around leveldb

.github/workflows/ci.yml, Makefile, scripts/slim-builds.sh
This change optimizes our CI workflow to take advantage of settings that produce slim builds. This is required because the CI machines only have 12gb of disk space, something we were routinely running out of. This should make CI and it's tests much more stable.
Supercedes https://github.com/timberio/vector/pull/2383
=> chore: Optimize CI workflow with slim builds

docker-compose.yml, tests/Makefile
This is the second pull request (after https://github.com/timberio/vector/pull/2450) in a series of pull requests for #2368. This change introduces specific target names to make room for Glibc builds in #2337. Given that we want to preserve MUSL builds we'll need to be more specific with our target names.
cc @a-rodin
=> chore(operations): Use specific target names in Makefile

scripts/docker-compose-run.sh, scripts/run2.sh, tests/Makefile
This change is pull request 3 (after https://github.com/timberio/vector/pull/2451) in a series of pull requests for #2368. This change makes it possible for the `tests/Makefile` to execute local scripts based on the presence of the `USE_CONTAINER` environment variable (default `docker`). We default to `docker` since it is guaranteed to work and the least surprising for first-time contributors. Regular contributors should set `USE_CONTAINER=none` and set up the appropriate dependencies if they prefer.
The process works like the following
* `USE_CONTAINER=docker make generate` -> `docker compose up --build --abort-on-container-exit generate`
* `USE_CONTAINER=none make generate` -> `scripts/generate.rb`
The local script detection uses `find` to locate the appropriate file:
```
FILE=$(find …
```
=> chore(operations): Allow the invocation of local script from the tests/Makefile

Cargo.toml, docker-compose.yml, scripts/test-integration-aws.sh, scripts/test-integration-gcp.sh, src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/transforms/aws_ec2_metadata.rs
This adds `aws-integration-tests` and `gcp-integration-tests` features to align with our `make` targets. It also prevents duplication, removing the need to specify every AWS and GCP service whenever we want to test those clouds.
=> chore(operations): Add aws-integration-tests & gcp-integration-tests feature

.github/workflows/nightly.yml, docker-compose.yml, scripts/build.sh, scripts/package-archive.sh, tests/Makefile
This is pull request 5 (after https://github.com/timberio/vector/pull/2453) in a series of pull requests for #2368. This points the nightly workflow to the `tests/Makefile`. This is the final change to centralize all GH workflows around the `tests/Makefile`. Once this is done we can drop the root `Makefile` and consolidate everything. This also sets the stage for #2337 since well be updating our release process to move to glibc.
cc @a-rodin
=> chore(operations): Point nightly GHA workflow to tests/Makefile

deny.toml
This dependency is only used in a test for our dns server which should
get swapped out very shortly via #2464. This is to unblock CI from
failing.
=> chore(security): Ignore `RUSTSEC-2020-0014`

Cargo.toml, benches/buffering.rs, benches/isolated_buffering.rs
This is a new set of benchmarks that roughly approximates the actual full-topology performance of the disk buffer but are based on a far more minimal interface.
The primary benefit is that we'll be able to evaluate the relative performance of new disk buffer implementations without having to do all the work to integrate them into topology. I've also included two channel implementations as a point of comparison.
One other small change here is to the name of the existing low limit disk buffer benchmark. It previously was a prefix of the non-low-limit benchmark, which made it impossible to run one without the other. This was particularly unfortunate because the low-limit benchmark takes much much longer to run.
=> chore(buffers): add new isolated buffer benchmarks

src/sinks/datadog/metrics.rs
Fixes #2441 
I am having some trouble actually sending metrics to datadog as I am getting a 404. That said, I've verified the healthcheck passes and we are getting the same 404 with the new changes. Since, this is my first time actually using this sink I could totally be doing something wrong so if someone has more experience could get that working that would be super helpful. Beyond that, this conforms to the docs and the healthcheck passes and we don't get any unauthenticated responses.
=> fix(datadog_metrics sink): Use header auth

scripts/test-unit.sh
There are situations when the target-triple is not set, e.g. when calling  
`USE_CONTAINER=none make test-unit`. Since the proper value for `target-triple`
depends on the system architecture, we leave it empty so that `cargo` uses the system default.
=> chore(operations): Fix local unit test execution

Cargo.lock, Cargo.toml, src/sinks/util/rusoto.rs, src/tls/mod.rs, src/tls/settings.rs
This fixes our issues when a user tries to use a sink that needs to use tls to connect to some well known host. This means that the hosts tls identity can be verified by a trusted root cert. Most computers contain them on the system but windows and mac require us to fetch this through their system tls libraries.
Opening this as a draft but it currently works for me, it would be good to get some others testing as well.
cc @bruceg 
Fixes #2256 and #2395
=> fix(networking): Fetch system ca certs via schannel on windows

src/transforms/aws_ec2_metadata.rs
enhancement(aws_ec2_metadata transforms): add instance-type as one more element collected from ec2metadata
Instance-type missing and it is one of the minimal default metadata needed from EC2 instance-level via aws_ec2_metadata transformation.
=> enhancement(aws_ec2_metadata transform): Add `instance-type` field

src/main.rs, src/sources/splunk_hec.rs, src/topology/builder.rs, src/topology/mod.rs, tests/config.rs, tests/topology.rs
Closes #2011.
Refactors the topology reload code to move shutdown procedure before building the new pieces. Also to facilitate that, only the pieces that will be added are built.
One interesting scenario is when we go through:
1. shutdown some of the old pieces
2. fail in building new pieces
3. fail in rebuilding the old shutdown pieces
At this point the topology is consisted only of pieces common to both old and new configuration. This situation is currently resolved by shutting down `vector`.
cc. @binarylogic @LucioFranco
=> fix(config): Shutdown topology pieces before building new ones

src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_logs/request.rs
Closes #1483 
> or older than the retention period of the log group
part of the second constraint I'm unsure in how to deal with it? 
Actually implementing this would somewhat complicate the sink, for a case which would happen rarely. If this isn't added, in the worst case `aws` may drop that batch which would have a limited effect since we are splitting the batches into 24h pieces. And dropping older messages also shouldn't be a problem since there is already a precedent of dropping messages older than 14 days. (EDIT: filtering on 14day should be enough)
=> enhancement(aws_cloudwatch_logs sink): Enforce age requirements

Makefile, scripts/release-s3.sh
Closes #2484.
Note that the verification script uses `wget` instead of `curl` because the latter doesn't support retries on HTTP 404 responses.
=> chore(operations): Add retries to the verification of the release artifacts

scripts/prepare-target-dir.sh
On some platforms like macOS, `mapall` is not available. As a result, running `make check-generate` will fail.
This reverts directory creation to the old behavior of iterating over `DIRS` instead.
@MOZGIII @binarylogic fyi
=> fix(operations): Iterate over target dirs to avoid missing mapall command on macOS

src/main.rs, src/shutdown.rs, src/sources/generator.rs, src/topology/mod.rs
Closes #1702 
Triggers shutdown of Vector if all sources finish, but not during config reload. 
Blocked on #2108 since it depends on all sources using `ShutdownSignal`.
=> enhancement(topology): Shutdown Vector if all sources finish

Cargo.lock
https://www.openssl.org/news/secadv/20200421.txt
=> chore(security): Upgrade openssl to `1.1.1g`

src/sources/stdin.rs
closes #2108 
- the `stdin.lines()` thread won't be stopped until newline has been read. 
- the new `stdin` source would start working in parallel with the old thread which could cause interference between the two.
The simplest way I see to solve this is to rewrite the `stdin.lines()` thread into a stream with `tokio::io::Stdin`.   ~~(EDIT: I'll make an issue for it)~~ (EDIT: we'll implement it here)
@bruceg @LucioFranco What do you think?
=> chore(stdin source): Wire `ShutdownSignal`

.github/workflows/code.yml, Makefile, distribution/kubernetes/README.md, distribution/kubernetes/vector-global.yaml, distribution/kubernetes/vector-namespaced.yaml, scripts/build-docker.sh, scripts/deploy-kubernetes-test.sh, scripts/start-docker-registry.sh, scripts/test-integration-kubernetes.sh
This PR outlines the initial test procedure we agreed upon at #2222.
It only includes minikube tests at CI, and it should be very easy to add EKS or GKE one we set them up.
Closes #2223.
=> chore(operations): Kubernetes test procedure

.meta/supported_versions.toml
Specify the minimal supported Kubernetes version, according to the #2222.
The file location is not set in stone, I'm open to changes.
I think this format is the best fit, since the supported versions aren't really a part of the installation domain.
The proposals at #2222 are conceptual and not concrete - that's by the design of the RFC process. We didn't complete the discussion at #2222, so we can finish it here.
=> chore: Set minimal supported Kubernetes version

src/sinks/humio_logs.rs, src/sinks/splunk_hec.rs
From splunk docs "Format events for HTTP Event Collector" event key
"time" should be formatted as "\<sec>.\<ms>".
https://docs.splunk.com/Documentation/Splunk/8.0.3/Data/FormateventsforHTTPEventCollector
Signed-off-by: Kirill Fomichev <fanatid@ya.ru>
Should resolve #2568
=> fix(splunk_hec sink): Send time in <sec>.<ms> format

.github/workflows/code.yml, scripts/copy-docker-image-to-minikube.sh, scripts/test-integration-kubernetes.sh
This PR introduces special support for uploading images directly to the `minikube` nodes, eliminating the need to go through a docker registry.
=> chore(operations): Copying docker images directly to minikube VMs

src/sinks/clickhouse.rs
Small miss from the clickhouse upgrade
=> chore: remove unused import

src/sources/journald.rs
Fixes the bug of getting
>May 08 11:05:28.428 WARN vector::sources::journald: The units setting is deprecated, use include_units instead
and using `units` even if `include_units` is used. 
ref #2558.
=> fix(journald source): Fix `units`/`include_units` switch 

src/sources/generator.rs
I was working on fixing our CI, and I found out `check-component-features` is supposed to be failing currently: https://github.com/timberio/vector/runs/668802095?check_suite_focus=true
This is my take on working around it. This should work for now, a proper solution can be applied later.
=> chore: Mark GeneratorConfig::repeat with #[allow(dead_code)]

tests/shutdown.rs
Use `localhost` for `prometheus` shutdown test so to avoid the firewall.
=> chore(tests): Use `localhost` for `prometheus` shutdown test

.meta/transforms/regex_parser.toml.erb, benches/bench.rs, config/examples/docs_example.toml, config/examples/file_to_cloudwatch_metrics.toml, config/examples/file_to_prometheus.toml, src/transforms/regex_parser.rs, tests/behavior/transforms/regex_parser.toml, tests/config.rs
This allows to specify multiple regular expressions to be defined
that will be matched on the input using `regex::RegexSet`.
Fixes #2469.
Note that this is a **breaking change**, as it requires all configs to be rewritten
to use `regexes = ["..."]` instead of `regex = "..."`. Alternatively, we could
support both fields in the config; although I think this would lead to confusion down
the road.
- The individual regular expressions are kept in a vector named `regexes`, while
the actual `RegexSet` is called `regexset` in the transform. The reason for keeping both is that
[RegexSet::matches] returns the set of regular expressions that match in the given text.
The set returned contains the index of each regular expression that matches in the given text.
The index is in correspondence with the …
=> enhancement(regex_parser transform): Add RegexSet support to regex

src/buffers/mod.rs
Just started work on #355 and found that if one option set for buffer other options (which have default value) also required what was not expected.
For example such config will be invalid, because require `when_full` (`block` by default):
```toml
[sinks.out.buffer]
type = "disk"
max_size = 1024
```
I also have question about `type` for docs (website), currently `type` is `int` for `max_events` / `max_size`, but `int` can have negative values. Maybe `type` should be changed to `uint` / `usize`?
=> chore(config): Fix default values for buffer

src/transforms/json_parser.rs
Closes #2552 
Warning seems more appropriate here and the log message is already properly rate limited.
=> enhancement(json_parser transform): log parse errors as warnings

Cargo.toml, tests/shutdown.rs
Closes  #2563.
There was a race condition on will the sink or source start first.
=> fix(tests): Remove race between sink and source in shutdown test

lib/file-source/src/file_server.rs, lib/file-source/src/lib.rs, src/sources/file/mod.rs
This PR fixes a bug at the `file_server`, that caused it to close the output channel.
I stumbled upon this while working on k8s integration.
Additionally, it improves the error handling at the `file_server` and file source, such that errors should be easier to track.
~It was introduced at https://github.com/timberio/vector/commit/271bcbd13d81e728b814d1273784147e5647a2b5#diff-55f9c2b436571d015f880127293d295f.~ Apparently, the bug was present even before that.
We might want to backport this fix ~to `0.9`, as that release is affected~ to a yet-to-be-specified set of the past releases. See [UPD3](#upd3).
I'm surprised how we didn't catch it in tests, we should think about improving the tests at the file server to prevent bugs like this in the future.
The problem in the current code is that …
=> fix(file source): Fix the bug with channel closing at file server

src/internal_events/add_fields.rs, src/internal_events/aws_kinesis_streams.rs, src/internal_events/json.rs, src/internal_events/mod.rs, src/internal_events/splunk_hec.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/splunk_hec.rs, src/transforms/add_fields.rs, src/transforms/json_parser.rs
This PR instruments few components with metrics following checklist from #2007 
I've followed initial implementation from #1953 
I have few open questions though:
- Is there a convention for internal events naming? I've got a bit confused. E.g. `ElasticSearchEventReceived` defined for `sink` component, however most internal events define `*Sent` events for sinks and `*Received` events for sources. And since corresponding metric name in most places is `events|bytes_processed`, it's a bit confusing adding metrics for the first time.
- Would it be possible to include component name as metric tag? Since same component type can be used multiple times in the config, it's super useful to be able to distinguish them.
=> feat(internal_metrics source): Instrument few more components with metrics

scripts/package-deb.sh
We need to figure out where this error 141 comes from.
I'll remove this once we finish with debugging, for now I need this in `master` to gather data across various runs.
=> chore: Enable debug for package-deb script

src/async_read.rs, src/lib.rs, src/sinks/util/tcp.rs, src/sources/socket/mod.rs, src/sources/util/tcp.rs, src/sources/util/unix.rs, src/tls/incoming.rs, src/tls/mod.rs, tests/buffering.rs, tests/support/mod.rs
Closes #2604.
Adds `ReadUntil` for `AsyncRead` similar to `TakeUntil` for `Stream`.
This wraps `tcp` and `unix` sockets with `ReadUntil` and `ShutdownSignal`. So once the shutdown starts there will be no more reads from the sockets, but all that have been read will be processed.  
This also fixes `mock` source.
=> fix(sources): Shutdown starting from `tcp` and `unix` sockets 

src/internal_events/tcp.rs
Fixes https://github.com/timberio/vector/issues/2664 by:
* Rate limiting `TCP Connection Error` logs
* Reduces their severity to `INFO` from `WARN` (Issue suggested `DEBUG`, looking for consensus here)
=> chore(vector source): Rate limit TCP connection errors, downgrade their severity

Cargo.toml, docker-compose.yml, src/stream.rs, src/transforms/util/runtime_transform.rs, tests/shutdown.rs
Closes #2654.
`lua` transform wasn't shutting down because it was waiting for the timers stream to end, which wasn't going to happen. 
The fix adds a new structure `WeakSelect` which behaves like `select` but will end if any of it's streams end. Also a test for this case has been added.
=> chore(lua transform): Avoid hanging on timers

src/sinks/influxdb/logs.rs
In result of #2474 and #2637 vector can not be compiled. `Buffer::new` accept `Compression` now instead `bool`.
=> fix(influxdb_logs sink): Fix buffer compression

src/sinks/util/service2.rs
The new auto concurrency limiter will need to be able to see temporary
errors before they are retried. As such, it needs to run before the
Retry layer instead of after it. This micro-patch simply reorders the
standard service layers to that effect, and is separated out to ensure
it isn't the cause of unanticipated problems.
=> chore: Reorder Tower service layers

.github/workflows/code.yml, Makefile, docker-compose.yml, scripts/test-default.sh, src/sources/syslog.rs, src/transforms/aws_ec2_metadata.rs
Closes #2673
Most of `source`, `transform`, and `sink` tests haven't been running in CI or more accurately they aren't tested with `USE_CONTAINER=none`, but are with a container.   
This PR: 
* Adds `test-default` which runs tests in library with `default` feature. 
* Changes `aws-ec2-metadata-integration-tests` feature with  `aws-integration-tests`, since it wasn't being used anywhere else so it wasn't run at all.
* Updates `syslog` tests that were failing.
=> chore(tests): Test with `default` feature in CI

.github/workflows/markdown.yml, .github/workflows/website.yml, rfcs/2020-05-25-2685-dev-workflow-simplification.md
Fixes the failing `check-markdown` job and also moves it into its own workflow. This ensures that it runs when any markdown file changes.
=> chore(operations): Fix check-markdown job

src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/util/http.rs, src/sinks/util/http2.rs, src/sinks/util/service.rs, src/sinks/util/service2.rs, src/sinks/util/sink.rs
Closes #2426
Fix for all `http` sinks that were using `ServiceSink`.
=> chore(sinks): Only log `200`-`299` responses as successful

.meta/transforms/tokenizer.toml.erb, website/docs/reference/transforms/tokenizer.md
In current version (0.9.1), some examples + options are wrong. Just fix docs.
=> docs: Fix wrong example in tokenizer module (version 0.9.1)

Cargo.lock
Closes #2748 
Upstream fix was here: https://github.com/tower-rs/tower/pull/459
=> fix(sinks): upgrade tower-limit to fix rate limiting

src/topology/builder.rs
Made narrowing the cause, #2799, much easier.
=> chore(topology): Log when components finish normally

Cargo.toml, Makefile, src/sinks/aws_cloudwatch_logs/mod.rs, src/transforms/aws_ec2_metadata.rs
Moved from #2777
- Change features dependencies for compiling integration tests
- Change testname filter in Makefile for `test-integration-aws`
- Fix `aws-cloudwatch-logs` integration tests for Template (introduced in https://github.com/timberio/vector/pull/2737)
- Fix test `cloudwatch_insert_out_of_range_timestamp` -- ~but there still question about order https://github.com/timberio/vector/pull/2777#discussion_r439056336 -- which events should be pushed first: oldest or newest?~
=> chore: fix aws integration tests ci

Cargo.lock, Cargo.toml, src/sinks/gcp/mod.rs
Part of #2118 
Thread blocking on `goauth::get_token` can be removed on chaning sink build to async.
=> chore: update goauth to new futures

src/sinks/humio_logs.rs, src/sinks/splunk_hec.rs
Closes #2749 
I did not found that HEC accept string, all examples show only float. I think it's ok send float even if will be encoded as `1591976882.3333`.
I set threshold to `0.001` and get on first run (18ms diff):
```rust
thread 'sinks::humio_logs::tests::humio_valid_time_field' panicked at 'hec_event.time = 1591976882.733, now = 1591976882.751', src/sinks/humio_logs.rs:115:9
```
so I think problem in slow CPU on CI run. Threshold bumped to 200ms. Also added assert message, so if test will fail again it should be clear why.
=> chore(humio_logs sink): improve time validation in tests

benches/isolated_buffering.rs, src/runtime.rs, src/sinks/kafka.rs, src/sinks/socket.rs, src/sinks/util/tcp.rs, src/topology/mod.rs, src/validate.rs, tests/tcp.rs
This changes add TLS layer to tcp stream detects disconnect test.
Signed-off-by: Kirill Fomichev <fanatid@ya.ru>
Not sure that I interpreted issue #2431 correct, but this add TLS layer.
- Because internal TlsListener use futures01 I changed test to futures01, not perfect, but never work with it and not obvious as std futures.
- On socket shutdown: is it ok make proper shutdown with SslStream or should be shutdown by TcpStream? (currently SslStream shutdown)
- ~Do not know how filter `HandshakeNotReady` error.~
=> chore(socket sink): Test stream disconnect with tls

src/topology/mod.rs
Closes #2775 
Removes the checks and separates `start` step into `connect` and `spawn`.
=> chore(topology): Allow disconnected components, and split `start` step

src/sinks/loki.rs, src/topology/mod.rs
Ref. #2778
Makes `encoding` optional and enhances `Unhandled error` message.
=> chore(loki sink): Make encoding optional

Cargo.lock, Cargo.toml, src/dns.rs, src/generate.rs, src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_s3.rs, src/sinks/splunk_hec.rs, src/sinks/util/http.rs, src/sinks/util/tcp.rs, src/sinks/util/udp.rs, src/sources/socket/mod.rs, src/topology/builder.rs, src/topology/config/mod.rs, src/topology/mod.rs, tests/tcp.rs
Closes #2635.
cc. @lukesteensen
=> chore(networking)!: Remove custom DNS resolution

src/sinks/util/buffer/json.rs
By using to_raw_value it's possible to skip parsing JSON again
=> enhancement(sinks): Use to_raw_value instead of to_string in JsonArrayBuffer 

.meta/sinks/aws_s3.toml.erb, config/vector.spec.toml, src/sinks/aws_s3.rs, website/docs/reference/sinks/aws_s3.md
Closes #2769 and #2773 
- `content_type` is `text/x-log` by default, but can be redefined
- `content_encoding` calculated from `compression` option by default, but can be redefined
cc @tyrken
=> enhancement(aws_s3 sink): Add content options

Cargo.lock, lib/file-source/Cargo.toml, src/event/mod.rs, src/sources/file/line_agg.rs, src/sources/file/mod.rs
Do not like that for creating `BytesMut` from `Bytes` data need to be copied, but looks like there is no way do this in bytes:0.5 without it.
=> chore(dependencies): file-source bytes update

src/sinks/socket.rs
`tcp_stream_detects_disconnect` test is commented as testing for a case when a proper server side write side shutdown happens, which wasn't been done in the test. This PR changes that. 
This should fix it's flakines.
=> chore(tests): Shutdown write side only in test `tcp_stream_detects_disconnect`

.github/workflows/tests.yml, Makefile, scripts/environment/definition.nix, shell.nix
Currently Kafka tests not compiled because `rdkafka` feature required.
Also see #2832 
Edit: should fail without #2832 (will rebase after merge).
=> chore(kafka sink): Fix command for integration tests

src/test_util.rs, tests/buffering.rs
This PR does three things:
* Resolves races exclusive to `buffering` tests.
* Moves around `thread::sleep` in `buffering` tests, reducing waiting in total.
* Splits `crate::test_util::CountReceiver::wait` method into `wait` and `cancel`. All of the usages of this method were having a race as they were expecting that the method would wait for the `tcp` channel to close, which wasn't the case. Instead the method was canceling the channel which caused a race.
=> chore(tests): Adjust buffering tests

Cargo.lock, Cargo.toml
Closes #2455. 
We don't have `RUSTSEC-2019-0031` if we don't depend on those crates, so this PR removes them. They became unnecessary with #2635.
=> chore(dependencies): Remove `trust-dns` dependecies

.meta/_partials/fields/_conditions_options.toml.erb, config/vector.spec.toml, website/docs/reference/tests.md, website/docs/reference/transforms/filter.md, website/docs/reference/transforms/swimlanes.md
Noticed I messed up the spaces in the docs I added for #2745 
In the website there wasn't any space between sentences, e.g.
> Check whether a fields contents exactly matches the value specified.This may be a single string or a list of strings, in which case this evaluates to true if any of the list matches.
=> docs: Adding spaces to condition docs

Cargo.lock, Cargo.toml, lib/codec/Cargo.toml
While `vector` itself do not use `native-tls` crate still used in dependencies...
```
$ cargo tree -i -p native-tls
native-tls v0.2.3
├── hyper-tls v0.3.2
│   └── reqwest v0.9.24
│       └── vector v0.10.0 (/home/kirill/projects/vector)
├── hyper-tls v0.4.1
│   ├── reqwest v0.10.6
│   │   └── goauth v0.7.1
│   │       └── vector v0.10.0 (/home/kirill/projects/vector)
│   └── rusoto_core v0.44.0
│       ├── rusoto_cloudwatch v0.44.0
│       │   └── vector v0.10.0 (/home/kirill/projects/vector)
│       ├── rusoto_firehose v0.44.0
│       │   └── vector v0.10.0 (/home/kirill/projects/vector)
│       ├── rusoto_kinesis v0.44.0
│       │   └── vector v0.10.0 (/home/kirill/projects/vector)
│       ├── rusoto_logs v0.44.0
│       │   └── vector v0.10.0 (/home/kirill/projects/vector)
│       ├── …
```
=> chore(dependencies): remove native-tls

Cargo.toml, docker-compose.yml, scripts/ci-docker-images/builder-x86_64-unknown-linux-gnu/Dockerfile
We cannot support sasl on musl yet.
It requires secure_getenv and you can see musl only recently got this: https://www.openwall.com/lists/musl/2019/05/28/3, leads to https://git.musl-libc.org/cgit/musl/commit/?id=7844ecb590893f8344324837956718001402d297, which seems to be released but I can't seem to link to?
It should be part 1.1.24: https://git.musl-libc.org/cgit/musl/commit/?id=ea9525c8bcf6170df59364c4bcd616de1acf8703, which is what we package https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/musl/default.nix
We're revisiting this once we see 1.1.25 in nixpkgs.
=> chore(kafka sink): Fixup sasl related knobs to allow releases on musl

lib/file-source/src/file_server.rs
This PR implements first-line-checksum fingerprinter outlined at https://github.com/timberio/vector/issues/2890.
It is a concrete implementation proposal, and also a proof of concept. Tests ensure that we achieve the desired behavior and also serve as the illustration for the properties of the solution.
---
One of the questionable moments is filling the buffer with `0` before leaving the match arm. We could alternatively pass the shorter slice to the `checksum_ecma`, but I'm not sure what we'd prefer here.
=> chore(file source): Add Fingerprinter::FirstLineChecksum

Cargo.lock, Cargo.toml, src/sinks/aws_kinesis_firehose.rs, src/sinks/clickhouse.rs, src/sinks/elasticsearch.rs, src/sinks/gcp/mod.rs, src/sinks/gcp/pubsub.rs, src/sinks/http.rs, src/sinks/influxdb/logs.rs, src/sinks/influxdb/metrics.rs, src/sinks/influxdb/mod.rs, src/sinks/loki.rs, src/sinks/splunk_hec.rs, src/sinks/util/http.rs, src/sources/docker.rs, src/sources/http.rs, src/sources/logplex.rs, src/sources/splunk_hec.rs
- Move `reqwest` to `dev-dependencies`
- Update `reqwest`
- Remove old `http:0.1` crate
- Remove old `headers:0.2` crate
Close #2782
=>  enhancement(dependencies): move reqwest to dev-dependencies 

.meta/_partials/fields/_kafka_options.toml.erb, Cargo.toml, docker-compose.yml, scripts/ci-docker-images/builder-x86_64-unknown-linux-gnu/Dockerfile, website/docs/reference/sinks/kafka.md, website/docs/reference/sources/kafka.md
Revert part of https://github.com/timberio/vector/pull/2915.
`sasl` is problematic right now. Problems with building statically linked, problems with using new not published vendored feature in rdkafka-sys (win32 not supported yet). `sasl` still will be available, but users will need build binaries themselves.
This PR close #2928 and #2929. After landing we need create issue for tracking.
=> chore(kafka sink): disable sasl feature

.meta/sources/kafka.toml.erb, src/sinks/kafka.rs, src/sources/kafka.rs, website/docs/reference/sources/kafka.md
Closes  #2700 
Extracts timestamp from event in `kafka` source and sets it as timestamp in emitted kafka message from `kafka` sink. Sink will behave like this for all timestamps, not only for those extracted in `kafka` source.
=> enhancement(kafka source): Extract timestamp from event

.github/workflows/release.yml
This PR goes ahead and creates an entirely new workflow for releases that only trigger on release tags. It seemed to be intended from https://github.com/timberio/vector/issues/2797 and I think that it makes sense.
In the future we can adopt more distinction between "Nightly jobs, such as audits/fuzzing/prop-testing/benching" and "release tasks, such as publishing artifacts, images, releases, and binaries". For now, they are coarsely similar.
This PR is **incomplete** as it depends on a `BRADY_BOT_TOKEN` set in the https://github.com/timberio/vector/settings/secrets to publish to the homebrew tap.
Please note I haven't tested this, I wasn't able to find any sort of check/dry run options and I'm not entirely comfortable with just running random release scripts and seeing what happens.
=> chore(operations): Move over homebrew/s3 release jobs

distribution/docker/alpine/Dockerfile, distribution/docker/debian/Dockerfile
This should help us track issues with bad docker images early.
=> chore(operations): Add smoke tests to docker images

.dependabot/config.yml, .github/labels.yml
Continuing on #2781 #2980 , I didn't like the shortened label names, this reverts us to the longer label names and the short PR prefixes.
=> chore(deps): Fix dependency label to be longer again.

scripts/ci-docker-images/builder-x86_64-unknown-linux-gnu/Dockerfile
Similar to #2974, this allows us to find problems with builder docker images early.
=> chore(operations): Add smoke test for cmark-gfm at builder

scripts/ci-docker-images/builder-x86_64-unknown-linux-gnu/Dockerfile
This solves the issue that appeared when we switched from debian to centos base at builders.
Our script for building `.deb` packages expects Perl `rename` command, but centos uses the one from `util-linux`, that can't do what we want from it.
=> fix(operations): Use perl rename at builder

Makefile
Corrects release task script invocations so that they can actually work.
=> chore(operations): Fixup release script formats

.meta/sinks/aws_s3.toml.erb, .meta/sinks/kafka.toml.erb, .meta/sinks/pulsar.toml.erb, .meta/sinks/splunk_hec.toml.erb, Cargo.lock, Cargo.toml, config/vector.spec.toml, src/buffers/mod.rs, src/sinks/pulsar.rs, website/docs/reference/sinks/aws_s3.md, website/docs/reference/sinks/kafka.md, website/docs/reference/sinks/pulsar.md, website/docs/reference/sinks/splunk_hec.md, website/metadata.js
Close #2948 
Related with #2687 
Unfortunately, it's not possible to update `pulsar` right now. Created `Pulsar` object depends on `Runtime` in which it was created and when runtime dropped objects related to this runtime dropped too, this cause errors if functions which use created object will be called. This should be unblocked by #2938.
=> chore(pulsar sink): update to 1.0.0-alpha-2

.meta/options.toml, README.md, README.md.erb, config/vector.spec.toml, rfcs/2020-04-15-2341-wasm-plugins.md, website/docs/reference/global-options.md
This cleans up all the website docs in prep for #2961
=> docs: Remove the dns-server options from docs

Cargo.lock
There was few pull requests where I was need merge lock file due to merge conflict. Looks like 2 lines were lost.
Will merge after CI pass.
=> fix(deps): update crates in lock file after merges

src/lib.rs
These 3 don't currently trigger any clippy warnings, so there doesn't
seem to be much point in keeping clippy from checking them.
=> chore: Drop 3 more clippy exclusions

src/topology/mod.rs
=> chore(tests): Delete `topology::reload_tests::topology_reuse_old_port`

src/sinks/clickhouse.rs, src/sinks/datadog/metrics.rs, src/sinks/elasticsearch.rs, src/sinks/gcp/pubsub.rs, src/sinks/gcp/stackdriver_logs.rs, src/sinks/honeycomb.rs, src/sinks/http.rs, src/sinks/influxdb/logs.rs, src/sinks/influxdb/metrics.rs, src/sinks/influxdb/mod.rs, src/sinks/logdna.rs, src/sinks/loki.rs, src/sinks/splunk_hec.rs, src/sinks/util/http.rs
Ref #2237 
Moves building of `HttpClient` from two locations, one for sink and one for healthcheck, to `build` method.
There are two sinks that had different behavior for sink and healthcheck:
- `honeycomb`
- `logdna`
In both cases healthchecks were using `TLS`, but sinks weren't. This PR changes that to not using `TLS`.
=> chore(sinks): Build `HttpClient` once

src/sinks/aws_s3.rs, src/sinks/http.rs, src/sinks/new_relic_logs.rs, src/sinks/util/rusoto.rs, src/sinks/util/test.rs, src/sources/kafka.rs, src/sources/logplex.rs, src/sources/splunk_hec.rs, src/sources/stdin.rs
While checked `bytes` docs, found that [method reader](https://docs.rs/bytes/0.5.5/bytes/buf/ext/trait.BufExt.html#method.reader) exists, so we do not need [std::io::Cursor](https://doc.rust-lang.org/std/io/struct.Cursor.html) in few places.
=> chore: reduce std::io::Cursor usage

Makefile
Some of our integration tests don't invoke the environment if they are asked to.
This fixes that. Related to #1644
=> chore(operations): Fixup integration test invocations

src/cli.rs
Closes #3007 
Changes default logging level for `generate` command from `info` to `warn`.
=> fix(cli): Cleanup `generate` command

src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs
Ref. #2237 
Moves building of various `aws` sink clients from two locations, one for sink and one for healthcheck, to build method.
=> chore(sinks): Build `aws` sinks clients only once

Cargo.lock, Cargo.toml, src/sources/kafka.rs
Close #2972 
- update `rdkafka` crate
- remove `owning_ref` crate
- remove extra clones
- add more async code
- fix `kafka-integration-tests` feature (before part of tests was not compiled for integration tests)
=> chore(kafka source): remove owning_ref

.rustfmt.toml
Using default values because the base rustfmt should be used. The perceived advantage is that
auto code formatters in contributors IDEs would more readily recognize that rustfmt should be
used over some alternative formatter.
Resolves #507
Signed-off-by: Harold Dost <h.dost@criteo.com>
=> chore: Add .rustfmt.toml to assist IDE formatters.

src/main.rs, src/sinks/gcp/cloud_storage.rs, src/sinks/gcp/mod.rs, src/sinks/gcp/pubsub.rs, src/sinks/gcp/stackdriver_logs.rs, src/sinks/pulsar.rs, src/topology/builder.rs, src/topology/config/mod.rs, src/topology/mod.rs, src/validate.rs, tests/config.rs
Closes #2687 
Closes #3019 
This adds a new `build_async` fn to `SinkConfig` that can be used in place of `build`. This was a smaller change than making `build` itself async and has the advantage of not requiring `async-trait` anywhere it's not needed, which improves error reporting.
We can follow up this PR and either add a default implementation of `build` or split the sync version into a subtrait. I don't have a strong opinion there so decided to punt for now.
=> chore(sinks): add SinkConfig::build_async

src/transforms/reduce/merge_strategy.rs, src/transforms/reduce/mod.rs
Closes #3074 
Two bugs fixed here:
1. Using `all_fields` instead of `into_iter` gaves us paths instead of keys, so thing like arrays and objects would not get strategized correctly.
2. Special casing arrays when constructing the `ArrayMerger` meant that the initial array would be flattened in the result but subsequent additions would not.
=> fix(reduce transform): improve array handling

.meta/_partials/fields/_kafka_options.toml.erb, Cargo.lock, Cargo.toml, config/vector.spec.toml, docker-compose.yml, scripts/environment/bootstrap-ubuntu-20.04.sh, website/docs/reference/sinks/kafka.md, website/docs/reference/sources/kafka.md
=> chore(deps): Reenable sasl

src/internal_events/elasticsearch.rs, src/sinks/elasticsearch.rs
It was pointed out in #2973 that we're logging an awful lot in the ES sink. The current setup issues an `info` log every time it encodes an event, which very much seems like overkill.
This moves that log down to trace level, puts it behind the event emit, and cleans it up a bit.
=> fix(elasticsearch sink): stop logging every received event

distribution/docker/debian/Dockerfile
Fix my mistake in #3129
Buster is stable, not sid.
=> chore(operations): Debian buster is stable, not sid

src/shutdown.rs
Ref.  #2945.
Removes direct dependency on `tokio01` in `src/shutdown.rs`.
=> chore: Remove tokio 0.1 from shutdown

src/lib.rs
In #3141 we were too fast and clippy lints were failing. This fixes them.
=> chore(operations): Fixup clippy issues from 1.44 rollback

src/topology/builder.rs, src/topology/config/mod.rs, src/transforms/aws_ec2_metadata.rs
Closes #2932 
Closes #2639 
Pretty straightforward! This was the only transform off the top of my head that needed an async build, but we can shift others if needed as well.
=> chore(transforms): add TransformConfig::build_async

.github/workflows/release.yml, Cargo.lock, Cargo.toml
Fixed the `make check-version` check failing
=> chore(operations): Bump vector to 0.11.0 to fix make check-version

Makefile
Fixes the `make version` command from outputting content that would break the release process. Closes #3152
=> chore(operations): Fixup version invocation to not have info

src/topology/builder.rs, src/topology/config/mod.rs
Closes #2933 
This one is unused for the time being, but added for consistency. I'll open an issue to align all of these once we're further along.
=> chore(sources): add SourceConfig::build_async

.dependabot/config.yml
Dependabot complains a lot about this so it's simple to fix: https://github.com/timberio/vector/pull/3116#issuecomment-660954930
=> chore(operations): teach dependabot the right label

.github/workflows/release.yml
Resolve the newest issues present in https://github.com/timberio/vector/actions/runs/178842534.
This is resolved by using a newer version of ubuntu that is bootstraped with our env.
This is solved by renaming `PASS_VERSION` to `VERSION`.
(Reminder we can't test these very well outside of actually trying to do a release)
=> chore(operations): Resolve newest release issues

.github/workflows/tests.yml
This will be fixed by #2702, but until then let's make tests pass on `master` .
=> chore(tests): Temporarily disable k8s integration tests

.github/workflows/release.yml, scripts/environment/bootstrap-ubuntu-20.04.sh, scripts/release-github.rb
This didn't slip into the other PR #3165 :(
Also provisions the https://github.com/timberio/grease tool in our bootstrappers and updates the `release-homebrew` task to use it.
=> chore(operations): Fix release-github and release-homebrew

website/docs/reference/field-path-notation.md
Quick spelling fix on the field path notation docs page.
=> fix(docs): Spelling fix on field path docs

benches/batch.rs, src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/clickhouse.rs, src/sinks/datadog/metrics.rs, src/sinks/elasticsearch.rs, src/sinks/gcp/cloud_storage.rs, src/sinks/gcp/pubsub.rs, src/sinks/gcp/stackdriver_logs.rs, src/sinks/honeycomb.rs, src/sinks/http.rs, src/sinks/influxdb/logs.rs, src/sinks/influxdb/metrics.rs, src/sinks/logdna.rs, src/sinks/loki.rs, src/sinks/splunk_hec.rs, src/sinks/statsd.rs, src/sinks/util/batch.rs, src/sinks/util/buffer/json.rs, src/sinks/util/buffer/metrics.rs, src/sinks/util/buffer/mod.rs, src/sinks/util/buffer/partition.rs, src/sinks/util/buffer/vec.rs, src/sinks/util/buffer/vec2.rs, src/sinks/util/sink.rs
Closes #3024 
This doesn't directly merge batch settings parsing with later handling, but ties the two together using type inference, such that the correct handler is used automatically.
=> chore(sinks): Batch buffer size rework

src/lib.rs, src/main.rs, src/signal.rs
Closes #1383 
With moving signal code "slight" updates to usage of `futures01` in handling code was applied. We can split this update out to a separate PR if needed, it was too tempting not to collapse all of the `select`,`compat`,`match`, etc., into a simpler form.
=> chore: Moves platform-specific signal code out of `main`

src/main.rs
Spotted by @lukesteensen in #3185 `cargo fmt` is confused in `select` macro so this PR hand formats it. 
I'll merge this immediately.
=> chore: Hand format `main`

rfcs/_YYYY-MM-DD-issue#-title.md
This change improves the RFC template:
1. Added a "Scope" section to help defined boundaries of the RFC up front. Inspired by [Google design docs](https://www.industrialempathy.com/posts/design-docs-at-google/).
2. Clarified what should be in the "Motivation" section.
3. Consolidated the "Guide-level" and "Doc-level" proposal to just "Proposal".
4. Moved the "Rationale" section after the proposal, where it flows better.
5. Improved the other descriptions based on the [Alloy RFC template](https://github.com/timberio/alloy-planning/blob/master/rfcs/_YYYY-MM-DD-issue%23-title.md), which I think did a better job.
=> chore: Update RFC template

src/transforms/regex_parser.rs
Previously, was incorrectly mapping the capture indexes of the matched
pattern across the capture groups of all patterns so that, with
something like:
```toml
[sources.in]
type = "stdin"
[transforms.regex]
type = "regex_parser"
inputs = ["in"]
patterns = [
'^blah \((?P<socket_code>[0-9]+): (?:[^\)]+)\) while (?P<timeout_while>.)',
"^notblah (?P<close_while>.+)$",
]
[sinks.out]
inputs = ["regex"]
type = "console"
encoding.codec = "json"
```
And a line of:
```
notblah something
```
Would end up setting both the `socket_code` and `close_while` fields:
```json
{
"close_while": "something",
"host": "jesse-thinkpad",
"socket_code": "something",
"source_type": "stdin",
"timestamp": "2020-07-22T19:30:12.647060371Z"
}
```
This change simply updates `RegexParser.capture_names` to also be a `Vec` of …
=> fix(regex_parser transform): Correctly assign capture group fields

scripts/environment/bootstrap-ubuntu-20.04.sh
We didn't catch this on CI because the docker images we're using differ slightly from the CI base images. (#3125 will improve this!)
=> chore(operations): Use curl to get grease

scripts/environment/bootstrap-ubuntu-20.04.sh
Signed-off-by: Marko Karppinen <marko@richie.fi>
bootstrap-ubuntu-20.04.sh uses wget but it's missing:
```
wget https://github.com/timberio/grease/releases/download/v1.0.1/grease-1.0.1-linux-amd64.tar.gz
./scripts/environment/bootstrap-ubuntu-20.04.sh: line 28: wget: command not found
The command '/bin/sh -c ./scripts/environment/bootstrap-ubuntu-20.04.sh' returned a non-zero code: 127
make: *** [environment] Error 127
```
Add it in.
Fixes: #3231
=> chore: fix missing `wget` in `make environment`

.github/workflows/lints.yml, .github/workflows/tests.yml, scripts/environment/bootstrap-macos-10.sh
It comes preinstalled with 2.6 which is below our Gemfile requirement in
scripts/.
https://github.com/actions/virtual-environments/blob/3d7f73608f6c438ef990a591dee574e90de9dce1/images/macos/macos-10.15-Readme.md
This fixes the mac related GH Actions checks.
Fixes #3167 
=> chore: Install Ruby on OSX CI runner

.meta/transforms/regex_parser.toml.erb, config/vector.spec.toml, website/docs/reference/transforms/regex_parser.md, website/metadata.js
It was being rendered in the docs as having "s around the list.
Discovered this while looking at https://gitter.im/timberio-vector/community?at=5f2214f625cae90e6d8c6f67
=> docs(regex_parser transform): Fix quoting of patterns in example

src/internal_events/tcp.rs
Noticed this while worked on #3188
=> chore: change level of TCP events

src/sources/file/line_agg.rs
=> fix(file source): correct an error with line aggregation in `continue_through` and `halt_before`

src/lib.rs, src/pipeline.rs, src/sources/docker.rs, src/sources/file/mod.rs, src/sources/generator.rs, src/sources/http.rs, src/sources/internal_metrics.rs, src/sources/journald.rs, src/sources/kafka.rs, src/sources/kubernetes_logs/mod.rs, src/sources/logplex.rs, src/sources/prometheus/mod.rs, src/sources/socket/mod.rs, src/sources/socket/udp.rs, src/sources/socket/unix.rs, src/sources/splunk_hec.rs, src/sources/statsd/mod.rs, src/sources/stdin.rs, src/sources/syslog.rs, src/sources/util/http.rs, src/sources/util/tcp.rs, src/sources/util/unix.rs, src/sources/vector.rs, src/topology/builder.rs, src/topology/config/mod.rs, src/topology/mod.rs, tests/crash.rs, tests/support/mod.rs
Closes #2935
This is just a mechanical change to introduce pipelines first as a wrapper around the old `Sender`s. Now that we have the wrapper in place, we can get going on some more interesting changes:
1. Embed transforms in pipelines
2. Add APIs for partitioning
3. Replace old channels with new ones
4. etc, etc
=> chore(sources): introduce Pipeline type

.github/workflows/test-harness.yml
This defaults the test harness output to compare to the `nightly/latest` version. The only outstanding issue here is the use `-c default` since this is not always the case. For example, https://github.com/timberio/vector/pull/2145#issuecomment-607508062 run a test with the `-c big-vms` flag which also needs to be passed to the `bin/compare` command.
=> chore(operations): Compare test harness output with nightly/latest

tests/buffering.rs
Should fix `test_reclaim_disk_space` flakiness. 
It doesn't fail on my computer, but does start to fail in vm setup, like CI, and seams to be OS sensitive, so I'm guessing the cause is the known race with writing to file/hard drive, while OS caching/paging is interfering.
=> chore(tests): Increase wait in `test_reclaim_disk_space`

Cargo.lock
Fixes #3311.
This should be sufficient to fix through `cargo update --package enum-ordinalize --package cidr-utils`.
(@jszwedko I am away monday, could you test this and push it through?)
=> chore(operations): Fixup armv7 musl build

.meta/sinks/splunk_hec.toml.erb, Makefile, src/sinks/splunk_hec.rs
This change removes the logic introduced in #2318 as we discovered it was causing issues with the `humio` sink as `humio` uses the sent source type to parse the incoming message. For example, if we send `syslog` as the `sourcetype` it attempts to parse our JSON payload as a syslog formatted message (details https://github.com/timberio/vector/issues/3082#issuecomment-665148156).
The first commit is just getting the splunk tests running again. The second commit is the change.
I'll open a follow up to add this configuration to the `humio` sink as well.
Fixes https://github.com/timberio/vector/issues/3250
=> fix(splunk_hec sink)!: Make sourcetype explicit on Splunk sink

.meta/sinks/humio_logs.toml.erb, src/sinks/humio_logs.rs
Targeting #3297  
This adds a configuration option to tell Humio what the type is of the
events so that it can parse them accordingly.
I think this usually won't be needed, but could be useful if the `text`
encoding is used.
Closes https://github.com/timberio/vector/issues/3082
=> feat(humio_logs sink): Allow configuration of type field

Cargo.toml
Fix https://github.com/timberio/vector/pull/3222
=> chore(deps): bump url to 2.1.1

Cargo.lock, src/sinks/util/retries.rs, src/sinks/util/retries2.rs
We are dropping the requests in these places so it should be `error!`, not `warn!`.
=> chore(observability): Increase serverity of logs

src/sources/splunk_hec.rs
#3275 introduced `Pipeline` which has less of a capacity than the previously used channel which caused a deadlock in tests that were depending on that capacity being larger than a certain size.
This PR removes this dependency.
=> chore(tests): Fix `splunk_hec` source tests

src/sinks/socket.rs, src/sinks/util/unix.rs, src/test_util.rs, tests/crash.rs, tests/tcp.rs
There was a race in some of our usages of `CountReceiver`, and there still is (explained later). The race was happening between `CountReceiver` establishing first connection and:
* waiting on it
* shutting down `topology`
If connection is established before both of them, everything is fine, if not, the events weren't being collected so the tests failed.
`CountReceiver` now exposes a way to wait for the first connection which tests can use to avoid the race. This theoretically doesn't remove the race entirely since we don't sync for other connections, but our usage of it is for one connection only so this fixes the race in practice. This behavior is commented in code.
First found while examining flaky `merge_and_fork` test, but was affecting dozens of tests. They were determined to be …
=> chore(tests): Fix race in `CountReceiver`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I noticed that it wasn't providing the issue templates when creating
a new issue. I think this is probably because the front-matter was not
valid YAML.
I also added in the additional config options that appear when using the
Github UI to create an issue template.
=> chore: Fix issue templates front-matter

.meta/sinks/splunk_hec.toml.erb, src/internal_events/splunk_hec.rs, src/sinks/splunk_hec.rs
Allows for setting the sourcetype dynamically based on an event field.
Related: #3251 
=> feat(splunk_hec sink): Make sourcetype templatable

Cargo.lock, Cargo.toml, src/sinks/datadog/logs.rs, src/sinks/papertrail.rs, src/sinks/socket.rs, src/sinks/util/tcp.rs, src/sinks/vector.rs, src/sources/http.rs, src/sources/logplex.rs, src/sources/socket/mod.rs, src/sources/splunk_hec.rs, src/sources/util/http.rs, src/sources/util/tcp.rs, src/tls/incoming.rs, src/tls/maybe_tls.rs, src/tls/mod.rs, src/tls/outgoing.rs, src/tls/settings.rs, tests/syslog.rs, tests/tcp.rs
Looks like #3188 hang up some tests in CI, I can not figure out right now what's wrong, so decide revert changes.
Part of CI pass in my fork: https://github.com/fanatid/vector/runs/946240422?check_suite_focus=true
Need green CI before merge.
=> chore: revert tokio in tls update (#3188)

src/sinks/elasticsearch.rs
This test fails to fail unless `request.in_flight_limit > 1`. It appears
to be caused by a weird issue with elasticsearch itself. By "breaking"
the data by adding a reserved field to the event, we can cause events to
reliably fail, making the test reliable when `in_flight_limit = 1`.
Closes #3303
=> chore(elasticsearch sink): Fix insert_events_with_failure test

.github/workflows/lints.yml
`make check-version` requires git history.
Appears to have broken by https://github.com/timberio/vector/pull/3348
when the CI checks were condensed as the old `make check-version` check
used actions/checkout@v1
Example failure:
```
Run make check-version
./scripts/check-version.rb
/var/lib/gems/2.7.0/gems/git-1.7.0/lib/git/lib.rb:989:in `command': git '--git-dir=/home/runner/work/vector/vector/.git' '--work-tree=/home/runner/work/vector/vector' '-c' 'color.ui=false' describe '--tags' '--abbrev=0' 'HEAD'  2>&1:fatal: No names found, cannot describe anything. (Git::GitExecuteError)
from /var/lib/gems/2.7.0/gems/git-1.7.0/lib/git/lib.rb:126:in `describe'
from /var/lib/gems/2.7.0/gems/git-1.7.0/lib/git/base.rb:271:in `describe'
from ./scripts/check-version.rb:41:in `<main>'
make: *** …
```
=> chore: checkout full repo for lint checks

.meta/sinks/humio_logs.toml.erb, src/sinks/humio_logs.rs
Targeting https://github.com/timberio/vector/pull/3327
This exposes the added `source` config from the Splunk HEC sink to the
Humio sink. It maps to `@source` in Humio. If unset, it is simply empty
in Humio.
https://docs.humio.com/integrations/data-shippers/hec/
Related to https://github.com/timberio/vector/issues/3251
=> enhancement(humio_logs sink): Add source configuration to Humio sink

.github/workflows/tests.yml
It turns out the paths were not being honored for pull requests. We must specify paths for both triggers. Unfortunately, Github Actions does not support YAML anchors.
=> chore(operations): Enforce paths for pull requests in the test workflow

src/sources/file/line_agg.rs, src/sources/file/mod.rs
This is a minor refactoring of the `sources::file::line_agg`, in preparation to extract it for reuse among other sources.
- Extracted logic into a reusable piece (experiments have shown that this will be very useful for some implementation variants).
- Switched to futures 0.3; an attempt to rewrite the implementation to `async_stream` was made, but it turned out to be more complicated than the raw poll-based implementation. The poll-based approach is easier to reason about. This isn't definite though, and possibly another attempt will be more successful.
=> chore: Refactor line_agg

rfcs/2020-08-04.3325.remap-v2.md
Closes #3325 
[Rendered](https://github.com/timberio/vector/blob/remap-v2-rfc/rfcs/2020-08-04.3325.remap-v2.md)
=> chore: Remap v2 RFC

src/topology/mod.rs
Ref. #3035
Test is only failing on Windows, so we can re introduce it and enable it for the rest.
=> chore(tests): Re add `topology_reuse_old_port` test for `unix`

.github/workflows/nightly.yml
Useful for testing changes to it without waiting.
=> chore(ci): allow nightly build to be manually triggered

distribution/systemd/vector.service
Instead, just rely on the default configuration the operator has
configured systemd with (typically journald). I think this is less
suprising than automatically forwarding via syslog not the least of
which because the host system may not be running a syslog daemon.
Users can still configure this via
a /etc/systemd/system/vector/override.conf file. I think the base
configuration should be as simple as possible.
Related to https://github.com/timberio/vector/issues/3414
=> fix(observability)!: Remove forwarding to syslog from distributed systemd unit

.github/workflows/nightly.yml, .github/workflows/release.yml
The armhf assets were still being referred to in the nightly build, but
are no longer being built.
=> chore(administration): Remove some more armv7 bits

src/sinks/util/auto_concurrency/tests.rs
These were supposed to be excluded by `#[cfg(unix)]` but apparently that is turned on for macos. Solve it instead with `#[cfg(note(target_os = "macos"))]`
Closes #3429
=> chore(tests): Do not run the auto-concurrency tests on macos

src/sinks/aws_s3.rs
These two ACLs appeared to be missing.
A user in gitter was asking about them:
https://gitter.im/timberio-vector/community?at=5f3527942376a9317f17a39e
Reference https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl
=> enhancement(aws_s3 sink): Add additional canned ACLs

.github/CODEOWNERS, src/lib.rs, src/line_agg.rs, src/sources/file.rs
This PR extracts the `line_agg` module from the `file` source, and renames the standalone `file/mod.rs` into `file.rs`.
Pretty trivial change.
=> chore: Extract line_agg from file source

.github/workflows/nightly.yml, .github/workflows/release.yml, scripts/ci-setup-helm.sh
This PR adds the Helm Chart release as part of the release CI workflow.
It also extracts the helm command setup into a script so it can be reused and don't clutter the workflow file.
To ensure we don't break the nightly by extracting the script (and that the release job works), I've run a nightly build manually: https://github.com/timberio/vector/actions/runs/208615012
=> enhancement(ci): Ship Helm Chart from release CI workflow

Makefile, docker-compose.yml, scripts/ci-docker-images/verifier-ubuntu-14-04/Dockerfile, scripts/ci-docker-images/verifier-ubuntu-16-04/Dockerfile, scripts/ci-docker-images/verifier-ubuntu-20-04/Dockerfile
This removes the no-longer-supported 19.04; replacing it with 20.04.
I also added 14.04 which is still supported.
Fixes #3290
=> chore(ci): Update the target Ubuntu distros for package verification

config/vector.spec.toml
The actual default is 10, not 1000.
@binarylogic how might I back port this so it is reflected in our live documentation on vector.dev?
=> docs(http sink): Fix default for rate_limit_num

src/sinks/streaming_sink/compat.rs, src/sinks/util/sink.rs
Closes #3438 
On `close` of the `Sink` it also wait's for the `sink` future to finish. Also adds implementation of `close` for `StreamSink` because it is wrapping the `Sink`.
The issue is affecting only `file` and `console` sinks since they are the only ones using `adapt_to_topology` at the moment.
Tested with #3373
=> chore(topology): Wait for detached sink to finish 

distribution/docker/alpine/Dockerfile, distribution/docker/debian/Dockerfile
Fixes #2718 by declaring `/var/lib/vector/` as a volume mountpoint.
```bash
ana@autonoma:~/git/timberio/vector$ make package-x86_64-unknown-linux-musl-all 
ana@autonoma:~/git/timberio/vector$ ./scripts/build-docker.sh 
ana@autonoma:~/git/timberio/vector$ docker run -ti -v $PWD/test.toml:/etc/vector/vector.toml:ro  timberio/vector:nightly-debian
Aug 18 21:51:46.343  INFO vector: Log level "info" is enabled.
Aug 18 21:51:46.347  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Aug 18 21:51:46.356  INFO vector: Vector is starting. version="0.11.0" git_version="v0.9.0-535-g8658b60" released="Tue, 18 Aug 2020 21:38:44 +0000" arch="x86_64"
Aug 18 21:51:46.358  INFO vector::sources::stdin: Capturing STDIN.
Aug 18 21:51:46.360  INFO vector::topology: Running healthchecks.
Aug 18 …
```
=> chore(docker source): Provision a /var/lib/vector in docker releases

.meta/sinks/file.toml.erb
Following up on https://github.com/timberio/vector/pull/3373#issuecomment-678809146
=> docs(file sink): Add `compression` option to the `file` source

Cargo.lock, Cargo.toml, src/sources/docker.rs
New version of bollard where some of unused deps was removed.
=> chore(deps): update bollard from 0.7.1 to 0.8.0

Cargo.lock, Cargo.toml
@dependabot can update only 1 dependency, I do not think that it makes sense update 1 rusoto crate (#3524).
=> chore(deps): bump rusoto from 0.44.0 to 0.45.0

.github/workflows/e2e.yml, .github/workflows/lints.yml, .github/workflows/tests.yml, CONTRIBUTING.md
As GitHub Actions doesn't support skipping whole workflows and you can't set
job defaults we need to specify the skip on every job.
=> chore: Added support for the ci-condition: skip label

Makefile
We do not need to build tests from `tests` folder for run integration tests. Reduce integration CI job on ~45s.
=> chore(tests): reduce compile units for integration tests

src/line_agg.rs, src/sources/file.rs
This PR alters `LineAgg` such that:
- it can pass around an extra piece of data together with each `line` - the `context`; this is required for some use cases - more on this below;
- it uses `Vec<Bytes>` instead of `ByteMut` to aggregate lines, and only does `BytesMut` once when the final event is emitted; this should reduce memory pressure and allocs count;
- it has different arguments order - the way it was before was natual for `file` source, but not for the current generic implementation.
`LineAgg` has to keep all the data nesessary to produce the `Event` from the aggragted `Bytes`. This is because we sometimes emit more than one line from the aggregation results - and the consumers of those merged line have to somehow transfer that data through the line aggregation mechnism.
Now, for …
=> enhancement: Rewrite LineAgg to allow passing context data and be more memory efficient

rfcs/2020-05-25-2692-more-usable-logevents.md
This is based off some discussions with @lukesteensen that these steps aren't necessary.
CLoses #2840 and #1377
=> chore: Amend event usability rfc (no more bytes/string split)

src/internal_events/mod.rs
Closes: #3571
This is the trivial fix, I foresee this function becoming used in more configurations, so the feature flags are likely to become unwieldy.
=> chore: Fix unused truncate_string_at warning

src/config/loading.rs, src/config/mod.rs, src/main.rs, src/topology/unit_test.rs, src/unit_test.rs, src/validate.rs, tests/config.rs
I've pulled this out of my larger set of changes because I think it warrants a review of its own.
The basic issue is that the current `validate` subcommand tries to be very fine-grained about where in the config loading process errors occur. It also attempts to validate config files one-by-one, which is not the way that we do it when running vector normally (they're combined and the result is validated). This is making it very difficult to consolidate and make that loading process more extensible, so I've opted here to simplify it and bring it more in line with how configs get validated at runtime.
The main differences in behavior here are:
1. There are no more distinct subsections of config errors in the `validate` output (e.g. file loading vs deserialization vs macro expansion)
2. …
=> chore: simplify validate subcommand behavior

src/sources/kubernetes_logs/pod_metadata_annotator.rs
=> enhancement(kubernetes_logs source): Store pod labels flat by default, remove the switch

src/sources/stdin.rs
Closes #3608
There are three meaningful changes here. If any of them are controversial I can break this up, but they're all related and it was easy to simplify all at once.
This is the big one. As described in #3608, the use of `tokio::sync::broadcast` channels here created the possibility for the background IO thread to outrun the forwarding task, which lead to lost data and an immediate shutdown. On my machine at least, this was extremely reproducible. 
The fix is to switch to normal `mpsc` channels that provide backpressure. This will slow down reads when the consumer can't keep up for any reason. It also actually simplifies the shutdown logic, since we are told directly by `send` when the consumer side of the channel has been shut down.
The previous implementation contained a good …
=> fix!(stdin source): switch off of broadcast channel

benches/event.rs, benches/lua.rs, src/event/mod.rs, src/sinks/logdna.rs, src/sources/docker.rs, src/sources/file.rs, src/sources/http.rs, src/sources/journald.rs, src/sources/kafka.rs, src/sources/kubernetes_logs/mod.rs, src/sources/kubernetes_logs/pod_metadata_annotator.rs, src/sources/logplex.rs, src/sources/socket/tcp.rs, src/sources/socket/udp.rs, src/sources/socket/unix.rs, src/sources/splunk_hec.rs, src/sources/stdin.rs, src/sources/syslog.rs, src/topology/unit_test.rs, src/transforms/grok_parser.rs, src/transforms/logfmt_parser.rs, src/transforms/lua/v1/mod.rs, src/transforms/regex_parser.rs, src/transforms/split.rs, src/transforms/tokenizer.rs, tests/topology.rs
Part of #2841 
This removes a few extra implementations of these which are kind of not idiomatic since we should encourage the caller to choose the allocation time of the values.
I allowed this in tests on `&str` since it's just so, so usable.
=> chore(deps): Remove some From implemementations from Event

distribution/helm/vector/templates/daemonset.yaml, distribution/helm/vector/values.yaml
The small PR add the ability for a user of the Helm template to add arbitrary pod labels to the DaemonSet spec template via a values.yaml file when deploying the package.
Resolves #3568.
=> enhancement(templating): adds new Helm DaemonSet template variable for pods labels

rfcs/2020-08-26-3191-host-metrics.md
=> chore: Draft host-metrics RFC

src/sinks/socket.rs, src/sinks/util/rusoto.rs, src/sources/kubernetes_logs/lifecycle.rs, src/sources/util/tcp.rs, src/test_util/mod.rs
[FutureExt](https://docs.rs/futures/0.3.5/futures/future/trait.FutureExt.html) / [StreamExt](https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html) have `_unpin` methods as a shortcut which pin object for us, so we do not need construct Pin before poll.
=> chore: use _unpin methods

benches/batch.rs, benches/bench.rs, benches/buffering.rs, benches/files.rs, benches/http.rs, benches/isolated_buffering.rs, src/sinks/util/sink.rs, src/test_util/mod.rs, tests/buffering.rs, tests/syslog.rs
Part of #3478. Update `runtime` helper function in `test_util` and adjust benches for tokio 0.2 runtime.
=> chore: update runtime in benches

docker-compose.yml
I worked out what was wrong with the Docker image that was making the add index duplicated and fixed that. Now adding the index is the right step in the docker-compose file.
=> chore: Added back add index after Docker image fix

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Updates a few issues with our Github issues templates:
* Removes a broken link
* Adds relevant community links
* Disables blank issues
=> chore: Update Github issue templates

src/sinks/splunk_hec.rs, src/test_util/mod.rs
Adds a `test_util::retry_until` helper, for retrying an async block until an `Ok(T)` is returned per `retry: Duration` - or until `until: Duration` has elapsed, whichever comes first. The latter panics.
Updates the Splunk integration test to use this approach vs. checking for openness of port 8089, which could occasionally result in a race condition where the port was open but the service wasn't fully initialised.
This could be used in other places where `wait_for_tcp` is currently employed, but for the sake of limiting scope, I've avoided touching other code paths.
=> chore(tests): Retry_until

benches/bench.rs, benches/buffering.rs, benches/files.rs, benches/http.rs, src/config/builder.rs, src/config/compiler.rs, src/config/diff.rs, src/config/loading.rs, src/config/mod.rs, src/config/unit_test.rs, src/config/validation.rs, src/event/log_schema.rs, src/event/mod.rs, src/main.rs, src/sinks/util/auto_concurrency/tests.rs, src/sources/file.rs, src/sources/prometheus/mod.rs, src/sources/statsd/mod.rs, src/test_util/mod.rs, src/topology/mod.rs, src/unit_test.rs, src/validate.rs, tests/buffering.rs, tests/config.rs, tests/crash.rs, tests/syslog.rs, tests/tcp.rs, tests/topology.rs
Closes #2936 
The overall goal here is to ensure that every `Config` instance is always valid and fully constructed. This means going through type checking, DAG validation, macro expansion, etc.
To do this, we bring all of those stages together in the `config` module and lock things down such that an invalid or incomplete `Config` can never escape the `config` module. This gives us the ability to add new stages (e.g. transform inlining) in one place, knowing they will be applied consistently.
More specifically, this PR introduces a new `ConfigBuilder` struct that takes over being {,de}serializable, clonable, test-friendly, etc, allowing us to lock down the actual `Config` struct significantly, making it harder to misuse.
There are definitely a lot of compromises here, mostly around the …
=> chore: consolidate config compilation

.meta/sinks/socket.toml.erb
Added groups to socket component metadata to display the sink type.
=> docs: Type missing in the Socket sink reference docs 

.meta/sinks/datadog_metrics.toml.erb, .meta/sinks/influxdb_metrics.toml.erb, .meta/sinks/prometheus.toml.erb, .meta/sinks/statsd.toml.erb, src/sinks/datadog/metrics.rs, src/sinks/influxdb/logs.rs, src/sinks/influxdb/metrics.rs, src/sinks/influxdb/mod.rs, src/sinks/prometheus.rs, src/sinks/statsd.rs, src/sinks/util/mod.rs, src/sources/prometheus/mod.rs, src/sources/statsd/mod.rs
Closes #3609 
Changes all of the sinks from #3609 except for `aws_cloudwatch_metrics`, reason being that the underlying library `rusoto_cloudwatch` requires namespace.
=> chore: Make the `namespace` option on metrics sinks optional

Cargo.lock, Cargo.toml
Remove `[patch.crates-io]` from `Cargo.toml`.
=> chore(deps): update warp 0.2.4 (git) to 0.2.5

src/sinks/gcp/cloud_storage.rs
Closes #3769 
Simple fix but the open a bigger question (related with #3766): how we can validate all sinks that encoding rules applied and when we should apply them.. extra documentation about encoding? Integrate encoding into the stream?
=> fix(gcp_cloud_storage sink): apply encoding rules after key prefix

.github/workflows/lints.yml, Makefile, distribution/helm/vector/Chart.yaml
This PR adds running `helm lint` at CI.
It is very simple, yet it poses an important question - is this the right way to manage Helm installation? Should we, maybe, keep it as part of our environment? If so, how is should look like?
CC @Hoverbear 
We'll also use Helm to generate YAML for Kubernetes - there's an upcoming PR.
=> chore(ci): Helm lint

src/internal_events/coercer.rs, src/internal_events/grok_parser.rs, src/internal_events/json_parser.rs, src/internal_events/regex_parser.rs
We are using both "processing_error" and "processing_errors" in counters.
This PR renames all to "processing_error**s**".
=> chore(observability): Make counters naming consistent

src/internal_events/mod.rs, src/sinks/clickhouse.rs, src/sinks/socket.rs
Fix `unused_imports` warnings (introduced in https://github.com/timberio/vector/pull/3743) in `clickhouse.rs`.
Also fixes `unused_imports` in `socket.rs`.
=> fix: remove unused imports

Cargo.lock, Cargo.toml, src/test_util/mod.rs
Replaces the static port 1234 used in `test_util::next_addr()` with [portpicker](https://github.com/Dentosal/portpicker-rs), to return an available TCP/UDP port.
I ran into a situation where I actually had a running service on 1234, and asserts of the response body were failing. This prevents that (probably quite uncommon, but hey-- it happened) scenario.
The [source](https://github.com/Dentosal/portpicker-rs/blob/master/src/lib.rs) looks fairly benign. A random port between 15000 - 25000 is tried (up to 10x) before deferring to the OS to pick a port by binding to localhost:0 and the attempting to listen on that port (again, up to 10x.) If the total 20 iterations fail, nothing is returned and the tests fail.
Should be a drop-in replacement, unless we're relying on hardcoded ports (which …
=> chore(tests): test_util::next_addr -- pick available port

src/internal_events/mod.rs, src/internal_events/tokenizer.rs, src/transforms/tokenizer.rs
Closes #3410
Pretty straightfoward. Snuck in one small cleanup to get rid of an unnecessary conversion and align better with other `MissingField` errors.
=> enhancement(tokenizer transform): add internal events

src/sinks/util/sink.rs
It's my hope this will resolve #3830, but I have no proof of it.
Regardless, this corrects a misbehavior I found with @LucioFranco and @fanatid during debugging. 
You can see in #3830 @spencergilbert hit:
```rust
12:          0x1f193b7 - <futures_util::future::future::NeverError<Fut> as core::future::future::Future>::poll::h7fb471e0dc82775f
13:          0x2203da9 - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::hd3a935b220d64df3
14:          0x1c1510a - <vector::sinks::util::sink::BatchSink<S,B,Request> as futures::sink::Sink>::poll_complete::h2ae3a9d473642464
```
Which leads us to here:
https://github.com/timberio/vector/blob/4d139851e441cac846414fe604c039d98461c7ff/src/sinks/util/sink.rs#L231-L232
As you can see, below, we use it here: …
=> chore: correct linger misbehavior

.meta/installation/platforms.toml, .meta/sources/kubernetes_logs.toml.erb
Supersedes https://github.com/timberio/vector/pull/3280 since we no longer host the website in this repo.
=> docs(kubernetes_logs source): Add reference docs

CONTRIBUTING.md
Also snuck in a change to just point people to the button for running
the nightly build instead of having them setup a Github API token and
run `curl`.
=> chore(internal docs): Add note about flakey tests to CONTRIBUTING.md

distribution/rpm/vector.spec
In #3657 we changed the tarball layout a bit and so the `--strip-components=` flag had to be updated.
=> chore(rpm platform): Fixup rpm builds to support new tarballs

Makefile
Supports tarball generation on Windows after #3657.
Sadly Windows generally packages busybox make or bsdmake, which don't support `--transform`
This also removes our use of the `vector-target` mount.
=> chore(windows platform): Support tarball generation on Windows

src/config/compiler.rs, tests/config.rs
Fixes #3889
This was me immediately getting bit by allowing unit tests to use invalid configs in #3672. The fix is simple and I added a test that would have caught it, but it's a reminder that we should try to go further in that refactoring for correctness.
=> fix(config): expand macros before validation

Cargo.lock, Cargo.toml
Noticed a feature was missing as I was working on the AWS Kinesis
Firehose source.  It's not required, I can use the older API, but
I didn't see a reason not to upgrade.
@Hoverbear should there have been a dependabot PR for this? I didn't see one.
Changelog:
https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md
=> chore(deps): Upgrade base64

src/sinks/http.rs
This test fails for reasons I do not understand - only on GH Actions macos-latest - I suspect some SSL inconsistency. I'll marking it as "do not run on osx" as a result. Happy to remove the test but it works fine on all the other platforms so this seemed to be a better outcome.
=> chore: Do not run http_headers_auth_conflict() on OSX

Makefile
#3890 was a botch, this is an unbotch by making the tarball structures identical.
=> chore(rpm platform): Resolve tarball differences

.github/dependabot.yml
Since Kirill has been involved in our dependencies I thought it would help to add him to Depdendabot. This should help push those PRs through faster.
=> chore: Add Kirill to dependabot

scripts/environment/bootstrap-ubuntu-20.04.sh
This is a workaround for GH https://github.com/actions/virtual-environments/issues/1605
This fix will be removed when GH addresses the issue.
What's happening here? Well, we use this script inside CI and Docker containers.
It'll run fine in CI because update-grub can find a root partition.
Inside a container, it'll fail. Either way, we don't care about the outcome of the command
so we ignore its exit.
This will fix our currently failing `environment-prepare` Make task.
=> chore: Fix grub to work in both CI and Docker containers

tests/behavior/transforms/remap.toml
I believe the nanoseconds aren't padded, and so the length equality check doesn't always succeed.
I've removed it for now, will see if we can make the numbers padded again in a follow-up PR, as I think that's a nice property to have actually.
=> fix: remove failing remap behavior test

.github/workflows/e2e.yml
This will help re-running tests after enabling the `ci-condition: k8s e2e all targets` without asking people to force-push the code at PRs.
=> chore(ci): Add workflow_dispatch to E2E tests

src/sinks/util/sink.rs
Ref #3830
It's still not clear to me how we could be getting a double-poll after #3869, but this should plug the gap rather thoroughly and give us some instrumentation to help explain. It also addresses a (very slight, likely never hit) behavior issue introduced there, along with a few small cleanups and explanatory comments.
The clue system can likely be removed once we figure out what is going on, but it should help us continue to track down the proble while mitigating user impact in the meantime.
=> fix(sinks): instrument and guard against double poll

src/sinks/socket.rs, src/sinks/util/tcp.rs
Closes #3928 
On various disconnects in `TcpSink` we would return `NotReady` variant, but without anything handling when to wake up the task. This would cause all dependent sinks to hang when disconnected.
=> fix: Add reconnect loop to `TcpSink`

scripts/package-rpm.sh
Our RPM uses systemd - the init script is not consumed by this RPM any longer and does not need to be copied into the environment.
=> chore: Do not copy in init.d to rpmbuild process as it is no longer used by the RPM

.github/workflows/tests.yml, Makefile, src/sinks/gcp/pubsub.rs, src/sinks/humio_logs.rs
This PR re-enables the Humio and GCP tests and fixes some warnings and failures in the GCP tests.
@bruceg I am unsure how to address the humio tests as I am not quite sure I understand the relationship between the Spunk and Humio sinks.
=> chore: Re-enable all integration tests

src/test_util/mod.rs, src/transforms/lua/v2/interop/event.rs
Removes test until #4003 can be fixed.
=> chore: Remove retry until after timeout test

.github/workflows/e2e.yml
Manually started E2E run: https://github.com/timberio/vector/runs/1146238453?check_suite_focus=true
=> chore(ci): Update the Kubernetes versions we test against at CI (1.19.2)

distribution/init.d/vector
function daemon does not have an output option, so delete it.
I couldn't find the init.d processor that has the output option, so I just want to delete it.
https://github.com/fedora-sysv/initscripts/blob/master/etc/rc.d/init.d/functions#L239-L272
=> fix(startup): init script / rm output option

src/sources/kubernetes_logs/mod.rs
Closes #4042.
Also adds extensive comments to capture the motivation behind the decisions on the `FileServer` configuration.
=> fix(kubernetes_logs source): Start reading logs at checkpoint

.github/workflows/nightly.yml, scripts/build-docker.sh
This will result in the following build in https://hub.docker.com/repository/docker/timberio/vecto
- timberio/vector:nightly-alpine
See also: https://github.com/timberio/vector-website/pull/104
=> chore: Remove Docker nightly-date images and nightly-debian

src/sinks/socket.rs, src/sources/splunk_hec.rs, src/sources/util/http.rs, src/sources/util/tcp.rs, src/tls/incoming.rs
Ref #2731.
The issue with vector shutting down when we fail to accept `tcp` connenction was fixed with #3449. This PR addresses the source of the error which was a call to `peer_addr`. There was probably a race, between us receiving the socket and calling `peer_addr`, and other side closing the channel. Although I wasn't able to trigger this race, the PR adds a fix which completely eliminates the need for calling `peer_addr` and so eliminates any race that we can avoid.
The bug was effecting multiple sources and sinks
=> fix: Avoid calling `peer_addr`

src/signal.rs
Fix the fix of #4025 on Unix so it handles signals in a look as well. Thanks @ktff for finding this.
=> fix: Fix tokio signal behavior to handle a loop of signals

src/event/metric.rs, src/sinks/util/buffer/metrics.rs
This is mostly just commentary, but contains a couple minor code tweaks.
I'd like attention in particular to the comments on the `AggregatedHistogram` and `AggregatedSummary` variants, to ensure I am representing them accurately. I was also unclear why `AggregatedSummary.values` was type `f64` and not `u32`, as my reading of the [Prometheus documentation](https://prometheus.io/docs/concepts/metric_types/#summary) seemed to indicate they are counts.
Closes #3168
=> chore(metrics): Enhance comments on the internals

lib/file-source/src/file_server.rs, lib/file-source/src/file_watcher.rs, lib/file-source/src/lib.rs, src/sources/file.rs
Fixes #2992 
This is an initial minimal-ish fix for the file source being too willing to return lines that did not end in a newline. Our original fix in #1236 was to wait up to a millisecond for the rest of a line to show up before considering it complete and returning it anyway. It turns out that in high-throughput situations, it's not uncommon for partial log lines to be visible for periods of time longer than this. This causes Vector to return a single logical line split across multiple events, which obviously breaks many kinds of downstream processing.
The problem with the sleep approach is that we can't know how long we need to sleep to see the rest of the line, and any amount of time we sleep is time we're not doing useful work, potentially lowering our overall throughput. This PR …
=> fix(file source): more robust handling of split reads

Cargo.toml, Makefile
The default `make check-clippy` target did not include the necessary features to check all the integration tests. This renames the appropriate feature flag (`docker` did not really mean a Docker-related feature) and adds the new `all-integration-tests` feature flag to the clippy command line.
Note: This will break CI until #4006 is resolved.
=> chore: Run clippy on all tests

src/topology/mod.rs
Closes #3035 
Adds a 200ms delay on windows during reload.
Maybe there is some Windows function we could call to check for this.
=> fix(reload): Wait on Windows after components shutdown

src/internal_events/json_parser.rs, src/transforms/json_parser.rs
When debugging json_parser transform, either in tests or classic run, it might be hard to understand why the parser fails.
The PR adds the value of the field that was attempted to be parsed in the warn message to help the user figuring out why the parsing failed.
Example of an output:
```
Sep 30 17:33:54.573  WARN vector::internal_events::json_parser: Event failed to parse as JSON. field=json_string value={this: is not: how json: looks} self.error=key must be a string at line 1 column 2 rate_limit_secs=30
```
=> enhancement(json_parser transform): add field's value in warn message when failing to parse

src/sinks/aws_s3.rs
The test was using `%S%f` for the time format for the object name, where
`%S` is "Second number (00--60), zero-padded to 2 digits."
(https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html#specifiers).
When the test ran close to the minute mark, this caused it write later
batches as objects that appear _earlier_ in the ListObjectsV2 call than
objects written before it.
This changes the filename_time_format to be `%s%f` where `%s` is the unix
timestamp so objects written later should always appear after.
Supersedes https://github.com/timberio/vector/pull/4222
Closes #4223
=> chore(aws_s3 sink): Fix flakey s3_gzip test

distribution/docker/README.md, distribution/docker/distroless-libc/Dockerfile, distribution/docker/distroless-static/Dockerfile, scripts/build-docker.sh
This is a simple PR which adds 2 docker container targets that use the [distroless](https://github.com/GoogleContainerTools/distroless) Container base.  
distroless/static is basically `FROM scratch` plus CA certificates.  
distroless/cc is distroless/static plus libc and related dependencies, so that dynamic binaries may run.  
I've successfully tested the musl build within the distroless/static,  and tested the debian package binary using the distroless/cc platform.  
The final containers are 86MB and 89MB respectively.
=> enhancement(docker platform): Added distroless-libc and distroless-static docker container bases

src/internal_events/mod.rs, src/internal_events/statsd.rs, src/internal_events/statsd_sink.rs, src/internal_events/statsd_source.rs, src/sinks/statsd.rs
On receiving an invalid event, the StatsD sink should emit an internal event rather than a warning.
This fixed #3635 
=> fix(statsd sink): Sink should emit event on invalid metric

src/sinks/prometheus.rs
This addresses #4238 
This assumes that the server will run forever (until shutdown) so the function only needs to be run once (but it won't hurt if it's run multiple times)
=> fix(prometheus sink): Ensure server starts immediately

lib/file-source/src/file_server.rs, lib/tracing-limit/benches/limit.rs, src/internal_events/wasm/compilation.rs, src/internal_events/wasm/event_processing.rs, src/internal_events/wasm/hostcall.rs, src/sinks/aws_s3.rs, src/sinks/gcp/cloud_storage.rs, src/sinks/prometheus.rs, src/sinks/util/udp.rs, src/sinks/util/unix.rs, src/sources/docker.rs, src/sources/journald.rs, src/sources/statsd/mod.rs, src/sources/syslog.rs, src/sources/util/tcp.rs, src/transforms/geoip.rs
When worked on ~#3032~ #4243  noticed that [tracing::field::debug](https://tracing.rs/tracing/field/fn.debug.html) / [tracing::field::display](https://tracing.rs/tracing/field/fn.display.html) used instead shortcuts `?`/`%` on creating trace events. This pull request replace methods by shortcuts.
=> chore(traces): use debug/display shortcuts on trace events

distribution/helm/vector/values.yaml, lib/k8s-test-framework/src/framework.rs, lib/k8s-test-framework/src/helm_values_file.rs, lib/k8s-test-framework/src/lib.rs, lib/k8s-test-framework/src/resource_file.rs, lib/k8s-test-framework/src/temp_file.rs, lib/k8s-test-framework/src/vector.rs, scripts/deploy-kubernetes-test.sh, scripts/kubernetes-yaml/values.yaml, tests/kubernetes-e2e.rs
This PR switches the E2E tests to using Helm chart instead of YAML config for greater configurability.
It also changes some of the Helm chart defaults, hence the `!`:
- moves master node toleration to the chart default, previously it was a YAML config-specific setting
Closes #3097.
It also unlocks writing more advanced tests, as now we can pass Helm values instead of just custom resources. This gives more possibilities to tweak the deployed Helm chart, and thus, to test more code paths.
=> chore(tests)!: Use Helm chart at the K8s E2E tests

.meta/installation/interfaces.toml
Fixes some of #4072 
See also:
* https://github.com/timberio/homebrew-brew/pull/3
=> docs: Updated Homebew configuration file path

.meta/sinks/humio_logs.toml.erb, Makefile, src/sinks/humio_logs.rs
This sink was previously not setting the `host` key of the Splunk HEC
format
(https://docs.humio.com/integrations/ingest-logs-with-a-data-shipper/hec/)
as the `host_key` field on the `SinkHecConfig` was defaulting `host_key`
to `''`.
I opted to expose the `host_key` as a config option on the Humio sink to
parallel its existence on the Splunk HEC sink.
Fixes #4228
=> fix(humio_logs sink): Set host key correctly

.meta/sources/splunk_hec.toml.erb
Implementation uses `8088` port.
=> docs(splunk_hec source): Correct port to `8088`

.github/workflows/bors_null.yml
The `paths-ignore` option did not work the way I thought it did. If ANY files are outside the ignore it'll run itself. What we actually want is negated paths.
=> chore: Change path matching for bors null job from ignore to exclude

docs/reference.cue, docs/reference/components.cue, docs/reference/components/sinks.cue, docs/reference/components/sinks/azure_monitor_logs.cue, docs/reference/components/sources.cue, docs/reference/components/sources/apache_metrics.cue, docs/reference/components/sources/file.cue, docs/reference/components/sources/http.cue, docs/reference/components/transforms.cue, docs/reference/components/transforms/swimlanes.cue
This cleans up the cue base schema:
* The `docs/reference.cue` defines the entire schema as recommended by the Cue docs.
* The intermediate files enforce domain-specific policies and boilerplate.
* The leaves define the actual data.
=> chore(external docs): Tiddy up cue schema

scripts/check-docs.sh
When a component instance is not completely specified, `cue vet`
produces the less than helpful error that `some instances are
incomplete; use the -c flag to show errors or suppress this message`.
Adding the `--concrete` option causes it to produce messages about which
specific fields were incomplete.
Additionally, the `--all-errors` causes `cue vet` to print all the
errors rather than just the first, reducing the number of
trial-and-error cycles necessary.
=> chore(external docs): Add options to `cue vet` command line

src/sources/apache_metrics/mod.rs, src/sources/apache_metrics/parser.rs
Was previously hardcoding `apache_up` as the metric.
I was going to refactor this namespace encoding to share among metrics sources, but figured I'd punt in-lieu of #3896 which I hope to get to next sprint, which would make it a first-class field on the `Metric` type.
=> fix(apache_metrics source): Use configured namespace for `up` metric

src/sinks/sematext_logs.rs
This PR renames the `sematext_logs` sink type to be in line with the [docs (https://vector.dev/docs/reference/sinks/sematext_logs/). It also sets the region to `us` by default if neither the host nor region is provided.
=> fix(sematext_logs sink): Rename sink type and fallback on US region by default

scripts/check-docs.sh
The check previously picking up changes to `Cargo.toml` and `.cargo/config` that happen as part of `make slim-builds` in CI.
Example: https://github.com/timberio/vector/pull/4101/checks?check_run_id=1226461323#step:9:15
=> chore(ci): Only check for diffs in the docs for `make check-docs`

src/transforms/metric_to_log.rs
We recently merged #4255 and some new PRs are landing which don't conform, this fixes one of them.
It's noone's fault, this is expected.
=> chore: Fixup a lint due to merge

src/validate.rs, tests/cli.rs, tests/shutdown.rs, tests/support/mod.rs
Ref #3930.
`validate` command now creates new directory "validate_tmp" in data_dir directory and changes data_dir path to "validate_tmp", and after its' completion the "validate_tmp" is deleted.
=> fix(cli): Use temporary data directory during `validate` command

src/sinks/util/auto_concurrency/mod.rs, tests/data/auto-concurrency/constant-link.toml, tests/data/auto-concurrency/jittery-link-small.toml
I used the `http_test_server` to run many tests, average the data, and then eyeball the graphs to see which produced the best results. The only parameter that needed obvious tuning was `ewma_alpha`. I still think we are not doing the right thing with the `rtt_threshold_ratio`  parameter, but it's not clear how to do it better. More testing on #3671 may point to a better solution.
@jszwedko @binarylogic I can clean up the scripts I used and contribute them to https://github.com/timberio/http_test_server if you think it's worth they're having around for posterity. They're a bit of a one-shot mess at the moment though.
Closes: #2530
=> fix(networking): Adjust auto concurrency tuning defaults

docs/reference.cue, docs/reference/components.cue, docs/reference/components/sources/file.cue, docs/reference/components/sources/http.cue, docs/reference/components/transforms/regex_parser.cue, scripts/check-docs.sh
As recommended by a Cue maintainer, we should be making judicious use of definitions:
1. Definitions are implicitly closed, making validation more strict.
2. Definitions provide better error messages.
3. Definitions are significantly faster.
=> chore(external docs): Make better use of Cue definitions

docs/reference.cue, docs/reference/components/sinks/azure_monitor_logs.cue, docs/reference/components/sinks/sematext_metrics.cue, docs/reference/components/transforms/add_fields.cue, docs/reference/components/transforms/aws_cloudwatch_logs_subscription_parser.cue, docs/reference/components/transforms/dedupe.cue, docs/reference/components/transforms/lua.cue, docs/reference/components/transforms/merge.cue, docs/reference/components/transforms/reduce.cue, docs/reference/components/transforms/regex_parser.cue, docs/reference/components/transforms/remove_fields.cue, docs/reference/components/transforms/remove_tags.cue, docs/reference/components/transforms/rename_fields.cue, docs/reference/components/transforms/sampler.cue, docs/reference/components/transforms/split.cue, docs/reference/components/transforms/swimlanes.cue
This adds support for an `input` key that documents support for the various Vector event types, including individual metric types.
=> chore(external docs): Add `input` key for metric types support

docs/reference.cue, docs/reference/components/sinks/sematext_metrics.cue, docs/reference/components/sources/apache_metrics.cue, docs/reference/components/sources/docker.cue, docs/reference/components/sources/file.cue, docs/reference/components/sources/host_metrics.cue, docs/reference/components/sources/http.cue, docs/reference/components/sources/journald.cue, docs/reference/components/sources/prometheus.cue, docs/reference/components/transforms/aws_cloudwatch_logs_subscription_parser.cue, docs/reference/components/transforms/dedupe.cue, docs/reference/components/transforms/lua.cue, docs/reference/components/transforms/merge.cue, docs/reference/components/transforms/reduce.cue, docs/reference/components/transforms/regex_parser.cue, docs/reference/components/transforms/remove_fields.cue, docs/reference/components/transforms/remove_tags.cue, docs/reference/components/transforms/sampler.cue, docs/reference/components/transforms/split.cue, docs/reference/data_model/schema.cue
This cleans up the #Field `array` types by implementing them with recursion. Instead of:
```
type: "[string]": {
default: null
examples: [["[error]", "field2"]]
}
```
We now do:
```
type: array: {
default: null
items: type: string: examples: ["[error]", "field2"]]
}
```
cc @sghall since this was breaking the Graphql schema on the website.
=> chore(external docs): Clean up array type

src/internal_events/add_tags.rs, src/internal_events/grok_parser.rs, src/internal_events/regex_parser.rs, src/internal_events/remove_fields.rs, src/internal_events/rename_fields.rs, src/internal_events/split.rs, src/internal_events/tag_cardinality_limit.rs, src/internal_events/tokenizer.rs
I've updated the log levels of several transforms to better match why it's being logged.
- add_tags: both of these logs are emitted when Vector takes the action as configured (only emits overwritten message when overwrite = true)
- grok_parser: set missing field log to warn based on a [quick chat](https://discordapp.com/channels/742820443487993987/746070604192415834/761038283655872532) with @binarylogic, conversion failure seems like a warning or maybe even an error?
- regex_parser: matched behaviour with grok_parser
- remove_fields: also discussed with @binarylogic - if you're trying to remove a field and it already isn't there, that seems _ok_
- rename_events: overwritten is again the configured behaviour like add_tags, warn on …
=> feat(observability): Update log levels for transforms

docs/reference/components/sinks/datadog_logs.cue, docs/reference/components/sinks/influxdb_logs.cue, docs/reference/components/sinks/influxdb_metrics.cue, docs/reference/components/sinks/logdna.cue, docs/reference/components/sinks/papertrail.cue, docs/reference/components/sinks/sematext_metrics.cue
The `endpoint` option was accidentally excluded.
=> chore(external docs): Add missing `endpoint` options

src/buffers/disk/mod.rs, src/sinks/mod.rs, src/topology/fanout.rs
Ensures close is propagated to the inner sink(s) for Fanout and buffers::disk::Writer.
Also ensures on error Fanout removes the Sink that actually returned an error
Closes #4256
=> fix(aws_s3 sink): Propagate close for Fanout and buffers::disk::Writer

distribution/helm/vector-agent/templates/daemonset.yaml, distribution/helm/vector-shared/templates/_env.tpl, distribution/kubernetes/vector.yaml, scripts/deploy-kubernetes-test.sh
This PR solves an issue that was overlooked at #4257.
=> chore: Allow setting literal env variable values via `global` at Helm charts

Cargo.toml
It's still not clear to me how this snuck in, but it seems like we started relying on the tokio `process` feature without explicitly enabling it [here](https://github.com/timberio/vector/commit/881fbb3ef12cdc04715ea18c1a81e636ddb34c8e#diff-acc89eb37f2db3e476b2c19fc1702a4f9bd795d859c7ba1858d3caa8ac56e911R34). Presumably this worked because of some other dependency enabling the feature, but that ended up breaking [here](https://github.com/timberio/vector/runs/1244690291?check_suite_focus=true).
This change just enables the feature we rely on directly and now the tests are fine locally.
=> chore: fix shutdown tests

scripts/check-style.sh
This is a workaround until we fix the Helm formatting.
=> chore: Allow distribution/kubernetes/vector.yaml to be formatted incorrectly

scripts/patch-packaged-helm-chart-versions.sh, scripts/release-helm.sh
This PR adds a workaround for the Helm release process that fixes an issue with version overrides via `--version` and `--appVersion` not being propagated to the subcharts.
Such propagation is just a very good fit for us, so we apply the workaround.
Closes #4560.
=> chore: A workaround for the Helm chart release version fields

lib/k8s-e2e-tests/tests/vector-agent.rs, src/sources/kubernetes_logs/mod.rs
This PR adds the ability to pass additional [label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors) and [fields](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/) selectors.
Closes #3412
Closes #3413
~Blocked by #4176, the test has to be added after it's merged.~
To do:
=> enhancement(kubernetes_logs source): Allow using custom selectors

docs/reference/components/sinks/elasticsearch.cue, docs/reference/components/sinks/file.cue, docs/reference/components/sinks/humio_logs.cue, docs/reference/components/sinks/loki.cue
=> chore(external docs): Restore templateable option

lib/k8s-e2e-tests/src/lib.rs, lib/k8s-e2e-tests/tests/vector-agent.rs, src/sources/kubernetes_logs/k8s_paths_provider.rs, src/sources/kubernetes_logs/mod.rs
This PR adds two new ways to filter logs to the `kubernetes_logs` source:
1. Filtering by `Pod` *annotation* in the form of `vector.dev/exclude-containers: "<container_name_1>,<container_name_2>,<...>"` - log files from the `<container_name_1>` and `<container_name_2>` are excluded.
2. Filtering by the file exclusion patterns configured at the Vector configuration at the `kubernetes_logs` source - for a pattern `/var/log/pods/pod-namepspace_pod-name_pod-uid/**` all the files matching that pattern will be excluded.
Closes #4213.
Closes #4270.
To do:
=> enhancement(kubernetes_logs source): Advanced container filtering

src/sources/file.rs
Ref #3780 
Test now periodically checks if the file has been removed with max total wait of 20sec.
=> chore(tests): Re add fixed `sources::file::tests::remove_file` test

src/sinks/loki.rs
=> fix(loki sink): Send auth header for healchecks

docs/reference.cue, docs/reference/components.cue, docs/reference/components/sources/statsd.cue, docs/reference/components/transforms/log_to_metric.cue, docs/reference/data_model/schema.cue
Closes #4558
* `vector` source is missing `output: metrics:` field.
* `#MetricEvent` is missing kind` field.
=> chore(external docs): Update `log_to_metric` docs

src/sinks/azure_monitor_logs.rs
azure_monitor_logs: Use Signer::sign_to_vec to support older OpenSSL versions
Closes #4616
=> fix(azure_monitor_logs sink): Use Signer::sign_to_vec to support older OpenSSL versions

src/mapping/query/function/ceil.rs, src/mapping/query/function/floor.rs, src/mapping/query/function/mod.rs, src/mapping/query/function/round.rs, src/mapping/query/function/util.rs, tests/behavior/transforms/remap.toml
Closes #4231  
Closes #4232 
Closes #4233 
Adds floor, ceil and round remap functions.
Because there is quite a lot of code duplication here, I experimented with creating a macro to avoid the repetition. What I found was that due to the way the `build_signatures` macro works, I would still need to create a separate file for each function, each with a single line invoking my macro. The result was would be that if someone wanted to find the code to look up the details of the function they would have to browse through several files. The added complexity didn't feel worth it. So there is a bit of duplication, but I think it makes for more easily understandable code.
=> feat(remap transform): add `floor`, `round` and `ceil` remap functions

.github/workflows/k8s_e2e.yml
This PR enables an opt-in way to run the K8s E2E tests for PRs in CI.
=> chore(ci): Only run E2E test suite on non-PRs, or if the opt-in label is set on the PR

src/sinks/datadog/metrics.rs
Previously it was exercising the `None` behavior of metric timestamps to
set it to the current time, but this would fail if the test ran close to
the end of a second where our `Utc::now()` would not match the
`Utc::now()` at the time of assignment.
If we want to exercise this logic, we could inject a function that
returns the current time.
Fixes #4664
=> chore(ci): Use a static timestamp for datadog_metrics test

Cargo.lock, Cargo.toml, Makefile, config/examples/file_to_cloudwatch_metrics.toml, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/elasticsearch.rs
Updates to latest localstack tag. I need this for some of the S3+SQS
work, but figured I'd do it separately.
The biggest change is that localstack now exposes all services on the
same port, 4566, simplifying our setup.
Additional changes due to localstack changes:
I updated `aws_s3` sink tests to use "Identity" for Content-Encoding as
this appears to be the default encoding now
I added a sleep in `aws_kinesis_streams` test to allow localstack to
fully create the stream (it was getting `ResourceNotFound` errors when
the sink tried to publish via `PutRecords`). I tried a `wait_for` with
`DescribeStream`, but the stream was successfully returned by that
before it was ready, still.
I updated `aws_kinesis_firehose` to create the Elasticsearch domain as
localstack now lazily starts …
=> chore(ci): Update localstack

src/internal_events/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs
Noted while worked on #2755 
- Move `AwsKinesisStreamsEventSent` to correct place. The event should be generated on success request, not on event encoding.
- Remove duplicated `Arc` from `KinesisService`. Inner value of `rusoto_core::Client` already use `Arc`, so we had `Arc` over `Arc`.
=> chore(aws_kinesis_streams sink): remove Arc and fix event

distribution/debian/scripts/postinst
`-G` is `--groups` rather than `--gid` (the latter is the initial login
group for the user).
Fixes #4692 
=> fix(releasing): Fix flag for `usermod` in postinst deb script

src/internal_events/mongodb_metrics.rs
=> fix: Renamed mongo metrics to new naming standards

src/mapping/query/function/parse_syslog.rs
Closes #4710 
Syslog test was testing against the timezone in Utc, but it should test against the local time. That is the timezone the parser assumes when no timezone is specified.
=> fix(remap transform): syslog test should assume local time zone

proto/event.proto, src/conditions/is_log.rs, src/conditions/is_metric.rs, src/event/metric.rs, src/event/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/console.rs, src/sinks/datadog/metrics.rs, src/sinks/humio/metrics.rs, src/sinks/influxdb/metrics.rs, src/sinks/prometheus.rs, src/sinks/sematext/metrics.rs, src/sinks/statsd.rs, src/sinks/util/buffer/metrics.rs, src/sources/apache_metrics/mod.rs, src/sources/apache_metrics/parser.rs, src/sources/host_metrics.rs, src/sources/mongodb_metrics/mod.rs, src/sources/prometheus/parser.rs, src/sources/statsd/parser.rs, src/sources/vector.rs, src/transforms/add_tags.rs, src/transforms/log_to_metric.rs, src/transforms/lua/v2/interop/event.rs, src/transforms/lua/v2/interop/metric.rs, src/transforms/lua/v2/mod.rs, src/transforms/metric_to_log.rs, src/transforms/remove_tags.rs, src/transforms/tag_cardinality_limit.rs
First of the PRs for #3896
Adds `namespace` field to `struct Metric` and wires this change through the code base. 
Does not change behavior of componenets.
=> enhancement(data model): Add `namespace` to `Metric` 

src/mapping/mod.rs, src/mapping/parser/grammar.pest, src/mapping/parser/mod.rs, tests/behavior/transforms/remap.toml
Closes #4234 
Added the log remap function.
Note, because this is an impure function (similar to `merge`) I haven't been able to use the new function methods, so there are a few additions to the pest file. This well need rethinking at some point. The log levels are an enum, and not a `Value`, so this could be another candidate for inclusion in `QueryValue` similar to `Regex`..
=> feat(remap transform): add `log` function

lib/file-source/src/file_server.rs, src/line_agg.rs, src/sources/file.rs, src/sources/kubernetes_logs/mod.rs, src/sources/kubernetes_logs/util.rs
This modifies the file source to send its whole `Vec` of lines at once instead of one at a time. It also attempts to unravel some of the compat layers that have accumulated in this area of the code.
Locally this shows a ~20% or more improvement to performance.
=> perf(file source): send batches of lines

rfcs/2020-10-06-3791-composing-components-pt-1.md
=> chore: add config composition RFC

src/sinks/new_relic_logs.rs
New Relic Logs API max payload size is 10^6 bytes.
While I'm not 100% sure this sets the actual JSON payload
size to where it should be, it does seem like an improvement
compared to the old value of 5MiB.
I have opted to allow the user to set a lower batch size, 
should they so prefer.
Comments & Feedback welcome!
=> enhancement(new_relic_logs sink): Fix API max payload size

src/sinks/aws_cloudwatch_logs/mod.rs, src/template.rs
- Remove `src_bytes`: `Template` stores a clone of `src` (`src` and `src_bytes`), but barely uses `src_bytes`.
- Flip `From<&str>` and `From<String>`: avoid cloning twice in `From<String>` impl.
- Flip `render` and `render_string`: avoid cloning and UTF-8 parsing in `render_string`.
- Change `get_ref` to return `&str`, more fitting for its usage in `aws_cloudwatch_logs`.
=> chore: Clean up redundancies in template

src/sinks/datadog/logs.rs
Closes #4687 
Closes #4720 
Sorry, this was caused when I factored both the text, and json encoding to use the same `build_request` method and neglected to change the `Content-Type` for each encoding. So json was being sent as text.
Regarding encoding the entire payload under `message`,  the code that encodes the message is [here](https://github.com/timberio/vector/blob/d99813e90c9668d4cfcf8d25abc329ed8eff4fb0/src/sinks/datadog/logs.rs#L206).
Currently, if there is no `message` field in the payload, it shows up in Datadog as follows:
If the message field is an object, for example, sending this:
```
{"message": {"subkey1": "subvalue1"}}
```
Results in this:
It looks like datadog merges the fields from the message key into the parent object.
If the message is simple text, it looks like …
=> fix(datadog_logs sink): use application/json for json encoding to Datadog

src/internal_events/console.rs, src/sinks/console.rs
This PR adds `processed_bytes_total` and `events_processed_total` metrics to the `console` sink. These metrics are already present on most of the other sinks and will be particularly useful in demo scenarios.
=> fix(metrics): Add event metrics to console sink

src/dns.rs
We do not use futures01 method anywhere.
=> chore: remove Resolver::lookup_ip_01

.github/workflows/nightly.yml
The needed artifact, vector-amd64.deb is built by
build-x86_64-unknown-linux-gnu-packages but this was not listed as
a dependency. I think this resulted in the action running too early
sometimes, culminating in it failing to fetch vector-amd64.deb.
Example failure: https://github.com/timberio/vector/runs/1307027438?check_suite_focus=true
=> fix(ci): Add missing dependency to nightly docker-release

distribution/helm/vector-agent/templates/daemonset.yaml, distribution/kubernetes/vector.yaml
This feature includes a sha256 of the configmap in the daemonset's pod template. This forces Kubernetes to redeploy the agents when the vector toml is updated, ensuring agents are using up to date configuration.
﻿Signed-off-by: Spencer Gilbert <spencer.gilbert@gmail.com>
Closes #4045.
=> feat(kubernetes platform): Force daemonset to redeploy when configmap is updated

Cargo.lock, Cargo.toml
=> chore(observability): Bump async-graphql to 2.0.0 -> 2.0.8

benches/bench.rs, src/transforms/remap.rs, tests/behavior/transforms/remap.toml
Closes #4281 
Renames the remap.mapping field to be remap.source.
In addition to the transform itself, I have updated:
- behaviour tests
- bench tests
I couldn't find anywhere else that needed updating. The cue docs are already using the `source` field.
=> chore(remap transform): rename remap.mapping to remap.source

src/mapping/query/function/flatten.rs, src/mapping/query/function/mod.rs, src/mapping/query/function/replace.rs, src/mapping/query/regex.rs, tests/behavior/transforms/remap.toml
Closes #3750 
Closes #3752 
This adds `replace` and `flatten` remap functions.
Note with the `flatten` function, it flattens both Arrays and Maps, but it does not attempt to flatten a value that is a combination of Arrays and Maps. The rules for flattening are determined according to what the top level value is. So an Array of Maps is flattened as an Array, and an Map of Arrays is flatten as a Map.
Creating this as draft for now, as it may need some additional work to merge it into #4695
=> feat(remap transform): add `replace` and `flatten` remap functions

.github/workflows/master.yml, .github/workflows/pr.yml
They seem to run fairly quickly (2 minutes locally).
This in response to a commit sneaking through to master that broke one
of them:
https://github.com/timberio/vector/runs/1314766689?check_suite_focus=true
Also renames the shutdown test action in the master workflow to match
the fact that it runs miscellaneous tests.
=> chore(ci): Run behavior tests for PRs

Makefile
Building the GraphQL `schema.json` currently involves a fairly complex Cargo command. This PR adds a make command for convenience.
=> chore(ci): Add make command for building the GraphQL schema

docs/reference/components/sources/http.cue, docs/reference/components/sources/logplex.cue, src/sources/http.rs, src/sources/logplex.rs, src/sources/util/http.rs, src/sources/util/mod.rs
Allow annotation of logs via query parameters for http + logplex source,
in a similar fashion as is currently supported for HTTP headers.
This is particularly useful with the logplex source as it allows for a
single vector instance to be used as a drain for multiple Heroku
applications.
Closes #4732
Signed-off-by: Christian Gregg <christian@bissy.io>
=> enhancement(logplex source): annotate logs with query parameters

docs/reference/components/sinks/elasticsearch.cue
Addresses #4648. This PR is a complement to #4777, which updates the current vector.dev site by updating the old TOML/ERB sources and targeting the `v0.10` branch. This PR "updates" the future Cue-driven site.
=> fix(config): Add endpoint config to Elasticsearch sink

src/sinks/blackhole.rs
I opted to encode event as JSON to match `Metric` handling. I could be
convinced that we should use `size_of()` instead here and possibly in
other places that report processed bytes in relation to events.
**EDIT**: This now uses std::mem::size_of_val instead rather than serializing the event.
Fixes #4704
=> fix(blackhole sink): Count total bytes for logs

src/sources/http.rs, src/sources/logplex.rs
For logplex and http sources.
Follow up to #4733 
=> fix(config): Make query_parameters optional

.github/workflows/pr.yml
These seem to run quickly:
* ~50s for test-shutdown, most of which is the 30s sleep for kafka in
the Makefile
* ~2s for test-cli
Given this, I think it is worth running them on PRs.
I just copied the miscellaneous test action from the master workflow
(moving test-behavior down).
Again, I think it'd be nice to have an action that ran the build setup
and cached the result to split up these tests into separate actions, but
this'll do for now. For one, the current behavior will have it fail as
soon as it hits an error where it'd be nice to run them all regardless.
=> chore(ci): Run test-shutdown and test-cli on PRs

src/sources/journald.rs
Resolve comment https://github.com/timberio/vector/pull/4243/#discussion_r511314467
@juchiast I only have a question is it correct to stop source and return from function? Or we should block a function forever? (with something like `futures::future::pending().await`)
=> chore(journald source): remove extra shutdown

.github/workflows/master.yml
To prevent links posted through the hook from expanding, since they never contain any useful information:
=> chore(ci): don't expand build failure link previews

src/sources/syslog.rs
The Syslog source in UDP mode uses `std::net:SocketAddr` (which represents the socket as `ipaddress:port`) as the value of the `source_ip` field. The TCP mode uses `SocketListenAddr` which represents just the `ipaddress`. This results in the `source_ip` field being set as `127.0.0.1` in TCP mode and as `127.0.0.1:1234` in UDP mode.
This PR calls the `ip()` method on `received_from` in the `udp` function. This results in the `source_ip` field to be set to `ipaddress` in both cases.
Before:
```
Oct 28 14:25:07 a-k53d9h7imuxj vector[358336]: {"host":"127.0.0.1","message":"test message","source_ip":"127.0.0.1:6712","source_type":"syslog","timestamp":"2020-10-28T18:25:07.917801031Z"}
```
After:
```
Oct 28 14:26:12 a-k53d9h7imuxj vector[358336]: {"host":"127.0.0.1","message":"test …
```
=> fix(syslog source): Fixes the value of `source_ip` in UDP mode from `ipaddress:port` to `ipaddress`

src/sources/kubernetes_logs/mod.rs
This PR exposes some file server tweaks that are useful for adjusting the performance to be user-configurable. It also bumps the default `glob_minimum_cooldown` value to 60 seconds.
=> enhancement(kubernetes_logs source): Expose the performance related parameters

lib/file-source/src/checkpointer.rs, lib/file-source/src/file_server.rs, lib/file-source/src/fingerprinter.rs, lib/file-source/src/lib.rs, src/sources/kubernetes_logs/mod.rs
This sets the stage for a transition from the old strategy of checksum fingerprinting to a new unified one. By differentiating between the different types of checksums on disk, we are able to intelligently upgrade existing checksums without breaking compatibility with existing stored checkpoints.
In this PR we change the in-memory representation of fingerprints and introduce a new format for writing them to disk. It also preps `FirstLineChecksum` to be the unified strategy by adding `ignored_header_bytes`. Next, we will add a path to transparently upgrade the `checksum` strategy to use `FirstLineChecksum` internally.
I did not give a huge amount of thought to the new format, since we will also be migrating away from the current filename-based storage. It should only be used as part of …
=> chore(file source): differentiate between types of fingerprints

src/config/compiler.rs, src/config/diff.rs, src/config/mod.rs, src/config/validation.rs, src/sinks/prometheus.rs, src/topology/mod.rs, src/transforms/log_to_metric.rs
Closes #4031 
Adds `Resource` which configs of sinks can report as having. This information is used to:
* Validate that there aren't port conflicts among the sinks in the config.
* Detect conflicting sinks, among a new and an old config, during reload. If found, we wait for them to finish before starting new ones. Crucially, sinks with resources should not use them during build phase, otherwise conflict can still occur. 
After merging this, open issues for:
- Will enable detection of more resource conflicts in config.
- Reload will be more robust.
- Resource conflicts between sinks and sources would be detected. 
- Useful after resources have been extended to sources.
=> enhancement(reload): Resolve port conflict in sinks

Makefile
This adds running the `lib/*` tests for every PR - these were not previously run as far as I can see.
Closes #2588
=> fix(ci): Run /lib/* tests in  on pull requests

lib/remap-lang/grammar.pest, lib/remap-lang/src/lib.rs, lib/remap-lang/src/parser.rs
This updates the remap-lang grammar to extend if statements with support for else-if conditionals:
```rust
if false {
0
} else if false { 
1
} else if true {
2
} else {
3
}
// => 2
```
I had this lying around from my previous work on refactoring the remap-lang implementation, I pulled it out at the last minute to not overcomplicate the PR (similar to #4802), but after reading @FungusHumungus RFC in #4808 I figured it'd be worth to re-submit the PR.
This doesn't do anything that's described in @FungusHumungus's RFC _other than_ extending if statements to support `else if` cases, which is a trivial thing to add and something people probably expect to exist regardless.
As with variables (#4802), I'm happy to drop this proposal, but I think its table stakes for any language, even one that …
=> feat(remap): support else-if conditional expression

lib/remap-lang/grammar.pest, lib/remap-lang/src/error.rs, lib/remap-lang/src/expression.rs, lib/remap-lang/src/expression/assignment.rs, lib/remap-lang/src/expression/variable.rs, lib/remap-lang/src/lib.rs, lib/remap-lang/src/parser.rs
This adds variable support to the remap language:
```rust
// variable assignment
$foo = "bar"
// path assignment and variable reference
.bar = $foo
```
This was removed in https://github.com/timberio/vector/pull/4695 (340842453a65875e3898f145bc332d2c4e104e76) to reduce the complexity of that PR and have it move forward without too much unrelated discussions.
Now that all the recent remap-lang changes have been merged, I'm re-introducing the concept of variables in this PR.
I'm happy to _not_ do this if there is opposition to this, but I'll posit my motivation for why I think it makes sense to add variables to the language.
**only manipulate the target object if you need to**
Remap language already supports assigning to paths, but if you want to hold a temporary value, right now you must …
=> feat(remap): add variable support

Cargo.lock, Cargo.toml
[pin-project](https://crates.io/crates/pin_project) changelog: https://github.com/taiki-e/pin-project/blob/master/CHANGELOG.md (nothing major, looks like stabilization).
Need clippy rule: `pattern_type_mismatch`. Unfortunately this rule will be available only in clippy with rust 1.47: https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-147
=> chore(deps): bump pin-project from 0.4.26 to 1.0.1

distribution/helm/vector-agent/templates/daemonset.yaml, distribution/helm/vector-agent/values.yaml, distribution/kubernetes/vector.yaml
This PR adds the ability to configure container ports. It is mostly useful to bind names to the exposed ports, which is required, in particular, if you're using `prometheus-operator`.
Closes #3808.
=> enhancement(kubernetes platform): Add the ability to set conatiner ports at vector-agent Helm chart

.github/workflows/pr.yml
Try to let the CI take a break on cross builds.
=> chore: disable bootstrap on cross

src/generate.rs
Closes #3013 
This PR should be straightforward. Not entirely confident on team patterns just yet but we effectively now take an extra argument for the `generate` subcommand of a filepath and we write the config to that location. It's a pretty dumb implementation. We check if the file already exists and pass an error if so. If its a directory path we create the directories assuming the user has the permissions to do so.
=> enhancement(cli): Adds optional file output to generate subcommand

rfcs/2020-11-02-remap-language-compile-time-type-checking-v1.md, rfcs/2020-11-02-remap-strict-return-value-types.md
This RFC spun out of a discussion in https://github.com/timberio/vector/pull/4743.
It moves one more failure condition from runtime to compile/boot-time.
👀 [Rendered version](https://github.com/timberio/vector/blob/ed88e3ff4ffc161955e521a40730c4eed228ccf5/rfcs/2020-11-02-remap-strict-return-value-types.md)
closes #4862
=> chore(rfcs): Remap language compile-time type checking v1

lib/remap-lang/src/error.rs, lib/remap-lang/src/lib.rs, lib/remap-lang/src/program.rs, lib/remap-lang/src/runtime.rs, src/conditions/remap.rs
This change makes sure we get more detailed error messages in Vector's log output whenever a remap-lang error occurs.
It changes this:
```
error for function "foo_func"
```
Into this:
```
remap error: error for function "foo_func": missing required argument "arg1" (position 0)
```
=> enhancement(remap): display full error chain

docs/reference/cli.cue
This PR adds Cue sources describing the Vector CLI. These Cue sources can serve as inputs for the Vector documentation. This is a fairly rough first pass that could use some refinement over time, but I think that it does provide sources that we can update as the CLI evolves.
=> enhancement(config): Add Cue sources for the Vector CLI

src/sinks/kafka.rs, src/sinks/mod.rs, src/sinks/pulsar.rs
Part of #2942 #4247 
Only introduce variant and upgrade pulsar and kafka. Integration tests for kafka fail for me locally, will mark as draft for some time.
=> chore: add VectorSink::Sink

scripts/build-docker.sh
Supersedes #4764.
Fixes https://github.com/timberio/vector/commit/26be119ac6c506cd50001b5fdc94adafdecb0f2d#r43596614
=> fix(ci): Fix passing --push arg at build-docker.sh

rfcs/2020-10-29-3736-remap-chain-parsing.md
Closes #3736 
Closes #2418 
Adds the ability to chain parsing functions to the Remap language. Each is run until one passes.
=> chore(rfcs): Remap chaining parsing functions RFC

src/internal_events/process.rs
With the `vector` default namespace, these metrics are `vector_vector_started`. This removes the extra vector namespace.
=> chore(metrics): Remove duplicate vector namespace from internal metrics

docs/reference/components/sources/kubernetes_logs.cue
This PR fills in some details at the `kubernetes_logs` source docs.
@binarylogic, could you do a pass on making the values fit the schema? I'm having a hard time figuring out the error cause, as errors are in pretty much all of the components.
Closes #4594.
Closes #4587.
=> chore(external docs): Fill in missing parts of the documentation at the kubernetes_logs source

src/sinks/humio/logs.rs, src/sinks/humio/metrics.rs, src/sinks/humio/mod.rs
Closes #4903 
There is a bug in Serde ([here](https://github.com/serde-rs/serde/issues/1504)) whereby if you flatten fields from another struct it will not alias any fields from that struct. 
So, I have had to copy the field from the Humio logs config rather that flatten them. The code is not as elegant, but until Serde fix that issue, there isn't much else to do. By the sounds of it, it is quite a hard bug to fix.
=> fix(humio_metrics sink): dont use flatten for logs config fields

docs/reference.cue
This PR fixes an issue pointed out in #4891 that Cue has a specific way to require at least one element of a type in a list:
```cue
[#T, ...#T]
```
This currently used syntax does not provide such length guarantees:
```cue
[...#T]
```
=> fix(external docs): Fix length requirement for Cue lists

src/api/schema/metrics/mod.rs
ping @leebenson 'Ello Guv'na! 😄
Attempting to fix an issue where the bytes processed always comes back as null on queries (not subscriptions).  Believe it's a typo in the API that's causing it.  This is **not** noticeable on the `vector top` because the initial query is immediately updated by the subscriptions.  The typo is understandable given that events goes the other way with `events_processed_total`.
If you run a query against master like this you will always get null even if there are results:
```gql
query {
sinks {
name
bytesProcessedTotal {
bytesProcessedTotal
}
}
}
```
=> fix(observability): Fix bytes processed total query

Cargo.lock, lib/file-source/Cargo.toml, lib/file-source/src/checkpointer.rs, lib/file-source/src/file_server.rs, lib/file-source/src/file_watcher.rs, lib/file-source/src/fingerprinter.rs, src/sources/file.rs
Closes #1427
Closes #1779
This adds functionality to migrate existing checkpoints to a new JSON-based file approach. It should be fully compatible, both backwards and forwards. This fixes a couple of outstanding issues and opens the door to storing more information with checkpoints, allowing for more intelligent fingerprinting algorithms.
Once this has been deployed in a new version, we should be able to remove a lot of the old code and clean things up, just noting that users will need to transition through this version if they want to migrate older-style checkpoints.
The first commit also fixes a bug introduced in #1499 and better testing that would have caught it.
=> chore(file source)!: migrate checkpoints to single JSON file

Cargo.toml, lib/k8s-e2e-tests/Cargo.toml, lib/k8s-e2e-tests/tests/vector-agent.rs, lib/k8s-test-framework/Cargo.toml, lib/k8s-test-framework/src/framework.rs, lib/k8s-test-framework/src/kubernetes_version.rs, lib/k8s-test-framework/src/lib.rs, src/sources/kubernetes_logs/pod_metadata_annotator.rs
Closes #4740 
Will probably need a thorough review @MOZGIII but ultimately pretty trivial. We tap `k8s_openapi` to get the `PodStatus` data that holds `PodIPs`. This also bumps the k8s feature level to `1_16` to support returning both the IPv4 _and_ IPv6 addresses attached to a pod in the case that both things do in fact exist.
=> enhancement(kubernetes_logs source): Add PodIPs into Pod Metadata event annotations

src/sinks/kafka.rs
Improvement of #4846, details: https://github.com/timberio/vector/pull/4846#discussion_r516955267
=> chore(kafka sink): use signal instead timeout

docs/reference.cue, docs/reference/components.cue, docs/reference/data_model.cue, docs/reference/releases.cue, docs/reference/remap.cue
This cleans up our cue definitions by implementing a new pattern where defintions are defined within their respective namespace.
This helps to unblock some work I'm doing to reuse definitions in the new installation cue data.
=> chore: Cleanup cue definitions

.github/workflows/k8s_e2e.yml, CONTRIBUTING.md
1.13.1 update seems problematic at the moment, this PR exists to gather some data through our CI runs.
1.40 was also problematic.
We're looking into updating to 1.15.1 now.
Upstream tracking issue: https://github.com/kubernetes/minikube/issues/9304
=> chore: Update minikube to 1.15.1

lib/remap-lang/src/expression/if_statement.rs, lib/remap-lang/src/expression/not.rs, lib/remap-lang/src/value.rs, src/remap/function.rs, src/remap/function/ceil.rs, src/remap/function/contains.rs, src/remap/function/ends_with.rs, src/remap/function/floor.rs, src/remap/function/format_number.rs, src/remap/function/format_timestamp.rs, src/remap/function/match.rs, src/remap/function/md5.rs, src/remap/function/parse_duration.rs, src/remap/function/parse_syslog.rs, src/remap/function/parse_url.rs, src/remap/function/replace.rs, src/remap/function/round.rs, src/remap/function/sha1.rs, src/remap/function/sha2.rs, src/remap/function/sha3.rs, src/remap/function/slice.rs, src/remap/function/split.rs, src/remap/function/starts_with.rs, src/remap/function/strip_ansi_escape_codes.rs, src/remap/function/strip_whitespace.rs, src/remap/function/tokenize.rs, src/remap/function/truncate.rs
With the Expression trait updated to remove `None` results in #5053, the usage of the `required!` and `optional!` macro's made functions more difficult to parse as a reader than not using them.
They hid so little implementation detail, and code within them wasn't being formatted by rustfmt, which made me decide to remove them entirely.
I think this improves readability of expressions, at the cost of sometimes one or two more lines of code within the expressions themselves.
Additionally, a few PRs back, helper functions were added to the `Value` type, which makes it easier to get a specific value kind through `{as,as_mut,try,unwrap}_{string,integer,...}`, that the resulting code is often easier to write and understand than with the macros.
Another added benefit is that we were kind of …
=> chore(remap): remove required! and optional! macros

Cargo.toml, Makefile, docs/reference/components/sources/aws_ecs_metrics.cue, docs/reference/urls.cue, src/internal_events/aws_ecs_metrics.rs, src/internal_events/mod.rs, src/sources/aws_ecs_metrics/mod.rs, src/sources/aws_ecs_metrics/parser.rs, src/sources/mod.rs
implements #4683. still a work in progress. need to find a reference implementation to finalize which metric is a gauge and which is a counter. can't find any good documentation on the docker container stats format. in the mean time, would love to get some feedback on if this general approach is sound.
=> feat(new source): ecs/fargate metrics source

src/sinks/statsd.rs, src/sources/stdin.rs
Fixes #5081
I surveyed the other usages of `Stream.forward` and `Sink.send_all`
looking for other places that should be flushing. I just found these
two, the rest follow two patterns:
* `Sink.send_all` / `Stream.forward` used with streams only containing
`Ok`s
* Consuming error in stream and returning `None` to end the stream
=> fix(topology): Flush sinks in a couple of more places

Cargo.lock, Cargo.toml, deny.toml
It doesn't appear we were using it anywhere.
Resolves RUSTSEC-2020-0053
=> chore(deps): Remove dirs
