README.md, docs/performance.md
Closes https://github.com/timberio/vector/issues/568
=> Use MiB not mib in docs

.circleci/config.yml, DEVELOPING.md, Makefile
=> Update Makefile and DEVELOPING.md

.circleci/config.yml
=> Reduce test threads from 8 to 4

.metadata.toml, config/examples/sources/file.toml, config/examples/transforms/add_fields.toml, config/vector.spec.toml, docs/usage/configuration/sources/file.md, docs/usage/configuration/sources/tcp.md, docs/usage/configuration/specification.md, docs/usage/configuration/transforms/add_fields.md
Follow up to https://github.com/timberio/vector/pull/565/files
=> Fix include exclude

.metadata.toml, docs/about/data-model.md, docs/usage/configuration/sources/statsd.md, src/transforms/log_to_metric.rs
Follow up to https://github.com/timberio/vector/pull/563
=> Fix gauge misspelling

CHANGELOG.md, Cargo.lock, src/sinks/aws_s3.rs
=> s3: Add filename extension option and fix trailing slash

src/sources/file.rs
Pulled out of another PR that had too many things going on in it.
=> File tests timeout instead of hang if channel is stuck open.

Cargo.lock, Cargo.toml, lib/tracing-limit/src/lib.rs, lib/tracing-metrics/src/lib.rs, src/main.rs
=> Add `--color` option and tty check for ansi colors

src/sinks/aws_cloudwatch_logs.rs
=> Fix cloudwatch test by dropping sink

docs/usage/configuration/sinks/blackhole.md
=> Fix argument type

.circleci/config.yml, src/test_util.rs, src/topology/mod.rs, tests/basic_tcp.rs, tests/crash.rs
=> fix: test thread usage to ensure tests pass on all machines

proto/event.proto, src/event/metric.rs, src/event/mod.rs, src/sinks/prometheus.rs, src/sources/statsd/parser.rs, src/transforms/log_to_metric.rs
This is a follow up of #567. Better to read commit by commit.
=> feat(metrics): Refactor metrics sampling, rename Timer to Histogram

Cargo.lock
=> fix: Update smallvec to `v0.6.10`

src/transforms/log_to_metric.rs
=> feat(metrics): push Histogram and Set metrics from logs

src/transforms/log_to_metric.rs
Signed-off-by: Alexey Suslov <alexey.suslov@gmail.com>
=> chore: remove labels support from log_to_metric

CONTRIBUTING.md, docs/setup/installation/README.md
This PR fixes minor typos in the `CONTRIBUTING.MD` and the installation `README` files
=> docs: fix spelling in READMEs

src/transforms/log_to_metric.rs
Closes #386.
Left out of scope of this PR:
- rate limited tracing
- interpolation of `field`s
=> feat(metrics): use templates for metric names in log_to_metric

docs/setup/getting-started/sending-your-first-event.md
Fixes minor typos in getting-started
=> docs: minor fixes in getting-started page

.circleci/config.yml
Related to https://github.com/timberio/vector/issues/699
=> fix: Disable armv7 musleabihf build

lib/tracing-limit/benches/limit.rs, lib/tracing-limit/examples/basic.rs, lib/tracing-limit/src/lib.rs
=> feat: Add rate limit notice when it starts

src/sources/statsd/mod.rs, src/sources/statsd/parser.rs
=> chore: add prometheus histograms test

.circleci/config.yml, scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
A few small improvements for the builder.
=> fix: Improve x86_64-unknown-linux-musl build

src/sinks/prometheus.rs, src/sources/statsd/mod.rs
=> feat(prometheus sink): Support sets

.metadata.toml, config/vector.spec.toml, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/specification.md, src/sinks/elasticsearch.rs
As the title says. Closes #361 
=> feat(elasticsearch sink): Add support for additional headers

.metadata.toml, CHANGELOG.md, config/vector.spec.toml, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/specification.md, src/sinks/elasticsearch.rs
=> feat(elasticsearch sink): Add support for custom query parameters

src/sinks/prometheus.rs, src/sources/statsd/mod.rs
=> feat(prometheus sink): add labels support

.metadata.toml, config/examples/complete/file_to_prometheus.toml, config/vector.spec.toml, docs/usage/configuration/sinks/prometheus.md, docs/usage/configuration/specification.md, src/sinks/prometheus.rs, src/sources/statsd/mod.rs
=> feat(prometheus sink): add namespace config

.companies.toml, .metadata.toml, README.md, scripts/generate/metadata.rb, scripts/generate/templates/README.md.erb
We should start collecting a list of companies using Vector build credibility and promote our users.
=> docs: add companies list

.metadata.toml, config/vector.spec.toml, docs/usage/configuration/specification.md, docs/usage/configuration/transforms/log_to_metric.md, scripts/generate/templates/docs/usage/configuration/transforms/log_to_metric.md.erb, src/transforms/log_to_metric.rs
=> feat(log_to_metric transform): add tags support

Cargo.lock, Cargo.toml, src/sources/udp.rs
=> chore(udp source): Use new UdpFramed

src/sinks/elasticsearch.rs
While testing Elasticsearch AWS authentication, I discovered that I made the `headers` and `query` fields non-optional, which makes configuring an Elasticsearch sink awkward. This fixes that deficiency.
=> feat(elasticsearch sink): Make headers and query optional

.circleci/config.yml, .metadata.toml, config/vector.spec.toml, docker-compose.yml, docs/usage/configuration/sinks/elasticsearch.md, docs/usage/configuration/specification.md, src/region.rs, src/sinks/elasticsearch.rs
=> feat(elasticsearch sink): Support AWS authentication

src/sinks/elasticsearch.rs
The elasticsearch AWS support and the error types PRs crossed paths and I left this one undone. I only noticed after I merged the PR.
=> feat(elasticsearch sink): Fix config parser error return type

src/transforms/add_fields.rs
=> fix(add_fields transform): rename config tag

src/main.rs
=> feat(config): default config path "/etc/vector/vector.toml"

scripts/package-deb.sh
=> fix(testing): Remove $VERSION from package-deb

.circleci/config.yml
=> fix(workflow): Use vendored OpenSSL for x86_64-unknown-linux-musl CI build

scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
Closes https://github.com/timberio/vector/issues/922
=> chore(operations): add git to musl builder

.meta/sinks/kafka.toml, config/vector.spec.toml, docs/usage/configuration/sinks/kafka.md, docs/usage/configuration/specification.md
=> docs: fix incorrect description of kafka option

.circleci/config.yml, Makefile, distribution/install.sh
This adds a workflow task as part of CI to sync the contained `distribution/install.sh` file, removing the human step to remember to push updated.
Ref https://github.com/timberio/vector/pull/957
=> chore(operations): Sync and verify install.sh

.circleci/config.yml
Adds a verification step for installing on mac.
=> chore(operations): Verify installation script on mac

.circleci/config.yml
Verifies that the https://sh.vector.dev script works. This ensures that the file is reachable.
=> chore(operations): Verify that sh.vector.dev works

src/topology/config/mod.rs
=> fix(config): default data_dir to /var/lib/vector

distribution/install.sh
=> chore(operations): Add sudo when installing via dpkg or rpm

src/template.rs
=> fix: correctly identify dynamic templates

tests/buffering.rs
=> chore(testing): Put buffering tests behind `leveldb` feature

Cargo.lock
=> chore(operations): Update leveldb-sys up to 2.0.5

src/transforms/regex_parser.rs
=> fix(regex_parser transform): Set default `drop_field` to true

src/sinks/datadog_metrics.rs
=> enhancement(datadog_metrics sink): Use metric buffer in Datadog sink

Cargo.lock
=> chore(operations): Update lock file for 0.6

Makefile
This PR adds a new `clean` target to Makefile that currently just invokes `cargo clean`.
=> enhancement(operations): Add `clean` target to Makefile

src/transforms/json_parser.rs
=> fix(json_parser transform): Fixes a bug droping parsed field

README.md, README.md.erb
=> docs: Fix components link in README

scripts/build-archive.sh
Closes https://github.com/timberio/vector/issues/1203.
=> fix(operations): Fix restoring of `rust-toolchain` file

.circleci/config.yml
This adds building of nightly and release archives for `armv7-unknown-linux-musleabihf`.
=> chore(operations): Produce archives for `armv7-unknown-linux-musleabihf`

.circleci/config.yml, scripts/docker-run.sh
This PR undoes #1227 and fixes detection of interactive mode.
=> fix(operations): Fix invocation of check jobs

.circleci/config.yml, Cargo.toml
Closes https://github.com/timberio/vector/issues/1238.
=> fix(operations): Make `openssl/vendored` feature optional

scripts/generate/templates/_partials/_install_from_archive_linux.md.erb, website/docs/setup/installation/manual/from-archives.md, website/docs/setup/installation/manual/from-archives.md.erb, website/docs/setup/installation/package-managers/dpkg.md, website/docs/setup/installation/package-managers/dpkg.md.erb, website/docs/setup/installation/package-managers/rpm.md, website/docs/setup/installation/package-managers/rpm.md.erb
=> docs: Reference exact latest version instead of "latest" in download urls

.circleci/config.yml, tests/crash.rs
Closes #1257, closes #1258, supersedes #1259, ref #1180.
=> fix(testing): Add timeouts to crash tests

scripts/release-s3.sh
This PR sets up redirects for links to historical `x86_64-unknown-linux-gnu` archives (see https://github.com/timberio/vector/issues/860#issuecomment-558090251).
Note that these redirects need to be created in CI and not manually because we want to create them at the same time as we release the next version to S3, not before or after it.
Closes https://github.com/timberio/vector/issues/860.
=> chore(operations): Set up redirects for x86_64-unknown-linux-gnu archives

scripts/release-s3.sh
Fix filename used for S3 package verification.
=> fix(operations): Fix S3 release verification

.circleci/config.yml, .meta/installation.toml, scripts/package-rpm.sh, website/docs/setup/installation/package-managers/rpm.md, website/metadata.js
This PR adds building of RPM packages for ARM architectures to CI.
Closes https://github.com/timberio/vector/issues/1275.
=> chore(operations): Build RPM packages for ARM

.meta/team.toml, README.md, scripts/util/metadata.rb, website/docs/reference/env-vars.md, website/docusaurus.config.js, website/metadata.js, website/sidebars.js, website/src/css/custom.css, website/src/pages/community.js, website/src/pages/community.module.css, website/src/pages/index.css, website/src/pages/index.module.css, website/src/theme/Navbar/index.js
This adds a community page with a mailing list CTA. I wanted to get this out of the way for some of the blog and release notes changes I'm making for `0.6.0`.
=> chore(website): Add community page with mailing list

src/event/metric.rs, src/sinks/util/buffer/metrics.rs
Few metric buffer optimisations and fixes. It's best to read each commit separately.
Closes #976
=> perf(metric data model): Performance optimisations in metric buffer

src/sinks/datadog_metrics.rs
=> fix(datadog_metrics sink): Rename `datadog` serde tag into `datadog_metrics`

scripts/ci-docker-images/builder-aarch64-unknown-linux-musl/Dockerfile, scripts/ci-docker-images/builder-armv7-unknown-linux-musleabihf/Dockerfile, scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
Closes https://github.com/timberio/vector/issues/1320.
=> chore(operations): Use LLVM-9 from the distribution repository

Cargo.lock, Cargo.toml
=> chore(docker source): Update `shiplift 0.6`

src/transforms/grok_parser.rs
=> fix(grok_parser transform): Add missing rate limited log

README.md, README.md.erb, distribution/docker/README.md, distribution/docker/README.md.erb, scripts/util/metadata/links.rb, website/blog/2019-11-19-arm-support-on-linux.md, website/docs/about/correctness.md, website/docs/about/what-is-vector.md, website/docs/meta/glossary.md, website/docs/reference/sources/file.md, website/docs/reference/sources/file.md.erb, website/docs/reference/transforms/grok_parser.md, website/docs/reference/transforms/grok_parser.md.erb, website/docs/reference/transforms/json_parser.md, website/docs/reference/transforms/json_parser.md.erb, website/docs/reference/transforms/regex_parser.md, website/docs/reference/transforms/regex_parser.md.erb, website/docs/setup/deployment/roles/agent.md, website/docs/setup/deployment/roles/agent.md.erb, website/docs/setup/deployment/roles/service.md, website/docs/setup/deployment/roles/service.md.erb
Fixes the performance link in the ARM architecture announcement.
=> fix(website): Fix performance comparison link

website/docs/reference/sources/statsd.md, website/docs/reference/sources/statsd.md.erb
=> docs: Update StatsD timestamp section

src/sinks/util/rusoto.rs
=> chore(networking): Fix https rusoto connections

src/sinks/clickhouse.rs, src/sinks/elasticsearch.rs, src/sinks/http.rs, src/sinks/splunk_hec.rs, src/sinks/util/http.rs
=> chore(networking): Update healtchecks to use resolver

.circleci/config.yml
=> fix(operations): Fix `rustup` for `x86_64-pc-windows-msvc` in CI

src/sinks/datadog_metrics.rs
=> enhancement(datadog_metrics sink): Send min from distributions

src/sinks/gcp_pubsub.rs
This adapts PR #1403 to the GCP pubsub sink, which crossed paths with those changes.
=> feat(gcp_pubsub sink): Use custom DNS resolver

CONTRIBUTING.md
=> chore(docs): links in `CONTRIBUTING.md`

src/sources/splunk_hec.rs
=> enhancement(splunk_hec source): Provide timestamp

tests/buffering.rs
=> fix(buffers): Re-enable buffering reclaim test

Cargo.lock, Cargo.toml, benches/batch.rs, benches/bench.rs, benches/buffering.rs, benches/files.rs, benches/http.rs
=> chore(testing): Update benches and minor cleanup

.meta/sources/docker.toml, config/vector.spec.toml, src/sources/docker.rs, website/docs/reference/sources/docker.md
=> chore(docker source): Merge fix

website/docs/about/data-model/metric.md
Counter value cannot be decremented, not incremented.
=> docs: Fix metrics documentation typo

.meta/sinks/aws_cloudwatch_logs.toml, .meta/sinks/aws_cloudwatch_metrics.toml, .meta/sinks/aws_kinesis_firehose.toml, .meta/sinks/aws_kinesis_streams.toml, .meta/sinks/aws_s3.toml, .meta/sinks/clickhouse.toml, .meta/sinks/datadog_metrics.toml, .meta/sinks/elasticsearch.toml, .meta/sinks/gcp_pubsub.toml, .meta/sinks/http.toml, .meta/sinks/kafka.toml, .meta/sinks/new_relic_logs.toml, .meta/sinks/splunk_hec.toml, config/vector.spec.toml, scripts/generate/templates/_partials/_component_sections.md.erb, scripts/util/metadata/sink.rb, src/sinks/aws_kinesis_firehose.rs, src/sinks/clickhouse.rs, src/sinks/elasticsearch.rs, src/sinks/http.rs, src/sinks/new_relic_logs.rs, src/sinks/util/http.rs, tests/config.rs, website/docs/reference/sinks/clickhouse.md, website/docs/reference/sinks/elasticsearch.md, website/docs/reference/sinks/http.md, website/metadata.js, website/src/components/VectorComponents/index.js
=> chore(config)!: Rename `basic_auth` to `auth` and unflatten

src/sinks/util/service.rs
So it looks like in #1189 the inner service was never polled ready and thus in some very small cases would let the inner service panic because it violated the contract of `tower_service::Service`. The contract states that if you never get a `Async::Ready` from `Service::poll_ready` and you call `Service::call`, call can panic. The fix is easy and originally we should have included a test since our mocking utils in `tower-test` check for this specific behavior. I've verified I can reproduce the panic with the test and the current fix does in fact fix it.
Fixes #1568
=> fix(aws_s3 sink): Poll inner service in `Map` svc

src/sinks/aws_kinesis_firehose.rs
The current healthcheck uses `list_delivery_streams` method with `exclusive_start_delivery_stream_name` parameter set to the name of the current stream. The response from AWS returns streams with names after the given stream name, so it leads to errors like 
```
22 16:29:36.082 ERROR vector::topology::builder: Healthcheck: Failed Reason: Stream names do not match, got other-independent-stream, expected my-log-stream
```
The problem was reported [in the chat](https://gitter.im/timberio-vector/community?at=5e287be73b40ea043c82daaa).
This PR replaces the method used for healthcheck with `describe_delivery_stream`.
=> fix(aws_kinesis_firehose sink): Fix `aws_kinesis_firehose` sink healthcheck

.meta/sinks/socket.toml, .meta/sinks/vector.toml, config/vector.spec.toml, website/docs/reference/sinks/socket.md, website/docs/reference/sinks/vector.md
=> chore(docs): Fix socket sink docs

.circleci/config.yml, distribution/nix/default.nix.erb, tests/config.rs
Ref #1527
Please go ahead and merge this if you approve @a-rodin
=> chore(testing): wrap failing test in feature flag

.circleci/config.yml, scripts/release-github.rb
This PR fixes the CI invocation of `make release-github`.
=> fix(operations): Fix `release-github` CI job

.circleci/config.yml, scripts/release-homebrew.sh
This PR fixes the authentication issues in the Homebrew releaser.
=> chore(operations): Fix `release-homebrew` CI job

.meta/sinks/sematext.toml, config/vector.spec.toml, src/sinks/sematext.rs, website/docs/reference/sinks/sematext.md
=> fix(sematext sink): Fix EU endpoint and docs

scripts/ci-docker-images/builder-armv7-unknown-linux-musleabihf/Dockerfile
This fixes broken nightly builds:
https://circleci.com/gh/timberio/vector/81112
=> chore(operations): Fix COPY path for armv7 Docker image

Cargo.lock, Cargo.toml, lib/tracing-limit/Cargo.toml, lib/tracing-metrics/Cargo.toml
Fixes https://github.com/timberio/vector/issues/1670
=> chore: Upgrade `tracing-subscriber 0.2.0-alpha.5` 

CONTRIBUTING.md
=> docs: Fix the SECURITY.md link at CONTRIBUTING.md

config/examples/docs_example.toml, config/examples/es_s3_hybrid.toml, website/docs/setup/configuration.md
This fixes `make check-examples` check.
=> docs: Fix `aws_s3` sink examples

src/sinks/util/retries.rs
=> fix(networking): Warn log for non retryable req

.meta/sinks/sematext.toml, config/vector.spec.toml, src/sinks/sematext.rs, website/docs/reference/sinks/sematext.md, website/docs/reference/sinks/sematext.md.erb
=> fix(sematext sink): Rename cloud and add host

REVIEWING.md, SECURITY.md
Follow up changes based on the comments in https://github.com/timberio/vector/pull/1642.
=> docs: Fixup security language

src/sinks/sematext.rs
This is technically a breaking change if we reject configs that we were previously accepting, but I'm not sure we should really care in this case.
=> chore(sematext sink): make host calculation more explicit

.github/CODEOWNERS
Alexey was a contractor that focused on our initial metrics support. He's embarking on a long personal vacation and will be stepping away for a little while. @lukesteensen has the most context on the metrics. I'm happy to swap in others if they feel confident to review these parts of the code.
=> chore: Update Alexey in CODEOWNERS

.circleci/config.yml, scripts/docker-run.sh
This PR add `--rm` flag to Docker arguments in `docker-run.sh` which ensures that all containers are deleted on exit.
=> chore(operations): Improve `docker-run.sh` script

.circleci/config.yml, scripts/ci-docker-images/verifier-nixos/Dockerfile, scripts/verify-nix.sh
This PR fixes such failures as https://circleci.com/gh/timberio/vector/82267.
=> chore(operations): Fix `verify-nixos` CI check

.meta/.schema.json, .meta/log_fields.toml, .meta/sources/file.toml, .meta/sources/syslog.toml, .meta/transforms/geoip.toml, scripts/generate/templates.rb, website/docs/about/data-model/log.md, website/docs/reference/sources/file.md, website/docs/reference/sources/syslog.md, website/docs/reference/transforms/geoip.md
Closes #1763 
I've also added this part of the `.meta` schema to be validated by our JSON schema. I am chipping away at adding all validations there.
=> chore(website): Fix nested field documentation

.meta/sinks/humio_logs.toml, config/vector.spec.toml, src/sinks/humio_logs.rs, website/docs/reference/sinks/humio_logs.md
=> chore(humio_logs sink): Remove encoding option

.meta/.schema.json, .meta/tests.toml, scripts/util/metadata.rb, website/docs/reference/tests.md, website/docs/reference/tests.md.erb
This fixes the broken unit tests reference page. It also adds this branch of the metadata to the meta JSON schema for validation.
=> docs: Fix unit tests reference

tests/behavior/transforms/ansi_stripper.toml, tests/behavior/transforms/coercer.toml, tests/behavior/transforms/concat.toml, tests/behavior/transforms/grok_parser.toml, tests/behavior/transforms/json_parser.toml, tests/behavior/transforms/logfmt_parser.toml, tests/behavior/transforms/regex_parser.toml, tests/behavior/transforms/split.toml, tests/behavior/transforms/tokenizer.toml
=> chore(testing): Add more behavior tests for transforms

website/docusaurus.config.js, website/package.json, website/src/css/custom.css, website/src/theme/BlogListPage/index.js, website/src/theme/CodeBlock/index.js, website/src/theme/CodeBlock/styles.module.css, website/src/theme/DocItem/index.js, website/src/theme/DocSidebar/index.js, website/src/theme/DocSidebar/styles.module.css, website/src/theme/Footer/index.js, website/src/theme/Layout/index.js, website/src/theme/Navbar/index.js, website/yarn.lock
There are a lot of good changes and fixes in this release, and because we "swizzle" theme componentns I want to make sure we stay up to date with incremental changes.
=> chore(website): Update to docusaurus 2.0.0-alpha.41

src/topology/unit_test.rs
Unit tests now fail for outputs that specify conditions but do not extract events. Conditions must now only pass for one event when multiple are consumed.
Fixes #1813
Fixes #1810
=> fix(cli): Ensure zero output unit tests fail

benches/bench.rs, benches/lua.rs, src/topology/builder.rs, src/topology/config/mod.rs, src/topology/unit_test.rs, src/transforms/add_fields.rs, src/transforms/add_tags.rs, src/transforms/ansi_stripper.rs, src/transforms/aws_ec2_metadata.rs, src/transforms/coercer.rs, src/transforms/concat.rs, src/transforms/field_filter.rs, src/transforms/geoip.rs, src/transforms/grok_parser.rs, src/transforms/json_parser.rs, src/transforms/log_to_metric.rs, src/transforms/logfmt_parser.rs, src/transforms/lua.rs, src/transforms/merge.rs, src/transforms/regex_parser.rs, src/transforms/remove_fields.rs, src/transforms/remove_tags.rs, src/transforms/sampler.rs, src/transforms/split.rs, src/transforms/tokenizer.rs, tests/support/mod.rs
=> chore(transforms): Add transform context

proto/event.proto, src/event/discriminant.rs, src/event/mod.rs
See https://github.com/timberio/vector/pull/1662#issuecomment-587362041 for details.
=> enhancement!: Support `Array` and `Map` kinds in `Value`

website/src/pages/press.js
The bio needs a lot of work. Some of our partners need this for co-marketing so I wanted to get it started.
=> chore: Add description and bio to press page

Makefile
Closes  #1834, see https://github.com/timberio/vector/issues/1834#issuecomment-590247290 for explanation.
=> chore(testing): Reduce RAM usage when running `make test`

src/sinks/clickhouse.rs
While prodding around I noticed the request config fields aren't actually nested for the clickhouse sink.
=> fix(clickhouse sink): Nest request fields

src/main.rs, src/trace.rs
=> Revert "feat(cli): Add `log-format` cli option"

src/sources/kubernetes/file_source_builder.rs
Apologies for breaking the tests.
=> chore(kubernetes source): Fix warning about unused import

src/transforms/kubernetes/watch_client.rs
=> chore(testing): Allow kubernetes tests to compile

tests/behavior/transforms/merge.toml
This is not expected to work yet, as it depends on #1819.
Closes #1807.
=> chore(testing): Add behavior test for the `merge` transform

Cargo.lock, Cargo.toml, src/sinks/kafka.rs, src/sources/kafka.rs
=> chore: Upgrade rdkafka to 0.23.1

Cargo.lock, lib/file-source/Cargo.toml, lib/file-source/src/file_server.rs, src/sources/file/mod.rs
As a side note, it seems like we don't test `lib/*` in CI. I'll check and create an issue if that's so.
=> chore: Upgrade lib/file-source to futures 0.3

src/topology/builder.rs, src/transforms/mod.rs
This adds a new `Transform::transform_stream` which allows consumers to
return their own type erased `Stream`. This should allow all various
types of advanced transforms, while still supporting simpler transforms
with a simpler API.
This fixes trait size issues by using arbitrary self types!
aka we were unable to call this type of trait fn:
```rust
fn transform_stream(self) -> Box<dyn Stream> { ... }
```
This is because the local `self` is required to be sized to be able to call it from a unsized trait object like `Box<dyn Transform>` which is what we use internally within topology.
To fix this we can use arbitrary self types to tell the compiler that we know what type of indirection we are using for the trait object. This allows us to call this code from a trait object backed by a boxed …
=> chore(topology): Allow transforms to implement `Stream`

src/sources/kubernetes/test.rs
With #1912 we switched to using `checksum` strategy for `file source` used in `kubernetes source`. This caused the tests to start failing because logs with which testing is done are smaller than 256B so they weren't picked up by the `file source`.
This PR increases size of logs to be larger than 256B.
=> chore(kubernetes source): Increase test log size

.circleci/config.yml, docker-compose.yml
This is a follow up from https://github.com/timberio/vector/pull/1922#issuecomment-591527197 (see thread).
=> chore: Add TEST_LOG to test-stable CI job

src/sinks/humio_logs.rs
=> fix(humio_logs sink): Correct typetag

src/generate.rs
Adds a flag `--fragment` (`-f`) that prevents the addition of global fields when generating a config. This makes it easier to generate a file using multiple generate commands, or using generate to append more components to an existing config.
Closes #1851
=> feat(cli): Add fragment flag to generate subcmd

.circleci/config.yml
=> fix(operations): Pull fresh containers on test

src/sinks/statsd.rs
=> chore(statsd sink): Fix race condition in test

src/sources/logplex.rs
Refactoring the logplex source to reuse code from the http source.
Mainly, this moves the creation of the warp server out of the logplex code.
=> chore(logplex source): refactor to use util/HttpSource

website/docs/reference/sinks/splunk_hec.md
=> chore(docs): Re-run doc generation

src/event/util/log/path_iter.rs, website/docs/reference/field-path-notation.md, website/docs/reference/field-path-notation.md.erb
=> enhancement(config)!: Support escaping in the field path notation

website/yarn.lock
=> chore(website): Upgrade dependencies

src/sinks/gcp/mod.rs, src/sinks/gcp/stackdriver_logging.rs, src/sinks/splunk_hec.rs
This is a follow up PR to #2072 and upgrades splunk and stackdriver. Next PR will contain more drastic changes to allow partition batching via `HttpSink`.
=> chore(sinks): Part 2 of `HttpSink` refactor

src/stream.rs
=> chore: Correct doctest at src/stream.rs

src/sinks/util/http.rs
=> chore(networking): Add proper user agent

.meta/sinks/splunk_hec.toml, config/vector.spec.toml, docker-compose.yml, src/sinks/splunk_hec.rs, website/docs/reference/sinks/splunk_hec.md
=> enhancement(splunk_hec sink): Support specifying custom index names

.github/workflows/test-harness.yml
=> chore: Upstream github-script action at test harness workflow

.github/workflows/test-harness.yml
=> chore: Switch to upstream repo-permission-check-action

distribution/install.sh
=> chore: Remove package managers from install script

.meta/sinks/clickhouse.toml, .meta/sinks/datadog_logs.toml, .meta/sinks/elasticsearch.toml, .meta/sinks/gcp_stackdriver_logs.toml, .meta/sinks/http.toml, .meta/sinks/splunk_hec.toml, config/vector.spec.toml, src/sinks/util/http.rs, src/tls/settings.rs, website/docs/reference/sinks/clickhouse.md, website/docs/reference/sinks/datadog_logs.md, website/docs/reference/sinks/elasticsearch.md, website/docs/reference/sinks/gcp_stackdriver_logs.md, website/docs/reference/sinks/http.md, website/docs/reference/sinks/splunk_hec.md
=> chore(networking): Enable verify_hostname for http

.github/labels.yml, .github/labels.yml.erb
I feel the need for this label. This should help classify the importance of this feature and it'll help when trying to understand which issues are high priority.
=> chore: Add `have: *` labels

scripts/generate/templates/_partials/_strategies.md.erb, scripts/util/core_ext/accessible_hash.rb
=> chore(website): Fix `make generate` command

Makefile
Allows our Windows users to run `make test` etc.
=> chore(windows platform): Improve Windows Makefile support

tests/topology.rs
=> chore(topology): disable flaky test

src/sources/kubernetes/test.rs, src/transforms/kubernetes/mod.rs
Adds tests mentioned in [comment](https://github.com/timberio/vector/pull/1888#issuecomment-607355861).
=> chore(kubernetes_pod_metadata transform): Add field tests

src/topology/mod.rs
=> chore(topology): Add basic module docs

src/sinks/influxdb_metrics.rs
=> fix(influxdb_metrics sink): Pass tls to healthcheck

src/sinks/aws_kinesis_streams.rs
Closes #622 with the same approach as in https://github.com/timberio/vector/pull/1573.
=> fix(aws_kinesis_firehose sink): Fix healthcheck

src/transforms/aws_ec2_metadata.rs
This PR changes how we make requests in the ec2_metadata transform to only dispatch the request if the field is requested.
Closes #2257
=> fix(aws_ec2_metadata transform): Only run required requests

.meta/transforms/lua.toml, config/vector.spec.toml, src/config_paths.rs, src/main.rs, src/transforms/lua/v2/mod.rs, website/docs/reference/transforms/lua.md, website/docs/reference/transforms/lua.md.erb
=> enhancement(lua transform)!: Set `search_dirs` to config dirs by default

src/sources/docker.rs
ref #2108 
Wires `ShutdownSignal` for `docker source` .
=> chore(docker source): Wire `ShutdownSignal`

src/main.rs
=> fix(windows platform): Fix Windows metrics

.circleci/config.yml, .github/workflows/test-harness.yml, Cargo.toml, scripts/build-archive.sh
=> perf: Add `lto = true` and `codegen-units=1` to `Cargo.toml`

website/src/theme/Layout/index.js
Add twitter author tags.
This hopefully will notify us if folks post our URLS!
=> chore(website): Add Twitter author tags

CONTRIBUTING.md
This helps to explain our new "highlights" concept. Please let me know if anything is not clear.
=> docs: Add highlights section to contributing

.meta/team.toml, website/metadata.js
I felt vain and wanted to update my bio.
=> chore(website): Update Ana bio

src/sources/splunk_hec.rs
=> chore(splunk_hec source): Wire with `ShutdownSignal`

.github/workflows/ci.yml, scripts/check-component-features.sh, scripts/generate.rb, website/metadata.js
Stages the component feature check with a bit of cleaning in between. This should make it pass on CI again.
=> chore(platforms): Reenable component feature check

.github/workflows/cancel.yml, .github/workflows/checklist.yml, .github/workflows/labels.yml, .github/workflows/linting.yml
Cancels previous workflows if a new one is triggered.
=> chore(operations): Cancel previous builds automatically

tests/Makefile
This is pull request #1 in a series of pull requests for #2368. I am preparing to consolidate our root `Makefile` with the `tests/Makefile`. This first change introduces stylistic changes only, no behavioral changes.
cc @a-rodin
=> chore(operations): Stylize tests/Makefile

Cargo.lock, Cargo.toml
=> chore(dependencies): Upgrade `snafu` to `0.6`

.github/workflows/nightly.yml
=> chore(operations): Fix typo at nightly CI workflow

.github/workflows/nightly.yml, Makefile, docker-compose.yml, scripts/build.sh, scripts/package-archive.sh, scripts/package-deb.sh, scripts/package-msi.sh, scripts/package-rpm.sh
The default for `NATIVE_BUILD` changed and this makes it explicit.
=> chore(operations): Fix nightly builds

src/sinks/splunk_hec.rs
=> fix(splunk_hec sink): Add indexed fields in `text` encoding

src/transforms/aws_ec2_metadata.rs
Reference #2477 
This PR is broken up into two main commits, the first commit upgrades the sink to use our internal HTTP client and the second commit allows us to treat `namespace = ""` as if it were never set.
cc @binarylogic
=> fix(aws_ec2_metadata transform): Treat empty namespaces as not set

CONTRIBUTING.md
Closes #2293 
I'm sure there are many improvements we can make to this process, but this is how I've been profiling.
=> docs: add profiling instructions

Cargo.lock, Cargo.toml
=> chore: Finish git merge

src/tls/mod.rs, src/tls/settings.rs
=> fix(security): Use specific error for x509 from system ca

.github/workflows/check.yml, docker-compose.yml, scripts/check-code.sh, src/tls/settings.rs
Prevents surprising compilation errors when releasing since we build on Windows.
=> chore(operations): Check code on Windows

distribution/rpm/vector.spec, scripts/package-rpm.sh
=> chore(operations): RPM build fix

distribution/rpm/vector.spec
=> chore: do not create /LICENSE and /README.md at RPM package

src/sinks/loki.rs
close #2535 
Signed-off-by: Alexandre Nicolaie <alexandre.nicolaie@gmail.com>
=> fix(loki sink): replace OrigID with OrgID

.github/workflows/code.yml
=> chore(operations): Upgrade deny action

.github/workflows/code.yml
=> chore(operations): Fix rustfmt

.github/workflows/code.yml
=> chore(operations): Disable `check-version` check

src/sinks/datadog/metrics.rs
=> fix(datadog_metrics sink): Use post requests

src/sinks/aws_kinesis_firehose.rs, src/sinks/util/mod.rs, src/sinks/util/rusoto2.rs
Reference https://github.com/timberio/vector/issues/2118#issuecomment-618073885
This is broken up into logical commits for review.
=> chore(sinks): Upgrade internal rusoto utilities

.github/workflows/code.yml, deny.toml
`RUSTSEC-2019-0031` not actual after #1648
=> chore(operations): Improve check-advisories CI job

.github/workflows/code.yml
This is temporary to unblock the processes. I'll submit a proper fix later.
=> chore(operations): Force disable k8s tests in CI

src/sinks/util/http2.rs
=> chore(sinks): Add `BatchedHttpSink` back to `http2`

src/sinks/clickhouse.rs, src/sinks/mod.rs
=> chore(clickhouse sink): Upgrade `clickhouse`

src/topology/mod.rs
Closes  #2109.
Blocked on ~~#2108~~ #2551.
=> chore(topology): Update shutdown deadlines

src/sinks/aws_s3.rs
=> fix(aws_s3 sink): Allow removed keys to be used for partitioning

src/sinks/http.rs
=> chore(http sink): Error on auth section and Auth header

Cargo.lock, Cargo.toml, docker-compose.yml
Fix up the failing Loki tests on master.
=> fix(tests): Fixup loki tests

website/docs/reference/transforms/json_parser.md, website/docs/reference/transforms/json_parser.md.erb
=> docs: Fix invalid link in JSON Parser transform

src/topology/mod.rs
=> fix(topology): Check if `transform`/`sink` is present

scripts/package-deb.sh
=> chore: Display free space at package deb task

.meta/sinks/humio_logs.toml.erb, config/vector.spec.toml, website/docs/reference/sinks/humio_logs.md
=> docs(humio_logs sink): Fix default host value

Makefile, scripts/install-git-hooks.sh
This significantly simplifies the use of git worktrees.
=> chore: A script to install git hooks

.meta/sources/syslog.toml.erb, src/sources/syslog.rs, website/docs/reference/sources/syslog.md, website/yarn.lock
Resolves https://github.com/timberio/vector/issues/2655 by adding `source_ip` and `hostname` fields that are always set.
=> chore(syslog source): Add `hostname` and `source_ip`

rfcs/2020-05-25-2064-dev-workflow-simplification.md, rfcs/2020-05-25-2685-dev-workflow-simplification.md
Adds the Dev workflow simplification RFC from https://www.notion.so/timber/Dev-Workflow-Simplification-c0990440bb494a71bc1150a52a4494d2
=> feat(platforms): Add dev workflow simplification rfc

.github/workflows/blog.yml, .github/workflows/generate.yml
This aligns the workflows with the actual files they match.
=> chore(operations): Split website workflow into generate and blog

src/sinks/prometheus.rs
Upgrades hyper for `prometheus` sink
Ref. #2117
=> chore(prometheus sink): Upgrade `hyper`

src/sinks/pulsar.rs
Just a small test fix for #2671 .
=> chore(pulsar sink): Fix test

src/sources/splunk_hec.rs
=> chore(splunk_hec source): Upgrade `hyper`

src/sinks/gcp/cloud_storage.rs, src/sinks/gcp/mod.rs, src/sinks/util/service2.rs
Upgrades direct and indirect usages of `hyper`.
Ref. #2117
=> chore(gcp_cloud_storage sink): Upgrade `hyper`

src/sinks/influxdb/metrics.rs, src/sinks/influxdb/mod.rs
=> chore(influxdb_metrics sink): Upgrade `hyper`

benches/http.rs, src/sinks/http.rs, src/sinks/influxdb/logs.rs, src/sinks/logdna.rs, src/sinks/new_relic_logs.rs, src/sinks/sematext_logs.rs, src/sinks/util/test.rs, src/sources/statsd/mod.rs
Updates tests and benches.
Ref. #2117
=> chore(tests): Upgrade `hyper`

src/transforms/aws_ec2_metadata.rs
=> chore(aws_ec2_metadata transform): Upgrade `hyper`

src/sinks/statsd.rs
=> chore(statsd sink): tower update

Cargo.lock, Cargo.toml, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs
=> chore: update rusoto to 0.44.0

src/hyper.rs, src/internal_events/prometheus.rs, src/lib.rs, src/sources/prometheus/mod.rs, src/transforms/aws_ec2_metadata.rs
Ref. #2117
This also updates `hyper-openssl` in the source.
=> chore(prometheus source): Update hyper

src/sources/prometheus/mod.rs
=>  chore(prometheus source): Update hyper in tests

Cargo.lock, Cargo.toml, src/sinks/elasticsearch.rs, src/sinks/util/rusoto2.rs, src/sinks/util/service2.rs
Moved from #2777 
`signature` was moved from `rusoto_core` to new crate `rusoto_signature`
=> chore(elasticsearch sink): update rusoto to 0.44.0

src/topology/config/watcher.rs
Fixes flaky `topology::config::watcher::tests::multi_file_update` test.
This a small change in tests so I'll merge it as soon it passes checks.
=> chore(tests): Properly synchronize file updates in `watcher` test

Cargo.lock, Cargo.toml, Makefile, src/event/mod.rs, src/sinks/splunk_hec.rs, src/sources/http.rs, src/sources/logplex.rs, src/sources/splunk_hec.rs, src/sources/util/http.rs
=> chore(dependencies): warp update

scripts/release-s3.sh
=> Fix release verification.

src/sinks/util/http.rs
Closes #2577
While likely not an issue in practice, our `start_send` implementation here was theoretically vulnerable to deadlock.
The issue would occur if the sink's slot was full and the subsequent call to `poll_complete` returned `Async::Ready`. We would then incorrectly return `NotReady` when we actually had the ability to accept the item. This is a problem because no underlying component had returned `NotReady` and our task would therefore not be registered to wake on any future notification.
=> fix(sinks): address potential deadlock

src/sinks/clickhouse.rs, src/sinks/datadog/metrics.rs, src/sinks/datadog/mod.rs, src/sinks/gcp/pubsub.rs, src/sinks/influxdb/logs.rs, src/sinks/influxdb/mod.rs, src/sinks/mod.rs, src/sinks/splunk_hec.rs
Noticed that this code not required now.
=> chore: remove outdated uri code

src/sinks/clickhouse.rs, src/sinks/datadog/metrics.rs, src/sinks/elasticsearch.rs, src/sinks/gcp/pubsub.rs, src/sinks/gcp/stackdriver_logs.rs, src/sinks/honeycomb.rs, src/sinks/http.rs, src/sinks/influxdb/logs.rs, src/sinks/influxdb/metrics.rs, src/sinks/influxdb/mod.rs, src/sinks/logdna.rs, src/sinks/loki.rs, src/sinks/splunk_hec.rs, src/sinks/util/http.rs
Changed for #2859. On HTTP request we need refresh AWS credentials in async function.
=> chore: make HttpSink::build_request async

src/sinks/datadog/logs.rs, src/sinks/papertrail.rs, src/sinks/util/tcp.rs, src/sinks/vector.rs, tests/tcp.rs
=> chore(sinks): Construct tcp healthcheck with TLS

README.md, scripts/generate/templates/_partials/_vector_summary.md.erb, website/docs/about/what-is-vector.md
=> chore: Update README.md

.dependabot/config.yml, .github/labels.yml, .github/semantic.yml, .meta/domains.toml
This PR also reduces the number of times dependabot checks down to weekly.
=> chore(dependencies): Configure dependabot to use correct issue names

.dependabot/config.yml
Fix #2979 , we talked about this. I just forgot to actually push the code...
=> chore(deps): Fixup dependabot config

src/sources/journald.rs
=> chore(journald source): Fix filter_unit_works_correctly test

.meta/links.toml, src/sources/socket/unix.rs, src/sources/syslog.rs, src/sources/util/unix.rs, src/test_util.rs, tests/syslog.rs, website/docs/reference/sources/syslog.md, website/docs/reference/sources/syslog.md.erb
=> enhancement(syslog source): Accept `octet-counting` encoded messages

src/topology/config/watcher.rs
=> chore(tests): Delete `topology::config::watcher::tests::multi_file_update`

tests/syslog.rs
=> chore(tests): Delete `test_udp_syslog` test

tests/buffering.rs
=> chore(tests): Delete `test_max_size_resume`

Cargo.lock, Cargo.toml, src/sinks/pulsar.rs
=> chore(pulsar sink): bump to pulsar-rs 1.0.0

.meta/transforms/coercer.toml.erb, website/docs/reference/transforms/coercer.md
Probably with this change example will be clear. Ref https://github.com/timberio/vector/issues/3071.
=> fix(docs): adjust log event in coercer transform

.rustfmt.toml
Ref. https://github.com/timberio/vector/pull/3063#issuecomment-658595581
=> chore: Fix warning message due .rustfmt.toml

docker-compose.yml, src/sinks/aws_s3.rs
Tested locally, but need confirmation from CI.
=> chore(tests): use localstack instead minio

benches/http.rs
Ref. #2945 
Removes direct dependency on tokio01 in `benches/http.rs`
=> chore: Remove tokio 0.1 from `benches/http.rs`

Cargo.lock, Cargo.toml
=> chore(operations): Update cidr-utils

.github/workflows/release.yml
=> chore(operations): Fixup release-homebrew

RELEASING.md, scripts/release-commit.rb
=> chore(operations): Fixup release commit

.github/workflows/release.yml
This PR should clean up the Windows CI in relation to #2797 .
=> chore(windows platform): Use a simpler CI invocation

src/buffers/mod.rs, src/lib.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/socket.rs, src/sinks/util/buffer/metrics.rs, src/sinks/util/buffer/mod.rs, src/sinks/util/http.rs, src/sinks/util/service.rs, src/sinks/util/service2.rs, src/sinks/util/sink.rs, src/sources/socket/mod.rs
=> chore: deny clippy rule clone_on_ref_ptr

src/internal_events/file.rs, src/internal_events/stdin.rs
Ref. https://github.com/timberio/vector/pull/3151#discussion_r462326066
=> chore: remove rate limit for tracing in internal events

Cargo.toml, src/internal_events/kubernetes_logs.rs, src/sources/kubernetes_logs/parser/docker.rs, src/sources/kubernetes_logs/parser/picker.rs
Ref. #1940 
PR doesn't extract shared code, but specializes it for it's call site. It's a bit faster, shorter, clearer, and has a dependency less.
=> chore: Remove dependency on `transforms-json_parser`

.github/workflows/lints.yml
Ref. https://github.com/timberio/vector/pull/3268#issuecomment-667053779
=> fix: pip3 installed binaries

src/internal_events/kafka.rs, src/internal_events/mod.rs, src/sources/kafka.rs
=> feat(observability): instrument "kafka" source

distribution/kubernetes/kustomization.yaml
~Will be rebased after #2653 is merged.~ :tada:
This PR adds a kustomization base suitable for production deployment.
=> chore: Add kustomization base for k8s production deployments

src/test_util.rs
=> fix: color in not tty for tests

src/event/discriminant.rs, src/lib.rs, src/sources/journald.rs, src/transforms/tag_cardinality_limit.rs
Clippy rule: https://rust-lang.github.io/rust-clippy/master/#ptr_arg
=> chore: set clippy ptr_arg to default

src/internal_events/vector.rs
=> chore(vector source): Tidy up instrumentation

tests/tcp.rs
Introduced by me (@fanatid) in https://github.com/timberio/vector/pull/3188
Temporary fixed by @lukesteensen in https://github.com/timberio/vector/commit/7464fe14607e803448a1f725a92cf681e8e7dcf8
=> fix(tests): tcp merge_and_fork

.github/workflows/lints.yml, .github/workflows/tests.yml, distribution/nix/default.nix.erb
Compress a lot of our CI jobs into fewer jobs.
=> chore(operations): Reduce number of CI jobs

src/sources/file/mod.rs, src/sources/journald.rs
Ref #2945. Finish tokio update in sources. `line_agg.rs` updated by @MOZGIII in https://github.com/timberio/vector/pull/3304
=> chore: update tokio in sources

src/shutdown.rs, src/sources/prometheus/mod.rs, src/sources/socket/mod.rs, src/sources/statsd/mod.rs, src/topology/builder.rs, src/topology/config/watcher.rs, src/topology/fanout.rs, src/topology/mod.rs, src/topology/task.rs, src/validate.rs, tests/topology.rs
Part of https://github.com/timberio/vector/issues/2945
Update tokio in `src/topology`.
=> chore: update tokio in topology

.meta/sinks/loki.toml.erb
This should help to get a better understanding of how to use these examples.
=> docs: update loki label examples

distribution/docker/README.md
-c is the parameter for passing configuration. -V is for version.
=> chore(docker platform): Incorrect flag was specified to pass config file

CONTRIBUTING.md
Meant to include this in #3428 
=> chore(internal docs): Add docs for running nightly tests manually

.github/workflows/nightly.yml
Given we are dropping support for armv7
Hopefully this is the last one!
=> chore(ci): Remove more arm references

src/internal_events/auto_concurrency.rs, src/sinks/util/auto_concurrency/controller.rs
=> chore(networking): Enhance the concurency change trace with more measurements

scripts/environment/bootstrap-macos-10.sh
=> chore(fix): OSX doesn't have realpath - added it via coreutils to the bootstrap

scripts/check-meta.sh, scripts/check-version.rb, scripts/load-meta.rb
=> chore(internal docs): Added some error checking for Make scripts

Makefile
Noticed when investigating issue introduced in #2149
=> chore: less work on shutdown test

.meta/_partials/descriptions/_aws_cloudwatch.toml, .meta/_partials/descriptions/_gcp_stackdriver.toml, .meta/_partials/descriptions/_kafka.toml, .meta/_partials/descriptions/_kubernetes.toml, .meta/_partials/descriptions/_syslog.toml, .meta/_partials/fields/_buffer_options.toml.erb, .meta/_partials/fields/_conditions_options.toml.erb, .meta/_partials/fields/_encoding_options.toml.erb, .meta/_partials/fields/_request_options.toml.erb, .meta/_partials/fields/_tls_acceptor_options.toml.erb, .meta/_partials/fields/_tls_connector_options.toml.erb, .meta/data_model/log.toml, .meta/data_model/metric.toml, .meta/guides.toml, .meta/options.toml, .meta/team.toml, .meta/tests.toml
=> docs(external docs): Some grammar and structure edits to .meta content

.github/CODEOWNERS
=> chore: Add k8s related code parts to CODEOWNERS

.github/CODEOWNERS, src/sources/file.rs, src/sources/util/mod.rs, src/sources/util/multiline_config.rs
This is a follow up from #3451, more specifically https://github.com/timberio/vector/pull/3451#pullrequestreview-467136523.
Let's discuss the proper location for the multiline config here.
=> chore(file source): Multiline config extract

CONTRIBUTING.md
=> fix: Fixed language on code fence in CONTRIBUTING.md

REVIEWING.md
Folks - I've added an expectation that we'll review PRs within 48 business hours as a rough SLA. Feedback welcomed.
=> chore: Update REVIEWING.md to add expectations

src/sources/kubernetes_logs/pod_metadata_annotator.rs
=> enhancement(kubernetes_logs source): Add the ability to store pod labels flat

src/kubernetes/reflector.rs, src/kubernetes/state/delayed_delete.rs, src/kubernetes/state/instrumenting.rs, src/kubernetes/stream.rs, src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/kafka.rs, src/sinks/socket.rs, src/sources/socket/mod.rs, tests/tcp.rs
Part of #3478.
@MOZGIII I'm not sure what I fixed (or not fixed), but kubernetes works fine without `threaded_scheduler` :laughing:
=> chore(tests): fix scheduler issues

Makefile
Maybe it's not a proper fix in the long run, but it'll do for now.
=> chore(administration): Fix `make signoff`

src/api/server.rs
A follow up from https://github.com/timberio/vector/pull/3514#discussion_r479192068
It's the same idea, but lifted to the `graphql_playground` var.
Do you like it?
=> Check if playground is enabled statically

src/internal_events/mod.rs, src/internal_events/remove_tags.rs, src/transforms/remove_tags.rs
Add metrics to remove_events transform, resolving #3403  .
=> chore(remove_tags transform): Add events to remove_tags transform.

rfcs/2020-08-26-3191-host-metrics.md
=> docs: Added host prefix to host-based metrics

.github/CODEOWNERS
=> chore: Fix a typo at codeowners

CONTRIBUTING.md
=> docs: Added metric naming convention - closes #3600

scripts/check-style.sh
Ignores GIF files in `scripts/check-style.sh`, mostly to unblock https://github.com/timberio/vector/pull/3648 but also to encourage liberal peppering of arbitrary memes in RFCs.
=> chore(tests): Add gif to check-style.sh

REVIEWING.md
=> fix(internal docs): Fix CODEOWNERS link

CONTRIBUTING.md
=> docs: Added notes about new sources, sinks, and transforms to CONTRIBUTING.md

rfcs/2020-08-31-3640-nginx-metrics-source.md
=> chore: New `nginx_metrics` source RFC

src/sinks/aws_cloudwatch_logs/mod.rs, src/sinks/util/service.rs
Closes #3487.
@bruceg thanks a lot for generic suggestions in the issue!
=> chore(sinks): add generic to InFlightLimit

.github/CODEOWNERS, CONTRIBUTING.md
=> chore: Initial edits to CODEOWNERS

src/sinks/elasticsearch.rs
Closes #3715
Pretty straightforward. It's probably worth making a pass through other sinks to see if this is an issue.
=> fix(elasticsearch sink): allow using excepted fields

.meta/_partials/fields/_multiline_options.toml.erb, .meta/_partials/fields/_request_options.toml.erb, .meta/_partials/fields/_tls_acceptor_options.toml.erb, .meta/_partials/fields/_tls_connector_options.toml.erb, .meta/_partials/fields/_types_options.toml.erb
=> chore: Spelling fixes - closes #3717

src/sinks/util/tcp.rs
We are incorrectly counting Err and NotReady into sent items
=> fix(observability): Fix TcpEventSent

deny.toml
CI fix for https://github.com/timberio/vector/issues/3764
=> fix(ci): add deny.toml

config/vector.spec.toml, src/sources/docker.rs
=> fix(docker source): add retry delay

src/sources/journald.rs
=> fix(journald source): Fix journald tests

CONTRIBUTING.md
=> chore: Add expected review counts to CONTRIBUTING.md

src/internal_events/mod.rs, src/internal_events/reduce.rs, src/transforms/reduce/mod.rs
=> enhancement(reduce transform): add internal events

.meta/sources/docker.toml.erb
=> docs: Add docs for retry_backoff_secs option

src/internal_events/dedupe.rs, src/internal_events/mod.rs, src/transforms/dedupe.rs
Closes #3393
There might be a better way to handle the double logging at different levels, but I figured we could defer that improvement for now.
=> enhancement(dedupe transform): add internal events

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore: Added cross installation to fix nightly builds

.github/workflows/environment.yml
=> chore: Added workflow_dispatch for the env workflow

CONTRIBUTING.md, Makefile
=> chore: Removing CI references to Nix

CONTRIBUTING.md
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
=> docs: Updates reference to gitter to point to the Discord server

Makefile, scripts/environment/Dockerfile, scripts/environment/bootstrap-ubuntu-20.04.sh, scripts/environment/prepare.sh
This improves our Windows support more so `make build ENVIRONMENT=true VERBOSE=true` works golden on it.
=> chore(windows platform): Windows support for ENVIRONMENT=true

PRIVACY.md
=> docs: Update Privacy policy for Discord

.github/workflows/environment.yml
=> chore: Added back docker push to environment workflow

Makefile
This takes a more conservative approach to #3862 and adds `.PHONY` to the targets where appropriate.
=> chore: Add PHONY per target in makefile

CONTRIBUTING.md
=> chore: Fixed Markdown error in CONTRIBUTING.md

.github/workflows/lints.yml, Makefile, scripts/check-internal-events.sh, scripts/environment/bootstrap-ubuntu-20.04.sh, scripts/environment/prepare.sh, src/internal_events/add_fields.rs, src/internal_events/ansi_stripper.rs, src/internal_events/docker.rs, src/internal_events/elasticsearch.rs, src/internal_events/file.rs, src/internal_events/heartbeat.rs, src/internal_events/http.rs, src/internal_events/kafka.rs, src/internal_events/kubernetes/api_watcher.rs, src/internal_events/kubernetes/instrumenting_watcher.rs, src/internal_events/kubernetes/reflector.rs, src/internal_events/kubernetes_logs.rs, src/internal_events/logplex.rs, src/internal_events/prometheus.rs, src/internal_events/regex_parser.rs, src/internal_events/socket.rs, src/internal_events/split.rs, src/internal_events/splunk_hec.rs, src/internal_events/statsd.rs, src/internal_events/stdin.rs, src/internal_events/syslog.rs, src/internal_events/tag_cardinality_limit.rs, src/internal_events/tcp.rs, src/internal_events/unix.rs, src/internal_events/vector.rs
Closes  #3546
Regularizes messages to adhere to uppercase and dot format, and runs the script, that @bruceg created, that checks for these rules, during CI `Checks` job.
=> fix(observability): Regularize internal event messages

scripts/ci-docker-images/builder-x86_64-unknown-linux-gnu/Dockerfile, scripts/package-deb.sh
Remove our dependency on cpan rename. (Please let this test on CI!)
=> chore: Remove cpan

rfcs/2020-09-02-3684-metric-namespaces.md
Ref: https://github.com/timberio/vector/issues/3684
=> chore(rfcs): Add RFC for first-class metric namespaces

distribution/rpm/vector.spec
It seems #3890 and #3876 stepped on toes.
=> chore(rpm platform): Fixup tar params

src/mapping/mod.rs, src/mapping/parser/grammar.pest, src/mapping/parser/mod.rs, src/mapping/query/functions.rs
=> feat(remap transform): Add new remap functions

src/config/component.rs, src/mapping/query/path.rs
Not sure why clippy didn't catch these.
=> chore: Replace ok_or with ok_or_else

.github/workflows/tests.yml, scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore: Remove apt upgrade step

scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore: Added update grub to fix bootstrap

distribution/rpm/vector.spec
I am not sure why #3938 broke things, but it did!
=> chore: Fix strip components call for creating rpms

.github/workflows/nightly.yml, .github/workflows/release.yml, Makefile, docker-compose.yml
This refactors the package* and package-archive* steps in the Makefile to simplify them.
=> chore: Refactor package steps to simplify them

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore: Remove remaining -all jobs

src/sinks/aws_cloudwatch_logs/mod.rs, src/sources/logplex.rs, src/sources/prometheus/mod.rs, src/sources/splunk_hec.rs, src/sources/statsd/mod.rs, src/transforms/geoip.rs, src/transforms/regex_parser.rs
=> fix: Add missing inventory::submit

.github/matchers/rust.json, .github/workflows/lints.yml
https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md
https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers
Taken from https://github.com/actions-rs/cargo/blob/master/.matchers/rust.json
=> chore(ci): Add Github Actions problem matcher for rust

.meta/links.toml
=> chore: Add apache_extended_status links

src/sources/file.rs
=> chore: Remove remove_file_test

.meta/sources/kubernetes_logs.toml.erb, src/sources/kubernetes_logs/pod_metadata_annotator.rs, tests/kubernetes-e2e.rs
=> enhancement(kubernetes_logs): Include container_name in kubernetes_logs

Cargo.lock, Cargo.toml, src/config/loading.rs, src/lib.rs, src/sources/file.rs, src/sources/stdin.rs
=> chore: Update the hostname crate to 0.3.1

distribution/debian/scripts/postinst, distribution/rpm/vector.spec
=> chore: Add vector to systemd-journal on Debian and RPM

CONTRIBUTING.md
This clarifies our language around the use of DCO for contributions.
=> chore: Update DCO language

.meta/sources/kubernetes_logs.toml.erb, src/sources/kubernetes_logs/pod_metadata_annotator.rs, tests/kubernetes-e2e.rs
=> enhancement(kubernetes_logs): Add container_image and pod_node_name annotations

.github/workflows/tests.yml
=> chore: Add matcher to tests

src/config/loading.rs, src/main.rs, src/transforms/lua/v2/mod.rs, tests/shutdown.rs
=> fix(reload): Recompute configuration paths

distribution/systemd/vector.service
=> chore: Add CAP_NET_BIND_SERVICE to systemd

scripts/check-markdown.sh
Otherwise gave me a lot of false positives locally.
=> chore(ci): Have markdownlint ignore target/

scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore: Remove grub-efi workaround

.github/workflows/nightly.yml
=> chore: Add Discord notification for failed nightly workflow

src/sinks/util/rusoto.rs
Rebased version of #3468 with some minor tweaks.
Tested in EKS and working as expected
=> enhancement: AWS EKS Web Identity support

.github/CODEOWNERS
=> chore: Sign myself up for docker at CODEOWNERS

scripts/build-docker.sh
=> chore: Re-enable date-stamped nightlies

.github/CODEOWNERS
=> chore: Add remap code owners

.github/workflows/prs.yml
=> chore: Only run Cargo deny and k8s yaml checks if required

.github/CODEOWNERS
=> chore: Add code owners for docs files

src/event/lookup/segment.rs
Adds a tad more hygenic tracing to our new lookup.
=> chore: Better tracing in lookups.

.github/workflows/bors.yml
=> chore(ci): Fix indentation

src/sinks/util/sink.rs
Closes #3830 
Now that the issue has been thoroughly identified, we can remove this extra logging that was added to help figure it out. It's not something that's otherwise useful and it'd just confuse users with a warning around a non-issue.
=> chore(sinks): remove diagnostics from double poll

.github/workflows/environment.yml
=> chore(ci): Fixed Docker username and password variable names

docs/reference.cue
=> chore: Add support for enums in [string] types

.github/workflows/environment.yml
=> chore(ci): Replace our Docker build with Github Actions native actions

docs/reference.cue, docs/reference/components/sources/apache_metrics.cue
=> chore(external docs): Fix spelling of "gauge"

scripts/check-markdown.sh, scripts/environment/prepare.sh
=> chore(ci): Install markdownlint globally to avoid path silliness

docs/reference.cue, scripts/check-docs.sh
=> chore(ci): Add cue formatting check

distribution/rpm/vector.spec
=> chore(ci): Update strip-components to 2

scripts/check-docs.sh
=> chore(ci): Only run cue fmt in CI

.github/workflows/master.yml, .github/workflows/pr.yml
This PR divides checks between pull requests and merged to master.
1. PRs run unit tests, style checks, and the `cross` build matrix job.
2. Master runs unit tests, integration tests, Kubernetes tests, and component checks.
Open to discussion on whether this is the right split.
=> chore(ci): Post Bors dividing tests back to into PRs and master

.github/workflows/master.yml
=> chore(ci): Remove changes job

.github/workflows/master.yml
=> chore(ci): Removed final changes check

src/transforms/metric_to_log.rs
=> chore: Fix clippy lint

src/sources/file.rs
=> fix(file source): Add alias to avoid breaking change

tests/shutdown.rs
Adds missing use. Introduced in #4341. I'll merge it now since it's trivial.
=> fix: Add missing use

docs/reference/components/sources/file.cue, docs/reference/components/transforms/add_fields.cue
Some of the changes in https://github.com/timberio/vector/pull/3714 were lost. This restores them.
=> chore(file source): Update docs

docs/reference.cue
This adds documentation to our cue fields. This should help clarify what a field is for.
=> chore(internal docs): Add docs to cue fields

docs/reference.cue
=> chore(external docs): Fixed some typos in reference.cue comments

docs/reference.cue, docs/reference/components/sources.cue, docs/reference/components/sources/apache_metrics.cue, docs/reference/components/sources/aws_kinesis_firehose.cue, docs/reference/components/sources/file.cue, docs/reference/components/sources/host_metrics.cue, docs/reference/components/sources/http.cue, docs/reference/components/sources/journald.cue, docs/reference/components/transforms.cue
This defines more boilerplate to assist in defining `.cue` files for our various components.
=> chore(external docs): Add partials for Cue boilerplate

.github/workflows/master.yml, .github/workflows/pr.yml
=> chore(ci): Bumped the cancel action version

.github/workflows/master.yml, .github/workflows/pr.yml
=> chore(ci): Only run master tests when needed

rfcs/2020-09-28-cloudwatch-metrics.md
=> chore(rfcs): AWS CloudWatch Metrics source RFC

docs/reference/components/sinks/aws_kinesis_firehose.cue
=> chore(external docs): Fix `aws_kinesis_firehose` sink docs

docs/reference/components/sinks/aws.cue, docs/reference/components/sinks/aws_cloudwatch_metrics.cue, docs/reference/components/sinks/aws_kinesis_streams.cue
=> chore(external docs): Add common AWS options

distribution/debian/scripts/postinst
=> enhancement: Add vector user to adm in debian packaging

Cargo.lock, deny.toml
Fixup the cargo deny rules.
Closes #4515
=> chore: Fixup Cargo deny

src/sources/http.rs
=> fix: Removed a stray Atom that snuck back in

.github/workflows/master.yml
=> chore(ci): Adding workflow dispatch to master CI runs

.github/workflows/k8s_e2e.yml, .github/workflows/master.yml
=> chore(ci): Add standalone k8s e2e tests

src/sinks/util/rusoto.rs
Updates the StsClient to use the CustomChainProvider that supports EKS web identity
This is not ideal, but as discussed on #2881, #3468 and #4049 there are issues with rusoto's crate topology that make it non-trivial for the default rusoto provider chain to support EKS web identity like recent AWS SDKs for other languages do.
Fixes (#4405)
=> feat(aws service): Support assume_role with EKS web identity

src/internal_events/windows.rs, src/service.rs, src/vector_windows.rs
Now properly handle `service restart` subcommand
=> enhancement(windows platform): correctly handle service restart

Cargo.toml, src/mapping/query/function/mod.rs, src/mapping/query/function/parse_syslog.rs, tests/behavior/transforms/remap.toml
Closes #4501 
This adds the `parse_syslog` function to the remap language.
=> feat(remap transform): add `parse_syslog` function

.github/workflows/master.yml, .github/workflows/pr.yml
=> chore(ci): Fail component checks on warnings

src/sinks/socket.rs, src/sinks/statsd.rs, src/sinks/util/tcp.rs, src/sinks/util/udp.rs, src/sinks/util/unix.rs
close #4610
- Change TCP and UNIX mode to stream sink.
- Don't resolve DNS for every batch send in UDP mode.
=> fix(statsd sink): Improve networking performance

docs/reference.cue, docs/reference/components/sinks/influxdb_metrics.cue, docs/reference/components/sinks/prometheus.cue, docs/reference/components/transforms/log_to_metric.cue
=> chore(external docs): Add examples for `distribution` and `summary` metrics to `prometheus` sink

Makefile, src/sinks/aws_kinesis_firehose.rs
Opening as a draft to see what CI does with this as I'm having some issues reproducing locally.
=> chore(ci): Wait for ES to start up for Kinesis Firehose tests

src/sinks/util/buffer/mod.rs
=> chore(sinks): Drop unused fn Buffer::size

src/sinks/file/mod.rs
Left-over of https://github.com/timberio/vector/pull/4636#discussion_r508582216 
=> chore: Remove "TODO" in generated config

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Maybe a bug with actions/download-artifact@v1

docs/reference.cue, docs/reference/components/sinks/aws.cue, docs/reference/components/sinks/gcp.cue, docs/reference/components/sources/docker.cue
=> chore(external docs): Add remaining AWS env vars

scripts/environment/bootstrap-ubuntu-20.04.sh
https://github.com/timberio/vector/pull/3962
=> chore(ci): Re-introducing grub build fix

Cargo.toml, distribution/rpm/vector.spec, distribution/systemd/vector.default, distribution/systemd/vector.service
=> chore: Added support for an /etc/default/vector environment file.

lib/k8s-e2e-tests/src/lib.rs
=> chore(tests): Fix k8s test

scripts/helm-dependencies.sh, scripts/patch-packaged-helm-chart-versions.sh
=> chore(kubernetes platform): Proper bash 4 support in helm related scripts

benches/lua.rs, src/transforms/add_fields.rs, src/transforms/remove_fields.rs, src/transforms/rename_fields.rs
=> chore(transforms): Do not use lookups in transforms right now.

skaffold/manifests/config.yaml, skaffold/manifests/patches/env.yaml
This PR updates the skaffold development setup after a series of our Helm chart refactors.
=> chore: Update the skaffold setup after the Helm charts refactor

scripts/helm-dependencies.sh
Closes #4592.
To do:
---
Note, my local Git version on Windows was worried that the symlinks were different at first, but after updating Git to the latest version I see no issues.
=> chore: Implement a workaround for symlinks on Windows at helm-dependencies script

kustomization.yaml
=> chore: Add more explanation to the top-level kustomization.yaml

CODE_OF_CONDUCT.md, CONTRIBUTING.md, NOTICE, README.md.erb
=> chore(external docs): Minor fixes to a few sections

rfcs/2020-10-15-3480-file-source-rework.md
Closes #3480 
[Rendered](https://github.com/timberio/vector/blob/file-source-rfc/rfcs/2020-10-15-3480-file-source-rework.md)
=> chore: add file source rework rfc

scripts/environment/bootstrap-ubuntu-20.04.sh
We've seen intermittent failures:
https://github.com/timberio/vector/actions/runs/343791534
=> chore(ci): Have apt retry fetches

src/sinks/elasticsearch.rs
GZip compression works with the latest AWS ElasticSearch versions - see https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html
=> enhancement(config): Remove error message for compression when using AWS ElasticSearch

.github/workflows/nightly.yml
=> chore(ci): Add artifact downloads

Cargo.lock, Cargo.toml
=> fix(syslog source): Parse RFC3614 messages lacking an app name

docs/reference/components/sinks/blackhole.cue, src/sinks/blackhole.rs
=> fix(blackhole sink): Make print_amount an optional option with a default of 1000

docs/reference.cue, docs/reference/components/sources/generator.cue, docs/reference/components/transforms/aws_cloudwatch_logs_subscription_parser.cue
This PR fixes an issue with list type syntax (#4890) and errors in the Cue sources stemming from that.
=> fix(config): Fix list type issue in Cue schemas

.github/CODEOWNERS
=> chore: Add vector-kubernetes team to CODEOWNERS

.github/workflows/install-sh.yml
I am unclear how this ever worked. But it does now I think.
=> chore(ci): Fix sync-install job

.github/workflows/install-sh.yml
=> chore(ci): Add sudo to install nightly

.github/workflows/install-sh.yml
=> chore(ci): Add python-dev to install.sh workflow

src/sinks/influxdb/mod.rs, src/sinks/statsd.rs
=> chore: Remove redundant sortings

src/transforms/wasm.rs
Follow-up to https://github.com/timberio/vector/pull/4684
Fixes #4930 
=> fix(wasm transform): Update WASM transform to implement TaskTransform

scripts/build-docker.sh
This PR restores the push capability of our docker build script.
=> chore: Correct the inverted condition at docker push

Cargo.toml, Makefile, src/sinks/prometheus/exporter.rs, src/sources/prometheus/mod.rs, tests/data/prometheus.yaml
=> chore: Add prometheus sink and source integration tests

distribution/helm/vector-agent/templates/daemonset.yaml, distribution/helm/vector-agent/values.yaml, distribution/kubernetes/vector.yaml, lib/k8s-e2e-tests/tests/vector-agent.rs, scripts/kubernetes-yaml/values.yaml
Closes https://github.com/timberio/vector/issues/4494.
=> fix(kubernetes platform)!: Remove hardcoded configs in Helm chart

rfcs/2020-10-29-3736-remap-chain-parsing.md
=> fix(rfcs): Fix markdown errors

src/sources/util/http.rs
=> fix(http source): Add span to future

docs/reference/components/transforms/key_value_parser.cue
=> fix(external docs): Fix Cue errors from k/v plugin

distribution/helm/vector-agent/values.yaml
=> chore(kubernetes platform): Adds inline docs for helm chart global variables

src/sources/internal_metrics.rs
=> enhancement(sources): make scrape interval configurable

docs/reference/cli.cue
This PR complements #4886 by adding Cue sources for the CLI.
=> enhancement(config): Document `vector top` CLI

lib/file-source/src/fingerprinter.rs, lib/file-source/src/lib.rs, src/sources/file.rs, src/sources/kubernetes_logs/mod.rs
Closes #3662
This doesn't add any user-facing config option yet, but it does turn off these errors for the kubernetes source.
=> enhancement(file source): add internal option to ignore missing files

src/top/cmd.rs
=> enhancement(cli): Edited a few vector top error messages

distribution/helm/vector-agent/templates/daemonset.yaml
=> chore(kubernetes platform): Only add checksum if not using external configmap

src/transforms/aws_ec2_metadata.rs
To use the transform as a task. The change from `FunctionTransform` to
`TaskTranform` happened in https://github.com/timberio/vector/pull/4875
Fixes #5063 
=> chore(ci): Update aws_ec2_metadata transform tests

src/internal_events/aws_s3.rs, src/internal_events/geoip.rs, src/internal_events/key_value_parser.rs, src/internal_events/logfmt_parser.rs, src/internal_events/windows.rs
Found that some events do not have `_total` suffix.
=> fix: add _total suffix to events

deny.toml
CI fix for https://github.com/time-rs/time/issues/293
=> fix(ci): add RUSTSEC-2020-0071 to deny.toml

src/rusoto/mod.rs, src/sinks/aws_cloudwatch_metrics.rs, src/sinks/aws_kinesis_firehose.rs, src/sinks/aws_kinesis_streams.rs, src/sinks/aws_s3.rs, src/sinks/aws_sqs.rs
Discussin in sqs sink: https://github.com/timberio/vector/pull/4675#discussion_r525282085
=> chore: handle TOO_MANY_REQUESTS in AWS sinks

Cargo.lock, Cargo.toml, src/sinks/util/retries.rs, src/sinks/util/tcp.rs, src/sinks/util/udp.rs, src/sinks/util/unix.rs
=> chore(deps): remove tokio-retry, task-compat

Cargo.lock, Cargo.toml
=> chore(deps): Remove a couple of more unused deps

Cargo.lock, lib/file-source/Cargo.toml, lib/file-source/src/checkpointer.rs, lib/file-source/src/file_server.rs, lib/file-source/src/internal_events.rs, src/internal_events/file.rs, src/sources/file.rs, src/sources/kubernetes_logs/mod.rs, src/sources/kubernetes_logs/util.rs
=> chore(file source): move checkpoint persistence to separate task

docs/reference/cli.cue
This PR updates our CUE docs for the Vector CLI in light of some minor recent changes. It also adds logic to specify whether specific argument and options are required.
=> chore(cli): Update CLI docs to account for recent updates

docs/reference/installation/_interfaces/helm3.cue, scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore: Update cue to 0.3.0-alpha5

docs/reference.cue, docs/reference/api.cue
@leebenson can you make sure this is accurate? I need to merge to unblock some release stuff I'm doing, but you could follow up with a pull request for any changes?
=> chore(docs): Enhance API docs with endpoints

Cargo.toml, config/vector.toml, distribution/rpm/vector.spec, docs/manual/setup/installation/manual/from-archives.md, docs/manual/setup/installation/manual/from-source.md
Addresses https://github.com/timberio/vector/pull/5012#issuecomment-731792458.
=> chore(external docs): Remove vector.spec.toml references

scripts/package-archive.sh
Fix a final reference to the `config/*.erb` files inside the package archive task.
=> chore: Fix package-archive task to remove *.erb reference

docs/reference/installation/_interfaces/kubectl.cue
This PR reworks `kubectl` installation docs a bit, introduces the internal structure, and corrects the kustomization base.
=> chore(external docs): Add internal logic to kubectl installation docs

rfcs/2020-11-01-remap-metrics-support.md
=> chore(rfcs):  Remap metrics support

distribution/kubernetes/vector-agent/resources.yaml, distribution/kubernetes/vector-all/resources.yaml
Failing check: https://github.com/timberio/vector/runs/1435709845
=> chore(ci): Fix whitespace in Kubernetes YAMLs

Cargo.lock, Cargo.toml, docs/reference/components/sources/docker_logs.cue, docs/reference/urls.cue
=> fix(docker_logs source): Upgrade bollard to 0.9 to close#4169

.github/workflows/master.yml
=> chore(ci): Run Windows build on self-hosted runner for master too

src/app.rs, src/config/builder.rs, src/config/compiler.rs, src/config/loading.rs, src/config/mod.rs, src/config/unit_test.rs, src/config/validation.rs, src/config/vars.rs, src/service.rs, src/validate.rs, tests/config.rs
=> fix(cli): Handle config warnings for `validate` command 

.github/workflows/test.yml
Missed that there were two defined.
=> chore(ci): Combine if statements in GA test.yml

rfcs/2020-11-01-remap-metrics-support.md
Some markdown lint errors crept through.
=> chore: Fixed markdownlint errors for remap metrics rfc

docs/reference/team.cue, docs/reference/urls.cue
=> chore(external docs): Add team data to CUE sources

docs/reference/components/sources/kubernetes_logs.cue
=> chore(external docs): Add Pod and container exclusion documentation to the kubernetes_logs source

scripts/util/commit.rb
Small fix to require successful parsing when releasing.
=> chore: Fix commmit parsing when releasing

src/sinks/util/adaptive_concurrency/controller.rs
=> fix(networking): Handle unexpected errors in ARC controller

docs/reference/remap.cue, docs/reference/remap/contains.cue, docs/reference/remap/del.cue, docs/reference/remap/ends_with.cue, docs/reference/remap/exists.cue, docs/reference/remap/flatten.cue, docs/reference/remap/format_timestamp.cue, docs/reference/remap/ip_cidr_contains.cue, docs/reference/remap/ip_subnet.cue, docs/reference/remap/md5.cue, docs/reference/remap/now.cue, docs/reference/remap/only_fields.cue, docs/reference/remap/parse_grok.cue, docs/reference/remap/parse_url.cue, docs/reference/remap/replace.cue, docs/reference/remap/sha1.cue, docs/reference/remap/starts_with.cue, docs/reference/remap/strip_ansi_escape_codes.cue, docs/reference/remap/uuid_v4.cue
=> chore: Add TRL description

src/config/api.rs
=> chore(config): Reject unknown API fields

.github/workflows/integration-test.yml, Makefile
ci: add `nginx`
make: add `humio`/`prometheus` to `integration` commands
=> fix(tests): fix integration tests list

.github/workflows/release.yml
=> fix(ci): Update release-docker task

docs/reference/remap/assert.cue, lib/remap-lang/src/error.rs, src/remap/function.rs, src/remap/function/assert.rs, src/remap/mod.rs, tests/behavior/transforms/remap.toml
Closes #4395 
~~Keeping draft until @JeanMertz merges a number of remap PRs that this will need merging into.~~
Has been merged with master now, so should be good to go.
=> feat(remap transform): add assert remap function

src/sources/statsd/mod.rs
=> chore(statsd source): remove futures01::Stream from statsd tests

.github/workflows/benches.yml
Also add master failure notification
=> chore(ci): Fix Github Actions versions in benches

tests/behavior/transforms/remap.toml
Flatten remap function needs a behaviour test.
=> chore(remap transform): Added flatten behaviour test

docs/reference.cue, docs/reference/components/sources/internal_metrics.cue
=> chore(external docs): Fix metrics tags enum values

.github/workflows/release.yml
=> chore: Fix Github release workflow

docs/reference/installation/_interfaces/helm3.cue
A small fix for the installation instructions for Helm at our website.
=> fix(external docs): Correct invalid YAML in Helm install docs

.github/workflows/k8s_e2e.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Makefile, scripts/package-rpm.sh, scripts/test-e2e-kubernetes.sh
=> chore: Add musl-based RPM for Centos 7 support

Makefile, scripts/package-rpm.sh
=> chore(ci): Simplify type selection

.github/workflows/release.yml
=> chore(ci): Fix nightly reference in release workflow

src/sinks/splunk_hec.rs
Addresses issue #5313.
Allows using template strings in the `index` option of the `splunk_hec` sink.
This is my first stab at Vector, and a Rust project in general. So I probably got something wrong here :-) Please direct me if I need to add more tests or missed something.
=> enhancement(config): Enabled templating of the 'index' option of the splunk_hec sink

docs/reference/installation/downloads.cue
=> chore(external docs): Add MUSL deb and RPM to downloads page

.github/ISSUE_TEMPLATE/config.yml
=> chore: Update issues templates to include discussions

docs/reference/cli.cue
This PR adds a bit of missing information to the CLI documentation.
=> chore(external docs): Update CLI docs

docs/reference/components/transforms/reduce.cue
=> chore(external docs): Add `reduce` transform `starts_when` option

SECURITY.md, docs/reference/components/transforms/split.cue
=> chore: Updates to security policy

.github/workflows/benches.yml
Until we sort out a way to isolate the builds as part of #5394
=> chore(ci): Run benchmarks on GA runners

docs/reference/components/sinks/humio.cue, docs/reference/components/sinks/loki.cue, docs/reference/components/sinks/splunk_hec.cue
=> chore(docs): Add missing endpoint config for humio, splunk, and loki sinks

Cargo.lock
This PR updated arc-swap to make cargo-deny happy.
=> chore: Update arc-swap

Cargo.lock, Cargo.toml, src/app.rs, src/sources/host_metrics.rs
This one is a tough one to test. Theoretically this shouldn't alter any behavior whatsoever _currently_
In order to test the behavior we have to be running a build of the branch in a container with the appropriate environment variables set. I'll post some output from my local testing here and ultimately @MOZGIII is adding e2e tests for this in our kubernetes testing components.
=> enhancement(host_metrics source): integrate upstream container support

.github/workflows/test.yml, deny.toml
=> chore(ci): Update Cargo deny licence configuration

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Update Strawberry Perl version

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Added https to Strawberry perl downloads

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Removed SHASUM

docs/reference/remap/match.cue
This PR adds documentation for a Remap function that we somehow missed.
=> enhancement(external docs): Document the match function for TRL

docs/reference/releases/0.11.1.cue
=> chore: Prepare v0.11.1

deny.toml
=> chore(ci): Added Apache-2.0 WITH LLVM-exception license to checks

Cargo.lock, Cargo.toml
Follow up from https://github.com/timberio/vector/pull/5561#discussion_r544464478
=> chore: Switch hyper patch to upstream repo and add a comment

deny.toml
=> chore(ci): Change license check default to warn

.github/workflows/benches.yml
Includes upstream changes
(https://github.com/dawidd6/action-download-artifact/commit/303fcc93806352341b5e13cad16640e067518917)
to filter the workflow artifacts by successful run in addition to the
branch filter.
=> chore(ci): Pull last successful artifacts for benches

docs/reference/components/sources/kubernetes_logs.cue
=> enhancement(kubernetes platform): Adds cue docs for k8s pod_ip and pod_ips annotations

docs/reference/data_model/schema.cue
As it says on the tin. Noticed these while reading the docs.
=> fix(external docs): correct a few misspellings

docs/reference/components/sinks/loki.cue
As of https://github.com/timberio/vector/pull/5204
=> fix(documentation): tenant_id is templatable on loki sink

docs/reference.cue, docs/reference/installation/_interfaces/helm3.cue, scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore(ci): Update cue to v0.3.0-alpha6

docs/reference/remap.cue, docs/reference/remap/encode_json.cue, lib/remap-functions/Cargo.toml, lib/remap-functions/src/encode_json.rs, lib/remap-functions/src/lib.rs, tests/behavior/transforms/remap.toml
=> enhancement(remap): add encode_json function

.github/workflows/test.yml, Makefile
=> chore: Make Kubernetes YAMLs plural in Github Actions and Makefile

docs/reference/components/transforms/remap.cue, docs/reference/remap/redact.cue
=> enhancement(external docs): More Remap examples

src/sources/journald.rs
Fix failed tests after #5683 
https://github.com/timberio/vector/pull/5683#issuecomment-749936260
=> fix(journald source): fix tests for fake journal

distribution/install.sh
=> chore(administration): Update install script version

docs/highlights/2020-12-23-filter-remap-support.md, docs/highlights/2020-12-23-graphql-api.md, docs/highlights/2020-12-23-internal-logs-source.md, docs/highlights/2020-12-23-reduce-transform-remap-support.md, docs/highlights/2020-12-23-swimlanes-remap-support.md, docs/highlights/2020-12-23-vector-remap-language.md
=> enhancement(external docs): Add 0.12 highlights

SECURITY.md
=> chore(security): Minor updates to our SECURITY policies

distribution/docker/alpine/Dockerfile
=> chore(security): Upgraded Alpine base image to address some vulns

.github/workflows/install-sh.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Add back in package verification jobs

distribution/docker/alpine/Dockerfile
=> chore(security): Upgrade alpine to 3.12

docs/reference/components/sinks.cue
It used to be "auto", but now it is "adaptive".
=> fix(external docs): Correct the config name for enabling adaptive concurrency

src/sources/util/http.rs
=> fix(http source): lower handle http req log to debug

src/internal_events/http_client.rs, src/metrics.rs
=> fix(internal_metrics source): Make internal metrics pass promtools check

docs/reference/components/sources/vector.cue
=> fix(external docs): Fix Vector source reference to support metrics

.github/workflows/nightly.yml, .github/workflows/release.yml
Add `linux/arm/v7` to the nightly and release Github workflows so that
they're built automatically.
Closes #5786.
Signed-off-by: Dan Norris <protochron@users.noreply.github.com>
=> enhancement(ci): Build ARMv7 images for all supported platforms

.github/CODEOWNERS, Cargo.lock, docs/reference/components/transforms/aws_cloudwatch_logs_subscription_parser.cue, docs/reference/remap/parse_aws_cloudwatch_log_subscription_message.cue, lib/remap-functions/Cargo.toml, lib/remap-functions/src/lib.rs, lib/remap-functions/src/parse_aws_cloudwatch_log_subscription_message.rs, lib/shared/Cargo.toml, lib/shared/src/aws_cloudwatch_logs_subscription.rs, lib/shared/src/lib.rs, src/transforms/aws_cloudwatch_logs_subscription_parser.rs, tests/behavior/transforms/remap.toml
=> enhancement(remap transform): add `parse_aws_cloudwatch_log_subscription_message` function

Cargo.lock, Cargo.toml, lib/file-source/Cargo.toml, src/top/dashboard.rs
Dependabot updates (#5788 #5789 #5790 #5791 #5792) + `cargo update --aggressive`.
=> chore(deps): bump deps

docs/reference/components/sinks/kafka.cue, src/sinks/kafka.rs
Closes #5341. This PR only about sending metrics to kafka.
=> enhancement(kafka sink): allow send metrics to kafka

.github/dependabot.yml
=> chore(deps): Update dependbot to also track github actions updates

lib/k8s-e2e-tests/tests/vector-agent.rs
=> fix(internal docs): Correct misspelling

src/sources/mongodb_metrics/mod.rs
=> chore(mongodb_metrics source): remove not used error variant

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Add a task to verify the OSX and Windows binaries work

.github/workflows/benches.yml
=> chore(ci): Export AWS credentials for benchmark artifact upload

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Fix nightly and verify jobs

docs/highlights/2021-01-10-kafka-sink-metrics.md
=> chore: Add kafka metrics support highlight

.github/workflows/integration-test.yml
=> chore(ci): only notify failed integration tests on master

config/vector.toml
=> chore: Update default configuration

config/vector.toml
Ref https://github.com/timberio/vector/issues/5888#issuecomment-756249238
=> chore: Disable API by default

.github/workflows/nightly.yml, .github/workflows/release.yml, distribution/debian/scripts/preinst
=> chore(ci): Stop Debian package failing if vector user already exists

src/test_util/mod.rs
=> chore(tests): Make `wait_for` use a quadratic backoff on delays

docs/reference/remap/to_bool.cue
=> chore(external docs): Add docs for to_bool function

src/sinks/prometheus/collector.rs, src/sources/prometheus/scrape.rs
Closes #5907
Creating as draft whilst I test
=> fix(prometheus_exporter sink): Fix prometheus exposition format

.github/workflows/nightly.yml, .github/workflows/release.yml
=> chore(ci): Add --replacepkgs flag to RPM test installs

src/sources/docker_logs.rs
=> chore(docker_logs source): Remove unnecessary `error` log

docs/reference/remap/to_syslog_facility.cue, docs/reference/urls.cue, lib/remap-functions/Cargo.toml, lib/remap-functions/src/lib.rs, lib/remap-functions/src/to_syslog_facility.rs, tests/behavior/transforms/remap.toml
Addresses #5769 (based on prior work from #5503) for creating a new Remap function which converts syslog facilities codes into their keyword.
Signed-off-by: jbradleynh <jbradley@fastly.com>
=> enhancement(remap): Add to_syslog_facility function for parsing syslog facilities into strings

docs/reference/remap/parse_tokens.cue, lib/remap-functions/Cargo.toml, lib/remap-functions/src/lib.rs, lib/remap-functions/src/parse_tokens.rs, tests/behavior/transforms/remap.toml
=> fix(remap): Rename tokenize to parse_tokens

lib/remap-cli/src/repl.rs
This isn't a huge improvement but I do think a step up from what we currently have 😄
=> enhancement(remap): Improve VRL REPL help text

Cargo.lock
=> chore(ci): Update smallvec

docs/reference/remap/assert.cue, docs/reference/remap/ceil.cue, docs/reference/remap/compact.cue, docs/reference/remap/contains.cue, docs/reference/remap/ends_with.cue, docs/reference/remap/floor.cue, docs/reference/remap/format_number.cue, docs/reference/remap/format_timestamp.cue, docs/reference/remap/merge.cue, docs/reference/remap/parse_key_value.cue, docs/reference/remap/parse_timestamp.cue, docs/reference/remap/redact.cue, docs/reference/remap/replace.cue, docs/reference/remap/round.cue, docs/reference/remap/sha3.cue, docs/reference/remap/slice.cue, docs/reference/remap/split.cue, docs/reference/remap/starts_with.cue, docs/reference/remap/to_timestamp.cue
=> fix(external docs): Update VRL optional arg syntax

lib/file-source/src/fingerprinter.rs
=> chore(file source): Filter out directories before fingerprinting 

Cargo.toml, lib/codec/Cargo.toml, lib/file-source/Cargo.toml, lib/k8s-e2e-tests/Cargo.toml, lib/k8s-test-framework/Cargo.toml, lib/portpicker/Cargo.toml, lib/prometheus-parser/Cargo.toml, lib/remap-cli/Cargo.toml, lib/remap-functions/Cargo.toml, lib/remap-lang/Cargo.toml, lib/shared/Cargo.toml, lib/tracing-limit/Cargo.toml, lib/vector-api-client/Cargo.toml, lib/vector-wasm/Cargo.toml
=> chore(deps): Remove license-file to be explicit about named license

scripts/setup_integration/humio_integration_env.sh, scripts/setup_integration/mongodb_metrics_integration_env.sh, scripts/setup_integration/nginx_integration_env.sh
Introduced in https://github.com/timberio/vector/pull/5884
=> fix(ci): correct start/stop instructions

tests/behavior/transforms/remap.toml
These were missing from our behavior tests.
=> chore(remap): add error-handling behavior tests

scripts/release-s3.sh
Reverts timberio/vector#5988
This PR wasn't actually working yet.
=> chore(ci): Revert 5988

lib/remap-functions/Cargo.toml, lib/remap-functions/src/lib.rs, lib/remap-lang/src/object.rs, lib/remap-lang/src/value/object.rs, src/event/log_event.rs, src/event/metric.rs, tests/behavior/transforms/remap.toml
Closes #5607 
I'm not 100% sure if we do want to remove this if we don't currently have any iterating support, but here it is in case we do!
=> chore(remap): remove only_fields remap function

.github/CODEOWNERS
Noticed some issues, fixed them.
=> chore: Update and fix k8s-related codeowners entries

docs/reference/remap.cue, docs/reference/remap/log.cue
Just covering a missing base here.
=> enhancement(external docs): Document log function for VRL

src/rusoto/mod.rs
Closes #5994
Carbon copy of https://github.com/rusoto/rusoto/pull/1892, since we have a modified version of the same code.
=> chore(aws service): Enhance error reporting for invalid header value

docs/reference/installation/_interfaces/homebrew.cue
=> fix(external docs): Added command: commands.configure to Homebrew cue

src/sinks/prometheus/exporter.rs
This reverts commit 91f77ef44a4dfa182c27cf3483a878ad576d8757 as discussed on Discord
Fixes #5916
=> fix(prometheus_exporter sink): Fix Metrics not Updating

docs/reference/installation/platforms/kubernetes.cue
=> chore(kubernetes_logs source): Document built-in metrics pipeline that we ship with the Helm charts

benches/remap.rs, tests/behavior/transforms/remap.toml
Fixes https://github.com/timberio/vector/actions/runs/494657045
=> chore(ci): Fix remap benches

docs/manual/setup/transformation.md
Closes [#286](https://github.com/timberio/vector-website/issues/286) in the `vector-website` repo.
=> enhancement(external docs): Add Transformation doc

docs/reference/components/sources/kubernetes_logs.cue
=> chore(kubernetes_logs source): Correct docs type and alter example for extra_field_selector

docs/manual/setup/getting-started.md
[Visualized](https://github.com/timberio/vector/blob/gs/docs/manual/setup/getting-started.md).
=> enhancement(external docs): Adding new Getting Started guide

.github/CODEOWNERS, .github/semantic.yml, Cargo.toml, benches/topology.rs, config/examples/docs_example.toml, docs/manual/meta/glossary.md, docs/manual/setup/configuration.md, docs/manual/setup/installation/manual/from-source.md, docs/reference/components/transforms/sample.cue, src/config/format.rs, src/internal_events/mod.rs, src/internal_events/sample.rs, src/transforms/mod.rs, src/transforms/sample.rs, tests/config.rs, tests/tcp.rs
=> chore(sampler transform): Rename to `sample`

distribution/helm/vector-aggregator/README.md, distribution/helm/vector/README.md
=> chore(kubernetes_logs source): Adds README to other helm charts.

src/internal_events/encoding_transcode.rs, src/internal_events/log_to_metric.rs
=> chore: Use internal_log_rate_secs to rate-limit logs

benches/buffering.rs, benches/files.rs, benches/http.rs, benches/languages.rs, benches/metrics_bench_util/mod.rs, benches/topology.rs, src/app.rs, src/dns.rs, src/shutdown.rs, src/sinks/util/adaptive_concurrency/tests.rs, src/sinks/util/http.rs, src/sources/prometheus/scrape.rs, src/sources/socket/mod.rs, src/sources/statsd/mod.rs, src/test_util/mod.rs, src/topology/mod.rs, src/vector_windows.rs, tests/buffering.rs, tests/crash.rs, tests/syslog.rs, tests/tcp.rs, tests/topology.rs
Closes #6237 
Ref #5103 
After this, I believe all that remains is #5775 and #6234 before we're totally off of futures 0.1.
=> chore: upgrade almost all remaining old futures

src/config/watcher.rs
The default notify backend on macOS seemed quite flaky for this test. Since we have a very simple use case here, I've just switched to the polling backend with an interval of one second. This should be plenty for watching config files and seems to be much more reliable.
I'm going to go ahead and merge to try to clean up CI, but further discussion is welcome.
=> fix(tests): use poll backend for watcher

lib/remap-functions/src/parse_regex.rs
=> chore(tests): Fix error message for parse_regex::tests::find_no_match

.github/workflows/test.yml, Makefile, config/examples/file_to_prometheus.toml, scripts/check-examples.sh
=> chore(ci): Fix `make check-examples`

benches/topology.rs
This PR fixes an error that was introduced at #6274.
=> fix: Correct the real world benches

Cargo.toml, src/vector_windows.rs
=> chore(deps): Make nom optional

docs/reference/installation/_interfaces/apt.cue, docs/reference/installation/_interfaces/yum.cue, docs/reference/urls.cue
=> enhancement(external docs): Add reference to detailed Cloudsmith instructions for apt and yum

docs/reference/remap/functions/parse_glog.cue, docs/reference/urls.cue, lib/remap-functions/Cargo.toml, lib/remap-functions/src/lib.rs, lib/remap-functions/src/parse_glog.rs, tests/behavior/transforms/remap.toml
=> feat(remap transform): Add `parse_glog` function

Cargo.lock, Cargo.toml
=> fix: Update bollard to 0.9.1 to fix #5937

docs/reference/remap/functions/join.cue
I neglected to do this as part of #6313. Derp!
=> enhancement(external docs): Add docs for the VRL join function

tests/data/wasm/parse_json/src/lib.rs
=> fix(wasm transform): Fix parse_json Wasm function

benches/lua.rs
The current implementation happened to work because setting event to
null resulted in an error that also caused the event to be dropped, but
this implementation is actually correct.
Fixes #5913 
=> fix(performance): Fix lua_field_filter/v2 bench implementation

benches/topology.rs
Wires up the missing sink target for 500 errors.
Fixes #5912 
=> chore(ci): Fix complex/complex healthcheck error

src/sources/postgresql_metrics.rs
Close #6086 
This is the last item from the #6086 list. These changes remove `expect`/`unwrap` for postgresql client / version.
=> chore(postgresql_metrics source): remove expect for postgreqsl client

src/sources/docker_logs.rs
Signed-off-by: drunkirishcoder <daniel.jin@gmail.com>
fixes #6394
=> fix(docker_logs source): docker_logs use override host key

docs/highlights/2021-02-15-vector-top.md
Adds a 0.12 highlight for @leebenson's lovely `vector top` feature
=> enhancement(external docs): Add vector top highlight

docs/reference/components.cue, docs/reference/components/transforms/add_fields.cue, docs/reference/components/transforms/ansi_stripper.cue, docs/reference/components/transforms/aws_cloudwatch_logs_subscription_parser.cue, docs/reference/components/transforms/coercer.cue, docs/reference/components/transforms/concat.cue, docs/reference/components/transforms/filter.cue, docs/reference/components/transforms/grok_parser.cue, docs/reference/components/transforms/json_parser.cue, docs/reference/components/transforms/key_value_parser.cue, docs/reference/components/transforms/logfmt_parser.cue, docs/reference/components/transforms/lua.cue, docs/reference/components/transforms/regex_parser.cue, docs/reference/components/transforms/remove_fields.cue, docs/reference/components/transforms/remove_tags.cue, docs/reference/components/transforms/rename_fields.cue, docs/reference/components/transforms/split.cue, docs/reference/components/transforms/tokenizer.cue, lib/remap-functions/src/lib.rs
=> enhancement(external docs): Provide VRL examples for deprecated transforms

scripts/environment/bootstrap-ubuntu-20.04.sh
=> chore(ci): Upgrade cue to 0.3.0-beta.5

benches/languages.rs
=> chore(ci): Small fixes to language benches

CONTRIBUTING.md
=> chore: Add the kubernetes architecture outline to the CONTRIBUTING.md
