vectordotdev/vector

lib/vrl/compiler/src/expression/function_argument.rs
lib/vrl/compiler/src/expression/function_call.rs
lib/vrl/diagnostic/src/diagnostic.rs
lib/vrl/diagnostic/src/note.rs
lib/vrl/tests/tests/diagnostics/call_to_undefined_function.vrl
lib/vrl/tests/tests/diagnostics/function_argument_arity_mismatch.vrl
lib/vrl/tests/tests/diagnostics/function_argument_missing.vrl
lib/vrl/tests/tests/diagnostics/invalid_if_condition_type.vrl
lib/vrl/tests/tests/diagnostics/invalid_regex.vrl
lib/vrl/tests/tests/diagnostics/regex_parsing_unsuccessful.vrl
lib/vrl/tests/tests/diagnostics/unhandled_expression_error.vrl
lib/vrl/tests/tests/diagnostics/unhandled_function_error.vrl
lib/vrl/tests/tests/diagnostics/unhandled_parse_regex_all_type.vrl
lib/vrl/tests/tests/diagnostics/unknown_function_argument_keyword.vrl
lib/vrl/tests/tests/diagnostics/unneeded_error_assignment.vrl
lib/vrl/tests/tests/diagnostics/unsuccessful_parse_json_type.vrl
lib/vrl/tests/tests/internal/infallible_ok_maybe_null.vrl
lib/vrl/tests/tests/issues/6469_fallible_operations_marked_as_infallible.vrl

chore(remap): improve type error message

---

lib/vrl/stdlib/src/parse_syslog.rs

fix(remap): Restore changes to parse_syslog

---

lib/vrl/cli/src/repl.rs

This PR improves the VRL REPL hinter by suggesting function names.

enhancement(remap): Add function name hinting to VRL REPL

---

docs/reference/components/transforms/remap.cue
docs/reference/releases/0.12.0.cue
docs/reference/remap.cue
docs/reference/remap/concepts/expression.cue
docs/reference/remap/expressions/assignment.cue
docs/reference/remap/expressions/function_call.cue
docs/reference/remap/expressions/index.cue
docs/reference/remap/expressions/path.cue
docs/reference/remap/expressions/variable.cue
docs/reference/remap/literals/array.cue
docs/reference/remap/literals/object.cue
docs/reference/remap/literals/regular_expression.cue
docs/reference/urls.cue

Some "finish line" updates for the 0.12 release.

fix(external docs): VRL docs updates for 0.12

---

lib/vrl/stdlib/src/parse_syslog.rs

This is extracted by the syslog source, but seemed to be missing here.
I'm not sure if that was intentional.

enhancement(remap): Extract version in parse_syslog function

---

src/sources/util/tcp.rs
src/sources/vector.rs

Closes #6064
Though there are some caveats

fix(vector source): Close stream on bad data in vector source

---

lib/vrl/stdlib/benches/benches.rs

Silent merge conflict with
https://github.com/timberio/vector/commit/ebab8b21fef4b819ba3274b1d0783b9ea4b76b84

chore(ci): Fix vrl parse_syslog bench assertion

---

Cargo.toml
docs/reference/components/transforms/lua.cue

chore(external docs): Note the version of the Lua engine in the docs

---

.github/workflows/rustdoc.yml

This PR adds an Action that triggers a build of Vector's Rustdoc on successful PR merge.

enhancement(ci): Build Rustdoc site on PR merge

---

src/sinks/elasticsearch.rs

fixes #6548. can parse the correct server side error message when `bulk_action` is set to `create`.

fix(elasticsearch sink): parse create bulk action error

---

rfcs/2021-02-23-6531-performance-testing.md

This RFC documents the technical details of our existing performance testing
process and describes avenues for future work to improve over the state of the
art in this project, then makes a proposal for where to go next.
Closes #6531, https://github.com/timberio/vector-test-harness/issues/68

chore: Performance Testing

---

lib/vrl/parser/src/lex.rs
lib/vrl/tests/tests/diagnostics/invalid_string.vrl
lib/vrl/tests/tests/issues/6571_invalid_escape.vrl

fix(remap): don't mark `/` as a valid escape target

---

cue.mod/module.cue

This initially puzzled me and I had to do some digging to figure out its purpose. Fortunately didn't have to dig too long as it's new, but I still think it'd be nice to add a little note of clarification here.

enhancement(external docs): Add note about CUE model

---

src/transforms/lua/v2/interop/metric.rs

It seems like we missed this when we initially introduced namespace
support for metrics.
Closes #6621

enhancement(lua transform): Add support for metric namespaces

---

rfcs/2021-02-23-6531-performance-testing.md

This commit introduces a plan of action section into RFC 6531, which I
previously did not include. This PR closes #6531.

chore: Performance Testing Plan of Action

---

CONTRIBUTING.md

Given we've backed off its use for now.

chore(external docs): Remove bors references from CONTRIBUTING.md

---

src/sinks/elasticsearch.rs

AWS ElasticSearch expects the `Host` header to match the domain that the
request was sent to, otherwise a user will see
`InvalidHostHeaderRequests` in their AWS Console [1].
With this change, the Hostname will be set from es.REGION.amazonaws.com
to the full Hostname passed into the ES Endpoint configuration.
[1]: https://aws.amazon.com/premiumsupport/knowledge-center/es-invalidhostheaderrequests-metric/

fix(elastic service, networking): Set correct Host header with AWS ES

---

CONTRIBUTING.md
docs/README.md

This PR adds a basic README for the sake of people who want to contribute to the docs. Just some basic instructions and cognitive mapping.

enhancement(external docs): Add README for CUE sources

---

.github/workflows/test.yml
docs/reference/remap.cue
docs/reference/remap/functions/parse_apache_log.cue
docs/reference/remap/functions/parse_logfmt.cue
docs/reference/remap/functions/parse_timestamp.cue
lib/vrl/stdlib/src/parse_apache_log.rs
lib/vrl/tests/src/docs.rs

Fixes indentation causing a syntax error: https://github.com/timberio/vector/actions/runs/632661972
Fixes currently failing tests

chore(ci): Fix VRL tests

---

tests/behavior/transforms/coercer.toml
tests/behavior/transforms/remap.toml

chore(ci): Fix VRL behavior tests

---

Cargo.toml

Currently causing a CI failure https://github.com/timberio/vector/runs/2078748585

chore(ci): Bump version in Cargo.toml

---

Cargo.toml

fix(releasing): Add VRL CLI to build targets outside of *-unknown-linux-gnu and *-apple-darwin

---

docs/reference/remap/errors/651_unnecessary_error_coalescing_operation.cue
lib/vrl/compiler/src/expression/op.rs

Oopsie. Here's another one that we missed.

fix(external docs): Add docs for VRL error code 651

---

docs/reference/components/sinks.cue

chore(external docs): Extend with help about transparent gzip handling

---

docs/reference/remap/errors/652_merge_non_objects.cue

fix(external docs): Add missing error doc for code 652

---

.github/workflows/test.yml
CONTRIBUTING.md
scripts/environment/bootstrap-ubuntu-20.04.sh

chore: Upgrade to cue 0.3.0-beta.6

---

.github/workflows/release.yml
Cargo.toml

Backporting fix to debian packaging to v0.11.0 to fix https://github.com/timberio/vector/issues/5642

fix(releasing): Backport depends fix

---

lib/vrl/tests/src/main.rs
lib/vrl/tests/src/test.rs
lib/vrl/tests/tests/examples/blog_vector_remap_language.vrl
lib/vrl/tests/tests/examples/blog_vector_remap_language_error_diagnostic.vrl
lib/vrl/tests/tests/examples/blog_vector_remap_language_handle_error.vrl
lib/vrl/tests/tests/examples/blog_vector_remap_language_raise_error.vrl
lib/vrl/tests/tests/examples/blog_vector_remap_language_specify_types.vrl

This adds test-cases for all examples in the announcement blog post, to make sure they work as promoted.

chore(remap): add tests to validate announcement blog post examples

---

Cargo.lock
Cargo.toml
docs/reference/components/transforms/lua.cue
src/transforms/lua/v2/interop/event.rs
src/transforms/lua/v2/interop/log.rs
src/transforms/lua/v2/interop/metric.rs
src/transforms/lua/v2/interop/util.rs
src/transforms/lua/v2/interop/value.rs

enhancement(lua transform): Upgrade Lua runtime to 5.4

---

.github/workflows/test.yml

chore(ci): Add `test-vrl` to notification list for failed master builds

---

distribution/install.sh
docs/reference/releases/0.12.1.cue

chore(external docs): Merge down 0.12.1 changes from v0.12 branch

---

docs/reference/components/transforms/lua.cue
docs/reference/remap.cue

chore(remap, external docs): Add note about data model in the remap transform

---

docs/reference/remap/functions/to_int.cue

chore(external docs): Improve `to_int` fallible reasons

---

src/validate.rs

fix(config): Fix when to validate healthchecks

---

docs/reference/components/transforms/remap.cue

This example did not compile, but I'm curious if we should lead with something better? Or derive this example from the list of Remap examples?

chore(external docs, remap): Fix initial remap example

---

lib/vrl/stdlib/src/assert.rs
lib/vrl/stdlib/src/ends_with.rs
lib/vrl/stdlib/src/ipv6_to_ipv4.rs
lib/vrl/stdlib/src/merge.rs
lib/vrl/stdlib/src/truncate.rs
lib/vrl/stdlib/src/upcase.rs
lib/vrl/stdlib/src/uuid_v4.rs

Closes #6492 
The previous PR missed a few functions that needed unit tests restored for them. This PR should get the rest.

chore(remap): add remaining unit tests

---

docs/manual/administration/validating.md

Ref: efc73b79dca5244c129ea428ae19907cfbf6631b

fix(cli): `--no-topology` has been removed from `vector validate`

---

docs/reference/components/sinks/gcp_stackdriver_logs.cue

chore(external docs): Typo: Stackdrive => Stackdriver

---

CONTRIBUTING.md

Given we backed out trying to manage local development that way.

chore(internal docs): Remove references to nix from CONTRIBUTING.md

---

docs/reference/remap.cue

vector triggered a failure in the CUE unity test setup when running
against cbda0d34cc67041b94a1f7d9bd2557598d9f3e49:
https://github.com/cue-sh/unity/runs/2201287248?check_suite_focus=true
Investigating bug led to us discovering:
* an underlying issue in the vector CUE setup;
* an underlying CUE bug.
The CUE bug was fixed in:
https://cue-review.googlesource.com/c/cue/+/9181
This PR fixes the underlying issue in the vector CUE setup.

chore(administration): fix bug uncovered by CUE bug fix

---

Cargo.lock

Fixes a few CVEs:
* CVE-2021-3450
* CVE-2021-3449
https://www.openssl.org/news/vulnerabilities.html

chore(deps): Upgrade vendored OpenSSL

---

docs/reference/remap/functions/to_string.cue

closes: #6798
I chose to update the docs over the implementation for now. We can always revisit this later.

chore(remap): fix to_string docs

---

Cargo.toml
Makefile
tests/cli.rs

chore(tests): Add tests for `validate` healthchecks

---

.github/dependabot.yml

chore(deps): Update dependabot assignments

---

lib/k8s-e2e-tests/tests/vector-agent.rs

chore: Fix kubernetes test framework

---

.github/workflows/test.yml
CONTRIBUTING.md
scripts/environment/bootstrap-ubuntu-20.04.sh

Signed-off-by: Ben Johnson <bjohnson@binarylogic.com>

chore(ci): Upgrade cue to `0.3.0`

---

src/sinks/kafka.rs

Specifically it seems like fetching the high watermarks would sometimes
fail because the partition didn't exist yet.
This seems to be happening more often after the Tokio 1.0 upgrade, but I'm not entirely sure why. The failure condition makes sense to me as something that could happen due to us polling before the sink has written the messages.

fix(tests): Retry errors in Kafka integration tests

---

src/sinks/http.rs

Signed-off-by: Georgy Chirkov <yo@yo.qa>
Added all HTTP methods for http sink.

enhancement(http sink): Add all HTTP methods

---

Makefile

chore(tests): Fix test targeting for nginx integration tests

---

docs/manual/about/concepts.md
docs/reference/components/sources/file.cue

fix(external docs): Fix spelling and wrong docs internal link target

---

Cargo.lock
Cargo.toml
docs/reference/components/sinks/gcp_stackdriver_metrics.cue
docs/reference/services/gcp_cloud_monitoring.cue
docs/reference/urls.cue
src/sinks/gcp/mod.rs
src/sinks/gcp/stackdriver_metrics.rs

feat(new sink): Add `gcp_stackdriver_metrics` sink.

---

.github/workflows/integration-test.yml

Seems to have been an oversight.

chore(ci): Run postgresql_metrics integration test in CI

---

src/sinks/influxdb/metrics.rs

chore(influxdb_metrics sink): Test contents sent to server

---

Cargo.lock

Cargo.toml was updated in https://github.com/timberio/vector/pull/7075
but the lock file updates weren't included.

chore(deps): Update Cargo.lock

---

docs/reference/cli.cue
docs/reference/urls.cue
src/cli.rs

fix(external docs): Fix link to unit testing documentation

---

.github/workflows/test.yml
CONTRIBUTING.md
scripts/environment/bootstrap-ubuntu-20.04.sh

chore(deps): Upgrade cue to 0.3.2

---

benches/languages.rs
tests/data/wasm/multifaceted/src/lib.rs

I broke them in https://github.com/timberio/vector/pull/7118

chore(performance): Fix remap benches

---

Cargo.lock

Resolves CVE-2021-22876 CVE-2021-22890

chore(deps): Upgrade curl-sys

---

rfcs/2021-04-13-7027-core-extraction.md

This commit introduces a new RFC for extracting the core of vector. Closes #7027.

chore: Extract Core RFC

---

docs/reference/remap/functions/to_regex.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/to_regex.rs

This PR tries to address #7051 .
Suggestions are welcomed. 
Signed-off-by: Jake He <jhe@homex.com>

feat(remap): add to_regex function

---

distribution/install.sh

chore(releasing): Update install script to 0.13.1

---

.github/workflows/test.yml

Accidentally replaced with 0.3.2 when upgrading cue due to an eager
find/replace.

chore(ci): Fix action-discord version for test workflow

---

docs/reference/components/sources/internal_metrics.cue

fix(external docs): Document scrape_interval_secs for `internal_metrics` source

---

docs/reference/components/sinks/aws_s3.cue

fix(external docs): Typo

---

lib/vector-core/src/event/metric.rs
src/conditions/check_fields.rs

This commit tidies up the iterator logic suggested by clippy to be more
direct. Changed suggested by @bruceg in #7240.
Partially resolves #7327

chore: Tidy up iterator logic

---

src/internal_events/process.rs
src/lib.rs

chore: Drop redundant copy of built info

---

lib/vector-core/src/event/finalization.rs
rfcs/2021-03-26-6517-end-to-end-acknowledgement.md
src/sinks/util/http.rs
src/sinks/util/sink.rs

Ref: https://github.com/timberio/vector/pull/7325#discussion_r627817343

chore(http sink): Distinguish end-to-end errors

---

distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/helm/vector-aggregator/values.yaml

Adds option to specify the priorityClassName of the vector-agent pods in the Helm values.

enhancement(setup): Add podPriorityClassName to Helm chart

---

lib/vector-core/src/buffers/disk/leveldb_buffer.rs
lib/vector-core/src/buffers/disk/mod.rs

This commit renames the `disk::Error` type to be `disk::DataDirError` and
changes its variant names to be inline with clippy's recommendations. There's
been no logic changes made.
Resolves #7406

chore: Remove `clippy::pub_enum_variant_names` grant for `disk::Error`

---

lib/vector-core/src/buffers/mod.rs
src/buffers.rs

Previously top-level vector was responsible for creating the acker, sender and
receiver that is a 'buffer'. This commit pushes the responsibility for that work
down into core, allowing the implementation there to vary.

chore: Make buffer creation a private affair

---

docs/reference/components/sources/syslog.cue

fix(external docs): Document real behaviour of the timestamp field in Syslog source

---

docs/reference/urls.cue

Really small doc fix, this was missed in https://github.com/timberio/vector/commit/4ec1700ae55f90bf0419a22ddca7eb0e2a97b8ff

chore(external docs): Updated doc URL to the event protobuf definition.

---

scripts/environment/setup-helm.sh
scripts/helm-template-snapshot.sh

chore(kubernetes_logs source): Add kubeval checks to helm chart updates

---

lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/metric.rs
lib/vector-core/src/event/mod.rs
lib/vector-core/src/event/proto.rs
src/sinks/vector/v1.rs
src/sinks/vector/v2.rs

This also introduces a `struct WithMetadata<T>` wrapper to assist with preserving metadata through a number of protobuf conversions.
Testing for this will have to wait for #7624.
Ref #7337

enhancement(vector sink): Add acknowledgement support

---

docs/reference/configuration.cue

fix(external docs): Fix link for deprecation warnings

---

lib/vector-core/src/event/finalization.rs
src/sources/util/http.rs
src/sources/vector/v2.rs

This will break #7618 so some fix up work will be needed after either one is merged.

chore: Wrap and report batch status receive errors

---

lib/vrl/stdlib/src/parse_aws_alb_log.rs

fix(remap): Accept quoted lists in `parse_aws_alb_log` function

---

docs/reference/components.cue
src/config/mod.rs

chore(config): Default end-to-end acknowledgements to off

---

docs/reference/team.cue

chore: Add myself to docs/reference/team.cue

---

Cargo.lock
Cargo.toml
distribution/install.sh

chore(releasing): Bump Cargo.toml to 0.15.0 and update install version

---

docs/reference/remap/functions/parse_ruby_hash.cue
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/parse_ruby_hash.rs

Create ruby hash parser based on nom

feat(remap): implement ruby hash parser

---

README.md

ReadMe Update
there is a need to do some word tweak so users can relate more to the details regardless of technical level. this is the reason why I cited those words.

updated the introductory part of the readme folder

---

src/internal_events/tcp.rs

chore(observability): Log probable healthcheck as debug

---

lib/vector-core/buffers/benches/common.rs

While working on #7783 it occurred to me that I could avoid some of the calls to
`Pin::new` et al in the buffer benchmark code. This was called out in the
original review but I wasn't totally sure how to address.

chore: Tidy up buffer benchmarks

---

docs/reference/installation/_interfaces/kubectl.cue

chore(external docs): Update Vector version in kubernetes guide

---

.github/PULL_REQUEST_TEMPLATE.md

chore(administration): Fix spec and improve description in PR template

---

docs/reference/installation/_interfaces/apt.cue

Closes #7291
Thanks again for adding this upstream @ypid!

docs(setup): Add extrepo as option for apt installation

---

lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_nginx_log.rs

fix(remap): parse nginx logs with and without referrer

---

scripts/environment/bootstrap-ubuntu-20.04.sh

This appears to be causing build failures now:
https://github.com/timberio/vector/runs/2830503940#step:6:1230
And the relevant Github Actions runner issue this was meant to address
(https://github.com/actions/virtual-environments/issues/1605) has been
resolved so it doesn't seem necessary anymore.

fix(ci): Remove grub installation from ubuntu bootstrap

---

.github/workflows/metrics.yml

chore(ci): start tracking workflow metrics for baseline timings

---

docs/reference/components/sinks/elasticsearch.cue
scripts/setup_integration/elasticsearch_integration_env.sh
src/sinks/elasticsearch.rs

Reverts timberio/vector#7774
This is currently breaking integration tests on master so I figured it'd be good to temporarily revert while we look into it to keep master green.

feat(elasticsearch sink): Temporarily revert handle data stream mode

---

lib/k8s-e2e-tests/tests/vector-agent.rs

fix(tests): See if waiting to ensure checkpoint is written fixes test

---

docs/reference/components/sinks/elasticsearch.cue
scripts/setup_integration/elasticsearch_integration_env.sh
src/sinks/elasticsearch.rs

feat(elasticsearch sink): implement datastream on es

---

distribution/systemd/vector.service

Closes #7256
Credit to: @nnz1024

enhancement(releasing): Run validate before starting Vector with systemd

---

lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_nginx_log.rs

fix(remap): handle starting message from nginx

---

docs/reference/components/aws.cue

docs(aws service): Document credential expiration behavior

---

lib/k8s-e2e-tests/tests/vector-agent.rs

chore(tests): Glob faster in checkpoint test

---

lib/k8s-e2e-tests/tests/vector-agent.rs

Currently broken since 7ac33e2ac32f78e87380fafc4842bf5840a8849a . We
tried to fix it with https://github.com/timberio/vector/pull/8003 but it
appears that didn't work so just ignoring until we can fix it to keep
master green.

chore(ci): Temporarily ignore checkpoint test

---

.github/workflows/k8s_e2e.yml
Cross.toml

For correctness tests we don't need release optimizations.
Closes #7899

chore(ci): Make k8s e2e workflow build faster

---

docs/reference/installation/_interfaces/msi.cue

Closes #8016 by correcting the file path

chore(setup): Fix config example for windows install

---

docs/reference/components.cue

To match actual defaults and types from `TowerRequestConfig`:
https://github.com/timberio/vector/blob/629e3b434fa6a57fbb21b69afd605fd558055f20/src/sinks/util/service.rs#L186-L213

chore(external docs): Update request defaults in docs

---

distribution/helm/vector-aggregator/templates/service-headless.yaml

chore(helm platform): Use the same conditional for both regular and headless service

---

distribution/helm/vector-shared/templates/_reroll.tpl
distribution/kubernetes/vector-agent/resources.yaml
distribution/kubernetes/vector-aggregator/resources.yaml
distribution/kubernetes/vector-all/resources.yaml
tests/helm-snapshots/builtin_configs/vector-agent/snapshot.yaml
tests/helm-snapshots/builtin_configs/vector-aggregator/snapshot.yaml
tests/helm-snapshots/topology_config/vector-agent/snapshot.yaml
tests/helm-snapshots/topology_config/vector-aggregator/snapshot.yaml

These values are currently inaccurate.
https://github.com/timberio/vector/issues/8038 represents the work to
re-add them.

chore(kubernetes platform): Remove checksum/config

---

src/app.rs
src/sources/host_metrics.rs

fix(host_metrics source): `init_roots` on `build`

---

src/sinks/loki.rs

`all_fields()` flattens nested objects into `key.subkey` but we should
just be inserting them as-is.
Fixes #7815

fix(loki sink): Avoid flattening objects

---

.github/workflows/integration-test.yml

fix(ci): Fix make target for EventStoreDB integration tests

---

.github/PULL_REQUEST_TEMPLATE.md
docs/reference/remap/functions/assert.cue
rfcs/2020-08-04-3325-remap-v2.md

docs: Improve example, fix spelling and fix URL link

---

docs/reference/components/transforms/lua.cue

Resolves:
https://github.com/timberio/vector/discussions/8133#discussioncomment-971041

docs(lua transform): Fix timestamp parsing example

---

CONTRIBUTING.md
scripts/environment/bootstrap-macos-10.sh
scripts/environment/bootstrap-ubuntu-20.04.sh

chore: Update CUE's address

---

docs/cue/reference/components/sinks/gcp_stackdriver_logs.cue
src/sinks/gcp/stackdriver_logs.rs

close https://github.com/timberio/vector/issues/6009

enhancement(gcp_stackdriver_logs sink): Allow template syntax in log_id

---

docs/cue/reference/components/sources/internal_logs.cue

This was actually released in 0.12
Closes #5977

docs(internal_logs source): Fix min Vector version

---

docs/layouts/partials/meta.html
docs/scripts/algolia-index.ts

This PR adds a `pageTitle` field to the search index for Algolia.

enhancement(search): Add page title to Algolia search index

---

docs/content/en/_index.md
docs/content/en/highlights/2019-12-14-kubernetes-source-alpha.md
docs/content/en/highlights/2020-10-27-kubernetes-integration.md
docs/cue/reference/components/sources/kubernetes_logs.cue
docs/cue/reference/examples.cue
docs/cue/reference/remap/functions/parse_int.cue
docs/layouts/home.html
docs/layouts/partials/home/configure.html

This PR also fixes some typos.

enhancement(external docs): Add Vector config examples to main page of vector.dev

---

docs/cue/reference/examples.cue

@jszwedko Oopsie. Clicked auto-merge and then forgot that I had done so. This PR addresses the issues you pointed out in the last PR.

fix(external docs): Fix issues in main page config examples

---

docs/assets/js/below.js
docs/layouts/shortcodes/api/endpoints.html

This PR makes the API endpoints headers so that the text describing those endpoints gets properly search indexed.

fix(search website): Add headings to HTTP API endpoints

---

lib/file-source/src/file_server.rs

fix(file source): write checkpoints before shutdown

---

docs/README.md

enhancement(internal docs): Add Netlify status badge to website README

---

docs/package.json
docs/yarn.lock

Just a bit of housekeeping. Shouldn't make any substantial difference but good to keep up.

enhancement(css website): Upgrade Tailwind to 2.24

---

docs/cue/reference/components/sinks/loki.cue

Signed-off-by: cmsxbc <i@cmsis.me>
Fixes #8313

enhancement(external docs): add batch.max_bytes in loki sink

---

docs/cue/reference/remap/functions/assert_eq.cue

Fixes the slight mismatch in the diagnostic of a VRL assertion

chore: Fix cue docs test

---

docs/cue/reference/services/prometheus_remote_write.cue

Addresses
https://github.com/timberio/vector/pull/8269#pullrequestreview-708504242

docs: clarify remote_write flag for prometheus

---

docs/cue/reference/components/sinks/gcp_stackdriver_logs.cue

close https://github.com/timberio/vector/issues/5105

fix(external docs): Fix stackdriver logging example in docs

---

Cargo.lock
Cargo.toml
docs/cue/reference/administration/interfaces/kubectl.cue

chore(releasing): Update version in Cargo.toml

---

.github/workflows/test.yml
docs/cue/reference/remap/functions/assert.cue
docs/cue/reference/remap/functions/assert_eq.cue
lib/vrl/tests/src/docs.rs

chore: Fix VRL examples for assert functions

---

docs/layouts/partials/data.html

fix(template website): Display enum option table for component config sub-params

---

scripts/setup_integration/nginx_integration_env.sh

chore: add missing '/' from nginx integration script

---

docs/static/press/vector-icon.svg

fix(external docs): Reinstate link to /press/vector-icon.svg

---

docs/cue/reference/components/sources/host_metrics.cue
src/sources/host_metrics.rs

feat(host_metrics source): Add disk_used_ratio to host metrics

---

docs/content/en/docs/setup/installation/package-managers/yum.md

docs: Add missing | to yum docs

---

.github/workflows/k8s_e2e.yml
CONTRIBUTING.md
Cargo.lock
Cargo.toml
docs/reference/releases/0.14.0.cue
docs/reference/releases/0.14.1.cue
lib/file-source/Cargo.toml
lib/file-source/src/checkpointer.rs
lib/file-source/src/file_server.rs
lib/file-source/src/fingerprinter.rs
scripts/test-e2e-kubernetes.sh

chore(releasing): Prep 0.14.1 release

---

distribution/install.sh

Rather than `latest` so this doesn't break if it isn't updated before
the next version is released.

chore(releasing): Have install.sh script pull from release directory

---

src/app.rs

This defaults to `tokio-runtime-worker`.
Closes: #8330

enhancement(observability): Name vector worker threads

---

docs/content/en/docs/setup/installation/package-managers/helm.md

fix(external docs): Update Helm install instructions

---

docs/cue/reference/components/sinks/aws_s3.cue

This PR removes an MDX component from the CUE sources.

fix(external docs): Remove stray MDX component

---

docs/Makefile
docs/assets/js/app.js
docs/config.toml
docs/cue/reference/components/sources/socket.cue
docs/cue/reference/components/transforms/log_to_metric.cue
docs/cue/reference/components/transforms/metric_to_log.cue
docs/cue/reference/components/transforms/reduce.cue
docs/cue/reference/components/transforms/route.cue
docs/cue/reference/components/transforms/tag_cardinality_limit.cue
docs/layouts/docs/component.html
docs/layouts/partials/components/example-configs.html
docs/layouts/partials/data.html
docs/package.json
docs/scripts/create-config-examples.js
docs/yarn.lock

Forgive me, for this JavaScript is a sin 🙏🏼
There's room for improvement here but I think this gets us reasonable copy/paste-able config snippets akin to what's currently available on vector.dev.

enhancement(external docs): Provide per-component config examples

---

docs/cue/reference/components/sources/internal_metrics.cue
src/sources/internal_metrics.rs

enhancement(internal_metrics source): Allow disabling of the host/pid keys

---

docs/yarn.lock

fix(external docs): Run yarn upgrade

---

src/sources/file.rs

chore: Ignore test_split_reads on Mac

---

.github/workflows/nightly.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
distribution/install.sh
distribution/rpm/vector.spec
docs/content/en/releases/0.15.1.md
docs/cue/reference/administration/interfaces/kubectl.cue
docs/cue/reference/releases/0.15.1.cue
docs/cue/reference/versions.cue
scripts/verify-install.sh

Cherry-picks RPM bug fix https://github.com/timberio/vector/commit/142427f16d01b341c566e506fbaa6bfd563d655e and preps release.

chore(releasing): Prep v0.15.1

---

rfcs/2021-07-20-8288-csv-enrichment.md

Ref #8288 
[Readable](https://github.com/timberio/vector/blob/5d7208667d476bed4adca5d7422c6d024bd946eb/rfcs/2021-07-20-8288-csv-enrichment.md)
RFC for adding functions to VRL to enable enrichment via CSV files. 

chore(vrl): CSV enrichment RFC

---

docs/scripts/create-config-examples.js

Fixes #8506
It's not pretty, and I do hope we can make that script less kludgey at some point, but it works!
Example fix:
https://deploy-preview-8517--vector-project.netlify.app/docs/reference/configuration/sources/nginx_metrics/

fix(external docs): Fix example array generation

---

rfcs/_YYYY-MM-DD-issue#-title.md

Some small RFC template refinements. I added a new "Future improvements" section that should help keep RFC scope small while demonstrating sound design. The rest is just language adjustments.

chore: RFC template refinements

---

src/validate.rs

fix(cli): Use env vars with `vector validate` command

---

src/topology/running.rs

This commit adjusts the deadline checking code in accordance with a TODO comment
left in the codebase. We now use `Duration::checked_duration_since`.

chore: Resolve TODO in topology code

---

CONTRIBUTING.md
USER_EXPERIENCE_DESIGN.md

The beginnings of a user experience design policy. I've wanted this document many times in the past to help align everyone behind shared principles and guidelines so that Vector upholds a high quality user experience. This should reduce questions around feature design, user facing changes, and rework as a result of lack of context in this area.
I plan to expand this document to include policies on deprecations, backward compatibility, and component statuses.

chore: Add user experience design document

---

USER_EXPERIENCE_DESIGN.md

docs: typo

---

docs/cue/reference/components/sinks/aws_sqs.cue
docs/cue/reference/urls.cue
src/sinks/aws_sqs.rs

enhancement(aws_sqs sink): Add message_deduplication_id support

---

distribution/helm/vector-agent/templates/daemonset.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/statefulset.yaml
distribution/helm/vector-aggregator/values.yaml

Hi there. This PR is adding options to the vector-agent helm chart to:
- set liveness probe
- set readyness probe
- set dnsPolicy
- add dnsConfig

enhancement(helm platform): Add DNS Policy and Config, Liveness and Readyness probes.

---

docs/cue/reference/components/transforms/aggregate.cue

docs(aggregate transform): Fix example title

---

docs/layouts/partials/data.html

Fixes #8655
The page in question:
https://deploy-preview-8668--vector-project.netlify.app/docs/reference/vrl/expressions

fix(external docs): Fix anchor IDs on VRL expressions page

---

distribution/helm/vector-agent/templates/secret.yaml
distribution/helm/vector-agent/values.yaml
distribution/helm/vector-aggregator/templates/secret.yaml
distribution/helm/vector-aggregator/values.yaml

Closes #8522
We could also add some templating to auto include these as env vars in the pod (if wanted)

enhancement(helm platform): Allow creation of Secret resources from Helm charts

---

docs/layouts/partials/data.html
docs/layouts/partials/heading.html

Addresses #8656
Here's an example link: https://deploy-preview-8682--vector-project.netlify.app/docs/reference/vrl/expressions/#assignment-example-nested-path-assignment

enhancement(external docs): Provide links for VRL expression examples

---

docs/cue/reference/components/transforms/aws_ec2_metadata.cue

docs(aws_ec2_metadata transform): Document instance-type field

---

distribution/install.sh
docs/content/en/releases/0.15.2.md
docs/cue/reference/releases/0.15.2.cue
docs/cue/reference/remap/functions/assert.cue
docs/cue/reference/versions.cue
docs/layouts/partials/navbar/search-bar.html
src/validate.rs

The commits are wrong, but the diff is right.

chore(releasing): Merge 0.15.2 into website

---

src/internal_events/aws_s3.rs
src/sinks/aws_s3.rs

We weren't shipping this before.

enhancement(aws_s3 sink): emit processed bytes when sending requests

---

docs/config.toml

This PR makes the change whose necessity was pointed out in #8696.
Major props to @DavidWeid for catching this!

fix(external docs): Fix base URL in site config

---

src/sinks/util/batch.rs
src/sinks/util/buffer/json.rs
src/sinks/util/buffer/loki.rs
src/sinks/util/buffer/mod.rs
src/sinks/util/buffer/vec.rs

chore: Clarify message when droppping large events

---

website/README.md

We are switching to use the current release branch as the website
production branch.

docs: Update website development branch documentation

---

src/internal_events/adaptive_concurrency.rs

enhancement(observability): Report more ARC metrics

---

website/content/en/docs/setup/installation/platforms/kubernetes.md

This worked for me instead of `kubectl`, unless I'm missing something

docs: update kubernetes configuration instructions

---

website/content/en/highlights/2021-08-24-helm-vector-dev.md

chore: Update helm.vector.dev highlight title

---

website/cue/reference/remap/functions/to_timestamp.cue

docs(vrl): Document support for converting floats to timestamps

---

scripts/release-helm.sh

chore: Publish vector-aggregator to latest repo

---

Cargo.lock

chore(deps): Regenerate Cargo.lock

---

src/sinks/util/test.rs
src/sinks/vector/v2.rs

fix(vector sink): retry on failed connection

---

website/cue/reference/components/sinks.cue

docs: Clarify request concurrency parameters

---

Cargo.lock
Cargo.toml

Replaces:
#8631 
#8630 
#8784 
Since they all need to be updated together.

chore(deps): bump opentelemetry dependencies

---

Cargo.lock
deny.toml

* RUSTSEC-2021-0089
* RUSTSEC-2021-0093

chore(deps): Update vulnerable dependencies

---

distribution/docker/alpine/Dockerfile
distribution/docker/debian/Dockerfile
distribution/docker/distroless-libc/Dockerfile
distribution/docker/distroless-static/Dockerfile
tests/data/dnstap/Dockerfile

chore(deps): Update base docker images

---

website/content/en/highlights/2021-08-24-vector-aggregator.md

Closes #8742
[Rendered](https://deploy-preview-8800--vector-project.netlify.app/highlights/2021-08-24-vector-aggregator/)

chore: Add vector-aggregator highlight

---

Cargo.lock

chore(deps): Update openssl crate

---

website/config.toml
website/cue/reference/urls.cue

chore: Update link to RELEASING.md

---

docs/USER_EXPERIENCE_DESIGN.md

This is a topic that came up today and felt it should be in the UX design doc.

chore: Add data loss defaults to user experience design

---

website/README.md
website/content/en/guides/advanced/wasm-hello.md
website/content/en/guides/advanced/wasm-multiline.md
website/layouts/docs/component.html
website/layouts/partials/blog/content.html
website/layouts/partials/content.html

Signed-off-by: Luc Perkins <luc.perkins@datadoghq.com>

enhancement(search website): Add system for de-indexing pages

---

website/content/en/docs/setup/installation/manual/from-source.md

docs: Update docker cross build instructions

---

lib/vrl/stdlib/src/parse_ruby_hash.rs

fix(vrl): handle complex ruby objects

---

src/sources/journald.rs
website/cue/reference/components/sources/journald.cue

close https://github.com/timberio/vector/issues/8255

enhancement(journald source): Add include_matches/exclude_matches options

---

website/cue/reference/components/sources/socket.cue
website/layouts/partials/data.html

fix(external docs): Add relevant when conditions to top-level configs

---

website/content/en/docs/setup/installation/platforms/kubernetes.md

chore(external docs): Add docs for using the Aggregator role with kustomize

---

tests/data/README.md

I figure we can start doing this as we introduce more test data files or regenerate existing ones.
Follow-up to #9053 

chore: Add how test intermediate certificates were generated

---

src/config/builder.rs
src/config/compiler.rs
src/config/id.rs
src/config/pipeline.rs
src/config/unit_test.rs
src/config/validation.rs

fix(config): ensure components don't have dots in their names

---

lib/vector-core/src/metrics/label_filter.rs
src/config/id.rs
src/config/mod.rs
src/sources/file.rs
src/sources/journald.rs
src/sources/kubernetes_logs/mod.rs
src/sources/socket/mod.rs
src/sources/vector/v1.rs
src/topology/builder.rs
src/topology/running.rs
src/topology/task.rs
tests/pipelines/vector.toml
website/cue/reference/components/sources/internal_metrics.cue

feat(pipelines): add component_scope field to internal metrics

---

src/sources/host_metrics/cgroups.rs

The cgroups metrics collector in the host_metrics source would report
errors while opening, reading, or parsing files without providing any
indication which file was at issue. This enhances those errors and adds
a start-up debug level message about which cgroup base directory was
detected.

chore(host_metrics source): Improve error reporting for cgroups metrics

---

src/codecs/mod.rs
src/codecs/parsers/bytes.rs
src/codecs/parsers/mod.rs

chore(codecs): Implement `bytes` parser

---

src/codecs/parsers/mod.rs
src/codecs/parsers/syslog.rs
src/internal_events/syslog.rs
src/sources/syslog.rs

chore(codecs): Implement `syslog` parser

---

src/codecs/parsers/json.rs
src/codecs/parsers/mod.rs

chore(codecs): Implement `json` parser

---

src/sources/internal_logs.rs

fix(tests): work around internal_logs lack of isolation

---

lib/k8s-e2e-tests/src/lib.rs

fix(tests): Fix smoke test first line function for e2e kubernetes tests

---

src/config/unit_test.rs
src/topology/builder.rs

Makes enrichment tables usable in test.

fix(enriching): Usable in Test

---

lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/find.rs
lib/vrl/stdlib/src/lib.rs
website/cue/reference/remap/functions/find.cue

feat(vrl): add find function

---

website/cue/reference/components.cue
website/cue/reference/components/sinks.cue
website/cue/reference/components/sinks/aws_cloudwatch_logs.cue
website/cue/reference/components/sinks/aws_kinesis_firehose.cue
website/cue/reference/components/sinks/aws_kinesis_streams.cue
website/cue/reference/components/sinks/aws_s3.cue
website/cue/reference/components/sinks/aws_sqs.cue
website/cue/reference/components/sinks/azure_blob.cue
website/cue/reference/components/sinks/console.cue
website/cue/reference/components/sinks/file.cue
website/cue/reference/components/sinks/gcp_cloud_storage.cue
website/cue/reference/components/sinks/http.cue
website/cue/reference/components/sinks/humio.cue
website/cue/reference/components/sinks/kafka.cue
website/cue/reference/components/sinks/loki.cue
website/cue/reference/components/sinks/nats.cue
website/cue/reference/components/sinks/papertrail.cue
website/cue/reference/components/sinks/pulsar.cue
website/cue/reference/components/sinks/redis.cue
website/cue/reference/components/sinks/socket.cue
website/cue/reference/components/sinks/splunk_hec_logs.cue

docs(sinks): Add documentation for encoding.codec

---

docs/DEVELOPING.md

Signed-off-by: Nathan Fox <fuchsnj@gmail.com>
Fix a small copy/paste error in the docs.

docs(internal docs): fix example command in DEVELOPING.md

---

Cargo.lock
deny.toml

chore(ci): Remove unused advisory

---

Cargo.toml

admin seems to be the best fit. This is what rsyslog is under, for
example.
https://packages.debian.org/unstable/
Closes: #9162

enhancement(releasing): Add section for debian package

---

website/content/en/docs/about/under-the-hood/architecture/pipeline-model.md

chore(external docs): Fix typo on pipelines page

---

src/topology/builder.rs

This commit introduces a `ready_chunks` into the pipeline for function
transforms. This combinator polls the underlying stream until either it signals
Pending or the chunk limit is reached, sending a vector of items downstream. In
this commit we pull at most 128 `Event` instances off the input stream for
processing, improving locality.
I have not done the same for task transforms, though I think it could be
done. Without changing the trait type we'd need the inverse of `ready_chunks` to
move from a `Stream<Item = Vec<Event>>` into a `Stream<Item = Event>`.
This is worth +7MB/s in #8512

chore: Slip `ready_chunks` into `Transform::Function` processing

---

website/config.toml
website/layouts/_default/baseof.html

Just a small thing for future site stewards.

fix(external docs): Make the top-line banner togglable in the site config

---

website/config.toml
website/layouts/docs/component.html
website/layouts/partials/content.html
website/layouts/partials/docs/component-under-hero.html
website/layouts/partials/page-actions.html

fix(external docs): Add source/edit buttons to docs and guides

---

website/content/en/docs/setup/installation/manual/vector-installer.md
website/content/en/docs/setup/quickstart.md
website/content/en/guides/getting-started/getting-started.md
website/content/en/highlights/2020-07-09-add-musl-and-glibc-support-to-install-sh.md
website/cue/reference/administration/install_commands.cue
website/cue/reference/administration/interfaces/vector_installer.cue

Closes: #9265
We should probably update the install script to not require bash, to
target more platforms, but this fixes the immediate issue.

fix(releasing): Use bash rather than sh for script installer

---

src/sources/kubernetes_logs/pod_metadata_annotator.rs
website/cue/reference/components/sources/kubernetes_logs.cue

Close #8338
The issue should have enough context, let me know if you need more information. Also, should we make this behind a flag?

feat(kubernetes_logs source): add pod annotations

---

Cargo.lock
Cargo.toml
lib/vector-api-client/graphql/schema.json
lib/vector-core/Cargo.toml

chore(deps): Bump to async-graphql 2.10.0

---

website/cue/reference/components/sources/syslog.cue

Signed-off-by: Luc Perkins <luc.perkins@datadoghq.com>

chore(external docs): Fix typo in VRL example

---

lib/enrichment/src/find_enrichment_table_records.rs
lib/enrichment/src/get_enrichment_table_record.rs
lib/enrichment/src/test_util.rs
lib/enrichment/src/vrl_util.rs

Ref #8815 
This enables the enrichment table functions to search on date ranges. #9021 Added the ability to the enrichment tables, but neglected to update the VRL functions to use the search!

enhancement(enriching): enrichment functions need to specify date conditions

---

website/cue/reference/examples.cue

docs: Fix reference examples

---

src/codecs/framers/mod.rs
src/codecs/framers/newline_delimited.rs
src/codecs/mod.rs
src/codecs/parsers/mod.rs
src/sources/socket/mod.rs
src/sources/socket/tcp.rs
src/sources/socket/udp.rs
src/sources/socket/unix.rs
website/cue/reference/components/sources/socket.cue

enhancement(codecs, socket source): Integrate `Decoder`/`DecodingConfig` with `socket` source

---

website/cue/reference/components/sources/socket.cue

Somehow the format check in #9209 passed but failed after merging with master.

chore: Fix cue docs formatting

---

src/sinks/util/retries.rs

After temporarily disabling retries against a poorly ElasticSearch cluster with `request.retry_attempts = 0`, I was a bit worried at the messages appearing in logs from the 0.16.1 service, indicating ES was still returning errors:
```
Sep 20 10:37:42 myhostname vector[29536]: Sep 20 10:37:42.486 ERROR sink{component_id=aws_es component_kind="sink" component_type=elasticsearch component_name=aws_es}:request{request_id=46354}: vector::sinks::util::retries: Retries exhausted; dropping the request.
```
After reading the vector code a bit more I realised it was probably a false alarm.  This PR improves the error message to only report if it would otherwise retry.

fix(observability): Improve misleading retry error message

---

website/layouts/partials/data.html

fix(external docs): Add column for VRL function arg optionality

---

website/tailwind.config.js

PR #9377 accidentally introduced some font color issues resolved by this PR, which simply reverts those changes straight up.

fix(external docs): Fix code font color changes

---

Makefile

enhancement(dev): Added check-build-tools to Makefile (#8146)

---

website/yarn.lock

Just some periodic housekeeping.

chore(external docs): Upgrade node dependencies

---

lib/vector-core/src/config/global_options.rs
src/config/builder.rs
src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/tests.rs

Closes #9298 
Signed-off-by: Vladimir Zhuk <vladimir.zhuk@datadoghq.com>

enhancement(datadog_logs sink): Set DD origin headers

---

Cargo.lock
lib/enrichment/src/find_enrichment_table_records.rs
lib/enrichment/src/get_enrichment_table_record.rs
lib/vrl/tests/Cargo.toml
lib/vrl/tests/src/main.rs
lib/vrl/tests/src/test_enrichment.rs

This adds some examples to the enrichment table VRL functions.
To actually make these functions return realistic looking data I also added a test enrichment table to the vrl test project for these examples to search against, otherwise we would just get errors in the examples which didn't feel as useful.

chore(enriching): added enrichment table function examples

---

website/content/en/docs/setup/installation/platforms/kubernetes.md

"kubectl install" to "kubectl apply"

docs:  Fix kubectl apply command

---

website/content/en/docs/reference/configuration/unit-tests.md

Signed-off-by: Luc Perkins <luc.perkins@datadoghq.com>

fix(external docs): Fix two broken links

---

lib/soak/Dockerfile

I am wondering if we could somehow drive this from rust-toolchain to
avoid drift.

chore(deps): Fix soak test Rust version

---

config/examples/namespacing/sinks/es_cluster.toml
config/examples/namespacing/sinks/s3_archives.toml
config/examples/namespacing/sources/apache_logs.toml
config/examples/namespacing/transforms/apache_parser.toml
config/examples/namespacing/transforms/apache_sample.toml
config/examples/namespacing/vector.toml
src/config/loading.rs
tests/namespacing-fail/foo/bar.toml
tests/namespacing-fail/sinks/es_cluster.json
tests/namespacing-fail/sources/apache_logs.toml
tests/namespacing-fail/tests/foo.toml
tests/namespacing-fail/transforms/apache_parser.toml
tests/namespacing-fail/vector.toml
tests/namespacing/sinks/es_cluster.json
tests/namespacing/sources/apache_logs.toml
tests/namespacing/tests/foo.toml
tests/namespacing/transforms/apache_parser.toml
tests/namespacing/vector.toml
website/content/en/docs/reference/configuration/_index.md
website/content/en/guides/getting-started/getting-started.md
website/content/en/guides/level-up/managing-complex-configs.md
website/cue/reference/configuration.cue

Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>

enhancement(config): Implicit namespacing based on the config directory structure

---

.github/workflows/soak.yml
.github/workflows/soak_observer.yml
soaks/bin/analyze_experiment.sh

This commit adds an additional step to the soak analysis which comments on
pull-requests as soaks wrap up. This makes it easier for folks to see if
their change adjusts vector performance, relative to the baseline.
Closes #9622

chore: Add soak analysis as PR comment

---

soaks/README.md

With description of where to find them.

chore(internal docs): Replace index of soak tests

---

website/content/en/docs/reference/configuration/unit-tests.md

```toml
[transforms.add_env_to_metric]
type = "remap"
inputs = []
source = '''
env, err = get_env_var!("ENV")
if err != null {
log(err, level: "error")
}
tags.environment = env
'''
```

docs: Fix VRL example on unit testing page

---

lib/vector-core/src/config/log_schema.rs

closes https://github.com/vectordotdev/vector/issues/9960

fix(config):  Fix global override for `source_type_key`

---

lib/vector-core/src/transform/config.rs
src/transforms/pipelines/mod.rs

Following https://github.com/vectordotdev/vector/pull/9733#pullrequestreview-798296774

chore(doc): fix some doc wording in pipelines transform

---

soaks/common/terraform/modules/lading_http_blackhole/main.tf
soaks/tests/fluent_elasticsearch/README.md
soaks/tests/fluent_elasticsearch/terraform/http_blackhole.toml
soaks/tests/fluent_elasticsearch/terraform/main.tf
soaks/tests/fluent_elasticsearch/terraform/tcp_gen.toml
soaks/tests/fluent_elasticsearch/terraform/variables.tf
soaks/tests/fluent_elasticsearch/terraform/vector.toml

chore: Introduce fluent -> elasticsearch soak

---

website/cue/reference/authors.cue

chore(external docs): Add Barry Eom to authors list

---

website/content/en/docs/reference/configuration/unit-tests.md

enhancement(external docs): Add docs for no_outputs_from in unit tests

---

docs/CONTRIBUTING.md

chore: Swap out DCO for CLA

---

website/assets/js/tracking-marketing.js
website/layouts/partials/javascript/head.html

- Create `tracking-marketing.js` to hold tracking scripts
- Adds Marketo Munchkin tracking script to `head.html` to be loaded on every page
Reference:
- https://datadoghq.atlassian.net/browse/WEB-1861

chore(javascript website): Add Marketo Tracking to Vector.dev

---

website/layouts/partials/download/download-matrix.html
website/layouts/releases/single.html

- Update release notes page (single.html template) to add the download matrix
- Allow user to easily download the release related to the release notes
https://deploy-preview-10035--vector-project.netlify.app/releases/0.17.3/

enhancement(template website): Add download matrix to release notes page

---

website/README.md

This PR adds some tips for people struggling with CUE. I'll add more here as footguns occur to me but this is an okay start.

enhancement(external docs): Add CUE dev tips to website README

---

src/config/compiler.rs
src/config/graph.rs

Signed-off-by: Vladimir Zhuk <vladimir.zhuk@datadoghq.com>
The cycle detection was sub-optimal with exponential complexity, which would end up in extremely slow config loading for larger graphs.

fix(config): optimize cycle detection in the graph

---

website/content/en/highlights/2021-11-16-implicit-namespacing.md

docs(config): Added automatic namespacing article

---

.github/workflows/soak.yml

Commenting it completely out is causing Github Actions to complain that
the file is missing `on`. I think maybe defining `on` as an empty map
could work?

chore(ci): Try disabling soak workflow another way

---

website/content/en/highlights/2021-11-16-failed-event-routing.md

docs(transforms): Added failed route event routing highlight article

---

lib/datadog/grok/src/grok_filter.rs
lib/datadog/grok/src/parse_grok.rs
lib/datadog/grok/src/parse_grok_pattern.rs
lib/datadog/grok/src/parse_grok_rules.rs
lib/datadog/grok/src/parser.lalrpop

Contains a couple of bug fixes(split by commits) found during testing real-life configs.

fix(vrl): fix some `parse_groks` issues

---

src/sinks/elasticsearch/service.rs

chore(elasticsearch sink): Remove println from es service

---

website/cue/reference/releases/0.18.0.cue

https://deploy-preview-10120--vector-project.netlify.app/releases/0.18.0/

chore: Add known issues section to 0.18.0

---

website/content/en/docs/reference/configuration/_index.md

docs: Fix automatic namespacing example transform name

---

website/content/en/docs/administration/monitoring.md

docs: Fix basic internal_logs example config

---

website/content/en/releases/0.18.1.md

chore: Fix title for 0.18.1 release page

---

website/cue/reference.cue
website/cue/reference/components/transforms/filter.cue
website/cue/reference/components/transforms/route.cue
website/cue/reference/components/transforms/sample.cue
website/cue/reference/components/transforms/throttle.cue
website/cue/reference/urls.cue
website/layouts/partials/data.html

Affected sections:
https://deploy-preview-10157--vector-project.netlify.app/docs/reference/configuration/transforms/filter/#condition
https://deploy-preview-10157--vector-project.netlify.app/docs/reference/configuration/transforms/sample/#exclude
https://deploy-preview-10157--vector-project.netlify.app/docs/reference/configuration/transforms/throttle/#exclude
I don't really love this just yet but it's a decent first stab. Curious what others think about this approach.

enhancement(external docs): Multiple condition types

---

website/content/en/guides/level-up/csv-enrichment-guide.md

docs(enriching): Added a guide article on how to use enrichment tables with two example use cases

---

benches/lua.rs
benches/remap.rs
lib/vector-core/core-common/src/byte_size_of.rs
lib/vector-core/src/fanout.rs
lib/vector-core/src/lib.rs
lib/vector-core/src/test_util.rs
lib/vector-core/src/transform/config.rs
lib/vector-core/src/transform/mod.rs
src/app.rs
src/config/unit_test.rs
src/test_util/mod.rs
src/topology/builder.rs
src/topology/mod.rs
src/transforms/aws_cloudwatch_logs_subscription_parser.rs
src/transforms/coercer.rs
src/transforms/filter.rs
src/transforms/grok_parser.rs
src/transforms/json_parser.rs
src/transforms/key_value_parser.rs
src/transforms/log_to_metric.rs
src/transforms/logfmt_parser.rs
src/transforms/metric_to_log.rs
src/transforms/mod.rs
src/transforms/regex_parser.rs
src/transforms/remap.rs
src/transforms/tokenizer.rs

There are still a few bits left here to finish (adding doc comments, concurrency-specific metrics, etc), but the core is in place and ready for feedback.

enhancement(topology): run transforms concurrently

---

.github/workflows/test.yml
website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md

docs: Fix whitespace in highlight guide for 0.19

---

website/cue/reference/components.cue

docs: Fix description of tls options

---

website/cue/reference/components/transforms/filter.cue

docs: Fix example for filter transform

---

docs/specs/component.md

This prompted by some [discussion on the New Relic
sink](https://github.com/vectordotdev/vector/pull/9764#discussion_r767986478)

docs(internal docs): Add note about health checks to component spec

---

.github/workflows/soak.yml

chore(ci): More soak refactoring to leverage matrices

---

src/sinks/blackhole/sink.rs

The blackhole sink has a `rate` config option that sets a rate-limit for how fast events are accepted. This works by delaying for a certain amount of time to achieve the desired rate. However, this delay is applied to an entire batch at once, not per-event.
`ready_chunks(1024)` is used for performance reasons to batch work. But if the `rate` is set to below 1024, this can cause an unnecessary delay in the amount of time it takes for metrics on the sink to update. In the worst case scenario, where the `rate` is set to 1 (1 per second), and there is a backlog of >=1024 events, it will take **over 17 minutes** for metrics to be updated. This is certainly not expected behavior.
The batching is now reduced if the `rate` is low. This will not noticeably impact performance since high rates will …

fix(blackhole sink): update metrics more often with a low rate limit

---

lib/k8s-e2e-tests/src/lib.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
lib/k8s-e2e-tests/tests/vector.rs
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/vector.rs
scripts/deploy-chart-test.sh

chore: Update k8s-e2e to use new helm chart

---

website/content/en/highlights/2021-11-18-implicit-namespacing.md
website/content/en/highlights/2021-12-14-improved-concurrency-model.md

... and fixed a very minor typo in implicit namespacing article

docs(performance): added highlight article for improved concurrency 

---

website/content/en/docs/setup/installation/package-managers/helm.md
website/content/en/docs/setup/installation/platforms/kubernetes.md

docs: Update Kubernetes and Helm docs to new chart

---

website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md
website/cue/reference/releases/0.19.0.cue

docs: Fix broken 0.19.0 links

---

website/cue/reference/components/sinks/kafka.cue

Ref: https://github.com/vectordotdev/vector/issues/10465#issuecomment-1002770627

docs(kafka sink): Document that topic is templatable

---

.github/workflows/integration-test.yml

chore: Fix typo in docker compose integration tests

---

.github/workflows/soak.yml

I _think_ the multi-if for the cancel job is correct

chore: Stop running soak jobs for dependabot PRs

---

netlify.toml

chore: Fix url for discussions redirect

---

src/sinks/kafka/config.rs

fix warning:
```
2022-01-04 17:07:53.923398500 2022-01-04T09:07:53.923205Z  WARN log: librdkafka: CONFWARN [thrd:app]: Configuration property queued.min.messages is a consumer property and will be ignored by this producer instance log.target="librdkafka" log.module_path="rdkafka::client" log.file="/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs" log.line=66
2022-01-04 17:07:53.925266500 2022-01-04T09:07:53.925188Z  WARN log: librdkafka: CONFWARN [thrd:app]: Configuration property compression.codec is a producer property and will be ignored by this consumer instance log.target="librdkafka" log.module_path="rdkafka::client" log.file="/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs" log.line=66
2022-01-04 17:07:53.925267500 …
```

fix(kafka sink): Separate default consumer/producer configs

---

website/content/en/docs/reference/configuration/transforms/aggregate.md
website/content/en/docs/reference/configuration/transforms/dedupe.md
website/content/en/docs/reference/configuration/transforms/throttle.md

- chore: Remove reference to time in dedupe description
- chore: Add missing descriptions to aggregate and throttle
Closes #10772

chore: Update transforms descriptions

---

website/cue/reference/components/sources/nginx_metrics.cue

chore: Fix type in nginx_metrics source documenatation

---

website/cue/reference/components/sources/datadog_agent.cue

This PR documents the multiple outputs introduced in #10776.

docs(datadog_agent source): Document outputs for datadog agent source

---

src/codecs/format/json.rs
src/codecs/format/mod.rs
src/codecs/mod.rs

Part of #8617, #10254 and towards the implementation of RFC #9864.

chore(codecs): Implement `JsonSerializer`

---

website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md

chore: Fix elasticsearch section name in upgrade 0.19 guide

---

src/sinks/new_relic/config.rs
src/sinks/new_relic/sink.rs

Silent merge conflict with #10809

fix(new_relic sink): Fix `new_relic` sink definition

---

RELEASES.md

chore: Fix links for RELEASES.md

---

src/api/tap.rs

This PR adds unit tests for `vector tap` on components with multiple outputs. Essentially,
- Check that you can tap a non-default output
- Check that you can tap multiple outputs with glob pattern

chore(api): Add unit tests for vector tap on multiple outputs

---

soaks/bin/run_experiment.sh
soaks/common/configs/tcp_blackhole.yaml
soaks/common/terraform/modules/lading_tcp_blackhole/main.tf
soaks/common/terraform/modules/lading_tcp_blackhole/variables.tf
soaks/tests/socket_to_socket_blackhole/README.md
soaks/tests/socket_to_socket_blackhole/terraform/main.tf
soaks/tests/socket_to_socket_blackhole/terraform/variables.tf
soaks/tests/socket_to_socket_blackhole/terraform/vector.toml

A test I wanted to have for #10684.
Depends on #10959.

chore(tests): Add socket -> socket soak test

---

website/content/en/highlights/2021-11-18-csv-enrichment.md

docs(enriching): Fix example in CSV enrichment highlight

---

src/internal_events/common.rs
src/sources/demo_logs.rs
website/cue/reference/components/sources/demo_logs.cue

Add `BytesReceived`, `EventsReceived` and `StreamClosedError`.
closes #10065

enhancement(demo_logs source): comply with component spec

---

lib/vector-core/src/metrics/mod.rs
src/api/schema/metrics/filter.rs
src/kubernetes/state/instrumenting.rs
src/sinks/util/adaptive_concurrency/tests.rs
src/sources/internal_metrics.rs
src/test_util/components.rs
tests/metrics_snapshot.rs
website/cue/reference/components/sources/internal_metrics.cue

Instrument using EventsReceived and StreamClosedError.
closes #10068

enhancement(internal_metrics source): comply with component spec

---

src/sinks/loki/config.rs
src/sinks/loki/service.rs
src/sinks/loki/sink.rs
website/cue/reference/components/sinks/loki.cue

enhancement(sink loki): Add `compress_level` option to compress post into loki
Closes: #9122

feat(loki sink): Add compression to loki sink

---

soaks/bin/analyze_experiment

This is a better name for the statistic.

chore(performance): Rename average to median in soak test output

---

website/content/en/highlights/2022-02-08-disk-buffer-v2-beta.md

chore(highlights website): add highlight article for beta release of disk buffer v2

---

Cargo.lock
Cargo.toml
scripts/integration/docker-compose.aws.yml
src/transforms/aws_ec2_metadata.rs

This reverts commit 47913187db384a1cb7f6250829469832c976336f.
Just curious if this fixes the Windows build.

fix(ci): Try reverting aws_ec2_metadata transform changes

---

soaks/tests/http_pipelines_blackhole/terraform/vector.toml

Updates `http_pipelines_blackhole` soak with the latest config.

chore(performance): update `http_pipelines_blackhole` soak with the latest config

---

website/content/en/highlights/2021-08-25-0-16-upgrade-guide.md

💥  Spotted these the other day...

chore: fix typos + grammar in upgrade guide

---

lib/vector-core/Cargo.toml
lib/vector-core/src/event/log_event.rs
soaks/bin/detect_regressions

chore(performance): try ref counting LogEvent's top-level Value

---

src/internal_events/vector.rs
src/sinks/vector/v2/service.rs
src/sources/vector/v2.rs
website/cue/reference/components/sources/vector.cue

Following the issues #11036 and #9643
Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>

enhancement(vector source): comply with component spec

---

Cargo.lock
lib/vector-common/Cargo.toml
lib/vector-common/src/byte_size_of.rs
src/internal_events/eventstoredb_metrics.rs
src/internal_events/kubernetes_logs.rs
src/sources/aws_ecs_metrics/mod.rs
src/sources/aws_kinesis_firehose/handlers.rs
src/sources/demo_logs.rs
src/sources/dnstap/mod.rs
src/sources/eventstoredb_metrics/mod.rs
src/sources/exec/mod.rs
src/sources/kafka.rs
src/sources/kubernetes_logs/mod.rs

Some issues were noticed by @jszwedko on the previous PRs, this comes to fix them.

fix(sources): update sources to comply with intrumentation

---

Makefile

Fixes build on non-Linux platforms

fix(ci): Use bsd-compatible cp in makefile

---

distribution/install.sh
distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml
website/content/en/releases/0.20.0.md
website/cue/reference/administration/interfaces/kubectl.cue
website/cue/reference/components/sinks/new_relic_logs.cue
website/cue/reference/releases/0.20.0.cue
website/cue/reference/urls.cue
website/cue/reference/versions.cue

chore(releasing): Prepare 0.20.0 release

---

Cargo.lock
Cargo.toml
distribution/install.sh
website/content/en/releases/0.19.3.md
website/cue/reference/releases/0.19.3.cue
website/cue/reference/versions.cue

chore(releasing): Prepare v0.19.3 release

---

src/source_sender/mod.rs
src/sources/datadog/agent/mod.rs
src/sources/internal_metrics.rs
src/sources/util/tcp/mod.rs

chore(performance): move more sources to send_batch

---

website/content/en/highlights/2020-08-31-mpl-2-0-license.md

docs: Typo in 2020-08-31-mpl-2-0-license.md

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

chore: Fix validation errors for Github issue templates

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml

To cover cases not covered by the templates.

chore: enable blank issues

---

website/cue/reference/releases/0.20.0.cue

Also update language to "will be fixed" so that we can publish this
before 0.20.1 is released.

chore(releasing): Add known issue for unit test warnings

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

Just ran ./scripts/generate-manifests.sh

chore(releasing): Update kubernetes manifests

---

lib/value/Cargo.toml
lib/value/src/value/arbitrary.rs
lib/vector-core/Cargo.toml
lib/vector-core/src/event/metric.rs

chore: fix vector-core feature flags

---

src/sources/datadog/agent/integration_tests.rs

Fix broken integration test on master.

chore(tests): fix datadog agent integration tests

---

website/content/en/docs/administration/monitoring.md

docs: update monitoring.md

---

website/content/en/docs/setup/installation/manual/from-source.md

chore(external docs): fix markup

---

website/content/en/docs/setup/quickstart.md

fix(external docs): Fix docker quickstart instructions

---

src/config/builder.rs

chore(schemas): correctly set schemas

---

lib/vector-buffers/src/topology/channel/limited_queue.rs
lib/vector-buffers/src/variants/disk_v1/tests/acknowledgements.rs
lib/vector-buffers/src/variants/disk_v1/tests/mod.rs
lib/vector-buffers/src/variants/disk_v2/tests/basic.rs
lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs
lib/vector-core/src/fanout.rs
src/kubernetes/reflector.rs
src/sources/aws_s3/sqs.rs
src/sources/docker_logs.rs
tests/topology.rs

chore: Simplify trivial `async { X.await }` anti-pattern

---

src/conditions/check_fields.rs
src/conditions/datadog_search.rs
src/conditions/is_metric.rs
src/conditions/mod.rs
src/conditions/not.rs
src/conditions/vrl.rs
src/lib.rs

This commit is a combination of retypist auto-work and small manual
intervention. It is a follow-up to https://github.com/vectordotdev/vector/pull/11538.

chore: Apply deny unreachable_pub to src/conditions

---

website/content/en/guides/level-up/vector-tap-guide.md

docs: small fixes/improvements

---

.github/workflows/soak_comment.yml

chore: Fix soak comment workflow

---

website/cue/reference/components/transforms/throttle.cue

chore: Correct option name in throttle documentation

---

docs/specs/component.md

Based on discussions had as part of https://github.com/vectordotdev/vector/pull/11383

docs: Refine `error_code`

---

soaks/soak.sh

Accidentally broke this in https://github.com/vectordotdev/vector/pull/11474

chore: Fix handling of whether to build image for soak.sh

---

website/layouts/releases/single.html

To encourage users to step through minor releases.

docs: Add note to releases about stepping through versions

---

.github/workflows/soak_comment.yml

chore: Another adjustment to soak comment workflow

---

.github/workflows/soak_comment.yml

chore: Fix artifact lookup in soak comment workflow

---

.github/workflows/soak_infra.yml

Realized this was missing when trying to run the soaks on ARM.

chore: Build soak builder for aarch64

---

.github/workflows/k8s_e2e.yml

chore: remove slim-build from k8s ci

---

soaks/tests/http_pipelines_blackhole_acks/terraform/vector.toml

This was missed when updating http_pipelines_blackhole in #11145

chore: Bring soak http_pipelines_blackhole_acks up-to-date with http_pipelines_blackhole

---

website/content/en/highlights/2021-02-16-reduce-transform-remap-support.md
website/cue/reference/components/transforms/reduce.cue

docs(reduce transform): Fix example type handling

---

src/config/cmd.rs
src/tap/cmd.rs

chore: Clippy allow output where expected

---

src/internal_events/redis.rs

Use the redis error code if set.
Noticed this lack while reviewing the redis source PR, #7096 .

enhancement(redis sink): Improve error codes for send failures

---

.github/workflows/soak_comment.yml

In an attempt to figure out why it is failing.

chore: Add debug statements to soak comment workflow

---

.github/workflows/soak.yml

We have a 16 core, 56GB instance. No details on IOPs. Time to beat is 10
minutes.

chore: Try out custom runners for building soak images

---

src/graph.rs
src/kubernetes/state/delayed_delete.rs
src/lib.rs
src/tcp.rs

This commit further reduces our public interface in the vector crate. The
changes here were done by hand but are mostly mechanically following the
compiler's guidance.

chore: Further minimize the public interface

---

website/content/en/docs/reference/configuration/sources/redis.md
website/cue/reference/components/sources/redis.cue

I neglected to bring the contributor PR for this source up-to-date with
docs changes.

docs(redis source): Fix docs

---

src/transforms/geoip.rs

Right now, when the `geopip` transform is cloned it actually reads the
database from disk again. I think this is bad for a couple of reasons:
* Presmuably this is not a fast process
* You could end up with multiple transforms using different versions of
the database if the file was replaced after Vector starts (ref:
https://github.com/vectordotdev/vector/issues/11817)
* It panics if the file is no longer there
Instead, just wrap the `Reader` in an `Arc`.

chore(geoip transform): Wrap the maxminddb reader in Arc

---

.github/workflows/nightly.yml
.github/workflows/release.yml

chore: move release builds over to custom hosted runners too

---

website/content/en/highlights/2022-03-15-vrl-vm-beta.md

Ref #11686 
This adds a highlight to announce the upcoming VM feature for VRL.

docs(external docs): Added VM highlight.

---

Cargo.lock

chore(deps): Update openssl-src

---

.github/workflows/nightly.yml
.github/workflows/release.yml
scripts/package-deb.sh

To match the conventions:
https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#pkgname
Fixes: #11885

fix(releasing): Fix debian package names

---

src/sinks/datadog_archives.rs

Get rid of the batch settings in the sink config for `datadog_archives` - they shouldn't be exposed to users(internally we should use settings recommended by DD).

fix(datadog_archives sink): remove batch settings from the sink config

---

.github/workflows/nightly.yml

My find/replace on - to _ was greedy.

fix(releasing): Fix nightly deb verify

---

Cargo.lock
Cargo.toml

chore(deps): Upgrade AWS SDK

---

website/content/en/highlights/2022-03-15-vrl-vm-beta.md

Feedback on https://github.com/vectordotdev/vector/pull/11845#pullrequestreview-915427362

chore: Revise VM highlight from feedback

---

src/sinks/datadog/metrics/config.rs
website/cue/reference/components/sinks/datadog_metrics.cue

closes https://github.com/vectordotdev/vector/issues/11734

chore(datadog_metrics sink): add tls options for datadog metrics

---

website/cue/reference/remap/functions/length.cue

docs(vrl): Document what the return value of `length` is

---

src/sources/syslog.rs
src/vector_windows.rs

fix(syslog source): makes the tests run on windows

---

scripts/environment/bootstrap-ubuntu-20.04.sh

chore: Upgrade cue to version 0.4.2

---

website/content/en/docs/setup/going-to-prod/architecting.md

chore(external docs): Remove stray asterisk

---

website/content/en/docs/setup/installation/operating-systems/debian.md

fix(external docs): Remove Helm from debian's list of supported installers

---

Makefile

This helps having all the information needed to fix the feature issues

enhancement(ci): stop failing early for component features check

---

src/internal_events/aws_ec2_metadata.rs
src/internal_events/aws_ecs_metrics.rs
src/internal_events/concat.rs
src/internal_events/json_parser.rs

fix(observability): Remove extra error labels

---

src/sources/journald.rs

Found these oddities while working on another issue and thought I'd pull them out as a clean baseline. These should have exactly zero effect on behavior.

chore(journald source): Clean up a couple pieces of tech debt

---

src/sinks/gcp/mod.rs
website/content/en/highlights/2022-05-03-0-22-0-upgrade-guide.md

fix(gcp_stackdriver_metrics sink)!: flatten the resource.labels to match stackdriver logs

---

.github/workflows/soak.yml

As a consequence of #12185 we are swamping the disk of the stock Github runner
instances with error logs. This means we cannot properly do analysis, which
breaks the whole soak workflow.
Resolves #12206

chore: Run soak analysis on custom runners

---

.github/workflows/nightly.yml
.github/workflows/release.yml

https://github.com/actions/checkout/issues/760
as a result of
https://github.blog/2022-04-12-git-security-vulnerability-announced/

fix(ci): Workaround git permissions issue

---

.github/workflows/release.yml

fix(ci): Add missing run command

---

.github/workflows/release.yml

fix(ci): Fix release artifact upload filename

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

chore(releasing): Update k8s manifests for 0.21.0

---

Tiltfile
src/kubernetes/reflector.rs
src/sources/kubernetes_logs/k8s_paths_provider.rs

- fix(kubernetes_logs source): Handle every arm from reflector's select! and include logging
- Update Tiltfile
Closes #12245

fix(kubernetes_logs source): Handle all outcomes in reflector's select!

---

website/content/en/docs/administration/monitoring.md

docs: cleanup monitoring doc and add example config

---

website/cue/reference/releases/0.21.0.cue

docs: Note performance improvement on v0.21.0 release notes

---

website/cue/reference/releases/0.21.0.cue

docs: Add known issues to 0.21.0 release

---

Cargo.lock
lib/datadog/grok/Cargo.toml
lib/datadog/grok/src/ast.rs
lib/datadog/grok/src/filters/array.rs
lib/datadog/grok/src/grok_filter.rs
lib/datadog/grok/src/matchers/date.rs
lib/datadog/grok/src/parse_grok.rs
lib/datadog/grok/src/parse_grok_pattern.rs
lib/datadog/grok/src/parse_grok_rules.rs
lib/datadog/grok/src/parser.lalrpop
lib/enrichment/Cargo.toml
lib/tracing-limit/Cargo.toml
lib/vector-buffers/Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-vrl-functions/Cargo.toml
lib/vrl/cli/Cargo.toml
lib/vrl/compiler/Cargo.toml
lib/vrl/compiler/fuzz/Cargo.toml
lib/vrl/tests/Cargo.toml
lib/vrl/vrl/Cargo.toml

I gave [`cargo machete`](https://github.com/bnjbvr/cargo-machete) a spin and it did seem to find a few unused dependencies (along with some false positives). Will let CI tell me if there are any uses I missed.

chore(deps): remove some seemingly unused dependencies

---

website/cue/reference/components/sources/internal_metrics.cue

Extracted from https://github.com/vectordotdev/vector/pull/12320 to
cherry-pick into the release branch.

docs(internal_metrics): Fix docs for tags

---

src/aws/auth.rs
src/aws/mod.rs
src/sinks/aws_kinesis_firehose/integration_tests.rs
src/sinks/elasticsearch/common.rs
src/sources/aws_sqs/integration_tests.rs

Fixes: #12314
Relevant: #12313

fix(aws provider): Pass configured region to credentials provider

---

Cargo.lock
Cargo.toml

chore(releasing): Bump next version to v0.21.1

---

src/transforms/pipelines/mod.rs

This follows [a comment](https://github.com/vectordotdev/vector/pull/12305#issuecomment-1104277021) from @jszwedko that noticed that the documentation was not up to date.

fix(pipelines transform): update comment not being up to date

---

scripts/environment/bootstrap-macos-10.sh
scripts/environment/bootstrap-ubuntu-20.04.sh

This is needed for building with the updated tonic.

chore(ci): Add protoc program to Ubuntu and MacOS bootstrap images

---

Cargo.lock
Cargo.toml
lib/codecs/Cargo.toml
lib/prometheus-parser/Cargo.toml
lib/vector-core/Cargo.toml
scripts/environment/bootstrap-macos-10.sh
scripts/environment/bootstrap-ubuntu-20.04.sh
scripts/environment/bootstrap-windows-2019.ps1

These are causing CI regressions with dnstap at least. I will roll up all the pieces and try again separately.

chore(ci): Revert prost/tonic upgrade

---

src/sinks/aws_kinesis_firehose/config.rs
src/sinks/aws_kinesis_firehose/integration_tests.rs
src/sinks/aws_kinesis_firehose/request_builder.rs
src/sinks/aws_kinesis_firehose/tests.rs
src/sinks/util/encoding/mod.rs

enhancement(aws_kinesis_firehose sink, codecs): Integrate `encoding::Encoder` with `aws_kinesis_firehose` sink

---

website/cue/reference/releases/0.21.1.cue

docs: Fix version typo in 0.21.1 release notes

---

website/cue/reference/components/sources/datadog_agent.cue
website/cue/reference/releases/0.21.0.cue

docs(datadog_agent source): Note version support for trace ingestion

---

.github/workflows/test.yml

Was accidentally still using the old filename here

chore(ci): Detect rust-toolchain.toml changes

---

src/sinks/aws_kinesis_streams/config.rs
src/sinks/aws_kinesis_streams/integration_tests.rs
src/sinks/aws_kinesis_streams/request_builder.rs

enhancement(aws_kinesis_streams sink, codecs): Integrate `encoding::Encoder` with `aws_kinesis_streams` sink

---

src/sinks/azure_blob/config.rs
src/sinks/azure_blob/integration_tests.rs
src/sinks/azure_blob/request_builder.rs
src/sinks/azure_blob/test.rs

enhancement(azure_blob sink, codecs): Integrate `encoding::Encoder` with `azure_blob` sink

---

src/sinks/aws_s3/config.rs
src/sinks/aws_s3/sink.rs
src/sinks/aws_s3/tests.rs

enhancement(aws_s3 sink, codecs): Integrate `encoding::Encoder` with `aws_s3` sink

---

scripts/integration/Dockerfile

chore: fix integration test dockerfile by explicitly installing build-essential

---

Makefile

chore: Update Makefile to refer to new dev image

---

lib/vrl/tests/src/main.rs
lib/vrl/tests/tests/rfcs/8381/map_complex_dynamic_object_based_on_conditionals.vrl
rfcs/2021-08-29-8381-vrl-iteration-support.md

Based on a more complex real-world use-case described in https://github.com/vectordotdev/vector/discussions/12387#discussioncomment-2639876.
This example validates that more complex needs are also doable using the initial iteration implementation.

chore(vrl): add additional example to VRL iteration RFC

---

src/transforms/route.rs

performance(route transform): run concurrently

---

Cargo.lock
Cargo.toml

chore(deps): Upgrade AWS SDKs to 0.11.0

---

distribution/rpm/vector.spec
scripts/package-deb.sh

Caught smol things while working on the target spec implementations, kicked them out to a separate PR as they're unrelated

chore: Small fixes on for deb and rpm targets

---

src/aws/mod.rs
src/aws/region.rs
src/internal_events/common.rs
src/sinks/aws_cloudwatch_logs/integration_tests.rs
src/sinks/aws_cloudwatch_metrics.rs
src/sinks/aws_kinesis_firehose/integration_tests.rs
src/sinks/aws_kinesis_firehose/service.rs
src/sinks/aws_kinesis_streams/service.rs
src/sinks/aws_sqs/integration_tests.rs
src/sinks/elasticsearch/common.rs
src/sinks/s3_common/service.rs
src/sources/aws_s3/mod.rs
tests/config.rs

fix(aws provider): Use default region provider if region unspecified

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

chore: Bump k8s manifests to Helm chart 0.10.2 rendering

---

distribution/rpm/vector.spec

From: https://github.com/vectordotdev/vector/pull/12573

feat(centos platform,rhel platform,rpm platform,yum platform): Match deb permissions and groups to rpm

---

lib/codecs/src/encoding/format/json.rs
lib/codecs/src/encoding/format/native.rs
lib/codecs/src/encoding/format/native_json.rs
lib/codecs/src/encoding/format/raw_message.rs
lib/codecs/src/encoding/mod.rs
src/sinks/aws_cloudwatch_logs/config.rs
src/sinks/aws_kinesis_firehose/config.rs
src/sinks/aws_kinesis_streams/config.rs
src/sinks/aws_s3/config.rs
src/sinks/azure_blob/config.rs
src/sinks/http.rs
src/sinks/kafka/config.rs
src/sinks/socket.rs
src/sinks/util/encoding/adapter.rs

enhancement(codecs): Couple sink input types to `Encoder` input types

---

src/codecs/encoder.rs
src/sinks/gcp/cloud_storage.rs

enhancement(gcp_cloud_storage sink, codecs): Integrate `encoding::Encoder` with `gcp` sink

---

src/sinks/papertrail.rs
src/sinks/util/encoding/adapter.rs

enhancement(papertrail sink, codecs): Integrate `encoding::Encoder` with `papertrail` sink

---

src/sinks/redis.rs
src/sinks/util/encoding/adapter.rs

enhancement(redis sink, codecs): Integrate `encoding::Encoder` with `redis` sink

---

src/sinks/nats.rs

enhancement(nats sink, codecs): Integrate `encoding::Encoder` with `nats` sink

---

src/sinks/aws_sqs/config.rs
src/sinks/aws_sqs/integration_tests.rs
src/sinks/aws_sqs/request_builder.rs

enhancement(aws_sqs sink, codecs): Integrate `encoding::Encoder` with `aws_sqs` sink

---

benches/files.rs
src/sinks/file/mod.rs

enhancement(file sink, codecs): Integrate `encoding::Encoder` with `file` sink

---

src/sinks/util/encoding/adapter.rs

chore: Fix silent merge conflict with encoding::adapter::Transformer

---

lib/vrl/tests/tests/rfcs/8381/merge_array_of_objects_to_object.vrl
rfcs/2021-08-29-8381-vrl-iteration-support.md

Added another use-case relayed to us by a customer.

chore(rfc): add additional VRL iteration example

---

Cargo.lock
src/topology/builder.rs
src/topology/mod.rs
src/topology/ready_arrays.rs

performance: try a ReadyArrays

---

lib/lookup/src/lookup_v2/mod.rs

This adds a few lookup V2 improvements. These were originally included in https://github.com/vectordotdev/vector/pull/12218, but the scope of that PR has expanded enough that I want to break this out and get it in earlier.
- Adds a `path!` macro that makes is easy to create paths from the segments
- Adds a `.concat` function that can be used on anything that implements `Path`. This concatenates 2 paths together without memory allocations.
- Fixes some lifetime issues

chore(core): add lookup_v2 improvements

---

lib/vector-core/src/event/log_event.rs

A new `value_mut` function was added that I assume should be doing the exact same as `fields_mut`, but it is different. This is just merging them.

chore(core): merge `value_mut` and `fields_mut`

---

lib/codecs/src/encoding/format/mod.rs
lib/codecs/src/encoding/format/text.rs
lib/codecs/src/encoding/mod.rs
lib/codecs/src/lib.rs
src/codecs/encoder.rs
src/sinks/aws_s3/config.rs
src/sinks/aws_sqs/config.rs
src/sinks/azure_blob/config.rs
src/sinks/azure_blob/test.rs
src/sinks/file/mod.rs
src/sinks/gcp/cloud_storage.rs
src/sinks/http.rs
src/sinks/nats.rs
src/sinks/papertrail.rs
src/sinks/redis.rs
src/sinks/socket.rs
src/sinks/util/encoding/codec.rs
src/sinks/util/encoding/mod.rs

enhancement(codecs): Implement `TextSerializer` and use it as default for `Encoding::Text`

---

lib/codecs/src/encoding/format/logfmt.rs
lib/codecs/src/encoding/format/mod.rs
lib/codecs/src/encoding/mod.rs
lib/codecs/src/lib.rs
src/codecs/encoder.rs
src/sinks/aws_s3/config.rs
src/sinks/azure_blob/config.rs
src/sinks/gcp/cloud_storage.rs
src/sinks/loki/config.rs
src/sinks/loki/event.rs
src/sinks/loki/sink.rs
src/sinks/loki/tests.rs

enhancement(loki sink, codecs): Integrate `encoding::Encoder` with `loki` sink

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

chore: Regenerate manifests based on 0.10.3 of the helm chart

---

.github/workflows/test.yml

Run workflow for all commits on master, for PRs, only run the latest
push.

chore(ci): Revise test.yml concurrency

---

website/content/en/highlights/2022-05-18-vrl-iteration-support.md

[rendered](https://deploy-preview-12795--vector-project.netlify.app/highlights/2022-05-18-vrl-iteration-support/)

docs(external docs): VRL iteration support highlight article

---

lib/vrl/compiler/src/expression/query.rs
lib/vrl/tests/tests/issues/12777_false_positive_for_fallibillity.vrl

fix(vrl): correctly type-def external root path

---

src/gcp.rs

chore(gcp service): Emit debug info when fetching auth tokens

---

lib/codecs/src/encoding/format/raw_message.rs
src/sinks/console/config.rs
src/sinks/console/sink.rs
src/topology/test/doesnt_reload.rs
src/topology/test/reload.rs
src/topology/test/source_finished.rs

enhancement(console sink, codecs): Integrate `encoding::Encoder` with `console` sink

---

lib/vrl/tests/src/docs.rs
website/content/en/highlights/2022-05-24-vrl-encryption.md
website/cue/reference/remap/functions/decrypt.cue
website/cue/reference/remap/functions/encrypt.cue

docs: Add release highlight for VRL encrypt/decrypt functions

---

website/content/en/highlights/2022-03-31-native-event-codecs.md

chore: Revisions to native encoding highlight

---

src/sources/prometheus/scrape.rs

The keyclock prometheus exporter errored when no Accept header was
provided rather than defaulting to `text/plain` as others do.
It seems safest to set this header in case there are other prometheus
exporters that have the same issue.
Closes: #12804

fix(prometheus_scrape source): Set Accept header

---

src/sources/syslog.rs

chore(ci): Allow println in tests

---

lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_nginx_log.rs

Closes https://github.com/vectordotdev/vector/issues/12900

fix(vrl): parse nginx rate limit errors

---

lib/codecs/src/decoding/framing/character_delimited.rs

Signed-off-by: Ryan Russell <git@ryanrussell.org>

chore(CharacterDelimitedDecoder): Fix bytes_processed typo

---

website/content/en/docs/setup/quickstart.md

docs: Fixup Docker quickstart instructions

---

distribution/install.sh
website/cue/reference/administration/interfaces/kubectl.cue

Neglected this when prepping the release.

chore(releasing): Bump installation versions

---

src/config/enterprise.rs

I think this was a merge conflict from cherry-picking release commit.

fix(ci): Add missing import

---

Cargo.lock
Cargo.toml

chore(releasing): Bump development version to v0.23.0

---

lib/tracing-limit/src/lib.rs

It was not correctly rate limiting per `log` function in a VRL program
as it wasn't looking at event fields (where `vrl_position` appeared) and
instead was only looking at span fields.
Closes: #12951

fix(vrl): Fix rate limiting for `log` function

---

soaks/tests/syslog_log2metric_humio_metrics/vector.toml
soaks/tests/syslog_log2metric_splunk_hec_metrics/vector.toml

They were attempting to double parse the input as syslog.
Closes: #12847

chore(soaks): Fix syslog soaks

---

website/cue/reference/remap/functions/parse_logfmt.cue

docs: Remove notice from parse_logfmt intended for encoding

---

src/transforms/tag_cardinality_limit.rs

fix(tag_cardinality_limit transform): Fix deserialization of action

---

website/cue/reference/components/sources/internal_metrics.cue

Prompted by https://github.com/vectordotdev/vector/issues/12958#issuecomment-1146321357

docs(internal_metrics source): Add note about making metrics unique

---

src/sinks/util/buffer/compression.rs

Solves a deserialization issue in `sinks::util::buffer::compression` when the provided value was a map.
Fixes: #12919

fix: Compression config map serialization

---

website/cue/reference/releases/0.21.0.cue

docs: Add known issue for assume role caching to 0.21.0

---

scripts/features
scripts/run-vector

chore(dev): Add script to run vector with minimal features

---

website/content/en/docs/reference/configuration/unit-tests.md

Also, it is equivalent to multi-file example shown just above it.

docs: that is a shell feature

---

website/cue/reference/remap/functions/get_metadata_field.cue
website/cue/reference/remap/functions/remove_metadata_field.cue
website/cue/reference/remap/functions/set_metadata_field.cue

These functions are infallible, so the examples don't compile due to the abort instructions

chore(docs): Fix examples for metadata functions

---

website/content/en/docs/reference/configuration/unit-tests.md

docs: some fixes to unit testing

---

src/sinks/datadog_archives.rs

Related to #9459.
The `encoding::{only_fields, except_fields, timestamp_format}` fields are now exposed and configurable for users.

enhancement(datadog_archives sink): Use `Transformer` in `datadog_archives` sink

---

Cargo.lock
Cargo.toml

chore(deps): Update AWS SDK to 0.13

---

src/sources/host_metrics/mod.rs
src/sources/mod.rs

chore(host_metrics source): Fix default namespace

---

src/sinks/honeycomb.rs

Related to #9459.
The `encoding::{only_fields, except_fields, timestamp_format}` fields are now exposed and configurable for users.

enhancement(honeycomb sink): Use `Transformer` in `honeycomb` sink

---

.cargo/config.toml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/test.yml
scripts/environment/bootstrap-ubuntu-20.04.sh

chore(ci): Fix application of `rustflags`

---

.github/workflows/k8s_e2e.yml
scripts/cross/bootstrap-ubuntu.sh
scripts/environment/bootstrap-ubuntu-20.04.sh

chore(ci): Use the mold wrapper script instead of linker flags

---

lib/vector-common/src/config.rs
lib/vector-common/src/finalization.rs

Found these issues while trying to run `cargo test --package vector-common`

chore(core): Fix `serde` feature flag in `vector-common`

---

scripts/cross/bootstrap-rhel.sh

Unused after https://github.com/vectordotdev/vector/pull/13166

chore: remove unused rhel bootstrap script

---

scripts/environment/bootstrap-ubuntu-20.04.sh

chore(ci): Fail on docs warnings too

---

.github/workflows/release.yml

chore(ci): Fix whitespace for release.yml workflow

---

docs/DEVELOPING.md

Move was made in 6c94aad0f55b8e50b624f50c9d656f26637c2bb9

docs: update file location

---

scripts/check-component-features

Otherwise it's difficult to figure out which check actually failed, if
one does, since the lines are interwoven.

chore(ci): Group and tag component feature check output

---

lib/vrl/compiler/src/expression/op.rs

chore(vrl): clean up op expression

---

Makefile

closes: #13220 
Renamed the variable to `FEATURES` to conform to current [docs](https://vector.dev/docs/setup/installation/manual/from-source/#linux) for building vector from source

fix(dev): Add support for providing features list for make build command

---

src/sinks/prometheus/exporter.rs

Closes #13265
I think this is all we can/need to do here - acking isn't really possible on this sink

enhancement(prometheus_exporter sink): Defer finalization until after processing

---

website/content/en/docs/reference/configuration/_index.md

fix(external docs): fix transform name in yaml and json example config

---

website/cue/reference/components/transforms/reduce.cue

Addresses feedback from https://github.com/vectordotdev/vector/discussions/13310

docs(reduce): Clarify `group_by`

---

website/cue/reference/components/sinks/prometheus_remote_write.cue

docs(prometheus_remote_write sink): Note acknowledgement support as true

---

lib/vrl/cli/src/cmd.rs
lib/vrl/cli/src/lib.rs
lib/vrl/cli/src/repl.rs

Similar to #13321, but for the CLI. The same caveats as mentioned in that PR apply here as well.

chore(vrl): clippy deny+fix on cli

---

lib/vrl/core/src/expression.rs
lib/vrl/core/src/lib.rs
lib/vrl/core/src/target.rs

Similar to #13321, but for the core crate. The same caveats as mentioned in that PR apply here as well.

chore(vrl): clippy deny+fix on core

---

lib/vrl/compiler/src/expression/assignment.rs

The changes from https://github.com/vectordotdev/vector/pull/13317 somehow got around CI and broke master.
This should fix everything.
Mostly just a missing import and some clippy dings.

chore(vrl): fix master

---

lib/vector-core/src/event/mod.rs
src/sources/exec/mod.rs
src/sources/kubernetes_logs/parser/cri.rs
src/sources/util/framestream.rs

chore: remove `Event::from(Bytes)`

---

benches/codecs/encoder.rs
lib/codecs/src/encoding/format/avro.rs
lib/codecs/src/encoding/format/json.rs
lib/codecs/src/encoding/format/logfmt.rs
lib/codecs/src/encoding/format/native_json.rs
lib/vector-core/src/event/mod.rs
src/sinks/util/encoding/mod.rs
src/sources/fluent/mod.rs
src/sources/logstash.rs

chore(core): Remove `Event::from(BTreeMap)` and `Event::from(HashMap)`

---

lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/diagnostic/src/diagnostic.rs
lib/vrl/diagnostic/src/formatter.rs
lib/vrl/diagnostic/src/label.rs
lib/vrl/diagnostic/src/lib.rs
lib/vrl/diagnostic/src/note.rs
lib/vrl/diagnostic/src/severity.rs
lib/vrl/diagnostic/src/span.rs

Similar to #13321, but for the diagnostic crate. The same caveats as mentioned in that PR apply here as well.

chore(vrl): clippy deny+fix on diagnostic

---

website/cue/reference/components/sources/kubernetes_logs.cue

docs(kubernetes_logs source): Update kubernetes api access requirements

---

Cargo.lock
Cargo.toml

chore(deps): Bump AWS SDK to 0.15.0

---

src/sinks/datadog/metrics/request_builder.rs
src/sinks/datadog/metrics/service.rs
src/sinks/datadog/metrics/sink.rs

Closes #13357.
The issue was that the datadog_metrics sink was not using the dd api_key which was being sent over in the event metadata.
Tested with the following configuration:
```toml
[sources.source0]
type = "datadog_agent"
address = "0.0.0.0:8181"
multiple_outputs = true
store_api_key = true
[sinks.sink0]
inputs = [ "source0.metrics" ]
type = "datadog_metrics"
default_api_key=""
```
Log snippet showing successful request:
```
2022-07-01T01:15:15.788926Z TRACE sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}: vector_core::stream::driver: Submitting service request. in_flight_requests=0 request_id=0
2022-07-01T01:15:15.789679Z DEBUG sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics …
```

fix(datadog_metrics sink): fix datadog api key pass-through for metrics

---

website/cue/reference/components/sinks/datadog.cue
website/cue/reference/components/sinks/datadog_events.cue
website/cue/reference/components/sinks/datadog_logs.cue
website/cue/reference/components/sinks/datadog_metrics.cue
website/cue/reference/components/sinks/datadog_traces.cue

docs(datadog provider): Correct the documentatation of API key handling

---

lib/vector-common/Cargo.toml

These tests work but can't be built by themselves. Tiny patch.

chore(tests): Fix `cargo test --package vector_common`

---

lib/vrl/compiler/src/expression/predicate.rs

Using optimizations, we've recently added to the `block` expression as well.
Initially, I wanted to swap the `Vec<Expr>` with `Block` to get those optimizations for free, but that caused scoping issues, and while that can be resolved, I wanted to keep this PR small.

chore(vrl): improve performance of `if-predicate` expression

---

website/content/en/docs/about/under-the-hood/architecture/concurrency-model.md

In response to https://github.com/vectordotdev/vector/issues/3899#issuecomment-1158003382

docs: Update concurrency documentation

---

.github/workflows/test.yml
Makefile
deny.toml
scripts/check-deny.sh

Adds a Makefile target for running cargo deny to check crate dependencies for advisories.
Included in make check-all.

enhancement(dev): add makefile target check-deny

---

website/cue/reference/components.cue

Clarifying the certificate validations- this was determined by calling :
https://docs.rs/openssl/latest/openssl/ssl/struct.SslContextBuilder.html#method.verify_param
within https://cs.github.com/vectordotdev/vector/blob/dc26ec3cc13f4fbe94e0b5585a58d0529c4f9d8b/src/tls/settings.rs#L236
and displaying the result:
```
2022-07-05T21:46:55.677125Z DEBUG vector::tls::settings: Fetching system root certs.
[src/tls/settings.rs:280] flags = CB_ISSUER_CHECK
```

chore(external docs): clarify TLS cert validations

---

src/conditions/is_trace.rs
src/conditions/mod.rs
src/transforms/pipelines/mod.rs

Closes the first item of #11648.

enhancement(pipelines transform): add explicit support for traces

---

distribution/install.sh
website/content/en/highlights/2022-05-03-0-22-0-upgrade-guide.md
website/content/en/highlights/2022-07-07-0-23-0-upgrade-guide.md
website/content/en/releases/0.23.0.md
website/cue/reference/administration/interfaces/kubectl.cue
website/cue/reference/releases/0.23.0.cue
website/cue/reference/versions.cue

chore(releasing): Prepare v0.23.0 release

---

website/cue/reference/releases/0.23.0.cue

Signed-off-by: Jesse Szwedko <vector@datadoghq.com>

docs(gcp_pubsub source): Correct changelog entry

---

website/cue/reference/components/sources/datadog_agent.cue

docs: Fix typos in datadog_agent docs

---

website/content/en/guides/level-up/troubleshooting.md

Signed-off-by: Jesse Szwedko <vector@datadoghq.com>

docs: correct links to open new issues on troubleshooting page

---

website/content/en/docs/setup/going-to-prod/arch/aggregator.md

This hasn't been implemented yet

docs: Remove note about external buffers

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

chore(releasing): Regenerate k8s manifests for 0.23.0

---

website/content/en/docs/reference/configuration/_index.md
website/content/en/guides/level-up/managing-complex-configs.md
website/content/en/guides/level-up/managing-schemas.md
website/cue/reference/cli.cue
website/cue/reference/components.cue
website/cue/reference/components/sources/aws_s3.cue
website/cue/reference/components/transforms/reduce.cue
website/cue/reference/configuration.cue
website/cue/reference/urls.cue

Extracted from f262fea3c
Noticed via https://github.com/vectordotdev/vector/discussions/13520#discussioncomment-3138619

docs(releasing): Backport changes to docs for transform removal

---

website/content/en/highlights/2022-03-31-native-event-codecs.md

Small fix that I noticed while working on #13518.

docs: Fix example in native codecs highlight

---

scripts/environment/prepare.sh
scripts/integration/Dockerfile
scripts/integration/docker-compose.axiom.yml

nextest has a regression, so bumping to latest version.
CI failure:
https://github.com/vectordotdev/vector/runs/7341680171?check_suite_focus=true#step:5:688
nextest issue:
https://github.com/nextest-rs/nextest/issues/356

chore(tests): upgrade nextest version to 0.9.25

---

website/cue/reference/components/transforms/throttle.cue

docs(throttle transform): Fix key_field docs to mention templating

---

src/sinks/elasticsearch/common.rs

Closes: #13450
config option `request.headers` was not being applied in the healthcheck

fix(elasticsearch sink): config http request headers in healthcheck

---

docs/REVIEWING.md

Adding new checklist items and expanding on others.

chore: Brushing off REVIEWING.md

---

docs/USER_EXPERIENCE_DESIGN.md

docs(dev): Add UX note about not requiring manual intervention

---

src/config/watcher.rs

We've seen this test be flakier lately.
Rather than read all of `/tmp`, create a temporary directory to scope
the configuration watching to. Just a hunch that maybe using `/tmp` is
causing it to take a long time to read all of the files.
Also added some more debug statements.

chore(tests): Try to fix file_directory_update test

---

docs/REVIEWING.md

chore(docs): Update link to Security guide

---

lib/vrl/stdlib/src/flatten.rs
website/cue/reference/remap/functions/flatten.cue

Introduces an optional separator parameter to the `flatten` function
Closes https://github.com/vectordotdev/vector/issues/13617

enhancement(flatten): Introduce an optional separator parameter

---

Cargo.lock
Cargo.toml
lib/vector-buffers/Cargo.toml
lib/vector-buffers/benches/common.rs
lib/vector-common/Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-core/src/event/metric/mod.rs
lib/vector-core/src/metrics/mod.rs
lib/vector-core/src/metrics/recorder.rs
lib/vector-core/src/metrics/storage.rs

This does not address any potential performance issues. I want to see if anything shows up on the soak tests before targeting any performance related changes.
Closes #13625

chore(internal_metrics source): Upgrade `metrics` crates

---

Cargo.lock
Cargo.toml
lib/vector-buffers/Cargo.toml
lib/vector-common/Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-core/src/metrics/recorder.rs

chore(dependencies): Upgrade metrics crates

---

rust-toolchain.toml
src/sources/aws_kinesis_firehose/mod.rs
src/sources/datadog/agent/tests.rs
src/sources/fluent/mod.rs
src/sources/heroku_logs.rs
src/sources/internal_logs.rs
src/sources/logstash.rs

chore(deps): Upgrade Rust to 1.62.1

---

Cargo.lock
src/transforms/sample.rs
website/content/en/docs/reference/configuration/transforms/sample.md
website/cue/reference/components/transforms/sample.cue

enhancement(sample transform): Allow for traces as inputs and outputs

---

.github/workflows/publish.yml
.github/workflows/test.yml

chore: Try configuring release build to use `git` to fetch

---

src/sources/datadog_agent/mod.rs

enhancement(datadog_agent source): Log the address for the datadog_agent http server

---

docs/DEVELOPING.md

chore(docs): update DEVELOPING.md to reference correct integration test github workflow file.

---

website/content/en/docs/reference/configuration/sinks/gcp_chronicle.md
website/cue/reference/components/sinks/gcp_chronicle_unstructured.cue

docs(gcp_chronicle_unstructured sink): Publish docs

---

src/sources/mongodb_metrics/types.rs

This PR is the further investigation of the previous one (#13656).
Signed-off-by: KernelErr <me@lirui.tech>

fix(mongodb_metrics source): Fix data types of metrics

---

src/sources/mongodb_metrics/types.rs

Reverts vectordotdev/vector#13729

fix(mongodb_metrics source): (revert) Fix data types of metrics

---

website/cue/reference/components/sources/internal_metrics.cue

chore(observability): Indicate that `processing_errors_total` is deprecated

---

distribution/install.sh

Fixes [this](https://github.com/vectordotdev/vector/pull/13613#issuecomment-1202003134) issue

Resolve installer script issues

---

website/static/img/roles/aggregator.svg

On https://vector.dev/docs/setup/deployment/roles/
Fixes: #13815

docs: Fix description for aggregator role

---

.github/workflows/publish.yml
website/content/en/docs/setup/installation/manual/from-source.md

I don't see this environment variable being read anywhere.

chore(releasing): Remove PASS_FEATURES

---

deny.toml

Closes: #6225
Closes: #5582
Closes: #5583
Closes: #5585
Closes: #5583

chore(deps): Remove some stale cargo-deny entries

---

Cargo.lock
Cargo.toml
src/sources/docker_logs.rs

Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>
fix #13861

fix(docker_logs source): Fix panic after bump bollard

---

Cargo.lock
Cargo.toml

chore(deps): Upgrade AWS smithy crates to 0.47

---

Cargo.lock
Cargo.toml
distribution/install.sh
lib/datadog/grok/src/parse_grok.rs
lib/value/Cargo.toml
lib/vector-core/Cargo.toml
lib/vrl/stdlib/src/parse_groks.rs
src/api/schema/relay.rs
src/codecs/decoding/decoder.rs
src/config/builder.rs
src/config/enterprise.rs
src/config/mod.rs
src/sinks/elasticsearch/sink.rs
src/sinks/elasticsearch/tests.rs
website/content/en/releases/0.23.1.md
website/cue/reference/releases/0.22.0.cue
website/cue/reference/releases/0.23.0.cue
website/cue/reference/releases/0.23.1.cue
website/cue/reference/versions.cue

Includes issues from: https://github.com/vectordotdev/vector/milestone/92
TODO:

chore(releasing): Prepare v0.23.1

---

scripts/version.sh

chore(releasing): Verify tag matches version for releases

---

soaks/bin/soak_one.sh

Improve the soak test debugging experience by adding stdout & stderr as collapsed blocks in Actions logs.

enhancement(soak tests): Emit vector stdout & stderr

---

website/cue/reference/releases/0.23.3.cue

docs(releasing): Clarify why versions were skipped

---

lib/vector-common/src/internal_event/bytes_sent.rs
lib/vector-common/src/internal_event/mod.rs
lib/vector-core/src/stream/driver.rs
scripts/check-events
src/internal_events/mod.rs
src/sinks/azure_common/service.rs
src/sinks/console/sink.rs
src/sinks/datadog/events/service.rs
src/sinks/datadog/logs/service.rs
src/sinks/datadog/metrics/service.rs
src/sinks/datadog/traces/service.rs
src/sinks/gcs_common/service.rs
src/sinks/kafka/service.rs
src/sinks/loki/service.rs
src/sinks/mod.rs
src/sinks/nats.rs
src/sinks/new_relic/service.rs
src/sinks/prometheus/exporter.rs
src/sinks/pulsar.rs
src/sinks/redis.rs
src/sinks/socket.rs
src/sinks/statsd.rs
src/sinks/util/udp.rs
src/sinks/websocket/sink.rs

Reverts vectordotdev/vector#13905
Causing integration test failures: https://github.com/vectordotdev/vector/runs/7777357604?check_suite_focus=true

enhancement(observability): (revert) Add initial registered internal event implementation

---

website/cue/reference/components/sources/opentelemetry.cue

Event wasn't actually implemented in this source, just copied from the vector source code

chore(opentelemetry source): remove unimplemented protobuf_decode metric

---

website/content/en/docs/about/under-the-hood/guarantees.md

docs: Remove duplicate sentence in guarantees.md

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

chore: Regenerate Kubernetes manifests

---

src/internal_events/common.rs

Affects a number of components, but part of #14003

feat(observability): Add intentional and reason for StreamClosedError

---

website/content/en/docs/setup/installation/platforms/docker.md

Also use default API port.
Fixes: #14007

docs(docker platform): Update docker setup docs to include example config

---

website/content/en/docs/about/concepts.md

Also made overlong lines not need horizontal scrolling,
for non-wrapping editor setups.

docs: add missing comma

---

website/content/en/docs/setup/installation/platforms/docker.md

docs: Tweak docker docs for better UX

---

src/sources/apache_metrics/mod.rs
website/cue/reference/components/sources/apache_metrics.cue

Closes: #14053.
part of https://github.com/vectordotdev/vector/issues/13995.

feat(observability): update component_discarded_events_total for `apache_metrics` source

---

Cargo.lock
Cargo.toml
lib/vrl/stdlib/Cargo.toml

No longer using it after 97ccda4bebd75e2a9b567071a1eb77c537b0a6b9

chore(deps): Remove `grok` crate

---

docs/specs/instrumentation.md

[rendered](https://github.com/vectordotdev/vector/blob/prognant/instrumentation-specs-minor-adjustement/docs/specs/instrumentation.md)

docs(internal docs): settle a minor ambiguity

---

website/content/en/highlights/2022-05-24-vrl-encryption.md

docs: Typo in VRL encryption function announcement

---

website/cue/reference/components/sources/internal_metrics.cue

docs(internal_metrics source): Typo in component_received_events_total

---

src/internal_events/codecs.rs
src/internal_events/common.rs
src/internal_events/template.rs

Small follow-up to https://github.com/vectordotdev/vector/pull/14021.

chore: Use booleans in `intentional` tag

---

docs/specs/instrumentation.md

Into a separate section to make them clearer.

chore(dev): Update instrumentation spec to pull up namespaces

---

src/internal_events/tag_cardinality_limit.rs

Signed-off-by: Eric Wang <wrqatw@gmail.com>

fix(buffers): minor fix debug key

---

lib/lookup/src/field.rs
lib/lookup/src/path.lalrpop
lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/tests/tests/issues/13461/1.vrl
lib/vrl/tests/tests/issues/13461/2.vrl
lib/vrl/tests/tests/issues/13461/3.vrl
lib/vrl/tests/tests/issues/13461/4.vrl
lib/vrl/tests/tests/issues/13461/5.vrl
lib/vrl/tests/tests/issues/13461/6.vrl

fix(vrl): update unquoted allowed-characters

---

website/content/en/highlights/2022-08-16-0-24-0-upgrade-guide.md

docs: Fix link in 0.24.0 upgrade guide

---

distribution/kubernetes/vector-agent/README.md
distribution/kubernetes/vector-agent/configmap.yaml
distribution/kubernetes/vector-agent/daemonset.yaml
distribution/kubernetes/vector-agent/rbac.yaml
distribution/kubernetes/vector-agent/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/README.md
distribution/kubernetes/vector-aggregator/configmap.yaml
distribution/kubernetes/vector-aggregator/service-headless.yaml
distribution/kubernetes/vector-aggregator/service.yaml
distribution/kubernetes/vector-aggregator/serviceaccount.yaml
distribution/kubernetes/vector-aggregator/statefulset.yaml
distribution/kubernetes/vector-stateless-aggregator/README.md
distribution/kubernetes/vector-stateless-aggregator/configmap.yaml
distribution/kubernetes/vector-stateless-aggregator/deployment.yaml
distribution/kubernetes/vector-stateless-aggregator/service-headless.yaml
distribution/kubernetes/vector-stateless-aggregator/service.yaml
distribution/kubernetes/vector-stateless-aggregator/serviceaccount.yaml

chore: Bump k8s manifests to v0.16.0 of the Helm chart

---

src/internal_events/mod.rs
src/internal_events/pulsar.rs
src/sinks/pulsar.rs
website/cue/reference/components/sinks/pulsar.cue

enhancement(pulsar sink): fix missing drop count

---

website/cue/reference/releases/0.24.0.cue

am not sure if this is what was meant

docs: Remove confusion

---

src/internal_events/pulsar.rs
src/sinks/pulsar.rs

fix(pulsar sink): adhere to new DroppedEvents checks / instrumentation spec

---

src/sources/internal_metrics.rs
website/content/en/highlights/2022-10-04-0-25-0-upgrade-guide.md
website/cue/reference/components/sources/internal_metrics.cue

enhancement(internal_metrics)!: Default to setting the host tag

---

src/sinks/datadog/traces/integration_tests.rs
src/sinks/datadog/traces/tests.rs

Closes: #14298
Epic: https://github.com/vectordotdev/vector/issues/13995

enhancement(datadog_traces sink): Add compliance test helpers.

---

src/config/unit_test/mod.rs
src/config/unit_test/unit_test_components.rs
src/sources/mod.rs
src/transforms/dedupe.rs
src/transforms/mod.rs

chore(dedupe transform): Test compliance to instrumentation spec in `dedupe` transform

---

lib/vector-common/src/internal_event/events_received.rs
src/sources/nats.rs

chore(nats source): Update to newer EventsReceived metric

---

src/internal_events/nginx_metrics.rs

Closes #14200
Other errors are handled by shared code, or prior to metrics being created in Vector.

enhancement(nginx_metrics source): Rate limit internal errors

---

website/content/en/docs/setup/going-to-prod/_index.md
website/content/en/docs/setup/going-to-prod/arch/agent.md
website/content/en/docs/setup/going-to-prod/arch/aggregator.md
website/content/en/docs/setup/going-to-prod/arch/unified.md
website/content/en/docs/setup/going-to-prod/rollout.md

Small PR to updated Observability Pipelines links and deprecate old support URLs.

Update website copy to remove deprecated support links

---

website/cue/reference/components/sources/aws_sqs.cue

chore: Fix formatting for requirement blurb

---

website/content/en/docs/reference/configuration/_index.md

docs: wilcards -> wildcards

---

Cargo.lock
Cargo.toml
distribution/install.sh
lib/vector-config/src/stdlib.rs
lib/vector-core/src/config/global_options.rs
lib/vector-core/src/event/metric/mod.rs
lib/vector-core/src/metrics/mod.rs
lib/vector-core/src/metrics/recorder.rs
src/sinks/http.rs
src/sources/aws_sqs/source.rs
src/sources/host_metrics/cpu.rs
src/topology/mod.rs
website/content/en/releases/0.24.1.md
website/cue/reference.cue
website/cue/reference/components/sinks/http.cue
website/cue/reference/components/sources/host_metrics.cue
website/cue/reference/configuration.cue
website/cue/reference/releases/0.24.0.cue
website/cue/reference/releases/0.24.1.cue
website/cue/reference/versions.cue

chore(releasing): Prepare 0.24.1

---

RELEASES.md

chore: Fix calendar link in RELEASES.md

---

website/cue/reference/releases/0.24.1.cue

docs(releasing): Remove duplicate release bullet

---

docs/DEVELOPING.md

chore(internal docs) mention GNU coreutils dependency 

---

src/sources/aws_s3/mod.rs
src/sources/aws_s3/sqs.rs

Closes #14195
- chore(aws_s3 source): Fix typo static name
- chore(aws_s3 source): Update comments and configurable description
- chore(aws_s3 source): Use SOURCE_TAGS const in tests
- enhancement(aws_s3 source): increment dropped events on StreamClosedError

enhancement(aws_s3 source): Adhere to errors spec

---

src/transforms/aggregate.rs

chore(aggregate transform): Test compliance to instrumentation spec in `aggregate` transform

---

src/transforms/filter.rs

chore(filter transform): Test compliance to instrumentation spec in `filter` transform

---

src/internal_events/mod.rs
src/internal_events/redis.rs
src/sinks/redis.rs

Closes:  #14141
Epic: https://github.com/vectordotdev/vector/issues/13995
- Added comments where common code is handling Errors
- Removed double emission in Error path
- Added compliance test helpers to remaining tests/int tests

enhancement(redis sink): Adhere to instrumentation spec

---

src/sinks/papertrail.rs

Now with 100% less pushing directly to `master`!

chore(papertrail sink): Remove old inventory::submit for SinkDescription

---

src/transforms/geoip.rs

chore(geoip transform): Test compliance to instrumentation spec in `geoip` transform

---

lib/vector-core/src/tls/settings.rs
website/cue/reference/components.cue

- protolols -> protocols
Tested:
- No

docs(alpn): Fix misspelling

---

lib/k8s-e2e-tests/src/lib.rs
src/app.rs
src/internal_events/codecs.rs
src/internal_events/common.rs
src/internal_events/datadog_metrics.rs
src/internal_events/datadog_traces.rs
src/internal_events/dnstap.rs
src/internal_events/influxdb.rs
src/internal_events/tcp.rs
src/trace.rs

fix(vector): internal log rates init usage fix

---

website/cue/reference/remap/functions/merge.cue

docs: Fix merge arg types

---

src/sinks/aws_kinesis_streams/config.rs
src/sinks/aws_kinesis_streams/integration_tests.rs
src/sinks/aws_kinesis_streams/request_builder.rs
src/sinks/aws_kinesis_streams/service.rs
src/sinks/aws_kinesis_streams/sink.rs

chore(aws_kinesis_streams sink): File cleanup and use SinkRequestBuildError

---

Makefile
docs/ARCHITECTURE.md
docs/CONTRIBUTING.md
docs/DEPRECATION.md
docs/DEVELOPING.md
docs/DOCUMENTING.md
docs/REVIEWING.md
docs/USER_EXPERIENCE_DESIGN.md
docs/specs/buffer.md
docs/specs/component.md
docs/specs/configuration.md
docs/specs/instrumentation.md
docs/specs/target.md

chore: Cleaning up markdown files and typos

---

src/sinks/aws_sqs/config.rs
src/sinks/aws_sqs/integration_tests.rs
src/sinks/aws_sqs/mod.rs
src/sinks/aws_sqs/request_builder.rs
src/sinks/aws_sqs/retry.rs
src/sinks/aws_sqs/service.rs
src/sinks/aws_sqs/sink.rs

enhancement(aws_sqs sink): File cleanup and use SinkRequestBuildError

---

website/content/en/docs/reference/configuration/sources/http_scrape.md
website/cue/reference/components/sources/http_scrape.cue

https://deploy-preview-14517--vector-project.netlify.app/docs/reference/configuration/sources/http_scrape

docs(http_scrape source): Fix title and alias

---

website/content/en/docs/administration/validating.md

Fixing typos in documentation

---

website/cue/reference/configuration.cue

docs(observability): Clarify behavior of expiring internal counters

---

website/content/en/docs/administration/management.md

Seems to be an incomplete duplicate of the section right above it.
Closes: #14001

docs(reload): Remove hanging paragraph about config watching

---

Cargo.lock
Cargo.toml

chore(deps): Upgrade all AWS crates

---

.github/workflows/publish.yml

Currently breaking the nightly build after #13766

chore(releasing): Install protoc during OSX release

---

scripts/environment/install-protoc.sh

chore: Handle installing protoc on arm and x86

---

src/sources/aws_s3/sqs.rs

https://github.com/vectordotdev/vector/discussions/14047
Vector currently fails to process test events created by S3. These are benign events that can be ignored to prevent serde parser failures.

fix(aws_s3 source): Handle s3:TestEvent and drop it

---

src/sinks/gcs_common/service.rs
src/sinks/gcs_common/sink.rs

Ref: #14633 
This updates the emitted errors, in particular emitting a `SinkRequestBuildError` for gcs shared components.

fix(observability): update gcs common emitted errors.

---

website/layouts/partials/data.html

feat(template website): Don't render required tag on telemetry tags
