vectordotdev/vector

Cargo.lock
Cargo.toml
src/transforms/aws_ec2_metadata.rs

This required aliasing `Bytes` in the `aws_ec2_metadata` transform
because `Bytes` no longer saisfies `ShallowCopy` (and the `bytes`
feature of `evmap` was removed) as of
https://github.com/jonhoo/evmap/commit/416ccef

chore(deps): Unpin evmap from fork

---

website/assets/css/style.css
website/layouts/partials/social-buttons.html

Testing:
Github icon in the header should be gray on hover in both dark and light modes.   Tested in Chrome, FF & Safari.

fix(css website): github icon should have hover effect in dark mode.

---

lib/vector-core/src/mapping/parser/mod.rs

Rename from `unexpected_parser_sytax` to `unexpected_parser_syntax`

chore: Rename `unexpected_parser_sytax` to `unexpected_parser_syntax`

---

Cargo.lock
lib/vector-core/Cargo.toml
lib/vector-core/src/byte_size_of.rs
lib/vector-core/src/lib.rs
lib/vector-core/src/stream.rs
lib/vector-core/src/stream/batcher.rs
lib/vector-core/src/time.rs
lib/vector-core/src/transform/config.rs

This commit is an extract of the work being done in #8825. The goal
with that work is to change the datadog logs sink to be done purely in
terms of `Stream`, with the goal of improving all our sinks along
similar lines. Most of the code in that PR is hampered by the lack of
streaming batching, whence this commit.
I've introduces a new type into vector-core: `Batcher`. This builds on
the `Partitioner` notion introduced in #8914 to divvy up incoming
items into a key space and ensure that blobs of items are issued when
they consume too much memory, if the blob is full or if the key has
sat for too long unflushed. This commit includes proptest property
tests as opposed to quickcheck with the hope that one day we'll be
able to use [propverify](https://github.com/project-oak/rust-verification-to …

chore: Introduce a `Batcher` stream processor

---

src/config/loading.rs

Closes #8987
```shell
~/C/g/t/vector on  master [!] is 📦 v0.17.0 via 🦀 v1.54.0
❯ target/debug/vector -c /tmp/test.yaml
Sep 01 12:31:36.917  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info" enable_datadog_tracing=false
Sep 01 12:31:36.920  INFO vector::app: Loading configs. paths=["/tmp/test.yaml"]
Sep 01 12:31:36.920 ERROR vector::config::loading: Error opening config file. error=Permission denied (os error 13) path="/tmp/test.yaml"
Sep 01 12:31:36.920 ERROR vector::cli: Configuration error. error=Config file not found in path: "/tmp/test.yaml".
~/C/g/t/vector on  master [!] is 📦 v0.17.0 via 🦀 v1.54.0
❯ target/debug/vector -C /tmp/
Sep 01 …
```

enhancement(config): Add path to error events during config load

---

.gitignore
src/sinks/blackhole.rs
src/topology/test/transient_state.rs
tests/api.rs
tests/cli.rs
tests/shutdown.rs
website/content/en/highlights/2021-10-05-0-17-upgrade-guide.md
website/cue/reference/components/sinks/blackhole.cue

This PR changes the behavior of the `blackhole` sink so that it prints out its statistics on a configurable interval (defaults to `10s`) instead of printing every N events.  This provides a more even reporting cadence regardless of the load.
We've also slightly tweaked the sink so that it uses `StreamExt::ready_chunks` instead of `chunks`, which ensures responsiveness when the input stream is slow.

enhancement(blackhole sink)!: print on interval instead of after X events

---

src/sources/splunk_hec.rs

Fixes: #8459
This swaps out our custom stream reading in-lieu of just using
`serde_json::StreamDeserializer` which seems to handle skipping
whitespace just fine.

fix(splunk_hec source): Do not blow up on trailing whitespace

---

Makefile

Unfortunately, the Humio integration tests haven't been run due to overly restrictive filters in place. Technically, the new filter is too loose, but we currently do so in the other integration tests as well.
The tests are failing locally for me, I'm still investigating how to fix them.

chore(tests): Reenable Humio integration tests

---

Cargo.lock
lib/vrl/compiler/src/value.rs
lib/vrl/compiler/src/value/regex.rs
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/unique.rs
website/cue/reference/remap/functions/unique.cue

Leveraging `indexmap::IndexSet` since we are already using that crate in
places. This ensures the unique elements are returned in order and does
not require the elements to have been sorted.

enhancement(vrl): Add function for retrieving unique elements from an array

---

website/cue/reference/components/sinks/elasticsearch.cue
website/layouts/partials/data.html

Fixes #9003 and #9030
It's nothing fancy but it presents the info we need to present. Example:
https://deploy-preview-9032--vector-project.netlify.app/docs/reference/configuration/sinks/elasticsearch/#index

fix(external docs): Add template note to config params

---

website/layouts/partials/data.html

PR #9032 fixed the missing config param examples but in such a way that it presented the example *as an array*, whereas what's needed is separately rendered examples for each.
As an example, [this config](https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#index)'s examples are rendered as an array of strings, whereas each example string needs its own rendering. The fixed version of the same param:
https://deploy-preview-9033--vector-project.netlify.app/docs/reference/configuration/sinks/elasticsearch/#index

fix(external docs): Fix rendering of config param examples

---

Cargo.lock
lib/vector-core/Cargo.toml
lib/vector-core/proptest-regressions/stream/batcher.txt
lib/vector-core/src/partition.rs
lib/vector-core/src/stream/batcher.rs
lib/vector-core/src/time.rs

This PR primarily focuses on changing `vector_core::stream::batcher::Batcher` from a "flush all batches at the same time" to an a per-batch timeout model.  Instead of flushing all batches at the same exact time, which can lead to bursts of activity that apply backpressure to other components in a pipeline, we apply timeouts at the batch level.  This means that the timeout for a batch starts when the batch is created.  As batches are typically constructed due to partitioning of the output -- partitioning based on the value of a field in the event, for example -- they tend to be spread out over time.
Overall, this leads to per-batch timeouts being important for spreading out the load over time, and providing _consistent_ throughput/latency to pipelines.
Additionally, this PR also removes …

chore(architecture): add per-batch timeout support to Batcher

---

website/cue/reference/components.cue
website/cue/reference/components/sinks.cue
website/cue/reference/components/transforms.cue

This only applies to transforms and sinks.

docs(sources): Remove utilization metric from sources

---

website/cue/reference/components/sinks.cue

A user was confused about `encoding` being required on the
`datadog_logs` sink even though none of the nested fields were required.
https://vector.dev/docs/reference/configuration/sinks/datadog_logs/#encoding
I think a better solution to this would probably be to not require
`required` to be defined on options that are `object`s given that it is
the subfields that are required or not.

docs(sinks): Mark `encoding` as optional

---

website/cue/reference.cue
website/cue/reference/components/sources/socket.cue

The `unix` option was deprecated and replaced with these.
Closes: #9028

docs(socket source): Fix references to `unix` to be to `unix_datagram` and `unix_stream`

---

src/config/compiler.rs
src/config/validation.rs
tests/config.rs

Closes #8920
This also cleans up a small error message regression from when we
implemented full input glob patterns. Instead of saying that an input
doesn't match any components, we would say that the component had no
inputs, which isn't quite right.

fix(config): error on duplicate inputs

---

website/cue/reference/components.cue
website/cue/reference/components/sources/aws_kinesis_firehose.cue
website/cue/reference/components/transforms/aggregate.cue
website/layouts/partials/data.html

This PR fixes a handful of rendering issues in the component docs.

fix(external docs): Fix component docs rendering nits

---

.github/workflows/nightly.yml
.github/workflows/release.yml

We seem to be hitting memory pressure on GH's runners.

chore(releasing): Run Windows builds on our CI runners

---

website/content/en/docs/reference/vrl/_index.md
website/cue/reference/remap/concepts/boolean_expressions.cue
website/layouts/partials/data.html

This fixes another oversight and provides a syntax badge in top-level configs plus some doc links for Remap programs/conditions.

enhancement(external docs): Add syntax links for VRL fields

---

src/codecs/framers/character_delimited.rs
src/codecs/framers/mod.rs
src/codecs/framers/newline_delimited.rs
src/codecs/mod.rs

chore(codecs): Implement `newline_delimited` framing

---

src/codecs/framers/bytes.rs
src/codecs/framers/mod.rs

chore(codecs): Implement `bytes` framing

---

src/sinks/aws_kinesis_firehose.rs

The Firehose API has a limit of 4 MiB or 500 events per request.
Previously we were not enforcing this though so users would see failed
API requests instead.

enhancement(aws_kinesis_firehose sink): Check batch configuration limits

---

Cargo.lock
Cargo.toml
lib/file-source/Cargo.toml
lib/prometheus-parser/Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-core/buffers/src/test/mod.rs
lib/vector-core/src/stream/batcher.rs
lib/vrl/stdlib/Cargo.toml

This did require pinning indexmap due to a circular dependency issue:
https://github.com/timberio/vector/pull/7120

chore(deps): `cargo upgrade --aggressive`

---

Cargo.lock
Cargo.toml
benches/metrics_bench_util/mod.rs
lib/file-source/src/file_server.rs
lib/file-source/src/fingerprinter.rs
src/app.rs
src/cli.rs
src/sources/internal_logs.rs
src/test_util/mod.rs
src/trace.rs
website/cue/reference/cli.cue

This reverts commit 37e06de830377f1ded73d70014f099ae487ad6da (#7929).

chore(observability): revert internal tracing proof of concept

---

src/sinks/aws_kinesis_firehose.rs
src/sinks/elasticsearch/mod.rs

This was changed to not collect and use Iter#any as part of the Rust
1.55 upgrade, but this turned out to be not correct since `input` is
used in a loop.

fix(ci): Put collects back

---

.github/workflows/integration-test.yml

Similar to the k8s e2e tests, this addes another label that
conditionally enables integration tests to make them easier to run on
PRs.
To aid this, I refactored the workflow into a matrix workflow which I'd
been planning on doing anyway.

chore(ci): Run integration tests on PRs with label

---

src/sinks/aws_s3/config.rs
src/sinks/aws_s3/sink.rs

These were in the wrong order so the number of bytes was being used as
the number of events and vice-versa.

fix(aws_s3 sink): Fix batching parameters

---

src/config/loading.rs

Closes #8994 
This checks the config file has a valid extension (toml, yaml, json) before attempting to load it.

fix(config): only load valid config files

---

.github/workflows/nightly.yml

Since we moved these to self-hosted runners, wix may already be
installed so we should overwrite it.
I think this should be moved to the image build, but this should fix it
for now.
Failure:
```
Run mkdir -p /c/wix
Archive:  wix-binaries.zip
replace x86/burn.exe? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Error: Process completed with exit code 1.
```
https://github.com/timberio/vector/runs/3577882554?check_suite_focus=true

fix(ci): Overwrite wix install if exists

---

src/rusoto/mod.rs

Closes #9005
I can't say that this is exhaustively tested, but I went through the API docs and some official client implementations to try to dig out some general patterns that we should be able to rely on here.
The most questionable part is the simple string matching instead of actually parsing the body, but the unknown format and structure made that seem tricky. It feels unlikely these error codes would be present in a 400-level response but not be _the_ error code.
I'm also not terribly attached to the mechanics of the matching. Given that the body size could be potentially large, it seemed worthwhile to match in a single pass, hence the `RegexSet`. But that may not be true with the additional complexity of the `OnceCell` and the fact that these will only happen occasionally and …

fix(aws service): more precise aws retry logic

---

lib/prometheus-parser/src/line.rs

Closes #8946 
As per the docs [here](https://prometheus.io/docs/instrumenting/writing_exporters/#naming), we should allow `:` in metric names.
I am a little unclear about what the docs mean:
> Exposed metrics should not contain colons, these are reserved for user defined recording rules to use when aggregating.
Does this imply that we should accept the `:` but remove the text after the `:` when we expose the metric in the prometheus sink?

fix(prometheus_scrape source): allow `:` in metric names

---

website/cue/reference/components/sources/datadog_agent.cue

As Vector does not yet support the V2 logs API
(https://github.com/vectordotdev/vector/issues/9144)

docs(datadog_agent source): Document setting use_v2_api to false

---

docs/CONTRIBUTING.md

Signed-off-by: Nathan Fox <fuchsnj@gmail.com>
Additional cleanup from https://github.com/vectordotdev/vector/pull/8372

docs: remove reference to deleted CODEOWNERS in CONTRIBUTING.md

---

lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs

Ref: https://github.com/vectordotdev/vector/issues/9144

fix(ci): Use use_v2_api: false for k8s datadog agent tests

---

docs/USER_EXPERIENCE_DESIGN.md
docs/specs/component.md
docs/specs/configuration.md
docs/specs/instrumentation.md

As we prepare efforts to standardize behind Vector's new [User Experience Design document](https://github.com/timberio/vector/blob/master/docs/USER_EXPERIENCE_DESIGN.md), I found the need to convert parts of that document to specifications. The User Experience Design document is intended to be theoretical and establish a mental model for UX decision making. Rigid rules, like naming, are better placed in a specification that can be strictly adhered to (e.g., #9110).

chore: Add specifications for configuration and instrumentation

---

src/sources/http.rs
src/sources/util/http.rs

According to https://httpwg.org/specs/rfc7230.html#deflate.coding HTTP request with `Content-encoding: deflate` 
shall send data using "zlib" data format containing a "deflate" compressed data stream, hence the shift from a `DeflateDecoder` to a `ZlibDecoder`.
Signed-off-by: prognant <pierre.rognant@datadoghq.com>

fix(http source): adjust deflate compression handling

---

src/sinks/util/adaptive_concurrency/tests.rs
src/sinks/util/service.rs
tests/data/adaptive-concurrency/defers-at-high-concurrency.toml
tests/data/adaptive-concurrency/defers-at-high-rate.toml
tests/data/adaptive-concurrency/drops-at-high-concurrency.toml

This change is intended to handle the issues noted in  https://github.com/timberio/vector/issues/8647 and https://github.com/timberio/vector/issues/8211, where concurrency limits were not being respected for http-based sinks when bad network conditions arose.
In changing this code, I noticed that the test `sinks::util::adaptive_concurrency::tests::all_tests` fails, due to the test sink achieving values well outside the maximums specified in the test file. I'm not sure if this is a case where the maximums were simply wrong before, or the layer swap has introduced improper behavior. I didn't want to commit to changing all of the concurrency test files until I had a better idea of which direction to take, so I would appreciate input there.

fix: reorder service layers to prevent unbounded retries

---

website/cue/reference/components/sinks/datadog_logs.cue

Reflected in the code but not in our documentation the new sink implementation
times out batches on 60 second intervals.

chore: Set Datadog Logs sink timeout to 60 seconds

---

src/buffers.rs

Fixes #7326 
Actually the following cannot be parsed
```toml
max_events = 42
```
because it requires the field `type` to be defined.
This is due to `#[serde(tag = "type")]`.
Implementing a custom deserializer fixes the issue.

feat(config): handle BufferConfig parsing without a type tag

---

src/sinks/s3_common/sink.rs

This PR fixes the behavior of the S3 sink by ensuring that the main task does not shut down until the I/O task shuts down, and that the I/O task only shuts down when it has processed all requests.
Prior to this, exiting the process (via something like Ctrl-C) would lead to in-flight batches never being fully sent, because while the batcher would recognize that it needed to emit them, the I/O task never had a chance to send them.

fix(aws_s3 sink): ship final batches when shutting down

---

src/sinks/datadog/logs/sink.rs
website/cue/reference/components/sinks/datadog_logs.cue

Inspired by the conversation on #9185 this PR adjusts the timeout down from 60
seconds to 5.

chore: Adjust Datadog Logs sink timeout to 5 seconds

---

src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/sink.rs
src/sinks/util/service.rs

This commit removes the referenced trait from the sink and from the
`TowerRequestLayer` implementation. Other callers can choose to leave this
constraint in place but it is not required. This change has also allowed me to
clean up the odd Ok/Err split noted in #8825.
I intend to do a similar bit of work to the s3 sinks.
REF #9140

chore: Removes `sink::Response` from the Datadog Logs sink

---

src/sinks/vector/v2.rs

In a like manner to #9203 and #9172 it turns out this trait, while implemented
in the v2 Vector sink, is not actually in use.

chore: Remove `sink::Response` from Vector V2

---

src/sinks/s3_common/config.rs
src/sinks/s3_common/service.rs
src/sinks/s3_common/sink.rs

This commit removes the need for `sink::Response` from the s3 sinks, in a like
manner to the work done in #9172.
Resolves #9140

chore: Remove the `sink::Response` trait from the s3 sinks

---

src/enrichment_tables/file.rs

It can be a real performance footgun and is clearly an error for an enrichment table function to search on a column that doesn't exist in the underlying dataset. 
This PR makes it an error to specify a field that doesn't exist.

enhancement(enriching): error if enrichment functions reference a non existent column

---

website/cue/reference/components/sinks/vector.cue

docs(vector sink): Fix relevant_when documentation for request options

---

src/sinks/s3_common/sink.rs

It turns out I introduced a breaking change in #9203. This commit fixes
it. Where the original implementation issued an 'Errored' for `Err` conditions
I'd adjusted it to be 'Failed'.

chore: Correct s3 integration tests

---

website/cue/reference/components/transforms/remap.cue
website/cue/reference/remap.cue

Also move the event_data_model "How it Works" to the `remap` transform
since it is unrendered in its current position.

docs(remap transform): Clarify how remap can access metrics

---

docs/specs/buffer.md

As mentioned in #7185, #5654, #4936, we'd like to provide more insight on buffer usage through instrumentation. Desired information includes (from #4936):
-  Buffer size in event quantity
-  Buffer size in bytes
-  Latency of the buffer (how long events are in the buffer)
-  Buffer total/possible size (to determine % used)
-  Events dropped quantity
This buffer specification details exact metrics that can be used. 
Signed-off-by: 001wwang <will.wang@datadoghq.com>

chore: Add buffer instrumentation spec

---

website/cue/reference/components/transforms/remap.cue

docs(remap transform): Missing ` in docs

---

Cargo.lock
Cargo.toml
src/top/cmd.rs
src/top/dashboard.rs
src/top/events.rs

Fixes #8449.
Note: This PR handles exiting gracefully (preventing the terminal stalling, and returning the cursor back to the active session). 
It doesn't tackle the CPU spike which still occurs when the host process is terminated. Tracking in #8770.

fix(cli): Fix `top` quitting when the host has gone away

---

docs/specs/instrumentation.md

chore: Re-add namespace to instrumentation spec

---

src/sinks/datadog_archives.rs

A follow-up fix on #8929: we incorrectly handled tags - instead of leaving them as is, we extracted array values `tags[0]`, `tags[1]`, etc

fix(datadog_archives sink): Correct encoding tags

---

website/content/en/docs/about/under-the-hood/_index.md
website/layouts/partials/docs/sidebar.html

Fixes #9239 and also updates the sidebar logic to accommodate mixing and matching pages and sections (rather than sections always being first). See here:
https://deploy-preview-9242--vector-project.netlify.app/docs/

fix(external docs): Change sidebar ordering

---

lib/vector-core/Cargo.toml
lib/vector-core/benches/event/log_event.rs
lib/vector-core/benches/event/main.rs
lib/vector-core/src/event/log_event.rs

This commit speeds up the `rename_key` function of `LogEvent` by 57%, avoiding
the use of path iteration code to achieve this. This results in +2MB/s in #8512.

chore: Speed up `LogEvent::rename_key` by 57%

---

website/yarn.lock

Just a standard housekeeping measure. This also eliminates the vulnerability warning on the main repo page.

chore(external docs): Upgrade JS dependencies

---

website/layouts/partials/javascript/below.html
website/layouts/partials/javascript/head.html
website/layouts/partials/javascript/home.html
website/layouts/partials/javascript/search.html

Apparently Hugo doesn't automatically add a subresource integrity fingerprint to JavaScript artifacts the way that it does to Sass/CSS artifacts. This PR fixes that. Just a small nit.

fix(external docs): Add JS fingerprint

---

lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/ip_aton.rs
lib/vrl/stdlib/src/ip_ntoa.rs
website/cue/reference/remap/functions/ip_aton.cue
website/cue/reference/remap/functions/ip_ntoa.cue

These functions were wrongly byte-swapping integers for their conversions, thus giving wrong results.
The `u32::from(Ipv4Addr)` and `Ipv4Addr::from(u32)` functions do not require bitness conversions after all.
I tested this using the `timberio/ci_image` Docker image (thanks for providing a ready-made environment!). But please let me know if anything else needs to be done for this PR.
Closes #9182 
cc: @jszwedko

fix(vrl): fix byte-swapped integers in ip_aton() and ip_ntoa() functions

---

website/cue/reference/remap/functions/match_datadog_query.cue
website/layouts/partials/badge.html
website/layouts/partials/data.html
website/tailwind.config.js

Addresses #9187, #9189, #9190, #9191, #9192
An example from the new template:
https://deploy-preview-9263--vector-project.netlify.app/docs/reference/vrl/functions/#parse_apache_log

fix(external docs): Improve VRL function templating

---

lib/vrl/parser/src/parser.lalrpop
lib/vrl/tests/tests/expressions/if_statement/multiline_predicates.vrl
website/cue/reference/remap/expressions/if.cue

This PR makes it possible to specify the statements in `if` predicates to work over multiple lines, so the following becomes possible:
```
if (
x = thing
y= thung
x == y 
) {
...
}
```
I've noticed some users have fairly lengthy predicates and this change makes things more ergonomic for them.

enhancement(vrl): allow statements in `if` predicates over multiple lines.

---

rfcs/2021-09-01-8547-accept-metrics-in-datadog-agent-source.md

TL;DR of the plan suggested in this RFC to ingest metrics from Datadog Agents:
1. Add a proxy feature that can relay unsupported payload from the `datadog_agent` source directly to Datadog
2. Support ingesting gauge, count & rate
3. Support ingesting distribution/sketches 
4. Follow-ups: handle non-metric payload beyond just proxying, use sketches/distribution in non-datadog piece of Vector
[Rendered RFC](https://github.com/timberio/vector/blob/prognant/RFC/accept-metrics-in-datadog_agent-source/rfcs/2021-09-01-8547-accept-metrics-in-datadog-agent-source.md)

chore(datadog_agent source): Accept metrics in the `datadog_agent` source RFC

---

src/buffers.rs

This shows up with `cargo clippy --no-default-features`

chore(buffers): Fix clippy error in `BufferConfig::resources`

---

netlify.toml
website/Makefile
website/config.toml
website/layouts/_default/index.json.json

This PR adds a JSON output to the site that will enable us to serve up metadata about Vector to clients. With these changes, the website will serve up VRL function metadata at `/index.json` so that it can be used by the VRL playground. There may be other uses for this in the future.

enhancement(external docs): Serve metadata as JSON

---

src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/mod.rs

feat(datadog_logs sink): use v2 endpoint for logs

---

lib/vector-api-client/graphql/queries/components.graphql
lib/vector-api-client/graphql/schema.json
lib/vector-api-client/graphql/subscriptions/component_events_in_throughputs.graphql
lib/vector-api-client/graphql/subscriptions/component_events_in_totals.graphql
lib/vector-api-client/graphql/subscriptions/component_received_events_throughputs.graphql
lib/vector-api-client/graphql/subscriptions/component_received_events_totals.graphql
lib/vector-api-client/graphql/subscriptions/events_in_throughput.graphql
lib/vector-api-client/graphql/subscriptions/events_in_total.graphql
lib/vector-api-client/graphql/subscriptions/received_events_throughput.graphql
lib/vector-api-client/graphql/subscriptions/received_events_total.graphql
lib/vector-api-client/src/gql/components.rs
lib/vector-api-client/src/gql/metrics.rs
lib/vector-api-client/tests/queries/file_source_metrics.graphql
src/api/schema/metrics/filter.rs
src/api/schema/metrics/mod.rs
src/api/schema/metrics/received_events.rs
src/api/schema/metrics/sink/generic.rs
src/api/schema/metrics/sink/mod.rs
src/api/schema/metrics/source/file.rs
src/api/schema/metrics/source/generic.rs
src/api/schema/metrics/source/mod.rs
src/api/schema/metrics/transform/generic.rs
src/api/schema/metrics/transform/mod.rs
src/top/dashboard.rs
src/top/metrics.rs
src/top/state.rs

Adds the `EventsReceived` side to the API per #9132. Deprecates `events_in_total` and related fields.
Will tackle `EventsSent` metrics in a separate PR.

chore(graphql api): Add `received_events_total` to the API

---

.github/semantic.yml

We have the source in tree, but no label for it yet.

chore(dev, ci): Add `exec` source to semantic.yml

---

lib/vector-core/src/sink.rs
src/sinks/blackhole.rs
src/sinks/console.rs
src/sinks/datadog/logs/sink.rs
src/sinks/file/mod.rs
src/sinks/nats.rs
src/sinks/prometheus/exporter.rs
src/sinks/s3_common/sink.rs
src/sinks/util/tcp.rs
src/sinks/util/udp.rs
src/sinks/util/unix.rs
tests/support/mod.rs

Signed-off-by: Nathan Fox <fuchsnj@gmail.com>
closes #9328 
Pros:
- `StreamSink::run` is now enforced by the compiler to only run once, removing the need to "Option unwrap" or do runtime checks if ownership is actually needed
Cons:
- `StreamSink::run` can now _only_ be called from a Boxed trait. This is all we currently do though, and probably not a large downside

chore(sinks): make StreamSink::run take self

---

.github/workflows/test.yml
rfcs/2021-09-01-8547-accept-metrics-in-datadog-agent-source.md
website/cue/reference/components/sinks/logdna.cue
website/cue/reference/components/sinks/loki.cue
website/cue/reference/components/sinks/splunk_hec_logs.cue

Note that this has an intentional missing indentation fix to double check that the cue format check step is actually happening.

chore(external docs): Actually run cue and markdown checks on CI

---

Cargo.lock
lib/vector-core/Cargo.toml
lib/vector-core/benches/path_iter.rs
lib/vector-core/build.rs
lib/vector-core/src/event/proto.rs
lib/vector-core/src/event/util/log/contains.rs
lib/vector-core/src/event/util/log/get.rs
lib/vector-core/src/event/util/log/get_mut.rs
lib/vector-core/src/event/util/log/insert.rs
lib/vector-core/src/event/util/log/path_iter.rs
lib/vector-core/src/event/util/log/remove.rs
lib/vrl/compiler/src/state.rs
lib/vrl/core/src/runtime.rs
src/sinks/datadog/events.rs
src/sinks/util/encoding/config.rs
src/sinks/util/encoding/with_default.rs
src/sources/dnstap/parser.rs
src/sources/dnstap/schema.rs
src/sources/docker_logs.rs
src/sources/kubernetes_logs/namespace_metadata_annotator.rs
src/sources/kubernetes_logs/pod_metadata_annotator.rs
src/transforms/grok_parser.rs
src/transforms/remap.rs
src/transforms/tokenizer.rs

We've reworked `PathIter` to avoid allocations where possible, as well as using the regular expression "fast path".
In profiling when investigating an issue reported by a user -- unexpectedly high memory usage (RSS specifically) -- it was determined that the bulk of allocations in their workload came from using the `remap` transform.  This was due to the nature of `PathIter`, allocating strings as it parsed paths, as well as running a regular expression over the input path to determine if a "fast path" could be taken.
We've reworked `PathIter` to remove this regular expression, as well as the fast path.  Instead, we parameterized `PathIter` over the lifetime of the input path, such that we can optimally return borrowed substrings when possible, only falling back to allocating when …

chore(architecture): refactor PathIter to avoid regex + allocations (plus a bonus change)

---

docs/specs/buffer.md

While implementing, I've realized calculating `buffer_usage_percentage` is tricky as determining current buffer size is difficult and it requires keeping track of `max_size`. 
Using a `buffer_max_{event, byte}_size` metric instead simplifies implementation and allows end users to derive `buffer_usage_percentage` relatively easily (e.g. `(buffer_received_events_total - buffer_sent_events_total) / buffer_max_event_size`).

chore: Add buffer max size metric to buffer specification

---

src/config/unit_test.rs
src/transforms/compound.rs
src/transforms/route.rs

Sanity check to avoid name-conflict in some expanded transforms (as mentionned #8848).

fix(transforms): add sanity check in route & compound transforms

---

lib/vrl/parser/src/parser.lalrpop
lib/vrl/tests/tests/expressions/if_statement/nested_if_else.vrl

Closes #8284 
The VRL parser was nesting the alternatives to `if..else` in the order they were parsed, which meant the first `if..else` became the most nested and thus the final predicate checked. This is the wrong order. This PR reverses the alternatives so the last gets nested deepest.

fix(vrl): reverse if else alternatives before nesting

---

CONTRIBUTING.md

A user missed it because they expected it to be at the root (which
I think is fairly common):
https://github.com/vectordotdev/vector/pull/9180#issuecomment-923886023

docs: Add link to CONTRIBUTING.md to root directory

---

rfcs/2021-08-29-8381-vrl-iteration-support.md

Running `make check-markdown` is failing on master.
Ref #9001 

chore(internal docs): Fix markdown lint issues in VRL iteration RFC

---

lib/vrl/stdlib/src/to_float.rs
website/cue/reference/remap/functions/to_float.cue

enhancement(vrl): Allow `to_float` to take timestamps

---

website/cue/reference/remap/functions/assert.cue
website/cue/reference/remap/functions/assert_eq.cue

Currently, the docs incorrectly label the `message` field as required when using the `assert` function. This PR corrects that and provides some clarification in the description.

fix(external docs): Provide the correct optionality for the VRL assert message

---

src/sinks/util/adaptive_concurrency/tests.rs
src/sources/generator.rs
src/topology/test/source_finished.rs
website/content/en/highlights/2021-10-05-0-17-upgrade-guide.md
website/cue/reference/components/sources/generator.cue

This may be somewhat controversial, in which case I'll retract it. But I feel like the default behavior of the `generator` source is probably not in line with users' expectations. As it stands, running the `generator` without specifying `interval` means that your terminal is *flooded* with a dizzying stream of events. Making the default behavior a steady trickle seems better to me. The 1.0 figure is purely arbitrary but seems intuitive enough.
I'm happy to retract this if others think that zero delay is indeed aligned with user expectations.

fix(generator source): Give the generator source a default interval

---

website/content/en/docs/reference/configuration/unit-tests.md

Given the issue I pointed out in #9386, the example link I'm removing here wouldn't work in a real unit test.

fix(external docs): Remove errant unit test example

---

lib/vector-core/buffers/benches/common.rs

Since switching from `block_in_place` to `spawn_blocking` in the disk buffer implementation ([see here](https://github.com/vectordotdev/vector/commit/70199c45637a7e3b665c3f80d0f95f47403f0d29#diff-0b6049db13528339ffd7add0386d3b413f5e79782faca2e69223aeb1f16c281dL111)), a runtime is now required for benchmarking.

fix(buffers): Use tokio runtime in buffer benchmarks

---

website/content/en/docs/setup/installation/package-managers/helm.md

Add a section pointing to the location of the helm chart source repository at https://github.com/vectordotdev/helm-charts
Took me a little bit to figure out where the new location was, so thought I'd send over a link! If this doesn't match reality (or y'all have other ideas) happy to make some tweaks!

enhancement(external docs): Link to Helm chart repo

---

website/content/en/docs/reference/configuration/_index.md

Remove extra tab for TOML, since [it breaks the page](https://vector.dev/docs/reference/configuration/#reference) otherwise.
Signed-off-by: Joe Smith <yasumoto7@gmail.com>

fix(external docs): Fix configuration reference

---

lib/vrl/DESIGN.md

These were missed in the PR since it predated the markdown linting.

chore(vrl): Lint DESIGN.md

---

website/cue/reference/components/sources/syslog.cue

It was using the socket configuration, but there are some differences
(`mode` has different values, `shutdown_timeout_secs` isn't supported).

docs(syslog source): Fix configuration documentation

---

lib/vrl/DESIGN.md
website/cue/reference/cli.cue

This is included in `vector --help` but not on the site, additionally it's not terribly clear for the other config options how to pass multiple file names - but I can't think of appropriate wording.

docs: Include config-dir option in CLI docs

---

website/cue/reference/components.cue
website/cue/reference/components/sources/datadog_agent.cue

Component descriptions were being limited in allowed characters. This
relaxes it to just allow strings. I'm unsure if there was a reason we
were restricting this though @binarylogic do you know?
Fixes: #9408 

docs(datadog_agent source): Fix description rendering

---

src/sources/prometheus/scrape.rs
website/cue/reference/components/sources/prometheus_scrape.cue

This adds a new configuration, `instance_key`, to the
`prometheus_scrape` source. If set, it will tag scraped metrics with their
instance in the same fashion as the prometheus scraper.
I opted to let users opt into this as this source has been around for
a while and I could see the extra tag causing some users some surprise
as Prometheus, when scraping, if the metric already has `instance`, will
avoid resetting it based on its `honor_labels` configuration.
Ref: https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series
Closes: #9322
Closes: #6953

enhancement(prometheus_scrape source): Allowing tagging metrics with instance and endpoint

---

website/content/en/docs/reference/configuration/unit-tests.md
website/layouts/partials/admonition.html

This PR enhances the recently added unit testing docs (#9377) by adding examples for multiple transforms. The new section:
https://deploy-preview-9418--vector-project.netlify.app/docs/reference/configuration/unit-tests/#multiple-transforms

enhancement(external docs): Add multiple transform examples to unit testing docs

---

src/rusoto/auth.rs
src/rusoto/mod.rs
website/cue/reference/components/aws.cue

Hello,
This pull request intends to introduce the support to use AWS credentials file for AWS authentication instead of specifying `access_key_id` and `secret_access_key` directly.
Usage example in [AWS Kinesis Firehose sink configuration](https://vector.dev/docs/reference/configuration/sinks/aws_kinesis_firehose/):
```toml
[sinks.my_sink_id]
type = "aws_kinesis_firehose"
inputs = [ "my-source-or-transform-id" ]
stream_name = "my-stream"
compression = "none"
region = "us-east-1"
credentials_file = "/path/to/aws/credentials" # <= new
profile = "production"                        # <= new
```

feat(aws service): add support to use AWS credentials file for AWS authentication

---

src/codecs/framers/bytes.rs

fix(codecs): Propagate empty byte frames in message based transports

---

src/sinks/datadog/logs/sink.rs
src/sinks/datadog/logs/tests.rs

Currently if users set `encoding.timestamp_format` to `unix` we would produce `date` in seconds, but DD expects unix timestamp in milliseconds.
Also changes `date` to `timestamp`, both fields are [parsed](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#log-date-remapper) as an event's timestamp by DD, but `timestamp` key is more aligned with the unix timestamp value as well as with Logs API.
Signed-off-by: Vladimir Zhuk <vladimir.zhuk@datadoghq.com>

fix(datadog_logs sink): always send unix timestamp in milliseconds

---

lib/vrl/tests/tests/fixme/README.md
website/content/en/blog/vector-remap-language.md
website/content/en/docs/reference/configuration/unit-tests.md
website/content/en/docs/reference/vrl/_index.md
website/content/en/docs/reference/vrl/errors.md
website/cue/reference/components/transforms/aws_cloudwatch_logs_subscription_parser.cue
website/cue/reference/remap/concepts/event.cue
website/cue/reference/remap/errors/305_divide_by_zero_error.cue
website/cue/reference/remap/features/high_quality_error_messages.cue
website/cue/reference/remap/features/type_safety.cue
website/cue/reference/remap/literals/regular_expression.cue
website/layouts/partials/data.html

A [side-by-side comparison](https://gist.github.com/lucperkins/bdbceef6c210d0f3d17eb27b566a5326), as well as a handful of RFCs, indicate that CoffeeScript syntax highlighting is slightly better for VRL than Ruby highlighting, which we've been using for the website thus far.

chore(external docs): Use CoffeeScript highlighting instead of Ruby for VRL

---

src/sinks/datadog/logs/healthcheck.rs
src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/tests.rs

V2 API replies with 202(Accepted) status code instead of 200.
Signed-off-by: Vladimir Zhuk <vladimir.zhuk@datadoghq.com>

fix(datadog_logs sink): expect ACCEPTED(202) instead of OK(200) 

---

lib/vector-core/buffers/examples/soak.rs
lib/vector-core/buffers/src/lib.rs
lib/vector-core/buffers/src/variant/memory_only.rs

Found by running `cargo clippy --workspace --all-targets --no-default-features` which does not enable the disk buffer path. Running `make check-clippy` runs with all features enabled, so this no-disk-buffer path is never tested by default.
Closes #9309 

chore(buffers): Fix compilation issues when disk buffers are not enabled

---

lib/vrl/stdlib/src/parse_url.rs

fix(vrl): Correct parse_url's value type

---

src/sinks/datadog/logs/healthcheck.rs
src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/tests.rs

This commit adjusts the sink code to respond correctly to either the v1 or v2
API's status codes. The vector user is allowed to explicitly set the API
endpoint, meaning the sink must continue to function for v1. Recent changes to
support the v2 API have muddied the implementation somewhat. I have updated 
the comments to reflect which status codes come from what API version and 
have expanded the tests to capture v1 and v2 responses.
I have confirmed that this reports logs into both v1 and v2 live API endpoints by 
direct experimentation. 
Resolves #9484. Strongly suggests we should pursue #8442.

chore: Accept either v1 or v2 status codes

---

scripts/release-github.sh

grease was not following the HTTP redirects

chore(releasing): Fix Github release asset upload

---

website/cue/reference/components/sources/aws_s3.cue

This PR updates the example to make the regex a one-liner so users can copy-paste and doesn't cause their configs to error.

enhancement(external docs): Update S3 source example

---

.github/workflows/soak.yml

We don't want to soak master/master. Because of this our previous setup was
effectively pull_request only, though we weren't quite intentional about
that. This PR makes that choice intentional.

chore: Only soak on pull requests

---

src/sinks/aws_s3/sink.rs
src/sinks/aws_s3/tests.rs

Credits to: [Alex-OH on discord](https://discord.com/channels/742820443487993987/746070591097798688/904789992281362524) for pointing out this issue.
This PR removes an unintended `/` when building the `partition_key` path. In accordance with[ documented behavior](https://vector.dev/docs/reference/configuration/sinks/aws_s3/#key_prefix), users should specify `/` explicitly.

fix(aws_s3 sink): Remove unintentional prefix

---

lib/vector-core/core-common/src/internal_event/bytes_sent.rs
lib/vector-core/core-common/src/internal_event/events_sent.rs
lib/vector-core/core-common/src/internal_event/mod.rs
lib/vector-core/src/stream/driver.rs
scripts/check-events
src/internal_events/common.rs
src/sinks/kafka/service.rs
src/sinks/kafka/tests.rs
tests/buffering.rs
website/cue/reference/components/sinks/kafka.cue

I reviewed the new-style sinks to make sure they are all sending `EventsSent` + `BytesSent` and have appropriate documentation for them. Only kafka ended up needing some changes.
As part of this, I also moved `BytesSent` into `core-common`.

chore(kafka sink): add `BytesSent` metric

---

.github/workflows/soak.yml

We could probably afford a more comprehensive audit of what runs when, but this PR applies a restriction that should make iterating on the site/docs more speedy.
I haven't verified that this rule for Actions actually works but [the docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-ignoring-paths) do seem to suggest so.

fix(external docs): Remove soak testing for website changes

---

website/cue/reference/components/sinks.cue

Closes #6975
This PR adds proper handling for sink compression options beyond `none` and `gzip`. As a [user noted in discord](https://discord.com/channels/742820443487993987/746107317459877968/905050324014870588), the kafka sink compression section is currently incorrect.
Sample output for the Kafka sink.
```
"compression": {
"common": true,
"description": "The compression strategy used to compress the encoded event data before transmission.\n\nSome cloud storage API clients and browsers will handle decompression transparently,\nso files may not always appear to be compressed depending how they are accessed.",
"name": "compression",
"required": false,
"warnings": [],
"type": {
"string": {
"default": "none",
"enum": {
"none": "No compression.",
"gzip": "[Gzip](https://www.gzip.org/) …
```

fix(external docs): Fix sink compression options

---

.github/workflows/soak.yml

This commit fixes a bug in our soak workflow where the analyze-results step is
missing compute-test-plan in its needs list.

chore: analyze-results requires compute-test-plan

---

.github/workflows/environment.yml
.github/workflows/integration-test.yml
.github/workflows/k8s_e2e.yml
.github/workflows/release.yml
.github/workflows/test.yml

This PR follows up on #9871 by removing yet more Actions triggered on the basis of changes to the `website` directory. I'm open to suggestion on the proper mechanism for this, and there are multiple ways of including/excluding changes to files and directories as potential build triggers, but this seems like the best way to me.

enhancement(external docs): Trigger fewer Actions from website changes

---

.github/workflows/soak.yml

This commit attempts to store soak captures in a single artifact, ideally
allowing us to process them in one shot in the service of #9622. Even if that
doesn't pan out these will still be easier to pull for later analysis in a
single artifact.

chore: Store captures in a single artifact

---

src/sinks/prometheus/exporter.rs

enhancement(prometheus_exporter sink): expire metrics

---

Cargo.lock
Cargo.toml
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/src/parse_syslog.rs
src/codecs/parsers/syslog.rs

Closes #9824 
This removes the escapes from the values in structured data fields - `/`.
See also https://github.com/StephenWakely/syslog-loose/commit/0db6ee4736acf624b2cd3a58cb3bdddc4d43dbd7 which updates `syslog_loose`.

enhancement(syslog source): Remove escapes from structured data in syslog message

---

src/config/loading.rs

With the `pipelines` transform being developed, we'll need the configuration to be able to load recursively.
This refactoring will allow the different component to implement their own way of loading subfolders.

feat(config): refactor loading for loading recursively

---

lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/lib.rs
lib/vrl/stdlib/src/tally_value.rs

We had originally added `tally` upon a user request even though it is
likely to be supplanted by the upcoming VRL iteration work. However,
they are sensitive to increases in RSS and found that `tally` increased
RSS more than they'd like. Their purposes are simpler in that they just
want to count the number of occurrences of a specific value which can be
done in a more memory efficient way.
Thus here I add `tally_value` to accomplish this. This function is also
a prime candidate to be deleted when VRL iteration is added so I left it
undocumented for now. Once iteration is added we can decide if either of
these functions is worth keeping around and publish them then.

enhancement(vrl): Add `tally_value` function

---

.github/workflows/soak.yml
soaks/bin/analyze_experiment.sh
soaks/bin/run_experiment.sh
soaks/soak.sh

Building from #9873 we now perform analysis in one step over all soaks. This has
the added benefit of allowing us to compute a markdown blob for output, which
should set us up nicely for #9622.

chore: Analyze all captures at once

---

website/layouts/partials/meta.html

With this PR, the SEO/Algolia titles for components include the component type. Thus, the `file` source would have the search title of "File source" rather than just "File," which should help to disambiguate component types in results.
Fixes #9908
You can see the changes at work in the `head` of this page:
https://deploy-preview-9914--vector-project.netlify.app/docs/reference/configuration/sources/file

fix(external docs): Improve SEO titles for components

---

.github/workflows/environment.yml
.github/workflows/integration-test.yml
.github/workflows/k8s_e2e.yml
.github/workflows/release.yml
.github/workflows/test.yml

This PR reverts #9872. For reasons that are quite murky to all involved, somehow using `paths-ignore` causes workflows to not _run_ but it doesn't change the _requirement_ that they be run. So we've ended up in a state where people submit website-only PRs and numerous ostensibly required checks are listed as unfulfilled... even though those checks should be simply ignored by GitHub Actions based on the supplied configuration. A counter-intuitive and, indeed, frustrating problem, but at the moment I don't see any way around it. I'll report to the proper authorities.
Note: both this and #9912 fail the DCO check. It's not clear to me, however, that a DCO would be necessary in this case. But if it is, I'm happy to close these and re-submit them as standard PRs rather than as GitHub auto-PRs.

chore(ci): Revert PR 9872

---

.github/workflows/soak.yml

This commit expands the class of ignored paths for soaking. RFCs and docs
changes don't change code and don't need a comparison run.

chore: Do not soak documentation changes

---

soaks/bin/build_container.sh

Older versions of vector have a very strict .dockerignore file in them which
docker builder is unable to ignore. This commit "ignores" that ignore file by
overwritting it with one that is present in the current SHA.

chore: Fix older vector soak builds

---

src/topology/builder.rs
src/utilization.rs

Opening this as a draft since I plan to do more testing, but it should be good to review as-is.
This is a relatively naive but straightforward adaptation of our existing utilization `Stream` wrapper to non-async transforms. The benefit is that we can start the "waiting" span sooner than the `Stream` case, as soon as the transform is done processing and begins sending to its output. This will provide a much more accurate view of how much work a transform is doing vs being blocked on downstream components.
As part of this, it was beneficial to make the wrappers for function and fallible function transforms more similar. This includes moving from combinators to an `async` block for the function variant, and adding the `ready_chunks` batching to the fallible variant. It'd be great to share …

enhancement(observability): improve transform utilization metrics

---

soaks/bin/run_experiment.sh
soaks/soak.sh

As the work on the CI workflow got more involved the local soak suffered. In
this case when the directory scheme shifted we did not maintain the same concept
in the local variant. Almost, but not quite. This commit allows the local
variant to go through a whole soak.

chore: Correct more local-run soak problems

---

.github/workflows/soak.yml

For pull requests, `github.sha`, is actually often the merge commit
Github Actions makes, before running the workflow, if the pull request
branch is out of date with `master`.
Closes: #9940
Ref: https://github.community/t/github-sha-isnt-the-value-expected/17903

chore(ci): Update how soak tests determine SHA

---

src/vector_windows.rs

On Windows, prior to this commit, the topology life cycle was handled separately from the main application running logic.
This meant that the windows service running logic did not benefit from improvement made inside the main application running logic.
That behavior was causing a memory-leak when running vector as a service on Windows because the "early buffering" mechanism that
was introduced for internal events was not properly stopped inside the windows running logic.
To make it future-proof, vector now directly calls `Application::run` inside the windows running logic.
This addresses #9207

fix(windows platform): call `Application::run` when running vector as a service on windows instead of manually handling the topology life cycle.

---

rfcs/2021-10-29-9465-splunk-hec-indexer-acknowledgements.md

This PR adds an RFC for supporting Splunk HEC indexer acknowledgement in the `splunk_hec` source and `splunk_hec` sinks. 
[Rendered](https://github.com/vectordotdev/vector/blob/rfc-indexer-acknowledgements/rfcs/2021-10-29-9465-splunk-hec-indexer-acknowledgements.md)

chore: Add Splunk HEC indexer acknowledgement RFC

---

.github/workflows/soak.yml
soaks/bin/analyze_experiment.sh
soaks/bin/boot_minikube.sh
soaks/bin/run_experiment.sh
soaks/bin/soak_one.sh
soaks/common/terraform/modules/vector/main.tf
soaks/common/terraform/modules/vector/variables.tf
soaks/soak.sh
soaks/tests/datadog_agent_remap_blackhole/terraform/main.tf
soaks/tests/datadog_agent_remap_blackhole/terraform/variables.tf
soaks/tests/datadog_agent_remap_datadog_logs/terraform/main.tf
soaks/tests/datadog_agent_remap_datadog_logs/terraform/variables.tf
soaks/tests/syslog_humio_logs/terraform/main.tf
soaks/tests/syslog_humio_logs/terraform/variables.tf
soaks/tests/syslog_log2metric_humio_metrics/terraform/main.tf
soaks/tests/syslog_log2metric_humio_metrics/terraform/variables.tf
soaks/tests/syslog_log2metric_splunk_hec_metrics/terraform/main.tf
soaks/tests/syslog_log2metric_splunk_hec_metrics/terraform/variables.tf
soaks/tests/syslog_loki/terraform/main.tf
soaks/tests/syslog_loki/terraform/variables.tf
soaks/tests/syslog_regex_logs2metric_ddmetrics/terraform/main.tf
soaks/tests/syslog_regex_logs2metric_ddmetrics/terraform/variables.tf
soaks/tests/syslog_splunk_hec_logs/terraform/main.tf
soaks/tests/syslog_splunk_hec_logs/terraform/variables.tf

This commit allows the user to set CPU/memory targets for the soak environment
and the CPU limit for vector. This allows us to provide more memory than
developers are expected to have in CI and also to adjust the units of our
analysis to bytes/second/CPU.
Closes #9939
REF #9926
REF #9942

chore: Allow CPU/memory targets to be set by user in soaks

---

lib/vrl/stdlib/src/compact.rs

It was implemented as `map`, but was documented as `object`, which is
how we refer to key/value types in VRL now (previously we did use
`map`).
Fixes: #9958

fix(vrl): Fix naming of `compact`'s `object` argument

---

website/cue/reference/components/sinks/prometheus_exporter.cue

This field took on more responsibility in
https://github.com/vectordotdev/vector/pull/9769. This PR updates the
doc to reflect its new semantics.

docs(prometheus_exporter sink): Update `flush_period_secs` docs

---

.github/workflows/soak.yml
soaks/common/terraform/modules/monitoring/observer.tf
soaks/common/terraform/modules/vector/main.tf
soaks/tests/splunk_hec_route_s3/README.md
soaks/tests/splunk_hec_route_s3/terraform/http_blackhole.toml
soaks/tests/splunk_hec_route_s3/terraform/http_gen.toml
soaks/tests/splunk_hec_route_s3/terraform/main.tf
soaks/tests/splunk_hec_route_s3/terraform/variables.tf
soaks/tests/splunk_hec_route_s3/terraform/vector.toml

This commit introduces a soak for the above configuration. Interestingly vector
crashes owing to being too memory hungry and the soak does not run as a result.
REF #9515 

chore: Introduce splunk_hec -> route -> s3 soak

---

.github/workflows/soak.yml

closes: https://github.com/vectordotdev/vector/issues/9973
The current theory is that for multiple runs of the same job, the `/tmp` directory is not cleared, so there is extra files being uploaded as artifacts that shouldn't be. This just deletes files before a soak is run

fix(ci): fix soak test artifact uploading

---

soaks/tests/fluent_remap_aws_firehose/README.md
soaks/tests/fluent_remap_aws_firehose/terraform/http_blackhole.toml
soaks/tests/fluent_remap_aws_firehose/terraform/main.tf
soaks/tests/fluent_remap_aws_firehose/terraform/tcp_gen.toml
soaks/tests/fluent_remap_aws_firehose/terraform/variables.tf
soaks/tests/fluent_remap_aws_firehose/terraform/vector.toml

This commit ports an older soak to the new CI format. There's nothing special
going on here, excepting that it is the first to involve the firehose sink.

chore: Introduce fluent -> remap -> firehose soak

---

src/kubernetes/reflector.rs
src/kubernetes/resource_version.rs

Closes #7943
I had to remove the const to set it like this, if there's a better alternative let me know. Setting this to 0 rather than None should allow us to use cached values from the apiserver rather than getting the freshest results from etcd directly.

feat(kubernetes_logs source): Use resource_version of 0 to use cache

---

soaks/common/terraform/modules/lading_http_blackhole/main.tf
soaks/tests/datadog_agent_remap_datadog_logs/terraform/http_blackhole.toml
soaks/tests/fluent_remap_aws_firehose/terraform/http_blackhole.toml
soaks/tests/splunk_hec_route_s3/terraform/http_blackhole.toml
soaks/tests/splunk_transforms_splunk3/terraform/http_blackhole.toml
soaks/tests/syslog_humio_logs/terraform/http_blackhole.toml
soaks/tests/syslog_log2metric_humio_metrics/terraform/http_blackhole.toml
soaks/tests/syslog_log2metric_splunk_hec_metrics/terraform/http_blackhole.toml
soaks/tests/syslog_loki/terraform/http_blackhole.toml
soaks/tests/syslog_regex_logs2metric_ddmetrics/terraform/http_blackhole.toml
soaks/tests/syslog_splunk_hec_logs/terraform/http_blackhole.toml

This commit relaxes the limits we put on http_blackhole. It hasn't come up but
in more throughput oriented experiments we've found that the blackhole will
crash after it triggers its CPU limit.
REF #9997

chore: Relax blackhole limits

---

soaks/common/terraform/modules/vector/main.tf
soaks/common/terraform/modules/vector/variables.tf
soaks/tests/datadog_agent_remap_blackhole/terraform/main.tf
soaks/tests/datadog_agent_remap_datadog_logs/terraform/main.tf
soaks/tests/fluent_remap_aws_firehose/terraform/main.tf
soaks/tests/splunk_hec_route_s3/terraform/main.tf
soaks/tests/splunk_transforms_splunk3/terraform/main.tf
soaks/tests/syslog_humio_logs/terraform/main.tf
soaks/tests/syslog_log2metric_humio_metrics/terraform/main.tf
soaks/tests/syslog_log2metric_splunk_hec_metrics/terraform/main.tf
soaks/tests/syslog_loki/terraform/main.tf
soaks/tests/syslog_regex_logs2metric_ddmetrics/terraform/main.tf
soaks/tests/syslog_splunk_hec_logs/terraform/main.tf

This commit follows-up on [this
comment](https://github.com/vectordotdev/vector/pull/9997#discussion_r747630811)
and removes unused `test_name`. The label has no value and is a hold over from
an earlier form these soak tests took.

chore: Remove unused 'test_name' variable in vector module

---

website/content/en/blog/graphql-api.md

Fixes an outdated example in the [GraphQL API announcement](https://vector.dev/blog/graphql-api/) post for querying a configured topology.
Closes #10028

fix(blog website): Fix topology query in GraphQL API blog post

---

soaks/README.md
soaks/tests/fluent_elasticsearch/terraform/main.tf

This parameter was dropped in https://github.com/vectordotdev/vector/pull/10003

fix(ci): Drop `test_name` parameter from soak

---

website/content/en/highlights/2021-10-08-0-17-upgrade-guide.md

This was moved to `demo_logs`
There is a redirect for this, but the link checker isn't aware of that:
https://github.com/vectordotdev/vector/blob/master/website/layouts/index.redirects#L33
Currently is breaking master: https://app.netlify.com/sites/vector-project/deploys/6192c95ee78d5e00079456cd

docs: Fix link to aliased `generator` source

---

.github/workflows/soak.yml

In #10053 we're attempting to diagnose why soak tests are not reliably producing
artifacts in CI. This work is made harder by competition from other jobs. With
the utility of soaks being low it makes sense to disable these for now, to be
re-enabled once the experiment reporting is reliable again.

chore: Temporarily disable soak testing

---

docs/specs/component.md

Small typo fix in the component spec.

fix(internal docs): Fix typo in component spec

---

soaks/common/terraform/modules/lading_splunk_hec_blackhole/main.tf
soaks/common/terraform/modules/lading_splunk_hec_blackhole/variables.tf
soaks/common/terraform/modules/lading_splunk_hec_gen/main.tf
soaks/common/terraform/modules/lading_splunk_hec_gen/variables.tf

This PR adds lading's `splunk_hec_gen` and `splunk_hec_blackhole` to the available soak test modules. I based these off the other lading modules.

chore: Add lading splunk_hec soak test modules

---

src/sinks/loki/config.rs
website/cue/reference/components/sinks/loki.cue

Closes #9791
Loki's default throughput limits are 4 MB/s.

chore(loki sink): Update batch defaults

---

website/content/en/highlights/2021-11-16-0-18-0-upgrade-guide.md

Compatibility was preserved here and so will be noted in the general
release notes.

chore(releasing): Remove breaking change note for `VECTOR_LOG`

---

src/transforms/throttle.rs
website/cue/reference/components/transforms/throttle.cue

For duration parameters we always add a suffix with the unit to make it
easy to tell what unit the parameter is in without checking the docs.
This is mentioned in the [configuration spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/configuration.md#option-naming).

fix(throttle transform): Rename `window` parameter

---

soaks/common/terraform/modules/vector/main.tf

Without this label the service selector was overly broad and included endpoints for any Pod with the baseline/comparison label - this then caused some resolutions to link to the wrong pod.

chore: Add additional label so Vector service works in soak tests

---

Cargo.lock
Cargo.toml

Our tokio version was previously 1.13.0 which had an advisory regarding a panic
in oneshot, per https://github.com/tokio-rs/tokio/issues/4225. This problem is
corrected in 1.13.1, which this commit bumps us to.

chore: Point upgrade tokio to address advisory

---

.github/workflows/soak.yml
Cargo.lock
lib/soak/Cargo.toml
lib/soak/configs/observer.toml
lib/soak/src/bin/observer.rs
soaks/common/terraform/modules/monitoring/observer.tf

It turns out the previous service definition for vector was overly broad
and allowed for traffic to be routed to pods that were not vector, but
only sometimes. This caused intermitent loss of experimental results.
Observer logging was expanded to help debug this. Credit to Spencer for
the ultimate realization.

chore: Correct soak service bug, expand observer logging 

---

lib/vector-core/buffers/src/config.rs

Found by running `cargo clippy --no-default-features`

chore(buffers): Fix clippy lint in `BufferConfig::build`

---

.github/workflows/soak.yml

This commit removes unused docker images from the soak machines after running an
experiment. We have found that the machines get gradually more slow as time
wears on and one hypothesis is that this has to do with the number of unused
images sitting around. In any event this will help our soak machines not run out
of disk space so quickly.

chore: Clean unused images from soak machines

---

src/sinks/influxdb/logs.rs
src/sinks/influxdb/metrics.rs
src/sinks/influxdb/mod.rs
src/sinks/sematext/metrics.rs

A small performance optimization in the hot path of the influxdb sinks, discovered while reviewing #10082. I'm sure there are other opportunities here, this was just a quick and easy find.

chore(influxdb_logs sink, influxdb_metrics sink): Reduce unneeded string clones

---

src/internal_events/kubernetes/reflector.rs

chore(kubernetes_logs source): Differentiate between stream and invocation desyncs

---

lib/vector-core/src/partition.rs
lib/vector-core/src/stream/batcher.rs
lib/vector-core/src/stream/mod.rs
lib/vector-core/src/stream/partitioned_batcher.rs
src/sinks/aws_kinesis_firehose/sink.rs
src/sinks/aws_kinesis_streams/sink.rs
src/sinks/azure_common/sink.rs
src/sinks/datadog/logs/sink.rs
src/sinks/datadog/metrics/sink.rs
src/sinks/elasticsearch/sink.rs
src/sinks/gcs_common/sink.rs
src/sinks/loki/sink.rs
src/sinks/s3_common/sink.rs
src/sinks/splunk_hec/logs/sink.rs
src/sinks/splunk_hec/metrics/sink.rs
src/sinks/util/builder.rs

closes https://github.com/vectordotdev/vector/issues/9720
A new `Batcher` was added, and the existing one was renamed to `PartitionedBatcher`.
There are multiple benefits of this re-write:
1. Partitioning is no longer required for the `Batcher`. This cleans up the code a bit, and removed the `NullPartitioner`. It also allows some optimizations such as removing the unnecessary overhead of using a `HashMap`.
2. The previous batcher required the use of the `ByteSizeOf` trait for determining the size of a batch. This implementation allows you to use anything (and an implementation that falls back to `ByteSizeOf` was added for easy migration). This is especially important for types that couldn't directly implement `BytesSizeOf` such as the protobuf types used in the `Vector` sink.
There are a …

chore(core): re-write the `Batcher` to remove the Partition requirement

---

src/transforms/remap.rs

Closes #10129
This is a bit of a hack, but it's small and should fix a wart that would otherwise have to wait until we do more remodeling of the transform model for branching. It takes advantage of the `impl<T> FunctionTransform for T where T: FallibleFunctionTransform` that was previously only used in tests and simply discards any error outputs. In this case we won't actually do any discarding because we know that the transform itself isn't configured to actually write anything to that output.

fix(remap transform): only add dropped output when enabled

---

website/cue/reference/components/sources/splunk_hec.cue

This PR corrects the acknowledgements configuration docs for the `splunk_hec` source (and some minor rewording). This was mistakenly left un-updated after a refactoring in #10044.

fix(external docs): Correct splunk_hec source acknowledgements docs

---

src/sources/splunk_hec/mod.rs

This PR removes an unnecessary debug print (introduced in recent merge of #10044) that is now caught by `clippy`.

fix: Remove unnecessary debug print

---

website/content/en/guides/level-up/managing-complex-configs.md

I am opening this PR to help new users getting into Vector. I actually wanted to fix https://vector.dev/docs/reference/configuration/sinks/socket/#example-configurations, but I assume that is auto generated with all the required options. I don’t know how that can be fixed. `address` and `path` are not required in all cases, depending on `mode`.

docs(config): Make example in guides/level-up/managing-complex-configs work with Vector 0.18

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature.md

Adopted this [from Terraform](https://github.com/hashicorp/terraform-provider-aws/blob/448475ec7f54b267e33d249d24acfa25904fd643/.github/ISSUE_TEMPLATE/Bug_Report.md).

chore: Add community note to issue templates

---

lib/vector-core/src/transform/config.rs
src/config/compiler.rs
src/config/mod.rs
src/transforms/pipelines/mod.rs

The pipelines transform should not be nested in another pipelines transform.
This PR adds a new `nestable` method to the `TransformConfig` trait to check if a transform can be embedded in some parent transforms.
For now, it's only used by the pipelines transform and the result defaults to `true` for all the other transforms.

feat(pipelines transform): forbid nesting pipelines transform

---

lib/vrl/parser/src/lex.rs
lib/vrl/tests/tests/expressions/literal/string.vrl
website/cue/reference/remap/literals/string.cue

Closes #7519
This allows multiline strings in Vrl by escaping the new line as per the following:
```
.thing = "foo \
bar"
assert(.thing == "foo bar")
```
All whitespace at the start of the ensuing line is removed.

enhancement(vrl): Allow multiline strings

---

src/config/loading.rs

Since vector is loading namespaces automagically, every folder in the `--config-dir` folder not corresponding to a type of component generates an error.
When Vector is installed with a `rpm`, an `example` folder is created in the default Vector's config directory and this makes Vector not being able to start properly.
This PR converts this error into a warning so that these folders are ignored, allowing Vector to start properly, but still logged so that users are aware of potential errors (creating a `tranforms` folder instead of `transforms` for example).
Fixes #10166

fix(config): only log warnings when folders invalid

---

scripts/environment/bootstrap-macos-10.sh

CI started failing inexplicably due to bundler not being found.

chore(ci): Install bundler on OSX

---

src/config/loading.rs

As required [here](https://github.com/vectordotdev/vector/issues/10166#issuecomment-979372404), we'll no longer have a warning if a folder exists in the configuration folder and its name doesn't match any component type.

fix(config): remove warnings when folder isn't expected

---

src/codecs/decoding.rs
src/sources/aws_kinesis_firehose/handlers.rs
src/sources/aws_sqs/source.rs
src/sources/datadog/agent.rs
src/sources/demo_logs.rs
src/sources/exec/mod.rs
src/sources/fluent.rs
src/sources/heroku_logs.rs
src/sources/kafka.rs
src/sources/logstash.rs
src/sources/nats.rs
src/sources/socket/udp.rs
src/sources/stdin.rs
src/sources/util/codecs.rs
src/sources/util/mod.rs
src/sources/util/tcp.rs
src/sources/util/unix_datagram.rs
src/sources/util/unix_stream.rs

Addressing the following TODO to better reflect that this error can occur while decoding any stream, not just TCP.
https://github.com/vectordotdev/vector/blob/f8d58c2f0c739165cd3cc2916a9d57218f10970b/src/sources/util/tcp_error.rs#L5-L6

chore(codecs): Rename `TcpError` -> `StreamDecodingError`

---

website/content/en/guides/level-up/managing-complex-configs.md
website/content/en/guides/level-up/managing-schemas.md

This is deprecated in-lieu of VRL conditions.
A [user was confused by
this](https://discord.com/channels/742820443487993987/746107317459877968/913850313730052187)

docs: Remove use of `check_fields` from guides

---

website/content/en/highlights/2021-10-08-0-17-upgrade-guide.md

docs(releasing): Add note to v0.17.0 about `events_processed_total` going away

---

lib/vector-core/src/metrics/mod.rs

This alias existed for maintaining compatibility, but when `events_out_total` was updated to `events_sent_total` in b5105d9fb we neglected to update this alias (if only we had had tests 😓).
Given that commit was released in v0.17.0 I'm planning to just update the release docs to mention it was dropped. I'll do this as a separate PR so I can cherry-pick that commit into the release branch to update the docs.

chore(observability): Remove unused alias for `events_processed_total`

---

website/cue/reference/components/sources/file.cue
website/cue/reference/components/sources/kubernetes_logs.cue

docs(kubernetes_logs source): Document `max_read_bytes`

---

docs/specs/component.md

These sinks, just `prometheus_exporter` at the moment, should not
publish the `events_sent_total` and `bytes_sent_total` metrics.

chore: Update component spec for aggregate pull-based sinks

---

.github/workflows/test.yml
soaks/bin/analyze_experiment

The line `csv['value'] = csv['value'].div(args.vector_cpus)` adjusts the
experiment value to a per-cpu unit. This means that any of the applications of
`adjust_per_cpu` were inappropriately doubling the number of CPUs that the
experimental values were being compared against.
This commit corrects the problem.

chore: Remove doubled-up per-cpu adjustment

---

.github/workflows/soak.yml
soaks/bin/detect_regressions

This commit adds a step to the soak workflow that flags regressions in a way
that will trip our CI setup. The thresholds here are the same as for the
analysis step, though they could be set to be more lax or strict as we desire.

chore: Soak detect regression

---

soaks/bin/analyze_experiment

As seen in #10202 it's possible for ttest_ind to return a nan for the test
p-value. Given that we have the exact data set and don't need to estimate we can
avoid this by using the ttest from stats. This also removes the possibility of
trimming data.

chore: Use ttest_ind_from_stats

---

src/sources/kubernetes_logs/mod.rs

Previously we only ever read one file per pod but this changed to
consume rotated files. We switch this to read older pod files first to
release our open handles to any rotated files and let the space be
reclaimed.

enhancement(kubernetes_logs source): Read older files first

---

src/sinks/kafka/config.rs
src/sinks/kafka/request_builder.rs
src/sinks/kafka/sink.rs
src/sinks/kafka/tests.rs
website/cue/reference/releases/0.18.0.cue

This was accidentally renamed in 9774570
We traditionally use `<field>_key` for these names so I preferred to
revert it to its old name for consistency rather than simply document
the change as breaking in 0.18.0.
Replaces #10221 

fix(kafka sink): Correct the name for the `headers_key` config option

---

lib/vector-core/src/config/id.rs
lib/vector-core/src/config/mod.rs
src/api/schema/components/mod.rs
src/api/tap.rs
src/config/graph.rs
src/config/id.rs
src/config/loading.rs
src/config/mod.rs
src/top/metrics.rs
src/topology/builder.rs
src/topology/task.rs
src/transforms/pipelines/mod.rs

The couple `ComponentKey` and `ComponentScope` have been introduced when we implemented the `Pipeline` v1. It has then be reverted but the `ComponentKey` and the `ComponentScope` stayed. It is, for now, not used for the `Pipeline` v2 feature.
Since then, all the components are using `ComponentScope::Global` and this field became useless.
This PR changes the way the `ComponentScope` is implemented and adapts it to `Pipeline` v2
Just removes the notion of scope considering it's used nowhere.
It keeps the notion of `ComponentKey` for further updates.
When creating a `Pipelines` transform, we end up with the following component ids:
- `processing.logs.filter`
- `processing.logs.pipelines.foo.filter`
- `processing.logs.pipelines.foo.transforms.0`
And, in the existing implementation, they are …

feat(config): update component key

---

src/sources/kubernetes_logs/mod.rs

This reverts commit 72067bb8eee63ea058526dd7005332503306fbaa.
This caused CI failures. Reverting to fix master and then I'll look into
the test failure.

fix(kubernetes_logs source): Revert read older files first (#10218)

---

lib/vector-core/src/metrics/mod.rs

This reverts commit 99400f0b0ec7b06080aa6a5de6c0606069070582.
This broke the k8s e2e tests.
Will be replaced by https://github.com/vectordotdev/vector/pull/10228

chore(observability): Revert remove unused alias for `events_processed_total`

---

website/cue/reference/releases/0.18.1.cue

chore: Fix cue indentation for 0.18.1 release

---

scripts/environment/bootstrap-windows-2019.ps1

Some Windows CI build are failing because OOM errors (e.g. https://github.com/vectordotdev/vector/runs/4367335521?check_suite_focus=true) 
As per https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources, runners cannot be requested with more ressources. 
And there is not much room to lower the ressource usage as runners have 2 core, hence suggesting to lower the number of parallel cargo jobs to 1.

chore(ci): lower `CARGO_BUILD_JOBS` for Windows runner

---

website/content/en/highlights/2021-10-08-0-17-upgrade-guide.md
website/cue/reference/releases/0.17.0.cue

Follow-up to https://github.com/vectordotdev/vector/pull/10228

docs(observability): Fix 0.17 note about processed_events_total metric

---

website/content/en/blog/graphql-api.md
website/content/en/docs/reference/api.md
website/content/en/highlights/2020-12-23-graphql-api.md
website/cue/reference/api.cue
website/cue/reference/urls.cue

The Vector deployment hosted at this domain was stood up manually and
never kept up-to-date. Until we can support it properly, just remove
references to the public playground and encourage users to run Vector
locally.

docs: Remove references to playground.vector.dev

---

src/sinks/loki/service.rs

Loki returns 204 for successful responses, but cLoki (a
Clickhouse-backed Loki-compatible storage) was returning 200s. They
fixed this, but I think it is reasonable to interpret any 200-level
status code as a successful publish. Prior to the sink rewrite in #9506
we were allowing any success code (due to how `HttpSource` handled
responses).
Closes: #10195

fix(loki sink): Allow any 2xx code as success

---

.github/workflows/soak.yml
soaks/bin/analyze_experiment

This commit changes a two important things. Firstly we set the p-value threshold
to 0.1 meaning changes with 90% confidence instead of 95% will be flagged. We
further expand the statistical summary table to display the confidence value,
allowing devs to understand if the result they're seeing is distinguished from
chance with, say, 91% confidence or 99%.

chore: Display confidence intervals, allow 90% as floor

---

scripts/environment/bootstrap-windows-2019.ps1

Less stupid iteration of #10235 that lowers the number of cargo jobs to half the vcpus/cores found on the system.
Edit:
CI jobs are reporting the correct number of jobs (runners are t3.2xlarge / 8 vcpu):
```
env:
AUTOINSTALL: true
AWS_ACCESS_KEY_ID: dummy
AWS_SECRET_ACCESS_KEY: dummy
CONTAINER_TOOL: docker
RUST_BACKTRACE: full
RUST_TEST_THREADS: 1
TEST_LOG: vector=debug
VERBOSE: true
CI: true
PROFILE: debug
RUSTFLAGS: -D warnings
CARGO_BUILD_JOBS: 4
SCCACHE_REDIS: ***
SCCACHE_IDLE_TIMEOUT: 0
```

chore(ci): set CARGO_BUILD_JOBS to half the number of core for Windows runners

---

website/cue/reference/components/sinks/datadog_metrics.cue

The `datadog_metrics` sink supports the "site" option, and mentions it as a non-deprecated alternative to `region`, but the option itself wasn't actually rendered on the page.

docs(datadog_metrics sink): add missing "site" documentation

---

website/assets/css/style.css
website/layouts/partials/download/download-matrix.html

Fix buttons in download matrix for Safari iOS:
- Gives button container width to allow space for buttons.
- Unsets webkit-appearance of type button 
Preview: Check in Safari, light & dark mode
- https://deploy-preview-10303--vector-project.netlify.app/download/
- https://deploy-preview-10303--vector-project.netlify.app/releases/0.18.1/

fix(css website): Fix rendering bug of download matrix in Safari

---

.github/dependabot.yml

A few are blocked right now so it'd be nice to have Dependabot be able to create more. The default is 5.

chore(ci): Bump allowed dependabot PRs

---

website/cue/reference/components/sinks/elasticsearch.cue

`normal.bulk_action` and `normal.index` do not exist. Should be `bulk.action` and `bulk.index`.

docs(elasticsearch sink): Fix deprecating messages in the cue file

---

src/sinks/influxdb/logs.rs
src/sinks/influxdb/metrics.rs
src/sinks/influxdb/mod.rs
src/sinks/sematext/metrics.rs
website/cue/reference/components/sinks/influxdb.cue
website/cue/reference/components/sinks/influxdb_logs.cue
website/cue/reference/components/sinks/influxdb_metrics.cue

The `influxdb_logs` sink hard-encoded `metric_type=log` tag in the influxdb line protocol, e.g.
```
req,host=example.com,metric_type=logs count=42,bytes=64 1572642947000000000
```
The tag is nothing special in the inflxudb protocol. Yet it was not possible to remove the tag, even by encoding rule `encoding.except_fields=["metric_type"]`.
The sink actually is general enough to sink any kind of event, other than just logs. So it is preferable to allow exclude the tag. See #7183 .
* Apply `metric_type` as a general tag in the influxdb_line_protocol; 
* Internally insert `metric_type` **before** applying encoding rules, so to allow exclude the tag.
```
cargo test --lib  -- sinks::influxdb
test result: ok. 43 passed; 0 failed; 0 ignored; 0 measured; 1287 filtered out; finished in 3.13s
``` …

chore(influxdb_logs sink): Allow to exclude `metric_type` tag

---

.github/workflows/soak.yml
soaks/bin/analyze_experiment
soaks/bin/detect_regressions

When we initially build the soak testing infrastructure we didn't consider that
some configurations of vector would be so erratic that their baseline /
comparison differences would always be statistically distinct. It turns out, we
have two. This commit adds a mechanism to avoid alerting on these erratic
configurations and sets syslog_loki, http_to_http_ack as the first two known
erratic soaks.
This is an important signal for how vector behaves, so adding an erratic soak
should not be done lightly. What this means in practice is our users can't rely
on vector's stablility for these two configurations.

chore: Avoid dinging PRs on erratic soaks

---

lib/vector-core/Cargo.toml
lib/vector-core/buffers/src/disk_v2/tests/mod.rs
lib/vector-core/buffers/src/disk_v2/tests/size_limits.rs

This fixes (hopefully) two main issues:
- some breakage in `lib/vector-core` due to a missing feature flag on the `prost` dependency
- a flaky test in `disk_v2::tests::size_limits` that was checking if a certain task was woken, which can be inherently flaky due to the indeterminate nature of async functions that have real dependencies on systems resources (like we do by using `tokio::fs::File`)

chore(buffers): try and make disk_v2 tests more reliable

---

rfcs/2021-11-12-9811-vrl-vm.md

Ref #9811 
[Readable version](https://github.com/vectordotdev/vector/blob/stephen/vrl_bytecode_rfc/rfcs/2021-11-12-9811-vrl-vm.md)

chore: add VRL VM RFC

---

website/cue/reference/components/sources/logstash.cue

Fix the indent. The description is shown as a code block because of the problematic indent.

docs(logstash source): Fix output timestamp description

---

lib/vector-core/buffers/src/disk_v2/tests/size_limits.rs

CI uncovered another indeterministic area of one of the disk buffer v2 unit tests.  This PR tries to better handle that indeterminism.

fix(buffers): try and fix another flaky assertion in disk v2 tests

---

website/cue/reference/configuration.cue

There was [some concern in
dokku](https://github.com/dokku/dokku/issues/4971) that it might contain
other files necessary for Vector operation and so couldn't safely be
mounted over for containers.

docs: Clarify that `/etc/vector` just includes configuration

---

website/cue/reference/components/transforms/aws_ec2_metadata.cue

We've seen customers have issues with Aggregator nodes over-writing log tags if this transform is enabled. This will at least note to people that this isn't a desirable configuration, or to know what they're getting into.
Better verbiage is very welcome.

docs: Add a warning about Aggregator metadata

---

src/sinks/loki/integration_tests.rs
src/test_util/mod.rs

This PR removes the randomness from the loki sink integration tests, following [this comment](https://github.com/vectordotdev/vector/pull/9506#discussion_r724404068) from @blt.
> Stochastic testing is absolutely useful but I'd prefer if we were going to do it we do it right with proptest. I'm happy to help with that. My concern with just having a random stream like we have here is we have no ability to reproduce errors in CI.
Fixes #9799.

chore(loki sink): remove randomness in integration tests

---

lib/vector-core/src/stream/driver.rs
src/internal_events/splunk_hec.rs
src/sinks/splunk_hec/logs/encoder.rs
src/sinks/splunk_hec/metrics/encoder.rs
src/sinks/splunk_hec/metrics/sink.rs
website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md
website/cue/reference/components/sinks/splunk_hec_logs.cue
website/cue/reference/components/sources/internal_metrics.cue

Closes #10349 
Todo:
Following up on instrumentation-related feedback in #10135, this PR:
- Removes the `SplunkEventSent` event. This event was emitted in the wrong place, and `EventsSent` is already emitted by the driver.
- Removes `encode_errors_total` metric to avoid redundancy.
- Updates `SplunkInvalidMetricReceived` to adhere to component error spec.
- Updates the sink `Driver` to emit `EventsSent` only on successful event status

chore(splunk_hec sink): Update splunk_hec sink instrumentation

---

src/sinks/blackhole/config.rs
src/sinks/blackhole/mod.rs
src/sinks/blackhole/sink.rs

closes #9453 
This was mostly just re-formatting the code a bit (splitting into files) and adding the standard metrics.
This is one of the most simple sinks we have, and it behaves a bit different, so I don't see much benefit in bringing in a lot of the common code such as the Driver.

chore(blackhole sink): rewrite blackhole sink in the new style

---

docs/CONTRIBUTING.md
docs/DEPRECATION.md

I used the following as examples when developing this policy:
* https://kubernetes.io/docs/reference/using-api/deprecation-policy/
* https://docs.gitlab.com/ee/administration/package_information/deprecation_policy.html

docs(releasing): Add deprecation policy

---

Cargo.lock
Cargo.toml
lib/vector-api-client/graphql/schema.json
lib/vector-core/Cargo.toml
src/api/schema/events/mod.rs
src/api/schema/health.rs
src/api/schema/metrics/mod.rs
src/api/schema/relay.rs
src/api/server.rs

Bumps `async-graphql` to 3.0.15.

chore(deps): Bump `async-graphql` to 3.0.15

---

src/sources/internal_logs.rs

I previously introduced this functionality to enrich internal logs with
pid and hostname, but accidentally _only_ applied it to buffered events.
All internal logs after start-up were then missing these tags.
I refactored the event handling to be unified accross buffered and
subscribed events to make it less likely this issue would crop in the
future where we only modify one.
Fixes: #10403

fix(internal_logs source): Associate pid and hostname with all logs

---

.cargo/config

The changes introduced in 7f8e41c0 (chore(dev): Have clippy catch debug
statements (#10125)) caused cargo to use different `rustflags` between
runs of `cargo clippy` and all other builds. This ended up causing
running `cargo clippy` to clear cached data for the other builds and
vice versa, resulting in some check cycles taking longer than necessary.
Since these flags are just defines, they can be turned on for all
targets, eliminating the problem.

chore(dev): Avoid unnecessary cargo check/clippy rebuilds

---

Cargo.lock
Cargo.toml
lib/vrl/tests/Cargo.toml
lib/vrl/tests/src/main.rs
src/lib.rs

Pushing this up to see what our new soak tests say about it, motivated
https://github.com/vectordotdev/vector/issues/7842#issuecomment-993648690
This reverts commit 3979d3a1bf3ff4a31761f84c006147169b9e1072.

enhancement(performance): Consider jemalloc again

---

scripts/environment/bootstrap-ubuntu-20.04.sh

This mirrors the change made for Windows: https://github.com/vectordotdev/vector/pull/10250
We've been seeing a number of failed benchmark runs recently which seem
to be related to rustc being OOM-killed. This is an experiment to see if
it reduces or eliminates these. A more long term idea might be to split up the
benchmark compilation and running steps. During compilation we typically
need more memory. During running we want compute optimized to match
what users will typically be running under.

chore(ci): Reduce CI cargo jobs to nproc / 2

---

scripts/setup_integration/prometheus_integration_env.sh

2.32.0 seems to have introduced an incompatible change as Vector no
longer recieves events via `prometheus_remote_write`.
I'll open a separate issue to investigate this.

fix(ci): Pin prometheus to 2.31.0

---

Cargo.lock
Cargo.toml
lib/vrl/tests/Cargo.toml
lib/vrl/tests/src/main.rs
src/lib.rs

This is breaking Windows tests because the allocator seemingly isn't being
correctly feature flagged for some reason. I will merge it again as https://github.com/vectordotdev/vector/pull/10459
I missed the Windows failure in the PR because I thought it was the transient benchmark failure that was blocking merge.
This reverts commit 5fe1767d3a0b847cfacc855b44164b03574d51a8.

enhancement(performance): Revert jemalloc (#10443)

---

Cargo.lock
Cargo.toml
Makefile
lib/vrl/tests/Cargo.toml
lib/vrl/tests/src/main.rs
src/lib.rs

This seems to be more actively maintained, is at a newer jemalloc
version, and is [what Rust
uses](https://github.com/rust-lang/rust/commit/3965773ae7743e051070b4eed3c6e02e9df3b25c).

chore(performance): Switch jemalloc crate to tikv_jemallocator

---

.github/workflows/soak.yml

Rely on Github Actions matrix rather than duplicating the jobs.

chore(ci): Refactor soak repliacs

---

lib/vector-core/buffers/benches/sized_records.rs
lib/vector-core/buffers/src/buffer_usage_data.rs
lib/vector-core/buffers/src/config.rs
lib/vector-core/buffers/src/disk/leveldb_buffer/mod.rs
lib/vector-core/buffers/src/disk/leveldb_buffer/reader.rs
lib/vector-core/buffers/src/disk/leveldb_buffer/writer.rs
lib/vector-core/buffers/src/disk/mod.rs
lib/vector-core/buffers/src/disk_v2/ledger.rs
lib/vector-core/buffers/src/disk_v2/mod.rs
lib/vector-core/buffers/src/disk_v2/reader.rs
lib/vector-core/buffers/src/disk_v2/tests/acknowledgements.rs
lib/vector-core/buffers/src/disk_v2/tests/mod.rs
lib/vector-core/buffers/src/internal_events.rs
lib/vector-core/buffers/src/test/common/variant.rs
lib/vector-core/buffers/src/test/model/on_disk_v1.rs
lib/vector-core/buffers/src/test/model/on_disk_v2.rs
lib/vector-core/buffers/src/topology/builder.rs
lib/vector-core/buffers/src/topology/channel/receiver.rs
lib/vector-core/buffers/src/topology/channel/sender.rs
lib/vector-core/buffers/src/topology/test_util.rs
lib/vector-core/buffers/src/variant/disk_v1.rs
lib/vector-core/buffers/src/variant/disk_v2.rs
lib/vector-core/buffers/src/variant/in_memory_v1.rs
lib/vector-core/buffers/src/variant/in_memory_v2.rs
src/app.rs

This PR accomplishes two main things:
- fixes the usage of `BufferUsageHandle` for both `BufferSender`/`BufferReceiver` and in internally instrumented cases (i.e. the disk buffer v1 code)
- adds a warning message when using `disk_v2`
The warning message is mostly meant to discourage people from using `disk_v2` since it's not ready for prime time yet while still allowing it to be used during testing, soak testing, etc, without a bunch of feature flag changes that slow down the development cycle.
I hand-checked the output of `memory`, `memory_v2`, and `disk_v1`, in terms of metrics, going to Datadog, and all of them report both sent/received metrics and in the right order (i.e. received represents events into the buffer, and sent represents events out of the buffer).
Closes #10426.

fix(buffers): update buffer metrics correctly + disk_v2 warning

---

lib/vector-core/src/stream/partitioned_batcher.rs

closes #10485 
The partitioned batcher could in some cases `poll()` the underlying stream after it was closed. The source stream is now wrapped in a `Fuse` to prevent the double `poll()`.

fix(sinks): fuse stream in partitioned batcher

---

README.md

Fluent Bit 1.7.0 has introduced multi-threading support. See https://github.com/fluent/fluent-bit/issues/1567.

chore: update Fluent Bit status in readme

---

.github/workflows/soak.yml

Rather than always using `master`. This can be useful when basing PRs
off of other PRs.

chore(ci): Use PR base for soak comparisons

---

website/cue/reference/releases.cue
website/cue/reference/releases/0.18.0.cue

I migrated the 0.18.0.cue release file as an example (though I didn't go
back and try to dig up all of the relevant pull requests to add the
numbers; we can do this moving forward).
Assuming we are on-board with this change, I think next steps would be:
* Update the website to render the changelog if it exists
* Remove the changelog from 0.18.0 description since it'll now be
rendered from the structured data
* Backport structured changelog data for previous releases (optional?
Maybe we just do the last few?)
* Remove commit list from releases and instead link to Github diff
* Update `scripts/release-prepare` to output the log file for reference
to create the structured changelog list, but not use it to generate
the commit list automatically

docs: Add cue schema for structured release changelogs

---

soaks/soak.sh

This commit changes the local soak runner to, by default, run all soak tests and
if --soak is specified to run only those experiments listed. This resolves
PR #10497.

chore: Allow local soak runner to run one, some or all soaks

---

src/codecs/mod.rs
src/codecs/ready_frames.rs
src/sources/fluent/mod.rs
src/sources/logstash.rs
src/sources/socket/tcp.rs
src/sources/statsd/mod.rs
src/sources/syslog.rs
src/sources/util/tcp.rs
src/sources/vector/v1.rs

This came out of some strange soak test behavior in #10432. Essentially, we had reduced the change down to what should have been insignificant performance-wise (roughly, one additional allocation per batch via `ready_chunks` vs `enqueued`), but were still seeing a ~10% penalty on certain soaks.
The theory was that for those tests to be so hyper-sensitive to the performance of `send_all`, they must be heavily bottlenecked by it. Given that it's not supposed to be a method that things should bottleneck on, I looked into why that might be. They all were based on the `TcpSource` trait and utilized our new codec work to implement their respective protocols. 
The interesting bit ended up being roughly [here](https://github.com/vectordotdev/vector/blob/21e252598300e0777ca412f0ae72e36b3dd3b1fb/src …

fix: actually batch TCP source decoder outputs

---

website/cue/reference/releases.cue
website/cue/reference/releases/0.18.0.cue
website/layouts/releases/single.html

This adds basic rendering of changelogs and known issues from release
cue data and removes the old changelog generation.
It does not render scopes or PR tags as I couldn't get those looking
pretty, but I'll open a follow-up issue for that.
Closes part of https://github.com/vectordotdev/vector/issues/10522

docs: Basic release changelog rendering

---

soaks/tests/fluent_elasticsearch/terraform/vector.toml

Soak test was using deprecated ES config, which broke once those deprecated fields were removed.

fix(tests): migrate ES soak test config

---

soaks/soak.sh

This commit makes a small adjustment to the local soak runner to allow for
soaking to continue if one run fails. This can happen, for instance, if we go
backward in time far enough and a bit of configuration is not properly supported
in an older version of vector.

chore: Continue to soak in the presence of failures

---

src/sinks/vector/mod.rs
src/sources/vector/mod.rs
website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md

Require users to specify the version to prompt them to upgrade as part
of the deprecation, and eventual removal, of the `v1` protocol.

enhancement!(vector source, vector sink): Remove default for version

---

lib/k8s-e2e-tests/src/lib.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
lib/k8s-e2e-tests/tests/vector.rs
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/vector.rs
scripts/deploy-chart-test.sh

Reverts vectordotdev/vector#10521
Appears to be causing CI failures. Reverting so we can re-open as a PR to investigate.
https://github.com/vectordotdev/vector/actions/runs/1608811257

fix(ci): Revert update k8s-e2e to use new helm chart

---

src/codecs/framing/character_delimited.rs
src/codecs/framing/newline_delimited.rs

Previously it would return `Ok(None)` when a frame longer than
`max_length` was encountered, but the `tokio_codec::Decoder#decode` trait method specifies:
> If an entire frame is available, then this instance will remove those bytes from the buffer provided and return them as a decoded frame. Note that removing bytes from the provided buffer doesn't always necessarily copy the bytes, so this should be an efficient operation in most circumstances.
>
> If the bytes look valid, but a frame isn't fully available yet, then Ok(None) is returned. This indicates to the Framed instance that it needs to read some more bytes before calling this method again.
>
> Note that the bytes provided may be empty. If a previous call to decode consumed all the bytes in the buffer then decode will be called …

fix(codecs): Fix framing handling of long frames

---

website/cue/reference.cue
website/cue/reference/components/sources.cue

Companion PR to https://github.com/vectordotdev/vector/pull/10570 which
updates the framing implementation to only accept a byte rather than
a, possibly, multi-byte character.

docs(codecs): Document that character delimited codec only accepts a byte

---

benches/codecs/character_delimited_bytes.rs
benches/languages.rs
src/codecs/framing/character_delimited.rs
src/codecs/framing/newline_delimited.rs
src/sources/aws_s3/sqs.rs
src/sources/journald.rs

This commit converts the delimiter to byte from char. In some instances a char
can be multi-bytes wide, meaning that it's possible for the current algorithm to
split a delimiter as it forwards in the underlying buffer. The implementation
assumes that we want single-byte delimiters, which is now the case.
Resolves #10569

chore: Convert delimiter to byte

---

Makefile
benches/languages.rs

Previously `language` was excluded because it required WASM which caused
other tests to fail on OSX, but we dropped WASM support so we can test
the rest. The `codecs` benches are new.

fix(ci): Test additional bench suites

---

lib/vector-core/Cargo.toml

Required for `extensions` method on `SpanRef`

fix(ci): Enable std feature for tracing-subscriber

---

.github/workflows/k8s_e2e.yml
lib/k8s-e2e-tests/src/lib.rs
lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-e2e-tests/tests/vector-aggregator.rs
lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs
lib/k8s-e2e-tests/tests/vector.rs
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/vector.rs
scripts/ci-setup-minikube.sh
scripts/deploy-chart-test.sh

Reverts vectordotdev/vector#10566
Re-introduces for debugging.

chore(ci): Re-update k8s-e2e to use new helm chart

---

.github/workflows/nightly.yml

This action only supports Linux. We'll need to handle Windows
differently though, at least so far, we haven't run into disk space
issues there.

fix(ci): Remove clean step from Windows nightly

---

website/cue/reference/releases/0.19.0.cue

docs: Escape \ more in 0.19.0 release changelog

---

Cargo.lock
Cargo.toml

chore(releasing): Bump Cargo.toml version to 0.20.0

---

website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md

This was renamed to `default_token`.
Closes: #10610

docs: Document deprecation of `token` for Splunk HEC sinks

---

lib/vector-core/src/event/finalization.rs

The `EventFinalizers` wrapper type was created with an immutable array
(`Box<[T]>`) under the assumption that the size of this array would tend
to be small, and so the space savings from eliminating the extra
`capacity` word would outweigh the performance loss from occasionally
copying the array when needed to enlarge it.
However, batches collect the finalizers from their events into an
`EventFinalizers` set, which can result in an array with thousands of
entries. This causes O(N^2) behavior when growing the array, resulting
in a significant performance drops when acknowledgements are turned on.
This enhancement switches out the underlying type for a plain `Vec` to
amortize that growth behavior.
Ref #10543

chore(performance): Speed up handling larger arrays of finalizers

---

Makefile

Following [this request](https://github.com/vectordotdev/vector/pull/10601#issuecomment-1002662184) from @jszwedko to add `AUTODESPAWN` back and refactoring the makefile to remove duplication for integration tests.

chore(ci): refactor makefile integration tests command

---

lib/vrl/stdlib/src/parse_klog.rs
lib/vrl/stdlib/src/parse_linux_authorization.rs
lib/vrl/stdlib/src/parse_syslog.rs
website/cue/reference/remap/functions/parse_klog.cue
website/cue/reference/remap/functions/parse_linux_authorization.cue

This PR fixes the [new year](https://github.com/vectordotdev/vector/runs/4688623472?check_suite_focus=true) bug by increasing the year from 2021 to 2022 in static strings.

fix(tests): increase year in docs

---

docs/content/en/docs/setup/quickstart.md

The docs currently suggest installing Vector using the easy install script seen elsewhere in the docs. This PR adds a second Docker installation option.

enhancement(external docs): Add Docker installation option to quickstart

---

rfcs/2021-11-05-9930-native-event-encoding.md

[Rendered](https://github.com/vectordotdev/vector/blob/ff8147bd1c3e74494c7e1a4c6e0dd2261b16554b/rfcs/2021-11-05-9930-native-event-encoding.md)

chore(rfc): native event encoding RFC

---

docs/specs/component.md

Adds an `output` property to the `EventsSent` event for components with multiple possible outputs. Relevant metrics can then be tagged with the appropriate output.

docs(internal docs): Update component spec for multiple outputs

---

src/config/unit_test/mod.rs
src/config/validation.rs
src/transforms/route.rs

This PR refactors `route` to use the new system of multiple outputs rather than macro expansion.
Based off #10640

chore(route transform): Use multiple outputs for route

---

.github/workflows/integration-test.yml
Makefile
scripts/integration/docker-compose.docker.yml

Following #10466, this PR moves the docker tests to use docker-compose
on the CI.

chore(tests): migrate docker integration tests

---

rfcs/2021-10-29-8621-framing-and-codecs-sinks.md

Closes #8621.
[Rendered version 👀.](https://github.com/vectordotdev/vector/blob/pablosichert/framing-and-codecs-sinks-rfc/rfcs/2021-10-29-8621-framing-and-codecs-sinks.md)

chore(codecs): Add RFC for "Framing and Codecs - Sinks"

---

distribution/install.sh

Closes #10740
This fixes the case on Alpine where the `ldd --version` output is on STDERR, as well as Ubuntu where "GNU" is not included in the `ldd --version` output.
Also included is a minor change to fix linebreaks when adding Vector to the user's path.
Before:
```bash
>>> Unpacking archive to /root/.vector ... ✓
>>> Adding Vector path to /root/.zprofile>>> Adding Vector path to /root/.profile ✓
>>> Install succeeded! 🚀
```
After:
```bash
>>> Unpacking archive to /root/.vector ... ✓
>>> Adding Vector path to /root/.zprofile  ✓
>>> Adding Vector path to /root/.profile  ✓
>>> Install succeeded! 🚀
```
Ubuntu 20.04.3
```bash
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc. …
```

fix(setup): Fix get_gnu_musl_glibc function

---

lib/vector-core/src/event/metric.rs
src/sinks/prometheus/exporter.rs
src/sources/prometheus/remote_write.rs

#10741 was accidentally merged before CI checks completed, which lead to some issues being merged into `master`.  This PR fixes those issues.

fix(prometheus_exporter sink): lint/fmt/clippy issues due to a bad merge

---

.github/workflows/integration-test.yml
Makefile
scripts/integration/docker-compose.fluent.yml

Following #10466, this PR moves the fluent tests to use docker-compose on the CI

chore(tests): migrate fluent integration test

---

.github/workflows/integration-test.yml
Makefile
scripts/integration/docker-compose.datadog-metrics.yml

Following #10466, this PR moves the datadog-metrics tests to use docker-compose on the CI.

chore(tests): migrate datadog-metrics integration tests

---

src/source_sender/mod.rs
src/sources/datadog/agent/mod.rs
src/sources/datadog/agent/tests.rs
website/cue/reference/components/sources/datadog_agent.cue

Small change that leverage named outputs:
With this config
```
sources:
dd_agent:
type: datadog_agent
address: "[::]:8081"
multiple_outputs: true
```
Metrics & Logs can then respectively be received using `dd_agent.logs` & `dd_agent.metrics`.

enhancement(datadog_agent source): add an option to route metrics and logs to different outputs

---

website/content/en/blog/kubernetes-integration.md
website/content/en/docs/administration/monitoring.md
website/content/en/docs/setup/installation/platforms/kubernetes.md
website/cue/reference/components.cue
website/cue/reference/components/sources/kubernetes_logs.cue
website/cue/reference/components/transforms/geoip.cue
website/cue/reference/components/transforms/remap.cue
website/cue/reference/components/transforms/route.cue
website/layouts/docs/component.html
website/layouts/partials/data.html

Closes #10615
This PR adds support for documenting named outputs for transforms in `cue`. Namely, we capture the notion of a `default_output` (for the majority of transforms) and `named_outputs` (for  `remap`, `route`). The `default_output` can be empty for transforms like `route`.
- Renamed `Output` section to `Output Data` for clarity
- Included some minor frontend changes to render this new data but happy to revert these changes and save them for later. I was mainly curious to make sure everything was working end-to-end, so it's not terribly pretty.

docs: Add component outputs as structured cue data

---

Cargo.lock
lib/vector-core/buffers/Cargo.toml

As noted in https://github.com/vectordotdev/vector/pull/10786#issuecomment-1010389063 this appears to be unused at this point

chore: Remove lading_common dependency

---

src/codecs/framing/character_delimited.rs
src/serde.rs

fix(codecs): Handle `framing.character_delimiter.delimiter` as `char` in config serialization

---

deny.toml

No available fix yet.
https://github.com/vectordotdev/vector/issues/10862

chore(ci): Ignore dashmap unsoundness for now

---

.github/audit.yml

This opens an issue like: https://github.com/tokio-rs/tracing/issues/1834 . We currently open these sorts of issues manually (like #10862).
We could consider dropping the `cargo deny` check that happens in, and
blocks, PRs as part of this. It's currently a bit of a nuisance when
a new vulnerability shows up because this causes all new PRs to fail
even though they if they aren't changing anything about dependencies
until it is fixed in master. The risk is that PRs that do change
dependencies introduce a security vulnerability which would be nice to
catch on the PR itself.
We can start with this new workflow and evaluating the removal, or
softening, of the `cargo deny` check on PRs.

chore(ci): Add a workflow for opening issues for security vulnerabilities

---

src/api/schema/events/log.rs
src/api/schema/events/mod.rs
src/api/schema/events/notification.rs
src/api/schema/events/output.rs
src/api/schema/mod.rs
src/api/tap.rs
src/cli.rs
src/sources/demo_logs.rs
src/tap/mod.rs
src/topology/test/backpressure.rs
website/cue/reference/cli.cue

The `TapSink` had it's own internal buffer that it saved events to. This buffer would only be flushed when `poll_flush` was called on this sink. An unrelated change to the topology / pipelines changed how events were sent to this sink, and it was no longer being flushed correctly.
The buffer inside of `TapSink` was actually unnecessary, and removing that fixes the problem. Instead of saving to a buffer and then flushing the buffer, `TapSink` now just writes directly to the output. The batching is still correctly applied since the channel that `TapSink` writes to has its buffer appropriately set, and all the real timing / batching happens in `create_events_stream`.
Regression tests were also added to make sure this doesn't break in the future.
closes …

fix(graphql api): Fix `TapSink` not flushing properly

---

src/internal_events/route.rs
src/transforms/route.rs
website/content/en/highlights/2022-02-08-0-20-0-upgrade-guide.md
website/cue/reference/components/sources/internal_metrics.cue
website/cue/reference/components/transforms/route.cue

Following up on #10738, this PR 
- Adds an `output` tag to route's `events_discarded_total` metric to preserve part of the UX of the previous expansion implementation.
- Adds a section to the upgrade guide for route metrics under breaking changes

chore(route transform): Add output tag to route event discarded metric

---

lib/vector-core/buffers/Cargo.toml
lib/vector-core/buffers/src/disk_v2/mod.rs
lib/vector-core/buffers/src/disk_v2/reader.rs
lib/vector-core/buffers/src/disk_v2/tests/invariants.rs
lib/vector-core/buffers/src/disk_v2/tests/known_errors.rs
lib/vector-core/buffers/src/disk_v2/tests/mod.rs
lib/vector-core/buffers/src/disk_v2/tests/record.rs
lib/vector-core/buffers/src/disk_v2/writer.rs

Back again with more inscrutable code changes!  Just kidding... I think.
This PR addresses two specific corner cases with the disk buffer v2:
- when a reader encounters a data file with a partially-written record at the end
- when a writer tries to skip an invalid data file and the next data file already exists
It also improves our acknowledgement logic by fixing an issue with acknowledging records that were part of a corrupted data file.
The first scenario is pretty straight-forward: for whatever reason, either due to a bug in the code or maybe a legitimate issue with the OS/filesystem/disk, we could potentially do a partial write for a record.  The reader currently expects that if there's even a single byte that it can read, the rest of it must be coming, and so it dutifully awaits, …

fix(buffers): detect partially written data file + wait on writer/reader file lap

---

Cargo.lock
Cargo.toml
lib/vector-core/Cargo.toml

Reverts vectordotdev/vector#10896
It seems like the PR checks don't require the cross-builds to pass.
Causing failures on master: https://github.com/vectordotdev/vector/runs/4858991297?check_suite_focus=true

revert(deps): bump mlua from 0.7.1 to 0.7.2

---

src/source_sender/errors.rs
src/source_sender/mod.rs

This started as an experiment to batch the communication between `source_sender::Inner` and the `Fanout` in the matching pump task, but that ran into a few complications (mostly buffer sizing). As part of that issue, I dug into channel implementations a bit more and learned that the `futures` channel uses a linked list implementation that does a heap allocation per item, while `tokio` channels use a linked list of blocks to amortize the cost of allocation. That sounded similar enough to the original goal of batching to try running through the soaks and see how much it gets us.

chore(performance): try tokio mpsc for SourceSender

---

.github/workflows/soak_infra.yml

But don't push. This'll let us validate PRs modifying the soak infra
don't break the image builds.
Follow up to https://github.com/vectordotdev/vector/pull/10810#discussion_r785233720

chore(ci): Build soak image for PRs

---

website/cue/reference.cue
website/cue/reference/components/transforms/reduce.cue
website/layouts/partials/data.html

I don't super love this but I think it does help to clarify the standard vs. shorthand distinction by providing full-fledged config examples.

enhancement(external docs): Add condition config examples

---

lib/vector-buffers/benches/common.rs
lib/vector-buffers/examples/buffer_perf.rs
lib/vector-buffers/src/disk_v2/reader.rs
lib/vector-buffers/src/disk_v2/tests/mod.rs
lib/vector-buffers/src/disk_v2/writer.rs
lib/vector-buffers/src/encoding.rs
lib/vector-buffers/src/lib.rs
lib/vector-buffers/src/test/common/message.rs
lib/vector-buffers/src/topology/test_util.rs
lib/vector-core/src/event/mod.rs

The `EncodeBytes` and `DecodeBytes` traits are parameterized over the
type implementing the trait. That type parameter is redundant and
implied by implementing a trait, so it can be removed with no semantic
changes.

chore(buffers): Simplify encode/decode traits

---

Cross.toml

We may or may not end up using these, but it is useful for users that
want to build Vector for another platform with a different page size.
Ref: https://github.com/vectordotdev/vector/issues/4392

chore(platforms): Pass through jemalloc page size env vars

---

rfcs/2022--01-06-8596-tcp-source-backpressure.md

[rendered](https://github.com/vectordotdev/vector/blob/5cde356653d84d931dd0f7e98d7779f2f99fcfcc/rfcs/2022--01-06-8596-tcp-source-backpressure.md)

chore(sources): tcp source backpressure RFC

---

lib/vector-core/src/transform/mod.rs
src/config/builder.rs
src/topology/builder.rs
tests/topology.rs

Fixes #10806
This is a fresh and clean version of #10899, which should hopefully give cleaner soak results. Also included is a new topology test that fails if either the source-side fix or the transform-side fix are removed.
The transform fix is a simple `flush` call after draining the whole buffer, which _shouldn't_ have a large performance impact because:
1. Flushing is a no-op for in-memory buffers, which all the soaks use
2. The buffer that's drained before flushing contains the results from a whole batch of events (up to 1024 for concurrent execution, 128 for inline), so when we're under load the call should be pretty effectively amortized.
The source fix is to switch from a feed loop to the `forward` method, which also _shouldn't_ have a large perf impact because:
1. Again, flushing …

fix(topology): ensure fanout is flushed on idle

---

lib/datadog/grok/src/filters/keyvalue.rs
lib/datadog/grok/src/parse_grok.rs

`keyvalue` filter in `parse_groks` function should support nested paths as keys.
For example,
```
parse_groks("db.name=my_db,db.operation=insert", 
patterns: ["%{data::keyvalue}"] 
)
```
=> 
```
{
"db" : {
"name" : "my_db",
"operation" : "insert",
}
}
```

fix(vrl): support nested paths in `keyvalue` filter for `parse_groks`

---

lib/datadog/grok/src/matchers/date.rs
lib/datadog/grok/src/parse_grok.rs

We need to support `d` and `y` shorthands in `date` matcher of `parse_groks` function:
```
parse_groks("Nov 16 2020 13:41:29 GMT", 
patterns: ["%{date("MMM d y HH:mm:ss z"):field}"] 
)
```
=> 1605534089000

fix(vrl): support `d` and `y` shorthands in `date` matcher of `parse_groks` function

---

Cargo.lock

Resolves https://rustsec.org/advisories/RUSTSEC-2022-0006

chore(deps): Update thread_local to 1.1.4

---

lib/datadog/grok/src/grok_filter.rs
lib/datadog/grok/src/parse_grok.rs
lib/vrl/stdlib/src/parse_groks.rs

`parse_groks` should return integers instead of floats whenever lossless conversion is possible.

fix(vrl): convert floats to integers when possible in `parse_groks`

---

src/api/tap.rs

This PR fixes a flakey test for `vector tap` on multiple outputs. Kudos to @spencergilbert for pointing this out.
- Previously, we were generating a total of `400` events from the two `demo_logs` sources involved in the test but only collecting a maximum of `100` events to assert on. We need to assert on events originating from both sources, but all `100` events could have come from a single source. This change guarantees that we end up collecting events from both sources.

chore(api): Fix flakey vector tap test

---

benches/lua.rs
benches/transform/dedupe.rs
benches/transform/reduce.rs
lib/vector-core/src/event/array.rs
lib/vector-core/src/transform/mod.rs
lib/vector-core/src/transform/runtime_transform/mod.rs
src/sources/kubernetes_logs/transform_utils/optional.rs
src/topology/builder.rs
src/transforms/aggregate.rs
src/transforms/aws_ec2_metadata.rs
src/transforms/dedupe.rs
src/transforms/lua/v1/mod.rs
src/transforms/lua/v2/mod.rs
src/transforms/merge.rs
src/transforms/reduce/mod.rs
src/transforms/tag_cardinality_limit.rs
src/transforms/throttle.rs

This is just surfacing the initial dumb code that converts events into single-element arrays and back for task transforms. More work on this path is coming but touches a lot more components so I wanted to get an idea of the impact of this minimal step forward.
Closes #10864

chore(transforms): Set up task transforms to accept event arrays

---

soaks/bin/plot_analysis

This adds a histogram plot to the soak test artifacts.
I tried to plot it all on one image using `plt.subplots` but wasn't able
to get that working (`lmplot` seems to assume it is the only plot).
Instead I create one image per plot and have each experiment have its
own subdirectory in the specified captures directory.
I had to add `reset_index()` to resolve
https://github.com/mwaskom/seaborn/issues/2515 but, disclaimer, I have no
idea why that works.

chore(performance): Add histogram to soak test artifacts

---

src/sinks/vector/mod.rs
src/sources/vector/mod.rs
website/content/en/highlights/2022-02-08-0-20-0-upgrade-guide.md

This takes the next step in the migration to version 2 of the protocol
used by the `vector` source and sink. The final step will be removing
the deprecated version 1 in a future release.

chore(vector source, vector sink): Default to version 2

---

website/cue/reference/components/sinks/elasticsearch.cue

This won't stop the site from rendering things like `bulk: null` but removes options that are no longer valid

fix(external docs): Remove documented elasticsearch sink options that were removed from code

---

.github/workflows/soak.yml
soaks/bin/analyze_experiment
soaks/bin/detect_erratic
soaks/bin/detect_regressions
soaks/common/terraform/modules/monitoring/observer.tf
soaks/common/terraform/modules/vector/main.tf
soaks/tests/splunk_hec_indexer_ack_blackhole/terraform/main.tf
soaks/tests/splunk_hec_to_splunk_hec_logs_acks/terraform/main.tf
soaks/tests/splunk_hec_to_splunk_hec_logs_noack/terraform/main.tf

This commit introduces a mechanism to automatically flag newly erratic
tests and signal when previously erratic tests no longer are. The
basic insight here is that experiments with very high coefficient of
variation are unlikely to produce consistent results. The flakey
results I have examined are all a result of variation within the
standard deviation of these experiments. We now flag a small handful
of soaks as 'erratic' and have a mechanism in place to signal when
they have improved, if other experiments become erratic.
There will need to be a follow-up bit of work to understand why vector
in these configurations displays such a high CoV but that is outside
the scope of this changeset.
Closes #10606 
REF #10626 

chore: Automatically detect erratic tests, un-erratic

---

website/content/en/highlights/2021-08-24-vector-source-sink.md
website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md

These options are not supported by version 2.

docs(vector source, vector sink): Document unsupported version 2 options

---

rfcs/2021-11-05-9930-native-event-encoding.md

chore(rfc): spelling and grammar fixes for the native event encoding RFC

---

lib/vector-buffers/src/disk/mod.rs
testing/github-10895/config.toml
testing/github-10895/create-clean-data-directories.sh
testing/github-10895/get-and-build-vector-binaries.sh
testing/github-10895/steps.md
testing/github-10895/test-results.md

This PR slightly refactors the buffer directory name generation code for disk buffer v1, and adds a unit test to assert that it meets a particular (fixed) format, in the hopes it will catch us (me) if there's ever an unintentional change that messes with the buffer directory names in the future.
I also ran a modified subset of the tests used for #10430 to validate that the behavior between versions (old to new, new to new, etc) still look the same as a more end-to-end test that the buffer naming is not regressed as a result of this PR.
Closes #10895.

chore(buffers): harden buffer directory name generation for disk buffer v1

---

.github/workflows/soak_infra.yml
lib/soak/src/bin/observer.rs
soaks/bin/run_experiment.sh
soaks/common/terraform/modules/monitoring/observer.tf

This commit ensures that we collect a sufficient number of `bytes_written` samples
from the underlying experiment. In some cases -- such as when minikube restarts
pods -- we can see collection blink out for a time. Previously we collected for a fixed time, 
meaning that we would lose sample opportunities. With this change we expose ourselves
to unbounded time runs if a soak test is buggy. The `observer` now logs somewhat
differently.
I have also bumped the total samples collected back to 200 from 60. This was an accidental
change. 

chore: Ensure we collect at least 200 `bytes_written` samples

---

src/internal_events/kafka.rs
src/sources/kafka.rs
website/cue/reference/components/sources/kafka.cue

Update `KafkaEventsReceived`, add `BytesReceived` and `StreamClosedError`.
closes #10069

enhancement(kafka source): comply with component spec

---

Cargo.lock
Cargo.toml
lib/file-source/Cargo.toml
lib/k8s-e2e-tests/Cargo.toml
lib/k8s-test-framework/Cargo.toml
lib/soak/Cargo.toml
lib/vector-api-client/Cargo.toml
lib/vector-buffers/Cargo.toml
lib/vector-core/Cargo.toml

Opening as a separate PR from https://github.com/vectordotdev/vector/pull/11075 because I'm curious to see the soaks which dependabot PRs do not run.

chore(deps): Upgrade tokio to 1.16.1

---

lib/vector-buffers/src/disk_v2/reader.rs
lib/vector-buffers/src/disk_v2/tests/basic.rs

This PR addresses a flaky test related to the disk buffer v2 code.  Simply put, these tests make real file I/O calls that are asynchronous, and so we can sometimes get a number of wakeups that doesn't fully match what we expect when thinking about the code as being otherwise run/driven in a sequential fashion.
We've simply removed a needless check here, because while it would be nice to say definitively that this code is waiting, and only waiting, on some specific primitive... we're already asserting that with `tracing-fluent-assertions`: the wake status isn't _necessary_ to prove that.
We've also cleaned up the logic in the reader that checks if the buffer is actually done and the reader should return.  We had an extra check that was compensating for previously deficient logic, but never …

chore(buffers): fix flaky test in disk buffer v2

---

rfcs/2021-12-20-10517-llvm-backend-for-vrl.md

Closes #10517.
[Rendered version 👀.](https://github.com/vectordotdev/vector/blob/pablosichert/llvm-backend-for-vrl-rfc/rfcs/2021-12-20-10517-llvm-backend-for-vrl.md)
Some preliminary results from my local machine (executing the script 1M times each):
```
.hostname = "vector"
if .status == "warning" {
.thing = upcase(.hostname)
} else if .status == "notice" {
.thung = downcase(.hostname)
} else {
.nong = upcase(.hostname)
}
.matches = { "name": .message, "num": "2" }
```
Traverse: `1.653175s`
VM: `715.790583ms`
LLVM: `608.121458ms`
----
```
.foo = string("hi!")
```
Traverse: `248.525166ms`
VM: `102.147416ms`
LLVM: `41.894708ms`
----
```
.key = "foo"
```
Traverse: `275.768333ms`
VM: `57.462375ms`
LLVM: `33.156291ms`
----
```
.num = 123
```
Traverse: `270.735291ms`
VM: `43.291541ms`
LLVM: …

chore(performance,vrl): Add RFC for "LLVM Backend for VRL"

---

tests/tcp.rs

I'm really not sure why this works, but it appears to fix the issue we
saw with this test starting to fail on Linux after the upgrade to Tokio
1.16.1.
I'm guessing this is due to the multi-threaded scheduler changes mentioned here: https://github.com/tokio-rs/tokio/pull/4383

fix(tests): Use one more thread for merge_and_fork test

---

lib/vrl/compiler/src/value/arithmetic.rs
lib/vrl/tests/tests/expressions/arithmetic/multiplication/string_integer.vrl

Closes #11105 
This fixes VRL so it no longer panics when you multiply a string by a negative number. Now it defaults to multiplying that number by 0 (ie returns an empty string).
I haven't updated the documentation as it seems multiplying strings is undocumented anyway (https://vector.dev/docs/reference/vrl/expressions/#arithmetic-example-multiplication-int).
I need this fix because the fuzz testing I am doing for the VM keeps bumping up against it.

fix(vrl): multiplying negative numbers by string returns an empty string

---

.github/workflows/k8s_e2e.yml
website/content/en/docs/setup/installation/platforms/kubernetes.md
website/cue/reference/components/sources/kubernetes_logs.cue
website/cue/reference/services/kubernetes.cue

To include newer versions. I dropped the versions no longer supported by
GCP, AWS, and Azure as a proxy for general cloud k8s support.

chore(ci): Bump the k8s versions we test against

---

.github/workflows/nightly.yml
.github/workflows/release.yml

Drop EOL distributions. This was prompted because the mirrors for Centos
8 no longer exist.
https://www.centos.org/centos-linux-eol/

fix(releasing): Update rpm tests

---

Cargo.lock
Cargo.toml
scripts/integration/docker-compose.aws.yml
src/transforms/aws_ec2_metadata.rs

This PR aims to solve a tricky and yet-fully-explained issue with the `aws_ec2_metadata` transform where it will randomly lock up and completely stall whichever pipeline it is used within after some random amount of time.  This was reported in #11064.
Frankly, I'm still not entirely sure why it happens, but I've taken the initial step of trying to at least remove the possibly of the stdlib `RwLock` playing a part by perhaps silently becoming poisoned and/or messing things up with Tokio.  This is accomplished by using `arc-swap` which utilizes no locks on the read or write path.
I've also switched some values over to `Cow<'static, str>` while in the file, just to save some wasted allocations that occur in the refresh metadata logic when there is no namespace configured.
Signed-off-by: Toby …

fix(aws_ec2_metadata transform): try to fix random lockup

---

lib/vector-buffers/src/buffer_usage_data.rs
lib/vector-buffers/src/disk_v2/tests/acknowledgements.rs
lib/vector-buffers/src/disk_v2/tests/mod.rs
lib/vector-buffers/src/topology/builder.rs
lib/vector-buffers/src/topology/channel/sender.rs
lib/vector-buffers/src/topology/channel/tests.rs
lib/vector-buffers/src/topology/test_util.rs
lib/vector-common/Cargo.toml
lib/vector-common/src/internal_event/bytes_sent.rs
lib/vector-common/src/internal_event/events_received.rs
lib/vector-common/src/internal_event/events_sent.rs
lib/vector-common/src/lib.rs

As described in the title, this PR fixes an issue where events that were dropped in DropNewest mode were also counted as having been sent to the buffer, which would lead to incorrect buffer metrics over time.
I also tweaked the use of `tracing` in `vector-common` to make it a non-optional crate, as well as skipping the extern import and requiring direct `use tracing::...` statements to bring clarity to what was being used and how it was being imported.  The only reason I touched this code in particular was that the `tracing` dependency was set to optional which meant things broke if you were pulling the crate in without also setting certain feature flags, and `vector-buffers` was not setting those flags... because they're entirely unrelated to what `vector-buffers` needs out of the crate. …

fix(buffers): fix buffer metrics when using DropNewest

---

lib/datadog/grok/build.rs

This commit juggles where we read in grok patterns above the lalrpop
rerun-if-changed directive. Previously we would only rebuild our patterns file
if src/parser.lalrpop changed, which results in odd build issues for people with
unclean trees.

chore: Ensure we always build grok patterns

---

src/topology/builder.rs

I'm starting to experiment with the removal of `Sink` implementation for
`Fanout` for #10144. My in-flight work is starting to sprawl uncomfortably so
this is a small patch to remove reliance on one of the related `Sink` traits.

chore: Avoid the use of SinkExt in src/topology/builder.rs

---

src/api/tap.rs

This PR fixes a still-flakey `vector tap` integration test for multiple outputs which I'd seen fail in unrelated PRs (e.g. [here](https://github.com/vectordotdev/vector/runs/5008576376?check_suite_focus=true#step:8:3181)). 
Based on the error message in those failures, I think this test currently fails because of the following scenario and is a timing issue.
- One of the `demo_log` sources, but not both, sends an event which makes its way to the task in `create_events_stream`. It's stored away.
- Before the other event can arrive, the `interval` in the `create_events_stream` task ticks and the single stored event is sent into the stream.
- We expect this next payload to include both events, so our assertion fails.
This change accounts for the fact that we might see a third tap payload …

chore(api): Fix flakey vector tap integration test

---

src/sinks/util/encoding/fixed.rs
src/sinks/util/encoding/mod.rs
src/sinks/util/encoding/with_default.rs

`EncodingConfigFixed` was missing the custom deserialization bits we
have for the other encoding config implementations.
Fixes: #11196

fix(codecs): Fix deserialization of `only_fields` for fixed encodings

---

src/codecs/decoding/format/bytes.rs
src/codecs/decoding/format/json.rs
src/codecs/decoding/format/syslog.rs
src/codecs/decoding/framing/bytes.rs
src/codecs/decoding/framing/character_delimited.rs
src/codecs/decoding/framing/length_delimited.rs
src/codecs/decoding/framing/mod.rs
src/codecs/decoding/framing/newline_delimited.rs
src/codecs/decoding/framing/octet_counting.rs
src/codecs/decoding/mod.rs
src/serde.rs
src/sources/aws_kinesis_firehose/mod.rs
src/sources/aws_sqs/config.rs
src/sources/datadog/agent/mod.rs
src/sources/datadog/agent/tests.rs
src/sources/demo_logs.rs
src/sources/exec/mod.rs
src/sources/heroku_logs.rs
src/sources/http.rs
src/sources/kafka.rs
src/sources/nats.rs
src/sources/socket/mod.rs
src/sources/socket/tcp.rs
src/sources/socket/udp.rs
src/sources/socket/unix.rs
src/sources/statsd/mod.rs
src/sources/statsd/unix.rs
src/sources/stdin.rs
src/sources/syslog.rs
src/sources/vector/v1.rs

We'll be doing the same for the encoding side, which is necessary to eventually infer the HTTP content type from the encoding configuration.

chore(codecs): Use `enum` delegation when decoding rather than dynamic dispatch

---

src/codecs/encoding/format/json.rs
src/codecs/encoding/format/raw_message.rs
src/codecs/encoding/framing/character_delimited.rs
src/codecs/encoding/framing/mod.rs
src/codecs/encoding/framing/newline_delimited.rs
src/codecs/encoding/mod.rs
src/sinks/util/encoding/adapter.rs

This is a prerequisite for inferring the HTTP content type from the encoding configuration.

chore(codecs): Use `enum` delegation when encoding rather than dynamic dispatch

---

website/content/en/docs/setup/installation/package-managers/helm.md
website/content/en/docs/setup/installation/platforms/kubernetes.md

Aggregator was misspelled as aggragator in a couple of places.

docs(external docs): fixed aggragator spelling

---

scripts/environment/prepare.sh

It looks like the latest version of `markdownlint` doesn't work with NodeJS version 10.19.0, which is the version provided by apt for ubuntu 20.04. - https://github.com/igorshubovych/markdownlint-cli/issues/258
This fixes the markdownlint-cli version to 0.30, which does work.
This should not be a long term solution!

chore(ci): fix markdownlint-cli to version 0.30.

---

lib/vector-buffers/benches/common.rs
lib/vector-buffers/examples/buffer_perf.rs
lib/vector-buffers/src/disk_v2/tests/known_errors.rs
lib/vector-buffers/src/disk_v2/tests/mod.rs
lib/vector-buffers/src/lib.rs
lib/vector-buffers/src/test/common/message.rs
lib/vector-core/src/event/mod.rs

This will be used by future changes to the disk buffer to deal with
event arrays, which may have more than one event per record.

chore(core): Add a `EventCount` trait to bufferable types

---

docs/specs/component.md

This metric should not be incremented for events that will be
reprocessed by a source or sink, only if the events were discarded in
a way that they would be lost.

chore(internal docs): Clarify `component_discarded_events_total`

---

lib/vector-core/src/event/metric.rs
src/sinks/prometheus/collector.rs

In https://github.com/vectordotdev/vector/pull/10741 we introduced logic
to normalize distributions into aggregated histograms to avoid holding
onto the samples forever. However, the conversion created "cummulative
buckets" which were then accumulated again in the `prometheus_exporter`
sink.
The rest of the code seems to expect that aggregated histograms, in
Vector, have discrete, rather than cummulative, buckets (e.g.
https://github.com/vectordotdev/vector/blob/0ba0d97f5dd116e37b369f3adc755d53ab74d936/lib/vector-core/src/metrics/ddsketch.rs#L596-L601),
so this fixes the conversion to create discrete buckets.
Also removes handling of distributions in the collector since they've
already been normalized.
Closes: #11180

fix(metrics): Fix conversion of distribution to aggregated histogram

---

deny.toml

chore(deps): Remove ignore for RUSTSEC-2022-0002

---

src/internal_events/ansi_stripper.rs
src/transforms/ansi_stripper.rs

Rename all existing errors to end with `Error`
Refers https://github.com/vectordotdev/vector/issues/11217

enhancement(transforms ansi_tripper): updates to comply with component spec

---

src/internal_events/aws_cloudwatch_logs_subscription_parser.rs
src/internal_events/aws_ec2_metadata.rs
src/transforms/aws_cloudwatch_logs_subscription_parser.rs
src/transforms/aws_ec2_metadata.rs

Rename all existing errors to end with Error
Refers https://github.com/vectordotdev/vector/issues/11217

enhancement(transforms): updates aws_* to comply with component spec

---

src/topology/builder.rs

We were neglecting to propagate the span so any events generated by the
transform were missing tags.
Fixes: #11240

fix(observability): Propagate concurrent transform spans

---

src/internal_events/template.rs
src/sinks/aws_cloudwatch_logs/mod.rs
src/sinks/aws_cloudwatch_logs/request_builder.rs
src/sinks/aws_sqs.rs
src/sinks/elasticsearch/config.rs
src/sinks/elasticsearch/mod.rs
src/sinks/file/mod.rs
src/sinks/gcp/stackdriver_logs.rs
src/sinks/logdna.rs
src/sinks/loki/sink.rs
src/sinks/nats.rs
src/sinks/papertrail.rs
src/sinks/prometheus/remote_write.rs
src/sinks/redis.rs
src/sinks/splunk_hec/common/util.rs
src/sinks/util/partitioner.rs
src/transforms/add_fields.rs
src/transforms/log_to_metric.rs
src/transforms/throttle.rs

Rename `TemplateRenderingFailed` to `TemplateRenderingError` which touches many components.
Note: we don't need to add `EventsReceived` and `EventsSent` in the transforms because it's handled at the topology level [here](https://github.com/vectordotdev/vector/blob/master/src/topology/builder.rs#L669) and [here](https://github.com/vectordotdev/vector/blob/master/src/topology/builder.rs#L678)
Refers #11217

enhancement(transforms add_fields): updates to comply with component spec

---

Cargo.lock
deny.toml
src/expiring_hash_map.rs

This reverts a commit to bump tokio-util from 0.6.8 to 0.6.9 (#9938)
since this introduced behavior where Vector would stop processing if the
incoming data couldn't be parsed by the codec.
This reverts commit d6ace26a214f61f33b5063f45333e9765befd2f3.
Closes: #11245

fix(codecs): continue on error

---

lib/datadog/grok/Cargo.toml
lib/vrl/cli/Cargo.toml

Our grok crate is unusual. We use regex in certain places like date parsing and
onig when dealing with the grok patterns themselves. Work on #11206 strongly
suggests that if sinks are allowed to run less subject to slow receiver issue
then `apply_date_filter` is a CPU hotspot. As suggested by @tobz we enable the
'perf' flags to the regex crate, which features heavily in the implementation of
that function.
REF #10144

chore: Add 'perf' feature flag on regex crate

---

src/internal_events/internal_logs.rs
src/sources/internal_logs.rs

As mentioned by @jszwedko, a new `BytesReceived` event is emitted

enhancement(internal_logs source): add missing BytesReceived

---

website/layouts/shortcodes/tabs.html

- Fixes long list of tabs overflowing the container
Updated HTML
- tabs shortcode flex container now raps, tweaking spacing logic
Tabs container with a long list of tabs should wrap to the next line. 
- https://deploy-preview-11259--vector-project.netlify.app/docs/reference/configuration/#automatic-namespacing

fix: Tabs Wrap, Not Overflow (website)

---

lib/vector-common/src/encode_key_value.rs
lib/vector-common/src/encode_logfmt.rs
lib/vrl/stdlib/src/encode_key_value.rs
src/sinks/loki/integration_tests.rs
src/sinks/loki/sink.rs

There doesn't seem to be a real reason it needs an owned version. Cloning the keys as needed, to flatten the map, should result in less copying. I think we could probably even remove that clone if we used a different data structure to store the keys.
Removes a clone that would be needed in https://github.com/vectordotdev/vector/pull/11234

chore(codecs): Have encode_logfmt take the `BTreeMap` by reference

---

Cargo.lock
Cargo.toml
deny.toml
distribution/install.sh
lib/shared/Cargo.toml
lib/vector-core/buffers/src/buffer_usage_data.rs
lib/vector-core/buffers/src/disk_v2/tests/acknowledgements.rs
lib/vector-core/buffers/src/disk_v2/tests/mod.rs
lib/vector-core/buffers/src/topology/builder.rs
lib/vector-core/buffers/src/topology/channel/sender.rs
lib/vector-core/buffers/src/topology/channel/tests.rs
lib/vector-core/buffers/src/topology/test_util.rs
lib/vector-core/core-common/src/internal_event/bytes_sent.rs
lib/vector-core/core-common/src/internal_event/events_received.rs
lib/vector-core/core-common/src/internal_event/events_sent.rs
lib/vector-core/core-common/src/lib.rs
scripts/check-version.rb
src/expiring_hash_map.rs
src/sinks/util/encoding/fixed.rs
src/sinks/util/encoding/mod.rs
src/sinks/util/encoding/with_default.rs
src/topology/builder.rs
website/content/en/releases/0.19.2.md
website/cue/reference/releases/0.18.0.cue
website/cue/reference/releases/0.19.0.cue
website/cue/reference/releases/0.19.2.cue
website/cue/reference/versions.cue

Backports regression fixes from v0.20.
It's best to review the individual commits, in particular the last one prepping the release; the rest are cherry-picked.

chore(releasing): Prepare v0.19.2

---

lib/vector-api-client/graphql/schema.json
lib/vector-api-client/src/gql/tap.rs
src/api/schema/events/encoding.rs
src/api/schema/events/log.rs
src/api/schema/events/metric.rs
src/tap/mod.rs

~~Opening as draft for now as this is stacked on #11201~~
Closes #6854 
This PR allows specifying `--format logfmt` in `vector tap` to change the event output format.
For the following config:
```toml
[api]
enabled = true
[sources.in]
type = "demo_logs"
format = "shuffle"
lines = [
"test1",
"test2",
]
[sources.internal_metrics]
type = "internal_metrics"
[sinks.out]
inputs = ["in*"]
```
running `vector tap -f logfmt "in" "internal_metrics"` will show log events like
```
message=test1 source_type=demo_logs timestamp=2022-02-07T23:44:56.690520215Z
```
and metric events like
```
counter.value=26 kind=absolute name=events_out_total namespace=vector tags.component_id=in tags.component_kind=source tags.component_name=in tags.component_type=demo_logs tags.output=_default …
```

enhancement(api): Support logfmt formatting option in vector tap

---

soaks/bin/detect_regressions

In the analysis script we are interested in the absolute magnitude of any mean
swing. That is not the case in detect_regressions, where we only care for
negative movements. The logic was inappropriately moved from the one script to
the other, now fixed. Regressions will no longer be flagged for _positive_
changes, only negative.

chore: Correct detect_regressions drift filter bug

---

soaks/bin/run_experiment.sh

We are seeing in practice that `http_pipelines_blackhole` soak is misbehaving,
queuing up our soak runners. We do not want soak tests to run indefinitely in
the even they've gone sideways. This commit caps sample collection attempts to
1000 periods, no matter how many samples have been collected.

chore: Timebound soak experimental runs

---

Cargo.lock
lib/vector-common/Cargo.toml
lib/vector-common/src/conversion.rs
lib/vector-common/src/conversion/tests/mod.rs
lib/vector-common/src/conversion/tests/unix.rs
lib/vector-core/src/event/discriminant.rs
lib/vector-core/src/event/legacy_lookup/mod.rs
lib/vector-core/src/event/lua/value.rs
lib/vector-core/src/event/proto.rs
lib/vector-core/src/event/test/common.rs
lib/vector-core/src/event/value.rs
lib/vector-core/src/mapping/parser/mod.rs
lib/vector-core/src/mapping/query/arithmetic.rs
lib/vector-datadog-filter/src/filter.rs
src/conditions/check_fields.rs
src/config/unit_test/mod.rs
src/sinks/influxdb/logs.rs
src/sinks/new_relic/model.rs
src/sinks/new_relic/tests.rs
src/sources/fluent/message.rs
src/transforms/add_fields.rs
src/transforms/logfmt_parser.rs
src/transforms/lua/v1/mod.rs
src/transforms/lua/v2/mod.rs
src/transforms/reduce/merge_strategy.rs
src/transforms/regex_parser.rs
src/transforms/split.rs
src/transforms/tokenizer.rs

This is part 1 in a series of PR's to unify the Vector and VRL Value types.
The VRL Value::Float requires all values to be NotNan. This PR adds that requirement to the Vector Value type.
The From<f64> was kept for testing purposes, but is only included for tests. Everywhere else now handles possible NaN values and converts them to NotNan first.
Note: This PR was cherry-picked from the original one (https://github.com/vectordotdev/vector/pull/11271)

chore(core): Value unification part 1 - NotNan floats

---

lib/vector-core/src/event/discriminant.rs
lib/vector-core/src/event/lua/value.rs
lib/vector-core/src/event/mod.rs
lib/vector-core/src/event/proto.rs
lib/vector-core/src/event/value.rs
lib/vector-core/src/event/value_regex.rs
src/transforms/dedupe.rs
src/transforms/reduce/merge_strategy.rs

This is part 2 in a series of PR's to unify the Vector and VRL Value types.
The VRL Value has a Regex variant, and the Vector Value does not. The behavior for converting between the 2 types when a Regex is involved is already well defined today, it is simply converted to the Bytes variant. This PR adds a Regex variant to the Vector Value. Whenever it is accessed, it behaves the exact same as it did before.

chore(core): Value unification part 2 - Regex

---

src/sinks/util/encoding/mod.rs

Fixes: https://github.com/vectordotdev/vector/pull/11198#issuecomment-1034789883

fix(codecs): Fix deserialization of `only_fields` in YAML for fixed encodings

---

.github/workflows/environment.yml

The nightly and release workflows are currently failing because they are
using a cached version of `timberio/ci_image:latest`. I'd like to update
the Makefile and scripts to use a specific tag, but we need to start
tagging them first. This adds that scaffolding.

chore(ci): Tag environment images

---

Cargo.toml
src/api/handler.rs
src/api/server.rs
src/app.rs
src/topology/running.rs
tests/shutdown.rs

Adds an Arc wrapped AtomicBool for the `stop` function from `RunningTopology` to use. The health handler references this new field to determine if a response is 200 or 503.
Initial work from health check RFC before larger task described in https://github.com/vectordotdev/vector/issues/10555

feat(api): Allow health endpoint to return 503s when Vector is shutting down

---

docs/specs/component.md

Prompted by discussion in
https://github.com/vectordotdev/vector/pull/11223#discussion_r801890688

chore(internal docs): Clarify `error` tag in component spec

---

Cargo.toml
src/config/compiler.rs
src/config/mod.rs
src/config/unit_test/mod.rs
src/config/unit_test/tests.rs
website/content/en/highlights/2022-02-08-0-20-0-upgrade-guide.md
website/cue/reference/releases/0.20.0.cue

Closes #11338
This PR adds informative error messages at unit test build time when non-existent targets are specified in `extract_from` and `no_outputs_from`, avoiding a panic. Note, when any build errors occur, no tests are run.
For the example described in #11338, you'll now see the following output:
```
Failed to build test 'crash':
Invalid extract_from target in test 'crash': transform 'parse-ssyslog' does not exist
```

fix(unit tests): Error on non-existent extract_from, no_outputs_from targets

---

scripts/check-docs.sh

`cat` doesn't support `-A` in the stock macos command line tools, but `-et` is equivalent on both mac and Linux

chore(external docs): Fix `check-docs.sh` compatibility with MacOS

---

src/conditions/check_fields.rs
src/conditions/datadog_search.rs
src/conditions/is_log.rs
src/conditions/is_metric.rs
src/conditions/mod.rs
src/conditions/not.rs
src/conditions/vrl.rs
src/config/unit_test/mod.rs
src/config/unit_test/unit_test_components.rs
src/transforms/filter.rs
src/transforms/reduce/mod.rs
src/transforms/route.rs
src/transforms/sample.rs
src/transforms/throttle.rs

This commit removes the notion of `Box<dyn Condition>` from the code base, using
a Big Old Enum approach instead. This is suggested by the work on #10144 where
Condition always ranks highly in on-cpu/off-cpu measures. It is hoped but not
known that removing dynamic dispatch in this hotspot will have a measurable
bump on condition heavy configurations, of which pipeline is a notable
instance.
This is roughly similar to the approach seen in #11200 but in a different area.

chore: Remove dynamic dispatch in Conditions

---

src/config/unit_test/mod.rs
src/config/unit_test/unit_test_components.rs

Closes #11335
This PR adjusts the unit test internals to avoid emitting warnings for unconsumed component outputs (emitted during topology building). While these warnings don't impact test execution/results, they are confusing to users.
For the example in #11335, output used to show
```zsh
Running tests
2022-02-11T21:20:40.274345Z  WARN vector::config::builder: Transform "log_event_router.bar" has no consumers
test test__1 ... passed
```
and is now
```zsh
Running tests
test test__1 ... passed
```

chore(unit tests): Avoid warning logs for unconsumed outputs

---

src/source_sender/mod.rs
src/sources/splunk_hec/mod.rs
src/sources/util/http/prelude.rs

Previously this was done in a streaming fashion, where a single internal
event was emitted with each individual event built. Now we build and
collect all the events, and emit one internal event describing the
total. This also lets us remove the awkward `send_result_stream` method
from `SourceSender`, of which this was the only caller.

chore(performance): emit splunk_hec metrics per request

---

website/cue/reference/components/sources/prometheus_scrape.cue

Signed-off-by: Ali Reza Yahya <ali.reza.yahya@wolt.com>
fix typo on warning docs on prometheus_scrape

docs: fix prometheus_scrape warnings typo

---

src/config/unit_test/unit_test_components.rs
src/source_sender/mod.rs
src/sources/apache_metrics/mod.rs
src/sources/aws_ecs_metrics/mod.rs
src/sources/aws_s3/sqs.rs
src/sources/aws_sqs/source.rs
src/sources/demo_logs.rs
src/sources/docker_logs.rs
src/sources/eventstoredb_metrics/mod.rs
src/sources/file.rs
src/sources/host_metrics/mod.rs
src/sources/internal_metrics.rs
src/sources/journald.rs
src/sources/kafka.rs
src/sources/kubernetes_logs/mod.rs
src/sources/mongodb_metrics/mod.rs
src/sources/nats.rs
src/sources/nginx_metrics/mod.rs
src/sources/postgresql_metrics.rs
src/sources/prometheus/scrape.rs
src/sources/socket/udp.rs
src/sources/stdin.rs
src/sources/syslog.rs
src/sources/util/framestream.rs
src/sources/util/unix_datagram.rs
src/sources/util/unix_stream.rs
src/sources/vector/v2.rs
tests/support/mod.rs
tests/topology.rs

This is a bit of an scatter shot batch of changes to update sources to send specific event types (ie `LogEvent` or `Metric`) into `SourceSender` to help with future event array conversion.
Closes #11350

chore(sources): Send specific event types into `SourceSender`

---

src/internal_events/json_parser.rs

`value` is the literal string that could not be parsed as JSON which
will result in this tag having infinite cardinality as well as very
awkward metric tags.

fix(json_parser transform): Remove `value` tag from metrics

---

lib/vector-api-client/graphql/schema.json
lib/vector-api-client/graphql/subscriptions/received_events_throughput.graphql
lib/vector-api-client/graphql/subscriptions/received_events_total.graphql
lib/vector-api-client/graphql/subscriptions/sent_events_throughput.graphql
lib/vector-api-client/graphql/subscriptions/sent_events_total.graphql
lib/vector-api-client/src/gql/metrics.rs
src/api/schema/metrics/events_in.rs
src/api/schema/metrics/events_out.rs
src/api/schema/metrics/mod.rs
website/content/en/highlights/2022-03-22-0-21-0-upgrade-guide.md

Ref #11263
This PR removes the following already deprecated subscriptions (deprecated as of #9300, #9313)
- `eventsInTotal`: use `componentReceivedEventsTotals`
- `eventsOutTotal`: use `componentSentEventsTotals`
- `componentEventsInThroughputs`: use `componentReceivedEventsThroughputs`
- `componentEventsInTotals`: use `componentReceivedEventsTotals`
- `componentEventsOutThroughputs`: use `componentSentEventsThroughputs`
- `componentEventsOutTotals`: use `componentSentEventsTotals`
- `eventsInThroughput`: use `componentReceivedEventsThroughputs`
- `eventsOutThroughput`: use `componentSentEventsThroughputs`
and deprecates the following subscriptions
- `receivedEventsTotal`: use `componentReceivedEventsTotals`
- `sentEventsTotal`: use `componentSentEventsTotals`
- `sentEventsThroughput`: …

chore(api): Remove deprecated subscriptions and deprecate unnecessary subscriptions

---

website/content/en/highlights/2021-12-28-0-19-0-upgrade-guide.md
website/cue/reference/components/sinks/splunk_hec.cue
website/cue/reference/urls.cue

Closes #11387 
This PR updates the `0.19.0` upgrade guide and `How It Works` section of the `splunk_hec sink` docs to highlight the channel behavior in `splunk_hec` sinks introduced alongside indexer acknowledgements work.

chore(splunk_hec sink): Update upgrade guide and docs with Splunk channel behavior

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

While creating an issue, I discovered that the form creates redundant
headers for the community note. This cleans that up.

chore: Improve issue template community note

---

website/content/en/highlights/2021-08-24-vector-source-sink.md

The inaccuracies in the timeline were pointed out by https://github.com/vectordotdev/vector/discussions/11399

docs: Update vector source/sink highlight timeline

---

src/transforms/pipelines/expander.rs
src/transforms/pipelines/mod.rs

We were explicitly prohibiting this which is is blocking https://github.com/vectordotdev/vector/pull/11407
I think it's useful to be able to run without transforms while
developing or debugging Vector configurations (e.g. commenting out
transforms).
I could see us having a "strict" mode in Vector in the future that would
prohibit things like this, but I think this change is in-line with
Vector's other behavior of starting with configurations that users
probably wouldn't want to run in production (like sources that are not
consumed).

chore(pipelines transform): Allow empty pipelines

---

soaks/bin/analyze_experiment

This:
* Adds `confidence` as a column to the detail table. Nathan mentioned
this is easier to scan than the p-values and I agree.
* Removes the stderr columns from the summary table. I don't think this
information is needed there. People generally just want to see the
change in mean and confidence.

chore(ci): Re-order soak results

---

soaks/bin/run_experiment.sh

It's pretty noisy and I'm curious if we still need it cc/ @blt.

chore(ci): Remove xtrace from soaks/bin/run_experiment

---

src/internal_events/open.rs

The Windows builds are breaking with:
```
error: associated function is never used: `any_open`
--> src\internal_events\open.rs:46:12
|
46 |     pub fn any_open(&self) -> bool {
|            ^^^^^^^^
|
= note: `-D dead-code` implied by `-D warnings`
```
This hopefully fixes it.

fix(ci): add unix flag to `any_open`.

---

website/content/en/guides/level-up/transformation.md

Should of been part of f0f71de28447dc716fc1dd0eac3f2681f61c0f3f

docs: we have just one Runtime transform now

---

src/topology/schema.rs

This adds a wrapper around `merged_definition` that caches the result of merging schema definitions from the same set of inputs (which guarantees that the cached combination of pipelines is always the same).
This resolves an issue with recursive merging exploding in complexity – and thus runtime – for configurations that have a lot of cross-dependency pipelines (not the feature), which can happen in cases where a config is using pipelines (the feature) with many components involved.
Specifically, this resolves the issue of the `pipelines` soaks timing out because it took too long to boot Vector.

chore(schemas): add cache to recursive schema definition merging

---

.github/workflows/soak.yml
soaks/README.md
soaks/bin/soak_one.sh
soaks/soak.sh

Since contributor PRs do not have write access to the GH registry, instead just store them in artifacts to pass them between jobs.
I thought maybe this would slow the build down due to the lack of image layer caching in the registry, but we didn't seem to be taking advantage of that anyway at the moment.

chore: Avoid using registry for soak images

---

src/topology/builder.rs
src/topology/mod.rs
src/topology/task.rs
src/topology/test/backpressure.rs

This PR is a [`retypist`](https://github.com/blt/retypist) run on `src/topology`. The intention is to make review, manual intervention more approachable compared to #11393.

chore: [retypist] `src/topology`

---

src/internal_events/socket.rs

Fix the emitted metric that was left to one when switching from processing one by one to processing events by batches.
closes #11468
Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>

fix(socket source): emit metric with good count for tcp

---

.github/dependabot.yml

Just noticed this when checking the time Dependabot is supposed to run.

chore: Remove unused dependabot reviewers and assignees

---

Makefile

The latest version of `make` on OSX:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0
```
Seems to have been taking the first rule that matches, which was
`test-integration-%`. This re-orders them so that the cleanup target
matches first.

chore: Fix cleanup make target

---

src/sources/docker_logs.rs

I didn't find a way to reproduce the bug but this kind of error seems to block the event stream. Returning should kill the component and force vector to stop/restart.
Maybe we should add a system of autorestart and not create the event stream while building the component. That way we could handle this case by just restarting the source itself.
Fixes [OBPS-1](https://datadoghq.atlassian.net/browse/OBPS-1)

fix(docker_logs source): break source when reader fails deserializing

---

src/dns.rs
src/lib.rs
src/utilization.rs

This commit makes `deny(unreachable_pub)` the default in the project, allowing
for carve-outs for large sections of the tree. This is consistent with my
background work recently to reduce the exposed interface of vector. I now have
specific areas to aim retypist at and we scope growth of the problem to only a
subset of the tree.
This flag does not apply to any sub-crates.

chore: Add a global deny unreachable_pub, with carve outs

---

src/internal_events/filter.rs
src/transforms/filter.rs

This commit -- part of the ongoing work to improve #10144 -- batches up our
emission code in `transforms/filter.rs` so we don't pay the cost of emission on
every `Event` that passes through.
This commit is a WIP. As noted in a comment a slow sender might never see the
metric emitted based on the current approach.

chore: Batch filter transform emissions

---

.github/workflows/soak.yml
.github/workflows/soak_comment.yml

The soaks were adjusted in
https://github.com/vectordotdev/vector/pull/11474 to allow outside
contributor PRs to run them, but workflows running on these PRs still
couldn't publish the comment with the soak results due to only having
read access. This commit follows the example laid out by
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
to move the PR comment posting bit to its own workflow with expanded
permissions.

fix(ci): Adjust soak workflow PR comment

---

Cargo.lock
Cargo.toml
src/sinks/nats.rs
src/sources/nats.rs

The async_nats crate was merged into the standard nats crate as a module and is no longer maintained. https://github.com/nats-io/nats.rs/pull/192
This will unblock jetstream support #10534.

chore(nats sink): Update from async_nats to nats::asynk

---

src/service.rs

Broken by unreachable_pub lint.

fix(ci): Fix Windows builds

---

src/kafka.rs
src/lib.rs
src/sink.rs
src/sinks/kafka/service.rs
src/tap/cmd.rs
src/tap/mod.rs

This commit applies unreachable_pub to a few more modules in the tree, those
easily done by hand. This commit relates to #11538 and #11547.

chore: Apply more deny unreachable_pub

---

src/sources/util/tcp/mod.rs

closes https://github.com/vectordotdev/vector/issues/11475
A request limiter was recently added to the TCP source to limit the amount of memory consumed during back-pressure. This worked by requiring a connection to hold a permit before it's allowed to read any data.
However, if there are many connections that are idle they will consume all the permits and prevent active connections from being processed correctly.
A small read timeout was added, and if a connection does not receive any data during that time it will release its permit (and try to obtain a new one) allowing other connections to read.

fix(socket source): Prevent idle connections from hoarding permits 

---

src/aws/rusoto/region.rs
website/cue/reference/components/aws.cue

This patch allows to use both the `region` and `endpoint` field for the
aws_s3 sink.
This is necessary when using a different S3 provider than AWS
since the region is derived from the endpoint and mapped against a known
map of AWS region [1], which will result in the use of the default AWS
region.
[1] https://github.com/vectordotdev/vector/blob/1d9a34e24c416501c3f6377b8400253a3ad538f6/src/aws/rusoto/region.rs#L64
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

fix(aws_s3 sink): allow the usage of `region` and `endpoint`

---

src/serde.rs

Small follow-up to https://github.com/vectordotdev/vector/pull/11232 that I forgot to include.

chore: Match capacity of `serde_json::to_vec`

---

tests/config.rs

I missed this failing check in
https://github.com/vectordotdev/vector/pull/11578 when I force merged.
I thought only the soak check was failing anomolously.

fix(tests): Fix test for `aws_s3` config

---

.github/workflows/soak_comment.yml

By default, the list methods only return 30 items. Using `paginate`
returns them all.

chore: Fix soak comment posting workflow

---

website/cue/reference/components/sinks.cue

These settings are always available on any sinks that support batching.

docs(sinks): Always render batch config options

---

src/sinks/aws_sqs.rs
src/sinks/clickhouse.rs
src/sinks/influxdb/metrics.rs
src/sinks/sematext/metrics.rs
src/sinks/util/adaptive_concurrency/tests.rs
src/sinks/util/http.rs
src/sinks/util/service.rs
src/sinks/util/sink.rs

There is only a single implementation of `trait ServiceLogic`, so inline it into its single use.
Closes #11562

chore(sinks): Inline `ServiceLogic` into batch sink framework

---

lib/vector-core/src/event/array.rs
lib/vector-core/src/event/mod.rs
lib/vector-core/src/event/proto.rs
lib/vector-core/src/event/test/common.rs
lib/vector-core/src/event/trace.rs
lib/vector-core/src/event/vrl_target.rs
src/conditions/check_fields.rs
src/sinks/util/encoding/codec.rs
src/transforms/remap.rs

The current trace event type is simply a type alias for the log event
type. This leads to silent ambiguities, particularly in the presence of
things like `impl From<LogEvent> for X`. This change converts
`TraceEvent` into a newtype wrapper for `LogEvent` to prevent that
ambiguity.

chore(core): Disambiguate `LogEvent` and `TraceEvent`

---

src/top/mod.rs
website/content/en/highlights/2022-03-22-0-21-0-upgrade-guide.md
website/cue/reference/cli.cue

This PR fixes a small bug in `vector top` wherein running `top` leads to a panic because `-h` from `--help` and `-h` from `--human_metrics` clashes. ~~I've added `--hm` as an alias for `--human_metrics`~~ since `clap` only supports shortened versions with a single character -- open to suggestions. 
Going with `-H` as the short flag for `--human_metrics`.

fix(api): Change vector top --human_metrics short flag

---

Cargo.lock
Cargo.toml
lib/vector-core/Cargo.toml
lib/vector-core/src/config/log_schema.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/metric.rs
src/sinks/vector/v1.rs
src/sources/dnstap/schema.rs
src/sources/socket/tcp.rs
src/sources/socket/udp.rs
src/sources/vector/v1.rs

The crate getset is used in only a few places in the codebase and, in most of
those, does quiet trivial things. This commit removes those spots with the
intention of teeing up a PR to remove getset entirely. We're already seeing that
builds fail on some systems because our dependency (and thus link) list is too
long, hence the desire to remove trivial dependencies where possible.

chore: Remove trivial instances of getset use

---

src/config/mod.rs
src/config/sink.rs
src/config/source.rs
src/config/transform.rs

I just got tired of paging through `src/config/mod.rs` to search for component-related config bits, so this breaks it up a bit. Zero code changes other than moves.

chore(core): Split config source into component modules

---

.github/workflows/soak.yml
.github/workflows/soak_comment.yml

`github.event.number`, which is the PR number, is not available to the
`workflow_run` workflow. The unique `run_id` is, however, so use that
instead.

chore: Use run_id rather than event number for soak artifacts

---

docs/ARCHITECTURE.md

This is just intended to be a starting point, as there's a great deal that's not yet discussed. I mostly aimed to capture the most significant bits around topology construction relevant to the recent work on concurrency, multiple outputs, etc. I also tried to include some more diagrams, but only one seemed to export and show up properly, so I'm leaving the rest to future work rather than continue wasting time with my rather poor design skills 😄

docs: add architecture.md

---

lib/vector-core/src/transform/config.rs
src/transforms/pipelines/expander.rs
src/transforms/pipelines/mod.rs
src/transforms/pipelines/router.rs

I'm going through the pipelines config code with a close eye. This commit is
consistent with my recent work to remove uncessary `pub`s from the project,
which netted us a bit of code removal.

chore: Some small `pub` changes, code removal in pipelines

---

website/cue/reference/components/sinks.cue

Was missing the () required by markdown

docs: Fix link to logfmt

---

website/content/en/docs/setup/going-to-prod/high-availability.md

This `short` metadata field seems to be used in the bread crumbs and
elsewhere and I think spelling it out is better to reduce acronym
alphabet soup.

docs: Unabbreviate High Availability

---

Cargo.lock
scripts/integration/docker-compose.datadog-agent.yml
src/sources/datadog/agent/integration_tests.rs

#11033 merge inadvertently overwrote an env var name that was recently changed in datadog integration tests.
Another merge issue related to a missing schema is also fixed.

fix(ci): Use correct env var for Datatog integration test

---

.cargo/config.toml

`[target.cfg(all)]` seems to not match anything.

chore: Fix clippy flag application

---

src/sinks/gcp/stackdriver_logs.rs

In my implementation, I'm seeing the occasional warning: `Unknown severity value string, using DEFAULT. value=er internal_log_rate_secs=10`.  Assuming I'm reading the message correctly, it's complaining as my log leve severity is the string `er`.
If I'm reading the supported grok pattern defined at https://github.com/daschl/grok/blob/master/patterns/grok.pattern#L94-L95 correctly, the pattern allows both `err` and `er`.  However, the `remap_serverity` function only allows errors starting with `err` (ignoring case).  The PR allows for `er` if the log level equals `er` (intentionally chose equivalency vs starts_with to avoid false positives).

fix(gcp_stackdriver_logs sink): Allow literal 'ER' as a log level type ERROR

---

lib/vector-core/src/fanout.rs
src/topology/running.rs
tests/topology.rs

Fixes #10412
It turns out that the fix for #9173 in #9536 was based on a misunderstanding of the underlying issue. In that commit, I noted that:
> When replacing the upstream component, the new input for the rebuilt downstream component has not yet been registered and therefore doesn't get readded to the rebuilt `Fanout`.
It's correct that the new input has not yet been registered, but it misses that the previous version of the input is still present and does get readded to the rebuilt `Fanout`. This is because we only remove existing inputs for components that are being removed from the topology entirely.
The actual issue in that case stemmed from the logic we have to reuse buffers for rebuilt sinks where the buffer config itself has not changed. To facilitate that reuse, we removed the …

fix(topology): correct fix for topology reloading around rebuilt sinks

---

src/config/datadog.rs
src/sources/host_metrics/mod.rs
src/sources/internal_metrics.rs
website/cue/reference.cue
website/cue/reference/components/sources/host_metrics.cue
website/cue/reference/components/sources/internal_metrics.cue

feat(internal_metrics source): Let scrape_interval_secs have fractional seconds

---

lib/vrl/stdlib/src/to_timestamp.rs
website/cue/reference/remap/functions/to_timestamp.cue

feat(vrl): Add configurable unit for to_timestamp

---

tests/topology.rs

This was accidentally left in the event array in topology merge

chore(tests): Fix topology test

---

.github/workflows/soak.yml

We have started to see in some soaks --
https://github.com/vectordotdev/vector/actions/runs/1936805810 -- that we are
crashing with a NaN bug deep in pandas. I am unable to replicate this locally
but have a more updated version of pandas on hand. As a first attempt I will
upgrade pandas.

chore: Correct soak NaN crash bug

---

src/transforms/route.rs

This commit is a follow-up to #11697. We don't actually need to iterate an
`IndexMap` repeatedly here as we never actually use the map capabilities of the
conditions field: a vec is enough. This is worth a small boost in the micro but
I suspect nothing in the macro.
If we are to actually optimize route we'll probably need to run multiple copies
of them, run an `EventArray` through it and/or dramatically improve the behavior
of `condition.check`.

chore: Moderately improve the micro behavior of route transform

---

src/sinks/azure_monitor_logs.rs
src/sinks/clickhouse.rs
src/sinks/gcp/pubsub.rs
src/sinks/gcp/stackdriver_logs.rs
src/sinks/gcp/stackdriver_metrics.rs
src/sinks/honeycomb.rs
src/sinks/http.rs
src/sinks/influxdb/logs.rs
src/sinks/logdna.rs
src/sinks/util/http.rs

Part of https://github.com/vectordotdev/vector/issues/11579.
Note that this does not create a new encoder for each HTTP request yet. I haven't figured out yet if it's possible to determine the end of an HTTP request from the methods in 
https://github.com/vectordotdev/vector/blob/4d2fc7572fed5dcaaab525253fc061c52d6c9f77/src/sinks/util/http.rs#L145-L198

chore: Refactor `util::http::HttpSink` to allow mutable access to `self` in `encode_event`

---

website/cue/reference/components/sinks/loki.cue

A user was confused because they tried to specify the full URL and got
a 404.

docs(loki sink): Clarify endpoint path

---

soaks/bin/analyze_experiment

This commit adds an assert to fail the analysis if a variant has no samples, as
opposed to kicking out an inexplicable exception. This probably relates to
issue #11633 and appears to impact http-to-http-noacks most frequently.

chore: Catastrophically fail if variant has no samples

---

distribution/debian/scripts/postinst

Current `postinst` script in Debian packages doesn't add vector user to the `systemd-journal-remote`.

enhancement: Add vector user to systemd-journal-remote group

---

.config/nextest.toml
.github/workflows/test.yml
Cargo.toml
Makefile
lib/file-source/Cargo.toml
lib/tracing-limit/Cargo.toml
lib/vrl/compiler/Cargo.toml
lib/vrl/stdlib/Cargo.toml
lib/vrl/vrl/Cargo.toml
scripts/environment/bootstrap-windows-2019.ps1
scripts/environment/prepare.sh

I added flakey test retrying but otherwise haven't taken advantage of any other nextest features yet. I hope to expand this to output JUnit compatible output to integrate with Datadog's CI product. Even without that integration, I think this is a worthwhile change for the flakey test behavior and improved output so I think this can safely go in first.
There are a couple of things to be aware of:
* `cargo-nextest` [doesn't support running docs tests](https://github.com/nextest-rs/nextest/issues/16) so these are split out into `make test-docs`
* `cargo-nextest` and `criterion` [don't play well yet](https://github.com/bheisler/criterion.rs/issues/562) so this PR drops testing of benches. `make check-clippy` should still ensure they compile though.
Assuming we like this, I'll expand it out to …

chore: Try out nextest in CI

---

src/sinks/util/encoding/adapter.rs
src/sinks/util/encoding/mod.rs

The `encoding::Encoder` integration PRs need to instantiate/name the `Transformer` in a couple of places.

chore: Expose `sinks::util::encoding::Transformer`

---

.github/workflows/soak_comment.yml

This should be `steps`. I'd copied over `needs` from the `soak.yml`
workflow where the pr-number was output from a different job.

chore: Fix lookup of issue number in soak comment posting

---

.github/workflows/soak.yml

These have been moved to a separate workflow, `soak_comment.yml`, so
that they are posted correctly for contributor PRs which lack the
requisite access to post from the `soak.yml` workflow.

chore: Remove redundant soak comment tasks

---

lib/lookup/src/lookup_v2/jit.rs
lib/lookup/src/lookup_v2/mod.rs
lib/value/src/value.rs
src/transforms/aws_ec2_metadata.rs

Recent changes to the path lookup started requiring special chars in field names to be escaped. Most of the fields used by the `aws_ec2_metadata` transform contain a special character. This transform also assumed that the tag name used for metric was the same value as the string lookup used to set log fields, which is no longer true. These were split so the metric tag name and path lookup are separate values. Path lookups now also use pre-parsed lookups.

fix(aws_ec2_metadata transform): fix regression from path lookup changes

---

.github/workflows/test.yml
Cargo.toml

A user in Discord was wondering what the last Vector version was that
supported 1.54 of Rust. I realized this would be easier to tell if we
started tracking it. I ran `cargo msrv` to figure out the current MSRV. We
are using the "Captured identifiers in format strings" feature from 1.58 so
that is our current MSRV.

chore: Add rust-version documenting MSRV

---

.github/workflows/soak_comment.yml

Was accidentally logging the github SDK object rather than the incoming
workflow context.

chore: Fix soak comment debug logging

---

lib/lookup/src/lookup_v2/mod.rs
src/sinks/datadog/events/request_builder.rs
src/sinks/util/encoding/adapter.rs
src/sinks/util/encoding/config.rs
src/sinks/util/encoding/fixed.rs
src/sinks/util/encoding/mod.rs
src/sinks/util/encoding/with_default.rs
src/sources/dnstap/parser.rs
src/transforms/grok_parser.rs
src/transforms/tokenizer.rs

This PR is a follow-up to https://github.com/vectordotdev/vector/pull/11198#pullrequestreview-873565962 and should fix some latent bugs within structs that have not explicitly used `deserialize_path_components` yet.  This work is done in preparation to integrate `encoding::Encoder` by using `EncodingConfigMigrator` in sinks, e.g. https://github.com/vectordotdev/vector/pull/11647.
tl;dr: Replaces
```
#[serde(deserialize_with = "deserialize_path_components")]
only_fields: Option<Vec<Vec<OwnedSegment>>>,
```
with
```
only_fields: Option<Vec<OwnedPath>>,
```

chore: Unify logic to (de)serialize `OwnedPath`s

---

src/transforms/pipelines/config.rs
src/transforms/pipelines/mod.rs

This commit is a mostly mechanical shuffle of our pipeline code, done
while investigating https://github.com/vectordotdev/vector/issues/10144. I found the previous organization
challenging to comprehend and this reads more clear to me. I've tried
to follow the section commenting style common to the rest of the
transform code.

chore: Slightly re-organize the pipeline code

---

.github/workflows/nightly.yml
.github/workflows/release.yml

Debian 8 has been EOL since June 30, 2020.

chore: release/nightly: Drop EOL Debian 8 (Jessie) and add Debian 11

---

.github/workflows/soak.yml
soaks/bin/plot_analysis
soaks/bin/plot_up

The soak observer keeps a record of every time it reaches out to Vector to
collect metrics and is unable to get a response. This is a 'down'
state. Previously we rarely saw Vector down, although now a see-saw pattern has
developed. This is a problem as Vector's health in soak is also measured by
whether it responds to metrics queries.
REF #11772

chore: Introduce 'up' plots

---

scripts/upload-test-results.sh

fix(ci): Allow test result upload to fail without failing the ci job

---

scripts/version.sh

Adding `rust-version` to `Cargo.toml` in #11754  was causing the `awk` script to match it as well.

fix(releasing): Fix version calculation

---

lib/vrl/compiler/src/value/arithmetic.rs

I noticed this diff to improve byte concatenation in some of the initial works of @StephenWakely's VM, should be generally useful for VRL as well.

chore(vrl): Optimize VRL byte concatenation

---

soaks/tests/syslog_loki/terraform/vector.toml

We should also see a performance bump with
https://github.com/vectordotdev/vector/pull/11761 which re-enables
concurrency when the out_of_order_action is `accept`.

chore: Update Loki soak to not reorder timestamps

---

soaks/bin/boot_minikube.sh
soaks/common/terraform/modules/vector/main.tf

This allows for k8s to give pods CPU affinity if they have a QOS of
Guaranteed and request a whole number of CPUs.
This PR also adds a memory limit for Vector since this is required to
receive a QOS of Guaranteed.
I discussed this with Brian and we are hoping this results in less throttling of Vector which could be causing additional soak variance.

chore: Utilize k8s static CPU manager policy for soaks

---

src/sources/journald.rs
website/cue/reference/components/sources/journald.cue

The `since_now` option is used to tell journalctl to start from now,
instead of the begining. It is useful when migrating to a new logging
stack (here vector) to not replay and resend all already collected
logs by another software.
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

feat(journald source): add a since_now option

---

.github/workflows/test.yml
Makefile

Instead of the Makefile. I think they fit better here since we should
only be uploading the reports in CI.
I split out `make test-cli` since it was uploading test results. I plan
to continue to split up the `test-misc` job to run one job per test.

chore: Move upload of test results to CI workflow

---

lib/vector-buffers/src/variants/disk_v2/tests/size_limits.rs

It is hanging in CI.
https://github.com/vectordotdev/vector/runs/5516891103?check_suite_focus=true

chore: Ignore writer_waits_when_buffer_is_full for now

---

Makefile

`docker-compose` doesn't automatically rebuild the images if the
`Dockerfile` used for the integration tests changes which was causing
some confusion about why changes weren't picked up.

chore: Rebuild integration test docker images

---

.github/workflows/test.yml
Makefile

The test times are longer because they start from a clean slate each time, but I think the trade-off is worth it to not need to maintain the custom runners. We can iterate on improving these times by:
* Doing less setup: not all jobs need all of the setup steps in the shared setup scripts
* Installing the cargo tools as binaries instead of building them on the fly

chore: Move Linux tests to GHA custom runner

---

soaks/tests/http_to_http_noack/README.md
soaks/tests/http_to_http_noack/terraform/main.tf
soaks/tests/http_to_http_noack/terraform/variables.tf
soaks/tests/http_to_http_noack/terraform/vector.toml

Ref #11633 
This soak was removed (#11717) as part of investigating the lock up issue in #11633 which is now resolved.

chore: Restore http-to-http-noack soak

---

Cargo.lock
Cargo.toml
lib/vector-buffers/src/topology/channel/sender.rs
lib/vector-buffers/src/topology/channel/tests.rs

This PR addresses a subtle issue with the new buffer topology code when it comes to running a buffer in the `DropNewest` mode.
At a high level, we use a wrapper type around Tokio's bounded MPSC channels, `PollSender`, that allows us to provide the necessary `Sink` interface that wires up into `BufferSender` and higher in the stack.  Under the hood, `tokio::sync::mpsc::Sender` uses a semaphore -- Tokio's own `tokio::sync::Semaphore` -- to handle managing capacity, specifically in the case of the sender knowing when it can send into the channel.
As part of Tokio's goal of providing deterministic executor latencies, they have a feature called "cooperative scheduling", where Tokio-provided primitives -- such as sockets, channels, timers, and more -- all tap into a thread-local coop "budget" …

chore(buffers): don't drop events when we yield for non-capacity reasons (v0.20.x)

---

benches/remap.rs
src/transforms/remap.rs

This PR eliminates the runtime match in here:
https://github.com/vectordotdev/vector/blob/3397283e9b23fed0ee9e4be244fa949aef73a8dc/src/transforms/remap.rs#L272-L281

chore: Make `Remap` transform generic over `Runner`

---

lib/vector-buffers/src/buffer_usage_data.rs
lib/vector-buffers/src/variants/disk_v1/tests/acknowledgements.rs
lib/vector-buffers/src/variants/disk_v2/tests/basic.rs
lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs
lib/vector-buffers/src/variants/disk_v2/tests/known_errors.rs
lib/vector-buffers/src/variants/disk_v2/tests/size_limits.rs
lib/vector-core/src/stream/driver.rs
src/http.rs
src/sinks/aws_kinesis_firehose/service.rs
src/sinks/aws_kinesis_streams/service.rs
src/sinks/aws_sqs.rs
src/sinks/azure_common/service.rs
src/sinks/util/sink.rs
src/sources/file.rs
src/sources/util/framestream.rs
src/sources/util/tcp/mod.rs
src/sources/util/unix_stream.rs
src/topology/running.rs
src/transforms/aws_ec2_metadata.rs

Instrumenting with an inactive span seems to divorce it from the parent
span altogether so that, for example, if Vector is run with a lower log
level so that the span being used to instrument is disabled, any metrics
published in that span lack the tags from the tracing context of parent spans.
This gotcha is mentioned on https://docs.rs/tracing/latest/tracing/trait.Instrument.html#provided-methods
> The Span::or_current combinator can be used in combination with
> instrument to ensure that the current span is attached to the future if
> the span passed to instrument is disabled:
Fixes: #11844

fix(observability): Ensure tasks are instrumented with active spans

---

lib/vector-buffers/benches/sized_records.rs
lib/vector-buffers/examples/buffer_perf.rs
lib/vector-buffers/src/config.rs
lib/vector-buffers/src/test/common/variant.rs
lib/vector-buffers/src/test/model/in_memory.rs
lib/vector-buffers/src/test/model/on_disk_v1.rs
lib/vector-buffers/src/test/model/on_disk_v2.rs
lib/vector-buffers/src/topology/builder.rs
lib/vector-buffers/src/topology/test_util.rs
lib/vector-buffers/src/variants/disk_v1/mod.rs
lib/vector-buffers/src/variants/disk_v1/tests/mod.rs
lib/vector-buffers/src/variants/disk_v2/mod.rs
lib/vector-buffers/src/variants/in_memory.rs
lib/vector-core/src/config/mod.rs
lib/vector-core/src/fanout.rs
src/topology/builder.rs
src/topology/test/backpressure.rs
tests/topology.rs

Providing 0 for in-memory buffers causes a panic. I'm guessing providing
0 for disk buffers will also mean you are going to have a bad time so
guarded against that here too.
Closes: #11770

fix(buffers): Require buffer sizes to be non-zero

---

distribution/docker/debian/Dockerfile
distribution/docker/distroless-libc/Dockerfile
scripts/package-deb.sh

Accidentally broke this in
https://github.com/vectordotdev/vector/pull/11887
See failure in https://github.com/vectordotdev/vector/runs/5592337799?check_suite_focus=true
```
+ mv target/x86_64-unknown-linux-gnu/debian/vector_0.21.0-1_amd64.deb target/x86_64-unknown-linux-gnu/debian/vector_0.21.0-1_amd64.deb
mv: 'target/x86_64-unknown-linux-gnu/debian/vector_0.21.0-1_amd64.deb' and 'target/x86_64-unknown-linux-gnu/debian/vector_0.21.0-1_amd64.deb' are the same file
make: *** [Makefile:548: package-deb-x86_64-unknown-linux-gnu] Error 1
rm target/x86_64-unknown-linux-gnu/release/vector.tar.gz
```

fix(releasing): Fix debian packaging

---

src/sources/kafka.rs

Fixes: #11878
When having other types as keys than string, the lossy conversion messes them up, e.g. when sending a Long value, it will become a 10-byte string, which is impossible to reverse on the receiver's side.

fix(kafka source): read message key as bytes instead of string

---

lib/vrl/compiler/src/expression.rs
lib/vrl/compiler/src/expression/op.rs
lib/vrl/compiler/src/expression/unary.rs
lib/vrl/compiler/src/vm/machine.rs
lib/vrl/stdlib/src/encode_logfmt.rs
lib/vrl/stdlib/src/parse_grok.rs
lib/vrl/stdlib/src/parse_logfmt.rs
lib/vrl/tests/src/main.rs
lib/vrl/tests/tests/internal/coalesced_fallible_op.vrl
scripts/test-vrl.sh

There were a number of remaining bugs highlighted by running the VRL tests after all the stdlib functions had been implemented.
This fixes them so all tests now pass.
I have also updated the tests so that the VRL tests are run for both AST and VM runtimes.
It may make more sense to review this PR commit by commit, since for the most part each commit covers one bug. (Ignore `Or should jump out if there is an error.` as it get's fixed properly in `Binary operations need to jump to the end on error`)

fix(vrl): fix remaining VM bugs

---

src/sinks/blackhole/sink.rs
website/cue/reference/components/sinks/blackhole.cue

By setting `print_interval_secs` to `0`. Previously this would panic
which also wasn't great.
I recommend viewing this without whitespace changes except @spencergilbert who goes his own way.
Closes: #11909

feat(blackhole sink): Allow disabling reporting

---

lib/vrl/vrl/Cargo.toml
lib/vrl/vrl/benches/runtime.rs

Just noticed that some labels were off when adding the LLVM alternative to the benches.

chore: Fix naming for VRL runtime benches

---

.github/workflows/test.yml

chore: Make check-msrv CI job name less opaque

---

lib/vrl/stdlib/src/parse_xml.rs

Previously nodes with a single child element did not have attributes
associated.
Fixes: #11901

fix(vrl): Fix parse_xml handling of single node children

---

Cargo.lock
src/sources/aws_sqs/source.rs

The message decoder in the `aws_sqs` source does a lot of `async` work for no real gain, as none of the code paths will ever actually wait asynchronously. This PR converts it all to an iterator.
The bulk of the code additions are the `FoldFinally` iterator adapter, for which I couldn't find an equivalent. The stream handles it by emitting the final value after the last `yield` with an internalized state machine built up by the compiler. This is an equivalent mechanism for an iterator, exposed as a struct.
This is partially related to #11908, as this kind of work may be required in other places if we have to move away from tokio's `FramedRead`.

chore(aws_sqs source): Convert decoder to iterator

---

website/cue/reference/components/sinks/blackhole.cue

https://github.com/vectordotdev/vector/pull/11912#discussion_r830349081

docs(blackhole sink): Add backticks around `print_interval_secs` value

---

website/cue/reference/remap/literals/regular_expression.cue
website/cue/reference/remap/literals/string.cue

This simple PR fixes/improves two minor aspects I noticed while reading the VRL literals documentation:
* fix incorrect example for regular expression literals
* improve string literals documentation
* do not double-escape unicode example (already is in a raw string block)
* do not use backticks in enum options (enums automatically adds them)
I ran `make check-docs CI=true` to verify formatting and correctness of the changes.

docs(vrl): minor fixes/improvements to literals documentation

---

.github/workflows/soak_infra.yml
soaks/Dockerfile.builder

This commit updates the mold linker for use in soak builder and, additionally,
makes the platforms the images are built for a matrix. This is intended to allow
parallel builds for platforms, especially as the ARM build is very slow.
Extracted from #11891

chore: Update mold, add matrix to soak_infra workflow

---

docs/specs/component.md

closes #9855
Specifies when the `component_received_bytes_total` should be emitted.

chore: update component spec

---

soaks/Dockerfile

It appears that the aws_firehose soaks are hanging for want of
ca-certificates. In #11891 it's obvious from the logs that the vector process
crashes with the following error message:
```
2022-03-24T02:17:59.513654Z  INFO vector::app: Log level is enabled. level="info"
2022-03-24T02:17:59.513723Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
2022-03-24T02:17:59.515117Z  WARN load_region{provider=ProfileFileRegionProvider { fs: Fs(Real), env: Env(Real), profile_override: None }}: aws_config::profile::parser::source: could not determine home directory but home expansion was requested
2022-03-24T02:17:59.515152Z  WARN load_region{provider=ProfileFileRegionProvider { fs: Fs(Real), env: Env(Real), profile_override: None }}: aws_config::profile::parser::source: could not …
```

chore: Add ca-certificates in soak runner

---

lib/k8s-e2e-tests/tests/vector-agent.rs

Due to a change [here](https://github.com/vectordotdev/helm-charts/commit/87ca537b54f9956c434ddbbd3cfcc9942d7e9c07) the k8s-e2e tests stopped running with 
```
Error: INSTALLATION FAILED: execution error at (vector/templates/daemonset.yaml:40:10): Specify `dataDir` if you're using `existingConfigMaps`
```
This adds a `dataDir` option to the test that uses the `existingConfigMaps` option.

fix(tests): add dataDir config option to values.yml in k8s-e2e-tests

---

Cargo.lock
Cargo.toml
lib/tracing-limit/src/lib.rs
lib/vector-buffers/benches/common.rs
lib/vector-buffers/examples/buffer_perf.rs
lib/vector-buffers/src/buffer_usage_data.rs
lib/vector-buffers/src/config.rs
lib/vector-buffers/src/lib.rs
lib/vector-buffers/src/test/common/variant.rs
lib/vector-buffers/src/topology/builder.rs
src/app.rs
src/lib.rs
src/topology/builder.rs
src/topology/running.rs
src/trace.rs

We have had code to support using `tokio-console` for a while now, but it resulted in subpar logging when actually compiled to work with `tokio-console` due a lack of using per-layer filtering.
This PR updates our tracing initialization to utilize per-layer filtering so that `console-subscriber` has accessed to the spans it needs while our normal application logging remains unaffected.  Additionally, we've been able to reduce a little bit of the boilerplate around tracing initialization.
As a cherry on top, we've also switched to utilizing more of the unstable tracing API in `tokio` in order to name some of our spawned tasks, namely component tasks.  This, essentially, gives us a `tokio-console` view that looks like this:
Now each top-level component task has a name based on the component …

chore(observability): better integration of tracing/tokio-console

---

lib/k8s-e2e-tests/tests/vector-agent.rs

The k8s tests were failing with this error:
```
Error: INSTALLATION FAILED: release vector failed, and has been uninstalled due to atomic being set: Service "vector-qywu3-vector-agent" is invalid: spec.ports: Required value
```
This should fix that error by specifying the ports.

fix(tests): add service.ports config option to values.yml in k8s-e2e-tests

---

website/content/en/docs/reference/configuration/template-syntax.md

Closes #4585
We had another user on Discord come up against this. The docs for what happens when a field specified in a template is missing.
This updates the docs.

docs(external docs): update docs for template missing fields

---

.github/workflows/soak.yml

In the past we set the threshold for mean drift at the 9th quartile. Feeling
that this was too high a bar we moved the threshold down to 5%. This, for the
most part, has worked out well, except for some soaks that are, for reasons
unknown, inclined to walk back and forth across that line. 6% is also regularly
violated but 7% rarely is.
In the longer term we'd like to make tolerances here tighter, of course, but
have a need to not force devs to re-run soaks just to see if the results are
accurate or random chance.

chore: Set mean drift threshold to 7% from 5% in soaks

---

soaks/soak.sh

This commit removes an off-by-one error in the `soak.sh` script with regard to
replica settings. I copied the logic up from `soak_one` which means that the
replica setting is -2 of what the user specifies by the time we get into
`soak_one`.

chore: Address off-by-one error in soak.sh replicas

---

src/sources/socket/mod.rs
src/sources/socket/udp.rs

For the `socket` source when `mode` is `udp`, the `host` key on events
includes the port of the peer address, but this is inconsistent with
other sources where the `host` is only the IP or domain name.
This will be followed up with a PR to allow annotating with `port` too.
Prompted by #11476

fix(socket source): Remove port from `host` for `udp`

---

distribution/docker/alpine/Dockerfile
distribution/docker/debian/Dockerfile
distribution/docker/distroless-libc/Dockerfile
distribution/docker/distroless-static/Dockerfile
soaks/Dockerfile
tilt/Dockerfile
website/content/en/highlights/2022-03-22-0-21-0-upgrade-guide.md

This declaration automatically creates an anonymous volume whenever the
Vector image is run, regardless of whether it actually needs it.
It seems better to, instead, rely on the user to provide a volume if
they want it.
See https://github.com/vectordotdev/vector/issues/11982 for additional
rationale.
Closes: #11982

fix(docker platform)!: Remove VOLUME declarations from Dockerfiles

---

lib/vrl/parser/Cargo.toml
lib/vrl/parser/build.rs
lib/vrl/parser/src/lex.rs
lib/vrl/parser/src/lib.rs
lib/vrl/parser/src/parser.lalrpop

This PR improves the compilation time of the `vrl-parser` crate.
Specifically, here are the before/after runs:
```
cargo clean && cargo build -p vrl-parser
...
Finished dev [unoptimized + debuginfo] target(s) in 2m 12s
```
```
cargo clean && cargo build -p vrl-parser
...
Finished dev [unoptimized + debuginfo] target(s) in 59.76s
```

chore(vrl): improve VRL parser compilation times

---

src/sinks/loki/config.rs
src/sinks/loki/sink.rs

Closes https://github.com/vectordotdev/vector/issues/9549
This PR allows expanding objects as log entry labels for Loki. It is useful when you don't know the exact keys of the object, e.g., when you want to extract all labels of a Kubernetes pod.
Raw entry part:
```json
{"kubernetes":{"pod_labels":{"app":"web-server","name":"unicorn"}}}
```
Vector config part:
```
labels:
pod_labels_*: {{ kubernetes.pod_labels }}
```
Result:
```
pod_labels_app: "web-server"
pod_labels_name: "unicorn"
``` 
You can do the same thing in promtail like this:
```
- action: labelmap
regex: __meta_kubernetes_pod_label_(.+)
replacement: pod_labels_$1
```

feat(loki sink): convert objects to Loki labels

---

website/yarn.lock

Closes https://github.com/vectordotdev/vector/security/dependabot/7

chore: update ansi-regex in website due to vulnerability

---

src/sources/prometheus/scrape.rs
website/cue/reference/components/sources/prometheus_scrape.cue

A new optional configuration option has been added: `query` to the `prometheus_scrape` source.
The option is modelled as a map of string keys to vector-of-strings values.
This representation allows for multiple values for the same parameter key as allowed by the HTTP spec.
It also mirrors the upstream Prometheus `params` option in the `scrape_config` section.
Custom request parameters provided using `query` are appended to the `endpoints` URIs.
All request query parameters are properly decoded/encoded from/to using `form_urlencoded`.
See more details in the referenced issue.
This is my second attempt at taming Rust, so feedback on improving the code style and techniques is highly appreciated.
I'm leaving some in-code comments of some questions I had during the development of this PR. …

enhancement(prometheus_scrape source): add support for custom request query parameters

---

website/cue/reference/components/sinks/elasticsearch.cue

Prompted by https://github.com/vectordotdev/vector/pull/12033#issuecomment-1087956363
Documentation of these key/value maps still doesn't render great on the website, but at least this is an improvement.

docs(elasticsearch sink): Fix documentation of `query`

---

Cargo.lock
Cargo.toml
src/sinks/vector/v2/config.rs
src/sinks/vector/v2/service.rs
src/sources/vector/v2.rs
website/cue/reference/components/sinks/vector.cue

Forewarning: I don't daily develop rust. Compared to this code-base, I'm a beginner. Appologies if I havent done anything the way you need it done.
Fixes #9558
Adds `compression` to the sink. v2 source gets the ability to receive compressed messages if supplied.
I wouldnt mind if someone more experienced than I added a test that confirmed the sink is sending compressed messages.

feat(vector sink): compression support for vector v2

---

src/sources/splunk_hec/mod.rs

I verified with Splunk 8.2.4 that it doesn't actually check the token.
Addresses https://github.com/vectordotdev/vector/discussions/12097

fix(splunk_hec source): Ignore the HEC token for health checks

---

lib/codecs/src/encoding/framing/bytes.rs
lib/codecs/src/encoding/framing/mod.rs
lib/codecs/src/encoding/mod.rs
lib/codecs/src/lib.rs

Part of #12080, https://github.com/vectordotdev/vector/pull/10684#pullrequestreview-907897403 for context.

enhancement(codecs): Implement `BytesEncoder` framing

---

rfcs/2022-03-07-3829-better-support-for-large-aws-s3-batches.md

Closes #3829 
[Rendered view](https://github.com/vectordotdev/vector/blob/s3-large-upload-support-rfc/rfcs/2022-03-07-3829-better-support-for-large-aws-s3-batches.md)

chore: RFC for improving S3's support for large uploads

---

src/sinks/datadog/traces/config.rs
website/cue/reference/components/sinks/datadog_traces.cue

This was a silent merge conflict between
623b18263ff4281c6c42cb9635a5403eb3991747 and
6fe2010d6542323aaf3e6030266957d44e0da517

chore: Batch default should be f64 for `datadog_traces`

---

rfcs/2021-07-27-7117-vrl-string-interpolation.md

Ref #7117 
This RFC discusses adding string interpolation to VRL so it is possible to construct strings like:
```
"The message is {{ .message }}"
```
Templates are delimited by `{{..}}`, and can be escaped by `\{{...\}}` if necessary.
[Readable](https://github.com/vectordotdev/vector/blob/7117_template_rfc/rfcs/2021-07-27-7117-vrl-string-interpolation.md)

chore(vrl): String interpolation RFC

---

website/cue/reference/components/transforms/route.cue

The current wording makes it sound like this route is used right now,
but it is just reserved for the future.
Closes: #12143

docs(route transform): Separate out note about _default route

---

.github/workflows/soak.yml

The soak-builder runners seem to have stopped picking up jobs. We've
reached out to Github support, but trying this until they get back to us.

chore: Move soak build jobs to test runners

---

website/content/en/docs/reference/configuration/_index.md
website/cue/reference/configuration.cue
website/cue/reference/urls.cue

This small PR adds a mention for [ytt](https://carvel.dev/ytt/) as another data templating tool, in this case for YAML configurations.
In a nutshell, ytt is to YAML what Jsonnet is to JSON.
In our team we use ytt with success and I think is fair to mention it as an alternative to Jsonnet+JSON for YAML users like us.

docs(config): mention ytt as another available templating tool

---

lib/codecs/src/encoding/mod.rs

This is a follow-up to #11929 to make the `Native`/`NativeJson` codecs configurable for sinks that use the new `Encoder`.

feat(sinks, codecs): Add `Native`/`NativeJson` encodings to `SerializerConfig` enum

---

src/config/loading/loader.rs

While developing the implementation for #10420, I discovered that configuration file loading errors are not properly propagated in the current `master` branch of Vector.
For example, consider the following configuration with a deliberate YAML syntax error on the top:
```yaml
sources: &
logs:
type: demo_logs
format: syslog
sinks:
console:
type: console
inputs:
- logs
encoding: json
```
When you try to start Vector in current `master` with the above configuration file, you get these results:
```
$ vector -c vector.yaml
2022-04-09T21:19:43.427912Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-04-09T21:19:43.432056Z  INFO vector::app: Loading configs. paths=["vector.yaml"] …
```

fix(config): fix error processing when loading configuration files

---

Cargo.lock
Cargo.toml
lib/codecs/Cargo.toml
lib/prometheus-parser/Cargo.toml
lib/vector-core/Cargo.toml

This reverts commit 74b7da00a0a7c5baf1518cb5619fb134f60d1cd8.
The prost upgrade (required by newer tonic) seems to have broken the Windows CI checks. This is testing if reverting the upgrade fixes the problem before doing more investigation.

chore(deps): revert bump tonic from 0.6.2 to 0.7.0 (#12062)

---

lib/vector-buffers/src/buffer_usage_data.rs
lib/vector-buffers/src/internal_events.rs
lib/vector-buffers/src/topology/channel/sender.rs

I missed this in https://github.com/vectordotdev/vector/pull/11962 which
changed the buffers to count discarded events as received before
discarding.

fix(buffers): `buffer_events` should decrement discarded

---

Cargo.lock
lib/datadog/grok/Cargo.toml
lib/datadog/grok/benches/filters/keyvalue.rs
lib/datadog/grok/benches/filters/main.rs
lib/datadog/grok/src/filters/keyvalue.rs
lib/datadog/grok/src/lib.rs
lib/datadog/grok/src/parse_grok.rs

With reference to #10144 and in light of #11849 we now have an understanding
that http -> pipelines -> blackhole is significantly bottlenecked in
datadog-grok. Unfortunately most of our data indicates we're looking at regex
being the prime pain point. This commit does two things: introduces
micro-benchmarks for `datadog_grok::filters::keyvalue::apply_filter` --
unfortunately exposing `datadog_grok::filters` from the crate so we can
benchmark it -- and improves the performance of said function by +40% in the
micro when there is a field delimiter in place. Specifically, we remove the need
for nom-regex and avoid cloning a `regex::Regex` instance for each key and each
value in a field.

chore: Add microbenchmarks to lib/datadog/grok

---

src/sources/socket/mod.rs
src/sources/socket/unix.rs
src/sources/statsd/mod.rs
src/sources/statsd/unix.rs
src/sources/syslog.rs
src/sources/util/mod.rs
src/sources/util/unix.rs
src/sources/util/unix_datagram.rs
src/sources/util/unix_stream.rs
tests/syslog.rs
website/cue/reference/components/sources/socket.cue
website/cue/reference/components/sources/syslog.cue

This patch adds a new option : `socket_file_mode` to the socket and
syslog sources to set the permission on the created unix socket.
Fixes #9241
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

feat(socket source, syslog source): allow custom permissions on socket

---

benches/http.rs
src/codecs/encoder.rs
src/codecs/mod.rs
src/sinks/http.rs
src/sinks/util/encoding/adapter.rs
src/sinks/util/encoding/mod.rs

This PR adds support structures needed to have both an `Encoder<()>` (no framing) and `Encoder<Framer>` (with framing), both of which emit internal logs when encoding fails.
Some context that triggered the need for this: https://github.com/vectordotdev/vector/pull/12133#discussion_r846364609.

chore(codecs): Implement additional `Encoder`/`EncodingConfig` without framing

---

src/sinks/util/encoding/codec.rs
src/sinks/util/encoding/mod.rs

Context: https://github.com/vectordotdev/vector/pull/12136#discussion_r846248439 / https://github.com/vectordotdev/vector/pull/12133#discussion_r846354046.

chore(codecs): Implement `StandardEncodingsMigrator`

---

.github/workflows/soak.yml

This commit tidies up the capture files etc from soak runs, resolving #12184.

chore: Tidy up our soak runs

---

lib/vrl/cli/src/repl.rs
lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/lib.rs
lib/vrl/vrl/src/lib.rs

resolves #12204.
To clarify on this comment in this issue:
> When resolving this, we should get some more comprehensive tests that verify the scoping rules.
The issue is unrelated to the scoping feature itself, instead it was caused by a happy consequent of that feature, allowing VRL to keep internal scope... internal.
However, VRL's CLI has been a hacky side-project from the start that never got a proper do-over, and it suffers from a few issues that originate from the fact that each line in the REPL is its own VRL program. Technically, two VRL programs should share zero information between them, but because of the REPLs current implementation, we have to keep sharing internal state between programs to ensure this REPL workflow:
```
$ foo = 5
$ foo
```
works, by passing information about …

fix(vrl): resolve CLI issues with local scoping

---

website/cue/reference/administration/downloads.cue

Closes: #12243
I will symlink all existing deb artifacts in S3 to their new names.

docs: Fix deb download link

---

src/config/loading/mod.rs
src/config/vars.rs
website/content/en/docs/reference/configuration/_index.md
website/cue/reference/configuration.cue

This PR improves the current environment variables interpolator to fully mimic the Docker compose syntax:
* `${VARIABLE:-default}` evaluates to `default` if `VARIABLE` is unset or empty in the environment.
* `${VARIABLE-default}` evaluates to `default` only if `VARIABLE` is unset in the environment.
* `${VARIABLE:?err}` exits with an error message containing `err` if `VARIABLE` is unset or empty in the environment.
* `${VARIABLE?err}` exits with an error message containing `err` if `VARIABLE` is unset in the environment.
**Note:** The last two cases (_exits with an error message ..._) will not show properly until #12149 is resolved.
In addition, the improved regex also allows for `default` and `err` to be empty strings, fixing the linked issue.
I was not sure where exactly to update the …

enhancement(config): extend environment variables interpolation syntax

---

src/config/loading/loader.rs

The issue https://github.com/vectordotdev/vector/issues/12042 reflected an issue when loading 
When loading the configuration in k8s, as @nicarim mentioned, some `..2022_04_15_06_27_41.1541743324` are created in the container, containing the exact same configuration. Which result in loading and merging the configuration in a `Table` structure as follow.
```
{".": Table({"entry_filter_supported": Table({"inputs": Array([String("kubernetes_logs")]), "reroute_dropped": Boolean(true), "source": String("supported_containers = [\"minimal-poc\"]"), "type": String("remap")})}), "..2022_04_15_06_27_41": Table({"entry_filter_supported": Table({"inputs": Array([String("kubernetes_logs")]), "reroute_dropped": Boolean(true), "source": …
```

fix(config): ignore directories starting with a dot

---

Cargo.lock
Cargo.toml

Since 0.21.0 has been released.

chore(releasing): Bump version to 0.22.0

---

website/content/en/highlights/2022-03-22-0-21-0-upgrade-guide.md
website/cue/reference/components/aws.cue

docs: Document lack of support for `credential_process` for AWS components

---

src/sources/splunk_hec/mod.rs
src/topology/running.rs
src/topology/test/mod.rs
src/topology/test/reload.rs

As stated in the title, this fixes the issue in #12273 where a panic would occur when new components were added to a running Vector process via the normal "watch a config directory for changes" reload logic.
I also did a little work to get some topology tests running again, so there's some unrelated changes to make the tests work again in service of being able to run the actually-new test I added when fixing the true issue.

fix(topology): don't panic when checking inputs for new component during reload

---

docs/specs/target.md

docs: Fix links to default configurations in target spec

---

README.md

The current link referes to `latest` which 404's.
Also, remove the `latest` reference since releases are ordered by newest first and, consequently, a visit to said page would show the latest.

docs: update link to releases

---

src/sinks/datadog/logs/service.rs
src/sinks/datadog/logs/tests.rs
src/sinks/datadog/metrics/service.rs
src/sinks/datadog/traces/service.rs

We intend to expand out retried requests to cover a much broader swatch
(likely all requests) as part of
https://github.com/vectordotdev/vector/issues/10870 but
https://github.com/vectordotdev/vector/issues/12220 is blocking a user
from trying out Vector so adding these ahead of time.
Closes: #12220

enhancement(datadog provider): Retry forbidden requests

---

src/cli.rs

This wasn't intended to be publicly released but I don't see a great way
to hide it from `-h` output without some significant refactoring.
Instead, just mark as experimental.
We'll want a bit more QA around this subcommand before marking it
stable. For example, it lacks support for the normal `--config` flags or
an output format.
Fixes: #12325 

chore: Mark `vector config` as experimental

---

src/sources/internal_logs.rs
src/trace.rs

This PR is a fix for #12251.
When previously switching over to per-layer filtering in `src/trace.rs` to better support using `tokio-console` without spamming the normal console logs with TRACE-level spans/events, we introduced a regression with internal logging.
For anyone using the `internal_logs` source, they would have started seeing TRACE-level logging flowing out of the source, even if the Vector logging level was at INFO.  We've fixed this by bringing `BroadcastSubscriber` -- the component responsible for feeding internal log events to `internal_logs` -- into the per-layer filtering fold.  This allows it to correctly filter events to match what is logged to console.
Fixes: #12251

fix(internal_logs source): apply correct log level filtering

---

lib/value/src/kind.rs
lib/value/src/kind/collection.rs

This improves the `Display` implementation of `value::Kind`, in preparation of iteration support in VRL.
ref #12317

chore(vrl): improve collection "kind" display

---

src/aws/mod.rs
src/aws/region.rs
src/internal_events/common.rs
src/sinks/aws_cloudwatch_logs/integration_tests.rs
src/sinks/aws_cloudwatch_metrics.rs
src/sinks/aws_kinesis_firehose/service.rs
src/sinks/aws_kinesis_firehose/tests.rs
src/sinks/aws_kinesis_streams/service.rs
src/sinks/aws_sqs/integration_tests.rs
src/sinks/elasticsearch/common.rs
src/sinks/s3_common/service.rs
src/sources/aws_s3/mod.rs
website/cue/reference/components/aws.cue

As of 0.21.0 where the new AWS SDK was integrated, `region`, is now
required by the client. If not provided, it fails at runtime to make
requests. Instead, make it a required configuration field.
Closes: #12311

fix(aws provider): Make region required configuration

---

src/config/cmd.rs

Closes #12329 
This PR adjusts `vector config --include-defaults` behavior to directly use user-provided array values rather than merge them with the related `ConfigBuilder`'s array values. This avoids duplicates.
With the following configuration,
```
[sources.source0]
type = "stdin"
[sinks.sink0]
inputs = ["*"]
```
Running 
```
vector -c {{your config path}} config --include-defaults
```
should generate the following  (trimmed for brevity). Previously, this output would include `inputs: ["*", "*"]`.
```
{
...
"sinks": {
"sink0": {
...
"inputs": [
"*"
],
...
}
...
}
```

fix(cli): Use user-provided array values in vector config --include-defaults

---

src/aws/auth.rs
src/sinks/elasticsearch/common.rs
src/sinks/elasticsearch/mod.rs
src/sources/aws_sqs/integration_tests.rs
tests/config.rs

Fixes a silent merge conflict between: efb5849 and f5391b6

fix(ci): Fix merge conflict for AWS auth changes

---

src/sinks/aws_kinesis_firehose/integration_tests.rs
src/sinks/elasticsearch/integration_tests.rs

Region is now required when AWS authentication is used.

fix(ci): Fix aws_kinesis_firehose and elasticsearch integration tests

---

lib/vrl/parser/src/lex.rs

Closes #12364 
VRL templates needs to treat `{` as an escapable character to handle escaping template delimiters - `\{{`. However if you have a string with a single `{` - `"\{"` - it wasn't properly escaping it and was panicking instead.

fix(vrl): allow a single brace to be escaped

---

lib/vrl/tests/src/docs.rs
lib/vrl/tests/src/main.rs

Small PR to allow speeding up VRL test runs during development.
ref: #12317

chore(vrl): allow ignoring cue during test runs

---

lib/vrl/compiler/src/compiler.rs
lib/vrl/parser/src/arbitrary.rs
lib/vrl/parser/src/ast.rs
lib/vrl/parser/src/lex.rs
lib/vrl/parser/src/parser.lalrpop
lib/vrl/proptests/src/main.rs

This PR adds syntactic support for function closures in VRL. This will be used to allow function calls to iterate over collections in an upcoming follow-up PR.
In its current form, the syntax is supported, but unused.
ref #12317

chore(vrl): add syntax support for function closures

---

website/cue/reference/remap/literals/string.cue

ref #7117 
This adds some documentation for template strings to the [VRL reference](https://vector.dev/docs/reference/vrl/expressions/).

docs(external docs): added documentation for template strings

---

website/cue/reference/releases/0.21.1.cue

Make "panics" consistent with others.

docs: fix typo in 0.21.1 release note

---

config/examples/namespacing/sinks/es_cluster.toml
scripts/check-examples.sh

For now, each `toml` file in the `config/examples` folder were validated individually. Therefore, the `namespacing` folder was not properly validated.
With this fix, every file/folder in the `config/examples` is validated as a single file or as a config folder.
Closes OP-148

fix(ci): ensure the example folder is validated with namespacing

---

lib/codecs/src/decoding/format/bytes.rs
lib/codecs/src/decoding/format/json.rs
lib/codecs/src/decoding/format/native.rs
lib/codecs/src/decoding/format/native_json.rs
lib/codecs/src/decoding/format/syslog.rs
lib/codecs/src/decoding/mod.rs
src/sources/aws_kinesis_firehose/mod.rs
src/sources/aws_sqs/config.rs
src/sources/demo_logs.rs
src/sources/exec/mod.rs
src/sources/heroku_logs.rs
src/sources/http.rs
src/sources/kafka.rs
src/sources/nats.rs
src/sources/redis/mod.rs
src/sources/socket/mod.rs
src/sources/stdin.rs

Closes #12049
This covers every source that has a `DeserializerConfig`, which I believe is the correct subset.

chore(codecs): make source output types depend on codec

---

lib/vrl/cli/src/repl.rs
lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/lib.rs
lib/vrl/compiler/src/program.rs
lib/vrl/vrl/src/lib.rs

The introduction of [local variable scoping](https://github.com/vectordotdev/vector/pull/12017) caused the VRL REPL to break. This was partially fixed in #12210, but the local state would still be dropped if the compiler returned an error in the REPL.
This PR solves that issue.
Closes #12400.

fix(vrl): remember local state after compilation error in REPL

---

src/internal_events/kubernetes_logs.rs
src/sources/kubernetes_logs/mod.rs

Closes #12401
There may be a more elegant way to handle the conditional logic in the
internal_event, but this keeps the behavior similar to the original code while
adding the `pod_namespace` tag to metrics.

feat(kubernetes_logs source): Include pod_namespace tag on emitted metrics

---

src/sources/internal_metrics.rs
website/cue/reference/components/sources/internal_metrics.cue

The current implementation is incorrect as it only adds the tags if the
tag is specified in the config (not matching the documentation) but then
also ignores the provided key value.
Given we aren't currently setting a default for this, I opt'd to update
the docs to reflect that since this seemed less disruptive than adding
the tags by default for everyone.
**EDIT**: extracted docs updates to https://github.com/vectordotdev/vector/pull/12321

fix(internal_metrics source): Fix setting of host/pid tags

---

Cargo.toml
src/config/enterprise.rs
src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/mod.rs
src/sources/internal_logs.rs

This PR creates an internal sink to report the internal logs to Datadog when the enterprise feature is enabled.
Closes OP-245

enhancement(observability): report internal logs to Datadog for enterprise

---

distribution/docker/alpine/Dockerfile
distribution/docker/debian/Dockerfile
distribution/docker/distroless-libc/Dockerfile
distribution/docker/distroless-static/Dockerfile
soaks/Dockerfile
tilt/Dockerfile

After removing the `VOLUME` declarations from the Dockerfiles, the images were left without a default empty data directory, thus preventing Vector to start when a data directory is required.
Fixes #12413  🙈

fix(docker platform): add empty `/var/lib/vector` directory to Docker images

---

src/api/schema/components/mod.rs
src/api/schema/metrics/source/file.rs
src/conditions/check_fields.rs
src/lib.rs
src/sinks/aws_cloudwatch_logs/request.rs
src/sinks/splunk_hec/logs/sink.rs
src/sinks/splunk_hec/logs/tests.rs
src/sources/dnstap/mod.rs
src/sources/http.rs
src/sources/internal_metrics.rs
src/sources/kafka.rs
src/sources/prometheus/scrape.rs
src/sources/socket/mod.rs
src/sources/socket/tcp.rs
src/sources/socket/udp.rs
src/sources/util/http/prelude.rs
src/sources/util/tcp/mod.rs
src/transforms/key_value_parser.rs
src/transforms/regex_parser.rs

This removes the global allow for the `too_many_arguments` clippy lint. I reworked several of the places that were throwing this lint, but just added a localized allow where reworking it was too annoying or non-critical (ie tests). I dropped a couple other clippy allows too that were trivial to remove.
As a bonus, it removes a little better than 100 lines of code. 🎉

chore: Drop global `allow(clippy::too_many_arguments)`

---

src/aws/auth.rs
src/sinks/aws_kinesis_firehose/integration_tests.rs
src/sinks/elasticsearch/integration_tests.rs
website/cue/reference/components/aws.cue

Technically an enhancement, but it allows working around a regression in
behavior (the default changing from 30s to 5s as part of the SDK
upgrade) so marking as a fix.
Closes: #12421

fix(aws provider): Allow configuring the load timeout for AWS credentials

---

.github/workflows/environment.yml

Not actually used in CI after https://github.com/vectordotdev/vector/pull/12437
Will follow up to update the Makefile since the image needs to be
published first.

chore: Rename Vector development image

---

distribution/docker/alpine/Dockerfile
distribution/docker/debian/Dockerfile
distribution/docker/distroless-libc/Dockerfile
distribution/docker/distroless-static/Dockerfile
lib/soak/Dockerfile
scripts/environment/Dockerfile
scripts/integration/Dockerfile
skaffold/docker/Dockerfile
soaks/Dockerfile
soaks/Dockerfile.builder
tests/data/dnstap/Dockerfile
tilt/Dockerfile

[hadolint](https://github.com/hadolint/hadolint)
Unfixed lints (mostly since we don't/haven't pinned things anywhere):
```shell
fd Dockerfile | xargs hadolint
./distribution/docker/alpine/Dockerfile:11 DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
./distribution/docker/debian/Dockerfile:12 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
./distribution/docker/distroless-libc/Dockerfile:10 DL3006 warning: Always tag the version of an image explicitly
./distribution/docker/distroless-static/Dockerfile:10 DL3006 warning: Always tag the version of an image explicitly
./lib/soak/Dockerfile:14 …
```

chore: Apply a number of hadolint fixes to Dockerfiles

---

.github/workflows/test.yml

While investigating a clippy check didn't flag on
https://github.com/vectordotdev/vector/pull/12412 I realized this is the
only job that runs in the environment image. I think it's better that it
be consistent with the other jobs.

chore: Run checks directly on VM

---

src/sources/aws_sqs/source.rs
src/sources/file.rs
src/sources/journald.rs
src/sources/kafka.rs
src/sources/splunk_hec/acknowledgements.rs
src/sources/splunk_hec/mod.rs
src/sources/util/finalizer.rs

The `ShutdownSignal` handles sharing of the trigger through use of an
`Arc`, and the tripwire can be cloned and waited on by multiple tasks.
As such, this does not need to be wrapped with the `Shared` future.

chore(sources): Shared shutdown signals don't need `Shared`

---

lib/vrl/cli/src/cmd.rs

This was added recently. Still trying to track down why CI didn't flag it.

chore: Allow clippy lint for stderr output in VRL

---

lib/codecs/src/encoding/framing/character_delimited.rs
src/sinks/util/encoding/adapter.rs

Bug/fix similar to #10829, just for the encoding side.

fix(codecs): Fix deserializing of `framing.character_delimited.delimiter` for encoding

---

Cargo.lock
Cargo.toml
src/aws/mod.rs
src/common/s3.rs
src/common/sqs.rs
src/sinks/aws_cloudwatch_logs/config.rs
src/sinks/aws_cloudwatch_metrics.rs
src/sinks/aws_kinesis_firehose/config.rs
src/sinks/aws_kinesis_streams/config.rs
src/sources/aws_s3/mod.rs

closes #12459 
This sets `sleep_impl` on all AWS client builders, using Tokio's `sleep` implementation.

fix: add sleep_impl to AWS SDK client builder

---

.github/workflows/test.yml
Makefile
scripts/check-component-features
scripts/check-one-feature
src/sinks/aws_cloudwatch_logs/integration_tests.rs
src/sources/util/http/auth.rs
src/sources/util/http/error.rs
src/sources/vector/v1.rs

This speeds up the `check-component-features` check by running each
feature in a separate job in a separate build tree. This is possible
because cargo doesn't overwrite output files after they are created. To
take advantage of this, we first do a check on the full build and then
create a temporary build tree for each feature composed of hard links to
the individual files created during that check. This speeds up the
subsequent builds and allows them to run in parallel as they no longer
clobber each other's outputs.
This check normally takes a little under 2 hours on the CI runners (currently 16 cores). The improved process finished in well under 1 hour on a 4 core (8 vCPU) instance, and should scale close to linearly with core count. I have added a test commit that will cause this to fail …

chore(ci): Run check-component-features in parallel

---

soaks/bin/analyze_experiment

This commit removes the now unreadably long table from the analysis comment. We
found in #12468 that this broke the comment upload, undesirable.

chore: Remove 'fine details of each soak run' detail section

---

lib/codecs/src/decoding/framing/length_delimited.rs
lib/codecs/src/encoding/framing/length_delimited.rs
lib/codecs/src/encoding/framing/mod.rs
lib/codecs/src/encoding/mod.rs
lib/codecs/src/lib.rs

In preparation to support `Native` encoding with `LengthDelimited` framing: https://github.com/vectordotdev/vector/pull/12179#discussion_r859874734.

enhancement(codecs): Implement `LengthDelimitedEncoder` framer

---

.github/workflows/soak.yml

Now that #12348 has landed we have an autoscale runner pool to back up gaining
more replicas. We can't increase our numbers on a single machine or we'll go
past the hour turn-around time but we _can_ increase the number of parallel
replicas in the workflow.
It's not totally clear if the difference between machines will make this
experiment invalid or not.

chore: Run multiple replicas of the soaks at a workflow level

---

src/sources/datadog/agent/mod.rs

So that things like `vector generate datadog_agent` work.
Fixes: #12469

fix(datadog_agent source): Submit source to inventory

---

.github/workflows/manual_soak.yml

This commit adds a new workflow that lets us manually trigger a workflow,
providing the two SHAs for comparison. This should allow us to compare releases
easily.

chore: Experiment with a 'manual trigger' soak

---

website/cue/reference/components/sinks/datadog_logs.cue

Closes #7259
This will be easier for users as schema work lands and we can determine any mapping internally.
I'm not entirely happy with how this is presented, and there's not a better link to the Body section of the API reference - however, I don't know how much of DD's documentation I want to copy into our docs and possibly drift from the source of truth.

docs: Add Attributes note to datadog_logs sink

---

docs/specs/component.md

Clarifying that the `BytesSent` event should be bytes _before_
compression to mirror the `BytesReceived` event.

chore: Update component spec for BytesSent re compression

---

lib/vrl/diagnostic/src/formatter.rs

fix(vrl): do not print empty warning log in VRL-based transforms

---

lib/vrl/stdlib/src/parse_ruby_hash.rs

closes https://github.com/vectordotdev/vector/issues/12489
`parse_ruby_hash` can now parse hashes that contain a symbol as the value, such as `{ "key" => :foo }`

allow parsing values as a symbol

---

lib/vector-core/src/config/mod.rs
src/config/graph.rs
src/sources/datadog/agent/mod.rs
src/transforms/pipelines/config.rs
src/transforms/pipelines/mod.rs
src/transforms/remap.rs
src/transforms/route.rs

This commit removes the `From<(Into<String>, DataType)>` conversion on `Output`
in favor of a builder-ish style function, similar to what already existed on
this type with `with_schema_definition`.

chore: Create `Output::with_port`

---

.github/workflows/soak.yml

As evidenced by
https://github.com/vectordotdev/vector/pull/12524#issuecomment-1115428258 having
30 replicas of each soak variant experiment does good things for noise. However,
we do have a relatively large compute cluster backing these soaks _and_ we still
have queued up jobs during the teams working day. It's not clear that we _need_
30 replicas, so this experiment drops to 20.

chore: Run only 20 replicas of each soak experiment

---

lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/parse_json.rs
website/cue/reference/remap/functions/parse_json.cue

Add the max_depth option to the `parse_json` VRL function to partially traverse highly nested JSON-formatted messages.
These changes were tested in the Kubernetes cluster 1.21 on top of the Vector 0.20
```
$ parse_json!("{\"1\": {\"2\": {\"3\": {\"4\": {\"5\": {\"6\": \"finish\"}}}}}}", max_depth: 5)
{ "1": { "2": { "3": { "4": { "5": "{\"6\": \"finish\"}" } } } } }
```
```
$ parse_json!("{\"1\": {\"2\": {\"3\": {\"4\": {\"5\": {\"6\": \"finish\"}}}}}}", max_depth: 4)
{ "1": { "2": { "3": { "4": "{\"5\": {\"6\": \"finish\"}}" } } } }
```
```
$ parse_json!("{\"1\": {\"2\": {\"3\": {\"4\": {\"5\": {\"6\": \"finish\"}}}}}}", max_depth: 10)
{ "1": { "2": { "3": { "4": {"5": {"6": "finish"} } } } } }
```
```
$ parse_json!("{\"1\": {\"2\": {\"3\": {\"4\": {\"5\": {\"6\": \"finish\"}}}}}}", …
```

feat(vrl): add a max_depth parameter to the parse_json function

---

lib/vector-config/tests/basic.rs

chore: Allow stdout/stderr in vector config tests

---

src/aws/mod.rs
src/common/s3.rs
src/common/sqs.rs
src/sinks/aws_cloudwatch_logs/config.rs
src/sinks/aws_cloudwatch_metrics.rs
src/sinks/aws_kinesis_firehose/config.rs
src/sinks/aws_kinesis_streams/config.rs
src/sources/aws_s3/mod.rs

We have our own retry layer wired up with ARC so we disable AWS's retries.
This also appears to match the AWS component's previous behavior with
rusoto (see https://github.com/rusoto/rusoto/issues/234 and discussion).

fix(aws provider): Disable retries

---

Cargo.toml
src/config/enterprise.rs
src/config/transform.rs
src/sinks/datadog/logs/config.rs
src/sinks/datadog/metrics/config.rs
src/sources/host_metrics/cgroups.rs
src/sources/host_metrics/disk.rs
src/sources/host_metrics/filesystem.rs
src/sources/host_metrics/mod.rs
src/sources/host_metrics/network.rs
src/sources/internal_logs.rs
src/sources/internal_metrics.rs

Pushing this up for thoughts.
While reviewing #12584 I realized that the logic for reporting to Datadog when the `enterprise` flag was enabled extended further throughout the code base than I expected.
This refactoring moves the logic that was conditionally adding the enterprise config version and key from the Vector components themselves into the internal topology via `remap` transforms.
Pros:
* Removes the config version and key from config structs, eliminating the possibility that a user might set them directly
* Encapsulates the enterprise logic more succinctly in `src/config/enterprise.rs`
Cons:
* Adds more components to the internal topology that is spun up when the `enterprise` flag is set
* Makes more component config fields `pub`. I actually think this is fine as I view the …

chore(enterprise): Refactor handling of enterprise configuration for components

---

Cargo.lock
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/src/log.rs

Encode the message before printing it.
```
2022-03-25T17:27:46.307945Z  INFO transform{component_kind="transform" component_id=log component_type=remap component_name=log}: vrl_stdlib::log: a simple message internal_log_rate_secs=1 vrl_position=0
```
```
{"timestamp":"2022-03-25T17:42:51.540297Z","level":"INFO","message":"a \"simple\" message","internal_log_rate_secs":1,"vrl_position":0,"target":"vrl_stdlib::log","span":{"component_id":"log","component_kind":"transform","component_name":"log","component_type":"remap","name":"transform"},"spans":[{"component_id":"log","component_kind":"transform","component_name":"log","component_type":"remap","name":"transform"}]}
```
***
Related to the first point of this issue …

fix(vrl): Unwrap logged messages from quote marks

---

src/config/enterprise.rs

Closes [OP-354](https://datadoghq.atlassian.net/browse/OP-354)
This PR adds an `enable_logs_reporting` option to enable/disable enterprise log reporting (default `true`).
- Also a small refactoring to break out the enterprise component setups into their own functions

chore(enterprise): Add option to disable enterprise logs reporting

---

src/sinks/influxdb/logs.rs
src/sinks/util/encoding/adapter.rs

Part of #9459.
Technically, this doesn't use `Encoder`, but only the new simplified `Transformer`.

enhancement(influxdb sink, codecs): Integrate `encoding::Encoder` with `influxdb` sink

---

Cargo.lock

Probably caused by silent merge differences between dependabot PRs.

chore(deps): Check in uncommitted changes to Cargo.lock

---

Cargo.lock
src/config/enterprise.rs
src/config/mod.rs

Closes [OP-337](https://datadoghq.atlassian.net/browse/OP-337)
This PR adds the ability to configure custom tags in the `[enterprise]` section which are then added to the metrics and logs we use for enterprise telemetry.
Set up an environment variable in your shell: `export ENV_VAR_TAG_TEST="env var tag"`. Set up a new pipeline in Datadog. Insert the resulting `[enterprise]` section into the following configuration
```toml
[api]
enabled = true
[enterprise]
api_key = "..."
application_key = "..."
configuration_key = "..."
[enterprise.tags]
some_tag = "tag"
some_env_var_tag = "${ENV_VAR_TAG_TEST}"
[sources.in]
type = "demo_logs"
format = "syslog"
[sinks.out]
inputs = ["*"]
```
Run the configuration: `target/debug/vector -c {path to config}`
In [Datadog Metrics …

enhancement(enterprise): Add dynamic tag configuration to enterprise section 

---

lib/datadog/grok/src/filters/keyvalue.rs
lib/datadog/grok/src/parse_grok.rs

closes https://github.com/vectordotdev/vector/issues/12402
This is technically a breaking change. Previously the key was parsed as if it was a VRL path, and if that failed it would fall back to treating it as a single segment. VRL path parsing should generally only be used on values that are provided by the user so
the nesting / character escaping can be provided. Since this key comes from the log content, we decided to treat is as just a single path segment. This also makes this change significantly smaller since it doesn't require switching to the new lookup parsing. There will likely be a small perf improvement once it is switched to the new lookup code, but I expect this will get us >95% of the improvement already.

chore(core): remove runtime lookup parsing for `keyvalue` filter in `parse_groks`

---

.github/workflows/test.yml
Cargo.toml

As stated in the title.
We should use our custom runners for the cross-linux and check job, as they compile Vector, and can benefit from more cores.
This also switches `test.yml` over to the native "cancel previous jobs" functionality of GHA in an effort to see if we can avoid using the workflow action, as it should be faster to avoid having to run it as a full-fledged step which requires a runner instance, and so on.
EDIT: Empirically, after pushing some further commits to this PR, the speed-up on the `Checks` and `Cross - *` jobs is about 3-4x, from 30-35 minutes down to 10 minutes or less.

chore(ci): use our custom runners for cross-linux + checks, and native action cancellation

---

src/sources/aws_s3/mod.rs
src/sources/aws_s3/sqs.rs

Closes #12498 
AWS escapes spaces in the filename with `+`, however the source was only percent decoding, assuming `%20` was the encoding for spaces.
This checks if there is a `+` in the name and replaces it with a space. We can be confident that all `+` will be representing spaces, since any actual `+` in the filename do get encoded to `%2b`.
Signed-off-by: Stephen Wakely <stephen.wakely@datadoghq.com>

fix(aws_s3 source): handle spaces in filenames

---

lib/value/src/value/target.rs
lib/vrl/core/src/target.rs

This PR removes a clone happening in `Value::target_remove`. I doubt it'll have a meaningful impact, but from an API perspective this implementation makes more sense, so it's good to get this merged regardless.

chore(vrl): remove `Value` clone in `Value::target_remove`

---

lib/vrl/compiler/src/expression/block.rs

This changes the implementation of the `block` expression to be more efficient. This has an impact on other expression types as well, as the `Block` type is used to store a list of expressions internal to other public expression types (such as if-statements, groups, etc).
The micro benches show an average improvement of ~20%. Given the simplicity of the change, it's worth a merge, but I'd be curious if any of this shows up in one of our soaks (although from perusing our soaks, I suspect we don't have any that have sufficiently complex VRL programs to show a big impact).

chore(vrl): improve performance of `block` expression

---

src/sinks/aws_sqs/config.rs
src/sinks/file/mod.rs
src/sinks/gcp/cloud_storage.rs
src/sinks/nats.rs
src/sinks/papertrail.rs
src/sinks/redis.rs

This is a followup to #12561 for the sinks that got based off an older branch.

enhancement(codecs, sinks): Extend sink input type to encoder input type

---

src/sinks/aws_kinesis_streams/config.rs
src/sinks/aws_sqs/request_builder.rs
src/sinks/file/mod.rs
src/sinks/gcp/cloud_storage.rs
src/sinks/nats.rs
src/sinks/papertrail.rs
src/sinks/redis.rs

This is some followup on the sinks that got based off a commit before 2c8749009e169f85957abcc94064aa40e4a7849b in https://github.com/vectordotdev/vector/pull/12561 landed.

chore: Remove unnecessary `clone`s of `encoding`

---

lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/expression/block.rs
lib/vrl/compiler/src/program.rs
lib/vrl/vrl/src/runtime.rs

This cleans up the code, and might have performance benefit as well, given that we no longer have to store a list of boxed trait objects, but store a concrete `Block` type, which itself stores a list of concrete `Expr` types.
Let's see if the soaks give it any credits, but if not, the code re-use is still worth the PR.

chore(vrl): change `Program` from `Vec<dyn Expression>` to `Block` expression

---

lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/trace.rs
lib/vector-core/src/event/vrl_target.rs

This PR changes the `Target` impl for `Event` to use the more efficient path lookup/removal/insertion logic that has existed in VRL's `Value` impl for a long time.
Now that the "value unification" work is done, I was able to switch over to those efficient implementations without much effort. This should get us another nice bump in performance.

chore(vrl): improve performance of `Target` impl for `Event`

---

src/test_util/components.rs
src/topology/builder.rs
src/topology/test/compliance.rs
src/topology/test/mod.rs

This PR is a follow-up to #12572 which checks transforms for their adherence to the component specification.
Admittedly, this one is sort of a gimme because the topology itself handles emitting these events for all transforms, and transforms only emit their relevant events -- events for dropping events if the transform can drop events, and so on -- so we're able to test a much smaller surface here while ensuring all transforms will "adhere" to the component specification.
This PR is based on the branch for #12572 which is not yet merged (yet) and so I'll point it to base off of master once that happens.

chore(observability): ensure transforms are checked for component spec compliance

---

soaks/tests/http_pipelines_blackhole/vector.toml
soaks/tests/http_pipelines_blackhole_acks/vector.toml

Per findings in #12267 the enriched mode of parsing user agents is very
expensive. It is not clear, however, if users will actually, in practice, make
use of enriched mode or if 'fast' is sufficient. As such, we've decided to focus
on 'fast' for the time being.

chore: Use 'fast' user-agent parsing by default

---

lib/vrl/stdlib/src/del.rs

This likely won't show up in the soaks, but micro-benchmarks show a ~5-10% performance gain.

chore(vrl): improve performance of `del` function

---

src/sources/kafka.rs

The inner message handling loop in the kafka source was over 100 lines long and hard to reason about. This breaks it down into more tractable components.

chore(kafka source): Simplify inner loop logic

---

src/providers/http.rs

Fixes #12579.
Small fix to continue the polling loop after encountering an error fetching the http config.

fix(config): Continue polling http config after error

---

lib/vrl/compiler/src/test_util.rs
lib/vrl/stdlib/src/compact.rs
lib/vrl/stdlib/src/encode_json.rs
lib/vrl/stdlib/src/parse_apache_log.rs
lib/vrl/stdlib/src/parse_aws_alb_log.rs
lib/vrl/stdlib/src/parse_aws_cloudwatch_log_subscription_message.rs
lib/vrl/stdlib/src/parse_aws_vpc_flow_log.rs
lib/vrl/stdlib/src/parse_common_log.rs
lib/vrl/stdlib/src/uuid_v4.rs
lib/vrl/vrl/src/prelude.rs

As discussed in #12695 one of the blockers to adjusting the `Value` type
systemtically is the difficult compiler output around our testing macros. This
commit removes one of those macros -- map! -- in favor of `BTreeMap::from` for
the most part.

chore: Remove map! macro

---

src/enrichment_tables/file.rs
src/sinks/util/encoding/mod.rs
src/sources/fluent/mod.rs
src/sources/host_metrics/cpu.rs
src/sources/host_metrics/network.rs
src/transforms/remove_tags.rs

Simliar to #12716 and with reference to #12695 this commit removes some
instances of the btreemap! macro in favor of `BTreeMap::from`. There are many
such instances of this macro and they're not easy to mechanically replace, so
this commit will be followed by others as time allows.

chore: Remove some instances of btreemap! macro

---

lib/file-source/src/file_server.rs
src/sources/aws_sqs/source.rs
src/sources/file.rs
src/sources/gcp_pubsub.rs
src/sources/journald.rs
src/sources/kafka.rs
src/sources/kubernetes_logs/util.rs
src/sources/splunk_hec/acknowledgements.rs
src/sources/util/finalizer.rs

The `FinalizerSet` is used by several sources to asynchronously process
acknowledgement responses. It is currently written to take a async closure
that is called when an batch is acknowledged, but this requires sharing
data into the closure, complicating program flow for some sources.
This change rewrites it to output a stream of acknowledged identifiers,
which is then either handled in the main loop in the source or in a 
separate task as needed. This rewrite also avoids the need for an
additional task in the finalizer framework moving that out into only
the sources that require background handling (as opposed to `select`
on the stream).

chore(sources): Convert the finalizer framework to output a stream

---

.github/workflows/test.yml

This makes two changes:
* Doesn't cancel workflow runs on `master`. I think we don't want to
cancel in-flight workflows on `maser` as it can make it more difficult
to see when breakages are introduced.
* Adds the workflow name to the concurrency group. Without this, Github
Actions will cancel all workflows in the group regardless of name.
This didn't manifest as an issue yet because we are only using
`concurrency` in one workflow so far.
Addresses comments on https://github.com/vectordotdev/vector/pull/12669 .

chore(ci): Correct concurrency options for test.yml

---

Cargo.lock
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/src/parse_user_agent.rs

I've found that the uaparser we use for "extended" parsing of user agents makes
a number of small allocations internally. I've got an experimental branch of
that project that prefers the use of `Cow` instead; this commit targets that
branch. I can measure a micro improvement in the benchmarks of uaparser but it's
unclear if this change will positively impact vector. Notably, even though
uaparser is returning a `Cow` this library then causes the small string to go
through an allocation, since our types are `String` on the VRL side.
Work here was incorporated upstream via https://github.com/davidarmstronglewis/uap-rs/pull/12. 
REF #12267

chore: Update uap-rs to 0.6.0 

---

lib/codecs/src/encoding/framing/character_delimited.rs
lib/codecs/src/encoding/mod.rs
src/sinks/aws_cloudwatch_logs/config.rs
src/sinks/aws_kinesis_firehose/config.rs
src/sinks/aws_kinesis_streams/config.rs
src/sinks/aws_s3/config.rs
src/sinks/aws_sqs/config.rs
src/sinks/azure_blob/config.rs
src/sinks/file/mod.rs
src/sinks/gcp/cloud_storage.rs
src/sinks/http.rs
src/sinks/kafka/config.rs
src/sinks/nats.rs
src/sinks/papertrail.rs
src/sinks/redis.rs
src/sinks/socket.rs
src/sinks/util/encoding/adapter.rs
website/cue/reference/components/sinks.cue
website/cue/reference/urls.cue

Closes #12473.
The error messages are improved in so far that sinks will reject unknown fields again and missing `framing` and `encoding` fields are mentioned explicitly.
Unfortunately, deserializing the `encoding` field itself will still give vague error messages due to https://github.com/serde-rs/serde/pull/1544 (some more details in #12162).
Additionally, this PR fixes a bug where the `framing` config could not be overridden when a legacy codec was used.

fix(codecs): Improve deserialization of `EncodingConfigAdapter` / fix overriding `framing`

---

Cargo.lock
lib/vrl/stdlib/Cargo.toml
lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/is_json.rs
lib/vrl/stdlib/src/lib.rs
website/cue/reference/remap/functions/is_json.cue

This PR adds a new function - `is_json`. 
It validates that a provided string is a valid JSON-formatted document.
It is better than checking the error from the `parse_json` method because `is_json` discards all deserialized data (see [serde](https://docs.serde.rs/serde/index.html)::[de](https://docs.serde.rs/serde/de/index.html)::[IgnoredAny](https://docs.serde.rs/serde/de/struct.IgnoredAny.html#)).
Benchmark results:
`is_json`
```
vrl_stdlib/functions/is_json/map                                                                            
time:   [65.001 ns 65.946 ns 66.930 ns]
thrpt:  [14.941 Melem/s 15.164 Melem/s 15.384 Melem/s]
vrl_stdlib/functions/is_json/invalid_map                                                                            
time:   [141.29 ns 143.05 ns 144.90 ns] …
```

feat(vrl): New function is_json

---

website/cue/reference/components/sources/syslog.cue

The structured data fields are namespaced under the name of each
structured data section.
Fixes: #12410

docs(syslog source): Correct documentation around structured data handling

---

.github/workflows/manual_soak.yml
.github/workflows/soak.yml

Looking at a recent soak run
(https://github.com/vectordotdev/vector/pull/12747#issuecomment-1128771074),
all but `http_to_http_acks`, are not detected as erratic, but are marked
as such.

chore: Remove non-erratic soaks, declared erratic

---

src/sources/kubernetes_logs/mod.rs

Abort reflectors on vector reload if a kubernetes_log source was deleted from the config.
I tested these changes manually and also executed the integration tests set. If anyone has an idea how to add an automatic test for this situation, it would be more than helpful (or we can just go without adding tests).
***
Closes #12472

fix(kubernetes_logs): abort reflectors on vector reload

---

Cargo.lock
Cargo.toml
src/sources/gcp_pubsub.rs

GCP occasionally issues a connection reset in the middle of the
streaming pull. This reset is not technically an error, so we want to
retry immediately instead of waiting for a timeout and slowing down the
streaming data.
Ref #12660

fix(gcp_pubsub source): Handle connection resets with fast retry

---

lib/vrl/stdlib/benches/benches.rs
lib/vrl/stdlib/src/is_json.rs
website/cue/reference/remap/functions/is_json.cue

This is an implementation of the idea from the linked issue. 
***
Close https://github.com/vectordotdev/vector/issues/12763

feat(vrl): add variant enum argument to the is_json function

---

website/cue/reference/remap/expressions/function_call.cue
website/cue/reference/remap/functions/for_each.cue
website/cue/reference/remap/functions/map_keys.cue
website/cue/reference/remap/functions/map_values.cue

This PR finalizes the initial version of VRL iteration support by adding docs for the initial three functions:
- `for_each`
- `map_keys`
- `map_values`
There's no special section on "iteration" yet, as I wasn't sure what to put there. Specifically, how iteration behaves depends on independent function implementations and there's no special iteration syntax (there _is_ special function-closure syntax, but I'm unsure how useful it is to document that, as it serves no purpose yet for non-iteration functions).
Curious to hear what others think.
closes #12317 🎉.

chore(vrl): add iteration docs

---

.github/workflows/soak.yml

Per a comment made by @JeanMertz, if the soak test is going to fail it's more
likely to fail on the comparison leg. He's right and this will save a bunch of
debug time.

chore: Run 'comparison' soak first

---

lib/k8s-e2e-tests/tests/vector-agent.rs
lib/k8s-test-framework/src/framework.rs
lib/k8s-test-framework/src/pod.rs
scripts/deploy-chart-test.sh
src/internal_events/kubernetes_logs.rs
src/sources/kubernetes_logs/mod.rs
src/sources/kubernetes_logs/node_metadata_annotator.rs
website/content/en/highlights/2022-05-03-0-22-0-upgrade-guide.md
website/cue/reference/components/sources/kubernetes_logs.cue

This PR adds a new feature. With these changes, the vector agent will annotate all entries from kuberenetes_logs sources with node labels.
**NOTE!**: Integrations tests do not work because access rights are required to list and watch node objects. When I faced this issue, I came up with an idea. What if we make nodes (and probably namespaces) annotators lazy-loaded? It will allow users to control each Vector pod's number of watch requests. Maybe this behavior is not explicit enough. I just wanted to share the idea.
***
Closes https://github.com/vectordotdev/vector/issues/7499

feat(kubenetes_logs): Annotate logs with node labels

---

lib/vrl/stdlib/src/log_util.rs
lib/vrl/stdlib/src/parse_nginx_log.rs

I placed the upstream capture group before the request because an example log line with host and referrer labels looks something like this:
```
2020/07/12 14:32:03 [error] 45625#45625: *10918 upstream sent too big header while reading response header from upstream, client: 139.xxx.yyy.zzz, server: www.nixcraft.com, request: “POST /app/mg/posts HTTP/2.0”, upstream: “fastcgi://unix:/run/php/php-fpm.sock:”, host: “www.nixcraft.com”, referrer: “https://www.nixcraft.com/mg/admin/index.app”
```
I also executed benchmarks but did not find any significant performance degradation.
***
Closes https://github.com/vectordotdev/vector/issues/12240

fix(vrl): parse_nginx_log upstream label

---

Cargo.toml
website/content/en/highlights/2022-05-03-0-22-0-upgrade-guide.md
website/content/en/highlights/2022-05-23-0-23-0-upgrade-guide.md

As @hhromic pointed out in https://github.com/vectordotdev/vector/pull/12635#issuecomment-1119659572, it doesn't make much sense for th Debian package to enable and start Vector before it's configured by the sysadmin.
My PR #12635 "defangs" the default configuration to not spout out random logs to the system journal, which helps a bit, but 
the sysadmin still needs to configure, then restart Vector for their system-specific configuration to take effect.
The `enable` and `start` configuration stanzas were gleaned from https://github.com/kornelski/cargo-deb/blob/51a59b377b88fa9b419a88a515be9077c098bc23/src/manifest.rs#L83-L101 .

fix(releasing): Don't enable & start service by default on Debian

---

lib/vector-buffers/src/lib.rs
lib/vector-common/src/byte_size_of.rs
lib/vector-core/src/event/mod.rs
src/sinks/loki/event.rs

In #12755, I incorrectly added a blanket implementation of `EventCount` for `Vec<T>`, but did not constrain `T` such that a construction such as `Vec<EventArray>` would receive the blanket implementation and, yet, return a potentially very incorrect value for event count: the length of the vector, rather than the sum of the event count of all elements.
This PR properly constrains the implementation and sums the event count of each element. Additionally, we've added blanket implementations for references to types implementing `EventCount`, as well as `ByteSizeOf`, to make things a little cleaner as well.
Fixes #12858.

chore(buffers): fix unconstrained generic parameter in `EventCount` impl

---

docs/specs/buffer.md
docs/specs/component.md
docs/specs/instrumentation.md
lib/vector-buffers/src/buffer_usage_data.rs
lib/vector-buffers/src/internal_events.rs

I'm working on a brief covering Vector's health and noticed we need tighter definitions around errors. Specifically, only emitting errors at the error level if they require user attention. This improves the signal to noise ratio for operators trying to understand the health of their Vector instances.

chore: Clarify error boundaries in instrumentation spec

---

clippy.toml
src/sinks/util/compressor.rs
src/sinks/util/encoding/codec.rs

We have had a few bugs related to the use of the base `Write::write`
method instead of `write_all`. This marks that function as disallowed
and carves out a small number of specific exceptions where we handle it
properly.

chore: Mark `Write::write` as disallowed

---

src/sources/util/grpc/mod.rs
src/sources/util/mod.rs
src/sources/vector/v2.rs

Since sources/vector is actually a grpc server, and there're maybe a lot of other sources based on the grpc(like opentelemetry), so it'd better to move those logic into sources/util/grpc to enhance its resuability.
New sources like opentelemetry, could just need to new its proto:Service, like:
```rust
let service = proto::Server::new(Service {
pipeline: cx.out,
acknowledgements,
})
.accept_gzip();
run_grpc_server(addr, tls_setting, service, shutdown).map_err(|x| error!("xxx"))
```

[refactor] move grpc server logic into sources/util

---

src/sources/journald.rs
tests/data/journalctl

The journald source used a fake internal journal type to pretend to run
the journal program, but this didn't actually test starting the journal,
shutting it down, etc. This change adds a simple `journalctl` fake
script that is run by the usual mechanisms. This both simplifies the
tests, improves our test coverage, and eliminates the need for the trait
complexity to cover both journal types.
There have been some issues around the external program handling. This should unblock being able to test that interaction.

chore(journald source): Use a journalctl test script to improve testing

---

src/transforms/aws_ec2_metadata.rs
website/cue/reference/components/transforms/aws_ec2_metadata.cue

A user was confused thinking Vector was completely locked up if the
IMDSv2 was unavailable, but really the default request timeout is just
very long for this situation (60s).
Here I allow the timeout to be configured and lower it to a default of
1 second, which seems much more reasonable for the metadata API which
typically responds in a few milliseconds.
Reference: #12916

enhancement(aws_ec2_metadata transform): Lower request timeout

---

src/config/enterprise.rs

This PR 
- Fixes a mistake in enterprise reporting wherein the `remap` transform attached to `internal_logs` was configured to override the `.vector` section of events. This accidentally removed `component_*` fields from spans.

fix(observability): Fix overriding Vector fields in enterprise logs

---

src/aws/mod.rs
src/sinks/aws_cloudwatch_logs/config.rs
src/sinks/aws_cloudwatch_logs/request.rs
src/sinks/aws_cloudwatch_logs/service.rs
website/cue/reference/components/sinks/aws_cloudwatch_logs.cue

Made it possible to pass in arbitrary request headers such that we can
set the "json/emf" header when the logs uploaded by this sink are
actually in the Amazon CloudWatch EMF format: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure
Closes #12760

enhancement(aws_cloudwatch_logs sink): add `json/emf` support

---

website/cue/reference/releases/0.22.0.cue

docs: typoes

---

Cargo.lock
Cargo.toml

Update Azure SKD to pick up this change: https://github.com/Azure/azure-sdk-for-rust/pull/775
Auth with azure managed identity wasn't working on VMs and Kubernetes.

enhancement(azure_blob sink): update azure sdk to pick up mi enhancement

---

scripts/environment/bootstrap-ubuntu-20.04.sh
soaks/Dockerfile.builder
tilt/Dockerfile

The mold project has steadily worked toward their goal of linking chromium in 1
second. We benefit from this work too.

chore: Update the mold linker to 1.2 from 1.1

---

.github/workflows/integration-test.yml
scripts/integration/Dockerfile
scripts/integration/docker-compose.aws.yml
scripts/integration/docker-compose.azure.yml
scripts/integration/docker-compose.clickhouse.yml
scripts/integration/docker-compose.datadog-agent.yml
scripts/integration/docker-compose.datadog-logs.yml
scripts/integration/docker-compose.datadog-metrics.yml
scripts/integration/docker-compose.datadog-traces.yml
scripts/integration/docker-compose.dnstap.yml
scripts/integration/docker-compose.docker-logs.yml
scripts/integration/docker-compose.elasticsearch.yml
scripts/integration/docker-compose.eventstoredb.yml
scripts/integration/docker-compose.fluent.yml
scripts/integration/docker-compose.gcp.yml
scripts/integration/docker-compose.humio.yml
scripts/integration/docker-compose.influxdb.yml
scripts/integration/docker-compose.kafka.yml
scripts/integration/docker-compose.logstash.yml
scripts/integration/docker-compose.loki.yml
scripts/integration/docker-compose.mongodb.yml
scripts/integration/docker-compose.nats.yml
scripts/integration/docker-compose.nginx.yml
scripts/integration/docker-compose.postgres.yml
scripts/integration/docker-compose.prometheus.yml
scripts/integration/docker-compose.pulsar.yml
scripts/integration/docker-compose.redis.yml
scripts/integration/docker-compose.shutdown.yml
scripts/integration/docker-compose.splunk.yml

This was causing issues as the integration tests run as `root` in Docker
and polluted the target directory of the host system so that subsequent
`cargo` operations on the host would fail due to file permissions.
I briefly went down the path of trying to continue to share the
directory and set the uid/gid appropriately but this turned out to be
non-trivial. I think having a separate volume shared by the integration
tests for `target/` seems sensible.
Also sped up the building of the integration container a bit by
installing the prebuilt `cargo nextest` binary rather than building it.

chore(tests): Avoid sharing target with host system for integration tests

---

website/cue/reference/components/sinks/datadog_metrics.cue

By marking it as uncommon. Also made the example `mynamespace` to make
it clearer that users should change it.

docs(datadog_metrics sink): Remove `default_namespace` from example

---

lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/compiler/src/expression/if_statement.rs
lib/vrl/compiler/src/state.rs
lib/vrl/compiler/src/type_def.rs
lib/vrl/stdlib/src/append.rs
lib/vrl/stdlib/src/merge.rs
lib/vrl/stdlib/src/push.rs
lib/vrl/tests/tests/expressions/if_statement/if_else_external_assignment.vrl
lib/vrl/tests/tests/expressions/if_statement/if_else_local_assignment.vrl
lib/vrl/tests/tests/expressions/if_statement/if_expression.vrl
lib/vrl/tests/tests/expressions/if_statement/if_external_assignment.vrl
lib/vrl/tests/tests/expressions/if_statement/if_local_assignment.vrl
lib/vrl/tests/tests/expressions/if_statement/if_new_external_assignment.vrl
lib/vrl/tests/tests/expressions/if_statement/if_null.vrl
lib/vrl/tests/tests/expressions/if_statement/if_resolves.vrl
lib/vrl/tests/tests/issues/12948_conditional_type_def_regression.vrl
website/content/en/highlights/2022-05-23-0-23-0-upgrade-guide.md

fixes: https://github.com/vectordotdev/vector/issues/11773
fixes: https://github.com/vectordotdev/vector/issues/12948
- This now correctly calculates the type definitions of locals and external values in if/else statements.
- The expression type of an if statement without an else clause now includes `null`. The actual value could already be null, but the type definition didn't include it.
Just if statement (original and block type are merged)
```
$ a = 5
5
$ if false {a = "string"}
null
$ a
5
$ type_def(a)
{ "bytes": true, "integer": true }
```
If/else statement (only the if/else types are merged)
```
$ a = 5
5
$ if false {a = "string"} else {a = {}}
{  }
$ type_def(a)
{ "bytes": true, "object": {  } }
```

fix(vrl): fix if statement type definitions

---

lib/vrl/compiler/src/compiler.rs
lib/vrl/compiler/src/expression.rs
lib/vrl/compiler/src/expression/assignment.rs
lib/vrl/compiler/src/expression/predicate.rs
lib/vrl/tests/tests/internal/fallible_op1.vrl
lib/vrl/tests/tests/internal/fallible_op2.vrl
lib/vrl/tests/tests/issues/6469_fallible_operations_marked_as_infallible.vrl
lib/vrl/tests/tests/rfcs/7204/remove-generic-fallible-error.vrl

This PR resolves the "[Remove Generic "Expression Can Result in Runtime Error" Diagnostic](https://github.com/vectordotdev/vector/blob/b530718e961b6d4a0a4ba9428fdcccb41a8a8e18/rfcs/2021-08-22-7204-vrl-error-diagnostic-improvements.md#remove-generic-expression-can-result-in-runtime-error-diagnostic)" section of RFC https://github.com/vectordotdev/vector/pull/8894.
There's a test that showcases the different diagnostic messages, such as:
```
error[E100]: unhandled error
┌─ :10:5
│
10 │ 5 + to_int(.foo)
│     ^^^^^^^^^^^^
│     │
│     expression can result in runtime error
│     handle the error case to ensure runtime success
│
= see documentation about error handling at https://errors.vrl.dev/#handling
= learn more about error code 100 at https://errors.vrl.dev/100
= see language …
```

enhancement(vrl): improve precision of fallible expression diagnostic

---

src/sources/socket/mod.rs
src/sources/util/unix_datagram.rs
src/sources/util/unix_stream.rs

`vector validate` was creating the unix socket because it constructs all
components (when `--no-environment` is not passed).
This was a regression from https://github.com/vectordotdev/vector/issues/12115
Ideally we'd do something more sophisticated here in the future, but the
pattern for this sort of failure is simply to `panic` to cause Vector to
shutdown (see the `bind` call).
Fixes: #13018

fix(socket source): Avoid creating unix sockets too early

---

Cargo.toml
src/config/enterprise.rs

Closes [OP-452](https://datadoghq.atlassian.net/browse/OP-452)
This PR
- Namespaces enterprise `internal_metrics` with `vector` and `host_metrics` with `vector.host`
- Preserves a `pipelines` namespace metric
Build this branch locally and create a new OP configuration in Datadog. The below examples use the following configuration
```toml
[api]
enabled = true
[enterprise]
...
[sources.foo_op_452]
type = "demo_logs"
format = "json"
[sources.stdin_op_452]
type = "stdin"
[transforms.remap_op_452]
type = "remap"
inputs = ["foo_op_452"]
source = '''
log("I'm an internal log")
'''
[sinks.bar_op_452]
inputs = ["*"]
```
Run your configuration `target/debug/vector -c {your config}`, and navigate to DD metrics explorer. You should see metrics like the following
- `vector` …

chore(observability): Namespace enterprise metrics with `vector`

---

website/cue/reference/components/sinks/humio.cue

The `#datacenter` key has to be quoted now due to changes in path syntax
handling per https://vector.dev/highlights/2022-03-22-0-21-0-upgrade-guide/#path-syntax-changes.
Closes: #13027

docs(provider: humio): Fix indexed_fields example

---

src/sources/aws_ecs_metrics/parser.rs

Closes: #13015
The values which were either reported as 'null' or fields were omitted entirely, were changed to be `Option<...>`
Note: I left the other fields as non-optional , but I could make the remaining fields in CpuUsage and MemoryExtStats if desired, for consistency.

fix(aws_ecs_metrics source): integration test failures due to 'null' type or missing fields

---

website/content/en/docs/reference/configuration/unit-tests.md

The aggregated histogram metrics work differently from the other kind. Had to dig into source to figure out if it was supported and how. Adding this to documentation should show that the framework supports it and how to use it.

docs(unit tests): Add example of an aggregated histogram metric

---

website/content/en/docs/reference/configuration/sinks/statsd.md
website/content/en/docs/reference/configuration/sources/statsd.md
website/cue/reference/components/sinks/statsd.cue

The statsd components deal with metrics, not logs.
The statsd sink was inheriting from socket and so was incorrectly
documenting support for configuration options like `encoding`.

docs(statsd sink, statsd source): A few docs fixes

---

src/sinks/new_relic/config.rs
src/sinks/new_relic/encoding.rs
src/sinks/new_relic/sink.rs

Related to https://github.com/vectordotdev/vector/issues/9459.
While we don't allow setting a codec (just as previously), we deprecate the usage of the former `EncodingConfigFixed` for the new `Transformer` here, for internal consistency and to make the intent clear.

chore(new_relic sink): Use `Transformer` in `new_relic` sink and remove `EncodingConfigFixed`

---

src/sinks/datadog/logs/config.rs
src/sinks/datadog/logs/sink.rs

Related to #9459.
While we don't allow setting a codec (just as previously), we deprecate the usage of the former `EncodingConfigFixed` for the new `Transformer` here, for internal consistency and to make the intent clear.
The `encoding::{only_fields, except_fields, timestamp_format}` fields are now exposed and configurable for users.

enhancement(datadog_logs sink): Use `Transformer` in `datadog_logs` sink and remove `EncodingConfigFixed`

---

website/layouts/releases/single.html

They weren't rendering as white in dark mode.

docs: Fix bullets on release changelog in darkmode

---

lib/codecs/src/decoding/format/bytes.rs
lib/codecs/src/decoding/format/json.rs
lib/codecs/src/decoding/format/syslog.rs
lib/vector-core/src/schema/definition.rs
lib/vector-core/src/schema/requirement.rs
src/sources/datadog/agent/mod.rs
src/sources/datadog/agent/tests.rs
src/topology/schema.rs
src/transforms/remap.rs

This removes the `optional` field from the schema definition. Instead of storing them separately, it now just appends a `null` to the `Kind` type.
`required_field` was renamed to `with_field`. The "required" naming was confusing since you could set a nullable type.
This is purely an internal code cleanup. There should be no behavior changes.

chore(vrl): remove separate optional field from schema

---

lib/vector-buffers/src/variants/disk_v2/common.rs
lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs
lib/vector-buffers/src/variants/disk_v2/tests/size_limits.rs
lib/vector-buffers/src/variants/disk_v2/writer.rs

In #13102, a user reported that they encountered an issue with trying to write too large of a record to their sink's disk buffer, which manifested as `EncodeError::BufferTooSmall`, emitted when we try to encode an `EventArray` and don't have enough space to do so.
When the disk buffer v2 implementation was initially written, we had only considered writing a single event per record, and so the current default limit of 8MB made sense. With the addition of supporting `EventArray`, this now makes far less sense as we can easily get 1000 events per array when using something like the `vector` source, which leaves a mere _8KB_ per event for the encoding budget.
It's not unreasonable to think that with encoding overhead, plus high-cardinality/rich metadata, that we could exceed this... or a user …

chore(buffers): max default max record size to align with default max data file size

---

scripts/integration/docker-compose.aws.yml
scripts/integration/docker-compose.azure.yml
scripts/integration/docker-compose.clickhouse.yml
scripts/integration/docker-compose.datadog-agent.yml
scripts/integration/docker-compose.datadog-logs.yml
scripts/integration/docker-compose.datadog-metrics.yml
scripts/integration/docker-compose.datadog-traces.yml
scripts/integration/docker-compose.dnstap.yml
scripts/integration/docker-compose.docker-logs.yml
scripts/integration/docker-compose.elasticsearch.yml
scripts/integration/docker-compose.eventstoredb.yml
scripts/integration/docker-compose.fluent.yml
scripts/integration/docker-compose.gcp.yml
scripts/integration/docker-compose.humio.yml
scripts/integration/docker-compose.influxdb.yml
scripts/integration/docker-compose.kafka.yml
scripts/integration/docker-compose.logstash.yml
scripts/integration/docker-compose.loki.yml
scripts/integration/docker-compose.mongodb.yml
scripts/integration/docker-compose.nats.yml
scripts/integration/docker-compose.nginx.yml
scripts/integration/docker-compose.postgres.yml
scripts/integration/docker-compose.prometheus.yml
scripts/integration/docker-compose.pulsar.yml
scripts/integration/docker-compose.redis.yml
scripts/integration/docker-compose.splunk.yml

This broke with the upgrade to `cargo nextest` 0.9.19 which wants you to
use an extra `--` to pass along extra flags to the test binary, but it
occurred to me that I don't think we need this flag. It's useful for
debugging, but otherwise we don't really need to see the integration
test output unless it fails, in which case it will output it.

chore(ci): Remove `--nocapture` from integration tests

---

lib/vector-common/src/finalization.rs
lib/vector-core/src/event/log_event.rs
lib/vector-core/src/event/metadata.rs
lib/vector-core/src/event/metric/mod.rs
lib/vector-core/src/event/mod.rs
lib/vector-core/src/event/trace.rs
src/sinks/datadog/events/tests.rs
src/sinks/splunk_hec/logs/integration_tests.rs
src/sinks/splunk_hec/metrics/integration_tests.rs
src/sources/aws_kinesis_firehose/handlers.rs
src/sources/gcp_pubsub.rs
src/sources/journald.rs
src/sources/splunk_hec/mod.rs
src/sources/util/message_decoding.rs
src/sources/util/tcp/mod.rs
src/test_util/mod.rs

The `BatchNotifier` type is used as a shared reference wrapped in `Arc`
_everywhere_ except in its implementation. This change simplifies the
type naming and import requirements for this type.
Note that this was first attempted as a type alias, but that requires
more code changes as we can't implement methods on `Arc<T>`.

chore(core): Make the base `BatchNotifier` type shared

---

lib/tracing-limit/src/lib.rs

In `tracing-limit`, a lot of work is done before the point of figuring out whether or not the event in question should be limited. This includes cloning the event message itself.
We've cleaned up the logic and deferred visiting (and cloning) the event message until it's absolutely required. We've additionally dropped trying to read the `vrl_line_number` field, as that field is no longer used at all, being superseded by `vrl_position`.
This change won't have much of an effect for non-rate-limited events, but ironically will speed up components that are being heavily rate limited, allowing them to... fail at processing even faster. 😂 But seriously, it avoids a lot of pointless allocations that will inevitably get dropped since the event message is only needed when starting to track a …

chore(core): avoid cloning event message in `tracing-limit` when rate limited

---

scripts/cross/x86_64-unknown-linux-gnu.dockerfile

A [recent change](https://github.com/cross-rs/cross/pull/764) to the default x86_64 cross-rs image changed it to use ubuntu rather than rhel.
This means our image no longer has access to `yum`. This changes it to bootstrap an ubuntu image.

chore: update x86_64_unknown-linux-gnu to use ubuntu not rhel

---

website/content/en/guides/advanced/parsing-csv-logs-with-lua.md

Markdown doesn't render in short tags using {{< >}} syntax.
Closes: #13160

docs: Fix links in Lua CSV parsing guide

---

Cargo.lock
Cargo.toml
lib/k8s-e2e-tests/Cargo.toml
lib/k8s-test-framework/Cargo.toml

chore(deps): bump kube to 0.73.1 and k8s-openapi to 0.15

---

Cargo.lock
Cargo.toml
lib/datadog/grok/Cargo.toml
lib/datadog/grok/src/grok_filter.rs
lib/vector-config-common/Cargo.toml
lib/vector-config-common/src/validation.rs
lib/vector-config-macros/Cargo.toml
lib/vector-config-macros/src/ast/container.rs
lib/vector-config-macros/src/ast/field.rs
lib/vector-config-macros/src/ast/variant.rs
src/api/schema/components/source.rs
src/config/loading/loader.rs
src/sinks/gcp/stackdriver_metrics.rs

This PR works to reduce some duplicate crate dependencies, and in turn, the need to compile them.
In no particular order:
- switch from `gouth` to `goauth` the `stackdriver_metrics` sink (`stackdriver_logs` already used `goauth`)
- remove `strum`/`strum_macros` as they provide little value over simple hand-rolled impls of common traits, at least where we happened to use them
- _remove_ the `default-features = false` for `syn` in `vector-config-common`, which was manifesting as an entirely distinct version of `syn` needing to be compiled
- switch to `darling@0.13` (down from `0.14`) for `vector-config-common` and friends, as this let us line up with other dependencies we have which use `0.13`
For both clean debug and release builds, this shaves a good 5-10s off the full build. With these …

chore(dev): drop unneeded dependencies and coalesce some others

---

Cargo.lock
lib/vector-config-macros/Cargo.toml
lib/vector-config-macros/src/lib.rs

Was generating warning:
> unknown attribute `norun`. Did you mean `no_run`?

chore: Fix no_run doc comment fences

---

lib/vector-buffers/src/buffer_usage_data.rs
lib/vector-buffers/src/internal_events.rs
lib/vector-buffers/src/topology/builder.rs
lib/vector-buffers/src/topology/channel/receiver.rs
lib/vector-buffers/src/topology/channel/sender.rs
lib/vector-buffers/src/topology/channel/tests.rs
lib/vector-buffers/src/topology/test_util.rs
lib/vector-buffers/src/variants/disk_v1/tests/mod.rs
lib/vector-buffers/src/variants/disk_v2/ledger.rs
lib/vector-buffers/src/variants/disk_v2/reader.rs
lib/vector-buffers/src/variants/disk_v2/tests/acknowledgements.rs
lib/vector-buffers/src/variants/disk_v2/tests/mod.rs
lib/vector-buffers/src/variants/disk_v2/tests/model/mod.rs
lib/vector-buffers/src/variants/disk_v2/v1_migration.rs

In #13178, we outlined a situation where a user discovered that restarting Vector, after crashing due to the `disk_v2` buffer hitting an "out of space" I/O error on the write path, they received a` PartialWrite` error on the _read_ path, which also got raised as a panic.
In almost all cases, errors on the read path are recoverable, or at least can be moved past: if we fail to deserialize a record, or we detect a partial write, we still know how to set ourselves to try and read the next valid record, or continue trying if we hit further such errors.
The `disk_v2` reader already had a notion of an error that was recoverable, but it never encoded that in any way except through doc comments.
This PR exposes a way to convert a `ReaderError` into an event that can be emitted -- which allows us …

bug(buffers): avoid panicking on recoverable disk_v2 reader errors

---

src/sources/datadog/agent/metrics.rs
src/sources/datadog/agent/tests.rs

Closes #12953.
- Added a helper function to extract the namespace from the input metric name from Datadog.
Tested by running the Datadog Agent locally and stdout as a sink:
/// before
```
{"name":"datadog.agent.started","tags":{"host":"i-0eacf44f2df5844ff","version":"7.36.1"},"timestamp":"2022-06-15T19:23:40Z","kind":"incremental","counter":{"value":1.0}
{"name":"system.disk.in_use","tags":{"device":"/dev/loop1","device_name":"loop1","host":"i-0eacf44f2df5844ff","source_type_name":"System"},"timestamp":"2022-06-15T19:23:57Z","kind":"absolute","gauge":{"value":1.0}}
{"name":"system.disk.free","tags":{"device":"/dev/loop3","device_name":"loop3","host":"i-0eacf44f2df5844ff","source_type_name":"System"},"timestamp":"2022-06-15T19:23:57Z","kind":"absolute","gauge":{"value":0.0}}
```
/// after …

feat(datadog_agent source): Parse namespace out of incoming events

---

lib/vrl/stdlib/src/parse_aws_cloudwatch_log_subscription_message.rs

closes https://github.com/vectordotdev/vector/issues/13186
We don't have a great way to test this right now, so I created https://github.com/vectordotdev/vector/issues/13188 as a more general testing strategy for this.

fix(vrl): fix type def for the `parse_aws_cloudwatch_log_subscription_message` function

---

scripts/environment/bootstrap-ubuntu-20.04.sh

It makes the component feature check pretty chatty.

chore(ci): Remove xtrace from rustc wrapper

---

distribution/install.sh

I think it's unwise to tell a system to look for everything in
~/.vector/bin before it looks in /usr/bin, /usr/local/bin, etc...
When I run `ssh`, I never expect or want to execute `~/.vector/bin/ssh`
however this install script put that bindir at the front of my $PATH.
It's only used so the `vector` binary can be located so there's no
reason it needs to be any earlier than the last entry on $PATH.
Dan Benjamin wrote a nice backgrounder called [Using
/usr/local](https://web.archive.org/web/20060321165501/http://hivelogic.com/articles/2005/11/29/using_usr_local) back in 2005.

enhancement: Append (rather than prepend) bin dir to $PATH

---

lib/vector-buffers/src/buffer_usage_data.rs
lib/vector-buffers/src/internal_events.rs

In #13180, we changed some code related to buffer usage metrics, in order to bring them more in line with the Buffer specification. As part of this, we started emitting an event (instead of only updating metrics) for `BufferEventsDropped`. This event is intended to be emitted when buffers drop events, as the name implies. However, the code that handles reporting buffer usage metrics emits them on an interval.... including even if the count is zero.
This PR reworks some of the code in the buffer usage logic to reduce duplication/boilerplate, but also to more easily allow for writing code that only emits an event if values changed. In turn, we also now only emit the `BufferEventsDropped` event when events were actually dropped.
I created a simple configuration that uses disk buffers, and …

chore(buffers): don't emit `BufferEventsDropped` event unless count is non-zero
